== Memoirs The Life And Religious Labors Thomas Scattergood, A Minister of the Gospel In the Society of Friends.

+++[+++The memoranda from which the following account of our beloved friend,
Thomas Scattergood, is chiefly drawn,
appear to have been penned for the information of his
family and his own instruction and improvement,
without any view to their being made public.
They enter more into private and personal details than
would be proper to meet the public eye,
and often with a degree of minuteness which would be tedious to the general reader.
It was therefore necessary to omit much of this description of matter;
to correct some grammatical inaccuracies and sometimes
to transpose a sentence for the sake of perspicuity.

The reader will perceive that our dear friend was one of those who knew what it was
to be "`in deaths often`" to be brought very low after seasons of divine favour,
and often to partake, according to his measure,
of that bitter cup which was drunk in its fulness by his Lord and Saviour.
But these seasons of conflict and suffering,
painful as they might be at the time were blessed to him, as a means of preservation,
and of preparing him,
not only to minister more effectually to the suffering and oppressed seed of God;
but also to partake more largely of those consolations which are in Christ,
when He in whose hand are the times and seasons, saw fit to change the dispensation,
and permit him to partake with his blessed Lord
in his resurrection into dominion and glory.
Few persons, it is believed,
were preserved more steadily in a state of inward exercise and retirement of spirit,
waiting on the Lord, or given to see more clearly, or to minister more pertinently to,
the states of meetings and individuals,--and few have left behind them more
seals to the baptizing and convincing power of their gospel ministry.]

Thomas Scattergood, son of Joseph and Rebecca Scattergood, was born in Burlington,
New Jersey, on the 23rd of first month, 1748.
His parents were members of the religious Society of Friends,
and his father was indentured to Thomas Chalkley to learn the business of a mariner,
with whom he performed several voyages.
After coming of age,
he appears to have had the command of a vessel which sailed from Burlington;
but he soon left this occupation and studied law,
which he continued to practice until his death, which occurred in 1754.
After this event, the care of Thomas' education devolved upon his mother,
who manifested an earnest solicitude for his best welfare,
and by tender counsel and judicious management,
endeavoured to shield him from the snares and temptations incident to youth,
and to lead him in the paths of piety.
His literary instruction would seem not to have
exceeded the common branches of an English education,
of which he acquired a competent knowledge.

Of his boyhood, little is known, though from some hints he has left respecting it,
he seems to have been favoured, as early as when six years old,
with seasons of serious thoughtfulness;
but not giving heed to the secret reproofs of instruction,
or to the admonitions of his concerned mother,
he yielded to the corrupt inclinations of the vain mind,
indulging in folly and forming associations,
the tendency of which was to alienate him from a serious and self-denying life.
His turn of mind rendered his company peculiarly acceptable to his associates,
among whom he was generally a leader in their youthful diversions;
and although it does not appear that his conduct was marked by
any flagrant departure from the path of rectitude,
yet he became much estranged from the yoke and cross of Christ.

About the fourteenth year of his age,
he was placed apprentice in the city of Philadelphia,
with a Friend in mercantile business; but the occupation not suiting him,
he remained in it but a short time.
He afterward went to learn the trade of a hatter,
and continued at it until about nineteen years old, when his master dying,
he quit the employment and learned to be a tanner,
in which business he continued during the remainder of his life.
The temptations to which he was exposed in the city,
and the facility there afforded for gratifying the inclinations of the carnal mind,
led him still further from the way of holiness;
but amid all his deviations he appears to have been watched over and cared
for by that compassionate Being who is a father to the fatherless,
and whose gracious visitations were at times powerfully extended,
in order to rescue him from the pit of pollution,
and make him a chosen vessel in his house.

He was sometimes in the practice of spending first-day afternoon with his
companions in sailing on the Delaware--an amusement in which he took much delight;
and on one occasion when employed in this manner,
his mind became so deeply impressed with the sinfulness of thus spending the day,
that he induced his comrades to set him ashore before they reached the place of
their destination,--nor did he ever afterward spend that day in a similar manner.
He was often heard to speak of this incident,
as a remarkable instance of the secret pleadings of the
divine witness in the breasts of even the young,
and there is reason to believe that soon after it,
he was made willing to bow to the tendering
visitations of divine love and mercy to his soul,
and taking up his daily cross, to follow Jesus in the regeneration.

It would be interesting and instructive to trace his progress in a religious life,
through its early stages,
and to mark the exercises and baptisms by which he was gradually prepared
for an instrument of remarkable usefulness in the church of Christ;
but he has left no record of this important period of his life,
nor are there materials to make up even an outline of it.
From some remarks which he made at different times,
there is ground to conclude that his inward conflicts and provings were many,
and that he was then no stranger to that deep and weighty exercise of spirit,
which so remarkably characterized the later periods of his life.

It appears from the records of the monthly meeting of which he was a member,
that soon after attaining to manhood,
he was brought into usefulness in the concerns of the church,
and employed in some important services for the Society.

In the tenth month, 1772, he was married to Elizabeth, the daughter of David Bacon,
who proved a helpmeet to him; but they were separated by death in about eight years,
which proved a close trial to him.
One son, Joseph Scattergood, was the only child who survived her.

During the commotions attendant on the war of the revolution,
the Society of Friends in Philadelphia were subjected to much suffering and many trials,
owing to their conscientious objection to everything of a warlike nature,
which exposed them to much jealousy and suspicion,
and often rendered them the subjects of unrighteous and oppressive exactions.
These difficulties, growing out of various causes,
brought Friends very near to each other in spirit, broke down the barriers of prejudice,
and produced that humility and tenderness of spirit,
in which they could feelingly sympathize with one another,
and were ready cheerfully to contribute of their substance for
the help of those more destitute and stripped than themselves.
Committees were appointed in the monthly meetings to
inquire into the situation of their members,
and afford the requisite relief wherever it was needed.
In this work of love and mercy, Thomas Scattergood was a diligent labourer,
and he was no less zealous in encouraging his fellow professors to maintain
faithfully their testimony to the peaceable reign of the Messiah,
and in endeavouring to convince others of the inconsistency of
all wars and fightings with the benign nature of the gospel,
which ever breathes peace on earth and good will to men.

In the tenth month, 1778, with the consent of his monthly meeting,
he accompanied a ministering Friend to some meetings in Maryland and Virginia;
in which service he was engaged about six weeks.

With the approbation of his friends, and to use his own words,
"`in a degree of tenderness of heart,`" he set out with Samuel Emlen
and George Dillwyn to attend the quarterly meeting of Fairfax,
in Virginia, in the twelfth month, 1779.
The account of this journey is the first which he appears to have kept,
but as it is little more than a notice of the different stages where they stopped,
it seems unnecessary to transcribe it here.
Throughout the visit he seems to have been under
close exercise respecting his own condition,
which induced him often to seek solitary places
where he might commune with his own heart,
and pour out his prayers and tears before the Lord.
In a memorandum made the 18th of twelfth month, he says,
"`Attended the committee on Reformation,^
footnote:[The sufferings of Friends during the Revolution,
not only tended to increase their love for each other,
but also led into close self-examination,
in order to ascertain wherein they had departed from the law and the testimony;
and in their conduct, pursuits, or manner of living,
had lowered the standard of purity which the gospel and our high profession enjoin.
In order more effectually to carry on this good work,
committees were appointed in many of the quarterly
meetings to promote a reformation among Friends,
and endeavour to encourage one another to greater faithfulness
in the support of the precious testimonies of Truth.
It is probably to a committee of this description, that Thomas Scattergood here alludes.]
in the afternoon.
Here I was bowed under a sense of my past disobedience
and lack of entire resignation to the divine will.`"

"`21st.--Attended the youths' meeting.
My beloved friends were favoured in this and the preceding meeting; but as for me,
I was reduced very low; yet am a little comforted under the tendering power of truth;
our esteemed friend W. M.,
speaking a little to my condition in a sitting we had at Abel Janney's.

"`First month 9th, 1780.--Being first-day,
attended Fairfax meeting under much distress of mind, and so continued until evening,
when a little ease was graciously granted me, for which I am thankful.
On taking the Bible and reading our dear Lord's sermon on the mount,
a serious thought took hold of my mind,
respecting doing to others as I would be done unto.
The remembrance of several men, to whom I paid money in days back, came before me,
with desires that I might fulfil the law of Christ,
in doing unto all men as I should desire them to do to me.`"

This uneasiness appears to have arisen from his having used
the "`Continental money`" in the payment of some of his debts;
and although it was a full settlement and discharge according to law,
yet he was fearful that he should not be acting in
accordance with the gospel rule of strict justice,
unless he made them some compensation for the loss they
probably sustained by its great depreciation.
He therefore records his desire that "`for the sake of peace of mind,`" a
certain sum might be paid to individuals whom he names,
in order to make up the deficiency.

Where unreserved obedience is yielded to the
manifestations of the light of Christ Jesus in the soul,
it brings under a deep and humbling sense of past transgressions;
begets a godly sorrow for sin, bringing into view those long since committed,
and perhaps forgotten; under the pressure of which,
the awakened mind is bowed in great humiliation and
made willing not only to confess its wrong doing,
but as far as may be in its power, to make restitution also.
An instance of the tenderness of conscience and nice sense of
justice which is thus produced in the disciple of Christ,
is related of Thomas Scattergood.
When a school boy at Burlington,
he had occasionally taken some apples from an orchard which
lay on the side of the road leading to the school-house;
and when in after life he came to see the exceeding sinfulness of sin,
this circumstance became a burden to his tender conscience.
He therefore requested a friend to endeavour to ascertain who
was the owner of the orchard at the time he took the apples,
remarking that he should feel most easy to remunerate
him for the fruit he had taken without permission.

On the 25th of first month, 1780, he returned from the visit to Fairfax quarter,
and soon after was appointed an overseer of the
monthly meeting of Friends of Philadelphia,
for the Northern district.
In the tenth month, his affectionate and beloved wife was removed by death,
a loss which he deeply felt, she being a woman of a tender and sympathizing spirit,
well qualified to feel with him under his various exercises and trials.
In the following year he joined David Brooks and Seth Coffin, of North Carolina,
in a religious visit to some parts of Pennsylvania, New York and New England,
and while engaged in this service, he first appeared in the ministry.

The following extract of a letter written to Henry Drinker,
a beloved and honoured Friend and elder of Philadelphia, conveys in his own language,
his exercises on the occasion.
It is dated at Moses Brown's, Providence, R. I., fourth month 2nd, 1781.
After giving some account of the meetings they had been at, he says:

Thomas Scattergood to Henry Drinker

"`And now, dear friend, seeing you have used brotherly freedom with me,
I feel something of the same, to inform you of my state of mind.
I have been long in a wilderness travel,
or rather partly in Egypt and partly in the wilderness, if I may so term it;
and a persuasion for years past has possessed my mind,
that a dispensation of the gospel would be committed to my charge, but how, when,
or where, was hidden from me.
Sometimes I expected the time was nearly come,
having had my mind impressed with words in meeting, but not with sufficient clearness;
and at other times,
through unfaithfulness and not being enough willing to abide the fire,
I have almost lost sight of it.
In some of these seasons I believe I could have borne a
separation from having anything to do in Society affairs,
being so sensible of my wretched and unworthy condition;
and when I had thought of accompanying these Friends a little on their journey,
my mind was turned toward the baptized condition I was in,
when with Samuel Emlen in Virginia, which was a time of great distress,
and I was fearful of being burdensome if I went with them.
In this state of mind I left you and got pretty
cheerful by the time we reached North Wales,
in which meeting a few words came up in my mind by way of encouragement to some there,
which I have since thought I might have dropped peacefully to myself.
In the meeting for business I said something in some zeal;
which I fear needed to be tempered with more charity.

"`I had thought of endeavouring to see Friends at Hardwich, some time before I left home,
and it being a favourable time,
I proceeded to our friend Robert Kirkbride's. In the evening my beloved
friend David Brooks was uncommonly free in conversation with me,
in an encouraging way; opening his experience to me,
though I did not inform him of my exercise; and next day on our way to Plumstead meeting,
our ancient Friend, J. Forman rode up alongside of me,
and told me whatever my hands found to do,
to do it with all my might and not to fear the presence of any who were there.
My mind was exercised again in this meeting, with a few words to deliver:
I was burdened with a profession that lacked the possession of godliness,
and the different states of the publican and pharisee opening in my view to deliver;
I sat some time, fearing I was under a delusion,
I endeavoured to settle down into stillness, and as I was favoured to get there,
I apprehended I heard this language, 'Be faithful; there shall be peace in it.'
So I gave up, and stammered out what had impressed my mind;
but when I got down on my seat, confusion surrounded me; but by settling down to my gift,
the peace that was promised I experienced;
and being afterwards told by my dear companions that it was well, I rested easy.
Thus I first opened my mouth at a place, where some years ago,
I behaved in such a manner as was a reproach; it being at the marriage of a near friend.

"`We attended Kingwood meeting, at which place I was silent.
Next day set off for Hardwich,
proposing to stop to see a few scattered Friends
that live about half way between the two places.
We had a lonesome ride this morning,
wherein little conversation passed and my mind was exercised to know my way,
whether to return home to my family after being at Hardwich,
join as a companion to our friend J. Forman,
if he inclined to visit any more meetings in the Jerseys,
or proceed on with David and Seth to Nantucket;
and as I was measurably favoured with resignation of mind,
I believed it was best for me to join the two last mentioned Friends in their visit.
We stopped at Aaron Watson's,
and I had not sat long in the house before David came and sat down by me;
and on telling him I had thought of keeping on with him to Nantucket,
he freely told me he could think of little else in our lonesome ride, but my going,
and believed truth would make way for itself.
My mind was bowed in awfulness,
and as I apprehended I felt something of the spirit of prayer and supplication,
I endeavoured to keep under it until we sat down to eat,
at which time I ventured to prostrate myself before Him who had been
graciously pleased to open a spring of consolation in a desert land;
and dear David told me afterwards, it had a tendency to open the same spring in him,
as he began after I concluded;
and we had a solemn time together in this wilderness place,
where we were altogether strangers except our guide.
This season of divine favour, dear Henry, has been a time for me to look back at since,
when I have been ready to question all.
Thus I have simply laid my state before you,
as one who is authorized by his station to care for me; and being absent,
I apprehend I can do it more freely than if I were present.`"

In the course of the journey, which occupied several months,
he passed through much exercise of spirit and was often brought very low,
yet it proved a satisfactory and instructive season;
and in alluding to it several years after, he says: "`It was the Lord's doings I believe,
to send me with this experienced brother, +++[+++David Brooks,]
and marvellous was his supporting hand throughout the
journey;--I hope never to be forgotten by me,
for he brought my wading soul out of great tribulation,
and to the praise of his holy name be it uttered,
he opened the way for me not only in the minds of elders and brethren at home,
but also abroad.`"

After returning home, he continued to appear at times in the ministry,
which was satisfactory to his friends,
who felt unity and sympathy with him in this weighty work.
The following memorandums show that he endured
many fiery baptisms and close conflicts of mind,
which tended to deepen him in the root of divine life,
and prepare him for more extensive usefulness in
the solemn service whereunto he was called.
Being brought into a state of humble dependence upon
the openings and leadings of the Holy Spirit,
and reverent waiting upon Christ Jesus, the Minister of ministers,
he was made of quick understanding in the fear of the Lord,
and careful to wait for the fresh extending of
heavenly help before he engaged in testimony;
and thus keeping, in simplicity and singleness of heart, to the gift bestowed upon him,
he was often enabled, as a good steward of the manifold grace of God,
to bring forth out of the treasury things new and old,
to the edification and comfort of his hearers.
He was acknowledged by his monthly meeting as a minister, in the first month, 1783.

Under date of twelfth month 17th, 1782, he writes:
"`I feel like a poor creature--after a time of favour,
stripping and trial come--so I have experienced.
It has of late been a time comparable to a sabbath day.

"`19th.--O how near is my lurking enemy to draw into a love to the creature.
I was favoured today with a few expressions to
drop for the encouragement of such as myself,
who are much in debt and have naught to pay with.

"`21st.--On looking back at this past week, I find the hand of mercy has been near,
but truly I have nothing to boast of.
It is admirable to me,
that such a one as I should be so bold as to venture to instruct others,
while I get along so heavily myself.
Lord animate me to press forward.

"`30th.--A day of sorrow;
yet this evening I feel a broken heart and am baptized into tears.
For such a one as I, this is a great favour, worthy of recording.
O Lord, my God, you have not forsaken me, though I have strayed far from you.
Renew your promises as in former years.
I am unworthy to ask your blessing, yet I desire to wait for it.

"`First month 5th, 1783.--Some brokenness and contrition experienced today,
and a desire raised to be more circumspect this week, if life is spared.

"`10th.--O what pain a small deviation from the strict law causes to a quickened,
feeling mind.
Lord help me to know and keep your law more and more.

"`11th.--How apt is one deviation, though it may seem as only from a tittle of the law,
to beget another.
When an old beloved lust, in some degree mortified, puts up its head,
what is then to be done but to know it bruised.
O when shall I know my beloved lusts so put down, as not to be able to rise.
Lord enable me to bear the rod and allow it to do its office,
that peace may again spring up through it.

"`12th.--A day of fasting and prayer, and I hope of true mortification.
I desire to see the death of some potent enemies, though it may be perfected by famine.

"`17th.--What would you have me to do Lord?
When wilt you be graciously pleased to favour with the
lifting up of the light of your heavenly countenance,
and destroy my enemies?
Be pleased to preserve me through the close exercises of my soul;
manifest your will clearly to your servant, and uphold me in it; enable me to bear,
and spare not.
O Lord, that I may experience your goodness as in the land of the living.

"`21st.--A little opened today at meeting, where I had something to deliver;
and also in a transient visit to a family.
I ventured to prostrate myself before God, and beg for protection and preservation.
How thankfully does the panting soul receive a little ease, refreshment and encouragement.

"`22nd.--A secret trust and hope lives in my heart:
how was David's life hunted in the wilderness, on the mountain, and amongst the rocks;
yet he was delivered.
O my soul, hope and trust in the same merciful deliverer.

"`23rd.--Favoured to encourage the mournful travellers.--Admirable that such a one as I,
should be thus led in public.

"`26th.--A day of more ease under the yoke,
and I feel desires kept alive and hope quickened, to press on,
endeavouring to eye my Captain and preserver.

"`27th.--It is pleasant to have a way cast up, and to be found walking therein.
To-day I have, in some degree witnessed that saying fulfilled,
'the effect of righteousness is peace.'

"`Second month 5th and 6th.--Not much to note,
only some ease of spirit to what I have of late experienced.
O that I may be kept attentive to Wisdom's voice, prepared at all times to say here am I.

"`10th.--Introduced to the meeting of ministers and elders.
Felt poor; little more about me than a desire to be what the Lord would have me to be;
however, am thankful that I was there.
O that I may be enabled more and more clearly to know and understand Wisdom's voice,
and to follow it even again and again into suffering.

"`11th.--What need of mercy and remission I feel this morning.
I hope that in due time my soul's desire will be answered, as Jabez's was.
O that you would bless me indeed, and enlarge my coast and keep me from evil,
that it may not grieve me.

"`13th.--Attended meeting, and near the close had something to say.
How am I tried with presentations of false visions, and at times narrow is my escape.
O that my gracious Master may preserve me from putting forth a hand to steal,
in the poverty that is necessary for me.

"`14th.--Felt my enemy gaining upon me, by lulling into ease.
Thanks be to the Lord, I feel more animated, and hope to resist him.
This is an old and sore evil;--slothful in business,
and not enough fervent in spirit serving God.
O for more animation in time to come, and forgiveness of past defects.

"`Second month 28th.--Spent this day alone in some quietness in my own habitation,
and find occasion of humbling.
O Lord, continue to enlighten and settle me; you know my buffetings and trials.

"`Third month 5th.--Spent some time with Sarah Harrison with unusual openness,
in comparing our getting along in a religious sense.

"`10th.--I am, indeed, a buffeted and sifted servant.
O Lord, forgive me the sins of my youth.
I have often and again slidden into folly,
and what have I to lean upon but your arm of mercy.
Be graciously pleased to open a way where there appears none;
preserve me from dishonouring you!
Continue to send a little help, and enlighten my darkness.
O my feebleness!
I hardly dared say I will trust in God, though I desire to do so.

"`11th.--Awoke this morning with a calm and easy mind,
when this encouraging language revived; 'I am the Lord that heals you,
and teaches you to profit, and leads you in the way you should go.'

"`16th.--A quiet silent day;
wherein an animating desire was felt to be more vigilant and more industrious.
Soul, watch that your resolution may be kept this ensuing week, if life is spared.

"`20th.--Thankful for favours received--found bodily exercise in labour profitable.
He that will be Jesus' disciple must deny himself, take up his cross and follow him.
What a favour to be instructed what this means, sell that you have;
what a lesson to learn.
I hope for more victory through faith, though I seem to make but a slow progress.

"`24th.--Felt my lurking subtle enemy very near, endeavouring to trip up my heels.
Oh! the mercy and kindness of my blessed helper, in assisting me to resist him,
so that I do not get so defiled and overpowered with weakness,
as has been my condition in days past.
May I still be enabled to maintain the warfare,
through him who has indeed showed me kindness--thanks be rendered to his name.

"`Fourth month 9th.--O wretched man that I am,
who shall deliver me from this body of death and sorrow of heart?
Is there not virtue in him who is called the Prince of Peace,
to dispense peace to such a poor cast down one?
O yes, there is, but I cannot command it.
Lord preserve me from taking flight in this winter season.
Preserve me in the faith, and be pleased to increase it;
make me worthy to receive redemption and mercy by your washing, preparing hand:
be pleased to blot out of your remembrance the sins of my youth;
my frequent backslidings and my neglect of your law.
O Lord, I am miserable without you! look down upon me.
I dare not seek pleasure away from you,--I believe you
can change my misery into comfort in a moment,
if you please.
I hope in your tender mercy, and though I am thus cast down,
I will endeavour to trust in you.

"`13th.--I feel a humble hope if the thread of my life is cut,
there is mercy reserved for me.
O may I be kept until the end without despairing.

"`14th.--Through mercy I feel my way more clearly cast up.
I have not walked enough with full dedication of heart,--and have
been too uneasy under the fiery law that must be submitted to,
for removing all my corruptions.
O Lord that you would animate, enlighten and keep me under it,
until its office is finished.

"`16th.--Hope I have felt something of the same healing virtue that went forth to him,
whose withered hand was healed upon stretching it out at the divine command.
Under the cross springs the crown of peace; but nothing is due to the creature:
neither is it of him that wills,
nor of him who runs,--although there is much required for the poor creature to do.

"`20th.--Concerned three times in public testimony:
at the lower meeting in the morning in a few words in testimony; after which,
dear Nicholas Wain, I thought, had a good time,
and was favoured to lift me up a little therein.
I was engaged afterward in supplication, to my comfort.
Attended Market street meeting in the afternoon,
where I was exercised in a close testimony to a libertine spirit:
believe the favoured meeting in the morning was some support to me in this.
Nicholas Wain had a precious time in the evening meeting,
after which I was concerned to endeavour to clinch the nail.
Nothing due to man.

"`21st.--With a reverent thankful mind, I may say, it is a holy day,
created anew by Him that has the times and seasons in his own power,
and wherein I am eased from that weight of oppression and sorrow which I have been under.
The Lord only be praised, and my poor soul be made willing to return to labour again,
when this graciously afforded sabbath is past.

"`Fifth month 1st.--O You that are all wisdom, strength and power, enable me so to walk,
as to experience an advancement to your praise.
What a favour to have the eye of the soul anointed to behold
the dear Son of God as our advocate in affliction.

"`12th.--I think my poor soul has been this day, as with Joseph in the prison house.
In the Lord's season he was delivered, and set above his enemies.
Trust in the Lord your God, O my soul;
though he may see fit to hide his comforts from you,--hope in his rich mercy still.`"

On the 15th of fifth month, 1783, he was married to Sarah Hoskins,
daughter of John Hoskins, of Burlington, New Jersey,
respecting which event he writes:--"`A day of covenant
in the Lord's fear with my dear and virtuous friend.
I was a little strengthened by the fresh revival of these expressions in my
mind;--'Be content with such things as you have:' and it was satisfactory to
hear dear George Dillwyn make use of the same for our encouragement.
G+++.+++ B. opened the public service with these expressions; 'Peace is sown for the righteous,
and joy and gladness for the upright in heart;' and afterward George
Dillwyn told us the same expressions soon struck his mind,
and out of the mouth of two or three witnesses every word was to be established.

"`20th.--Went to preparative meeting in a humble waiting frame,
and therein my Master was graciously pleased to hear my petition,
and cast up a way to walk in.
May I ever be preserved from stepping out of it.

"`Sixth month 1st.--A day of some enlargement;
spoke in testimony at our own meeting in the morning,
and also a few words in the early part of the evening meeting,
which seemed as a text for dear Nicholas Wain to enlarge much upon; who it is probable,
may not soon have the like opportunity amongst us in that meeting.^
footnote:[He was soon to embark for England,
on a religious visit to the churches in Great Britain and Ireland.]
It was encouraging, thus as it were,
to have a mantle thrown over me by an experienced elder brother.

"`3rd.--A parting meeting with Nicholas Wain--a low time with me in the fore part,
but dropped a few tears under that dear friend's
instructive testimony in the latter part of it;
and afterward took my leave of him.

"`10th.--Several changes today, yet trust I have not given place to the subtle serpent,
with whom my poor tried soul has such a controversy.
O that the protecting arm may still be near.

"`19th.--A dull heavy meeting today: it is a day of outward ease again;
and there is a great stir in this populous city in trading and business;
but where are the poor baptized mournful travellers to
be found?--I believe there is a remnant preserved.

"`22nd.--Apprehended it my duty to go to the middle meeting.
It was exercising to me to pass by my own, and be engaged in such mortifying labour;
but hope I complied with a good degree of cheerfulness.
O that I might be enabled to feel more content in my allotment,
seeing I dare not climb up another way.
I could rather desire my natural life might go for a sacrifice,
than live to dishonour my God, after appearing in so high a station.
Lord! preserve me--my desire is toward you; enable me to love and cleave to you,
that in due time I may come to experience your blessing.

"`Seventh month 2nd.--O my soul, endeavour to persevere in patience under your burden.
If the Lord delight in you, he can bring you unto what you pant after.
If faith and patience be graciously afforded, then let the fire burn.`"

In the year 1784, with the concurrence of his monthly meeting,
he paid a visit to the meetings composing the yearly meeting of New England.
He attended the yearly meeting at Newport, Rhode Island, on his way;
and learning that David Sands had obtained a
certificate to visit the meetings in New England,
he seemed to be impressed with a belief that it
would be right for them to travel together.
Under date of sixth month 3rd, he writes to his wife:

"`O may my dear Master, who has seen fit to allow near trials to beset me in days past,
and has measurably preserved me as I clave to him, still be with me and provide for me,
if it is his will that I should be longer from you.
I desire, in resignation and submission, to recommend you, with my own soul,
to his gracious care and protection.`"

After the yearly meeting closed,
it was some time before he could see which way it would be right for him to move;
as the following extract of a letter, dated sixth month 16th, indicates.

"`I humbly trust my being here has been in the will of the Lord;
having been measurably favoured with enlargement, both in meetings and in some families,
to my own comfort and the satisfaction of my friends; although I came poor amongst them,
and now the meeting is over, have to return to the same safe spot again,
I told Friends of the select meeting, near the conclusion,
that they might find by the care in wording my certificate,
how thoughtful my friends at home were about my right moving amongst them.
That I felt like one who had left his father's house,
and Friends of this meeting seemed like my friends at home,
on whom I desired to cast myself; not seeing it safe to return home,
and further service amongst them did not clearly open.
I find that thus simply casting my burden amongst them,
has gained me some near sympathizers.`"

After holding a conference with several Friends,
the prospect of joining David Sands in visiting the
meetings in the eastern part of the yearly meeting,
seemed to open with the most clearness;
and David Sands having intimated to him that his company would be truly acceptable,
they set off together.

In a letter to his wife dated at Boston, seventh month 20th, 1784,
he thus speaks of their progress.

"`We have been kindly received by our friends in this place,
whose families we have visited, and got through yesterday,
and in the evening went to see a family about six miles out of town,
where a few days past we had a meeting,
amongst a people that I do not learn ever had the like appointed amongst them before.

"`I have been pretty much exercised in my mind in this town.
But thanks be to my kind Master, I have had renewedly to rejoice this day,
in that he has enabled me to labour in my little services in this place,
to a degree of comfort and satisfaction,
so that my mind is measurably set at liberty and my health renewed.
We propose leaving this place in the morning to go on east, having had various meetings,
wherein considerable numbers of the gay inhabitants
have given their company and conducted very commendably;
and indeed I may say, we have been treated very respectfully by them.
The services of my dear brother, David Sands, have been extensive,
and I believe well accepted.
I trust we increase in uniting love, and I have humblingly to hope at seasons,
I shall be enabled to get through my services in these parts, and return in peace.

"`My heart is at seasons in company with you, in such a manner as to revive my hope,
that divine Goodness is will not fail to support you; and you have my prayers for you,
though my bodily presence is lacking.
Lift up your head in hope, and still stretch heavenward in the desire of your mind,
believing that it is easy with the Lord to turn our wilderness into a fruitful field,
after he has sufficiently tried us.
I have cause to speak well of his excellent name,
who is my sufficiency in all my exercises;
and no doubt it will be a comfort to you to know that I have been so far helped,
as not knowingly to omit any little service I have apprehended myself called to perform.
We have met with various friendly people here,
with whom we have had some baptizing seasons;
and I find as much engagement as ever to see the
people in the back parts of New England.`"

On the 21st, they set off in accordance with their prospect,
to visit the eastern settlements of Maine; in the performance of which service,
it being an unsettled and wilderness country, they found considerable difficulty;
having to swim their horses over rivers,
and to lodge in cabins and other poorly sheltered places;
notwithstanding which they were favoured with health and strength,
and reached Vassalborough on the 18th of the eighth month,
where the following memorandum was made.

"`Almost, or may be quite, at the far end of our journey in a wilderness land,
where my mind is pleasantly turned home this first-day morning,
to take a view of my dear family, feeling my heart a little comforted and strengthened,
after many trying seasons.
O may our dear Master be our comfort and strength; and if it be his will,
bring us together again and more and more unite us in best love.`"

In a letter dated at Boston, ninth month 6th, 1784, he thus describes this visit:
after speaking of a meeting held at Falmouth,
in which he had an open encouraging opportunity, he says:

"`It was like a time of healing,
after many proving seasons since I left this place before.
The close exercise I was under,
I expect you might easily discover from the contents of my letter,
written from here before going eastward;
wherein I mentioned that I believed it was required of me to stand
resigned to labour in these parts until the quarterly meeting.
I gave up with a good degree of cheerfulness to accompany my dear companion, David Sands,
and have been pretty nearly through that wilderness country.
I have passed through close trials of faith and love, in this journey;
and have also found my gracious Master to be near in them, who has from time to time,
as I was willing to be emptied, caused the heavenly oil to fill the empty vessel,
both to discharge the debt, and afford some to live on myself.
Blessed be his name for his mercy and care over me,
one of the least and most unworthy of his servants.
A monthly meeting coming on, I found my mind drawn to attend it,
as also the preparative meeting, held about twenty-five miles nearer.
We left Vassalborough, accompanied by various Friends who intended for those meetings,
and rode to a new settlement called Winthrop,
where we were taken in and kindly entertained by a friendly man;
had a sitting with him and family next morning,
when my mind was strongly engaged to be at their meeting of business;
and David found a full stop in his mind, and told us,
that with the friendly man's consent, he must stay and have a meeting at his house,
but was very free for me to go forward.
I did not see, when I parted with him,
but that I should return and join him again after monthly meeting;
though I understood by one of the Friends who came with me,
that he said he did not expect to meet me again.
We parted in that near love and affection in which we were favoured to travel together;
one of the Friends staying to accompany him, and two others came on with me.`"

He thus describes his subsequent engagement:

"`A dear friend who came from Kennebec with me, had it on his mind to bear me company,
and I believe was at that time dipped into my exercise, and has given up,
with Friends' approbation, to accompany me, though not without some cost,
and proves a valuable feeling yoke-mate.
I have ventured in my journeying this way,
to appoint meetings where David and I have not been;
and hope I was favoured to get through to a good degree of satisfaction,
both to Friends and myself; it was a new scene, and I have not been without trials in it.
I reached this town last seventh-day afternoon,
and was with much affection received by my kind friends, John and Rebecca Dean,
who seem desirous I should stay until their monthly meeting at Lynn comes on,
and rest myself.
I found a considerable draught to this town,
and sat with Friends yesterday in two meetings.
There seems to be considerable openness and love amongst them, and also other societies,
that is very encouraging and comforting.`"

The remaining memorandums of this visit are principally an
account of the different families with whom they put up.
On the 28th of the tenth month, 1784, he arrived at his own residence, as he says,
"`in peace.`"

In the fifth month, 1785,
he obtained the concurrence of his monthly meeting to pay a religious
visit to the yearly meeting of Friends on Long Island,
and the meetings composing the quarterly meetings of Oblong and Nine Partners.
After attending the yearly meeting,
he went to New York with a Friend who had
offered to accompany him to some of the meetings,
but the way seemed to close as to proceeding further.
In a letter to his wife, dated sixth month 10th, he thus describes his feelings:

"`My prospect was to go towards Oblong and Nine Partners,
and so continued until second-day afternoon.
We sat down with Henry Haddock, and some other Friends who came in;
and here I was plunged into such a condition as I have not often experienced.
The importance of the undertaking spread with solemn weight over my mind,
joined with a sense of weakness and incapacity without the interposition of divine help;
under which I was much broken into tears,
in humble resignation to follow my gracious Master,
who had been pleased to lead me thus far, measurably in his counsel and will.
I endeavoured, as well as I could, to inform my friends how it was with me,
and we concluded it would be safest to wait until morning.
Retiring to my room, I got vent,
for indeed my cup was made to overflow much in the same manner as when I left you,
only with this difference; that then I moved in the clearness and in sweet peace;
now there seemed a cloud in the way of going forward.

"`Next morning my mind was settled into sweet quiet,
with a release for the present from proceeding;
and concluded to let my beloved companion leave me and move homeward.
Since he has left, I remain easy to set my face homeward,
with a heart resigned to return and finish the visit when my
heavenly Master may be pleased clearly to open the way.`"

On the 11th he set off for home, and having two meetings by the way,
arrived there on the 13th.

On the 29th of the seventh month,
he again obtained the certificate of his monthly meeting to perform this visit,
and set off in company with his brother-in-law, "`feeling,`" as he remarks, "`very poor,
with many discouragements, but endeavouring to wear the sackcloth underneath.`"

On the 1st of the eighth month, they arrived at New York,
where he parted with his brother-in-law, and proceeded to James Mott's, at Mamaroneck.
On the 4th and 5th, he attended the quarterly meeting of Purchase;
"`at the conclusion of which,`" he says,
"`I was free that mention might be made of my
willingness to sit with Friends in several meetings.

"`On the 9th, to the meeting appointed at Mamaroneck.
Went poor and empty, and in the fore part was humbled under a sense of my unworthiness;
and while pondering thereon,
a language like this arose with a degree of strength to begin my testimony with.
'It is written, man shall not live by bread alone,
but by every word of God;' and with it I arose with tears;
and hope the meeting was to some profit.

"`10th.--My friend James Mott, having got himself in readiness to accompany me,
we sat out together this morning to the appointed meeting at Purchase,
which I hope was to satisfaction.
Lodged at Jacob Underbill's,
who told us he remembered when there were no
Friends further north than this neighbourhood.
My companion also informed me,
that in looking over the monthly meeting minutes of the year 1727,
he finds there was but one monthly meeting and three particular meetings on the main;
and now there are seven monthly meetings, two quarterly,
and twenty-five particular meetings on the main;
which shows the great increase of Friends in this government.

"`11th.--To the monthly meeting at Shappaqua, which was satisfactory.
Went home with John Griffin, of Amawalk; in going to whose house,
a distance of six miles, we had a mountainous road to travel,
and near it the river Croton to ford after night; through all which I felt pleasant.

"`On the 14th went to the meeting called the Valley,
and then proceeded to Daniel Merritt's. After ascending a rough narrow passage,
on a desolate mountain we passed over today,
there opened to view a small plantation with a dwelling house.
On riding up to the door to inquire our way,
a goodly woman came out with a bible in her hand, and gave us directions.
I engaged her in a little conversation, and found she was a member of Society.
I was made renewedly sensible, that He who formed the mountains and planted the hills,
whose presence is every where, could be worshipped here,
and my mind was favoured with content in my present allotment; blessed be His name,
whose work it is to bring into such a condition.
Even in a waste wilderness, far away from family and friends,
he can enable us to visit them in spirit,
and engage in humble prayer for our own and their preservation.
Thus I may thankfully acknowledge it has been with me today,
although much exercised and tried in setting out from my dear wife and family.

"`15th.--Went to monthly meeting,
and on the 17th attended the quarterly meeting
of ministers and elders held at Nine Partners,
and on the 18th and 19th, the quarterly meeting for business.

"`20th.--The usual time of holding the monthly meeting at the Creek, being yesterday,
it was adjourned until today.
We attended it, and it held from eleven o'clock until night,
A committee was appointed to visit the meetings of Hudson and Coeyman's Patent,
respecting settling two preparative meetings.

"`21st.--Went to a meeting about twelve miles further, called Little Nine Partners,
held in the barn of Obadiah Gifford.
This was an encouraging meeting to me,
and after it we took a little refreshment and proceeded, accompanied by several Friends,
who were going to the new city of Hudson, thirty miles.

"`22nd.--Was not easy to appoint a meeting in this place,
but concluded to let Friends appoint one tomorrow,
about sixteen miles further on the other side of the river,
and move on with the aforementioned committee.

"`23rd.--Crossed the North river opposite the town, and rode to meeting,
and after an open time with Friends and friendly people,
opened the business of the monthly meeting,
respecting their holding a preparative meeting;
and after a solid conference it was concluded they might hold one.
The first meeting in this place was held by a Friend on a religious visit,
five years ago, and I have a comfortable prospect there will be an increase.
The meeting was held in a log-house.

"`25th.--Attended their week-day meeting at Hudson, with the monthly meeting's committee,
and at the close mentioned to Friends a prospect which accompanied my mind,
to engage in visiting families, if they united therewith, which being approved,
some Friends were appointed to accompany me.
In the afternoon we visited four families.`"

On the 26th ten families were visited; and he says,
"`this has been an arduous laborious day's work,
under which I seemed at times near fainting,
but was favoured to go through to a good degree of satisfaction to myself,
feeling peaceful this evening.`"

On the 27th, after enumerating the families visited, he remarks;
"`another day of exercise and close labour.`"

"`28th.--First-day of the week.
Went to their meeting held at Hudson, which proved an exercising, searching time;
wherein an invitation was held forth to all ranks,
to come and join themselves to Christ Jesus, the free teacher of his people,
and to beware of false and hireling teachers.
In the afternoon finished visiting families.

"`29th and 30th.--Spent pretty much alone at our lodgings,
being much shut up as to any prospect of moving from this place with clearness;
find it safest to endeavour to stand still and wait to see what will turn up.`"

On the 3rd of the ensuing month, accompanied by several Friends, he went to New Britain;
on the 5th they were at Hoosack; on the 8th at the monthly meeting of East Hoosack,
and on the 10th at an appointed meeting at a settlement called White creek;
to which he says he "`went poor and distressed, and so remained for a time,
but Truth arose and a remnant was thankful we were together.`"

11th.--He says, "`we crossed a mountain, and arrived at our friend Stephen Rogers',
and after resting a little went to meeting,
in which my heart was more enlarged than at any time since I left my home;
there appearing something lovely amongst these mountain people.
Returned with Stephen Rogers, where we met with several friendly seeking people,
with whom we had a solid time.
I showed them my certificate;
and the care and order of Friends in such cases were satisfactory to them,
having never seen the like before.
This has been a day to be remembered with reverence and humility,
under a sense of divine favour and love.
I had a good time with the family and several of the neighbours.

"`Ninth month 12th.--Our kind friend provided us
fresh horses to go forward to monthly meeting.
From about half-past one to near six o'clock this day, we rode through a wilderness,
where we found but one path.
We were overtaken in this wilderness by a man, who from his appearance,
we judged to have been an under officer in the late war,
who was helpful in piloting us through to his house.
On the way I saw it to be my duty to show unto him the way of life and salvation,
and concluded I would leave it until we were likely to part, which would be time enough.
When we came up to his cottage in the wilderness, doubts and weakness so prevailed,
as to induce me to endeavour to pass him by; but on riding a few rods forward,
I found I must go back.
My dear companion, James Mott, told me afterwards, he was just going to say to me,
that if I had anything for that man, to be faithful and do it.
We turned back and went into the house,
where I found my mind concerned to declare the way of life to them.
Beside the man's wife, his aged father, who was deaf,
and his mother who was sick and in bed, were there, and also a brother and his wife,
and one or two young women.
I told them I had something to say to them if they would be silent and hear me.
The sick woman answered that they were not of my profession, and they knew enough.
I was grieved with her conduct, and told them I had freely offered,
and if they would not hear me, I should be clear;
and taking out the man who came with us, I opened my concern to him,
and also to some of the rest at the door, on parting.
I believe they were concerned at the old woman's behaviour,
and one of the young women appeared tender.
I was glad there was a little stir made among them,
although this act of duty might appear small.

"`13th.--To the meeting held at Daniel Hull's,
which was a good time amongst both Friends and others.
In the silent part I apprehended I felt the gospel of
Christ Jesus to flow over this wilderness land,
even to Canada; and after dinner had a baptizing time in a Friend's family,
wherein one of the children was spoken to particularly.

"`14th.--To meeting; a searching, but toward the close a good time,
and was glad I was there.
After meeting we had a baptizing time on parting from the family where we dined;
then rode to the river, three miles,
and crossed it in a boat which sunk in taking Friends over to last monthly meeting;
one of whom was drowned.

"`15th.--To Saratoga monthly meeting, and had a good time in the meeting for worship.
The meeting for discipline held until night.

"`16th.--After a tendering opportunity in the family where we lodged, set out for Hudson,
and attended the morning and afternoon meeting on the 18th.`"

On the 20th he visited David Sands, in whose family they had a solid opportunity.

"`On the 22nd reached James Mott's residence,
and went to the week-day meeting with the family,
and therein was employed in looking a little over my labours;
and although I feel poor and like an unprofitable servant,
nevertheless am favoured measurably with a reward of solid peace in looking back,
and feel easy to endeavour to be with my brethren at our yearly meeting.`"

Soon after this he went to New York, from which he proceeded homeward,
and arrived there on the 24th, as he says, in "`sweet peace.`"

In the eleventh month, 1786,
he made a religious visit to the quarterly meeting of Fairfax, in Virginia,
accompanied by his friend Charles Williams, a valued member of the same monthly meeting.
In relation to the quarterly meeting, he thus writes:
"`I have been favoured with an open door amongst
my friends during the time of the quarter,
and have occasion, with thankfulness of heart, to admire the goodness of the Lord,
who has a right to turn and overturn at his pleasure,
and who can change or alter the condition of men
as a man does the water course in the field.`"

He appears to have been detained in the neighbourhood of Fairfax,
visiting families and appointing meetings in this and some of the neighbouring villages,
in relation to which he says, under date of 18th of twelfth month:
"`My religious prospects are much closed up: have been working in a circle;
and am now at this place again, and see no way out.
Wait in patience, O my soul, for the further opening of duty,
seeing you have been enabled hitherto from place to place, to set up your Ebenezer.`"

Again, in a letter to his wife, under date of 19th of twelfth month:
"`In these parts I frequently have not seen my way but a few hours beforehand,
but as I am at times favoured to set up my Ebenezer, though led in a trying path,
I am encouraged to move on in the faith, and hope you have been and will continue to be,
favoured to partake of that precious reward which the Master gives his servants,
both those who go forth to battle and those that stay by the stuff.`"

Under date of 21st of twelfth month, he says: "`Went home with J. R.,
where we met with an open kind reception.
This man and wife, when I was here seven years ago with George Dillwyn and Samuel Emlen,
requested a religious opportunity in his family.
I am informed that in the beginning of our late troubles and war,
he was a captain of the militia, and led his men over the mountains against the Indians;
he is now a valuable member of Society,
and has offered to accompany me on my religious errand,
on the same rout over which years ago, he led forth his men to war.`"

On the 9th of the first month, 1787, he says:
"`A day of close exercise of mind yesterday,
because of so long confinement in this neighbourhood,
and no opening to any religious service.
I had a wakeful, thoughtful time last night.
Individuals in this neighbourhood are frequently brought into view,
but no clear prospect opens to visit them.

"`10th.--Attended the week-day meeting again at Fairfax, where, to my own humbling,
and I believe the comfort of others, we had a favoured time: the meeting is increasing;
it was small on our first coming here,
partly arising from an idle irreligious disposition,
and partly from the fear of getting the putrid sore throat, which has been prevalent.

"`11th.--We are yet detained in this neighbourhood; no way appears to move out,
and no clear prospect to proceed to a family visit.
Soul wait in patience, willingly disposed to do anything which may make for peace.

"`12th.--A pleasant scene opened the latter part of last night in my wakeful moments,
confirming me that I am in the way of my religious duty.
I had also an agreeable turn (mentally) into my own family and amongst my friends,
being enabled to put up a petition for them.`"
He visited a few families on this and the following day,
which were generally favoured opportunities,
and produced a feeling of peace and consolation to his mind.

On the 14th he again attended Fairfax meeting; in relation to it he says:
"`It was the largest we have been at here,
and I found much enlargement of heart to speak to various states;
there appears to be a precious visitation renewed to this people,
and I believe some are made truly sensible thereof.
I have found that my trials in this place have been for good,
and have seen the end of them,
even to baptize into a feeling sense of the state of this people.
What is revealed in secret in a time of mourning, in the night season as well as by day,
is afterward to be proclaimed as on the house-top.
I have found it good to wait and quietly hope for God's salvation;
for when the Messenger of the covenant appears at seasons, his work is before him;
for his work it is, and his precious reward he gives to his' humbly devoted servants.
Trust in him, O my soul.`"

From the 14th to the 22nd, he was engaged in family visits to Friends and others,
in many of which he was qualified to speak to the
states of individuals in a remarkable manner.
In relation to one of the opportunities, he says, under date of 22nd:
"`Felt my mind exercised with something to say to a particular state present with us;
and remarked, in conclusion, that I was willing to wait for days, under probation,
dipping into the states of others, to find the way open and ability afforded to speak,
if it were to but one individual.
Amongst the little company was one who appeared much reached and tendered.`"

Another instance is thus related: "`After we had dined,
came in a young man whom I wanted to see,
from some feelings which had accompanied my mind at times, though he was much a stranger.
Frequently when I heard his name mentioned,
I thought it was likely I must go to Leesburg almost on purpose to see him.
After he came in amongst us, although I felt poor,
being thoughtful of my own trying circumstances, a weight of exercise came over me,
and we had a tendering baptizing time;
and by the account Friends gave me afterward of what he had been,
the thoughts of his heart were plainly told him by a stranger,
who knew nothing by outward information.
Thus am I detained in this neighbourhood, in a stripped and tried condition,
but not for naught;
so may thanksgiving be rendered by my tried soul
for past preservation under such dispensations,
and a dedicated mind lived in for time to come.`"

On the 28th of the month, he again remarks respecting the meeting at Fairfax:
"`I was silently exercised for some time with
the consideration of Saul's assuming to offer,
at the desire of the people, without the presence of Samuel;
and willingly resigned to wait until right ability was given.
I had to stand up in weakness, not clearly seeing what to open my mouth with,
yet we were once more favoured together,
and I ventured to conclude the meeting in supplication.`"

After this meeting he was released from further labour in this neighbourhood,
and felt his mind drawn to Redstone.
He started on the 30th, accompanied by several kind friends.
In the families of Friends on the way, and also at the meetings he attended,
he appears to have been favoured in his ministry,
and some of the opportunities he describes as being "`tendering seasons to many.`"

At that time when the most fertile parts of our widely
extended country were but thinly inhabited,
and the roads through them but little attended to,
a journey across the mountainous district which separates the
western from the eastern portion of Virginia and Maryland,
must have been lonely, if not hazardous.

To one constituted as hp was, it must have been especially cheerless; he however,
appears to have been preserved in a resigned state of mind,
and favoured generally with a cheerful spirit.
On the 7th of the second month, at a tavern on the mountain,
they were much annoyed with some rude persons, who kept him awake much of the night:
"`As I lay,`" he observes, "`it was my concern to endeavour to get to my watch tower,
and examine how I had conducted since we crossed the Blue mountain,
being desirous to renew my acquaintance with the Lord my master,
who I believe had called me forth.`"

On the 10th of the second month he attended the monthly meeting held at Redstone,
and the next day, their first-day morning meeting,
in which he was silent and clothed with "`much peace of mind toward the latter part.`"

From a letter dated Redstone, second month 11th, 1787, the following extract is taken;

"`I got as far as this place on sixth-day evening last,
after a long and lonely ride over the Alleghany mountain.
I have been much favoured with health, and also,
to perform what I apprehended I was called unto, and some seasons of precious favour,
which have proved like seals of encouragement when under more trying circumstances,
have been mercifully afforded.
But for the most part, it has been my lot to travel along in a little and low state,
which I have believed to be a safe one.
I think I have also seen that those who come as far as this remote settlement,
had need to know their feet shod with the preparation of the gospel of peace.
I have experienced my faith to be tried,
and have had to look back and inquire what brought me here,
and have concluded it must have originated from best motives,
even love to the brethren--I remembered that
when under the chastening hand three years ago,
this place was opened before me, and I felt a willingness to set off then, if the Lord,
my heavenly master,
would be pleased to restore me to health of body and grant me peace and serenity of mind.
I trust at that time the will was taken for the deed;
and after a season He was graciously pleased to grant my
request and open the way for me to go to New England.
The visit I am now engaged in,
appears to me like endeavouring to fulfil my part of the
covenant entered into in a season of sore affliction,
and like performing my vows.

"`I think my lot may be a little compared (if so unworthy a
servant may so speak) to that of the prophet Ezekiel,
when he digged through the wall.
I do not find that it is expedient, at every meeting,
to open what it may be given me to see,--it has been so at this place,
having been at two public meetings, one of them the monthly meeting held yesterday,
and the other held to day, and have been silent in both.
Toward the close of that held this morning,
my mind was clothed with thankfulness in a full belief in the truth of those expressions;
'To obey is better than sacrifice,
and to hearken than the fat of rams:' I am desirous that I may be
favoured to conduct myself through the course of this journey,
so as to return to you again in peace.
My friends feel near to me, and I desire the help of their spirits,
having frequently had I to remember you, and your kind desire for me when parting.
I had not a prospect of staying so long when I set out,
but find it good for me to labour from time to time after a state of resignation,
having experienced in past journeyings, being favoured to return home in peace,
and this is my aim now, whether my absence be lengthened or not.`"

On the 13th, he says, "`exercised in mind this morning,
but was favoured with a good degree of resignation to my allotment,
nothing opening with clearness,
and was content to abide this day at our friend Reese
Cadwalader's. O! my weakness and blindness.`"

The next day he thus writes: "`a poor creature this morning, compassed with weakness;
I set off to a week-day meeting, about seven or eight miles distant,
on the other side of the river, called Dixon's meeting, and a miry road to travel.
We got to it however in time, where we found about fifteen or sixteen friends, men,
women and children,
collected in a little log cabin:--I sat the meeting through in silence,
and was favoured to drop a tear in resignation, not daring to put forth a hand to steal.

"`Attended Westland meeting, which came next in course:
I was closely exercised in humble silent waiting to know my Master's will concerning me;
and was favoured to drop my silent tears in resignation to my allotment;
the way appearing closed up as to any public communication amongst this people,
whom I have taken so much pains to come and see.`"

A striking trait in the character of this dear friend,
was the great care he manifested not to move in any religious engagement,
without satisfactory evidence of its being the will of
the great Master in whose service he was engaged.

This may account for the following remarks which he makes
about this time:--"`19th.--At a stand which way to move:
feel a willingness to go toward home if my divine Master pleases,
having f trust been concerned to act, so far, measurably in his counsel and will,
as made known to me a poor creature.`"

Upon conferring with some friends, he concluded to move on,
and prepared to cross the mountain, but after riding some distance into the woods,
all seemed to close up,
and it appeared most pleasant and easy to him to return
back to the friend's house from which they started;
where he says, "`I feel easy under this roof, and remember with instruction,
that when the cloud rested upon the tabernacle, Israel was to abide in their tents.
Laboured patiently to content ourselves here this night.`"

The next day he says, "`no way opens and the pain of my heart is not easily described;
but in all these laborious seasons how good it is to sink down
into that which endures the racing of the sea of affliction.
O! how am I tried with jealousy and fear that it
was not right to come across this mountain,
and no sufficient clearness can I find--wait in patience, O my soul, and reverently hope,
though it may be against hope, that your Saviour is not far from you;
believe him to be as in the 'sides of the ship.'`"

Towards the close of the evening of this day he was favoured
with so much "`calm as to cause thankfulness to arise,
in that the bitter cup was a little sweetened, so retired to rest.`"

In the morning "`felt rather easier,`" and after breakfast sat down with the family,
amongst whom there appeared tenderness, and it being their week-day meeting at Redstone,
he attended it;--respecting which he says, "`another silent meeting,
in which my mind was deeply exercised;
and I was wrought into a willingness to leave this settlement,
and move on towards Hopewell; and while thus looking and thinking,
not knowing but that I should be clear--having
endeavoured to be found in the way of my duty,
as far as I could find it, this thought presented to my mind;
suppose I should have to return back from there or further, how then?
But even to this proving prospect I was resigned,
for the sake of my dear Master's owning presence,
and was ready to conclude it might be a sacrifice
called for at my hands to humble the instrument,
and for a sign to the people.
While these thoughts possessed my mind,
I was brought into a state wherein I could conclude on nothing,
and so was willing to become a blank; nevertheless,
at intervals under these provings of soul,
the states of my fellow professors seemed to be opening before
me--so broke up the meeting and lagged behind my companions,
and breathed forth my complaint unto God, desiring to be preserved in patience.

"`22nd.--Awoke this morning with fervent desires,
if the cause of this detention was in myself, that it might be searched out:
my youthful days, and days of vanity were brought up into remembrance,
and I found a willingness to look over the past days of my life,
from my very youth to this day.

"`Went to Westland meeting,
and therein was solemnly engaged in a continued deep search into my past life,
unto the present time;
and although blushing and confusion attended in the remembrance of past transactions,
mercy is with the Lord that he may be feared and served with dedication of heart,
'Such were some of you,' said the holy apostle.
What were some of them in that day?
Unthankful, unholy, disobedient to parents, covenant breakers,
and guilty of many other evils!
O that I had been more careful to keep my
covenants with the Lord my God in youthful days;
then had I escaped many of the evils which he mentions,
which came down upon me like a mighty stream.
But why does a living man complain; a man for the punishment of his sins?
may not my tried soul join company measurably with them to whom that servant also wrote,
and to whom he says 'such were some of you; but you are washed, but you are sanctified,
but you are justified in the name of the Lord Jesus, and by the spirit of our God.'
Reverent thankfulness arose in my soul at the close of this meeting,
for sensible enlargement of heart, with a secret belief I am in my place;
so I ventured to tell friends after this sixth silent meeting of worship, (that is,
as to myself,) of what had weightily impressed my mind, which was,
with their approbation,
to assemble their children--and appoint a meeting for
them to be held next day but one after.`"

The next day being peaceful and easy in mind, he visited a family,
one of the members of which was sick.
He had a religious opportunity with them, and in the evening remarks:
"`a lonesome evening in the midst of company.`"

After a refreshing night's rest he says,
"`was measurably favoured with a calm this morning.
O! that I may be favoured to feel after and
discharge my religious duty amongst this people,
to the honour of truth and my soul's peace.
I went to the meeting appointed for the children,
feeling poor and in a stripped condition in the fore part of it,
and though I thought I dare not say much about it,
yet Friends concluded it was a favoured time.

"`The next day attended the first-day meeting at
Westland--went to it with my usual poverty;
so stripping a time with me in the forepart,
that I thought it likely we should have another silent meeting;
but feeling some little reviving of religious concern,
I laboured honestly in a close searching manner.
Found but little ease after this meeting, and my way being again much shut up,
conversation was as much so.
After dinner opened my mouth amongst the Friends present, and told them,
though some were ready to wonder at my being thus led,
I believed if I returned home without saying anything more,
my honest concern would have its use, and the Master could sanctify it,
and like bread cast on the waters, bring it up after many days,
when we were far from each other.
I also remarked that I was willing to move towards home,
if consistent with the divine will.
It was a broken, tendering time, and some dear Friends expressed sympathy with me.`"

He appointed a time to see the children of Friends together at Dixon's meeting,
and had an opportunity in the family of the Friend at whose house he stopped,
which "`appeared to be a time of brokenness of heart.`"
He observes: "`After breakfast, retired into the woods,
where I am now finishing these two days' notes, with a thankful heart dedicated to God,
under a sense of his loving kindness and favour.`"

On the following morning he attended the meeting appointed for the children,
in which he was favoured,
and had renewed cause to believe it was in the
ordering of divine Wisdom that he appointed it.

On the 28th, he attended the week-day meeting, "`which,`" he says,
"`was a favoured opportunity, to the comfort and rejoicing of more than myself;
after which had a solid opportunity with Friends,
and felt refreshed and comforted in this day's labour.`"

On the 1st of the third month, he attended another meeting,
and was again shut up in silence.
"`There were some here not professing with us, to whom I felt a tenderness,
and after expressing a few words to turn their minds to the everlasting Father,
in whom there is no disappointment, even in silent meetings,
I requested they would leave Friends together and withdraw.
After this I relieved my mind in some degree in close labour with them;
directing all to a deep examination of themselves, as had been my concern,
to see what the cause was that it should be thus with them.
Little but barrenness have I felt amongst this people.
At the close appointed a meeting for the children,
to be held tomorrow at the eleventh hour.

"`Third month 2nd.--A refreshing night's sleep.
The meeting for children is coming on,
and what am I? O for the washing of water by the word.
Went to the meeting at the time appointed, under exercising discouraging thoughts,
and continued silently shut up until it appeared near time to break up,
when a concern arose in my mind to tell such of the elders or parents as were present,
what had been my employment in the meeting.
This was, to have my own heart searched,
and my desire remained that they might be found engaged in the same work.
After which I was turned toward the children,
and also in a particular manner toward a seeking state present, not of our Society,
unto whom I found considerable openness, and was informed after meeting,
that there were several of that number present; some who had left the Church of England,
and were now looking toward, or had joined the Methodists; and one seeking man,
who heard of this meeting,
rather chose to come to it than go to a marriage he was invited to.
With this day's labour I found peace, though trying in the beginning.

"`On the 3rd, attended another meeting for the children at Redstone,
in which I had an open time, which was cause of thankful rejoicing.`"
The next day after attending the regular meeting at Redstone,
which he describes as a laborious painful time, he returned to Reese Cadwalader's,
where he had the company of several Friends, amongst whom and the family, he remarks:
"`I was once more favoured to feel the spring of gospel ministry arise in such a manner,
as to water others and be refreshed myself.

"`5th.--Favoured with a good degree of serenity and peace of mind this morning,
under a sense that I have so far laboured to be found in the way of religious duty.`"

Charles Williams feeling released from further duty, left him; respecting which he says:
"`This morning I took an affectionate farewell of my tender hearted companion,
who has gone toward home;
after which I laboured in retirement of mind to
feel after my divine Master's will concerning me.
O that I may be preserved under a solemn sense of the
importance of the business I am engaged in,
and that the good hand may accompany this dear youth to his parents and friends.
After dinner we went to C. G.'s, and with him and family had a solid time.
I thought it was solemnly so,
and these expressions arose with weight and were delivered amongst them;
'I counsel you to buy of me gold tried in the fire, that you may be rich;
and white raiment, that you may be clothed,
and that the shame of your nakedness do not appear; and anoint your eyes with eye salve,
that you may see.'
From there went to P. G.'s, where we had another searching religious opportunity.
My mind is often depressed under a sense of the low
state of things amongst the professors in our Society,
and I meet with various provings, in the manner in which I am led when abroad.

"`On the 7th attended their week-day and preparative meeting at Redstone;
a painful suffering time.
In the fore part thereof this language was uttered, 'Awake, arise you sleeper,
call upon your God, if happily he may save us.'
I had some prospect in the morning of appointing
a meeting in the little town this evening;
but now it is gone.
There must be faith, love and desire, in hearers as well as preacher, to labour to profit.
This has been a dark and heavy day to my spirit.`"

On the 8th he visited the preparative meeting of Westland,
and had an opportunity with the children of a Friend in the neighbourhood,
and during the two next days was principally engaged in visiting families.

"`On the 11th, went to meeting, which, after some struggling and conflict,
was pretty open.
The people were exhorted to labour in all their
religious meetings to know the true place of waiting,
and to beg for their daily bread.
While speaking I met with a sudden stop in my mind as to the expression of more words,
and found it safest to sit down, and experienced peace in doing so.
After some time, the situation of Abraham and Lot,
with their being so mercifully delivered out of Sodom, very suddenly impressed my mind;
with which I stood up again and expressed,
that I dare not doubt that the good and great Remembrancer, or quick and powerful Word,
which is sharp and sharper than a two edged sword,
to the dividing between a man and his lovers, flesh and spirit,
influenced my heart to warn some to be content
with such things as they were favoured with;
reminding them of the annexed blessing:
'I will never leave you nor forsake you;'--and not indulge a roving disposition,
and leave their friends with whom they were so
favoured as to be embodied into a little Society;
and as they kept their places they would yet be favoured.
But if any should break through, and go contrary to the mind of concerned brethren,
and get several hundred miles off--if any unforeseen distress should come upon them,
how would it fare with them?
This little testimony appeared close and searching,
and I did not find my peace disturbed in delivering it.
Some Friends after meeting expressed their satisfaction therewith,
believing it would have a tendency to strengthen the hands of the honest labourers.
No way opens with clearness to leave this place;
and this evening felt so impressed with a sense of my own weakness and unworthiness,
that it led me into the fields to seek counsel of the Lord,
where I experienced a little quiet and calm, in a solitary situation.

"`12th.--A restless night,
under the painful thought that the flesh prevailed too much over me in one instance.
O what small things grieve a tender conscience!
May I be favoured to labour after more perfect victory,
and at present rest humbled under this petition; 'Lord forgive what is past,
and condescend to be near to help in future.'`"

Although he was for some time considerably exercised as to what step to take,
he finally concluded to go homewards;
and had parting religious opportunities with several families and Friends;
in relation to one of which he thus writes, under date of 13th of the month.

"`Had a parting opportunity with this family,
which I hope will not be easily forgotten by us or them;
after which I found considerable ease of mind, and rode to Beesontown, twelve miles,
where we dined; and then collected this large family together, with some others,
and were favoured with a baptizing season.
My soul was bowed in supplication, and also in reverent thanksgiving,
to the gracious Author of my life and well being, who led me here,
and has preserved and fed me, and now is opening a door out,
to my solid peace and comfort.
Parted with dear Reese Cadwalader at this place;
and I thought the ancient language was measurably experienced by my thankful mind:
'The wilderness and solitary place shall be glad for them,
and the desert shall rejoice and blossom as the rose.'`"

In crossing the mountain they met with the usual
difficulties experienced by travellers at that period,
in consequence of the rugged character of the road,
and the poor accommodations both for man and horse, which they were obliged to submit to.
At the taverns, as well as on the road, when he believed it to be his duty,
he did not fail to exhort persons with whom he met, to flee from the error of their ways.
With respect to the scenery of the mountain,
with which he was much interested and gratified, he says:

"`Heard the sound of the frogs, denoting the approach of spring.
What harmony in the outward creation! nothing, however minute, was made in vain.
Even these creatures seem to be uttering thanks to the great Creator,
for the opening of a new season.
I was delighted with seeing the birds sporting themselves in the woods:
the voice of the turtle-dove was also to be heard,
and the husbandman was seen at the plough.
All this perhaps not more than fifteen miles from ice and snow.
It has been a day of solid thoughtfulness,
in meditation on the wonderful works of Providence.
When viewing the beautiful springs gushing from the sides of the hills,
amongst the rocks and stones,
I had to remember that 'springs were to be found even in the desert,
and fountains in high places.'
Various landscapes opened one after another,
in viewing which I frequently found profitable employment on the road.
But over and above all, this day, and peculiarly so this afternoon,
was the fresh feeling and sense of the love of Christ my Lord and Master,
shed abroad in my heart, making it like spring time in a spiritual sense.
The remembrance of the poverty of spirit in which I
crossed this mountain about one month ago,
of my close exercises on the other side, of the preservation vouchsafed under them,
and how the way and time to return homewards, were set open so clearly before me,
brought feelings over my mind, in which that saying was measurably fulfilled;
'He that goes forth and weeps, bearing precious seed,
shall return again bringing his sheaves with him.'
My mind was bowed in reverent thankfulness,
and many passages of Scripture were opened to my understanding,
wherein I was measurably favoured with a taste of the
same experience which holy men of old spoke of.
This made it feel like a spring time indeed,
the wintry season of trials and close provings being for a moment past and hid,
and the singing of birds heard, as also the voice of the turtle spiritually.
My dear family and some of my friends were brought feelingly into remembrance,
and as I had been engaged for the good of the children of others,
so now my desires and my prayers have been put up to my gracious Redeemer,
that he would look down and remember mine.
May I still be engaged to give up in the littleness and weakness, but in the faith,
to follow my Lord and Saviour Jesus Christ,
who is abundantly able out of weakness to make strong.`"

On the 17th, after having been kindly entertained at a Friend's house,
who since they passed that way before, had experienced considerable affliction, he says:
"`I remembered when about to leave this house on our outset, I ventured,
on my bended knees, to supplicate my dear Lord to go with us,
as he did with his poor prophet formerly, whom he caused the ravens to feed;
and now considering how he had preserved and brought me back again in peace,
and had so eminently visited this family,
my mouth was again unexpectedly opened to express the grateful sense received,
and to pray for further preservation;
which proved a tendering time I believe to most present.`"

After attending Centre meeting, in which he had to set an example of silence,
for which he remarks, he thought there was cause,
he felt a drawing to visit an individual and her father, who were Methodists,
where it appears he lodged and was hospitably entertained.
"`In the morning,`" he says, "`family duty was performed before we were out of bed.
When we were about setting down to breakfast, grace was said by the master,
as was last evening; and my heart being exercised in a thoughtful concern for them,
I kept my standing, and after a season kneeled down in supplication;
after which I found peace to flow as to my own particular.
Breakfast being ended, the daughter expressed something in a low voice,
like giving thanks for benefits received; and being about to leave them,
I requested a silent opportunity, when I was favoured I trust,
to declare my exercise faithfully: some tenderness appeared,
and the religiously minded woman on parting, desired the Lord might bless me.`"

From the 20th to the 30th of the third month,
he was detained in the neighbourhood of Fairfax, visiting meetings,
and also many of the families composing them.
On the 29th he says, "`he went to M. J.'s,
in order to get ready to leave this settlement in the morning;
the way and time seem to be opening.
I trust all my debts here are nearly paid,
and may I not stay one hour longer than the precious oil which is due to others,
is experienced to run.`"

On the 31st, he proceeded some distance toward home, which he says, "`looked pleasant,
but at the same time I felt a care of indulging
the prospect of reaching it in a few days.`"
A concern arose in the evening to visit Pipe and Bush creek meetings,
which had been hid for some days previous.
This, he remarks, would be work enough for six or eight weeks more,
and having no steady companion, his beast lame,
and "`the instrument poor and empty,`" he was introduced into much exercise.
The next day he attended two meetings,
in which he was favoured to labour to the ease of his own mind
and to the encouragement and comfort of some others;
yet he thus writes: "`What a poor creature I am this evening: my enemy is very near,
and has been labouring to cause me to break rank.

How careful should gospel ministers be--those who make use of such exalted language
as is at times put into their mouths--to keep their bodies in subjection,
lest they be caught in the snares of the wicked one, and after such high favour,
become cast-aways.
Went to bed under exercise; my way closed up.`"

For some time his way continued hedged up, and under deep exercise he thus writes:
"`Dearest Lord, have I not given up to be your servant?
lead, O lead and guide me in the way I should go.
If there be anything more for me to do, baptize and fit me for the service,
and if there is no more, be pleased to preserve your servant,
and bring him in safety to his outward habitation;
for you can abundantly bless all them that love you.`"

On the 5th, he attended the meeting at Bush Creek,
in which he had an open satisfactory opportunity;
on the 7th the monthly meeting of Warrington, which he sat almost through in silence,
but near the close these expressions impressed his mind to deliver;
"`it is a precious thing to be found a learner in that school,
wherein Jesus Christ presides as the heavenly teacher;
and where this lesson is to be learnt, 'not my will, O Father,
but yours be done;' it is a lesson I found necessary for me to learn,
and I had peace in dropping the same.`"

Soon after he was permitted to turn his face homeward again, and arrived in York,
Pennsylvania, on the 10th, where he writes:

"`It has been a proving dispensation since I left this place;
somewhat resembling my outward journey over the mountains,
where a place called 'the shades of death,' is to be
passed through on the way to a beautiful prospect,
from the mountain over the good land!
O, that I may be favoured with renewed faith and patience;
and experience a returning home in peace, when this religious pilgrimage is fully over,
to the honour of the great Master;
who knows best how to break the spirits of his servants,
and fit them for the reception of himself in his
blessed appearance of sweetening encouraging love.`"

Having been considerably indisposed, he staid a day or two at York to recover his health;
and Peter Yarnall having offered to accompany him to Lancaster,
where he understood John Townsend, a ministering friend from England expected to be,
they started for that place on the 13th. But on the 14th,
he believed it to be his duty to return and visit
Monallen meeting and some others in the neighbourhood,
though he says, "`with very little prospect of any good resulting,
unless for his own mortification.`"

He visited these meetings, and found in one at least there was cause for his returning.
He had the company of his elder brother John Townsend,
who proved to be a sympathizing father and encourager to him, and he remarks,
"`it was a peculiar satisfaction to find we have been
led so much alike in religious communication.`"

On the 19th after attending Monallen meeting, he says: "`I find much relief,
and it appeared as though my release from more religious service was near;
my mind being turned toward my own residence.`"

On the 20th he set off, and at the ferry over the Susquehannah,
he says he felt his mind religiously concerned to caution and advise the inn-keeper,
which he accepted kindly,
and he was also engaged to reprove the ferry men for their vanity and swearing,
to which they seemed to listen with attention.
O! how many poor abandoned creatures there are up and down,
who are drinking in sin and iniquity as an ox drinks water.`"

On the 21st of fourth month, 1787, after an absence of nearly five months,
he was permitted to return to his family and friends with "`the sweet reward of peace.`"

On the 27th of the eleventh month, 1788, he again left his family and friends,
with the approbation of his monthly meeting;
on the 28th attended the youths' meeting at Middletown, Bucks county, Pennsylvania;
on the 30th Plumstead meeting and taking Buckingham monthly meeting,
Wrightstown and Falls meetings, he crossed the river to Burlington,
and on the 7th of twelfth month had a meeting for the inhabitants of his native city,
which was large, and thought to be a solid good time.

On the 8th he attended an appointed meeting at Mansfield neck,
and the next day their monthly meeting, and being joined by John Hoskins and John Cox,
they were at meetings at Vincentown, Mount Holly, and Upper Springfield.

On the 16th he says: "`had a solid time with the widow Newbold's family,
and then went to see a young man, about twenty-five years of age,
with a lovely wife and child, who lies ill in consequence of a fall from a horse,
which he was running on the afternoon of the last youths' meeting at Crosswicks.
He left home on business, but attended the meeting,
which I have understood was a favoured time,
and from there he went to a tavern and got amongst some
company who induced him to join them,
against his judgment and inclination,
and at last persuaded him to run his horse against one of theirs.
As he was doing so, he was knocked off the horse by striking a tree,
and was taken up for dead, and has been in a deplorable condition for three weeks past.`"

On the 17th attended Mansfield meeting in a stripped condition;
on the 18th shut up as to any prospect, so remained at C. Newbold's,
our kind friend John Cox remaining with us in sympathy.

"`21st.--Learned that the young man above alluded to was still alive,
and expressed some concern that I did not come to see him; so concluded to do so,
and found him sensible; I laboured in the ability given for his everlasting welfare,
and he expressed his satisfaction and thankfulness for the visit.

"`22nd.--This morning received an account that L. N., the before-mentioned young man,
deceased last night.
Went after breakfast to see J. F., who lay in a sorrowful condition,
and then to another family who had kindly invited us.
After we had dined and were about sitting down together in a religious way,
Daniel Offley came in; which put me to some trial, but I found there was no time to lose,
and my beloved brother, Daniel Offley, soon perceived what was going forward,
and proved a fellow-helper.
The next day attended the funeral of the young man, and held a meeting on the occasion,
in which D. Offley was a fellow-labourer.
Then I found a liberty gently opening in my heart,
but in much weakness and fear to appoint meetings forwards.
I called to see the poor afflicted widow who did not go to the funeral;
and returned to M. Newbold's, peaceful and easy,
being now favoured to see the end of my detention and trials in this neighbourhood,
and hope the aforesaid meeting was a solemn time of warning and caution to numbers.
My heart is thankful to the Lord for his merciful preservation in patience.

"`On the 24th attended a meeting appointed at Bordentown,
and on the 25th at a large meeting at Crosswicks,
where my Lord and Master favoured me with strength to relieve my soul fully;
having in the course of religious communication to revive the
melancholy circumstance of the poor young man before recited.
After dinner visited the tavern keeper and wife, near by where the race was run,
and then to Nathan Wright's, where we were affectionately received and owned.

"`26th.--To Arneytown meeting, which was large, but a very exercising time to me.
As we were riding towards Nathan Wright's, about one mile from meeting,
over a very rough road, my mare fell down and threw me over her head,
but through preserving mercy and care I received not much hurt.
For which favour, as soon as I was a little recovered from such a sudden surprise,
I found reverent thankfulness to spring up in my heart,
unto the upholder and preserver of his creature man.
Spent this evening at Nathan Wright's,
partly in a solid religious opportunity with this family, and some others present,
I hope to profit.`"

After attending meetings at Robins', Shrewsbury, Freehold and Trenton, he writes:

"`First month 1st,
1789.--Awoke this morning with renewed desire to be found walking in the way of my duty,
and that it might be as the day of a fresh setting out
under the guidance of the heavenly pilot,
Christ Jesus.
Was also favoured with some precious openings in regard to my present journey;
went to meeting at the time appointed,--my companion,
I thought had something lively to offer, but found it my business to sit silent,
in which I was favoured with renewed satisfaction and comfort;
yet on the close was not easy without appointing
another meeting at six o'clock this evening,
desiring such as were with us to come again, and also to invite their absent neighbours.
Went to meeting at the time appointed, which was pretty full,
and trust it proved a solid baptising time.`"

Went to Burlington,
and on the 4th opened in their monthly meeting a prospect of visiting in their families,
all the inhabitants of the town who were willing to receive him,
which being solidly considered,
some Friends were appointed to accompany him--John Cox offering himself a volunteer.
From this time until the 6th of the second month, was spent in accomplishing the service;
after which, accompanied by John Cox, went to the Falls, and from there to Makefield,
Wrightstown, Kingwood, Hardwich, and Mendham; from there to Plainfield, Rahway,
Stony Brook, and through Trenton to Burlington quarterly meeting.
After this he returned to his own home with sheaves of peace in his bosom--and adds,
"`may the Lord, the helper of Israel, be praised.`"

In the summer of this year he again left home in the service of his divine Master,
being engaged to pay a visit in gospel love to some meetings in New York,
and on Long Island, in which engagement he had the company of his friend John Cox.
After attending a number of meetings on Long Island,
he was at Oyster Bay on the 26th of seventh month,
which was a solemn and profitable season,
as was also a religious opportunity in a family: he remarks,
"`here it may not be unprofitable to record the mercy
and goodness of the Lord to his devoted children,
who at times is pleased to make them helpful one to another,
and encouragers of one another when favoured of Him.`"

He attended the quarterly meetings at Purchase and at Flushing,
and also the monthly meeting at the latter place,
at which were a number of Friends appointed by the quarter,
and it proved a strengthening and comforting season,
wherein they were enabled to thank God and take courage.
They soon after returned to the city of New York, where they met with Rebecca Jones,
and the following memorandum occurs:

"`Eighth month 9th.--Attended the meetings in New York,
wherein my elder sister Rebecca Jones had a large share of public service,
and I also had some labour, which afforded satisfaction and peace to myself.

"`12th.--Went to the week-day meeting at New York,
accompanied by a friend who had been low in his mind,
and had not been at meeting for upwards of six years.
It proved a good meeting to more than myself, and in the evening,
to the great comfort of his relations,
prevailed on the above mentioned friend to return to his lovely family,
from whom he has been absent several years.
When I was here four years ago, I was concerned to visit this poor disconsolate man,
and on bended knees to pray for him.
I also went to see his wife and children, and in an opportunity with them,
had to express my prospect, that the time of deliverance from this affliction would come,
and perhaps was not afar off; and it has been strengthening and encouraging to me now,
to see him again restored to his family, and in his right mind.`"

On the 14th he left New York,
and the 15th and 16th he attended the quarterly meeting at Rahway,
in company with Rebecca Jones and M. Robinson;
after which the following memorandum occurs:

"`17th.--A very large meeting, and a great mixture of different sorts of people,
many of whom could not get into the house.
I believed it my place to stand forth amongst them with a heart much exercised,
on account of the looser sort, not only amongst Friends, but of all ranks.
I was led to caution and warn the unwary and frolicksome youth,
and to tell them of the circumstance of the young man who was killed at a horse race;
remarking that the Almighty warned his creatures in various ways,
sometimes by night in dreams and visions as Job says; and sometimes by day also.
After this our dear friend Rebecca Jones, was favoured in a large testimony,
chiefly to Friends; and at the close of the meeting when about to part,
I had again to stand up, and warn the youth in a particular manner,
that they should return from the meeting home,
under a thankful sense of the favours received, and keep out of lightness and frolicking.

"`On the 18th was a large meeting, wherein there was acceptable service;
we had the company of our dear friend Joseph Delaplaine, of New York,
whom I felt near to my life in inward labour, although silent.

"`19th.--Went to Plainfield monthly meeting, accompanied by my friend James Whitall,
who has been with me during the time of Rahway quarterly meeting.
Rebecca Jones and John Cox staid at Rahway poorly, not venturing out in the rain.
I think we had a favoured good meeting at Plainfield, and then returned to Rahway.`"

In a letter to a friend, dated Rahway, eighth month, 1789, he says:

"`I thought I would send you a few lines by the bearer hereof, E. R.,
who attended Plainfield monthly meeting yesterday with his offering.
I was glad for E.'s sake that I was there, and thought there was a solid weight attended.
Friends readily received him into membership,
and a certificate to our meeting is to be prepared, to be produced next month.
I thought it would be satisfactory to hear this much,
and a little also of what your poor and often enfeebled brother has been about.
I went no further than Purchase quarterly meeting, about thirty miles above New York.
Finding that Nine Partners quarter was held the same week as this at Rahway,
I was easy to cross to Long Island again.
I was much shut up and exercised in that Island,
but favoured to come away easy and peaceful, and my visit to friends in New York,
as to myself, has been the most peaceful and pleasant of any time I have been there.

"`My companion John Cox, sets off presently in company with E. R.,
and I have James Whitall of Woodbury with me;
he came with a minute from their monthly meeting,
to see me round within the compass of their quarter; but here I am this morning,
as frequently is my lot, a poor blind servant, waiting for future direction,
seeing no way to move with sufficient clearness.
I have been favoured with the acceptable company of our dear Rebecca Jones,
both at New York and in this place, which has been strengthening to me.

"`20th.--John Cox left us pretty early;--some time after which dear M. Robinson,
J+++.+++ Delaplaine, and other friends from New York, being ready to return,
we sat down together and were favoured with a precious season.
After parting with so many near friends, my mind was tenderly affected,
and gathered into a quiet habitation,
wherein it was nearly turned toward my beloved help-mate in life.

"`On the 21st, Rebecca Jones left in company with Joseph Shotwell;
and after they were gone my mind was thoughtfully engaged to
know for what end I was thus left as it were alone;
and all prospect of religious service removed.
I had laboured fervently during the time of the quarterly meeting,
and had thoughts of appointing a meeting on Staten Island, but that was removed,
and here I was left, a poor blind exercised servant;
and was sunk under such a weight of exercise,
that I thought of going up to lay on my bed.
While sitting in this exercised condition,
James Shotwell came into the room where I and my companion James Whitall were sitting,
and informed us that a sorrowful circumstance had happened;
a number of young people going into the water at Sandy Hook were drowned,
and the bodies of four young women were just brought up in the shallop they went out in.
We walked down to the landing, and there saw them lying on straw on the deck,
side by side, and a very serious sight it was.
After we returned home to James Shotwell's, I was soon informed by my blessed guide,
there was more work for me to do in this place,
and I was strengthened to desire Friends to go
to the houses of the relatives of the deceased,
most of whom it was expected would be laid in Friends' ground,
and make way for a meeting after the burial, which they did,
and it was concluded to bury them all in one grave in Friends' ground;
and there being a burial this afternoon of a young woman of the Presbyterian Society,
who died of a putrid fever, and some Friends attending it,
gave notice of the burial tomorrow.
I went to the house of a relation of one of the persons drowned,
where we had a humbling time amongst a number of the relations and others,
who escaped the jaws of death.

"`22nd.--Went to the burial, which was a solemn scene:
such a grave I never saw before--wide enough to lay the
bodies of these poor young women side by side,
who but a few days before were mostly in full health and strength,
and most or all of them at meeting.
Solemn it was to see the coffins one by one, brought into the grave yard.
We went into meeting, which was made up of various ranks and classes of men and women,
the passages filled up with those who stood, and many out of doors who could not get in.
I had a laborious time amongst them, but trust, through divine help,
the free and everlasting gospel was preached, and truth not dishonoured.
The people behaved quietly, considering the great throng.
It was a relieving time to me, although spending to the body;
but the Lord can help and does help his poor servants in the needful time:
praised be his name,
and may the mouths of the servants be kept as in the dust before him.`"

The following account of this mournful event, is furnished by another hand:

"`At our last quarterly meeting, our beloved friend Thomas Scattergood,
in the course of his public testimony, in moving language,
warned the youth present to beware of loose behaviour, dancing, frolicking, etc.;
stating,
that he had known several instances of divine
displeasure being manifested to individuals,
who had attended such meetings as these, and directly afterwards had gone to horse races,
or other sinful pastimes.
One instance he mentioned, of a young man, who, on his way home from a favoured meeting,
falling in with a company of persons who were collected for a horse race;
they urged him to ride one of the horses--he at first refused,
but being pressed by some of them, at length yielded;
and in the race was thrown from the horse, which occasioned his death.
He said it appeared to be his business to warn the youth present,
to beware of such conduct, lest some of them might be made like examples.
'I do not say,' said he, 'it will be the case,
but I find it my place to proclaim a solemn warning.'`"

"`On third-day our meeting ended:--twenty-seven persons, chiefly young people,
embarked on board a boat, bound for Sandy Hook; but before they set off,
it was observed that several of them were discouraged, and ready to give it up;
and on their way it was remarked, how dreadful it would be,
if any unfavourable accident should happen, after having been at meeting,
and hearing the advice then given.
On fourth-day they went to view a monument erected over a person of distinction,
who with twelve others perished there not long before.
On fifth-day, they walked to the light-house,
and on their return went on a narrow reef of sand, which is bare at low water,
as also the way to it; on this they spent some time in walking, etc.
At length, observing the tide to run fast, they were alarmed and concluded to return.
But alas! the sea had hidden their path, and covered all their way-marks!
However, they made the attempt, and as they were pressing on,
eleven of them suddenly stepped into the deep, were overwhelmed as in a moment,
and seven of them perished.
The others, with the assistance of some of the company who could swim, got to the shore,
though almost spent.
Four of the bodies were found, and brought up here +++[+++Rahway,]
on sixth-day.
The next day was appointed tor their interment, and notice being given,
a great concourse of people attended; after which a meeting was held,
wherein our beloved friend Thomas Scattergood was enabled to preach the gospel,
pertinently to exhort all present to profit by the present calamity,
and feelingly to impart a portion of consolation
to those who drank largely of sorrow's streams.
He had not felt easy to return home after our quarterly meeting ended;
but waiting in great exercise of mind,
was not able to discover the cause of his being thus detained.
On sixth-day morning, he retired into a private room,
and sitting a while under the like pressure of exercise,
a messenger stepped in with the foregoing sorrowful tidings.
Then he could account for the trying dispensation he had passed through,
which he related in his discourse to the crowded audience,
observing that it might be said of him as of Nehemiah, 'why are you sad,
seeing you are not sick?'
'I was not sick,' said he, 'but felt such oppression of exercise,
that I thought of taking my bed.'`"

"`23rd.--Attended two pretty large meetings in Rahway--had large open service in them;
and in the evening went to visit the afflicted widow of +++_______+++, who perished,
and is not yet found: here we met with a number of neighbours,
and it was I hope a humbling awful time, which will be remembered,
and the poor widow I trust, was somewhat strengthened and encouraged.`"

After holding a meeting on Staten Island, he again attended Rahway meeting on the 25th,
and proceeded to Stony Brook, where he appointed a meeting the next day,
in which he was silent; from there he went to Trenton, where a meeting was held,
in which he says, "`I hope we were favoured to offer an acceptable evening sacrifice.`"

After this he attended Bucks quarterly meeting, and went to Burlington,
where he remained visiting the meetings as they came in course,
until the 4th of the ninth month.

On the 3rd he thus writes: "`Attended the week-day meeting in Burlington,
in which my mind was very particularly turned to speak to the state of an individual,
who appeared to me to be present; and next day I met with a person,
whom I knew not was at meeting, but he acknowledged frankly,
that he was the person thus spoken to, and hoped he should be favoured to improve by it.
This was cause of renewed encouragement to me,
it having been trying thus to be detained in this place.

"`Ninth month 5th.--To Joseph Shotwell's at Rahway,
and feel myself a poor exercised servant, not knowing for what I came here again,
but am favoured with peace of mind,
the great blessing promised by our Lord himself to his devoted followers:
soul wait in patience.
On first-day, the 6th, I attended two large meetings,
and in the close of the day was made thankfully to rejoice.
On the 7th appointed a meeting for those of other religious denominations,
and which was a laborious one to me.

"`On the 9th went to Plainfield meeting, which was also laborious.
On the 10th to a large and favoured meeting at Rahway.
On the 11th to an appointed meeting at Elizabeth Town,
Here we had some of the heads of the people, and hope this meeting was to some profit:
the governor being at it, kindly invited me to go home with him and was very friendly.
Dined with a friendly tavern-keeper, who with much affection, entertained a number of us,
and after dinner we were favoured to partake together
of a measure of that which exceeds outward bread.

"`On the 12th attended an appointed meeting in the court-house at Amboy, which was large,
and I thought a solid good time.
Had an exercising time at the tavern where we left our horses;
thanks be to him who is ever worthy,
for the strength vouchsafed to relieve my mind
amongst a company of wild youth and others;
and O the thankfulness of heart I now feel,
under a sense of the Lord's goodness in thus preserving me
through this one more weighty and arduous week's work.

"`Ninth month 13th.--Attended two large meetings in Rahway;
and in the morning was favoured, I thought,
with much strength and ease to unburden my mind; but that in the afternoon was laborious.
A large number of Friends came to our lodgings in the evening,
and hope it proved an opportunity to be remembered in a future day by some of us.
My soul desires to lay prostrate before the Lord,
that I may do nothing to mar his blessed work,--
feeling much jealousy and fear on my own account:
ever keep your poor servant, O Lord, in a sense that you are good and I myself am blind.

"`15th.--Went to an appointed meeting held at Newark court-house; which was large,
and appeared to be to general satisfaction;
it being the time of the sitting of the court,
the judges were so respectful and kind as to adjourn to
a public house to accommodate the meeting,
and several of the lawyers came to it.

"`16th.--To an appointed meeting at a place called Westfield,
where there never had been a Friends' meeting; it was held at the house of Dr. Elmore,
who not only opened his house, but we had reason to believe his heart also was opened,
and it proved a time to general satisfaction: the priest of the place attended,
and in the presence of a number of his hearers owned the doctrine delivered.

"`On the 17th to the monthly meeting at Rahway, which proved an open comforting time.

"`18th.--Waiting to see with clearness which way to
move--feeling much peace and comfort on looking back,
and remembering the supporting hand of the Lord that has been with me
and upheld in the arduous labours in and around this place.
'I will thank you for your mercies past,
and humbly hope for more.'`" After this he
returned through New Brunswick and Stony Brook,
and reached his residence on the 21st, in peace, for which he says,
"`Thanks be to him who is ever worthy thereof.`"

From the 22nd of the ninth month to the 11th of the tenth month, he spent at home,
attending the yearly meeting and looking after his outward affairs.

From the 11th of tenth month to the 18th of the eleventh month,
he was engaged in visiting the meetings belonging to
Haddonfield and Woodbury quarterly meetings,
and between this and tenth month 1791,
performed several little journeys to quarterly meetings.

In the tenth month 1791, accompanied by his friend John Pemberton,
he visited Shrewsbury quarterly meeting,
and a number of families at a place called the Branch;
and in the latter end of the first month 1792,
again attended Shrewsbury quarterly meeting and visited
a number more families at Deal and Poplar Swamp,
and appointed several meetings in and about that neighbourhood.
He then parted from John Pemberton, and taking the monthly meetings in his way,
beginning at Upper Springfield, went as far as Cohansey;
in which journey he met with some singular occurrences,
as often heretofore "`through which,`" says he,
"`the Lord supported my exercised soul unto the end,
and favoured me to get home to my family in peace.
I went forth weeping and in great strippedness and poverty,
and yet was favoured to discharge my religious duty in such a manner,
as to return with sweet peace.
O Lord, my gracious helper, favour me still in my passage through life,
with your light to enlighten and guide my steps.
Returned home on 3rd day of third month 1792.`"

Extracts from a letter written while on this journey to his family, dated Poplar Swamp,
second month 4th, 1792.

"`I left you in great weakness as I expressed and my going forth was I knew not where,
and to receive the inheritance of peace, I knew not when.
I have rejoiced heretofore in sitting down with you,
and parting under a solemn covering of divine love,--
but at this time I saw little but to go forth,
and so I left my home, committing you all, with myself,
to the keeping of the good Shepherd, who puts his servants forth and goes before them,
and provides all things convenient,--and all this in faith,
without much prospect of service.
I received a small portion of encouragement in a parting opportunity at James Thornton's;
on taking a view of his diligent labours in the gospel in younger life, when of ability,
who now is rendered unfit for travelling by infirmity of body;
in the revival of those expressions of a primitive
labourer in the same blessed work and calling;
'Our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom,
but by the grace of God we have had our conduct in the world.'
Very simple, poor and destitute I often felt while with you,
when weaning from the breast of this world,
and preparing to leave all that is near and dear in life,
to follow the leadings of that good hand, which has, in adorable mercy,
plucked me as a brand from the burning;
and redeemed my soul from the pit of destruction and misery.
When I am thus separated from you, fervent have been the desires of my soul,
that he who leads his poor servants forth to war a good warfare, under his safe-conduct,
may be with those who stay by the stuff.`"

Extract from a letter to Hannah Cathrall, dated,

"`John Wistar's, Salem, N. J., second month 23rd, 1792.`"

"`I received your encouraging lines this afternoon on
my way from Alloway's Creek to this place,
and thought I would inform you how acceptable they were to me,
a poor exercised traveller.
They brought into remembrance your sympathy with me while I was in New England,
at a time when I thought I stood in need of such remembrance.
My path is singular when abroad, and with reverent thankfulness I may acknowledge,
that strength has been graciously afforded me in every trying and
needful season,--and some such I have met with in this journey.
I left my own habitation very poor in mind--indeed I felt in
this condition when my friends set me at liberty,
and could but admire at the cheerfulness which appeared in some minds to do so.

"`I do not recollect that any testimony of approbation which dropped
from the lips of any of my dear friends in that low season,
has proved more of a refreshing cordial,
than a few expressions which were uttered by dear E. H. What a small portion of bread,
if really bread, and sanctified and blessed, is truly nourishing and refreshing.

"`Therefore, beloved sister, there is abundant reason for humble hope,
that in present provings and succeeding conflicts,
he who is Lord in Zion will furnish the necessary qualification.
Be therefore strong, let not your hands be slack.
How often have I wished that strength might be the girdle of your exercised mind,
with respect to the fulfilment of your duty in the line
of the ministry of peace and reconciliation.
Do you not undoubtedly believe that a gift,
received from the great and bountiful Giver of all good and perfect gifts,
will prosper in every turning of it?
O then, dear friend, let us follow it closer; let us say with devotion of heart,
'draw me and I will run after you,' not waiting for great manifestations,
or tempting our divine Master with saying 'show
us a sign,'--but rather let our language be,
only condescend to show me that the requiring is from you, the Lord my God,
my heavenly Prophet, and I will follow you whithersoever you are pleased to lead.
May you be the companion of such as these.
How many are there up and down in the land, who would rejoice and be refreshed,
in the exercise of that precious gift and talent conferred on you,
my sister,--therefore let not him who brings in strong reasonings,
have place for a moment;
but exercise that faith which removes mountains out of
the way--making them at times to skip like rams,
and the little hills like lambs, that thus we may do our day's work in the day time.`"

