== Chapter II.

In the fifth month, 1785,
he obtained the concurrence of his monthly meeting to pay a religious
visit to the yearly meeting of Friends on Long Island,
and the meetings composing the quarterly meetings of Oblong and Nine Partners.
After attending the yearly meeting,
he went to New York with a Friend who had
offered to accompany him to some of the meetings,
but the way seemed to close as to proceeding further.
In a letter to his wife, dated sixth month 10th, he thus describes his feelings:

[.embedded-content-document.letter]
--

My prospect was to go towards Oblong and Nine Partners,
and so continued until second-day afternoon.
We sat down with Henry Haddock, and some other Friends who came in;
and here I was plunged into such a condition as I have not often experienced.
The importance of the undertaking spread with solemn weight over my mind,
joined with a sense of weakness and incapacity without the interposition of divine help;
under which I was much broken into tears,
in humble resignation to follow my gracious Master,
who had been pleased to lead me thus far, measurably in his counsel and will.
I endeavoured, as well as I could, to inform my friends how it was with me,
and we concluded it would be safest to wait until morning.
Retiring to my room, I got vent,
for indeed my cup was made to overflow much in the same manner as when I left you,
only with this difference; that then I moved in the clearness and in sweet peace;
now there seemed a cloud in the way of going forward.

Next morning my mind was settled into sweet quiet,
with a release for the present from proceeding;
and concluded to let my beloved companion leave me and move homeward.
Since he has left, I remain easy to set my face homeward,
with a heart resigned to return and finish the visit when my
heavenly Master may be pleased clearly to open the way.

--

On the 11th he set off for home, and having two meetings by the way,
arrived there on the 13th.

On the 29th of the seventh month,
he again obtained the certificate of his monthly meeting to perform this visit,
and set off in company with his brother-in-law, "`feeling,`" as he remarks, "`very poor,
with many discouragements, but endeavouring to wear the sackcloth underneath.`"

On the 1st of the eighth month, they arrived at New York,
where he parted with his brother-in-law, and proceeded to James Mott`'s, at Mamaroneck.
On the 4th and 5th, he attended the quarterly meeting of Purchase;
"`at the conclusion of which,`" he says,
"`I was free that mention might be made of my
willingness to sit with Friends in several meetings.

"`On the 9th, to the meeting appointed at Mamaroneck.
Went poor and empty, and in the forepart was humbled under a sense of my unworthiness;
and while pondering thereon,
a language like this arose with a degree of strength to begin my testimony with.
'`It is written, man shall not live by bread alone,
but by every word of God;`' and with it I arose with tears;
and hope the meeting was to some profit.

"`10th.--My friend James Mott, having got himself in readiness to accompany me,
we sat out together this morning to the appointed meeting at Purchase,
which I hope was to satisfaction.
Lodged at Jacob Underbill`'s,
who told us he remembered when there were no
Friends further north than this neighbourhood.
My companion also informed me,
that in looking over the monthly meeting minutes of the year 1727,
he finds there was but one monthly meeting and three particular meetings on the main;
and now there are seven monthly meetings, two quarterly,
and twenty-five particular meetings on the main;
which shows the great increase of Friends in this government.

"`11th.--To the monthly meeting at Shappaqua, which was satisfactory.
Went home with John Griffin, of Amawalk; in going to whose house,
a distance of six miles, we had a mountainous road to travel,
and near it the river Croton to ford after night; through all which I felt pleasant.

"`On the 14th went to the meeting called the Valley,
and then proceeded to Daniel Merritt`'s. After ascending a rough narrow passage,
on a desolate mountain we passed over today,
there opened to view a small plantation with a dwelling house.
On riding up to the door to inquire our way,
a goodly woman came out with a bible in her hand, and gave us directions.
I engaged her in a little conversation, and found she was a member of Society.
I was made renewedly sensible, that He who formed the mountains and planted the hills,
whose presence is everywhere, could be worshipped here,
and my mind was favoured with content in my present allotment; blessed be His name,
whose work it is to bring into such a condition.
Even in a waste wilderness, far away from family and friends,
he can enable us to visit them in spirit,
and engage in humble prayer for our own and their preservation.
Thus I may thankfully acknowledge it has been with me today,
although much exercised and tried in setting out from my dear wife and family.

"`15th.--Went to monthly meeting,
and on the 17th attended the quarterly meeting
of ministers and elders held at Nine Partners,
and on the 18th and 19th, the quarterly meeting for business.

"`20th.--The usual time of holding the monthly meeting at the Creek, being yesterday,
it was adjourned until today.
We attended it, and it held from eleven o`'clock until night,
A committee was appointed to visit the meetings of Hudson and Coeyman`'s Patent,
respecting settling two preparative meetings.

"`21st.--Went to a meeting about twelve miles further, called Little Nine Partners,
held in the barn of Obadiah Gifford.
This was an encouraging meeting to me,
and after it we took a little refreshment and proceeded, accompanied by several Friends,
who were going to the new city of Hudson, thirty miles.

"`22nd.--Was not easy to appoint a meeting in this place,
but concluded to let Friends appoint one tomorrow,
about sixteen miles further on the other side of the river,
and move on with the aforementioned committee.

"`23rd.--Crossed the North river opposite the town, and rode to meeting,
and after an open time with Friends and friendly people,
opened the business of the monthly meeting,
respecting their holding a preparative meeting;
and after a solid conference it was concluded they might hold one.
The first meeting in this place was held by a Friend on a religious visit,
five years ago, and I have a comfortable prospect there will be an increase.
The meeting was held in a log-house.

"`25th.--Attended their week-day meeting at Hudson, with the monthly meeting`'s committee,
and at the close mentioned to Friends a prospect which accompanied my mind,
to engage in visiting families, if they united therewith, which being approved,
some Friends were appointed to accompany me.
In the afternoon we visited four families.`"

On the 26th ten families were visited; and he says,
"`this has been an arduous laborious day`'s work,
under which I seemed at times near fainting,
but was favoured to go through to a good degree of satisfaction to myself,
feeling peaceful this evening.`"

On the 27th, after enumerating the families visited, he remarks;
"`another day of exercise and close labour.`"

"`28th.--First-day of the week.
Went to their meeting held at Hudson, which proved an exercising, searching time;
wherein an invitation was held forth to all ranks,
to come and join themselves to Christ Jesus, the free teacher of his people,
and to beware of false and hireling teachers.
In the afternoon finished visiting families.

"`29th and 30th.--Spent pretty much alone at our lodgings,
being much shut up as to any prospect of moving from this place with clearness;
find it safest to endeavour to stand still and wait to see what will turn up.`"

On the 3rd of the ensuing month, accompanied by several Friends, he went to New Britain;
on the 5th they were at Hoosack; on the 8th at the monthly meeting of East Hoosack,
and on the 10th at an appointed meeting at a settlement called White creek;
to which he says he "`went poor and distressed, and so remained for a time,
but Truth arose and a remnant was thankful we were together.`"

11th.--He says, "`we crossed a mountain, and arrived at our friend Stephen Rogers`',
and after resting a little went to meeting,
in which my heart was more enlarged than at any time since I left my home;
there appearing something lovely among these mountain people.
Returned with Stephen Rogers, where we met with several friendly seeking people,
with whom we had a solid time.
I showed them my certificate;
and the care and order of Friends in such cases were satisfactory to them,
having never seen the like before.
This has been a day to be remembered with reverence and humility,
under a sense of divine favour and love.
I had a good time with the family and several of the neighbours.

"`Ninth month 12th.--Our kind friend provided us
fresh horses to go forward to monthly meeting.
From about half-past one to near six o`'clock this day, we rode through a wilderness,
where we found but one path.
We were overtaken in this wilderness by a man, who from his appearance,
we judged to have been an under officer in the late war,
who was helpful in piloting us through to his house.
On the way I saw it to be my duty to show unto him the way of life and salvation,
and concluded I would leave it until we were likely to part, which would be time enough.
When we came up to his cottage in the wilderness, doubts and weakness so prevailed,
as to induce me to endeavour to pass him by; but on riding a few rods forward,
I found I must go back.
My dear companion, James Mott, told me afterwards, he was just going to say to me,
that if I had anything for that man, to be faithful and do it.
We turned back and went into the house,
where I found my mind concerned to declare the way of life to them.
Beside the man`'s wife, his aged father, who was deaf,
and his mother who was sick and in bed, were there, and also a brother and his wife,
and one or two young women.
I told them I had something to say to them if they would be silent and hear me.
The sick woman answered that they were not of my profession, and they knew enough.
I was grieved with her conduct, and told them I had freely offered,
and if they would not hear me, I should be clear;
and taking out the man who came with us, I opened my concern to him,
and also to some of the rest at the door, on parting.
I believe they were concerned at the old woman`'s behaviour,
and one of the young women appeared tender.
I was glad there was a little stir made among them,
although this act of duty might appear small.

"`13th.--To the meeting held at Daniel Hull`'s,
which was a good time among both Friends and others.
In the silent part I apprehended I felt the gospel of
Christ Jesus to flow over this wilderness land,
even to Canada; and after dinner had a baptizing time in a Friend`'s family,
wherein one of the children was spoken to particularly.

"`14th.--To meeting; a searching, but toward the close a good time,
and was glad I was there.
After meeting we had a baptizing time on parting from the family where we dined;
then rode to the river, three miles,
and crossed it in a boat which sunk in taking Friends over to last monthly meeting;
one of whom was drowned.

"`15th.--To Saratoga monthly meeting, and had a good time in the meeting for worship.
The meeting for discipline held until night.

"`16th.--After a tendering opportunity in the family where we lodged, set out for Hudson,
and attended the morning and afternoon meeting on the 18th.`"

On the 20th he visited David Sands, in whose family they had a solid opportunity.

"`On the 22nd reached James Mott`'s residence,
and went to the week-day meeting with the family,
and therein was employed in looking a little over my labours;
and although I feel poor and like an unprofitable servant,
nevertheless am favoured measurably with a reward of solid peace in looking back,
and feel easy to endeavour to be with my brethren at our yearly meeting.`"

Soon after this he went to New York, from which he proceeded homeward,
and arrived there on the 24th, as he says, in "`sweet peace.`"

In the eleventh month, 1786,
he made a religious visit to the quarterly meeting of Fairfax, in Virginia,
accompanied by his friend Charles Williams, a valued member of the same monthly meeting.
In relation to the quarterly meeting, he thus writes:
"`I have been favoured with an open door among
my friends during the time of the quarter,
and have occasion, with thankfulness of heart, to admire the goodness of the Lord,
who has a right to turn and overturn at his pleasure,
and who can change or alter the condition of men
as a man does the water course in the field.`"

He appears to have been detained in the neighbourhood of Fairfax,
visiting families and appointing meetings in this and some of the neighbouring villages,
in relation to which he says, under date of 18th of twelfth month:
"`My religious prospects are much closed up: have been working in a circle;
and am now at this place again, and see no way out.
Wait in patience, O my soul, for the further opening of duty,
seeing you have been enabled hitherto from place to place, to set up your Ebenezer.`"

Again, in a letter to his wife, under date of 19th of twelfth month:
"`In these parts I frequently have not seen my way but a few hours beforehand,
but as I am at times favoured to set up my Ebenezer, though led in a trying path,
I am encouraged to move on in the faith, and hope you have been and will continue to be,
favoured to partake of that precious reward which the Master gives his servants,
both those who go forth to battle and those that stay by the stuff.`"

Under date of 21st of twelfth month, he says: "`Went home with J. R.,
where we met with an open kind reception.
This man and wife, when I was here seven years ago with George Dillwyn and Samuel Emlen,
requested a religious opportunity in his family.
I am informed that in the beginning of our late troubles and war,
he was a captain of the militia, and led his men over the mountains against the Indians;
he is now a valuable member of Society,
and has offered to accompany me on my religious errand,
on the same rout over which years ago, he led forth his men to war.`"

On the 9th of the first month, 1787, he says:
"`A day of close exercise of mind yesterday,
because of so long confinement in this neighbourhood,
and no opening to any religious service.
I had a wakeful, thoughtful time last night.
Individuals in this neighbourhood are frequently brought into view,
but no clear prospect opens to visit them.

"`10th.--Attended the week-day meeting again at Fairfax, where, to my own humbling,
and I believe the comfort of others, we had a favoured time: the meeting is increasing;
it was small on our first coming here,
partly arising from an idle irreligious disposition,
and partly from the fear of getting the putrid sore throat, which has been prevalent.

"`11th.--We are yet detained in this neighbourhood; no way appears to move out,
and no clear prospect to proceed to a family visit.
Soul wait in patience, willingly disposed to do anything which may make for peace.

"`12th.--A pleasant scene opened the latter part of last night in my wakeful moments,
confirming me that I am in the way of my religious duty.
I had also an agreeable turn (mentally) into my own family and among my friends,
being enabled to put up a petition for them.`"
He visited a few families on this and the following day,
which were generally favoured opportunities,
and produced a feeling of peace and consolation to his mind.

On the 14th he again attended Fairfax meeting; in relation to it he says:
"`It was the largest we have been at here,
and I found much enlargement of heart to speak to various states;
there appears to be a precious visitation renewed to this people,
and I believe some are made truly sensible thereof.
I have found that my trials in this place have been for good,
and have seen the end of them,
even to baptize into a feeling sense of the state of this people.
What is revealed in secret in a time of mourning, in the night season as well as by day,
is afterward to be proclaimed as on the house-top.
I have found it good to wait and quietly hope for God`'s salvation;
for when the Messenger of the covenant appears at seasons, his work is before him;
for his work it is, and his precious reward he gives to his`' humbly devoted servants.
Trust in him, O my soul.`"

From the 14th to the 22nd, he was engaged in family visits to Friends and others,
in many of which he was qualified to speak to the
states of individuals in a remarkable manner.
In relation to one of the opportunities, he says, under date of 22nd:
"`Felt my mind exercised with something to say to a particular state present with us;
and remarked, in conclusion, that I was willing to wait for days, under probation,
dipping into the states of others, to find the way open and ability afforded to speak,
if it were to but one individual.
Among the little company was one who appeared much reached and tendered.`"

Another instance is thus related: "`After we had dined,
came in a young man whom I wanted to see,
from some feelings which had accompanied my mind at times, though he was much a stranger.
Frequently when I heard his name mentioned,
I thought it was likely I must go to Leesburg almost on purpose to see him.
After he came in among us, although I felt poor,
being thoughtful of my own trying circumstances, a weight of exercise came over me,
and we had a tendering baptizing time;
and by the account Friends gave me afterward of what he had been,
the thoughts of his heart were plainly told him by a stranger,
who knew nothing by outward information.
Thus am I detained in this neighbourhood, in a stripped and tried condition,
but not for naught;
so may thanksgiving be rendered by my tried soul
for past preservation under such dispensations,
and a dedicated mind lived in for time to come.`"

On the 28th of the month, he again remarks respecting the meeting at Fairfax:
"`I was silently exercised for some time with
the consideration of Saul`'s assuming to offer,
at the desire of the people, without the presence of Samuel;
and willingly resigned to wait until right ability was given.
I had to stand up in weakness, not clearly seeing what to open my mouth with,
yet we were once more favoured together,
and I ventured to conclude the meeting in supplication.`"

After this meeting he was released from further labour in this neighbourhood,
and felt his mind drawn to Redstone.
He started on the 30th, accompanied by several kind friends.
In the families of Friends on the way, and also at the meetings he attended,
he appears to have been favoured in his ministry,
and some of the opportunities he describes as being "`tendering seasons to many.`"

At that time when the most fertile parts of our widely
extended country were but thinly inhabited,
and the roads through them but little attended to,
a journey across the mountainous district which separates the
western from the eastern portion of Virginia and Maryland,
must have been lonely, if not hazardous.

To one constituted as he was, it must have been especially cheerless; he however,
appears to have been preserved in a resigned state of mind,
and favoured generally with a cheerful spirit.
On the 7th of the second month, at a tavern on the mountain,
they were much annoyed with some rude persons, who kept him awake much of the night:
"`As I lay,`" he observes, "`it was my concern to endeavour to get to my watch tower,
and examine how I had conducted since we crossed the Blue mountain,
being desirous to renew my acquaintance with the Lord my master,
who I believe had called me forth.`"

On the 10th of the second month he attended the monthly meeting held at Redstone,
and the next day, their first-day morning meeting,
in which he was silent and clothed with "`much peace of mind toward the latter part.`"

From a letter dated Redstone, second month 11th, 1787, the following extract is taken;

[.embedded-content-document.letter]
--

I got as far as this place on sixth-day evening last,
after a long and lonely ride over the Alleghany mountain.
I have been much favoured with health, and also,
to perform what I apprehended I was called unto, and some seasons of precious favour,
which have proved like seals of encouragement when under more trying circumstances,
have been mercifully afforded.
But for the most part, it has been my lot to travel along in a little and low state,
which I have believed to be a safe one.
I think I have also seen that those who come as far as this remote settlement,
had need to know their feet shod with the preparation of the gospel of peace.
I have experienced my faith to be tried,
and have had to look back and inquire what brought me here,
and have concluded it must have originated from best motives,
even love to the brethren--I remembered that
when under the chastening hand three years ago,
this place was opened before me, and I felt a willingness to set off then, if the Lord,
my heavenly master,
would be pleased to restore me to health of body and grant me peace and serenity of mind.
I trust at that time the will was taken for the deed;
and after a season He was graciously pleased to grant my
request and open the way for me to go to New England.
The visit I am now engaged in,
appears to me like endeavouring to fulfill my part of the
covenant entered into in a season of sore affliction,
and like performing my vows.

I think my lot may be a little compared (if so unworthy a
servant may so speak) to that of the prophet Ezekiel,
when he digged through the wall.
I do not find that it is expedient, at every meeting,
to open what it may be given me to see,--it has been so at this place,
having been at two public meetings, one of them the monthly meeting held yesterday,
and the other held to day, and have been silent in both.
Toward the close of that held this morning,
my mind was clothed with thankfulness in a full belief in the truth of those expressions;
'`To obey is better than sacrifice,
and to hearken than the fat of rams:`' I am desirous that I may be
favoured to conduct myself through the course of this journey,
so as to return to you again in peace.
My friends feel near to me, and I desire the help of their spirits,
having frequently had I to remember you, and your kind desire for me when parting.
I had not a prospect of staying so long when I set out,
but find it good for me to labour from time to time after a state of resignation,
having experienced in past journeyings, being favoured to return home in peace,
and this is my aim now, whether my absence be lengthened or not.

--

On the 13th, he says, "`exercised in mind this morning,
but was favoured with a good degree of resignation to my allotment,
nothing opening with clearness,
and was content to abide this day at our friend Reese
Cadwalader`'s. O! my weakness and blindness.`"

The next day he thus writes: "`a poor creature this morning, compassed with weakness;
I set off to a week-day meeting, about seven or eight miles distant,
on the other side of the river, called Dixon`'s meeting, and a miry road to travel.
We got to it however in time, where we found about fifteen or sixteen friends, men,
women and children,
collected in a little log cabin:--I sat the meeting through in silence,
and was favoured to drop a tear in resignation, not daring to put forth a hand to steal.

"`Attended Westland meeting, which came next in course:
I was closely exercised in humble silent waiting to know my Master`'s will concerning me;
and was favoured to drop my silent tears in resignation to my allotment;
the way appearing closed up as to any public communication among this people,
whom I have taken so much pains to come and see.`"

A striking trait in the character of this dear friend,
was the great care he manifested not to move in any religious engagement,
without satisfactory evidence of its being the will of
the great Master in whose service he was engaged.

This may account for the following remarks which he makes
about this time:--"`19th.--At a stand which way to move:
feel a willingness to go toward home if my divine Master pleases,
having f trust been concerned to act, so far, measurably in his counsel and will,
as made known to me a poor creature.`"

Upon conferring with some friends, he concluded to move on,
and prepared to cross the mountain, but after riding some distance into the woods,
all seemed to close up,
and it appeared most pleasant and easy to him to return
back to the friend`'s house from which they started;
where he says, "`I feel easy under this roof, and remember with instruction,
that when the cloud rested upon the tabernacle, Israel was to abide in their tents.
Laboured patiently to content ourselves here this night.`"

The next day he says, "`no way opens and the pain of my heart is not easily described;
but in all these laborious seasons how good it is to sink down
into that which endures the racing of the sea of affliction.
O! how am I tried with jealousy and fear that it
was not right to come across this mountain,
and no sufficient clearness can I find--wait in patience, O my soul, and reverently hope,
though it may be against hope, that your Saviour is not far from you;
believe him to be as in the '`sides of the ship.`'`"

Towards the close of the evening of this day he was favoured
with so much "`calm as to cause thankfulness to arise,
in that the bitter cup was a little sweetened, so retired to rest.`"

In the morning "`felt rather easier,`" and after breakfast sat down with the family,
among whom there appeared tenderness, and it being their week-day meeting at Redstone,
he attended it;--respecting which he says, "`another silent meeting,
in which my mind was deeply exercised;
and I was wrought into a willingness to leave this settlement,
and move on towards Hopewell; and while thus looking and thinking,
not knowing but that I should be clear--having
endeavoured to be found in the way of my duty,
as far as I could find it, this thought presented to my mind;
suppose I should have to return back from there or further, how then?
But even to this proving prospect I was resigned,
for the sake of my dear Master`'s owning presence,
and was ready to conclude it might be a sacrifice
called for at my hands to humble the instrument,
and for a sign to the people.
While these thoughts possessed my mind,
I was brought into a state wherein I could conclude on nothing,
and so was willing to become a blank; nevertheless,
at intervals under these provings of soul,
the states of my fellow professors seemed to be opening before
me--so broke up the meeting and lagged behind my companions,
and breathed forth my complaint unto God, desiring to be preserved in patience.

"`22nd.--Awoke this morning with fervent desires,
if the cause of this detention was in myself, that it might be searched out:
my youthful days, and days of vanity were brought up into remembrance,
and I found a willingness to look over the past days of my life,
from my very youth to this day.

"`Went to Westland meeting,
and therein was solemnly engaged in a continued deep search into my past life,
unto the present time;
and although blushing and confusion attended in the remembrance of past transactions,
mercy is with the Lord that he may be feared and served with dedication of heart,
'`Such were some of you,`' said the holy apostle.
What were some of them in that day?
Unthankful, unholy, disobedient to parents, covenant breakers,
and guilty of many other evils!
O that I had been more careful to keep my
covenants with the Lord my God in youthful days;
then had I escaped many of the evils which he mentions,
which came down upon me like a mighty stream.
But why does a living man complain; a man for the punishment of his sins?
may not my tried soul join company measurably with them to whom that servant also wrote,
and to whom he says '`such were some of you; but you are washed, but you are sanctified,
but you are justified in the name of the Lord Jesus, and by the spirit of our God.`'
Reverent thankfulness arose in my soul at the close of this meeting,
for sensible enlargement of heart, with a secret belief I am in my place;
so I ventured to tell friends after this sixth silent meeting of worship, (that is,
as to myself,) of what had weightily impressed my mind, which was,
with their approbation,
to assemble their children--and appoint a meeting for
them to be held next day but one after.`"

The next day being peaceful and easy in mind, he visited a family,
one of the members of which was sick.
He had a religious opportunity with them, and in the evening remarks:
"`a lonesome evening in the midst of company.`"

After a refreshing night`'s rest he says,
"`was measurably favoured with a calm this morning.
O! that I may be favoured to feel after and
discharge my religious duty among this people,
to the honour of truth and my soul`'s peace.
I went to the meeting appointed for the children,
feeling poor and in a stripped condition in the forepart of it,
and though I thought I dare not say much about it,
yet Friends concluded it was a favoured time.

"`The next day attended the first-day meeting at
Westland--went to it with my usual poverty;
so stripping a time with me in the forepart,
that I thought it likely we should have another silent meeting;
but feeling some little reviving of religious concern,
I laboured honestly in a close searching manner.
Found but little ease after this meeting, and my way being again much shut up,
conversation was as much so.
After dinner opened my mouth among the Friends present, and told them,
though some were ready to wonder at my being thus led,
I believed if I returned home without saying anything more,
my honest concern would have its use, and the Master could sanctify it,
and like bread cast on the waters, bring it up after many days,
when we were far from each other.
I also remarked that I was willing to move towards home,
if consistent with the divine will.
It was a broken, tendering time, and some dear Friends expressed sympathy with me.`"

He appointed a time to see the children of Friends together at Dixon`'s meeting,
and had an opportunity in the family of the Friend at whose house he stopped,
which "`appeared to be a time of brokenness of heart.`"
He observes: "`After breakfast, retired into the woods,
where I am now finishing these two days`' notes, with a thankful heart dedicated to God,
under a sense of his loving kindness and favour.`"

On the following morning he attended the meeting appointed for the children,
in which he was favoured,
and had renewed cause to believe it was in the
ordering of divine Wisdom that he appointed it.

On the 28th, he attended the week-day meeting, "`which,`" he says,
"`was a favoured opportunity, to the comfort and rejoicing of more than myself;
after which had a solid opportunity with Friends,
and felt refreshed and comforted in this day`'s labour.`"

On the 1st of the third month, he attended another meeting,
and was again shut up in silence.
"`There were some here not professing with us, to whom I felt a tenderness,
and after expressing a few words to turn their minds to the everlasting Father,
in whom there is no disappointment, even in silent meetings,
I requested they would leave Friends together and withdraw.
After this I relieved my mind in some degree in close labour with them;
directing all to a deep examination of themselves, as had been my concern,
to see what the cause was that it should be thus with them.
Little but barrenness have I felt among this people.
At the close appointed a meeting for the children,
to be held tomorrow at the eleventh hour.

"`Third month 2nd.--A refreshing night`'s sleep.
The meeting for children is coming on,
and what am I? O for the washing of water by the word.
Went to the meeting at the time appointed, under exercising discouraging thoughts,
and continued silently shut up until it appeared near time to break up,
when a concern arose in my mind to tell such of the elders or parents as were present,
what had been my employment in the meeting.
This was, to have my own heart searched,
and my desire remained that they might be found engaged in the same work.
After which I was turned toward the children,
and also in a particular manner toward a seeking state present, not of our Society,
unto whom I found considerable openness, and was informed after meeting,
that there were several of that number present; some who had left the Church of England,
and were now looking toward, or had joined the Methodists; and one seeking man,
who heard of this meeting,
rather chose to come to it than go to a marriage he was invited to.
With this day`'s labour I found peace, though trying in the beginning.

"`On the 3rd, attended another meeting for the children at Redstone,
in which I had an open time, which was cause of thankful rejoicing.`"
The next day after attending the regular meeting at Redstone,
which he describes as a laborious painful time, he returned to Reese Cadwalader`'s,
where he had the company of several Friends, among whom and the family, he remarks:
"`I was once more favoured to feel the spring of gospel ministry arise in such a manner,
as to water others and be refreshed myself.

"`5th.--Favoured with a good degree of serenity and peace of mind this morning,
under a sense that I have so far laboured to be found in the way of religious duty.`"

Charles Williams feeling released from further duty, left him; respecting which he says:
"`This morning I took an affectionate farewell of my tender-hearted companion,
who has gone toward home;
after which I laboured in retirement of mind to
feel after my divine Master`'s will concerning me.
O that I may be preserved under a solemn sense of the
importance of the business I am engaged in,
and that the good hand may accompany this dear youth to his parents and friends.
After dinner we went to C. G.`'s, and with him and family had a solid time.
I thought it was solemnly so,
and these expressions arose with weight and were delivered among them;
'`I counsel you to buy of me gold tried in the fire, that you may be rich;
and white raiment, that you may be clothed,
and that the shame of your nakedness do not appear; and anoint your eyes with eye salve,
that you may see.`'
From there went to P. G.`'s, where we had another searching religious opportunity.
My mind is often depressed under a sense of the low
state of things among the professors in our Society,
and I meet with various provings, in the manner in which I am led when abroad.

"`On the 7th attended their week-day and preparative meeting at Redstone;
a painful suffering time.
In the forepart thereof this language was uttered, '`Awake, arise you sleeper,
call upon your God, if happily he may save us.`'
I had some prospect in the morning of appointing
a meeting in the little town this evening;
but now it is gone.
There must be faith, love and desire, in hearers as well as preacher, to labour to profit.
This has been a dark and heavy day to my spirit.`"

On the 8th he visited the preparative meeting of Westland,
and had an opportunity with the children of a Friend in the neighbourhood,
and during the two next days was principally engaged in visiting families.

"`On the 11th, went to meeting, which, after some struggling and conflict,
was pretty open.
The people were exhorted to labour in all their
religious meetings to know the true place of waiting,
and to beg for their daily bread.
While speaking I met with a sudden stop in my mind as to the expression of more words,
and found it safest to sit down, and experienced peace in doing so.
After some time, the situation of Abraham and Lot,
with their being so mercifully delivered out of Sodom, very suddenly impressed my mind;
with which I stood up again and expressed,
that I dare not doubt that the good and great Remembrancer, or quick and powerful Word,
which is sharp and sharper than a two edged sword,
to the dividing between a man and his lovers, flesh and spirit,
influenced my heart to warn some to be content
with such things as they were favoured with;
reminding them of the annexed blessing:
'`I will never leave you nor forsake you;`'--and not indulge a roving disposition,
and leave their friends with whom they were so
favoured as to be embodied into a little Society;
and as they kept their places they would yet be favoured.
But if any should break through, and go contrary to the mind of concerned brethren,
and get several hundred miles off--if any unforeseen distress should come upon them,
how would it fare with them?
This little testimony appeared close and searching,
and I did not find my peace disturbed in delivering it.
Some Friends after meeting expressed their satisfaction therewith,
believing it would have a tendency to strengthen the hands of the honest labourers.
No way opens with clearness to leave this place;
and this evening felt so impressed with a sense of my own weakness and unworthiness,
that it led me into the fields to seek counsel of the Lord,
where I experienced a little quiet and calm, in a solitary situation.

"`12th.--A restless night,
under the painful thought that the flesh prevailed too much over me in one instance.
O what small things grieve a tender conscience!
May I be favoured to labour after more perfect victory,
and at present rest humbled under this petition; '`Lord forgive what is past,
and condescend to be near to help in future.`'`"

Although he was for some time considerably exercised as to what step to take,
he finally concluded to go homewards;
and had parting religious opportunities with several families and Friends;
in relation to one of which he thus writes, under date of 13th of the month.

"`Had a parting opportunity with this family,
which I hope will not be easily forgotten by us or them;
after which I found considerable ease of mind, and rode to Beesontown, twelve miles,
where we dined; and then collected this large family together, with some others,
and were favoured with a baptizing season.
My soul was bowed in supplication, and also in reverent thanksgiving,
to the gracious Author of my life and well being, who led me here,
and has preserved and fed me, and now is opening a door out,
to my solid peace and comfort.
Parted with dear Reese Cadwalader at this place;
and I thought the ancient language was measurably experienced by my thankful mind:
'`The wilderness and solitary place shall be glad for them,
and the desert shall rejoice and blossom as the rose.`'`"

In crossing the mountain they met with the usual
difficulties experienced by travellers at that period,
in consequence of the rugged character of the road,
and the poor accommodations both for man and horse, which they were obliged to submit to.
At the taverns, as well as on the road, when he believed it to be his duty,
he did not fail to exhort persons with whom he met, to flee from the error of their ways.
With respect to the scenery of the mountain,
with which he was much interested and gratified, he says:

"`Heard the sound of the frogs, denoting the approach of spring.
What harmony in the outward creation! nothing, however minute, was made in vain.
Even these creatures seem to be uttering thanks to the great Creator,
for the opening of a new season.
I was delighted with seeing the birds sporting themselves in the woods:
the voice of the turtle-dove was also to be heard,
and the husbandman was seen at the plough.
All this perhaps not more than fifteen miles from ice and snow.
It has been a day of solid thoughtfulness,
in meditation on the wonderful works of Providence.
When viewing the beautiful springs gushing from the sides of the hills,
among the rocks and stones,
I had to remember that '`springs were to be found even in the desert,
and fountains in high places.`'
Various landscapes opened one after another,
in viewing which I frequently found profitable employment on the road.
But over and above all, this day, and peculiarly so this afternoon,
was the fresh feeling and sense of the love of Christ my Lord and Master,
shed abroad in my heart, making it like spring time in a spiritual sense.
The remembrance of the poverty of spirit in which I
crossed this mountain about one month ago,
of my close exercises on the other side, of the preservation vouchsafed under them,
and how the way and time to return homewards, were set open so clearly before me,
brought feelings over my mind, in which that saying was measurably fulfilled;
'`He that goes forth and weeps, bearing precious seed,
shall return again bringing his sheaves with him.`'
My mind was bowed in reverent thankfulness,
and many passages of Scripture were opened to my understanding,
wherein I was measurably favoured with a taste of the
same experience which holy men of old spoke of.
This made it feel like a spring time indeed,
the wintry season of trials and close provings being for a moment past and hid,
and the singing of birds heard, as also the voice of the turtle spiritually.
My dear family and some of my friends were brought feelingly into remembrance,
and as I had been engaged for the good of the children of others,
so now my desires and my prayers have been put up to my gracious Redeemer,
that he would look down and remember mine.
May I still be engaged to give up in the littleness and weakness, but in the faith,
to follow my Lord and Saviour Jesus Christ,
who is abundantly able out of weakness to make strong.`"

On the 17th, after having been kindly entertained at a Friend`'s house,
who since they passed that way before, had experienced considerable affliction, he says:
"`I remembered when about to leave this house on our outset, I ventured,
on my bended knees, to supplicate my dear Lord to go with us,
as he did with his poor prophet formerly, whom he caused the ravens to feed;
and now considering how he had preserved and brought me back again in peace,
and had so eminently visited this family,
my mouth was again unexpectedly opened to express the grateful sense received,
and to pray for further preservation;
which proved a tendering time I believe to most present.`"

After attending Centre meeting, in which he had to set an example of silence,
for which he remarks, he thought there was cause,
he felt a drawing to visit an individual and her father, who were Methodists,
where it appears he lodged and was hospitably entertained.
"`In the morning,`" he says, "`family duty was performed before we were out of bed.
When we were about setting down to breakfast, grace was said by the master,
as was last evening; and my heart being exercised in a thoughtful concern for them,
I kept my standing, and after a season kneeled down in supplication;
after which I found peace to flow as to my own particular.
Breakfast being ended, the daughter expressed something in a low voice,
like giving thanks for benefits received; and being about to leave them,
I requested a silent opportunity, when I was favoured I trust,
to declare my exercise faithfully: some tenderness appeared,
and the religiously minded woman on parting, desired the Lord might bless me.`"

From the 20th to the 30th of the third month,
he was detained in the neighbourhood of Fairfax, visiting meetings,
and also many of the families composing them.
On the 29th he says, "`he went to M. J.`'s,
in order to get ready to leave this settlement in the morning;
the way and time seem to be opening.
I trust all my debts here are nearly paid,
and may I not stay one hour longer than the precious oil which is due to others,
is experienced to run.`"

On the 31st, he proceeded some distance toward home, which he says, "`looked pleasant,
but at the same time I felt a care of indulging
the prospect of reaching it in a few days.`"
A concern arose in the evening to visit Pipe and Bush creek meetings,
which had been hid for some days previous.
This, he remarks, would be work enough for six or eight weeks more,
and having no steady companion, his beast lame,
and "`the instrument poor and empty,`" he was introduced into much exercise.
The next day he attended two meetings,
in which he was favoured to labour to the ease of his own mind
and to the encouragement and comfort of some others;
yet he thus writes: "`What a poor creature I am this evening: my enemy is very near,
and has been labouring to cause me to break rank.

How careful should gospel ministers be--those who make use of such exalted language
as is at times put into their mouths--to keep their bodies in subjection,
lest they be caught in the snares of the wicked one, and after such high favour,
become cast-aways.
Went to bed under exercise; my way closed up.`"

For some time his way continued hedged up, and under deep exercise he thus writes:
"`Dearest Lord, have I not given up to be your servant?
lead, O lead and guide me in the way I should go.
If there be anything more for me to do, baptize and fit me for the service,
and if there is no more, be pleased to preserve your servant,
and bring him in safety to his outward habitation;
for you can abundantly bless all them that love you.`"

On the 5th, he attended the meeting at Bush Creek,
in which he had an open satisfactory opportunity;
on the 7th the monthly meeting of Warrington, which he sat almost through in silence,
but near the close these expressions impressed his mind to deliver;
"`it is a precious thing to be found a learner in that school,
wherein Jesus Christ presides as the heavenly teacher;
and where this lesson is to be learnt, '`not my will, O Father,
but yours be done;`' it is a lesson I found necessary for me to learn,
and I had peace in dropping the same.`"

Soon after he was permitted to turn his face homeward again, and arrived in York,
Pennsylvania, on the 10th, where he writes:

"`It has been a proving dispensation since I left this place;
somewhat resembling my outward journey over the mountains,
where a place called '`the shades of death,`' is to be
passed through on the way to a beautiful prospect,
from the mountain over the good land!
O, that I may be favoured with renewed faith and patience;
and experience a returning home in peace, when this religious pilgrimage is fully over,
to the honour of the great Master;
who knows best how to break the spirits of his servants,
and fit them for the reception of himself in his
blessed appearance of sweetening encouraging love.`"

Having been considerably indisposed, he stayed a day or two at York to recover his health;
and Peter Yarnall having offered to accompany him to Lancaster,
where he understood John Townsend, a ministering friend from England expected to be,
they started for that place on the 13th. But on the 14th,
he believed it to be his duty to return and visit
Monallen meeting and some others in the neighbourhood,
though he says, "`with very little prospect of any good resulting,
unless for his own mortification.`"

He visited these meetings, and found in one at least there was cause for his returning.
He had the company of his elder brother John Townsend,
who proved to be a sympathizing father and encourager to him, and he remarks,
"`it was a peculiar satisfaction to find we have been
led so much alike in religious communication.`"

On the 19th after attending Monallen meeting, he says: "`I find much relief,
and it appeared as though my release from more religious service was near;
my mind being turned toward my own residence.`"

On the 20th he set off, and at the ferry over the Susquehannah,
he says he felt his mind religiously concerned to caution and advise the innkeeper,
which he accepted kindly,
and he was also engaged to reprove the ferry men for their vanity and swearing,
to which they seemed to listen with attention.
O! how many poor abandoned creatures there are up and down,
who are drinking in sin and iniquity as an ox drinks water.`"

On the 21st of fourth month, 1787, after an absence of nearly five months,
he was permitted to return to his family and friends with "`the sweet reward of peace.`"

On the 27th of the eleventh month, 1788, he again left his family and friends,
with the approbation of his monthly meeting;
on the 28th attended the youths`' meeting at Middletown, Bucks county, Pennsylvania;
on the 30th Plumstead meeting and taking Buckingham monthly meeting,
Wrightstown and Falls meetings, he crossed the river to Burlington,
and on the 7th of twelfth month had a meeting for the inhabitants of his native city,
which was large, and thought to be a solid good time.

On the 8th he attended an appointed meeting at Mansfield neck,
and the next day their monthly meeting, and being joined by John Hoskins and John Cox,
they were at meetings at Vincentown, Mount Holly, and Upper Springfield.

On the 16th he says: "`had a solid time with the widow Newbold`'s family,
and then went to see a young man, about twenty-five years of age,
with a lovely wife and child, who lies ill in consequence of a fall from a horse,
which he was running on the afternoon of the last youths`' meeting at Crosswicks.
He left home on business, but attended the meeting,
which I have understood was a favoured time,
and from there he went to a tavern and got among some
company who induced him to join them,
against his judgment and inclination,
and at last persuaded him to run his horse against one of theirs.
As he was doing so, he was knocked off the horse by striking a tree,
and was taken up for dead, and has been in a deplorable condition for three weeks past.`"

On the 17th attended Mansfield meeting in a stripped condition;
on the 18th shut up as to any prospect, so remained at C. Newbold`'s,
our kind friend John Cox remaining with us in sympathy.

"`21st.--Learned that the young man above alluded to was still alive,
and expressed some concern that I did not come to see him; so concluded to do so,
and found him sensible; I laboured in the ability given for his everlasting welfare,
and he expressed his satisfaction and thankfulness for the visit.

"`22nd.--This morning received an account that L. N., the before-mentioned young man,
deceased last night.
Went after breakfast to see J. F., who lay in a sorrowful condition,
and then to another family who had kindly invited us.
After we had dined and were about sitting down together in a religious way,
Daniel Offley came in; which put me to some trial, but I found there was no time to lose,
and my beloved brother, Daniel Offley, soon perceived what was going forward,
and proved a fellow-helper.
The next day attended the funeral of the young man, and held a meeting on the occasion,
in which D. Offley was a fellow-labourer.
Then I found a liberty gently opening in my heart,
but in much weakness and fear to appoint meetings forwards.
I called to see the poor afflicted widow who did not go to the funeral;
and returned to M. Newbold`'s, peaceful and easy,
being now favoured to see the end of my detention and trials in this neighbourhood,
and hope the aforesaid meeting was a solemn time of warning and caution to numbers.
My heart is thankful to the Lord for his merciful preservation in patience.

"`On the 24th attended a meeting appointed at Bordentown,
and on the 25th at a large meeting at Crosswicks,
where my Lord and Master favoured me with strength to relieve my soul fully;
having in the course of religious communication to revive the
melancholy circumstance of the poor young man before recited.
After dinner visited the tavern keeper and wife, near by where the race was run,
and then to Nathan Wright`'s, where we were affectionately received and owned.

"`26th.--To Arneytown meeting, which was large, but a very exercising time to me.
As we were riding towards Nathan Wright`'s, about one mile from meeting,
over a very rough road, my mare fell down and threw me over her head,
but through preserving mercy and care I received not much hurt.
For which favour, as soon as I was a little recovered from such a sudden surprise,
I found reverent thankfulness to spring up in my heart,
unto the upholder and preserver of his creature man.
Spent this evening at Nathan Wright`'s,
partly in a solid religious opportunity with this family, and some others present,
I hope to profit.`"

After attending meetings at Robins`', Shrewsbury, Freehold and Trenton, he writes:

"`First month 1st,
1789.--Awoke this morning with renewed desire to be found walking in the way of my duty,
and that it might be as the day of a fresh setting out
under the guidance of the heavenly pilot,
Christ Jesus.
Was also favoured with some precious openings in regard to my present journey;
went to meeting at the time appointed,--my companion,
I thought had something lively to offer, but found it my business to sit silent,
in which I was favoured with renewed satisfaction and comfort;
yet on the close was not easy without appointing
another meeting at six o`'clock this evening,
desiring such as were with us to come again, and also to invite their absent neighbours.
Went to meeting at the time appointed, which was pretty full,
and trust it proved a solid baptising time.`"

Went to Burlington,
and on the 4th opened in their monthly meeting a prospect of visiting in their families,
all the inhabitants of the town who were willing to receive him,
which being solidly considered,
some Friends were appointed to accompany him--John Cox offering himself a volunteer.
From this time until the 6th of the second month, was spent in accomplishing the service;
after which, accompanied by John Cox, went to the Falls, and from there to Makefield,
Wrightstown, Kingwood, Hardwich, and Mendham; from there to Plainfield, Rahway,
Stony Brook, and through Trenton to Burlington quarterly meeting.
After this he returned to his own home with sheaves of peace in his bosom--and adds,
"`may the Lord, the helper of Israel, be praised.`"
