== Chapter III.

In the summer of this year he again left home in the service of his divine Master,
being engaged to pay a visit in gospel love to some meetings in New York,
and on Long Island, in which engagement he had the company of his friend John Cox.
After attending a number of meetings on Long Island,
he was at Oyster Bay on the 26th of seventh month,
which was a solemn and profitable season,
as was also a religious opportunity in a family: he remarks,
"`here it may not be unprofitable to record the mercy
and goodness of the Lord to his devoted children,
who at times is pleased to make them helpful one to another,
and encouragers of one another when favoured of Him.`"

He attended the quarterly meetings at Purchase and at Flushing,
and also the monthly meeting at the latter place,
at which were a number of Friends appointed by the quarter,
and it proved a strengthening and comforting season,
wherein they were enabled to thank God and take courage.
They soon after returned to the city of New York, where they met with Rebecca Jones,
and the following memorandum occurs:

"`Eighth month 9th.--Attended the meetings in New York,
wherein my elder sister Rebecca Jones had a large share of public service,
and I also had some labour, which afforded satisfaction and peace to myself.

"`12th.--Went to the week-day meeting at New York,
accompanied by a friend who had been low in his mind,
and had not been at meeting for upwards of six years.
It proved a good meeting to more than myself, and in the evening,
to the great comfort of his relations,
prevailed on the above mentioned friend to return to his lovely family,
from whom he has been absent several years.
When I was here four years ago, I was concerned to visit this poor disconsolate man,
and on bended knees to pray for him.
I also went to see his wife and children, and in an opportunity with them,
had to express my prospect, that the time of deliverance from this affliction would come,
and perhaps was not afar off; and it has been strengthening and encouraging to me now,
to see him again restored to his family, and in his right mind.`"

[.offset]
On the 14th he left New York,
and the 15th and 16th he attended the quarterly meeting at Rahway,
in company with Rebecca Jones and M. Robinson;
after which the following memorandum occurs:

"`17th.--A very large meeting, and a great mixture of different sorts of people,
many of whom could not get into the house.
I believed it my place to stand forth amongst them with a heart much exercised,
on account of the looser sort, not only amongst Friends, but of all ranks.
I was led to caution and warn the unwary and frolicksome youth,
and to tell them of the circumstance of the young man who was killed at a horse race;
remarking that the Almighty warned his creatures in various ways,
sometimes by night in dreams and visions as Job says; and sometimes by day also.
After this our dear friend Rebecca Jones, was favoured in a large testimony,
chiefly to Friends; and at the close of the meeting when about to part,
I had again to stand up, and warn the youth in a particular manner,
that they should return from the meeting home,
under a thankful sense of the favours received, and keep out of lightness and frolicking.

"`On the 18th was a large meeting, wherein there was acceptable service;
we had the company of our dear friend Joseph Delaplaine, of New York,
whom I felt near to my life in inward labour, although silent.

"`19th.--Went to Plainfield monthly meeting, accompanied by my friend James Whitall,
who has been with me during the time of Rahway quarterly meeting.
Rebecca Jones and John Cox stayed at Rahway poorly, not venturing out in the rain.
I think we had a favoured good meeting at Plainfield, and then returned to Rahway.`"

[.offset]
In a letter to a friend, dated Rahway, eighth month, 1789, he says:

[.embedded-content-document.letter]
--

I thought I would send you a few lines by the bearer hereof, E. R.,
who attended Plainfield monthly meeting yesterday with his offering.
I was glad for E.`'s sake that I was there, and thought there was a solid weight attended.
Friends readily received him into membership,
and a certificate to our meeting is to be prepared, to be produced next month.
I thought it would be satisfactory to hear this much,
and a little also of what your poor and often enfeebled brother has been about.
I went no further than Purchase quarterly meeting, about thirty miles above New York.
Finding that Nine Partners quarter was held the same week as this at Rahway,
I was easy to cross to Long Island again.
I was much shut up and exercised in that Island,
but favoured to come away easy and peaceful, and my visit to friends in New York,
as to myself, has been the most peaceful and pleasant of any time I have been there.

My companion John Cox, sets off presently in company with E. R.,
and I have James Whitall of Woodbury with me;
he came with a minute from their monthly meeting,
to see me round within the compass of their quarter; but here I am this morning,
as frequently is my lot, a poor blind servant, waiting for future direction,
seeing no way to move with sufficient clearness.
I have been favoured with the acceptable company of our dear Rebecca Jones,
both at New York and in this place, which has been strengthening to me.

--

"`20th.--John Cox left us pretty early;--some time after which dear M. Robinson,
J+++.+++ Delaplaine, and other friends from New York, being ready to return,
we sat down together and were favoured with a precious season.
After parting with so many near friends, my mind was tenderly affected,
and gathered into a quiet habitation,
wherein it was nearly turned toward my beloved help-mate in life.

"`On the 21st, Rebecca Jones left in company with Joseph Shotwell;
and after they were gone my mind was thoughtfully engaged to
know for what end I was thus left as it were alone;
and all prospect of religious service removed.
I had laboured fervently during the time of the quarterly meeting,
and had thoughts of appointing a meeting on Staten Island, but that was removed,
and here I was left, a poor blind exercised servant;
and was sunk under such a weight of exercise,
that I thought of going up to lay on my bed.
While sitting in this exercised condition,
James Shotwell came into the room where I and my companion James Whitall were sitting,
and informed us that a sorrowful circumstance had happened;
a number of young people going into the water at Sandy Hook were drowned,
and the bodies of four young women were just brought up in the shallop they went out in.
We walked down to the landing, and there saw them lying on straw on the deck,
side by side, and a very serious sight it was.
After we returned home to James Shotwell`'s, I was soon informed by my blessed guide,
there was more work for me to do in this place,
and I was strengthened to desire Friends to go
to the houses of the relatives of the deceased,
most of whom it was expected would be laid in Friends`' ground,
and make way for a meeting after the burial, which they did,
and it was concluded to bury them all in one grave in Friends`' ground;
and there being a burial this afternoon of a young woman of the Presbyterian Society,
who died of a putrid fever, and some Friends attending it,
gave notice of the burial tomorrow.
I went to the house of a relation of one of the persons drowned,
where we had a humbling time amongst a number of the relations and others,
who escaped the jaws of death.

"`22nd.--Went to the burial, which was a solemn scene:
such a grave I never saw before--wide enough to lay the
bodies of these poor young women side by side,
who but a few days before were mostly in full health and strength,
and most or all of them at meeting.
Solemn it was to see the coffins one by one, brought into the grave yard.
We went into meeting, which was made up of various ranks and classes of men and women,
the passages filled up with those who stood, and many out of doors who could not get in.
I had a laborious time amongst them, but trust, through divine help,
the free and everlasting gospel was preached, and truth not dishonoured.
The people behaved quietly, considering the great throng.
It was a relieving time to me, although spending to the body;
but the Lord can help and does help his poor servants in the needful time:
praised be his name,
and may the mouths of the servants be kept as in the dust before him.`"

[.offset]
The following account of this mournful event, is furnished by another hand:

[quote]
____
"`At our last quarterly meeting, our beloved friend Thomas Scattergood,
in the course of his public testimony, in moving language,
warned the youth present to beware of loose behaviour, dancing, frolicking, etc.;
stating,
that he had known several instances of divine
displeasure being manifested to individuals,
who had attended such meetings as these, and directly afterwards had gone to horse races,
or other sinful pastimes.
One instance he mentioned, of a young man, who, on his way home from a favoured meeting,
falling in with a company of persons who were collected for a horse race;
they urged him to ride one of the horses--he at first refused,
but being pressed by some of them, at length yielded;
and in the race was thrown from the horse, which occasioned his death.
He said it appeared to be his business to warn the youth present,
to beware of such conduct, lest some of them might be made like examples.
'`I do not say,`' said he, '`it will be the case,
but I find it my place to proclaim a solemn warning.`'`"

"`On third-day our meeting ended:--twenty-seven persons, chiefly young people,
embarked on board a boat, bound for Sandy Hook; but before they set off,
it was observed that several of them were discouraged, and ready to give it up;
and on their way it was remarked, how dreadful it would be,
if any unfavourable accident should happen, after having been at meeting,
and hearing the advice then given.
On fourth-day they went to view a monument erected over a person of distinction,
who with twelve others perished there not long before.
On fifth-day, they walked to the light-house,
and on their return went on a narrow reef of sand, which is bare at low water,
as also the way to it; on this they spent some time in walking, etc.
At length, observing the tide to run fast, they were alarmed and concluded to return.
But alas! the sea had hidden their path, and covered all their way-marks!
However, they made the attempt, and as they were pressing on,
eleven of them suddenly stepped into the deep, were overwhelmed as in a moment,
and seven of them perished.
The others, with the assistance of some of the company who could swim, got to the shore,
though almost spent.
Four of the bodies were found, and brought up here +++[+++Rahway,]
on sixth-day.
The next day was appointed tor their interment, and notice being given,
a great concourse of people attended; after which a meeting was held,
wherein our beloved friend Thomas Scattergood was enabled to preach the gospel,
pertinently to exhort all present to profit by the present calamity,
and feelingly to impart a portion of consolation
to those who drank largely of sorrow`'s streams.
He had not felt easy to return home after our quarterly meeting ended;
but waiting in great exercise of mind,
was not able to discover the cause of his being thus detained.
On sixth-day morning, he retired into a private room,
and sitting a while under the like pressure of exercise,
a messenger stepped in with the foregoing sorrowful tidings.
Then he could account for the trying dispensation he had passed through,
which he related in his discourse to the crowded audience,
observing that it might be said of him as of Nehemiah, '`why are you sad,
seeing you are not sick?`'
'`I was not sick,`' said he, '`but felt such oppression of exercise,
that I thought of taking my bed.`'`"
____

"`23rd.--Attended two pretty large meetings in Rahway--had large open service in them;
and in the evening went to visit the afflicted widow of +++_______+++, who perished,
and is not yet found: here we met with a number of neighbours,
and it was I hope a humbling awful time, which will be remembered,
and the poor widow I trust, was somewhat strengthened and encouraged.`"

After holding a meeting on Staten Island, he again attended Rahway meeting on the 25th,
and proceeded to Stony Brook, where he appointed a meeting the next day,
in which he was silent; from there he went to Trenton, where a meeting was held,
in which he says, "`I hope we were favoured to offer an acceptable evening sacrifice.`"

[.offset]
After this he attended Bucks quarterly meeting, and went to Burlington,
where he remained visiting the meetings as they came in course,
until the 4th of the ninth month. On the 3rd he thus writes:

"`Attended the week-day meeting in Burlington,
in which my mind was very particularly turned to speak to the state of an individual,
who appeared to me to be present; and next day I met with a person,
whom I knew not was at meeting, but he acknowledged frankly,
that he was the person thus spoken to, and hoped he should be favoured to improve by it.
This was cause of renewed encouragement to me,
it having been trying thus to be detained in this place.

"`Ninth month 5th.--To Joseph Shotwell`'s at Rahway,
and feel myself a poor exercised servant, not knowing for what I came here again,
but am favoured with peace of mind,
the great blessing promised by our Lord himself to his devoted followers:
soul wait in patience.
On first-day, the 6th, I attended two large meetings,
and in the close of the day was made thankfully to rejoice.
On the 7th appointed a meeting for those of other religious denominations,
and which was a laborious one to me.

"`On the 9th went to Plainfield meeting, which was also laborious.
On the 10th to a large and favoured meeting at Rahway.
On the 11th to an appointed meeting at Elizabeth Town,
Here we had some of the heads of the people, and hope this meeting was to some profit:
the governor being at it, kindly invited me to go home with him and was very friendly.
Dined with a friendly tavern-keeper, who with much affection, entertained a number of us,
and after dinner we were favoured to partake together
of a measure of that which exceeds outward bread.

"`On the 12th attended an appointed meeting in the court-house at Amboy, which was large,
and I thought a solid good time.
Had an exercising time at the tavern where we left our horses;
thanks be to him who is ever worthy,
for the strength vouchsafed to relieve my mind
amongst a company of wild youth and others;
and O the thankfulness of heart I now feel,
under a sense of the Lord`'s goodness in thus preserving me
through this one more weighty and arduous week`'s work.

"`Ninth month 13th.--Attended two large meetings in Rahway;
and in the morning was favoured, I thought,
with much strength and ease to unburden my mind; but that in the afternoon was laborious.
A large number of Friends came to our lodgings in the evening,
and hope it proved an opportunity to be remembered in a future day by some of us.
My soul desires to lay prostrate before the Lord,
that I may do nothing to mar his blessed work,--
feeling much jealousy and fear on my own account:
ever keep your poor servant, O Lord, in a sense that you are good and I myself am blind.

"`15th.--Went to an appointed meeting held at Newark court-house; which was large,
and appeared to be to general satisfaction;
it being the time of the sitting of the court,
the judges were so respectful and kind as to adjourn to
a public house to accommodate the meeting,
and several of the lawyers came to it.

"`16th.--To an appointed meeting at a place called Westfield,
where there never had been a Friends`' meeting; it was held at the house of Dr. Elmore,
who not only opened his house, but we had reason to believe his heart also was opened,
and it proved a time to general satisfaction: the priest of the place attended,
and in the presence of a number of his hearers owned the doctrine delivered.

"`On the 17th to the monthly meeting at Rahway, which proved an open comforting time.

"`18th.--Waiting to see with clearness which way to
move--feeling much peace and comfort on looking back,
and remembering the supporting hand of the Lord that has been with me
and upheld in the arduous labours in and around this place.
'`I will thank you for your mercies past,
and humbly hope for more.`'`" After this he
returned through New Brunswick and Stony Brook,
and reached his residence on the 21st, in peace, for which he says,
"`Thanks be to him who is ever worthy thereof.`"

[.small-break]
'''

From the 22nd of the ninth month to the 11th of the tenth month, he spent at home,
attending the yearly meeting and looking after his outward affairs.

From the 11th of tenth month to the 18th of the eleventh month,
he was engaged in visiting the meetings belonging to
Haddonfield and Woodbury quarterly meetings,
and between this and tenth month 1791,
performed several little journeys to quarterly meetings.

In the tenth month 1791, accompanied by his friend John Pemberton,
he visited Shrewsbury quarterly meeting,
and a number of families at a place called the Branch;
and in the latter end of the first month 1792,
again attended Shrewsbury quarterly meeting and visited
a number more families at Deal and Poplar Swamp,
and appointed several meetings in and about that neighbourhood.
He then parted from John Pemberton, and taking the monthly meetings in his way,
beginning at Upper Springfield, went as far as Cohansey;
in which journey he met with some singular occurrences,
as often heretofore "`through which,`" says he,
"`the Lord supported my exercised soul unto the end,
and favoured me to get home to my family in peace.
I went forth weeping and in great strippedness and poverty,
and yet was favoured to discharge my religious duty in such a manner,
as to return with sweet peace.
O Lord, my gracious helper, favour me still in my passage through life,
with your light to enlighten and guide my steps.
Returned home on 3rd day of third month 1792.`"

[.offset]
Extracts from a letter written while on this journey to his family, dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Poplar Swamp, second month 4th, 1792.

I left you in great weakness as I expressed and my going forth was I knew not where,
and to receive the inheritance of peace, I knew not when.
I have rejoiced heretofore in sitting down with you,
and parting under a solemn covering of divine love,--
but at this time I saw little but to go forth,
and so I left my home, committing you all, with myself,
to the keeping of the good Shepherd, who puts his servants forth and goes before them,
and provides all things convenient,--and all this in faith,
without much prospect of service.
I received a small portion of encouragement in a parting opportunity at James Thornton`'s;
on taking a view of his diligent labours in the gospel in younger life, when of ability,
who now is rendered unfit for travelling by infirmity of body;
in the revival of those expressions of a primitive
labourer in the same blessed work and calling;
'`Our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom,
but by the grace of God we have had our conduct in the world.`'
Very simple, poor and destitute I often felt while with you,
when weaning from the breast of this world,
and preparing to leave all that is near and dear in life,
to follow the leadings of that good hand, which has, in adorable mercy,
plucked me as a brand from the burning;
and redeemed my soul from the pit of destruction and misery.
When I am thus separated from you, fervent have been the desires of my soul,
that he who leads his poor servants forth to war a good warfare, under his safe-conduct,
may be with those who stay by the stuff.

--

[.offset]
Extract from a letter to Hannah Cathrall, dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
John Wistar`'s, Salem, N. J., second month 23rd, 1792.

I received your encouraging lines this afternoon on
my way from Alloway`'s Creek to this place,
and thought I would inform you how acceptable they were to me,
a poor exercised traveller.
They brought into remembrance your sympathy with me while I was in New England,
at a time when I thought I stood in need of such remembrance.
My path is singular when abroad, and with reverent thankfulness I may acknowledge,
that strength has been graciously afforded me in every trying and
needful season,--and some such I have met with in this journey.
I left my own habitation very poor in mind--indeed I felt in
this condition when my friends set me at liberty,
and could but admire at the cheerfulness which appeared in some minds to do so.

I do not recollect that any testimony of approbation which dropped
from the lips of any of my dear friends in that low season,
has proved more of a refreshing cordial,
than a few expressions which were uttered by dear E. H. What a small portion of bread,
if really bread, and sanctified and blessed, is truly nourishing and refreshing.

Therefore, beloved sister, there is abundant reason for humble hope,
that in present provings and succeeding conflicts,
he who is Lord in Zion will furnish the necessary qualification.
Be therefore strong, let not your hands be slack.
How often have I wished that strength might be the girdle of your exercised mind,
with respect to the fulfilment of your duty in the line
of the ministry of peace and reconciliation.
Do you not undoubtedly believe that a gift,
received from the great and bountiful Giver of all good and perfect gifts,
will prosper in every turning of it?
O then, dear friend, let us follow it closer; let us say with devotion of heart,
'`draw me and I will run after you,`' not waiting for great manifestations,
or tempting our divine Master with saying '`show
us a sign,`'--but rather let our language be,
only condescend to show me that the requiring is from you, the Lord my God,
my heavenly Prophet, and I will follow you whithersoever you are pleased to lead.
May you be the companion of such as these.
How many are there up and down in the land, who would rejoice and be refreshed,
in the exercise of that precious gift and talent conferred on you,
my sister,--therefore let not him who brings in strong reasonings,
have place for a moment;
but exercise that faith which removes mountains out of
the way--making them at times to skip like rams,
and the little hills like lambs, that thus we may do our day`'s work in the day time.

--
