== Chapter IV.

[.chapter-synopsis]
* Visit to the Southern States.

His mind having been exercised with a prospect of paying a
religious visit to Friends and others in the southern states,
in the fourth month 1792,
he obtained certificates of the unity of his monthly and quarterly meeting,
and soon after proceeded to perform it.
From the memorandums made during the journey, the following are extracted:

[.small-break]
'''

"`Fifth month 20th, 1792.--Left my habitation,
after first sitting down and being favoured with a comfortable
opportunity with my family and several Friends,
who came to take leave of me,
and accompanied by a number of Friends went to the house of my companion,
Josiah Bunting at Darby, and attended that meeting, which proved a strengthening one.

"`21st.--This morning sat down with a number of Friends,
and were favoured with another confirming opportunity,
and a sense that we were in the line of divine appointment.
22nd.--To the youths`' meeting at London Grove and lodged at Joshua
Pusey`'s. Here we met with our dear friend Sarah Harrison,
from whom we parted in near regard,
not expecting to see each other again for a considerable length of time,
she being shortly to embark for England.`"
He then attended Sadsbury monthly meeting, meetings at Yorktown,
and the quarterly meeting at Pipe Creek;--"`in all which,`" says he,
"`I was favoured with something to communicate;
and it has been a time of humiliation with me since I left
home--feeling a strong current of affection at times prevalent,
toward those I have left there, and the length of my present journey closely affecting;
but the Lord is good and bears up my spirit.

"`30th.--To the week-day meeting at this place, wherein I was led in an encouraging line,
particularly to the youth.

"`31st.--To Bush Creek meeting which was large,
and a number of other societies collected,
to whom my mind was drawn forth in gospel love.
Sixth month 1st.--To Fairfax, stopping by the way at Richard Richardson`'s,
and while sitting with them,
I had to look back and remember the time I was
there with Samuel Emlen and George Dillwyn,
and the deep sorrow I waded under; but this was a different dispensation,
wherein Jacob`'s acknowledgment, through adorable mercy was mine, and I had to mention it,
'`The Lord was in this place and I knew it not.`'

"`3rd.--To Fairfax meeting,
and although it was silent throughout, and painful and exercising in the forepart,
the latter part thereof was a sweet time of renewing my own strength,
wherein my dear wife and family, and very particularly my dear aged mother,
were brought into remembrance with fervent prayer on her account;
and the length and breadth of the land was opened before me,
with animating strength of mind to follow my great and good Shepherd.`"

[.offset]
Extract of a letter dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fairfax, sixth month 4th, 1792.

I have not doubted the fitness of my leaving home,
neither the time nor the getting along so far,
although I travel in the usual poverty and blindness from day to day;
yet am at seasons comforted in the hope of being favoured to journey forward,
so as to secure the best of treasures, which is peace.
It is not the largeness of the offering, neither thousands of rams,
nor ten thousands of rivers of oil; it is not barely giving the first born,
or surrendering wife and children and all, but continuing in the Lord`'s will,
subjectly given up thereto, from day to day, which I have found to be my sanctification.
May the same good hand which has led forth and preserved me in a state of resignation,
be with you my dear companion, and support and succour in the needful time.
My heart at seasons when looking toward my dear family has been broken within me,
and secret breathings have arisen to the Strength of Israel,
for your protection and help as for my own, in this widely extended journey.

--

"`6th.--To South Fork meeting; the house could not hold near all the people,
and though there appeared much rawness,
yet strength was given to preach the word to some good effect, and we left them in peace.

"`7th.--To Goose Creek meeting, which was an arousing searching time, and I had peace.

"`9th.--To the quarterly meeting of ministers and elders, which was a close time,
but was favoured with peace.
10th, first-day.--Had an open good meeting,
as was also the meeting for business on the 11th. 12th.--The youths`' meeting was large,
and an open relieving time to me.
I believe the Lord, who is worthy of all praise,
was near with a visitation of love to the people.
Visited a number of families here, and was at their weekday meeting,
which was an exercising time, under a sense of the low state of things,
but strength was afforded, after a time of waiting,
to labour honestly for the good of the members, particularly the airy youth.
While we were sitting with a family and some other Friends in the evening,
a few expressions impressed my mind,
respecting the care of youth and timely stretching the
line of discipline over transgressors.
When I ceased speaking, my mind did not feel relieved,
and it appeared to me that there were near the house some of a
different class from those I had been addressing,
and on opening the front door,
found the porch and steps round about crowded with most
of the young people of this licentious little village,
and it afforded an opportunity greatly to relieve my mind,
and so went home to our lodgings in peace.

"`14th.--To the Gap meeting, which proved a very open time;
my mind was affected in beholding the people along the road going to meeting,
as well as in the house, it not being large enough to contain them by much:
left this place in peace.
15th.--To Bullskin meeting, which, after the expectations of the people were starved,
proved through divine help, an open good time; a number of strangers being at it.

"`17th.--To a large meeting at Hopewell, which was low and discouraging in the forepart,
but through favour ended more solidly and well;
next day after a comfortable sitting with the family of children where we lodged,
set off to go over the mountains.

"`23rd.--To the monthly meeting of Redstone,
in which I was silent until near the close of that for business;
and then after a season of painful conflict,
I was favoured to relieve my mind in a remarkably close line;
and to my admiration it proved a baptizing season,
and I trust through the fresh extension of heavenly regard,
brought a remnant near one to another:
thanks be given to him who is worthy of the praise of his own work.

"`24th.--To Redstone meeting, which was large, and after a season of waiting,
I stood up with an opening, which appeared mostly for people of other persuasions,
as there seemed to be pretty many there, but found it hard work to get along,
and at length all closed up.
In this condition I quietly sat down, and passed the meeting through in silence.
In the afternoon met with a committee appointed in the monthly meeting yesterday.

"`25th.--A morning of close conflict, wherein all seemed closed up.
I could not see it right to appoint a meeting;
but in a season of inward retirement was favoured with resignation to my lot,
and after strewing a few tears was a little easier.

"`26th.--A morning of renewed exercise: no way opening to move forward,
which was trying indeed, when I considered the length of my journey from home.
Surely I had failed,
if a secret hope had not been granted that I should yet behold
the goodness of the Lord in the land of the living.
In this proving state, A. W. proposed to leave us and visit his daughter,
as no prospect of service seemed to open;
and almost immediately on his mentioning his thoughts,
there appeared a little ray of light arising toward two meetings on that side the river,
and I found liberty in my mind to send word to Friends and only Friends,
to get together at Fallowfield tomorrow, and on sixth-day at Westland.

"`Sixth month 27th.--Crossed the river to Fallowfield meeting, which was a laborious one.
I sat nearly or quite two hours before I could stand up; but it ended well,
after which I was much depressed.
Went home with Mary England and lodged.

"`29th.--Crossed the river again to Westland meeting,--
stopped by the way to see a sick friend,
which with some detention at the ferry caused us to be rather late.
The forepart of the meeting was trying to me,
although on my first sitting down there seemed something good spreading.
I sat nearly two hours before I felt the revival of
that which would enable me to minister to the people,
but it was vouchsafed in the Lord`'s time,
which may my soul be more and more engaged to wait for.
It was thought to be a good meeting and ended comfortably.

"`30th.--Went to Redstone meeting,
where I was favoured to relieve my mind in a close but tender manner,
and returned with a good degree of peace;
and after a religious opportunity with a number of
Friends went towards a little meeting near Beesontown,
with resignation to the divine will, either to go on toward the Alleghany,
or to labour further in this land.

"`Seventh month 1st.--This morning walked out into the field and woods,
and had to commemorate the Lord`'s goodness and love,
wherein my dear wife was brought into remembrance.
O Lord, my soul reverences your name,
in that you are pleased to accept the feeble efforts of an unworthy servant,
who desires to thank you for your mercies past,
and humbly to hope for the continuance of them, through this trying journey.
Be pleased to remember my dear family and friends left behind;--
graciously be near to my dear help-mate and my aged mother.
O Lord, look down in tender mercy on my dear children.
Went to this little meeting, held in a cabin about sixteen feet square,
without a window in it, and a very warm day; but through mercy it proved a good time.
After dinner my mind was closely exercised to know what step to take next,
and towards evening was easy to go to Beesontown;
this night was a wakeful conflicting one.

"`2nd.--Thoughtfully exercised to feel my way in this land: after breakfast,
taking a walk abroad, and seeing the reapers in the field of our landlord,
(who is a Presbyterian,
but his wife and several of the children of our Society,) my
mind was turned toward them in gospel love,
and when they came in to their breakfast and had done, I requested that they,
together with this large family would sit down quietly with me,
and to my humble rejoicing I had a good time with them,
from these words of Boaz to his reapers, '`The Lord be with you;`' and they replied,
and '`may the Lord bless you.`'
I now felt easy to leave these parts,
having laboured with much honesty and plainness amongst them;
and after dinner we rode to Samuel Morton`'s in the Alleghany mountain,
a place called Sandy Creek Glades,
where there are a few families of Friends and a little meeting,--a more wilderness,
desolate road or path, I think I have not travelled.
We got in after night, and they kindly entertained us.

"`3rd.--I went to the little meeting, held in a cabin about two miles off;
in as wild a place, I think as I ever was in.
In the forepart of it my mind was led to view the situation of our first parents,
both before and after their sorrowful fall,--how the ground was cursed
because of man`'s disobedience,--and that though they were few in number,
yet they were favoured with a merciful condescending
God to converse with and instruct them.
The wilderness and solitary place surely must have been
glad and rejoiced at such a time as this.
And O! gladdening thought, that the Lord is the same to day as then,
and remains so forever.
Praise him O my soul!
We went home with our friend John Smith, five miles,
by a lonely path through woods and glades;
and on parting from them the great Lord of the universe refreshed our souls
with living food from heaven--I have not often seen more brokenness;
and they remain as epistles yet to be read at this time.

"`6th.--A dull morning; my way being darkened and blocked up,
although I thought on the road yesterday,
that I saw it would be right for me to go on for Hopewell,
be there on first-day and come back to this place, Bear Garden, on second-day,
and so take the meetings hereaway next week.
But this morning all was gone, so concluded to move on,
but could not leave the family without a space of quiet retirement;
and after expressing what occurred to this family,
I thought we might pass on without a meeting;
but the opening returned with a degree of clearness,
and we gave liberty to notify the people of our being back on second-day:
wait the issue with resignation, O my soul!

"`8th.--Went to meeting at Hopewell, and was shut up in silence.

"`9th.--Attended Bear Garden meeting, which was exercising and laborious.

"`10th.--Attended Back Creek meeting, which proved a close and laborious season.

"`11th.--Poorly this morning; the weather close and warm,
which tries my poor feeble frame.
Inward provings also attendant, and the life of religion low.
O, that I may be preserved as well as those I have left behind,
from being swept away with the strong current in this day of outward ease.
My prayers have been put up this morning for myself and dear wife.
Lord keep us near to you, the fountain of strength,
and support in all trials of faith and confidence.
Went to the Ridge meeting, held in a school house, wherein I had close things to say,
but humbly trust I was in my place.
Had an increase of inward conflicts, but was favoured with a comfortable night`'s rest,
and in the morning (12th) with a degree of the overshadowing of the wing of divine love,
in a sitting with this family before we parted;
and on the road to a meeting called Tuscarora, felt brokenness of heart,
which seemed as a preparation for cross-bearing afterward, both in the meeting,
in which I was silent, and after it was over.

"`13th.--To Middle Creek meeting, which was made up, as I found afterward,
by a number of other societies, and it proved an open and I trust, through divine favour,
a baptizing time in the latter part.

"`18th.--To Crooked Run, a large, mixed, and open meeting;
in the close of which received a request from a
Methodist to have a meeting in a town called Font Royal,
about six miles off, to which after solidly weighing it, we consented.

"`19th.--To the meeting at Font Royal,
which was held in an unfinished Methodist meeting house;
it was hard work to preach amongst them,
and although life did not rise into such dominion as could have been desired,
during the greater part of the meeting, yet it was thought to end solidly,
and their preacher after meeting, came and taking me by the hand,
owned the testimony delivered.

"`20th.--After a remarkable opportunity with J. F.`'s family,
set off and stopped at a poor man`'s house, with whom and his wife and eight children,
we had a religious opportunity.

"`21st.--A poor night`'s rest, and unwell this morning.
O! what a poor feeble creature I am, to move forward altogether amongst strangers.
This day a sore and long fit of sickness I had some years before,
came humblingly into view, and my covenant then made to serve and follow the Lord,
even to the end of the land.
Lord send forth your light and your Truth; let them lead me, let them guide me.
You can raise out of weakness and sickness into strength and health,
I hope and trust in you.

"`22nd.--Went to meeting, which was an open time, and after it felt comfortable.

"`23rd.--At Evan Thomas`'; and it being a rainy day, stayed mostly within doors;
as in the outward, so in the inward, it seemed a cloudy, dull time.
Attempted after dinner to set off and move forward,
but after sitting down with the family under a painful cloud,
in which I found nothing to say, had no liberty to move.
Wait in patience, O my soul.

"`24th.--After breakfast sat down with this family,
and was favoured to relieve my mind of an exercise which lay on it.`"

[.offset]
After visiting several families, he remarks:

"`My mind was sweetly comforted on the road after the opportunity at the last house;
but O the baptism I had to pass through on account of this family, in the evening,
night and morning; but found an opportunity to relieve my mind in a serious opportunity,
and then moved on toward the old settled parts of Virginia,
We missed our road and got lost, and about one o`'clock came to a house in a lonely place,
where we sat down contentedly, as has been the case frequently,
and ate our cake with some butter and milk.
In the evening we sot over the Blue mountain, at Rockfish Gap, to a friendly man`'s,
where we were kindly entertained for pay; and in the morning when about to set off,
took a serious opportunity with him, wife and some of the family, much to my own comfort,
and it appeared to be to their satisfaction, and so moved forward in peace.
Yesterday crossed six or seven considerable waters,
and in the evening reached John Douglass`', near Douglass`' meeting: poor,
exercised travellers, what need we have of faith and patience.

"`27th.--To meeting,
and for a time I was almost ready to conclude we might leave them as we found them,
so little was to be felt;
but in the latter part strength was given honestly to discharge myself,
and felt peaceful and easy.
On our road afterward,
my soul praised the Lord for the extension of his arm of protection and deliverance,
for of late it has been a time of sore trial.
Had a comfortable ride, and when we arrived at E. J.`'s,
he came and affectionately saluted us, and gave us such a hearty welcome,
poor pilgrims as we were, that it was truly comfortable;
for which I am thankful while penning this under his roof;
and yet desire to rejoice with becoming fear, seeing how good mortification,
poverty and abasement prove, when rightly submitted to and lived under.`"

[.offset]
In a letter dated seventh month 30th,
after speaking of a meeting which he held on the 19th, he says:

[.embedded-content-document.letter]
--

This is the first meeting out from amongst Friends,
and hope truth was not dishonoured thereby;
but it is not the line of service I have been led in, and am ready to think sometimes,
may not be much so in the course of this visit.
My cup seems full toward our own professors;
and if my religious communications are not in all
places so large as in some visits amongst other people,
I think my cup of suffering, in and under a sight and sense of Zion`'s desolate state,
is as large as ever I experienced, but the Lord, my helper,
has been kind beyond expression, and in a sense of it, at seasons we can say,
we lack nothing.

The way to have got over much ground, and made quick despatch in the visit,
I suppose would have been to pursue our route up the country to South River,
and from there to New Garden,
and also the way to have breathed a more pure outward air back of the mountains,
but that road was shut up, and a little light shone this way into a sickly country,
and at a sickly season.
Times and seasons, health and sickness, life and death,
are with the ever gracious Helper of all that trust in him,
and having put my (or our) hands to his plough, we may not look back,
and I may again say, with thankfulness of heart,
I rejoice that I am favoured with such a true yoke mate
in the various dipping seasons to be met with.

--

"`Eighth month 1st.--To Black Creek meeting, a mournful time,
under a sense of the low state of the church.

"`3rd.--Had a religious opportunity,
in which some of the poor negroes came near the door,
and my speech was turned toward them; they wept, and I was comforted in the belief,
that the visitation of God`'s love was towards them.
Leaving them in this tender frame of mind, we went to the preparative meeting,
held at White Oak Swamp.

"`7th.--To Wain Oak week-day meeting; and notice having been given in the neighbourhood,
it was pretty large, and thought to be profitable;
had a serious opportunity in the family where we dined,
with a number of neighbours who stopped; went on to Skimino,
and stopped at a friendly man`'s and lodged.

"`8th.--To Skimino week-day meeting; which was large, and an open tendering season,
which had a tendency to brace me up a little.

"`9th.--To James River, this was an exceedingly close warm night,
and trying to my weak frame, but I humbly hope all will work together for my good,
as resignation to the divine will is laboured after.

"`10th.--Spent the morning of this day in a comfortable degree of quiet,
after a tossing night, and feel desirous my love may increase to my dear Lord and master,
who has led me forth in his work.

"`11th.--Spent the morning of this day in a quiet sweetness;
went to the quarterly meeting of ministers and elders, held at Black Water,
which was a comfortable open time.

"`12th.--To a large and mixed meeting; the weather continuing exceedingly warm,
with the addition of very close exercise and religious labour, affected me much;
my appetite failing--but the Lord being good and gracious to me,
I was favoured with ease of mind, and in the afternoon also,
was helped to discharge my religious duty towards both
white and black of this family and others,
although to the spending of my bodily strength.

"`13th.--To the quarterly meeting;
found Friends in the practice of discouraging all but members attending on this day;
we did not sit long before the business of the meeting was opened,
and in the mean time I was favoured with a comforting season amongst them,
and also in the meeting for business;
I relieved my mind much to my comfort and satisfaction,
and trust to the edification of my brethren;
and in the evening a solid opportunity in the family of A. Bailey.

"`14th.--Set off accompanied by Jesse Copeland and Benjamin Pretlow,
to the Western Branch; a long trying ride, and no house to stop at but the meeting,
which although laborious in the beginning, ended comfortably.

"`15th.--To Bennett`'s Creek, where was a mixed large meeting, and an open time.
In the afternoon returned to a meeting held in Suffolk court-house,
where I sat almost two hours in silence, and was thankful for preservation;
and although no mighty works were done,
I was glad in feeling the good and preserving hand near.
Near the close had a little to communicate to the inhabitants,
and before the meeting ended, to the poor African race in particular,
a number of them being there; and left the place in peace.

"`16th.--We went to Summerton meeting, which was large,
the house not containing the people by many, and a pretty open time.

"`17th.--A cold night, and this morning sat by the fire.
To Johnson`'s meeting, where the expectations of the people appeared great.
I sat nearly two hours in silence, and had but a painful season at last.

"`18th.--To the widow Vick`'s, to the meeting held in her house, which was large and open.

"`19th.--To Black Creek, where we found a large mixed gathering of people,
more than the house could hold, and through the extension of divine strength,
was a good meeting.

"`20th.--To Stanton meeting, to which came many people,
as has been the case for several days past; and the weather was hot,
and the house close and crowded, and numbers out of doors,
yet I may not forbear recording the goodness of Israel`'s Shepherd,
who was as near to help this day as heretofore.
May praise be rendered unto him for this,
and for the preservation of my poor weak body through heat and cold,
watchings and fastings;
even to him who preserves his servants in burning climes and lands remote,
and supports them by his care.
With reverence I bow, in remembering that man is not to live by bread alone,
but by every word that proceeds out of the mouth of God.
O! dearest Master,
preserve me in watchfulness and humble thankfulness for your favours past and present.

"`21st.--A trying night, and felt unwell this morning, with but little appetite.
Went to the meeting called Seconk, which was crowded,
the house not being large enough to contain the people.
And O, how mercifully near was the Lord my God,
furnishing with strength to clear myself of the people;
there being a large collection of youth, and also others from different meetings,
and after it was over parted from several of them with brokenness.
In this day`'s work I have been wonderfully supported, seeing I was so weak this morning.

"`24th.--To Micajah Crew`'s;
and for the favour of being permitted to arrive again at this kind friend`'s house,
through such arduous labour as I have experienced since Black Water quarterly meeting,
I feel thankful, and recruited in bodily health and strength.

"`26th.--To the select quarterly meeting at Cedar Creek, which was a uniting season;
and at eleven o`'clock, to a very large and mixed meeting,
wherein the Gospel of peace was preached,
and through its prevailing many were reached and tendered,
and my mind relieved and comforted.
Let the praise and honour of this day`'s work be rendered unto the Lord,
who is a present helper in the time of need.

"`27th.--To the quarterly meeting for business, which began at ten o`'clock,
and held until near six.
This was nearly select, and an open time in the meeting for worship,
especially toward the youth, and I hope throughout it was a meeting to be remembered.

"`29th and 30th.--Spent these two days in an emptied state, seeing no way open to move;
and it has been a time of renewal of outward health and strength,
after such close labour in the heat of the weather;
it being now and for a week past cool and pleasant.

"`Ninth month 1st.--My mind was exercised this morning, not knowing which way to move,
or what to do.
O! what need is there of patience in such stripping seasons.
After dinner set off in much weakness toward Genito meeting,
accompanied by our kind friend Micajah Crew.

"`2nd.--To Genito meeting; and no notice being given, it was small,
but I was comforted in my present poor state therein.
Prayed for my dear wife, mother and children,
and was favoured with a small opening to move forward;
and after dinner had a little to communicate to a number of young people of the family,
and others who came to see us.

"`3rd.--Set off on our journey, and crossed James`' River,
and stayed all night at S. Pleasants`', where we were favoured with a precious opportunity,
and I had a sweet refreshing night.
A measure of the same sweetness and love covered our minds on parting this morning,
and the savour thereof remained with me for some time.
Ate our dinners on the road, and in the evening arrived at our friend J. Johnson`'s,
at Amelia.

"`5th.--We were most easy to see the two or three families of Friends together,
in their tattered meeting-house, with an earthen floor, a habitation for hogs;
and although I went in weakness,
the presence of Him who took up his abode in a stable
and a manger (there being no room in the inn,) was near,
and favoured not only with strength to preach the gospel to a few,
but with a renewed prospect that the time will come,
that the wise will be confounded in their earthly wisdom, and, weary of it,
will be prevailed upon to follow Christ Jesus, the light of the world;
even so be it in the Lord`'s time.

"`6th.--We rode to an inn and lodged.
Ate some provisions we had with us in a poor house by the way,
and had some religious conversation with the woman, and set off well refreshed.

"`7th.--To our friend William Johnson`'s at South River, and lodged.

"`9th.--To Seneca meeting which was held in a log building without a window in it.
A close, hot time, as to the outward, and in an inward respect,
very little good to be felt amongst the people, either within or out of doors:
but being helped through my close and laborious exercise,
it proved at the close a solid refreshing time, I hope to more than myself.
Went home with R. B. and dined; here was but poor outward accommodations,
which to the flesh was trying;
but on parting was favoured with a precious opportunity with parents and children.

"`15th.--To South River monthly meeting, which held until almost night,
and was a satisfactory time.

"`16th.--To a meeting at the above mentioned place, which was large and favoured;
I felt great unworthiness, but the Lord was merciful;
went home with Joseph Anthony to a town called Lynchburg.

"`17th.--Here we tarried until about noon,
and several Friends came a number of miles to see us.
We sat down together with the family, and I trust it proved an instructive time.
We rode this day to a public house about twenty-seven miles.
Ate our dinners by the roadside, were well refreshed,
and in the evening my heavenly Master refreshed my soul in a plentiful manner.

"`18th.--This morning on parting we requested a religious opportunity with the family,
which was readily granted and proved a baptising season,
there being several other travellers with us,
among them two goodly Virginia gentlemen of some distinction;
after which I had great peace,--the Lord be praised therefor.

"`19th.--After some edifying conversation with our host this morning we rode to C. L.`'s,
and next day after a baptising opportunity with
him and wife and also visiting the school,
which I believe was satisfactory to the master, though not a Friend;
we parted affectionately and went home with our kind friend Samuel Parsons,
who has been acceptably with us in this tour since we left his house.

"`21st.--Spent this day at our friend Samuel Parsons`'; Thomas Pleasants coming to see us,
was favoured with a solid opportunity with him and wife, who were much tendered.

"`23rd.--To Genito meeting which was large, and I was much exercised,
and found it hard work to get relief.

"`25th.--I feel like a poor creature this morning;
nothing presenting with clearness to my mind,
and this staying in one place looks much like loitering away
time,--but time is the Lord`'s and his time is the best.
O my soul wait patiently for it, and when again opened into service be simply obedient.
After breakfast walked abroad,
and a prospect opened on my mind to visit a family and to
appoint a meeting at S. Pleasants`' house at noon tomorrow.
On informing our friend Thomas Pleasants, it was readily complied with,
and he accompanied us to S. C`'s.,
where we were favoured with a baptising season together,
and next day went over the river to the meeting held in S. Pleasants`' mill,
which was large;
but I did not find that relief and satisfaction of mind which I have in some places;
although the people appeared goodly and behaved solidly.

"`27th.--Went to Genito week-day meeting under close exercise of mind,
and as we entered the house found it almost filled up with people, which was unexpected,
not knowing how they got notice, or what induced so many of them to come together.
Great stillness prevailed, and my mind was so much humbled as to bring me on my knees,
after which I was favoured with an open time in testimony.
The Lord be praised for his goodness.

"`28th.--A night of exercise, and feel poor, blind, and unworthy this morning;
no way opening to move forward.
O what a great thing it is to keep always shod
with the preparation of the gospel of peace,
and not to transgress or break the least tittle of the law.
Truly I may not boast.

"`30th.--To Genito meeting, which was pretty large,
considering there is a yearly meeting of the Baptists`' Society within six miles.
It proved an open relieving time; went home with Samuel Parsons,--took our farewell,
and came back with our kind friend Thomas Pleasants, where we met with a hearty welcome,
and my spirit was set a little more at liberty,
in a hope that way may open in the morning to leave this neighbourhood.

"`Tenth month 1st.--I feel this morning as though we might be released out of this place,
and know not that there is one stone left unturned with regard to anyone.
O that the Lord may bless the labour he has bestowed instrumentally on individuals,
to their growth in the ever blessed truth.
We left Thomas Pleasants`' after another baptising tendering season,
wherein my dear wife and family came into remembrance,
and the Lord was prayed unto for the continuance
of his strength and love to us who are abroad,
and to those left at home, after which set off in comfort and peace,
and '`the trees of the field did clap their hands.`'
We arrived at Richmond before night,
and on the 3rd set off accompanied by Samuel Couch and Robert Evans, pretty easy in mind,
and thankful that we could leave Richmond.
Arrived at our friend Robert`'s before night at Petersburg,
who with his wife and children received us with openness,
and after they had refreshed our bodies,
the Lord condescended to feed and refresh our better part together;
and I thought it was worth being shut up a day at Richmond in blindness,
and riding this thirtyseven miles for.
Went to bed easy and comfortable,
but my dear companion was taken very unwell in the night, which alarmed me.

"`4th.--Went to Gravelly Run meeting,
notice having been sent forward,--and it was a season to be remembered by me.
I could think of little in the forepart, but returning back to Richmond,
to which prospect I cheerfully resigned myself,
and was afterward favoured with an open time in the meeting.
We had a remarkable time at the house where we dined,
wherein I believe the strong was made to bow before Him whose power was eminently felt,
and after it went on peacefully to Petersburg.

"`7th.--Returned to Richmond and attended a meeting at the capital.
We received a respectful letter from the person who occupied the most convenient room,
excusing his not giving it up to us, as he was to preach a funeral sermon for a major,
on the death of his wife.
The meeting was not large at first,
and many of those who had gathered were uneasy with silence.
I felt willing, after a time, to get up and gently reprove them,
and commend the few who kept their seats,
and also invite them to come together in the afternoon and bring their neighbours,
thinking that would be all that would be required of me to say.
But when I began to speak, the people crowded into the house in such a manner,
as caused me to pause and consider,
whether it would not be best to sit down and recover strength
to labour amongst them in the line of the ministry;
but concluded it safest to endeavour to continue speaking,
and through favour I was in some degree enabled to relieve my mind,
and it was thought Truth arose and spread into some dominion.`"

[.offset]
In a letter to Hannah Cathrall, dated "`Richmond, tenth month 9th, 1792,`" he says:

[.embedded-content-document.letter]
--

We came into this place yesterday morning from Robert Pleasants`', accompanied by him,
and although I feel a care on my mind respecting going too much to,
or being too free in the houses of disowned members or others not of our Society,
as has appeared so open-hearted and friendly since our lot has been cast here,
I was free to stop at his door, and after meeting came back and lodged.
I have thought more of your lines,
since a proving dispensation I had to pass through yesterday,
than when I first received them;
and some of your expressions are as fitly framed as if you had been on the spot.
My beloved companion told me last evening,
that he thought of the bow and battle axe mentioned by you,
while your poor friend was exposed amongst a multitude of strangers,
in this dissipated city.
So it was in Boston, when I was under very deep conflict and exercise of soul,
your words through favour, were like apples of gold in pictures (or a basket) of silver.
But for all this, bear with me,
I have felt at times something rising up in my mind by way of rebuke against you,
under a fear that you do not sufficiently avail
yourself of that stretched out hand and arm,
which with such clearness and pertinence you can write of to others.
I want you, my dear sister, to fulfill or accomplish your task in the day time,
knowing that the Lord of the harvest has blessed you with a precious gift.
Is your bodily presence weak and your speech contemptible amongst the people,
or only in your own opinion?
There are many poor children crying for bread in places, and few,
very few delegated feeders or shepherds to administer to their needs;
and this thing is not of the Lord of hosts,
but I believe for lack of unreserved obedience in all things to his blessed will.
Therefore it is, that strangers have to stand and feed their flocks,
and the sons of aliens to be for husbandmen and vine dressers.
Lift up your eyes and behold what a field of labour there is;
and although deep are the plungings of the labourers, yet sweet is also, at seasons,
their reward; yes, it is preferable to an earthly crown.

--

"`11th.--Went to Curies meeting, which was small: I felt peace in going,
and comfort and satisfaction on sitting down in the meeting, in the remembrance,
that Truth will remain the same, although all men forsake it.
I laboured in weakness and poverty,
and although encouragement was held forth to the poor and needy,
yet it was afflicting to feel the irreligious spirit
that is so prevalent in this neighbourhood.

"`14th.--To a meeting in the Assembly room in the town-hall at Richmond, which was large,
and we had the company of many Friends from different parts of the country.
Dear T. Harris and wife came thirty miles; and to my great comfort,
dear Mary Berry came from Micajah Crew`'s, at Cedar Creek, twenty-two miles,
and arrived after the meeting had nearly gathered.
She exercised her gift, both in supplication and testimony, amongst a mixed people,
who behaved well, all things considered;
and after it was over we were treated with kindness by several.`"

[.offset]
Speaking of this meeting in a letter,
after stating that his beloved friend Mary Berry came in late, he says:

"`I cannot fully describe the feelings of my exercised mind,
when thus favoured with her company, and the help of her spirit.
Indeed I felt a degree of shame cover me,
in the remembrance of these expressions of the Master, '`O you of little faith,
wherefore did you doubt;`' perhaps this was on the sudden
appearance or putting forth of his power formerly.
It was a large gathering, in which I was strengthened to stand forth in a good degree,
I trust, of innocent boldness, carefully leaving room and time for this beloved friend,
who appeared in prayer and afterward in testimony.
I may with gratitude say, the name of the Lord be magnified for his mercy,
and the stretching forth of his arm to help of late.

"`17th.--'`To the meeting called Jack`'s Swamp; the forepart whereof was laborious,
under a sense of an infidel unbelieving spirit resisting the truths of the gospel;
and after the meeting for worship ended I was more confirmed in this belief.
However, I had a good time near the close of the preparative meeting with Friends,
both men and women, and the meeting ended with brokenness and tears.

"`22nd.--Got to the quarterly meeting for business at Contentney, in North Carolina,
which held until about sunset.

"`23rd.--After a comfortable season in parting, set off the for yearly meeting,
and in the evening were refused admittance at a house of entertainment;
but riding a few miles further, we were taken in at a private house.

"`Eleventh month 3rd.--The yearly meeting of
North Carolina held until seventh-day evening.
We lodged at our kind friend Aaron Morris`';
and the last night did not get home until late,
owing to one religious service presenting after another.
The service of the yearly meeting was laborious:
a lively spirited remonstrance was drawn and signed, to be laid before the Assembly,
respecting the free black people being taken up and sold again into slavery.
The yearly meeting was attended by a solid committee from the yearly meeting of Virginia,
and I trust upon the whole,
there was a moving forward in the great work of righteousness.

"`4th.--This morning awoke early, and my mind was impressed with a prospect,
which had at several times opened, to go toward the Western quarterly meeting,
and mentioned it to my companion, who united with it: so we got ready and set off,
after an opportunity with this kind family, and left them with sweetness.
Got to Little River meeting, which was a good one,
where we met with Mary Berry and her companion.`"

[.offset]
The following extracts are taken from a letter written to his wife, dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Symons`' Creek, North Carolina, Eleventh month 3rd, 1792.

You have often been the companion of my mind, my dear and tender wife,
since the receipt of your last letter, put into my hands at the yearly meeting;
in which I discovered that you were closely exercised, not only on my behalf,
but also on your own account, when reflecting on the frequent separation,
which is our lot in this uncertain world of losses, crosses, and repeated trials.
But let us remember that our Maker has declared himself to be our Husband,
our gracious Redeemer, the holy One of Israel; that is, to those who look to him,
trust in him, and lean upon his arm of strength and true comfort;
and that he is justly called the God of the whole earth,
who unites and knits our hearts together in the covenant of true love.
May this still be kept in view by us in this present separation,
that so we may be made a savour of life unto life, one to the other.
My heart was affected on reading your lines, and no part of them was more precious to me,
than your prayer for my preservation through the ups and downs which are to be met with.
There is frequently an echo of the same language in my heart,
and my fervent prayers both in private,
and also when favoured with the gift of utterance, have been poured forth for you,
my dear mother, and our children.
May your desire and care increase, in the best sense, toward these,
that it may please the Lord,
who often turns the feet of their exercised father from them,
to condescend to be their father and friend, and to make them truly his children.
As I am favoured to keep my habitation in the Truth,
which the Lord in his infinite mercy and love grant, through heights and depths,
both at home and abroad, may be my happy lot; next to this,
their walking in the Truth will be my greatest joy.

--

[.offset]
After mentioning some particulars of their journey from Richmond,
a distance of three hundred and fifty miles, he continues.

[.embedded-content-document.letter]
--

I have been favoured with a sufficient reward
for going round to Contentney quarterly meeting,
and can set my seal to the truth,
that the Lord is a rich rewarder of all that serve him in sincerity of heart;
and I have no doubt it is in his will also,
that our lot has been cast amongst Friends in this yearly meeting.

I have met with various occurrences since I left you;
had many long rides and close exercise of mind various ways;
but I am not disposed to give an evil report of such a journey,
lest I may unknowingly throw discouragement on the blessed work,
for truly in and through all I have met with,
the Lord has never failed to help with a little help,
and my exercised mind has at times been set at liberty in the gospel of his dear Son,
Jesus Christ, my merciful Saviour.
Therefore, my dear, give me up now into his further keeping and care,
for I know not when I may get through this journey.

I often call to mind the deep, and I was going to say,
horrible pit of distress and despair into which I was plunged,
and which you were a witness of, not many months after our marriage,
when the jaws of death seemed to open upon me,
and I was looking with deep thoughtfulness at the-house appointed for all living;
when fearfulness overspread me, under an awful sense that I was not in readiness.
Then, O then, was I willing to covenant with the Lord,
that if he would restore peace to my mournful soul and continue it,
I would follow him to the land`'s end.
No marvel, that since that day it should be my lot to be often engaged abroad;
and I feel sweet enriching peace of mind in a faithful
dedication of all that I am favoured with,
to divine disposal, however trying.
I have also received this assurance, that as there is a continuance in the same,
I shall not go without necessary outward good things;
and likewise as you continue in that which has hitherto strengthened
you to give your husband up to the all-wise Disposer,
to run with alacrity his errands,
you shall witness the blessing descending upon you in a way which, at seasons,
you can hardly believe.

--

[.offset]
Extract of a letter to John Hoskins, from the same place.

[.embedded-content-document.letter]
--

The situation of the poor blacks, who,
after being set at liberty by their conscientious masters,
have been sold again by wicked men under the sanction of a law of this state,
came before this yearly meeting;
and although a petition was handed the Assembly last year and rejected.
Friends were encouraged to move in it again;
and a committee of nine Friends was appointed to attend the Assembly this month,
with a lively, spirited remonstrance.
I have a hope that if they use endeavours in opportunities with the members separately,
when they go to Newborn, something more will be gained, favourable to the poor blacks.
There was a pretty large committee attended from Virginia yearly meeting,
respecting a junction with this,
but they proceeded no further than to leave it for consideration,
and appointed a committee to attend the next yearly meeting in Virginia.
My mind has been closely exercised on these two
subjects during the sitting of this meeting;
although neither I nor my father before me, that I know of,
was ever concerned with slaves;
neither has it fallen to my lot at home to speak much in meetings on their behalf.
It has not been so now; for while thinking, of such gross wickedness,
I have felt the fire to burn, which led also to speaking with the tongue.
And I think Friends have too much permitted their hands
to hang down with feebleness in this matter.

--

"`8th.--Went to Lewisburg to the house of a kind Methodist,
who would not take pay for what we had.
I was made sensible that religion had a place in his mind, and that of his wife,
almost as soon as I entered the house,
and we had a solid season with the family before we left them.

"`10th.--To the meeting of ministers and elders at Cane Creek.
In the ride this morning,
I remembered the helpless condition I was reduced to this time about nine years ago,
by weakness of body and mind, and now through mercy,
this twenty-six miles ride appeared little to me.
My heart was filled with gratitude to my merciful Lord and Master,
and although I have had times of suffering and proving in this country,
I have no doubt of being in the proper allotment.
But O, how the dispensation was changed in meeting!
Wait and hope, O my disconsolate soul, upon your Deliverer,
who never fails in the needful time.

"`11th.--A large meeting; but alas! what a lifeless one.
O! the rawness which appeared; there was not much room for public communication,
and but little was given to me; it was a suffering time.

"`12th.--To the quarterly meeting, which was an exercising, searching time;
and in the close I felt peace, especially at the conclusion of the select meeting,
which held after night.

"`14th.--This day begins our work in appointing meetings in this country;
notice having been given in the quarterly meeting until first-day week.
This was thought to be a pretty good meeting.

"`15th.--After a good opportunity in the family, we set off before the sun was up,
and rode to Spring meeting.
As our friend John Carter and I rode together, he informed me, that in his young years,
being visited by the day spring from on high,
he sought much to find a place of rest to his soul, and joined the Baptists.
After a time he grew dissatisfied with their mode of worship,
not feeling that peace which he was in pursuit of;
and one day after seeking the Lord with great earnestness,
and begging of him to show him whether that was the people he must join himself to,
he went to their meeting with a determination that if he felt
an evidence of the owning love of God to attend his mind,
he would submit to go into the water to be baptised, or anything for peace sake:
but on that day the preacher held forth such doctrine to the people,
that it turned him away from them, in his mind,
and led him more and more into a lonely seeking state.
At this time,
the little company of Friends in the neighbourhood had
grown so weak as to neglect their meeting,
and had given consent for the Baptists to hold meetings in their meetinghouse.
For some time his mind was impressed with an apprehension,
that it was required of him to go and sit down by himself in the meeting-house;
but he put it off, being ashamed.
At length he went by a private way and sat down alone and was greatly refreshed;
but he could not do it privately long, feeling a necessity to travel the road openly,
for his friends and neighbours used to wonder where he went in private.
One day in going to meeting he met with one of them, who asked him where he was going,
and he told him honestly, '`I am going to meeting:`' '`strange,`' says the other,
'`what will you go there for?`'
He left him, however, by the way, and had peace in the meeting.
Next time he went, seven of his neighbours hearing of his going, joined him;
and in process of time he was united to the Society of Friends:
zeal and religion revived amongst them, and there is now a large meeting,
called Spring meeting, which we were at today;
and this Friend is a valuable minister amongst them.
We had a favoured meeting.

"`16th.--To the meeting at Cane Creek, which, upon the whole was a good time.

"`17th.--To Rocky River meeting, which was large for the place,
the house could not hold the people, and it was an open encouraging time.
Several Friends came after meeting to David Vestal`'s, to see us,
and our parting was such a time of divine favour, as will not, I believe,
easily be forgotten by some.

"`18th.--Went to Nathan Dickson`'s, and when the hour for meeting came,
we were agreeably surprised to find his barn well accommodated with seats, etc.,
but it would not hold the crowd of people that gathered; many were out doors,
both sitting and standing; and through divine mercy it was a thorough, favoured time.
After meeting a man came to me with tears, and said,
'`I know that the glorious and everlasting gospel has been preached this day,
although I am not of your profession,
and may the Lord bless and protect you;`' or nearly to this purpose.
May the Lord have the praise of his own work, and flesh be laid in the dust.

"`19th.--To the meeting called Tyson`'s, held in a log house,
which was not large enough to contain the people, and an open time it proved;
many of other societies being here,
and I humbly trust the gospel was preached with some degree of demonstration.
Stopping at a house to eat some provisions which a Friend had kindly brought for us,
and several others also coming there,
I had another opportunity to preach the gospel of my Lord and Saviour,
and so parted from our kind and hospitable friends and
their sober neighbours with sweet peace.

"`20th.--At Holly-spring meeting, which was large,
and though exercising in the forepart, I hope it ended profitably.
After it, a gray headed old man came to me,
and asked whether I was of the family of the Scattergoods, in New Jersey;
and after telling him I was, and some little more conversation passing, he said,
'`You have scattered much good today; may we keep it.`'
May the praise, if any good is done, be rendered to the Lord,
to whom it is due for all his tender mercies.
On the 22nd attended meeting at Providence, and next day to Center.
In the evening Peter Dicks informed me,
that there were but four or five families settled near him, when he moved to this place,
about forty years ago.
They held their meeting first in a private house, then built a small meeting-house,
which is yet standing, and used for a school; and near it is a large meeting-house,
built within these few years,--and a large settlement of Friends.
He also told me, that at the time William Penn came the second time into Pennsylvania,
his grandfather was settled on Brandywine;
and on William`'s return from a treaty with the Indians at the forks of Brandywine,
for the land on this side of Susquehanna, called the Conestoga land,
he came to his grandfather`'s, and offered him and others a large tract of that good land,
for 5 the hundred acres, and left them to consider of it, which they did;
and after consulting, concluded to send him word they would not take it,
because it was so far back, that they thought it would never be settled,
and it would only be money thrown away.

"`24th.--Set off accompanied by our kind young friend Phineas Nixon,
who came to this place to conduct us to his house.
It was a precious ride to me, through a piney wilderness, particularly the forepart,
in meditating on the divine law.
This day saw a fine buck near the road-side, and part of a flock of wild turkeys;
and at a tavern by the way, a lad brought a fine buck on horseback out of the woods,
which had been shot.

"`25th.--To Back Creek meeting, which was very large and an open time.

"`27th.--While I sat in company and conversation at a Friend`'s house,
my mind was very suddenly impressed with weight and solemnity, and giving way to it,
my dear wife and family, and also companion`'s, and in a very particular manner my son,
were brought into remembrance,
and under a precious exercise of spirit I kneeled down and prayed for them.
I trust the Lord heard, and in his own time will grant the travail of my soul.
It was an hour of love and mercy,
and the sweetness remained on my mind along the road for most of the afternoon.

"`28th.--A morning of close baptism and exercise;
having very close things to say in the meeting at Marlborough,
but after it felt pretty easy, and several told me that what was said was to purpose.
Ah, what is yesterday`'s manna when gone!
It is not to be looked to or depended on to day,
but day by day we are to seek the daily bread.

"`Twelfth month 1st.--Went to Springfield monthly meeting,
where I was closely exercised in the meeting for worship.

"`2nd.--O how very close was the exercise of my soul at Deep River meeting this day.
It was a large assembly, and I sat long in silence,
but at length had to deal out doctrine to very gross conditions,
but was comforted in that a little food for the Lord`'s children, the sheep and lambs,
was at length given me.
Here I met with my old friend and father, David Brooks, and his wife,
who appeared glad to see me.
I have had close doctrine indeed to deliver in some of the meetings lately.
O merciful Father, preserve me from saying anything which may prove a burden.

"`3rd.--To the monthly meeting, which was rather a more easy time than yesterday,
and found considerable relief in my labour, although it was indeed close.
After night rode home with David Brooks, and found a comfortable habitation,
quite sufficient for a resting place for the traveller.
Both he and his wife gave me a hearty welcome,
and time passed away in the evening pleasantly,
while engaged in recounting the gracious dealings of a merciful God,
since we were together almost twelve years ago, in New England.`"

[.offset]
He then attended meetings at Muddy Creek, Upper and Lower Reedy Fork, Bull Run,
and the quarterly meeting at New Garden.
After which he remarks:

"`11th.--After a sweet and refreshing night`'s rest,
and feeling comfortable and easy in mind this morning,
I have sat down with thankfulness to the Lord my helper, and made this little record,
looking for baptisms and humbling trials, both inwardly and outwardly to succeed;
but may I humbly hope and trust in the arm of Divine strength.
At this meeting we had the company of a pretty
large number of Friends from Cane Creek quarter.
Dear old David Vestal, who has been as a father to me,
said on parting '`I am grown old and cannot do as I have done in younger life,
in going with and helping Friends; but I have felt such love towards you,
that I have thought some times I could almost run after you on foot.`'

"`12th.--To meeting at Muddy Creek, which was large and laborious,
but was thought a profitable one, and solid in the conclusion.
My dear friend David Brooks stopped me in the meeting house,
and desired I would not be discouraged in low seasons, for he could inform me,
that the state of things had been spoken to.

"`13th.--To Blue Creek meeting, which was a humbling baptising time to me;
wherein I trust I was favoured to pour out my spirit in humble supplication,
and afterwards in testimony;
and I thought a state or states present were designed for the ministry,
or usefulness in the church.

"`16th.--To Westfield meeting, which was large and mixed.
I was much exercised in desires that there might be a quiet settlement among the people,
and got up to speak; but such was the instability manifested,
and the absence of life in the meeting, that I soon sat down,
and waded under a travail for an hour or more.
After this conflict, my gracious Master helped me to discharge myself to my own relief,
and I hope to the warning of some, and to the comfort and help of others.

"`18th.--Was at Deep Creek meeting, which was the most crowded we have attended;
the house could not hold the people by many,
and although it was very spending and laborious, my companion says it was a good meeting,
especially the latter end.
I was informed that George Dillwyn was the first Friend who had a meeting in this place,
and now they have requested to hold a monthly meeting.

"`19th.--This morning`'s ride has been a serious humbling one to me;
and after we got here my spirit was brought into great exercise,
in which I sat nearly an hour in much conflict, like one bound hand and foot;
but through the arising of divine love and mercy,
I was at length set at liberty to appoint a meeting.
The husband was prepared for the word of command,
for which my exercised soul had been also waiting;
and he soon went off to notify his neighbours; the daughter, about thirteen years of age,
as soon almost as I mentioned the liberty I felt to have a meeting,
said she did not doubt that the neighbours would be glad of it,
and with great cheerfulness mounted a horse, and went to give notice.
Soon after, we saw her aged grand-mother, a Baptist, who was here on a visit,
walking along a path which led into the woods, as briskly as a young woman.
O my soul, wait the issue of all this unexpected faith and love!
My faith and patience have been closely tried;
truly it is a precious thing to be passive and willing,
waiting the Lord`'s time for his holy will to be done.
Lord keep me in the way you desire I should go.

"`20th.--A mixed meeting of Anabaptists and Methodists: I sat long in silence,
and believe it was right to do so,
but at length my gracious Master appeared for my help and strength,
and it was thought to be a good time.
At the close, some of the people parted from us with the appearance of affection.

"`21st.--Proceeded on our journey by a way which none of us knew,
and after crossing the Catawba River got to a friendly man`'s house where we stayed,
and I feel humbly thankful that my spirit is borne up and supported this evening.

"`22nd.--Sat down and was favoured in a solid opportunity with this family.
The elder boys brought my childish days into remembrance,
and I was engaged to direct their minds to more precious things.
While I was engaged in testimony, a stranger came in, whom I met with last evening,
soon after we crossed the river.
One of our guides asked him the way, and instead of giving a civil answer,
he was abusive, appearing to be somewhat intoxicated.
But he was changed before we left this family, for being about to mount my horse,
and offering to take him by the hand to bid him farewell,
he said he was going the same road, and wanted company.
Truth was over him, and he was a loving and useful man to us on the road all day.
Both Josiah and I had good satisfaction in endeavouring
to open the way of life and salvation to him,
and he acknowledged to the truth of it.

"`23rd.--We moved forward, and meeting with some difficulty in finding the road,
stopped at a Captain Mix`'s. I was comforted on entering the door,
in finding his wife with a good book on her lap;
we had some religious conversation with them, and when we were ready to go,
he told us we were welcome to put up and stay with him that day.
I felt much love toward him on parting,
for indeed he appeared a lovely sensible young man,
and I could not be easy without telling him my desire,
that the Lord would enlarge his heart in the gospel of his Son;
and on looking over the neighbourhood,
I felt an earnest breathing to the Lord of the universe,
that he would make way for the propagation of the gospel of peace, both here,
and unto the ends of the earth.
We found the way to the ferry at Broad River with difficulty;
and the boat had been brought to the side on which we were by some young people,
who were gone a distance off.
A woman on the opposite side told us we might ferry ourselves over;
and Josiah and I undertook it.
Here we fed our horses and ate our dinners on a stump, and after the company had set off,
I had to turn back and open to the woman who directed us over,
that passage of our dear Lord`'s conversation with the Samaritan woman.
She appeared glad of the freedom I took in explaining it to her understanding,
as was also a younger one, who stood by her.
Many doubtless are the scattered sheep,
without an outward shepherd rightly to direct them.
Soon after we left the ferry, it began to rain,
and we stopped at a house by the fording place over Packolet river;
and after some pleading, Josiah and I got entrance,
the Friends in company with us going back about a mile with our horses.
We were taken into a weaving room, with a little fire on the hearth,
where we sat contentedly drying ourselves, not knowing:
where we might be permitted to lay our heads this night.
After a while we were conducted into another room, with an earthen floor and a good fire,
where we ate our suppers.
Although the man gave us no great expectation, yet we were furnished with a bed;
in the morning he went to the river with us, to direct us over the ford.
I parted from him in the love of the gospel,
after being engaged to open some of the truths of it to his mind.

"`25th.--A prospect of labour opens within Bush River quarter.
Lord keep me, and preserve me in patience, devoted in heart to do your blessed will.

"`27th.--To Paget`'s Creek meeting, which was large, but long in gathering;
and when mostly settled, a rude company came past and disturbed it.
Yet through favour we had a pretty good meeting afterwards.

"`28th.--This morning after breakfast, our friend John Clark called for us,
and after a sweet opportunity in the family, we proceeded toward Rocky Spring.
It began to snow about three hours before day and continued until about noon,
the bushes and trees were loaded with it, and the way was very difficult; nevertheless,
it has been a day of favour to me--for although
I ate nothing but a piece of cake for my dinner,
and a drink of water by the way,
through the extension of divine love shed abroad in my heart, all was pleasant.
My dear and precious wife was brought very near in spirit,
and my prayers were to the Lord, who had so mercifully opened to me the fountain of life,
that she might be a sharer in the same.

"`29th.--A very cold night, water froze to a considerable thickness on the table.
Had a suffering time both inwardly and outwardly at the monthly meeting at Bush River,
from which we went home with Isaac and Charity Cook.
Ah, what a poor unworthy slipping creature I am; may care and circumspection be renewed,
so that I may know preservation from secret faults.
I am in heaviness this evening, not so living as I ought.

"`30th.--Another very cold night and a suffering one; it would not have been so,
if the deceiver and deceit had been more narrowly watched against.
Lord Jesus forsake me not in my labour and travail in this remote land.
Went to Bush River meeting, and although it was long in gathering,
and the minds of the people for a considerable time unsettled;
yet we were at length I trust favoured,
and my mind opened to deliver some weighty gospel truths.

"`31st.--Set off early this morning for Mudlick meeting, accompanied by Isaac Cook.
A poor little company collected, but we fared much better than I expected.

"`First month 1st, 1793.--To Raban`'s Creek meeting,
held in a poor house with an earthen floor,
which was damp with the beating in of the rain and snow.
I thought on sitting down that it seemed a very poor beginning,
but I was enabled to preach the gospel amongst them, and came away easy.

"`2nd.--After riding all day, we lodged in a little cabin, and met with Samuel Pearson,
who expects to go with us to Georgia.

"`3rd.--Went to meeting at Allwood`'s very poor, and continued so for a season,
but to my admiration my heart was greatly enlarged in gospel love, and my mouth opened,
and trust it proved a profitable season;
after which we proposed to get on our way ten or twelve miles,
but I was discouraged on account of my feebleness,
and concluded to take an early start in the morning.

"`4th.--Arose before daylight, and proceeded on our way;
stopped in the woods twice and fed our horses; crossed Savannah river,
which is three hundred yards wide, at M`'Koy`'s ferry, and also Little river.
The sun shining in our eyes,
for some time we could not see the landing place on the opposite side;
and being strangers to the ford, we did not go right,
and I have not been so much tried in crossing any water since we left home.
My heart is thankful for this preservation,
and for the many others we have through mercy experienced.
Travelled most of this day along a lonely desolate path,
with notched trees for our guide, and but few inhabitants by the way;
arrived at our friend William Farmer`'s about sun set,
and think we must have rode nearly or quite forty-five miles.
This kind man met us at his gate, and upon querying whether he could take us in,
his habitation looking so small, he cheerfully answered, he had feed for us and horses,
and would do as well as he could for us.
This is the smallest house I think I remember to have been in;
but we were favoured with enough--his heart is larger than his house.
He told us that four years ago, when he settled here,
his wagon was their dwelling place for some time;
at first ho built a little bower or tent, but a storm blew off the roof,
and they took again to the wagon for shelter.

"`5th.--To the monthly meeting of Wrightsborough; on the way and in the meeting also,
my mind was under close conflict, and I felt spiritual death increase on me,
and told my companion on the way,
that if my friends did not rise up in spirit and help me,
I feared I should sink and do nothing amongst them.
Thus I continued for a time in the forepart of the meeting;
having to look over my stoppings along in this journey,
also to remember the hand of my God upon me nine years
ago in sickness and deep affliction of soul,
wherein I was made willing to follow Him for the sake of his divine presence;
who then was mercifully pleased to hear my groans,
and take my engagement to answer the debt, when called upon.
Under a sense of his protecting care and divine providence,
in leading and also feeding me,
and having enabled me to reach that part of these southern lands which was then shown me,
my heart, in the midst of my afflicted state, was broken; and after venting a few tears,
I was willing to close this silent part of the meeting.
Friends proceeded to their business, and alas! how I was disappointed.
Often on the way I was pleasing myself with the prospect of getting amongst a tender,
hopeful people, who would receive me with open arms,
and that I should visit them from family to family; but instead of this,
I do not remember to have had closer things to say in any meeting.
My spirit was oppressed and grieved;
but having with honesty endeavoured to discharge my religious duty, I felt peaceful,
and we returned to our friend John Embree`'s, who received us kindly,
where I feel much relieved this evening.

"`6th.--Felt much at liberty in my mind this morning,
which continued on the way to meeting,
and I thought it was likely I should be favoured with an open relieving season;
but on the contrary, I sat the meeting through in silence,
and at the close told the people who were not of our Society,
that I felt much love toward them, but had not so learned Christ as to tell the people,
like some, to come together and that there would be preaching on such a day,
and that in a time of spiritual poverty I dare not put forth my hand to steal.
I then requested that they would leave me with Friends,
for I wanted to see them together, which, after a time, was mostly complied with,
and I had a close searching time with the members of Society;
a number of whom gathered about us after the meeting broke up, and were loving and kind.

"`7th.--O, the conflicts of my soul last night and this morning,
in which dear Josiah was my companion.
I hope the Lord, in his wisdom and love,
baptised me measurably into a feeling of the death and sufferings of my Saviour,
and thereby caused a willingness still to follow Him in the way of the cross.
'`Know you not, that as many as were baptized into Jesus Christ,
were baptised into his death.`'
We had a solid opportunity in this family, and then joined by a number of Friends,
went to an appointed meeting at William Farmer`'s,
who met us about five miles from his house,
and told me he had been up since about midnight,
providing seats and fitting up a shed to hold the meeting in.
He met me in a broken and tender manner; and the prayer of my heart was,
that according to his faith in God, so might it be done for him.
It proved a good meeting, as appeared by the brokenness of some,
both in the meeting and afterward; although there were some who laughed and jeered,
who were sharply reproved.
A number of the neighbours came back in the afternoon,
amongst whom we had a precious season,
and they parted from us with the desire that the Lord might go with us.

"`8th.--Set off at daylight accompanied by our friends James Galbraith and Samuel Pearson.
William Farmer and his brother Benjamin,
also went as far as Little River to see us safely over that difficult ford.
After crossing the Savannah river,
we stopped at the ferry house and refreshed ourselves with provisions we had with us,
and fed our horses.
I proposed to the landlord to see his family together in a religious way;
which was readily granted, and we were taken to a house at a small distance,
where we found his wife sick.
The family were soon gathered, and I had an open time amongst them,
which appeared to be much to the satisfaction of the parents.

"`9th.--Stopped and had a meeting with the scholars in the meeting or school-house,
which afforded peace to my mind;
and I had a sweet and comfortable ride most of the morning
through the wilderness--crossed the Saluda at the island ford,
which was somewhat trying, but got safely over.

"`10th.--Feel better in health this morning, after a comfortable night`'s rest;
went to the week-day meeting at Bush River, accompanied by dear Mary Pearson,
who came before breakfast to see us.
It was a conflicting silent meeting.
O, the death and heaviness which overspread my mind this day, and continues this evening;
I do not feel strength enough to appoint a meeting here tomorrow;
therefore wait in patience, O my soul, under the baptism of death.

"`12th.--Went to the meeting of ministers and elders;
where we met with dear David Vestal and his companion,
on a religious visit to these parts.
It was an exercising time to me, and no opening to labour in the forepart;
but I hope we were afterward profitably in our places, in the business of the day.

"`13th.--To a very large and laborious meeting at Bush River,
the house not containing the people.
The wicked, unruly, and dissipated ones were warned;
and I hope the seeking traveller encouraged to hold on his way.
I was much spent, and after taking some refreshment,
laid down under exercise and conflict of mind, being tried ever since we left Georgia,
with a prospect of returning back,
and through favour there is a willingness begotten to be obedient,
and to do all that my good Master may open and qualify for.
O, my soul, your dwelling has of late been as amongst those who kill the divine life;
hope and trust in the Divine arm, to be carried through;
that arm which has hitherto at seasons been made bare for your help and deliverance,
and by which the mouth of the murmurer and complainer has been stopped;
and this is cause of thankfulness.

"`16th.--A rainy day: kept house and employed myself in reading, writing,
and looking over letters from my dear family and friends, who have sympathized with me:
and although it has been, in some degree, a quiet improving day, nevertheless,
I am a poor servant; yet hope for more favoured times.
Is not all good which is ordered in divine appointment?

"`17th.--Set off this morning after breakfast, and it has been a peaceful day,
although turning my face from home.

"`18th.--Accompanied by our two Friends Marmaduke Mendenhall and Richard Batten,
with David Vestal and his companion, and Benjamin Farmer, we got well over the waters,
though we had to ride about ten miles round in order to
avoid Little River ford and find a good bridge.
Reached our friend Benjamin Farmer`'s cabin in the
evening--and although I felt poorly most of the day,
and under some discouragement,
nevertheless my mind was supported and borne up through all.

"`19th.--Lord, why should such a worm as I am, murmur or complain,
when you in infinite love condescended to dwell on earth;
condescended to men of low estate, and took up your abode with the poor of this world;
thereby to set all your servants an example of humility and lowliness.
O, how sweet is your presence,
whether experienced in the habitations of the rich or of the poor,
or in the wilderness and lonely places.
How are your servants blessed, O Lord, who are favoured to cast their care on you.
Went to a meeting at William Farmer`'s, held in his new unfinished cabin,
which he had fitted up for the purpose, and upon the whole it was a commodious place;
this meeting was appointed by David Vestal and Isaac Wilson, his companion;
I had some service in it.

"`20th.--After breakfast, came ten or fifteen Friends and friendly people,
from Farmer`'s settlement, on their way to meeting, most of them on foot,
having walked eight or nine miles.
It rejoiced me to see their zeal; and after we were gathered, it was a large meeting,
more than the house could contain, and I was, for once in this place,
favoured with an open and measurably relieving time, for which I was thankful.
It is eight months this day, since I left my dear wife, mother and children,
and the tender solicitude of my heart goes forth on their account.
May divine mercy and kindness be near and bear up the spirit of my dear companion,
and as he is doing and has done of late for me, so also to remember her,
and make hard things easy and bitter things sweet.

"`21st.--To a large and mixed meeting, held at the house of Marmaduke Mendenhall,
which was pretty laborious, but hope there were some tender minds.

"`22nd.--Unwell, but peaceful and easy.

"`23rd.--Enter my forty-fourth year,
(O. S.) and I have been favoured since I awoke from sleep,
with a little space of sweetness of mind in quiet.
O precious stillness, how good it is!
Rode to meeting, and such was my feebleness that my knees trembled under me; but,
thanks be to Him who is ever worthy, it proved an instructive time to seeking,
sober inquirers;
after which we requested the active members of our Society to stop with us,
and had a searching time among them;
some were disposed to confess their faults one to another,
and I hope things are on the mend: but O,
what conflicting seasons I have to pass through in this place.

"`24th.--Spent this day at our friend Daniel Williams`' in an exercised state of mind,
and feebleness of body.

"`25th.--A morning of close exercise of mind,
but no opening to any religious service amongst Friends; it would be pleasant,
through divine help, to be favoured to break a little portion of bread,
after it is blessed.
It is a trying state, not to know where to go or what to do.
'`Foxes have holes, and the birds of the air have nests,
but the Son of Man has not whereon to lay his head.`'
If it was thus in the green tree, the Son and Heir of all things, wait in patience,
O my soul, under every painful dispensation, that so,
having fellowship with your Lord in suffering, in the day when he shall appear,
you may be prepared a little to rejoice with him; who, when he comes,
rewards amply for all our suffering.
After breakfast walked out into the woods under thoughtful exercise,
and on my return found J. E. in the house,
with whom my companion and I had a solid conversation.
He acknowledged with tenderness,
his gratitude that the Lord had turned us back amongst them,
and that we had been made instrumental in the hands of Christ,
to open the prison door for his enlargement.
He said that our turning our backs on them,
appeared like shaking the dust off our feet against them, which was affecting.
My spirit felt a little revived, after encouraging him in the way of peace.

"`26th.--Spent this day in no small affliction,
feeling as in an imprisoned state--seeing nothing to do,
and so far and so long from home.
O for patience and resignation in this proving condition.
Not my will, O gracious Lord and Master, but yours be done.

"`27th.--Went to meeting, and sat for a time under conflict,
but at length was opened and favoured measurably to relieve my spirit,
in a close and searching testimony.
It was again a crowded meeting.
After which I had to return to my former state of trial and pain of mind.
I remembered Samuel Bownas, who speaks of the same being his experience.
I believe mine is on account of, the state of things hereaway, or at least measurably so:
who can rejoice when the seed (Christ) is under oppression in professors and profane.
O! what a wicked spirit has reigned in these southern lands,
and what a lack there is still amongst all sorts of people,
of honouring the God of their life, breath and being!
Went home with Francis Jones;
in the evening we were favoured with a precious baptising opportunity in this family,
with a number of the children, and afterwards my bed was made sweet and easy to me,
although unwell.
The Lord be praised for his preserving care, which keeps the poor tossed mind in patience.

"`28th.--Spent part of this morning in walking abroad, and part in reading.
It is a warm day, in which the frogs are tuning their notes of praise,
answering the end of their creation.

"`29th.--A wakeful night, in which my home was brought nearly into view.
Surely I should faint,
if it were not that there is a grain of living
faith preserved in this poor earthen vessel.
I felt weak in body and exercised in mind, after I arose from my bed.
Lord Jesus,
shall I again witness times of greater confirmation in
the way and work to which you have,
in unsearchable wisdom, appointed me!
Wait in patience, O my poor tried soul, even in the deeps.

"`30th.--The meeting today, in the forepart, was a time of serious looking back,
and retrospection into my conduct in days past.
When the Lord humbles the creature,
and gives it clearly to see its own insufficiency and need of superior aid,
how it hides pride.
Before the meeting closed, I imparted some of my feelings,
and thought I was dipped into the states of some,
to their encouragement in the way everlasting.
My bodily strength is renewed, and I am more easy and quiet in spirit,
for which favour I feel thankful in heart to the Preserver of men.

"`Second month 1st.--Went to J. J.`'s,
and was favoured with a comfortable sitting with these young married persons;
left them with sweetness and peace and went to S. M.`'s,
where we had a religious opportunity,
which I hope will not soon be forgotten by either parents or children.
This family, amongst many others in these parts,
were robbed and spoiled in the time of the late war.
Their house was burnt, and one of the children told us,
that a man who was instrumental in spoiling their goods,
was at meeting last fourth-day week, in which I had to speak to murderers, thieves, etc.,
and pointed out to them the necessity of endeavouring
to do all in their power to make restitution.
The child observed that he seemed much brought down, and his lips quivered.

"`3rd.--Went to meeting, which was a pretty open time,
and when it was over Friends took an affectionate leave of us.`"
After a religious opportunity which he had with an individual, he says:
"`O what close things escape my lips.
Lord, I am in your hand; purge me from all the dregs of malice or bitterness,
and look down in mercy on this family.
When we were about leaving them, N+++_______+++ took me aside to speak to me;
and as I had told them I stood open to hear anything they might have to say to me,
and now was the time if they had anything to object against my conduct,
and not when we were gone--I thought he was going to make some objections,
but instead of that, he freely confessed that he had done amiss in several respects,
and acknowledged that I had been made, in the divine hand, an instrument of good to him;
'`for,`' said he, '`I have been a wicked man.`'
This youth with others had been the cause of much grief
and exercise to my mind in the first meeting we were at.
I now parted from him in tenderness and love,
and he desired I might remember him when far separated;
and their younger brother on parting, also told me in an affectionate manner,
that he was never more glad to see any body in his life,
than he was to see us on our return to his father`'s:
we left them with good desires and went home with F. J. and lodged.

"`4th.--We had a solemn affecting parting time with Friends
and others;`"--and after visiting several families,
in which religious opportunities occurred, he remarks: "`Went peacefully to rest,
and for the favours of this day I bow in thankfulness to the Lord.

"`5th.--Found a Friend in the house when we arose,
who came seven miles this morning to see us.
O how precious is true love manifested by the poor amongst men--the
widow`'s mite was precious when seasoned with this.
Called to see a Friend and his wife who were sick, and had a pretty open opportunity,
in the close of which I kneeled down and prayed
to the Almighty to preserve my dear friends,
and also to look down in mercy upon the inhabitants of Georgia;
and felt peaceful and easy after parting from several of my friends here:
got into Augusta before night.

"`6th.--Looked carefully over this town in love,
but did not see that it was required of me to call the people together.
After we had parted from our friends at the bridge,
and got over on the other side of the Savannah river, I saw a company of black people,
men and women, with hand barrows, making a large causeway to the foot of the bridge.
I felt pity flow in my heart toward them, and made a stop and asked them how they did.
My heart was enlarged to preach the gospel as I sat on my horse, to the poor,
who received the sound thereof with tears and brokenness,
and my mind was sweetly comforted in parting from them.

"`7th.--Reached Isaac Cook`'s; and on the 10th attended Bush river meeting,
which was a large and mixed one, very irregular in gathering,
and unsettled in the forepart.
My companion had something suitable to say to them,
and afterward I stood up and laboured zealously and honestly,
to the ease and peace of my mind.
More relief and sweetness graciously afforded, and the way to move forward seems opening.

"`13th.--To Rocky-spring meeting; which was large and mixed.
A number of Anabaptists came to it, and the universality of the love of God,
and the one true and saving baptism were preached to the people.

"`14th.--Accompanied by several Friends,
we arrived at J. G.`'s on the road leading to Charleston,--on the 15th,
after a seasonable, and may it prove a profitable opportunity with part of the family,
pursued our journey through a wilderness country and got to a house kept by a German,
where we made out pretty well, and set off peaceful and easy in mind,
after taking an opportunity to express to him what weighed on my mind,
concerning a future state, slaves, etc.
Stopped by the way and fed our horses, and while they ate,
we also partook of some food,--the ground being our table, as it frequently is,
or else a stump or log.
Provision, however simple or humbly spread, eats sweet to the contented mind; yes,
a contented mind is a continual feast:
the Lord be praised for the many mercies received since I left Georgia;
and may I stand girt about, and prepared for further suffering for the Seed`'s sake.

"`17th.--Went to Edisto, a little meeting of a few Friends and friendly people, who meet,
but have not the consent of Bush river monthly meeting;
yet we were free to stop amongst them,
and such neighbours as inclined to come and sit with us.
We got to the meeting about eleven o`'clock,
but it was not fully gathered until one o`'clock or near it, and held until three;
and it was five before we got any dinner.
This has been frequently our lot in these parts, which is spending to the body,
but mercy and kindness follow us, which has borne up my mind under exercise this day,
and I feel peaceful and easy this evening.

"`19th.--Got into Charleston, and on the 20th went to the week-day meeting,
where was a little company, and I had but little to say.`"

[.offset]
In a letter dated Charleston, second month 19th, 1793,
after describing the many privations which they experienced,
in travelling through a country where there were no regular taverns or dwelling houses,
he alludes to their having to go back into Georgia.

[.embedded-content-document.letter]
--

I wrote you from Augusta that we had to go back again almost one hundred miles,
to Georgia.
I saw it before we left Georgia, and was concerned about my dear companion;
but the blessed Master who has united us truly together as yoke-mates,
gave him also to feel the concern,
and when I hinted on the road that perhaps we should have to return,
after the quarterly meeting of Bush river,
he quickly answered that it was what he expected.
Indeed he was deeply dipped into sympathy with me in that place,
insomuch that he told me he felt almost as if his natural life must go,
and was pondering in his mind what would become of me.
This was joyful to me,
because I found we were baptized by the same spirit into one living
concern for the resurrection of life and the increase of it,
amongst the people; and such baptisms make near and dear one to another.
We not only left Georgia, but also Bush river, with sheaves of peace in our bosoms.

--

"`23rd.--O my poverty and weakness!
Where is the righteous man to stand in the gap?
yet I hope there is a seed preserved even in this wicked place.

[.offset]
At Charleston, under date of second month 23rd, 1793,
he wrote the following letter to his beloved friend John Pemberton.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to John Pemberton

I received your letter dated eleventh month 26th,
on the day after our return from Georgia to Bush River: it met me at a seasonable time,
and the contents were then, and continue to be,
as the oil of joy and consolation to a poor and often mournful soul.
I have passed through very close exercise, and my path has been deeply proving,
especially in Georgia, a place of which I seemed to have a prospect,
a number of years ago, when confined to the bed of sickness,
and at a time when the heavens appeared as brass, and the earth as iron.
O the pangs,--the unutterable anguish I had to pass through in that day,
when I was brought into a willingness to say, '`Lord,
be graciously pleased to remove this heavy stroke from me,
and if you lead me forth to the end of the land,
and will go before me and favour with a sense of your love and acceptance,
I will follow you,`'--and this covenant has been
frequently and humblingly brought into my view.

There were eight or ten days between the monthly
meeting of Bush River and the quarterly meeting,
and I was free to make use of this time in going to
Wrightsborough and attending the monthly meeting there,
hoping it might be the means of encouraging some to get out to the quarter,
who otherwise would not.
We accordingly attended the monthly meeting, and the meeting on first-day,
and were much shut up as to public service,
although there was a considerable flocking to meetings, both by Friends and others.
We were both much pained under a sense that something was out of order;
and in a private opportunity, the state of things was opened to Friends,
in a manner which excited their admiration,
seeing we knew so little by outward information.

After the two meetings above mentioned,
and one with a little company of hopeful Friends, ten miles nearer to Bush River,
we left them and proceeded to the quarterly meeting; but before I left the place,
I was made sensible that my will must be resigned to turn back again,
and I was not a little concerned about my dear companion,
but on giving him a hint how it felt to me, to my great joy,
I found the same invisible hand had been at work to prepare his mind for the trial.

After the quarterly meeting we returned,
and were dipped more deeply into the state of things,
and were happily favoured to feel and see the healing waters stirred among them:
we stayed to another monthly meeting,
and left the settlement with the reward of enriching peace in our bosoms.
Our first day`'s journey on our return was to Augusta, having passed a nearer way before,
but now were under a necessity to go through that place on account of the high waters.
I endeavoured carefully to feel whether it was my place to have a meeting in the town,
but did not see that it was, and so passed quietly away,
but not without the flowing of love and good desires in my heart for the inhabitants.

After we had passed over the great bridge of Savannah,
I saw a pretty large number of poor black people, both male and female,
carrying dirt on hand barrows to make a cause-way.
At first sight of them I felt pity flow in my heart toward them,
under a sense of their burdens--and after expressing my sympathy with them,
I found a necessity laid on me to pull off my hat and
preach to them the gospel of Jesus Christ,
their suffering Lord and Saviour.
It was a solemn time; and when I took off my hat, they did so likewise,
and threw aside their tools; and there was loud weeping among them.
In thus unexpectedly labouring among this Ethiopian congregation,
(not having the least thought of such a thing
five minutes before,) there was no lack of words,
or of that seasoning sweetness which makes right words reach the heart,
and under this precious sense,
it would have been as my food and drink to have spent myself in labours of love,
if instead of twenty or thirty, there had been as many hundreds:
great was the sweetness which attended my mind on the road after leaving them.

We spent several days at Bush River; attended several meetings, visited some families,
and laboured with a committee of the monthly
meeting for the freedom of some black people;
we also stopped at a place called Edisto,
and had a meeting last first-day,--a few in that
neighbourhood being convinced of Friends`' principles.
We arrived here on third-day morning,
and next day attended the little meeting held in this place,
and sat with the few members,
and two Friends who were part of a committee appointed at Bush River,
by request of the meeting for Sufferings, to take some care of matters here.
I wish there had been more zeal and willingness in that committee,
which consists of eight Friends.
I sat most of the meeting in silence, taking a view of our poor, desolate Society here;
how she sits as a mournful, bereaved widow, her walls thrown down,
and her gates burned with fire.
It has appeared to me that Truth, the pure, unchangeable, precious Truth,
will not flourish in this dissipated place,
until the righteous God of Truth rises up to assert his own sovereignty;
and under this sense I have rested peaceful and quiet, feeling very poor and small,
and the prospect of only staying and sitting in Friends`' meeting tomorrow,
appears a weighty thing.
We have had the company of a number of the inhabitants at our lodgings,
who have manifested civility and kindness.

I hope we shall leave this place after attending two meetings tomorrow.
Bonds and afflictions are our companions both in towns and country places;
and my desire is to be strengthened to endure hardness,
as a good soldier of Jesus Christ ought to do, even to the end of this journey,
and in and through whatsoever my merciful Lord may be pleased to lay upon me,
to the end of my pilgrimage.
I sympathize with you, my dear friend, under your continued exercise,
although I may not at present write much on this subject.
I have admired at seasons how it was with me before I wrote to you from Virginia:
perhaps I may say, that not a day passed and frequently in the day,
without your being brought feelingly into remembrance,
until I relieved my mind by writing to you, since which,
that weight of solicitude has abated.
I still believe, that as you patiently wait, a day of deliverance will come,
and that your labours in a foreign land will not all be like water spilled upon a stone.

My love to your dear wife, and father,
Isaac Zane,--may his bow abide in strength to the end.
O how precious to behold such greenness in advanced age!
Such may well be compared to Caleb, who feel as strong in spirit for the Lord`'s work,
as when he first led them out of Egypt`'s land.

I had like to have forgotten to mention,
that I received a bundle of books since we came to this place,
which I have parcelled out and sent back into the country,
to the care of Friends in remote places, to lend to their inquiring neighbours,
and have written such a request in them.
Some went to Edisto, where there appears to be a considerable stir among the Methodists;
one or two I sent to a Baptist preacher,
who I heard was well pleased with being at one of our meetings,
although I thought it a low, exercising time;
and some others I have engaged a Friend either to send or take himself,
to a man who treated us with much Christian love,
on our way from Tom`'s Creek to Bush River.
Indeed I have thought that some of our rich merchants,
who have traded long in temporals in our favoured city,
might open an enriching trade in spiritual things, to some of these back parts,
where the name of a Quaker is hardly known, by taking a wagon load of books,
and judiciously distributing them,--and thus be engaged in laying up treasure in heaven,
where neither moth nor rust can corrupt, nor thieves break through and steal.
O that the day may be hastened when men will be
more engaged to spread the noble Truth of God,
than to be laying up treasures here on earth, to the corrupting, and I fear,
to the utter destruction of some of their children.

--

"`24th.--Attended meetings in the fore and afternoon, which were small;
and although trying to my spirit, and the labour exercising and close,
yet I was favoured with a solemn calm, which was precious,
and a belief that the Lord has witnesses in this licentious place,
and my heart yearned towards them in their several places of worship.
We had the company of a goodly Methodist at J. K`'s;
and another good man told me his state was spoken to,
and he hoped it would prove a blessing to him:
he also seemed desirous we might appoint a meeting amongst them,
signifying there would be a willingness amongst his brethren to come;
to which I could say but little.
We had a pretty solid sitting this evening in D. L.`'s family, with several other Friends;
and my dear companion says the meetings in this place were solid and profitable;
that he beheld the tears trickling from the eyes of some, to whom he felt much love:
may the Lord be praised for preservation and so favour
us that we may do nothing against the Truth;
for it appears that no mighty works are to be done here.

"`25th.--Arose from my bed peaceful in mind,
and conclude to stay until tomorrow in this place.

"`26th.--Set off after breakfast and a solid tendering opportunity with D. L.`'s family,
and parted tenderly from them and also some of the blacks,
and were accompanied by several Friends about sixteen miles.
After we parted from them I had a broken time on the road,
in considering our lonely situation in a strange land, and feeling such great poverty:
however we travelled along and comforted one another.
Stopped and fed our horses near sunset, and afterward rode nine miles to M. M.`'s,
and lodged, where we found a quiet house and no company,
which was a comfort to my exercised mind.

"`27th.--We are indeed strangers in a strange land,
yet mercifully favoured with quietness and patience--a favour for which I am thankful.
Set off after the rain was over and rode to Nelson`'s ferry on the river Santee,
about eighteen miles, where we found the water so high that they would not put us over;
which was a discouraging prospect.
They told us we must ride up the river ten miles, to Manningoe`'s ferry;
so we sat off in company with a woman who was at a store by the river side,
and said she was going home about five miles,
and would put us in the way through the plantations.
We accordingly accepted of her kindness,
and after we had refreshed ourselves at her house, we concluded to stay all night.
This is a trial of faith and patience,
but I found it good for me to turn my mind to
feel after that Fountain of love and goodness,
which I at times recommend to others.
'`Your Maker is your husband, your Redeemer, the holy One of Israel,
the God of the whole earth shall he be called.`'
O that I may hold fast my confidence in him!
Spent part of this evening in reading Benjamin
Holmes`' '`Serious Call,`' to the man and wife,
some of the children, and a young man, a store keeper who lodged here;
I hope to some profit.
I should myself have felt more comfortable if I had abode in true contentment.
O what a very poor creature I sometimes feel like,
when I only deviate as in a tittle from the pure law of life.
O that my slippings may be instructive to me,
and bring me more and more into the divine fear.`"

"`28th.--After crossing several streams and swamps,
which was attended with considerable hazard, they arrived at Manchester,
where they lodged: in relation to this ride he remarks, "`A desert,
lonely ride this afternoon;
but what are all these outward light afflictions compared to that sense of
poverty and distress which my poor soul has been plunged into this day.
Where are all boasted acquirements,
when the Lord is pleased to veil his sweet presence and
leave the soul to combat with death and sorrow.

"`Third month 1st.--Very poor and distressed this morning,
and hardly ever felt more so than on the road:
a wilderness ride indeed both inwardly and outwardly.
Lord, be graciously pleased not to leave me in my distress, but help your poor servant;
is the cry of my soul.
O that I may be more and more redeemed, and my body made a temple for the Lord my God.
What is man when deprived of the sweet incomes of his love.
I have borne chastisement, and I desire not to offend; that which I see not teach me,
and if I have done any iniquity, purge me and enable me to do so no more.
O the bitterness of death! would to God the children of men,
the unthoughtful children of men, would consider and turn from their transgressions,
that so iniquity may not prove their ruin.
Stopped after riding about twenty miles,--Josiah`'s mare appears sick and will not eat;
but we got into Camden about two hours before night, where a kind man took us in,
and very hospitably cared for us.
We sat on our horses sometime, in the street,
waiting for him while a negro man went to seek him, hardly knowing what to do,
or where we should lay our heads.
After breakfast next day, being greatly tried between a prospect of staying and going,
I was favoured to hear a language like this, '`it is enough,
move forward;`' so we parted from these hospitable people and some others,
after expressing what rested on my mind.
They would take nothing for our stay with them, and sent their good wishes after us,
and a goodly old farmer present gave us a hearty blessing.
Now my spirit was set a little more at liberty, and although we set off in the rain,
the road was pleasant and delightful,
because the darkness and death were in some degree removed,
and my dear companion and I had a solid profitable
conversation respecting our various trials,
and the Lord`'s mercy and care over us hitherto;
which was a season of setting up our Ebenezer.

"`6th.--To Gum Swamp meeting, which was large,
some of our friends getting up before day to give notice.
I went to it in great poverty,
and after a time apprehended I felt a little opening to stand up,
but found it hard work to get along, and after I had stood sometime,
the carelessness and inattention of the people appeared great,
insomuch that I was defeated in my first prospect,
and I was under a necessity to sit down, believing it safest so to do, as Truth rose not.
But toward the close of the meeting,
I ventured to stand up again and then had close and searching things to deliver,
to a state that is always ready and full of activity, in the will of the creature,
and had to tell them that there were sighs and groans which at seasons cannot be uttered,
which were more acceptable than a multitude of words, songs, prayers,
etc. in man`'s will and time.
Dined at J. T.`'s; after which,
and kneeling down in their family and praying
for the help and protection of the true seed,
scattered in this desert country,
and that the Lord Almighty might turn and overturn all false ways and worships,
and make way for the worship of his dear Son, in spirit and in truth,
we left them and called at W. B.`'s, who has given up to accompany us.
We got to our friend M. C.`'s, at Pedee, twenty miles, after night.
I have since understood there was occasion for the singular line in which I was led
at Gum Swamp meeting,--one appearing amongst that little company who is a burden,
and the Anabaptists much opposed to Friends in the neighbourhood.

"`8th.--It began to rain hard before day, and continued so until near nine o`'clock.
We set off and missed our path to the main road, and had to ride four miles back;
about three miles further we came to a creek which our kind guide entered,
putting the wallet containing our food and horse feed on his shoulders.
It proved so deep as to require him to swim his horse some distance down the stream,
and the water came up nearly to his breast.
However, he got safely through and went up to a house which was near,
and was directed by a woman to a ford higher up.
As we were going to it and had nearly got opposite, he without much thought,
being wet before, rode in.
This, although narrower, was more rapid, and took his horse from under him,
he kept his feet in the stirrups and the saddle
happily having no girth let the horse loose:
he held him by the bridle with one hand, and clung to a bush by the other, until Josiah,
who was foremost, got to his assistance, and both he and the horse were saved.
When he came out of the water both feet were in the
stirrups,--a deliverance for which I am thankful.
We rode up the creek, crossing one little branch after another,
until with difficulty we got over, and rode to the house where our guide left his wallet,
and while he and Josiah cared for the horses,
I went and hunted pine knots to make a fire to dry our friend and Josiah,
who were very wet.
We have been from nine o`'clock until one coming four miles.

"`9th.--Arrived at our friend J. T.`'s, where we were affectionately received,
and I am afraid of rejoicing overmuch in being thus indulged
once more to be in a settlement of my dear friends.

"`10th.--We went to meeting, +++[+++Deep River]
and the house could not contain the people: yet it was but a low time;
I had a little opening to stand up with,
but although I humbly hope it was from the living spring,
yet I could not get along with satisfaction to myself, and so, soon sat down.`"

They proceeded toward Lynchburg, and on the 14th,
after a slushy muddy ride we got to John Pannel`'s and lodged.

"`15th.--At the house where we stopped for breakfast,
almost as soon as I got to the fire,
the woman looked toward me and addressed me somewhat after this manner;
'`I understand sir, that you are a man of authority, a minister of the gospel,
and a teacher of ignorant ones.
I am one of those poor creatures, and should be glad to hear a word of exhortation.`'
I told her I was a poor creature, and had but little for myself,
and after some more conversation on the subject she dropped it,
and went to see about breakfast; and while I was eating, was kindly attentive to me.
After breakfast I walked abroad under thoughtful exercise of mind,
and as I was returning into the house, these expressions fastened on my mind,
'`He has showed you, O man, what is good; and what does the Lord require of you,
but to do justly, and to love mercy, and to walk humbly with your God?
And I felt strength and encouragement to invite her,
with her husband and two neighbours who were about the house, to sit down;
and I thought we were favoured with a good time:
I understood afterward by one of our company,
that it was much to this religiously minded woman`'s satisfaction.

"`16th.--To the monthly meeting of South River,
which was an open time in the first meeting,
and I hope a profitable one in transacting the business, although a searching time;
we got to C. Johnson`'s near sunset.

"`17th.--To the first-day meeting, which was large, the house not holding the people;
and I have not experienced such an open time to preach the gospel for months past,
and was favoured through the prevalence of divine goodness,
to water and be watered myself Friends after meeting were affectionately kind to me.
Went home with our friend John Lynch near the meeting house,
and had a solid opportunity in the family, several others being present.

"`18th.--Sat down and wrote a letter to the little
company of persons who profess with us at Bannister;
principally directed to Elizabeth Hendricks,
who was the first that stood forth in the cause of truth in that neighbourhood.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Extracts from the letter.

[.signed-section-context-open]
Lynchburg, Third month 18th, 1793.

[.salutation]
Beloved friend, Elizabeth Hendricks:

As it is not likely I shall have an opportunity to see you,
I thought I should be most easy to sit down and inform you,
that since I first heard of your religious concern to be found
building up and repairing the waste places in Zion,
it has had a sweet savour in my mind; and the desire of my heart is,
that the Lord may strengthen you to hold on with faithfulness and firmness in the work.
Mighty is he who calls forth his devoted children and servants; may you,
dear young woman, with your dear sister, with whom I gained some acquaintance,
your other relations, and all concerned ones in the neighbourhood,
where your lot is cast; keep in the divine fear,
for in the fear of the Lord there is strong confidence,
and his children have a place of refuge to flee unto in every time of need.

Therefore, know him to be your sanctuary; wait upon him in humble depending patience,
in all your meetings,
and your minds will be animated and lifted up above the world and the fading,
perishing things of it.
Be often found, through the day,
when your hands are employed about the lawful business of fife,
lifting up your hearts to God for protection and support.
For be assured that there is no state in which
preservation from evil and unprofitable thoughts,
is more likely to be experienced,
than in a habitual and constant communion with the God of our lives.
When we meet with temptations of various kinds, by often looking to him,
a secret yet living hope revives in the midst of tribulation,
that the temptation will have an end, and that the Lord will make a way for us to escape,
as we hold fast our confidence in him; as the Scriptures declare,
blessed is the man that endures temptation; that is,
who dare not fly from the Lord in this proving season;
which will be but as for a moment to the upright in heart.
After these have nobly stood their ground, they receive the crown of life and peace,
which the Lord has promised to all them that love him;
and thus our many and various afflictions and trials, which are necessary to humble us,
if rightly abode under, bring us nearer and nearer to the righteous God of our lives.
I have heard of singular instances,
in which divine goodness has supported even an individual,
or individuals although few in number,
who have been concerned to bear a public testimony,
by sitting down in a religious meeting in order to wait upon and honour him;
and in time more have been drawn by such an example to come and do likewise,
until at length there has been a meeting of spiritual worshippers gathered,
who have been made as lights in a neighbourhood.
The Lord loves cheerful givers; he loves the gates of Zion,
more than all the dwelling places in Jerusalem:
he loves those who are found watching and keeping the door of their hearts and lips,
and he will appear unto such and dispense the bread of life to them.
Therefore, as you have begun a good work in the face of the neighbourhood,
may you be found seeking strength of the Lord, to enable you to hold on your way:
be kindly affectioned one to another, with brotherly and sisterly love,
in honour preferring one another:
strive to excel one another in innocency and virtuous living,
and you will be favoured to see who is to be held in
the greatest honour and esteem for the work`'s sake,
even such as live the most exemplary lives.
Let no vain glorying or strife be among you;
but remember that he or she who is the least in their own opinion, walking in humility,
circumspection and godly fear, is the greatest.
May you live in love, and then no doubt the God of love and peace will be with you,
and increase you in the increases of his love, favour and acceptance.
He will then accept of your offerings,
although they may sometimes be no more than a secret sigh and inward groan,
which cannot be uttered so as to be heard by others.
The acceptable sacrifice to the Lord is that of a broken heart,
and a contrite and tender spirit in religious meetings,
even when we can breathe forth no more than something after this manner,
in inward desire,--Lord I am poor and sorrowful,
let your salvation appear to lift up my soul,
and engage it to hold on in the way you have cast up for me;
or Lord help me or I shall faint and fall; for he who is a pure and spiritual being,
hears the groans of the wrestling seed within us.
God is a spirit, and they that worship him acceptably,
must worship him in spirit and in truth.
Therefore keep true in heart: be sincere,--remember that the Lord sees us at all times:
sincerity is the life of all our graces, and puts life into all our duties.
If we have not sincerity and truth of heart,
then all our performances will be no more than a dead thing,
offensive in the nostrils of God,
who will not then smell our offerings as a sweet savour.

My dear companion and fellow-labourer in the work of the gospel, Josiah Bunting,
unites in tender desires for your preservation and growth.
We thought to have stopped in your neighbourhood,
but finding that the people on the road knew not how to direct us rightly,
and time being but short for us to go to South River monthly meeting, we omitted it;
perhaps I may venture to say, that divine Providence has so ordered it for the best,
that your expectation of help from instruments may be
disappointed--your attention weaned from man,
and that your hearts and hands may be turned to look unto and lean upon the Lord,
for in him there is everlasting strength.

--

"`19th.--Set off about nine o`'clock accompanied by W. H.,
after a solid religious opportunity with these young friends, and rode forty-five miles.
We stopped about the middle of the afternoon at Hood`'s,
the place where we called the family together when S. P. was with us, six months ago,
and gave them Joseph Phipps`' works, and hope it will be to profit.

"`20th.--This day rode fifty miles; stopped by the way at J. F.`'s,
who appears to be a goodly seeking man:
may the Lord enlighten his mind to see the beauty and excellency of Truth.
These two long days`' rides have been peaceful to me,
and I do not know that I have left anything undone that causes pain.
The Lord be praised for his protection and help so far:
we arrived at our kind friend Samuel Couch`'s after seven in the evening.
It is ten months this day since I left my habitation.

"`24th.--Set off for Genito meeting about an hour before the time,
and spent it with dear Mary Pleasants.
The meeting was the largest held in this place,
the house not containing the people by many; and continued in silence nearly,
or quite two hours, and I thought would have concluded so;
but a degree of strength was at length given,
and I trust I laboured honestly once more amongst them,
and hope the meeting ended profitably, although it held three hours and a half.

[.offset]
In a letter written from Beaver Dam, Virginia, to John Pemberton, he says:

[.embedded-content-document.letter]
--

I received your letter at our friend R. Pleasants`',
which at that time was comfortable to me,
and the tenor of it has been peculiarly so since, in a close trial which overtook me,
wherein I had encouragingly to remember this expression contained therein,
'`the work of righteousness is peace.`'
I seem as if I cannot forbear informing you,
that when I have been riding in lonely and wilderness ways,
day after day and oftentimes in the day, my thoughts have been turned toward you,
insomuch that I have had to pause and inquire with myself,
what is the cause that the cogitations of my heart are
so much fixed on an individual in that great city,
where so many dwell whom I nearly love?
Is my beloved friend labouring under close exercise of mind at this season, and am I,
a younger brother, made to partake in spirit with him though far separated?
At such seasons, as now, you have been made near to me,
I believe by Him who metes out the portions of all of us by just weight and measure,
and who has declared that '`the needy shall not always be forgotten,
nor the expectation of the poor perish forever.`'
And if a sparrow cannot fall to the ground without his notice,
surely he will take notice of and record the honest labours of those who,
at his command spend many of their days in endeavours
to gather souls into his everlasting kingdom,
even though little fruit may be visible to them.
After this manner has my spirit been led to look over
your labours and travels in lands very far remote,
and receiving this for an answer, it has been preciously comfortable to me;
there shall be a glorious recompense in the resurrection of the just.

I have thought at such seasons that I could say much more to you, my heart being full,
but let this suffice.
It is my firm belief, that the Lord was with you in your visit among the Orkney Islands,
and the seed which you have sown in that land,
at the command of the great Lord of the whole family of mankind,
shall not be gathered up by the wicked one,
but in the Lord`'s time spring up to the praise of his adorable name.
With regard to your present prospect, my desire is that you may still pray for patience,
and be kept in that patience which enables to run the race,
and at last obtains the crown.
The Lord is on his way, I believe, to set you at liberty, and no matter how,
so that it is seen to be his doing, which will be marvellous in your eyes.
I wish you to live still in that which dare not think the time long,
and which keeps us in true devotion of heart, so as to say, '`here am I, send me.`'

I am persuaded that the more the wife of your bosom, your affectionate companion,
comes to be resigned to the will of an all-wise and overruling Providence,
the more of the incomes of true and lasting peace she will experience.
Submitting to that divine power which qualifies for every good word and work,
in her family and in the church,
she will be prepared in divine authority to say unto others,
'`arise you careless women that are at ease, awake out of sleep you lukewarm,
unconcerned daughters; let us be in earnest to get our day`'s work done in the day time,
for the shades of evening advance quickly.`'
And O that she may ask counsel of God, and wait for it,
with regard to your heavy exercise,
that by an entire resignation of heart in all things to the Lord`'s will,
putting away every weight and burden which may arise from the reasoning part,
true peace may flow into her heart, and the Lord`'s will be done in you both,
by you and upon you,
to the praise of his excellent name in the end--
so wishes your exercised friend and brother,
who has written as things arise, in the simplicity of a child;
and who is a child and needs the care and the prayers of all those his elders,
who love the Lord Jesus in sincerity.

We get but slowly along, but for every little act of faith and labour of love,
there has been a rich reward bestowed by Him who has a right to our obedience.
Dear Josiah is an encouraging, feeling companion,
preserved in much patience under the many singular turns we meet with,
which endears him to me.

I believe the Lord gave me some place in +++_______+++'`s heart when at his house,
and my prayers are, that the Lord may '`smite both his winter and summer house,
throw down his palaces of ivory,
and bring him to mourn in the dust because of Him whom he has pierced.`'
I mourn over him and for him while I am writing,
because I see what an instrument of good he might have been, and may yet be, I hope,
if with unreserved obedience he yields up his will unto
the will of the great Author of his being,
who can as suddenly meet with him as he did with Nebuchadnezzar of old,
when all things may seem to go on pleasantly as to the outward.

--

"`25th.--This morning a sober Anabaptist woman came to see us,
and after a solid baptising opportunity with the family,
and such other Friends as were here, we set off accompanied by several,
and stopped to see a Friend who is confined,
where we had another solid opportunity with him, wife and children;
after which we went to our friend Micajah Crew`'s at Cedar Creek.
The same conflict attended me yesterday, as did in a meeting before at Genito,
and I was painfully exercised in treating with an infidel unbelieving state;
and have been told since, that a person was there again,
who was at meeting when we were here before; and it was remarked by his neighbours,
that what was then said had come to pass, namely: that the time might soon come,
when some would be laid on a sick bed, which he was, and has recovered,
and then they would have to remember the doctrine sounded in their ears;
which it seems he did, for he was brought almost to death`'s door.`"

[.offset]
In a letter to Rebecca Jones, written from Cedar Creek, Virginia, he says:

[.embedded-content-document.letter]
--

Your sisterly token of remembrance, which came safely to hand at Curies,
tended to my encouragement.
O how good and pleasant a thing it is,
when thus separated from our dear brethren and sisters,
to find that we have a place in their minds.
It must undoubtedly have been so with the Apostle,
or he would not have left these feeling expressions on record, '`Brethren pray for us.`'
My mind is at seasons sweetly turned toward my beloved friends of our meeting,
with secret breathings that you may be kept in your tents,
and enabled to worship as in the tent door.
These precious seasons of remembrance I am frequently favoured with,
when riding along the road, and looking back on my dear friends,
and may I not say that one of the greatest favours I enjoy,
is that of sensibly feeling the unity and help of the spirits of my friends.
May I ever be so preserved in lowliness, as not to forfeit this precious oneness.
My dear sister, the harvest is great, great in these parts, and the labourers very few.
I have thought of you and dear Hannah Cathrall several times lately;
whether there are not sheaves that you and other gifted
sisters might come and gather up here in Virginia.
Bear with me,
for sometimes I think I feel a little of the disposition and spirit of Moses,
and would to God there were more made to prophesy,--sent abroad,
even unto the four corners of the earth,
to declare the way of life and salvation through Jesus Christ our Lord.
May you remember, that the night is approaching,
when none can work,--how necessary is it then to labour at all times and in all places,
both at home and abroad, when favoured with a sight and sense of our duty,
that so in the evening of the day, this language may happily be ours,
'`I have finished the work which you gave me to do.`'

--

"`27th.--To the week-day meeting at Cedar Creek,
in which I was exercised in very great weakness and poverty;
but I felt easy and quiet after it.

"`28th.--Spent this day at T. H.`'s, the forepart in close thoughtful exercise,
seeing no way open to move: this continued until after we had dined,
when we went into the sick room; and had not sat long,
before a sweetness accompanied by a solid exercise spread over me,
and I desired that the rest of the family might be called in.
In this opportunity I was concerned to go on my knees,
and beg the continuance of the blessing of preservation to us poor travellers,
and that the Lord might be graciously pleased to open a way,
where none at times appeared;
to bless and favour the heads of this family and all present;
and be near to our aged parents we had left behind, and comfort and support their minds,
as also my dear wife`'s,
and take our dear children more and more under his protection and care:
after which I had an open time in testimony,
which I trust will prove like bread cast on the waters, to be found after many days.
We then visited three negro families on this plantation, to our satisfaction:
indeed it is a comfort to see some of those people live so reputably and well;
they have rented land of T. H. Spent the evening peacefully and pleasantly.

"`29th.--Peaceful and easy in mind this morning:
O what a favour to be indulged now and then to
feel comfortable and quiet in our allotment!

"`30th.--Spent this day at C. T. M.`'s, partly in writing.
After dinner the black children came in with their books to read their lessons,
which they performed cleverly,
and I was comforted in beholding such care and attention toward them.
C.`'s wife came in amongst the men, at the yearly meeting,
to plead the cause of this people, and she might with propriety do so,
seeing she is in her own example what she then recommended to her brethren.
O that there were more such in this land.

"`31st.--To Caroline meeting, where was a gay, mixed assembly; and according to the day,
so was the strength afforded to preach the everlasting gospel; it was an open good time;
several members of Congress were present,
one of whom came to me after I had got into the wagon and said,
'`Permit me to give you my hand, although a stranger, and my best wishes go with you.`'

"`Fourth month 2nd and 3rd.--Stopped at A. J.`'s at Stephensburg,
who accompanied us almost twelve miles on our way to Culpepper.
Ate our dinners on the grass by the bank of the Rappahannock river,
after we had forded it.
Got to J. G.`'s; this has been an evening of exercise, feeling for my way,
what to move in next.

"`4th.--A heavy time this morning:
I cannot see anything that looks easier than to visit the few families of Friends here,
and so am made willing to give up to the prospect,--Lord help me, a poor servant.
Sat down with this family, and it was a watering, encouraging time,
to the father in particular.
We sent for his son and wife, she was with us,
but he plead that he could not leave his men, who were at work.
I hope it was a good time.

[.offset]
Several other families were visited this day,
in which he was favoured with "`baptizing seasons,`"--he remarks:

"`It has been a day of sweetness,--the Lord fulfills his promises to his servants;
He that labours receives wages, and gathers fruit unto life eternal:
blessed be the name of the Lord.`"

"`5th and 6th.--He was occupied in visiting the families about Stephensburg,
in nearly all of which he describes his services as being well received,
and accompanied with a baptising and reaching effect.

"`7th.--A comfortable, refreshing night.
'`I sleep, but my heart wakes; and it is the voice of my beloved that knocks.`'
I feel renewed in my bodily powers this morning, for which favour I am humbly thankful.
Had a large, open, favoured meeting to day at Southland,
which afforded encouragement to my mind.
After I had been pretty largely drawn forth in gospel love to the people,
and had sat down,
I was concerned to stand up again and address the inhabitants
of the little town of Stephensburg in particular;
cautioning and encouraging the merchants and innkeepers
to sanctify the Lord in their occupations,
and the youth to beware of reading pernicious books, such as plays, novels, and romances;
and I trust the meeting ended solidly and well.
After it was over many persons not of our Society came and spoke to me,
and appeared loving.
May the Lord have the praise of his own work,
whose name and truth have been exalted this day,
through the efficacy of his divine power.
It appeared to me, that there will in time be a gathering of such in this neighbourhood,
who will be instrumental in the divine hand to spread the testimony of Truth.
O says my soul, may it be so here, and throughout the earth, that praises, high praises,
may ascend from sanctified and prepared vessels, to the everlasting,
holy and merciful God, who is our only upholder and preserver.
Amen.`"

[.offset]
In a letter to Rebecca Jones, dated Curies, fourth month 7th, 1793, he writes as follows:

[.embedded-content-document.letter]
--

Although it is uncertain when or where this may meet you,
I thought as I felt the springing up of a measure of that love
which unites the children of the heavenly Father`'s family,
both present and absent, I would try to write to you.
Your last letter was sweet and encouraging to my wading mind,
which is frequently very closely exercised,
with earnest desires that I may approve myself, not only unto God and his people,
but to others also, a servant who is not ashamed of the gospel of Christ,
or of those bonds which are its constant attendants.
Unworthy as I feel myself, my lot seems to be cast, more than that of many others,
among those whose walks are, as it were, in the streets and lanes of the city,
and in the highways and hedges; and my concern is to hold on in faithfulness,
clear my way as I go, and endure hardness as a good soldier of Jesus Christ,
that so my return may be with the reward of unshaken peace.
I have been absent from home almost twelve months,
and am now turned back again nearly or quite one hundred and fifty miles,
and the chief service which presents,
seems to be amongst people of other religious persuasions.
We have had several meetings in towns and neighbourhoods,
where large numbers have gathered,
and so far divine mercy and kindness have been near to support and bear me up.
Blessed be the Lord, his goodness and truth have been witnessed, who, even to this day,
gives mouth and wisdom,
tongue and utterance to those that are living in a humble and abasing sense of the
force and truth of those expressions which dropped from his sacred lips,
'`Without me, you can do nothing.`'

It was pleasing to me to hear of the devotedness of my dear fellow
servants who are going to and fro in the service of the gospel;
and that so many have given up to go with the Commissioners into the Indian country.^
footnote:[For some account of the engagements of the Friends
who went to the Treaty with the Indians at Sandusky,
to which Thomas Scattergood here alludes, see the Journal of William Savery, vol.
1st of Friends`' Library, page 331, etc.]
I feel with and for them, and for dear George and Sarah Dillwyn, and Elizabeth Drinker.^
footnote:[George and Sarah Dillwyn and Elizabeth Drinker,
were under religious concern to visit the churches in Great Britain.]
I was also glad to find that you, my sister, who have been going on your way in secret,
silent travail, are likely to go forth in gospel mission,
I trust to water and refresh those abroad,
who may be under the like dispensation in lonely spots and places.
Be faithful, dear sister, in your allotment, that so your reward may be sure.
O how good is the Lord to those who live in devotedness of heart,
fulfilling that ancient declaration; '`Though you have lien amongst the pots,
yet shall you be as the wings of a dove covered with silver,
and her feathers with yellow gold.`'
May the Lord give the word, and in his time,
increase the company of them that shall publish it.

We are waiting the coming on of the yearly meeting,
not without some prospect of further labour out of the pale of our Society,
and can say but little more than that I desire
to live in that spirit which enables us to say,
'`Your will be done,`' even under the most trying dispensations.
Tell my dear friend and brother David Sands, that although when I received his letter,
I was so dull a scholar that I could not fully understand his language, yet since,
I have been led about and instructed more fully,
and believe he was favoured with a lively sense of my tried condition.
May the Lord preserve him, with my own soul, under his divine protection and favour,
through all the various trials which may yet be permitted to come upon us,
and at last crown our end with everlasting peace.

--

"`9th.--This morning I took an opportunity while we were quietly riding along the road,
to inform my companion that a prospect of being at the yearly meeting in Virginia,
had been resting as a weight and exercise on my mind;
and although at seasons the prospect of getting home to our quarterly meeting next month,
looked pleasing, yet my will was required to be given up;
to which he did not make any objection.
So I left it with him; and when after a time, I rode up alongside of him again,
he spoke encouragingly to me, and wished me not to be cast down under my burdens,
but patiently submit to the yoke; observing,
that when I first mentioned my prospect to him, he was prepared for it;
for he had been thinking of the preservations we had been favoured with,
and the trials we had been helped through.

"`10th.--Not many at the meeting but Friends;
and it was a season wherein I had to feel sympathy with, and speak encouragingly to,
a small remnant, exhorting them not to cast away their confidence:
the careless also were called unto; and upon the whole it was a good meeting.
Put up at Fredericksburg at a tavern.

"`11th.--Got to our friend C. M.`'s.

"`12th.--I feel solitary in again turning my back upon home; nevertheless, O my soul,
hope in, and rely upon, the arm of Divine strength,
hitherto mercifully held forth for your help.

"`13th.--C. M. and wife took us to Cedar Creek monthly meeting,
in which I was led to speak, I hope feelingly, and in degree effectually,
to a tried state present.

"`14th, first-day.--Went to meeting: wait O my soul,
to be found doing the will of your God, in this your lonely state.
O for preservation to hold out to the end of this journey! more depth, more patience,
more stability and solidity are lacking to carry through and over all.
The meeting was large and mixed, and was a favoured season;
the Lord be praised for strength and renewed
ability to ease my exercised mind amongst them.
An ancient man, T. M. came to me after meeting, and said, '`you did not number my age,
for I am four score and five;
but you have traced my state from a boy until this day,`' etc.
A young man came afterward and affectionately took me by the hand,
and expressed his desire that the Lord might be my preserver and protector through time,
and at last give me an admittance into his everlasting kingdom.

"`16th.--I am blind and poor this morning; not knowing which way to take, or what to do.
O that I may be preserved in that patience which gains the victory,
and be so kept as to do nothing against the Truth.

"`17th.--To the week-day meeting; and after it, home with Thomas Terrill.
A little before night a number of Friends came, and also an aged man, an Anabaptist;
we were pleased with their kind notice and attention,
and their openness and freedom in conversation; and we read our certificates to them,
mine being directed not only to Friends, but also to solid inquirers after the Truth.
One of the company said he was at both the meetings at Richmond,
and that a gentleman told him,
when noticing what I said concerning the abominations acted in that place,
that he feared Sodom was not more guilty.`"

"`18th and 19th.--Spent in visiting families,
and on the 20th he went to Fredericksburg and appointed a meeting.

"`21st.--To a large mixed meeting held in a room over the market place.
It was quiet and ended well, and my heart is thankful for preservation and favour.

"`22nd.--My mind feels comfortable in looking
back over yesterday`'s work,--good is the Lord,
may my soul say, and worthy to be trusted in and obeyed.
Rode to our friend Thomas Terrill`'s, twenty-eight miles, with a sweet and easy mind.
'`The disciples were not to rejoice that devils were made subject to them,
but that their names were written in the Lamb`'s book of life.`'
O that I may more and more learn this great lesson;
to rejoice in tribulation as well as in favoured seasons.

"`23rd.--Visited a family in which we were favoured with a good time.

"`24th.--To meeting,--a crowded and very laborious one;
but trust the labour will not be lost.
Truth appeared comfortably over us at the close,
and I had to stand up and recommend more care and
attention to the education of the black children,
stirring up the youth in families to engage in the good work of instructing them;
many being present of different societies.

"`28th.--Went to Cedar Creek meeting; it was a comfortable peaceful ride there,
and most of the meeting a season of sweet silence;
but in the close I had a little to communicate to the weak and feeble of the flock,
and in the end to stir up to prize the day of lengthened out mercy,
and while the day lasted to do justly and love mercy,
lest it might be shortened and their judge come as a thief at a time unexpected.
Stopped at Thomas Stanley`'s, accompanied by Micajah Crew and wife,
and had a religious opportunity,
in which the parents were encouraged to attend to their gifts,
and be patient under the various operations of the divine hand;
also to be careful in the education of their children, who appear lovely.
Went home with Micajah Crew under exercise,
it being about nine months since we were first here,
and now have to traverse the same path again, and at this season in a state of blindness.
Wait, O my soul, in humble submission,
upon your never failing Helper for the further unfolding of his will;
although you sit at present in a state of darkness or lack of light.
I find a precious, kind brother and fellow helper in Micajah Crew.

"`30th.--A stormy night, and continues so this morning, and I see no opening to move.
These dispensations are trials of faith and patience,
but when I remember that all things shall work together for
good to those who continue in the obedience of faith,
my mind is calmed in the midst thereof.
Spent this day also at Micajah Crew`'s, the after part in pretty close exercise.

"`Fifth month 1st.--Though feeling poor and weak,
I have ventured to pack up my clothes and feel willing to go on, if the way opens.
Lord, so order and direct my steppings along,
as that I may not linger through cowardice and fear.
You are all sufficient; I trust in you, O gracious Helper!
Unless your divine presence goes with me,
take me not hence--may I not be permitted to go into any further religious labour.
I opened the Bible, and cast my eye on the fifty-fourth Psalm, and read it to my comfort.

"`After breakfast set off, accompanied by Micajah Crew,
in order to go to our friend Robert Pleasants`'; had a sorrowful ride to Curies,
and continued to feel so after our arrival.
Spent the evening heavily,
although we met with a very kind reception from this dear aged friend.

"`2nd.--A morning of heavy conflict; went to Curies meeting,
where were only six white males, three females, and two black women: a time of exercise,
but was favoured to pour out my supplications among the few who met,
and in the end was a little comforted in an assured belief,
that Truth remains to be Truth,
although many of the descendants of those who were valiants for its promotion,
have forsaken it.
I prayed for them, and that the Lord would preserve us.
O for patience to hold out faithfully to the end of this journey,
and receive the sheaves of peace.

"`3rd.--I have spent this day in an exercised condition: who is so blind as your servant,
or so deaf as your messenger.
O! what a fearful thing it is to incur that reproof from the Lord; '`You have run,
and I have not sent you, therefore you shall not profit the people at all.`'
May I be kept subjectly given up to do his will; yes,
humbly and patiently to wait for the pointing of my heavenly Master`'s finger,
and that more stability and gravity may be the girdle of my loins.

"`4th.--A little opening presented in much weakness and fear to go towards Petersburg:
if your presence, O Lord, go not with me, take me not hence, is the language of my soul.
All I desire is clearness of sight, and let your will be done.
Set off and felt peaceful on the road; got there between two and three o`'clock,
and obtained a large room in a tavern for holding a meeting;
hearing that the court house was to be occupied by an Episcopalian.

"`5th.--What a poor servant, if worthy to take the name.
O for more purity of heart,
that so I may be indulged with greater clearness to see the Lord`'s will and do it.
It was discouraging to me when I heard of a meeting advertised
to be held in the new court house for the first time,
and that there was to be a Methodist meeting also, to begin at eleven o`'clock.
However, our friends took considerable pains to spread the notice of ours,
and it proved large, quiet and satisfactory;
much to the ease and relief of my exercised mind, although I was greatly spent after it.
In the afternoon we had a meeting with Friends
and such as made any pretensions to own us,
which was a comfortable time to me: after I had finished my testimony,
my spirit was poured out in humble supplication,
in which my own and my companion`'s family were brought into remembrance.
I was so spent with the labours of this day, that I could not sleep as usual,
but all was well, peace being the best portion;
for which I am thankful to the Father and Fountain of all our sure mercies.

"`6th.--After an opportunity with this family where we stayed, and some of the neighbours,
left Petersburg with sweet peace,
and rode home with our beloved friend and brother R. Pleasants.

"`8th.--Last night was one of mental conflict,
and such has been the state of my mind this day; however,
this evening I feel rather easier.
I have been delighted frequently, since we have been here, with the singing of birds,
particularly between daylight and sunrise.

"`9th.--To Curies meeting, which was silent and a deeply exercising,
tribulated time to me, as well as before as after the meeting was over.
O what a singular path I tread! yet let not one murmuring thought arise,
but wait in patience to see the end of every trying dispensation.
My body is weak and reduced by exercise of mind.
May I be favoured to hold on in the way that is cast up;
for all these sufferings are not on my own account,--there is a cause.
Zion lies waste, her walls are thrown down, and her gales are consumed as by fire,
her sons gone into grievous captivity, for which I mourn day by day.

"`12th.--Very poor indeed: rejoicing in hope, patient in tribulation,
continuing instant in prayer, was the advice of the apostle Paul,
and O that it may yet be, in measure, my experience; hope for a different dispensation,
O my soul.
Went to Curies meeting once more, where we found a larger gathering than on week-days,
but a cloudy, dark time: yet I ventured to relieve my very pained mind freely,
and afterwards felt easier, and spent the remainder of the day so.

"`15th.--Spent this day quietly at R. P.`'s, reading in Thomas Story`'s life;
opened on that passage where he speaks of the kind treatment
of John Bates of Skimino,--which brought to my remembrance the
comfortable feeling I was favoured with,
when at that meeting,
and which I had to mention to some of the descendants of this
worthy man when they gathered about me after meeting.
Some of the children of Benjamin Bates now living there, appeared hopeful;
they were pretty much reached and broken.
I copied it, in order to present it to some of them to peruse.

"`16th and 17th.--Attended the meeting of ministers and elders at White Oak Swamp,
and the quarterly meeting at Wainoak,--The 18th, to the meeting for Sufferings.

"`19th.--To a very large and mixed meeting, the house mostly filled up with women.
Joseph Cloud and J. Mendenhall, appeared in the forepart of the meeting;
but there was such a multitude out of doors, and many so uneasy and rude,
that it was a cause of grief.
My mind was exercised to leave my seat and go to one of the doors,
and endeavour to cast off my burden: my companion followed,
and I requested a few Friends to go out of doors and gather the people near the door,
and keep them quiet,--and it was indeed a laborious time to speak to such a crowd,
so as to be heard within and without the doors.
There are no people, whose states and conditions are so distressing and burdensome,
as those who have turned away in heart from the simplicity of Truth,
and become deistical and unbelieving.
O how my life has been oppressed with it this day, and often before in this land.

"`20th.--More people assembled this day than could get into the house,
and they appeared to be mostly such as were orderly;
and I hope a number of goodly seeking ones.
The two Hopewell Friends appeared in the early part of the meeting,
after which I had a pretty thorough opportunity, open and relieving to my spirit;
and indeed I felt like another man after it: the Lord be praised for his goodness.

"`21st.--An open satisfactory meeting today; things being well conducted,
and I feel peaceful and easy.

"`22nd.--To the meeting of ministers and elders at nine o`'clock, which was a comfortable,
instructive season.
At the eleventh hour the yearly meeting sat, to which came Joseph Cloud;
and after a time of silence,
he stood up and requested the partition might be opened for the women to hear;
and in a tender manner began with nearly these words:
'`You see my friends to what a state of bodily weakness I am reduced.
I have come this morning to express among you the great desire I feel,
that all present may be concerned to attend to their gifts;
for all our riches and the comforts of this life,
will do us but little good when brought to such a state as I am in.
I feel resigned and peaceful amongst you, and am glad I am here,`' etc.
After which I embraced the present season to relieve my mind towards the visited youth.

"`23rd.--To the adjournment at ten o`'clock, and meeting held until near six,
and got through the business, which was well conducted and to good satisfaction,
both in this sitting and others.
In the close thereof my mind was drawn forth in love again towards Friends,
and the youth in particular, and it appeared to be a solemn good parting;
numbers taking me very affectionately by the hand and parted in nearness.`"

[.offset]
In a letter written from Wainoak, dated fifth month 24th, 1793,
addressed to his beloved friend John Pemberton, he says:

[.embedded-content-document.letter]
--

The yearly meeting closed yesterday afternoon, and being now released from that service,
my mind is exercised with further openings of duty.
I have just been conferring with a number of my dear friends,
respecting another meeting at Richmond on first-day next,
and several are engaged to go and prepare the way.
I have often had thoughts of attending the quarterly meeting of Fairfax,
held a little more than two weeks from this time;
and when the prospect has been weightily before me,
I have thought it would contribute to the relief of my exercised mind,
to have it in my power to distribute some valuable small
tracts to some of the inhabitants in the Alleghany mountains,
in the way between Redstone and Fairfax.
I see the necessity to stir up Friends, when travelling backwards and forwards,
to leave such books at public houses and at other places on the way,
and have no doubt but some may be engaged in this good work,
who may attend the next quarterly meeting.
As there are a number of Friends of the yearly
meeting`'s committee likely to attend there,
if you could send by some of them I should be glad; but more so, my dear friend,
to see yourself thus employed in your usual enriching
and useful mode of disseminating useful knowledge.
I have had much satisfaction in spreading those sent to Charleston,
several of which I brought into Virginia and gave them
to goodly people where Friends mostly put up,
and they were cheerfully and kindly received by them.
One of Joseph Phipps`' books I sent to a young woman at Banister,
who has been instrumental to raise up the ruins in that place, by meeting for a season,
in the old forsaken meeting-house, by herself,
and by her exemplary conduct has drawn others to join her.
She has been with us at yearly meeting,
and I think bids fair to become a princess among the Lord`'s people.

I have had much peace and comfort in my labours in this yearly meeting, which has been,
I am informed, unusually large.
On first-day morning there appeared to be as many people out of doors,
as would have filled another house as large as the one we were in;
and poor and cast down as I often feel, I have occasion to acknowledge that the Lord,
my gracious helper, has not forsaken me in the most trying moments:
my desire is that I may fully and faithfully follow Him to the end of this journey;
and also if further dispensations should be permitted to exercise my faith and patience.

I do not know a more useful book of the size than Benjamin Holme`'s Serious Call,
and believe a couple of dozens might be profitably spread as I have mentioned before.
Perhaps some of the Friends will come in carriages,
as I fear it will be too late to send them by water to Alexandria.
I would have written sooner,
but my poverty and blindness is such that sometimes I
cannot get at things until the last pinch.

It seems to come before me just to say,
that Friends who have had occasion to go on business
into some of the towns where we have had meetings,
have told me that the people appear much satisfied with them;
which has been encouraging to me.
Truly it has been a trying dispensation for me, a poor weak one,
thus to go out from among Friends, but I cannot plead excuse in any way.
I am blessed with a solid, feeling elder for a companion, and my Lord and Master,
from season to season, lifts up my head out of a state of great weakness;
into which I see it is necessary for me first to be baptized:
may His holy name be reverenced and praised for the protection and help vouchsafed,
without which, I know I should faint and fall.

--

"`24th.--After engaging some Friends to be in Richmond early next morning,
to see about a meeting there on first-day, went to the widow Ladd`'s,
where I hope we had a seasonable opportunity: we returned back to J. Ladd`'s,
in company with Joseph Cloud, David Vestal, and a number of other Friends;
after which had the family together,
and the opportunity proved a solemn affecting season.
Dear Joseph is so weak that he has given out going to Richmond with us,
although his prospect on leaving home was to that place and other towns;--however,
he sat with us and was favoured to deliver an affecting testimony.

"`While I sat by him in silence, as well as at other seasons,
my mind was humbled in beholding his great weakness,
now so far from his dear wife and family,
and also in a sense of the Lord`'s goodness to me,
in affording so much bodily strength as to move along from place to place,
as Truth has opened the way.
On the close of his communication I ventured to kneel down and pray for him,
the family and Friends present, for myself and companion in labour;
and that the Lord my God might be pleased to continue the wife of my
bosom under his protection and favour--and to preserve us in patience,
if our faith and love are to be tried by a yet longer separation.
After this I had to labour with some of the children in particular,
encouraging those who are in the right way,
and cautioning and warning others of impending danger.
After which look a solemn farewell.

"`25th.--Rode to Richmond,
after a satisfactory opportunity with some Friends and the family.

"`26th.--Attended the meeting at Richmond, which was large, numbers being out of doors,
and much rudeness appeared in some.
It was upon the whole, a quiet meeting,
although there were some so hardy as to laugh in my face while I was speaking,
who met a suitable reproof before all, to their shame.
At the close I mentioned a prospect I had of a meeting with the black people,
at the same place, at five o`'clock in the afternoon,
and told them it was a delicate thing, but I stood open, if anyone had any objection,
and wished some of their sober masters to come and be with us.
We found afterwards that it was somewhat alarming, but no opposition appeared,
and we had a number of them together, with many whites also,
in which I had a quiet opportunity to relieve my mind.

"`27th.--Awoke early this morning,
under the weight of a prospect which had opened on my mind,
to see the little company of Friends here together, and such as go no other way.
I had made an attempt yesterday in the meeting at large, to address them,
but found it would not do;
so I now requested Samuel Parsons to collect them together by half-past nine o`'clock,
which he did, and we were favoured with a solid, instructive, and I hope,
baptising opportunity, at least to some.
James Mendenhall and his companion, Jonathan Wright, David Vestal,
Thomas Harris and wife staying,
we were about thirty in number at J. S. Pleasants`'. Josiah, S. Parsons and I,
went to bid the mayor, Robert Mitchell, farewell, who had been kind,
and attended both meetings; he appeared well pleased with that for the negroes,
though he said he was solicited by some of the inhabitants to put a stop to it;
and that he himself feared it would be of bad consequence,
but I believe none had any occasion to be uneasy:
the mayor confessed that the doctrine was suitable to them, and to the whites also.

"`O the wickedness and the abominations of this little city!
Is it any wonder at all, that I have gone through the sufferings which I have;
but thanks be given to Him who is ever worthy, on leaving the mayor,
and telling him how the mountebanks`' sign which hung out in the street,
and their other wicked doings, struck at my life, and leaving it with him,
I felt on walking away, relieved and peaceful.
Left the place between one and two o`'clock, and rode in company with several Friends,
pleasant and easy in mind.

"`30th.--To Genito meeting,
in which my mind was exercised on account of a visited seed hereaway,
and I was drawn forth in love to them: it appeared to be a watering season.

"`Sixth month 1st.--We had thought of going on to Southland to day, but I felt unwell,
and withal my mind was turned towards the first-day meeting here,
and we concluded to stay; and after breakfast I went to bed.
In and through all,
may I yet be favoured not to give way to the drawings of the affectionate part homeward,
but say with resignation of mind, '`Here am I Lord, you have hitherto been my support,
protection, and help, and can keep that which you have enabled me to commit to your care.

"`2nd.--Went to the meeting at Caroline, which was crowded,
and an open time,-- several expressed their gladness to see us again,
though very unexpected.

"`5th.--To Southland meeting, which was large.
I felt very poor and sat nearly or quite two hours in silence,
very different from the time we were here before.
The desire of the people seemed strong to hear words;
and although there was something arose to communicate,
it was to me a poor low time;--called afterwards to see a sick Friend,
and although I felt very poor here, yet on parting she said to me,
'`I love you and have been refreshed.`'`"

[.offset]
After an opportunity in a friendly man`'s family, with whom they put up for the night,
they pursued their journey and arrived at Mahlon Janney`'s at Hopewell.

"`7th.--Wait on your God, O my soul!
This place was the beginning corner for me this time twelve months ago,
when entrance into a large field of labour opened with clearness;
wait with humble submission to be rightly informed what you must do next.
It has been of late, a time of temptation and trial to me,
and I have had to feel what a wretched condition it is not to
experience the sweet presence of Jesus Christ our Lord.
But why should I complain?
Do not such dispensations prepare the soul for the
enjoyment of greater degrees of divine love and life?
O Lord, may what I have passed through, and what I may yet, in your sovereign will,
have to pass through, qualify me to live answerably to your goodness and truth,
if favoured to return to my house in peace; for you have been a God of truth to me,
your unworthy servant, in this journey.`"

[.offset]
In a letter written from Hopewell, Virginia, to his beloved friend John Pemberton,
he says:

[.embedded-content-document.letter]
--

I have remembered it was not far from this place, that you with other Friends,
were held in a state of banishment from all that was near and dear to you in this life,
and that the Lord`'s preserving hand supported you through and over all,
and restored you to your temporal comforts again.
Afterwards the Lord called for a free-will offering at your hand,
even to surrender them all again,
and become a sojourner for years in a strange and distant land;
and he has been with you in heights and in depths unto this day,
and has not forsaken you even in the most trying moments,
A sense of these things has caused my heart to rejoice on your account,
and also on my own, who am a poor pilgrim, and stranger in a strange land,
separated from wife and children, houses and lands, for the gospel`'s sake;
yet I am mercifully cared for by the Shepherd of Israel,
who puts his sheep forth and goes before them.
I have indeed great occasion thus to speak well of his excellent name,
for his goodness to me in this present proving journey.
Your kind attention and sympathy before I left home, as well as that of other Friends,
has been a strength to me.
Ah! what a poor, solitary, and I was going to say, benighted creature,
have I sometimes felt like,
before I have given up thus to leave all that is comfortable at home,
and run the Lord`'s errands; somewhat like a season of preparation,
wherein I could take but little delight in anything about me, or in myself.
But the Lord has made it up to me when I have cheerfully left all to follow him;
and my heart is tendered under a sense of his love while thus writing to you.
I believe I am afresh enabled to feel and sympathize with you,
with earnest desires that you may be favoured to live in a state of
dedication under all your provings for the gospel`'s sake;
most assuredly believing,
that a way will be made for you through the cloud and through the sea.
I have had near fellowship with you in your exercises when abroad on Truth`'s service,
when I have been with you,
and have looked upon it as an honour to take part with you as an elder brother.
I write with great freedom, for my heart is enlarged, and the love I feel is, I trust,
that which casts out all fear.

I know you have many discouragements in getting along, and think little of yourself;
and sometimes I have feared,
that the great discourager of the Lord`'s work would
willingly persuade you to think your gift little also,
less than many of your brethren.
Never did you do me more good as an instrument, than the day I left home;
and your extension of fatherly care to me at Shrewsbury
remains precious to me until this time,
and has been helpful to me in this journey.

Should this reach you in time, present my love to Mary Ridgway, Jane Watson,
Samuel Emlen, and Sarah Harrison;
+++[+++about to embark for England,]--may the Lord`'s
preserving hand be with them on the mighty ocean;
accompany the former to their outward habitations with sheaves of peace in their bosoms,
and with the latter as a pillar of fire and cloud through all their journey.

The harvest is indeed great, and the labourers few:
I think of my dear gifted brethren and sisters of Philadelphia,
with desires that more of them might give up to go abroad on the Lord`'s errands,
for we have received many favours, I mean the little company in that city;
and I believe more would be drawn abroad in Truth`'s service,
if the reasoner was shut out and barred against.
The Lord on high is mightier than the noise of many waters; yes,
mightier than the raging waves of the sea.

--

"`8th.--Attended the select meeting, and had a close searching testimony to deliver;
things appearing low.

"`9th.--Met with Hannah Cathrall, and companions Hannah Mitchell and Edward Garrigues,
who brought me letters from home.
In the evening we had a sitting with this family and a number of others.

"`10th.--In the forepart of the meeting today I was silent;
but in conducting the business I had my exercise respecting the low state of
things--the declension of the aged and the deviations of the youth.

"`11th.--We have the company of George Churchman and William Cole, of Deer Creek,
Maryland, and James Emlen of Middletown, Pennsylvania.
Met a committee of the quarterly meeting appointed yesterday,
to take into consideration the matter depending
between Hopewell and Crooked Run monthly meeting,
and the yearly meeting of Pennsylvania;
in which I trust I was favoured uprightly to discharge myself:
after the breaking up of the committee, I went into the youths`' meeting,
which was very large, a number being out of doors.
Ruth Kirk and Hannah Cathrall had testimonies to deliver, of an awakening tendency;
after which, although in the other two meetings I sat peacefully silent,
I felt my mind drawn forth in a close and searching testimony,
from the parable of the ten virgins.
I hope on the whole it was a profitable and instructive season, although things are low.
Went to M. Janney`'s and dined,
and about the middle of the afternoon believed
it right to make some preparations for going,
as my way opens with some degree of clearness now after this meeting,
to proceed homewards.
We sat down with a large company of young and old, who came in,
and I took my leave of them in a solid and baptising opportunity,
and concluded to stay until morning.

"`12th.--This morning before we set off, came W. H. and wife to take leave;
we sat down together with the family, Hannah Cathrall and her companion, etc.
I had to speak of the many favours we had received, and deliverances in this journey,
and that my dear Lord and master had set me at liberty to return home from this place.
I had also to mention and commemorate the deep wadings
I had to go through in this place many years ago,
before my mouth was opened in testimony, and now I could reverently acknowledge,
that the Lord was in this place, although I then knew it not, as now.
Both S. Janney and Hannah Cathrall bore testimony to
the goodness of the Lord--the first with a belief,
that sheaves of peace would be our portion on our return; and the latter in like manner,
but with the caution, to rejoice in the divine fear, etc.,
that we should yet have to taste of the wormwood and the gall.
It was a precious time, and we parted in near affection.
Stopped at Joseph Janney`'s and had a baptising time with some of the children.
Crossed the Potomac to a house where they kindly refreshed our bodies;
and in a religious opportunity afterwards,
I believe the Lord refreshed and encouraged their souls in the way of well doing.
It was a precious season, both to parents, grandmother and children,
and encouraging to me in a sense that I am in my place on the way home,
so we left them peaceful and easy.`"

[.offset]
After this he had no further religious labour, but returned directly home,
where he arrived on the 15th of the sixth month, 1793; in relation to which he says:

"`I met an open, loving reception from my dear help-mate in life, mother, children,
and the rest of my family, after an absence of thirteen months, minus five days;
for which, and all other blessings and favours received at the Lord`'s hand,
my mind is bowed in thankfulness to Him who is worthy of obedience, glory, and honour,
and praise; who puts his ministers forth, goes before them,
and at seasons seals life and peace to their souls.
And although I know it is my duty to sit down in
this low condition spoken of by our blessed Lord,
'`After you have done all that I command you, say we are unprofitable servants,
we have done no more than was our duty to do;`' nevertheless,
it is in my heart also to leave this record, that I have lacked nothing:
the Lord has brought me through all my exercises,
I trust measurably to the honour of his great and holy name,
although many and singular they have been, even unto the banks of deliverance and praise.
And O, that I may be favoured still to remain under his heavenly notice,
protection and care, through the further probation yet to be met with,
unto the end of my days, and be counted worthy in the solemn close of time here,
together with my bosom friend, dear aged mother and children,
to rest in the kingdom of righteousness and peace,
with the generations of those who have gone before and follow after.`"
