== Chapter VI.

"`15th, first-day.--Went to Grace-church street meeting, accompanied by George Dillwyn,
and was seated between him and dear Samuel Emlen--a sweet comfortable season,
although I had but little to communicate.
Samuel Emlen preached, mentioning the coming of Titus to Paul,
and how they were mutually comforted together.
In the afternoon went to Devonshire house meeting; silent on my part,
but a comfortable season to me--came home in the
evening accompanied by dear George Dillwyn,
and found various young people there, with whom we had a favoured opportunity;
dear George staid with me until bed time, and a pleasant evening it has been.

"`16th.--Towards evening, came Sarah Harrison, and her companion Sarah Birkbeck,
who staid and lodged.
They came upwards of twenty miles to see me, and it was truly a pleasant meeting.

"`22nd.--Joseph Smith took me to Tottenham meeting, which was silent.
In the afternoon attended the meeting held in the Clerkenwell school-house,
and had a comfortable time with the scholars.`"

After attending London and Middlesex quarterly meeting,
Ratcliff meeting and one with the scholars at Clerkenwell,
he makes the following memorandum:

"`29th.--Was at Grace-church street meeting, both in the morning and afternoon,
and laboured in testimony in both;
and at six o`'clock in the evening went to an appointed meeting for servants,
apprentices etc., which was held in the women`'s new house;
it was very large and ended solidly and well.

"`30th.--No way opens out of this city,
and great is the openness toward me amongst Friends;
may my soul be preserved in humility and fear.

"`Seventh month 1st.--Went to Horselydown meeting, and although we were few in number,
it proved a precious season,
where both dear Martha Routh and I were much enlarged in testimony,
and in the close my heart was drawn forth in prayer for myself,
and those other exercised servants,
who have been sent across the sea in the service of Truth.
O Lord, support and bear me up under all the dispensations which you,
in your unsearchable wisdom, may see fit to permit to be my lot;
and sweeten all the cups you are pleased to dispense to my dear wife--what can I do less,
my most merciful Lord and Master, than submissively say, your will be done.

"`2nd, fourth-day.--Had a restless night, and a weeping morning.
I dare not say, if you deal thus with me, slay me, I pray you;
but preserve me I pray you O Lord; for your will has proved my sanctification hitherto.
Went to Grace-church street meeting, and though not large, it was an open time,
wherein I had fervently to labour, and dear Samuel Emlen told me after it,
that one of the elders came to him with tears and mentioned,
that even the same words had been made use of by me as had frequently been by him:
and that it was marvellous.
After dinner, had a favoured opportunity in the family.
I went on board William Rotch`'s ship with Elizabeth Drinker, accompanied by William,
and Sarah Rudd and Rachel Smith.
Elizabeth Drinker expressed the satisfaction she felt on board,
and that it seemed like a pleasant home for those that were permitted to go;
but as regarded herself,
she did not know but that Trophimus must be yet left at Miletum sick;`'
alluding to Samuel Emlen`'s testimony at select meeting on second-day;
when he mentioned this passage in sympathy with her.

"`8th.--Went to the monthly meeting at Devonshire house, and during the part for worship,
I think we had a good time; I have not felt it more so, to myself,
since being in this city.

"`9th.--Attended Grace-church street monthly meeting,
and silently weighed a prospect which had rested on my mind,
to visit the families in this meeting; and at the close mentioned it, in much weakness,
before men and women separated.
It was united with, and a large committee appointed to make the necessary arrangements.

"`10th.--To the adjournment this afternoon,
where I mentioned Richard Chester as a companion in the work above alluded to,
with which the meeting united.

"`11th, sixth-day.--Dined at home,
(Joseph Smith`'s,) and had the company of Thomas Clarkson,
the great advocate for the liberty of the blacks.

"`12th, seventh-day.--Lord enable me to look with greater steadiness to you,
and to preserve the balance of my mind;
and O that I may seek counsel and strength from you,
so as to be rightly directed in this weighty work of going from house to house.
Unworthy as I am, I desire to prostrate myself before you,
and beseech you graciously to afford me the covering of your Spirit,
and a more even frame of mind.

"`19th, seventh-day.--A day of exercise;
no clear prospect opening to move in the family visit, and I am jealous of myself.
O for the water of purification, and that my soul may be abased,
and by abiding there find preservation!
Great is the subtlety of the enemy.

"`20th, first-day.--May I know a setting out anew this morning,
by the power of him who overturns, washes and makes up anew.
I am a poor creature, and I am glad to be made sensible of it.
Went to Devonshire house and sat silent;
dined with Martha Routh and company at Job Allen`'s; and when we sat down to eat,
it was a solemn time, in which my speech was directed to the parents,
their three sons present, and the maid.
In the afternoon went to Grace-church street meeting, which was dull in the fore part,
but after being favoured with a little strength to open a door,
Samuel Emlen had much to say to a number of strangers present,
and hope the meeting ended pretty well.

"`21st, second-day.--Breakfasted with Martha Routh, her husband, and several Friends,
at Simon Bayley`'s, and after a solid sitting, accompanied her on board the ship Barclay;
where I found dear John Wigham.^
footnote:[These two Friends were about embarking
on a religious visit to Friends in America.]
We had to part from them pretty soon, and the ship got under way.
After we landed, I stopped at the widow Smith`'s near the tower, with a number of Friends;
where we sat down together, and it proved a time of divine favour to be remembered.

"`22nd.--Breakfasted at Joseph Bevan`'s with Samuel Emlen;
and accompanied him to the water side, where I took leave of him in an affecting manner:
he was going, with a number of Friends, in a Gravesend boat,
to embark for America in the ship Barclay, After this, went with Elizabeth Minchell,
Sarah Rudd and Elizabeth Messer to Radcliff meeting, to the burial of Robert Forster.
It was a large mixed meeting, a number of poor inhabitants coming in;
and I was glad I was there.
On visiting William Rotch, the only passenger now left behind, and feeling his lonely,
tried situation,
I expressed a willingness to accompany him to the ship lying at Gravesend,
which he accepted.

"`23rd.--Set off in a post-chaise with William Rotch;
when we got to Gravesend found our friends on shore at a public house,
near the water`'s edge, all ready to put off, so we took boats and went on board;
staid about a quarter of an hour with them, and then took a solemn leave once more,
soon after which the ship got under way, with a fair wind,
and when we landed was nearly out of sight.
We sat down in the large room in the tavern,
and I hope we were favoured to send our wishes and prayers for
preservation after the little band on the water.
Returned with William Dillwyn, and as we rode along,
we saw a very great smoke arise toward London, which we found to be a fire.
It broke out in a boat builder`'s shop,
adjoining the East India Company`'s large warehouse and salt petre works;
which were soon on fire and burned violently.
It continued burning many hours,
and it was supposed that between four and five hundred houses were destroyed.
It came very nearly up to Ratcliff meeting house,
and extended over several acres of ground.

"`24th.--This was the day of Ratcliff monthly meeting, which I knew not,
but found my mind turned that way rather than to Westminster week-day meeting.
Joseph Smith went with me,
and when we got there we found the yard pretty much filled up with casks,
and no appearance of a meeting.
It being early we took a walk among the ruins and rubbish caused by the fire yesterday,
and in a little while returned, and found two Friends standing in the grave yard,
who hardly knew whether to go into the meetinghouse or not;
but I encouraged them to go in, so we went and sat down:
our meeting amounted to four members of the meeting on the men`'s side,
and two women and a child on the other,
with about as many from other meetings,--and a minute was made by a Friend,
adjourning the meeting for one week; the clerk we understand is burnt out.

"`25th.--Went to the meeting for the scholars at Clerkenwell school,
which was attended by only a few Friends, but hope it was to some profit.

"`26th.--A low time, in a sense of my weakness and unworthiness.
The prospect of a family visit is removed out of sight,
and it is proving to be here so long, just attending meetings as they come in course.
In conversation with my friend this morning, I find our feelings very much correspond.
This evening, on looking over the day, and also those days which I have spent in London,
what can I say or do more than the poor publican did?
We poor creatures can neither add to, nor take from the work,
O that neither carelessness, nor unwatchfulness, nor sloth may be laid '`to my charge,
I am jealous and afraid of myself.

"`31st, fifth-day,--To Ratcliff monthly meeting; which, although small,
I hope was an edifying time to some.
In the evening went to the Park meeting with Sarah Rudd,
which was the largest I have been at, and my mind was drawn forth toward the youth;
and yet, notwithstanding such seasons, what a poor stumbling creature I seem to be,
I laid down in pain and exercise, and had a tossing uneasy night.
I am a poor unworthy instrument,
if indeed I dare to number myself among the Lord`'s instruments.
I preach to others, and yet see my own shortness.
Lord, in your mercy, stretch forth your crook of love and tender compassion to me,
as you have done abundantly in time past.

"`Eighth month 3rd.--At Devonshire house meeting I was favoured with a sweet, calming,
refreshing time in silence.
E+++.+++ M. was there, and appeared after some time of silence,
and then I was favoured with an open time.
In the afternoon went to Grace-church street meeting, which was large,
and I hope profitable, my heart being enlarged and my mouth opened.
Returned home and sat a little while with dear Elizabeth Drinker, who seems to weaken,
but is in a precious child-like state of innocency.
This has been a comfortable encouraging day; may the Lord have the praise,
who can and does raise up as from the dust, and sets the poor soul at liberty.

"`4th.--My mind was thoughtfully exercised, before daylight this morning,
in regard to proceeding in the family visit,
laid before Grace-church street meeting a month ago this day.
A female companion has been waiting a month to join me,
and I have been shut up from going on, and this morning am still poor and blind.
O Lord my God, preserve me from joining in with anything which will mar your work!
I am poor and blind, you are riches, light and life: I prostrate myself before you.
I know not what step to take.
Lord, graciously condescend to the low estate of your servant,
and send forth your light and your truth, and let them guide my feet.

"`7th.--As I was going down from my chamber, I met Joseph Smith coming to inform me,
that they thought Elizabeth Drinker was departing.
I went into her room and found her almost gasping for breath,
but after a time she revived.

"`8th.--In my wakeful moments last night heard dear Elizabeth Drinker;
and sometimes she appeared, by the melody of her voice, to be singing.
I did not rise until late, soon after which, Dr. Fox came,
and I went into her room with him; and while we sat with her,
she appeared melodiously in supplication in broken sentences.

"`9th.--Dear Elizabeth appeared to me to be singing praises in the night,
and early this morning.
What a desirable state she is in!
O my poor soul, wait on your God for the discovery of his will and ability to do it.

"`Ten o`'clock.--I have just left Elizabeth Drinker.
On sitting down by her, I asked if I should remember her love to Friends,
as I was writing home; she answered, '`Yes,
give my love--I love them:`' and then turning from the subject, said distinctly,
'`O the pearl gates!`' After a few minutes I asked her if
she wished to send it to her dear husband and daughter,
she answered, '`O yes, let it go: with much affection and great earnestness.`'
This morning when I went first into her room, she said in a broken manner,
'`O my dear husband`'--and then spoke of the wall of the heavenly city,
the gates and the hewing and squaring of the materials;
which bespoke where her thoughts were placed.

"`10th, first-day.--Dear Elizabeth Drinker is very low;
a little before meeting time I went up with the doctor to see her,
and apprehending she would not suddenly depart,
I ventured to go to Grace-church street meeting, which was large,
and my heart was largely drawn forth.
The doctor returned with me--found our dear friend alive:
I went to the afternoon meeting and was again enlarged in testimony.
While John Townsend, Joseph Smith and I were sitting by dear Elizabeth Drinker,
she seemed in a great struggle with the phlegm, and looked around at us,
and moved her hand as though she wanted to say something.
Soon after this she was helped out of bed, and before she could be got back again,
she very quietly expired.
I have been for days past, in a state of much weakness.
I am thankful, however, this evening, not only to feel pretty comfortable in body,
but relieved from considerable pressure and conflict of mind.
'`When the dead are at rest, let their remembrance rest;
and be comforted for them when the spirit is departed from them.`'

"`12th, third-day.--Feel more comfortable and revived in bodily strength.
O what a path I tread,
and yet what cause of reverent thankfulness that I am counted worthy to
labour and suffer for the Lord`'s cause! if I dare use the expression.
Labour to hold fast, O my soul.
Went to Devonshire house weekday meeting which
was held for the first time in the new house,
(women`'s,) and a very comfortable time it was.
In the afternoon Mary Stanton came to see me;
a young woman who was at the Peel meeting in the afternoon of the
first-day that I left Grace-church street meeting to go there.
It was a laborious and a low time,
but towards the close my mind was enlarged to such as were seeking the way to Zion,
with their faces thitherward;
and this young woman informs me that her doubts were answered that evening,
with respect to the attendance of our meetings.

"`15th.--At ten o`'clock attended the remains of our dear deceased
friend Elizabeth Drinker to Grace-church street meeting-house,
where was a very large meeting: in the forepart, John Townsend appeared;
after which I had a pretty full opportunity.
We then accompanied the corpse to the grave yard, which was at a considerable distance.
There was a large collection of Friends and strangers at the grave,
and I had another opportunity amongst them.

"`17th, first-day.--Was at Tottenham meeting, which was pretty large,
and Thomas Shillitoe appeared in a very lively manner; protesting against the pride,
equipage and high things which so much prevail.
When he was done, my mind was exercised to stand up pretty much in the same line,
and I do not remember that closer doctrine has been delivered by me,
a poor unworthy instrument, at any meeting in this land.
The afternoon meeting was a time of binding up,
and my mind seemed enlarged towards the young people and little children.

"`23rd.--I hope my health and strength are recruiting:
O that devotedness of heart may be my happy experience.

"`29th.--Walked out this afternoon alone, bemoaning my present imprisoned condition,
and after I returned, withdrew into a room where my condition came more fully before me,
and in the thoughtful exercise, the state of the great city of London,
revived again and again; and on opening Cowper`'s poems this passage first struck my view;

[verse]
____
'`Cry aloud, thou that sittest in the dust,
Cry to the proud, the cruel and unjust;
Knock at the gales of nations--rouse their fears,
Say, wrath is coining, and the storm appears;
But raise the shrillest cry in British ears;
____

+++.+++..which seemed to correspond with the deep conflicts of my mind,
which has been ready of late to take up the prophet`'s language;
'`Who has believed our report?`'
what can such poor unworthy feeble instruments do to
put forward the work of the Lord in the earth?

"`31st, first-day.--To Tottenham meeting,
which was a time of enlargement and favour to me, and I hope profitable to others.

"`Ninth month 2nd,
third-day.--Spent some comfortable moments in William Dillwyn`'s office; being favoured,
I trust, with a ray of heavenly light.
Rode out about three or four miles before dinner and feel
better,--continue to take the doctor`'s prescription:
O that my heavenly Physician may condescend to heal me, and open my blind eyes.

"`5th, sixth-day.--To London and attended the meeting for Sufferings,
in which my mind was exercised to stir up Friends to zeal in
filling up their places in this important station;
and prepare for a day of suffering,
if it should be the great Master`'s will to suffer it to come.
Several other weighty subjects impressed my mind to mention, and it was a good time.
Returned home with my friends William and S. Dillwyn
after night--more watchfulness and prayer needful.

"`7th, first-day.--To Epping meeting, which was very small, but a memorable time to me;
my heart being engaged to come into a disposition to say, '`Not my will but yours, O Lord,
be done;`' who will do all things concerning us well.
I had some religious communication,
and also in the afternoon--the latter of an encouraging character.

"`8th.--Feel a renewal of strength both of body and mind this morning:
may praise and thanksgiving be rendered to the Preserver of men.

"`Went to Chelmsford and attended the quarterly select meeting,--where I was
seated between my much esteemed friends George Gibson and Elizabeth his wife,
(formerly when in our country,
Elizabeth Robinson,) and the consolation and comfort
that my soul witnessed in this opportunity,
I cannot set forth.
I had to look back to my first acquaintance with this mother in Israel,
who was a mother in the Truth to me, who now sat near me in the meeting, and after it,
owned me as a child.
Truly the Lord provides all necessary good things for his devoted people.
A few months after she had returned from her visit to our country,
her husband was removed by death;
but her loss seems abundantly made up by her present one, who is a prince in Israel.

"`9th, third-day.--To the quarterly meeting, and although a very rainy time,
it was large, and I was comforted in the company of so many valuable Friends,
and an open instructive time I think it proved.
Dined at Robert Greenwood`'s with a large number of Friends,
and had a solid religious opportunity, my friends George Gibson and wife being with us.
What a favour, I have thought, to be thus noticed and cared for,
by one whom the Lord made as a sharp threshing instrument to me, in my own land.
The works of the Lord are indeed wonderful,
and his doings among men are hidden from the wisdom of this world.
I am a poor creature, unworthy of the many favours I receive;
and were it not for his abundant mercy, I should be confounded and consumed.

"`12th, sixth-day.--To a meeting at Tottenham, appointed for a marriage.
It was very large, many of the people of the town being at it;
and I hope it was a profitable season.
I went home with Thomas Horne, and when we sat down to eat,
a number of Friends being at the table,
I hope it was a good time to all of us in humble prayer.
After tea we dropped again into silence,
when this passage of the prophet impressed my mind; '`It shall come to pass in that day,
that the ploughman I shall overtake the reaper,
and the treader of grapes him that sows seed; and the mountains shall drop sweet wine,
and all the hills shall melt:`' from which I had to
speak encouragingly to the dear children of the family,
as had been frequently the case before;
and near the close of the opportunity dear S. opened
her mouth in testimony to the goodness of the Lord,
It was a heart tendering time.

"`14th, first-day.--Went to Grace-church street meeting, which was pretty large,
and I was favoured with one more thorough open time, as also in the afternoon meeting.
Spent the evening with unusual sweetness of mind, and feel a renewal of bodily health,
even after such great exercise--what mercy.

"`17th.--Attended Grace-church street,
which was one of the most open meetings I have been at in that house.
The love of the gospel flowed freely towards the poor in spirit.

"`18th.--To the Park meeting appointed for a marriage.
E+++.+++ Bevington was there and favoured both in supplication and testimony;
and I hope it was to the profit of individuals present, as much tenderness appeared.

"`19th.--To the burial of Abraham Gray, at Winchmore hill.
This was a time of relief to me; wherein serious weighty truths were held forth.
Susanna Horne opened the service of this day to my comfort.
Jacob Bell and Sarah Rudd appeared in the grave yard,
and I had some further communication to make to the children of the deceased,
who were respectful and kind.`"

On the 19th of ninth month, 1794,
he was taken sick and confined to the house until the 28th. On the 26th he writes:
"`after dinner being alone, my heart was humbled into weeping.
O, the many trials there are to pass through, in order to refine us.
O Lord my God, you know all things, and know what is best for me:
not my will but yours be done.
Keep me in the work and service unto which you have called me, until you say it is enough.

"`27th.--Rather better in health--O for more living
substantial improvement in the things of the kingdom.

"`30th.--Went to quarterly meeting, which was comfortably conducted:
dined at Joseph Smith`'s with a number of Friends,
and think we were favoured both on sitting down to eat and after dinner,
with a singularly good time.
Let praise be given to the Lord most gracious.

"`Tenth month 1st.--At Grace-church street meeting; and although small,
it was a sweet season of the spreading of heavenly love.
In the evening went to the youths`' meeting, held in Devonshire house:
it was large and solid, and the labour fell on me, and I trust it was an edifying season.

"`5th, first-day.--Feel pretty comfortable this morning, both in body and mind;
a favour calling for continued thankfulness.
What fathers and mothers, brethren and sisters,
are raised up to be helps and comforts to me in this far distant land.
Attended morning meeting at Tottenham,
and the testimony of Truth was close and searching to the libertines,
as has frequently been the case.

"`9th, fifth-day.--To the monthly meeting at Tottenham, and in the gathering of it,
my mind was covered with sweetness,
which ripened into an exercise that I was not easy to keep to myself,
and trust it was through divine favour, a time of love to some of us.
After dinner at Thomas Horne`'s, where there were a number of Friends,
we had a solid and instructive religious time,
and in the evening we were again favoured with divine good.
William Forster, his two sons, sister Ann, and Sarah Fairbank came in,
with whom we had another opportunity,
in the close of which Susanna Horne appeared in prayer.
Great and marvellous are your works, O Lord.
Be pleased to strengthen your servant to preach your word with all boldness,
in the name of your holy child Jesus.
This has been a day of enlargement,
for which unmerited favour may my soul be prostrated before Him whose
power remains sufficient to open when all appears closed up.

"`10th, sixth-day.--Thoughtfully exercised this morning, what to move in next:
sometime after breakfast felt liberty to send for T. Philips--when
the lad got near their door he met his wife and daughter Ann,
coming over to see us,
and soon after came Thomas also and Hannah Kendall--with this little company,
this family and Mary Reynolds,
I had an open encouraging opportunity from these expressions;
'`many shall be purified and made white.`'
After it was over, dear Susanna expressed a desire to accompany me to a Friend`'s family,
who had a son drowned about twelve months ago, on a first-day afternoon.
The lad was at meeting when S. E. and Elizabeth Drinker both bore a remarkable testimony;
Elizabeth saying among other things, that there was a person in the meeting,
who would be so suddenly taken, as hardly to have time to say '`Lord have mercy on me.`'
Instead of going to meeting in the afternoon at his father`'s request,
the boy went to bathe in the river, and on the way one of his acquaintances said to him,
'`we had better go to meeting,`' but he refused and persisted in his design:
soon after getting into the water, he got out of his depth, and as he could not swim,
was suddenly drowned.
I went into this family quite a stranger, and soon after we sat down,
dear Susanna addressed the son and daughter present in an affectionate manner,
mentioning this awful circumstance;
also the trial of the family in parting with a beloved brother-in-law;
and hoped the dispensation might prove a blessing to both families.
Much brokenness of spirit appeared, and I hope it was a good time;
a door being opened by Susanna for me.
Returned back to Thomas Horne`'s, and soon after J. H. and C. B.,
who had passed the meeting yesterday, came and drank tea with us;
we soon as with one consent dropped into silence,
and I think it was a time that will be remembered by us all.
My path has been exercising in religious communication under this roof,
and the parents and children are made increasingly near to me.

"`12th, first-day.--One more favoured meeting at Tottenham,
wherein very close labour has been bestowed on the backsliders.

"`15th, fourth-day.--In a lonely walk this morning I felt some brokenness of spirit,
of which I was glad; the afternoon and evening were not so pleasant,
yet hope I have been measurably content;
but fear I do not experience that advancement and
firmness in the Christian life which is desirable.
My days are few and fleeting--O for greater religious improvement,
and more wisdom and stability.

"`16th.--Attended Tottenham meeting, where the corps of H. C. was brought,
on the way to the burial ground, at Winchmore hill, I had very close work, after which,
went home with Thomas Horne.

"`19th, first-day.--To Grace-church street meeting, which was large;
and a laborious time to me, in pleading with the high and unconcerned ones,
who will not come forward and join in the work of Truth.
In the afternoon meeting, my mind was drawn forth to a seeking state, and felt much spent.

"`20th, second-day.--Attended the morning meeting,
which was a time of sweetness and enlargement.

"`22nd.--To the burial of Rebecca, widow of Abraham Gray, at Winchmore hill,
which proved a solid time, and hope the meeting was held to profit.
After dinner my mind became exercised to labour with the company present,
to embrace the Divine call, and enter into the vineyard and work.
In the evening, had another religious opportunity with some Friends who came in,
which was an open encouraging time.
Truly I may acknowledge I am favoured, far beyond my deserts,
who am indeed a poor creature.

"`23rd.--To Tottenham week-day meeting, which was unusually small,
but solid and comfortable.

"`25th.--Set off in a post chaise for Hitchen, and arrived there a little before night.
I felt poor and stripped, much like a stranger and pilgrim on earth.

"`26th, first-day.--Went to the meeting, where I found a little company of Friends,
who were soon made near to me; my spirit was united with those, in every age,
who had no certain dwelling place,
and I was brought into near sympathy with the labourers and travellers in this day;
and after a time stood up with the subject before me,
and was favoured with an open encouraging time.
The afternoon meeting was to me a silent contemplative time,
wherein the book of prophecy was measurably opened to read in.
After meeting went to see that dear aged servant of the Lord, Samuel Spavold,
and it was precious to me to be favoured to sit by and converse with him,
and to receive his blessing.
He told me the Lord was with me, and that he hoped I would be preserved to the end.
'`I longed to see you,`' said he, '`after I heard you had come.
You sees I am a poor old man; I can`'t see you,
though I sometimes say see,--but I am glad to hear you.
The Lord has been wonderfully good to me, and I love him;
but sometimes I tear I cannot love him enough.`'
On mentioning the trials and temptations to be met with, he said,
'`don`'t fear the adversary, for perfect love casts out fear:
my divine Master has been wonderfully kind to me, and given me victory over him;
I don`'t fear him; and he has enabled me to say to him in time past, Devil do your worst,
I fear you not.`'
After a little pause he said, '`for whose sake I know not,
but these expressions have impressed my mind, '`there is that which scatters,
and yet increases; and there is that withholds more than is fitting,
and it tends to poverty;`' be faithful, and so farewell.`'
Sometime after when we again entered into conversation, he said to me,
'`don`'t take any burden away with you.`'
After a little time he continued, '`the Lord, my Master, has been very kind,
and has given me enough to live comfortably upon--I have a dear
Master,`' I told him that I had heard so in my own country,
and it was encouraging to me to hope and trust also, and endeavour to serve him.
He replied, '`yes, he will be with you; you are a favoured servant.`'
This was after an opportunity with a room full of Friends, most of them young,
to whom I had something encouraging to communicate.
'`I am going home,`' said he, '`and I am glad of it.`'
On my saying, heaven would be a happy place, free from all labour and toil, he said;
'`with the church of the first born--the general assembly; I long to be with them.`'

"`27th.--Went to the monthly meeting, and it was an open good time:
supped at John Ransom`'s with a considerable number of Friends; we dropped into silence,
and had, I hope, a solid meeting.

"`28th.--To Isaac Sharpless`' to breakfast, and after it was over,
I trust the bread of life was broken amongst us; then to J. W.`'s,
where we were favoured with a good opportunity, Mary Stacey being my fellow helper;
from there to Samuel Spavold`'s. O the sweetness that accompanied my mind while with him;
and after a season of silence, I kneeled down in supplication,
and my soul wrestled with the Lord our God for a blessing,
both to be continued to his worthy aged servant,
and for the continuation of it to me in this land, and that if I should in time to come,
be excused from labours and travels abroad, my soul might rest as his does;
and that the Lord would favour his heritage, and raise up labourers and send them forth.
The dear old man expressed his satisfaction, and told me,
he could not fully express the love he felt for me,
and for the labourers the Lord is sending forth; '`For,`' continued he,
'`His work will be carried on.
The Lord will favour and bless you.
Master will prevail--his work will go forward.`'
We parted with much affection.`"

After visiting a few families, he took postchaise and rode to Hartford,
where he attended their week-day meeting,
and visited a number of families and some aged individuals,
and arrived in London on the evening of the 30th;
the next day attended the scholars`' meeting, at Clerkenwell.

"`Eleventh month 2nd, first-day.--To Grace-church street meeting,
and had a laborious time in caution and warning to Friends,
to endeavour to stand armed against the evil and trying day.
In the afternoon silent.

"`5th, fourth-day.--To Grace-church street meeting; a laborious, trying season,
both in the first and second meeting, but not altogether without some comfort.`"

[.offset]
Extract of a letter, written by him, dated Stoke Newington, near London,
eleventh month 6th, 1794.

[.embedded-content-document.letter]
--

I am now at the house of my friend Richard Chester;
an elder whom I chose to accompany me, when way might open,
to conduct me into the families of Friends
belonging to Grace-church street monthly meeting,
and who has been waiting for that purpose.
You wilt find by my letters, that I have had rather a singular path to step in,
having been landed several months, and no settled fixed line of service has opened.
Within a few days, some little opening has presented,
and we have been into some families; and although in much weakness and fear,
and not without some trembling at the prospect; yet so far, it has produced peace,
and a willingness is wrought in my mind to proceed, as Truth may open the way,
and I think it not unlikely that I may winter in and near this great city.
It is a place my mind was peculiarly drawn to, when at home,
and also the latter part of the time I was at sea;
a place in which peculiar exercise has been my lot, both in meetings and out of them.
O that I may be favoured to dwell so low and deep,
as to be enabled to leave it with that peace, of which my soul is in pursuit.
I have thought of late of my tour to the south,
and remember how the remote part of Georgia lay most on me,
and the covenant I entered into, at the time when you were my careful nurse,
that if the Lord would but raise me up, and give me to experience the sense of his love,
and go with me, I would follow him to the end of the land.
I magnify that divine hand and arm that went with and supported me all along,
and through peculiar exercises in that remote spot.
How the scene is changed; they were poor,
and I was brought nearly to sympathize and feel with men of low estate,
in their little cottages.
Now there is an abounding;--O the perfection, there is here,
as to outward beauty and comeliness!
Herein are trials that are fresh and new,--and I
think of dear Rebecca Jones`' bemoaning language;
'`I am by far a poorer creature than you have any idea of;
and doubt my getting through to the honour of the great Master.`'
You may tell her, that I have occasion frequently to remember her advice:
'`Be not afraid of the rich and great,`' etc.
I may also say that I have been favoured at seasons to
penetrate through the shell or covering,
and find precious ones here and there;
and with such I have been permitted to drink of the brook by the way,
greatly to our refreshment.

--

[.offset]
In a letter to S. H., written about this time, he says:

[.embedded-content-document.letter]
--

I have frequently thought of putting my pen to paper,
and telling you a part of my trials, but could not until this morning.
O that the Shepherd of Israel may be your leader, enlarge your gift,
and make you a blessing to many.
Wait then, my friend, patiently wait under all your trials,
for the live coal from off the holy altar, to warm your heart and touch your lips.
This is what will make our words drop as oil,
to the strengthening of the true mourners and upright burden bearers.
Without a doubt you are called, and as you keep in lowliness and humility,
you wilt come yet more and more into the state of the chosen of the Lord:
'`You have not chosen me, but I have chosen you, that you might go and bring forth fruit,
and that your fruit might remain.`'
O that like Moses,
you may be favoured to throw all glittering preferments behind your back,
and learn more and more what a Christian`'s life is, meditating in the law of life;
and then no matter what your conflicts and inward exercises may be,
life will spring up in the Lord`'s own time, and a testimony to his goodness,
mercy and power will be put into your mouth.
As poor as I have been, and indeed was on sitting down to write this letter,
faith has arisen with respect to you,
and the desire to hold forth the language of encouragement.
I might go on and fill my paper, but perhaps I have said enough,
especially when we look back and remember those precious
seasons of heavenly regard we have been favoured with,
when the canopy of divine love has been so remarkably spread over us;
which are frequently revived in my mind, and the language has arisen,
I trust in sincerity, O Lord, preserve the parents unto your everlasting kingdom,
and favour the children.

--

"`8th.--Richard Chester went to town this morning,
in order to pave the way for entering more fully
into the family visit in the city next week:
spent the morning mostly in reading the New Testament.

"`9th, first-day.--To Grace-church street meeting, which was large,
and a relieving time to me from these words, that rested on my mind to begin with:
'`O that there was in them a heart to fear me, and to keep my commandments always;
that it might be well with them, and their children after them.`'
Went to afternoon meeting, which was thought to be one of the largest almost ever known,
without notice being given.
My mind was sweetened with a sense of divine love,
and under this I had encouragingly to labour for the help of others;
a seeking seed being present.
After the meeting visited several families, and this evening I feel peaceful and easy,
and it is in my heart to return the tribute of praise to the Lord my helper.`"

From the 10th to the 16th he was closely engaged in visiting
families belonging to Grace-church street meeting;
but from this time to the 30th, the way being closed for further labour,
he remained in the city and its neighbourhood,
taking the meetings as they came in course.

"`30th, first-day.--To Grace-church street meeting morning and afternoon:
in the morning a laborious close time,
yet was favoured with a good degree of sweetness and ease, and felt comfortable after it.
At the breaking up a young man came and spoke to me, and acknowledged in a tender manner,
that his condition had been spoken to.
The afternoon meeting was large, and an open time with the poor of the flock.
Several Friends spent the evening with us, and I was favoured with a good time in prayer;
my burden is lightened; for this favour may thanks be given to Him who is ever worthy.
O it is good to be thankful in all states and conditions, even the most proving.

"`Twelfth month 1st.--This day begins another month,
and I feel like making a new beginning.
The old exercise seems passed away,
and I do not find condemnation for travelling so
far in this concern in the manner I have,
and so feel willing to resign up all.
O that the all-sufficient power of Him who makes all things new,
may be near to help me in future labours, travels and exercises.

Attended the select meeting, in which Sarah Fairbank appeared in supplication;
and when she arose, I believed it right for me to continue the same;
and my mind felt comfortable and easy after meeting.
I feel resigned to whatever my Lord and Master
may be pleased in wisdom to inscribe upon me,
and to perform what further labour may be right; either to pursue the family visit,
or other work in a different line.
Good is the Lord and worthy to be waited upon.

"`7th, first-day.--Attended Grace-church street meeting, which was large, open, I trust,
and favoured; as was also the afternoon meeting.
Had a good time with the family in the evening, and laid down fatigued,
but preciously peaceful and easy in mind.

"`10th.--Attended the monthly meeting of Grace-church street;
and it proved a blessed opportunity, and hope it was profitable to individuals.`"
In the evening he was taken sick, and remained so for several days;
and in a letter dated 15th of this month, after speaking of his indisposition,
he remarks,
"`You will find that I am frequently thrown back by indisposition and other ways;
but do not be discouraged,--I am helped along;
and though my detention has been singular in this part of the city,
I dare not doubt it has been in the ordering of divine wisdom:
and the sweetness of that soul-enriching peace, which is my portion,
(in humility be it spoken,) is more than an adequate
reward for all that I have had to pass through,
in order to prepare for the work.

16th.--Opens again the family visit.--"`Sat with Joseph
Gurney Bevan at eleven--an open encouraging time;
after which I had a remarkable opportunity with a woman Friend and her daughter,
from these words: '`The Lord is my judge,`' etc,;
the daughter was affected so that tears rolled down her cheeks,
and the mother was also tendered.`"

From the 16th of this month, to the 6th of the first month, 1795,
he was daily engaged in visiting families;
in which he was favoured to administer to the spiritual states of individuals,
in many cases in a remarkable manner.

Having for some time believed it would be required of him to
offer himself to Devonshire house monthly meeting,
to go from family to family,
he attended that meeting on the 6th of the first month for that purpose,
which he thus describes;--"`A low time in the first meeting;
but I could not forbear to mention my prospect of a family visit,
with which Friends united, and appointed a committee to assist me in the work:
soon after which I went and sat a little time in the
women`'s meeting,--and mentioning what I had done,
several expressed their satisfaction and unity with the proposal;
which was encouraging to my tried mind.

"`7th.--This has been a day of sorrow and exercise,
having undertaken more work in this great city;
and it feels discouraging that so little fruit appears after
the arduous labour bestowed in this +++[+++Grace-church street]
meeting; yet I hope it will not be altogether fruitless.
O my weakness and poverty!
Who is sufficient for these things?

"`8th.--A comfortable night`'s rest, and feel rather more courage this morning.
O Lord, my helper, enlighten the eye of your servant, for in vain is the help of man!
Be pleased to favour me with ability to see and to do your blessed will.`"

From the 8th to the 13th, he continued engaged in visiting families;
and having received information of the death of Samuel Spavold, he went to Hitchin,
the place of his abode, to attend the burial.

"`15th.--To meeting at eleven o`'clock, where the body of our deceased friend was brought.
It was a large, mixed meeting, and I thought a low time.
O for preservation on such occasions, when there is so much looking to instruments!
I followed the corps to the ground, where I could not forbear uttering these expressions,
with some little addition; '`My father, my father, the chariots of Israel,
and the horsemen thereof;`' with a desire,
that the youth of that neighbourhood might be favoured to take
up the mantle of this faithful servant of the Lord.
Dined with the widow, children, and grand children, etc.,
and was engaged in prayer at the table.
After dinner, came in Mary Pryor and Sarah Rudd, who had some lively communication,
which opened a further door for me fully to relieve my mind.`"

On the 16th he returned to London, and spent next day mostly at home.
"`On the 18th attended Barking meeting,
where the body of John Harvey was brought,--the house
could not contain the people so as to get seats;
it was a pretty open time, and after it I had a good opportunity with the widow,
children and other relatives.

"`19th.--Went to London and attended the select meeting;
and on the 20th went to Horsleydown meeting, where I was silently shut up.

"`23rd.--After an open time of encouragement with a
number of females at the meeting-house chamber,
I sat with several clerks, etc., at the same place;
being the last opportunity laid out by the committee within this meeting,
(Grace-church street.) My weakness was great, but strength arose,
and I was favoured to relieve my mind; and after they were gone I sat down,
and in weakness and humility, looked over my arduous labour within this meeting;
and though sensible I am a poor unprofitable servant,
yet felt thankful in that enriching peace was my portion.

"`25th, first-day.--Attended Devonshire house meeting, both morning and afternoon,
and was silently shut up; it has been an exercising day to me.

"`26th.--Went to the morning meeting, where an exhortation to servants,
written by Job Thomas of Wales, was read, and a committee appointed to correct it.
In the evening I met them at John Elliot`'s, and it proved a time to be remembered.

"`27th.--To Devonshire house meeting, and was again silently shut up under exercise.

"`28th.--Attended Grace-church street meeting, and through divine favour,
my mind was supported, and I hope enabled to worship in humble silent prostration,
and was favoured with some precious openings.
O for more religious weight and depth! that so the divine blessing
may rest upon me through the future labours in this great city.
I have need to be baptized again and again for so great a work.

"`30th.--Went with Joseph Smith to the monthly children`'s meeting at Clerkenwell,
and was favoured with a pretty open time.
Meeting with my friends Thomas Horne and daughters,
I concluded to go home with them to Tottenham, where I met, as usual, much openness,
and we had a comfortable sitting with the family and several Friends.

"`31st.--Spent this morning in reading;
hoping that before long my divine Master will appear,
and set me to work again in his harvest field.`"

[.offset]
About this time he received a letter from his friend J. W., dated twelfth month 11th,
1794, from which the following is taken:

[.embedded-content-document.letter]
--

We often think of you, and sometimes talk about you,
since you have left your native land, your endeared wife and children,
and also your beloved friends; in many of whose hearts,
I believe you have obtained a large place.
I may acknowledge that it is cause of thankfulness to the Father of mercies,
that ever I saw your face and heard your voice, being as a tender nursing father to me,
even before you knew me outwardly,
but were made sensible of my inward state and condition,
and in the precious light of Truth, did seal instruction on my heart,
and afford abundant encouragement to me, to press forward in that high and holy way,
which, through divine kindness, and the teachings of the Holy Spirit,
has been cast up and made plain to my understanding.
Your testimony also greatly tended to confirm me in the
prospect which had been spread before the view of my mind,
in a very remarkable manner; that some day or other, the Lord had a service for me to do;
namely, to publish his gospel message to the people.
This was at a time when I had read very little in Friends`' books,
was not joined with them in their holy profession, and knew but little about them:
and the first time you saw me and took notice of me, it afforded me much encouragement,
at a time when often under doubts and discouragements.

May I treasure in faithful remembrance the
several eminently favoured opportunities I have,
since that day, had in your company, and in hearing your testimonies,
which have been as marrow to my bones, or as cold water to a thirsty man.

--

"`Second month 2nd.--Went to select meeting in London, which was a memorable time,
though exercising to me.
The Address by Job Thomas being again read, it was concluded to send it to him to publish.

"`3rd.--To Devonshire house monthly meeting; and although low in the fore part,
it was a day of some comfort to me;
Friends conducting their business in much brotherly love.

"`4th.--Attended Grace-church street monthly meeting;
and in the fore part had a relieving time, though it was low water in the beginning.
The testimony of Truth was very close to such as had
neglected the visitations of their youthful days.
A memorial concerning our beloved friend Elizabeth Drinker was brought forward.
On the whole I seem somewhat relieved;
but it is remarkable how one thing after another detains me in London.
I love its inhabitants and travail in spirit for the welfare of all ranks and classes.

"`5th.--Set off this morning, accompanied by George Stacey and Rachel Smith,
to the burial of the wife of Simeon Hagan, at Staines,
and the corpse was taken into the meeting, in which I was shut up in silence.
Ann Crowley, a young woman, sat near me, and appeared under exercise,
but did not give up to speak;
and at the grave I thought she again appeared under a
concern to express something to the people;
so I took her by the arm and put her before me, and soon after she spoke,
and thus opened a door for me to labour.

"`8th.--To High Wycombe meeting, and was shut up in silence.
My strippings and provings of late have increased,
and I feel very little strength to minister to others,
the cause of which my soul is anxious to know.
The Lord can turn a barren wilderness into a fruitful field;
but I sometimes fear that I am in the circumstance that Moses was,
when the Lord met him by the way going towards the land of Egypt with the Lord`'s message:
it seems he had forgotten or neglected doing his duty.
My past condition sometimes comes up, and the prayer of my heart is,
that my divine Master may cause his light more and more to arise and shine in me,
that nothing, which is wrong may lay hid;
for I see heaven is a clean and pure habitation.
And now, O Lord my God,
graciously condescend to the low estate of your servant--open
the way and go before me in this land;
and if you do not go with me, take me not up from here!
O guide my heart and my tongue, that I may not speak a false vision in this land.

"`11th, fourth-day.--To Grace-church street meeting, poor and stripped.
The body of Frances, wife of Joel Cadbury, was brought there,
and the meeting was pretty large.
John Townsend opened the service, and it was once more a time of enlargement with me,
and I hope measurably, a tendering season.

"`15th, first-day.--The meeting at Devonshire house was pretty large,
and I laboured among them in much bodily weakness.
Saw a little light on the family visit.

"`16th.--This afternoon opens the family visit in Devonshire house monthly meeting,
accompanied by Simon Bayley.`"

[.offset]
The following letter, dated London, third month 1st,
addressed to his friend Sarah Harrison, at that time on a religious visit in England,
gives an account of his labours about this time,
and will serve to show the close fellowship which
subsisted between these two devoted servants,
while engaged in similar labours, to promote the cause of Truth and righteousness.
After acknowledging her acceptable letter, which came to hand a few days previous,
he says:

[.embedded-content-document.letter]
--

You have been favoured to hit the nail on its head in nearly every stroke.
What a blessing,
that one fellow servant should be so dipped into
feeling and sympathy with another at a distance,
and without knowing or hearing by outward information, as you say was your case.
My exercises, both in meetings and families, some of them at least,
I think have been singular.
I was favoured to get through Grace-church
street meeting much to the peace of my own mind;
having a kind, attentive yokefellow, and who continues to be my near friend.
In the opening and liberty I feel while writing to a dear sister,
I will give you a little sketch of my winding up in that business.

The last opportunity was with a little company of female servants,
who could not be seen in the families where they lived, held in the meeting chamber.
Felt poor, as if it was indeed the last running of the little oil; however, we were,
I hope, somewhat tendered together; after which, being left alone,
I sat down under reflections that one more arduous undertaking was got through;
and although I had to acknowledge in secret to the goodness,
mercy and power of the good Shepherd, in putting forth and condescending to go before,
yet I remembered also, what He told his beloved disciples on a like occasion;
After you have done all that I have commanded you, say we are unprofitable servants;
we have done no more than was our duty,`' etc., and so wound up quiet, calm and easy.

After this I had a humbling dispensation to go through,
having some time before the finishing of this visit,
laid a similar prospect before Devonshire house monthly meeting, in much weakness,
and now had to look towards the accomplishing of that.
But, O the strippedness I was brought into; and the concern was so much removed,
that I could see no time to make a beginning.
While I was in this state,
+++_______+++ came to London with some prospect of joining me in the service of Truth;
but his coming did not relieve me,
nor open my way,--his mind having been turned towards Westminster meeting,
and he had let in thoughts, that mine would be so likewise.
I could neither see him to be the right companion for me in the work in Devonshire house,
nor a beginning corner for myself, and he was made sensible of it.
After he commenced his visit, my way opened, and accompanied by Simon Bayley,
an acceptable companion, I have visited sixty-nine families in the last two weeks.
And truly, I find, beloved friend,
that it is good to be plunged down into Jordan`'s bottom,
or deeply baptized into weakness, nothingness and poverty, previous to such engagements;
for way has since been made for me in a marvellous manner,
and ability given to relieve my exercised mind.
What a mystery is this!
Is it not a miracle,
like the running of the oil into the empty vessels borrowed by the poor woman formerly,
whereby she was enabled to pay her creditors.
I have felt more cheerful and easy since a way and means have opened to pay this debt;
but we know all the honour is to be rendered to
the everlasting Prophet and Bishop of souls,
who indeed is, and will be,
a very present help in the needful time to all that wait on him.
So dear sister, as you have been so favoured to encourage me, allow me to say to you,
and not without feeling,--Lift up your head in hope,
for surely the same good hand which has hitherto been near,
and enabled you to set up your Ebenezer, will not fail,
even though more such singularly exercising meetings may turn up, as you describe.
'`Be careful for nothing, but in every thing by prayer and supplication,
with thanksgiving,
let your request be made known unto God:`' this
encouraging language occurs to offer for your help,
and I trust, for my own also, being often sensible of poverty.

I hope I shall not say too much; but truly, when I think of our situation,
as the only two messengers now on this island from America,
separated from all our near and dear connections,
we may give way a little to those sympathetic feelings we are favoured with.
Approve yourself, therefore, and that with a willing mind,
a labourer that need not be ashamed--rightly dividing the word.
You know the fat and full must be fed with different food from the panting,
bleating sheep.
Alas! alas! how many there are of the first description, not only under our name,
but amongst the people at large, although the judge appears to be so near the door.
Well, dear friend, amid all which we may have to wade through for the Lord`'s sake,
I think I see, and hope I am not deceived,
that the strength of Israel is yet with his people,
and that the declaration of the prophet will be more fully brought to pass;
'`The Lord will comfort Zion: he will comfort all her waste places;
he will make her wilderness like Eden, and her desert as the garden of the Lord:
joy and gladness shall be found therein, thanksgiving and the voice of melody.`'
There are precious plants, even little children, in this city, who,
by keeping faithful to the Lord, will in due time have this song, or one similar to it,
to sing.
The Lord is blessing Zion; but O how poor and desolate she sits in this great city:
are not her sons found slain at the head of every street?
And for this I have mourned.
I might enlarge, but this is enough, perhaps,
to show you where my dwelling place has often been for months past.

--

He continued engaged in visiting the families of Devonshire
monthly meeting until the 17th. In this visit he had often to
commemorate the goodness of his divine Master,
for furnishing him with ability to speak to the conditions of those he visited;
as well as for the enriching reward of peace,
graciously vouchsafed in fulfilling the duty.

"`Third month 18th.--To Peel monthly meeting, and was silent in the fore part.
Ann Christy opened her concern to visit families,
and I waited to know my divine Master`'s will concerning me, but was quite shut up,
although I attended with some little prospect of moving in a like concern.

"`19th.--This morning I took coach and went to Ratcliff monthly meeting,
in the fore part of which I sat in a state of poverty;
but before the meeting ended felt an opening to speak to an exercised state present.
Went home with Joseph Smith; all my prospects seem gone again.
Am I not indeed an unprofitable servant?
It is well if I can say I have done all, and as it should be done.
I am a poor creature, yet am favoured to feel pretty quiet and resigned.
I desire to be a devoted servant.

"`22nd.--To Tottenham meeting,
and although I thought but little more of this turn into the
country than that it was pleasant to accompany an elder sister,
and get a little country air;
yet on the road my mind was impressed with a sense of the uncertainty of time,
and the dreadfulness of being taken in the midst of worldly joys and lusts;
and early in the meeting I stood up with this concern, and delivered it in few words;
after which several Friends appeared,
and mostly to the same import--and it was a memorable meeting; but my mind was sorrowful,
in a sense that there was a disposition to put it off.

"`23rd.--The select quarterly meeting was a very trying time;
I expressed some close things,
under a sense of a forward spirit prevailing too much in some.

"`24th.--To quarterly meeting, which was so large that the people could not all sit down.
There were a number of appearances, and I thought I could have sat in a low place,
with my mind and mouth in the dust,
for the sake of the little ones being brought forward;
but felt a short testimony of encouragement arise to this class,
and to those struggling under difficulties, etc.;
and again at the close expressed a desire,
that friends might be preserved under the weight and sense of Truth,
and be careful how and what they spoke.
At five o`'clock attended the adjournment, which held until near nine o`'clock,
and I had some very close things to say,
being sorry to behold an active busy spirit at work.
I am jealous and fearful of my own standing:--the Lord knows my state;
and O that I may be rinsed and washed from every stain, and preserved unto the end.

"`25th.--To another adjournment at the tenth hour, which held until near three o`'clock;
passed through it without much to say,
in silent suffering on account of a forward spirit.
Went in to the women`'s meeting with my friend Richard Chester,
when he took in the Memorials concerning Elizabeth Drinker and Deborah Townsend;
and after they were read, I had a comfortable opportunity.`"

[.offset]
While in London he received the following letter from Ann Crowley,
an account of whom is contained in the seventh volume of the [.book-title]#Friends Library#:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Shillingford, Third month 24th, 1795.

It is not without a degree of diffidence that I
take up my pen to address a father in Israel;
but as my mind has at seasons been favoured with a glimmering hope,
through the many clouds of discouragements, that although many are my failings,
yet I do feel true desires to be enabled to tread in
the footsteps of the flock of Christ`'s companions;
I am encouraged to believe, that my beloved friend will receive a few lines,
although it come from a babe in the knowledge of the mysteries of the kingdom,
in that love which nearly unites the children of one Father,
whether aged or young in years.
It is not from an apprehension of having much to communicate,
nor from a desire to draw unprofitable consolation from my dear friend,
that I am induced to address him at this time; but as I have, I trust,
in the liberty which Truth gave,
a little unfolded to him the exercise of my often discouraged mind,
I did believe it would not be altogether unacceptable,
to hear a little how it fares with his poor friend; who,
though often tempted to believe that she haS not yet known her
spiritual eye to be anointed with the true eye-salve,
nor her spiritual ear to be enough unstopped,
to distinguish the voice of the true Shepherd from that of the stranger;
yet can say she feels no greater desire,
than that she may be favoured clearly to behold the pointings of the divine finger;
and when seen, be enabled, by the assistance of the Lord`'s mighty power,
to be obedient thereunto;
that so she may indeed become a humble follower of a crucified Saviour,
although it may cost her the parting with a right eye, or a right arm.

After I parted with you in London, I went to Staines,
where I spent near a week with my relations,
though my mind was so oppressed with the weight of the prospect before me,
that I had but little satisfaction in the company of any,
even of my nearest and dearest friends.
I thought solitary places, where I could pour out my petitions to the Searcher of hearts,
and supplicate for the continuation of his merciful regard, aid and direction,
were safest for me;
well knowing that of myself I could do nothing that
would bring glory to my great Lord and Master,
or afford permanent peace to my own mind.
I continued to feel the weight of the exercise,
and as yet knew of no companion who was likely to join me;
but as I thought I felt at liberty to cast my eye a little round amongst my friends,
my attention was turned towards one in particular,
though I dared not write to her till I had weighed it, as well as I was capable,
in the true balance.
While endeavouring to do this, as my head was reclined on the pillow,
I suddenly felt a stop, and the weight of the exercise was taken from me;
but my mind was left in a state of depression,
for what cause I knew not--the only consolation I felt was,
that I could appeal to my heavenly Father, in this language; '`You know, O Lord,
that I desire to do your will.`'
My mind remained in a mournful state till morning,
not being able to rejoice in the hope that a ram was caught in the thicket;
but felt as if some new trouble awaited me.

On rising in the morning, I found this to be the case, as I received a letter from home,
giving me the affecting information of my dearly beloved
mother being seized with a repeated paralytic stroke,
which so much affected her speech, as scarcely to be understood in any conversation,
and that the doctor apprehended a sudden change might take place.

You wilt, I doubt not, conclude this was a close struggle for nature to bear,
and needed a fresh supply from the bountiful hand,
to enable me to drink the bitter cup with patience and resignation.
But blessed be the name of the Lord,
he is pleased often to mingle sweets with the bitters, which proved to be the case now;
for, although on my coming home, I found my dear mother so very weak and ill in body,
that there appeared no room to flatter ourselves with an expectation of her recovery,
yet her mind was favoured with such a sweet calm,
and appeared so remarkably patient under '`her allotted affliction,
that I scarcely dared allow a desire to enter, that she might be restored to us again,
believing our loss would be her eternal gain.
You may conclude I esteemed it a great favour,
to feel my mind relieved from the load of exercise which had so long attended it,
and at liberty to pay close attention to a dearly beloved parent,
whose tenderness and solicitude for her children have been such,
as seemed loudly to call upon us to use all our endeavours to alleviate her affliction.
But I may tell my beloved friend in freedom,
that here I brought fresh trouble upon myself;
for as nature rejoices to shrink from suffering,
so I was now glad to shake off the prospect of being called from home,
and thought the will would be accepted for the deed,
and that my whole attention should now be paid to waiting on my dear mother,
and that I should be excused from doing the Lord`'s work.
O, such was the artful insinuation of the enemy of our soul`'s salvation,
to endeavour to draw my mind off from a strict,
watchful attention to the pointings of the finger of Truth.
Well, it is with sorrow of heart I say, he did in some degree gain his point,
for I got unprofitably from under the deep exercise which had so long attended my mind,
with the plausible excuse of performing my duty to a beloved parent.
This brought darkness over my mind, and deep distress; but blessed be the Lord,
after he had in great mercy, chastised with his rod,
he was pleased to speak peace to my soul, and I became instructed in the belief,
that he that loves father or mother more than the Lord, is not worthy of him.

All must be given up to obey the voice of Him,
who has an undoubted right to employ his servants and hand-maids,
whom he is qualifying to work in his vineyard, how and when he pleases.
I may now tell you, the prospect has again opened in my view,
and I believe my peace will be concerned in closing in with it,
though the time for moving is not yet clearly seen, nor do I yet know of a companion;
but a little faith arises that one will be found,
when the full time is come for the offering to be made.
Perhaps indulgent Goodness will allow me a
little longer time to stay with my sick parent,
who is still living, though in a very weak state, wholly confined to her bed.

--

"`26th, fifth-day.--Went to Ratcliff meeting poor and low,
but had an open time of encouragement, and my mind is a little raised;
near the close I desired Friends to inform their neighbours,
that I proposed sitting with them on first-day morning next.

"`27th.--Attended the school meeting, and after it,
was favoured with a good time with the boys and girls separately.

"`29th, first-day.--We found a very crowded meeting at Ratcliff,
and it proved an open time.
The afternoon meeting was also large and favoured: I stood up near the close,
and told them that I had seen that day good things in
store for the inhabitants of this neighbourhood,
if on their part they would embrace the visitations of the Holy Spirit;
and that as divine Providence had allowed a devouring
fire to lay waste their outward habitations,
and they were now raising pleasant buildings on the ruins;
so if they were willing to let the searching and overturning power of
the Lord lay waste their old buildings spiritually to the foundation,
and remove the rubbish out of the way,
they in due time would be favoured to be built up a church and people to his praise:
and testimony bearers would be raised up amongst them to promote the work.
In the evening felt spent and poorly, but comfortable:
let the praise for this day`'s support be rendered to the Lord my helper.`"

[.offset]
About this time he received a letter from his beloved friend, William Savery,
dated Philadelphia, second month 25th, 1795, from which the following is extracted:

[.embedded-content-document.letter]
--

[.salutation]
Dear Thomas,

Perhaps it may have given you some surprise,
not to have received a line from me since we parted.
I waited to hear of your safe arrival, of which I was glad to be informed;
but it was only a short time before I left home with my dear companions,
to attend the Indian Treaty; and since we returned,
but few opportunities have occurred from this place.
I am persuaded you wilt be furnished with many excuses for me,
rather than place the omission to the account of any declension of my love for you,
or any lack of brotherly sympathy with you in your arduous engagements.
No,--my dear brother,
I can assure you that I felt more deeply for you when you were about to leave us,
than I remember to have done upon any similar occasion,
being no stranger to the tribulated path you have had to tread in this land,
even amongst your own people;
and I have no reason to believe that the general state of things, in a religious sense,
among those to whom you are sent, is such as to cause a less degree of exercise,
or a more easy path of labour.
I am not surprised to find that bonds and afflictions have been your portion;
for so it must be in every place where Christ Jesus, the Lord of life and glory,
does not reign--rejoicing cannot be the common or frequent experience of his servants:
yet through faithfulness, we may at times rejoice even in this;
that we are accounted worthy to suffer in some measure for his sake,
who suffered so much for us, that he might bring many sons and daughters unto glory.

I can readily conceive, my brother,
that your spirit will be frequently wafted across the mighty waters,
to visit your brethren and sisters of the North meeting,
who have you in frequent and very affectionate remembrance;
and I trust many of us will remain to be to you, and you to us,
as living epistles written in one another`'s hearts.
When we are favoured to draw nigh unto Him who sits between the cherubims,
may we mutually make intercession that his holy arm may
continue to be our protection and defence on every side.
We may with thankful hearts acknowledge,
that much brotherly love continues with those among us,
who put forth their hands to support the ark of the testimony;
but the riches and grandeur of this world, are leading many into captivity.
Our meetings are large, especially on first-day mornings,
when as many sometimes come as we can comfortably
accommodate on the men`'s side of the house;
and mercy and goodness still follow us beyond what we deserve.

Our very dear friends, Deborah Darby and Rebecca Young,
have been in the city during most of the winter,
and have visited the families of Friends in the lower meeting, +++[+++Pine street,]
accompanied by Nicholas Wain, until he was taken poorly.
They have often visited us at the North meeting,
and been largely engaged in very affectionate labour, which,
as I cannot doubt it has gained the approbation of all,
so I also hope it has been truly refreshing and fruitful of good to many.
They are greatly beloved by every rank in society;
have been much favoured in our crowded evening meetings,
and have had a meeting in the North house, and another in Pine street, of an evening,
for people of other societies, and truth`'s testimony was exalted in both.
They also held a meeting in the Jail, to which I accompanied them.
The poor prisoners, of whom there were about two hundred, were many of them tendered,
and some much broken; and indeed it was a solid favoured time.

I am anxious that you may not, as dear Samuel Emlen says,
abuse my fellow servant by greater exertion and more continual
exercise and labour than your bodily frame can support.
Let me remind you, that we serve not a hard master, or an austere man, as you well know;
therefore, embrace times of relaxation, as wisdom directs and opportunity offers,
in order to recruit your health; for I much desire after your labours abroad are over,
to have the pleasure of sitting side by side with you among our own people,
that we may be favoured to share together,
as has been the case in some measure heretofore, that inestimable peace,
which is the sure reward of faithfulness unto God.
My brother, pray for me, for Satan often desires to have me, that he may sift me as wheat.

[.signed-section-closing]
My prayers attend you, and in dear unity, I continue your brother,

[.signed-section-signature]
William Savery.

--
