== Chapter VIII

The yearly meeting of London coming on,
and his mind being brought under deep exercise and discouragement,
no memorandums occur until the following:

I laid aside my pen until this morning, the 6th of sixth month, and second of the week;
feeling more cheerful and comfortable in mind.
I have passed through a scene of affliction of late,
not only during the time of the yearly meeting, but since;
my religious prospect appearing at times almost like a brook dried up.`"

The following extracts are taken from a letter which he received while in London,
from his beloved friend Rebecca Jones:

[.embedded-content-document.letter]
--

Sitting pensively and alone this evening,
while Friends are assembled at the High street meetinghouse,
and recounting some of the Lord`'s gracious
dealings and marvellous acts towards and upon me,
you were brought so preciously near to my disconsolate mind,
that I have taken the pen in hand to tell you so.

Your letter to me, written partly at sea,
and your remembrance of me in those to your dear wife and son,
both revived and contrited my spirit.
Our dear brother Samuel Emlen was at our North meeting this morning,
where he was enabled to declare the Master`'s counsel faithfully in a living testimony,
which, with a similar one from dear Deborah Darby two weeks ago,
was like '`summing up the evidences`' for me,
now near the close of the arduous family visit I have been engaged in,
and which I trust will be completed in another week.
I have proceeded gradually, often beset with discouragements,
often in great weakness and fear.
But the Lord who healed me in sickness, has been near,
and to Him be the praise of his own works;
for indeed his hand alone has opened a door of admission into the houses of my friends,
and melted many of our hearts together,
under the softening influences of his great mercy and lovingkindness toward us.
May I be kept little and low before him,
and may you derive some encouragement from this feeble testimony to his goodness;
so as to finish the work which may be given you
to do in that part of the Lord`'s vineyard,
where he has many precious plants, unto whom my spirit is united in Christian fellowship.

Our yearly meeting was large and solemn, and some steps have been taken, I hope,
in best wisdom, for the advancement of the great and good cause:
a joint committee of men and women Friends was appointed to consider
and arrange matters for opening a boarding school for the youth;
so that in time we may have an American Ackworth, which was dear Sarah Grubb`'s prospect.
I am too old to enter again into the service,
but as my heart wishes prosperity to the work,
I have submitted to have my name on that committee.

When the afflicting tidings of dear Elizabeth Drinker`'s departure arrived,
I went down and stayed a great part of the day with dear Daniel and Abigail,
where I had to tell them that our sitting solemnly together reminded
me of the time when Job`'s friends sat with him in silent astonishment,
and that it was sealed upon my spirit, with regard to the dear departed,
that all is well.
Soon after this your letter to Daniel came to hand, and I read it to the relations,
wherein were the very same expressions,
which you offered as descriptive of your first visit to her.
They bear the affliction as becomes Christian minds, and will, I hope,
be supported under the close trial,
by the same good hand which was so eminently near her to the end.

--

[.offset]
After alluding to several recent deaths she says:

[.embedded-content-document.letter]
--

It is indeed a solemn day everywhere:
O that the inhabitants of the earth may now learn righteousness.
May the work you are engaged in be blessed by the great Master;
for as the ability is from him,
so must we also leave the outcome with Him who can work without us, and also with us,
as he pleases.
May your heart endure and your hands be strong in our Master`'s service,
that so his blessed will may be perfected, and your peace flow as a river.
Think sometimes of poor me, and intercede when you can for my preservation; for O,
I feel as though I should sink like poor Peter did, was the divine hand withdrawn;
and my faith, like his, is often very small.

You are frequently in my affectionate remembrance,--may the Shepherd of Israel,
who evidently put you forth, go before you and make all your labour prosperous,
under his immediate blessing; without which, neither the planting of Paul,
nor the watering of Apollos, will promote the intended happy increase of righteousness,
which is in the Lord`'s time to cover the earth, as the waters cover the sea.
May infinite Wisdom be pleased, for his own name`'s sake, to hasten this day;
and may we wait in patience, and endure hardness as good soldiers, for Christ`'s sake,
seeing that to him and his followers the victory is decreed.

--

"`Went to morning meeting in a humbled condition, and soon prostrated myself on my knees,
and prayed to the Father and fountain of mercies, for myself, and my fellow-labourers,
both on sea and land, our wives, children, etc.,
and for all the Lord`'s gathered messengers.
Spent part of the afternoon retired alone in my chamber, under close conflict; and yet,
after so often mentioning these things,
I know there is no room for murmuring or repining.
Cast your care then, O my tribulated soul, on the Lord,
and patiently wait until deliverance comes.
What greater trial is there than to be stripped and unclothed of all good,
and to sit in this state from day to day, and appear like an idler in the work,
so far from home; these are peculiar trials.

"`12th, first-day.--Attended the meeting at Tottenham,
in which Sarah Harrison had a remarkably close time;
soon after I took my seat in the afternoon meeting,
I felt a little to communicate in weakness to some of the servants,
and those of low degree, etc., in an encouraging line.
Sarah Harrison had such a searching time,
that it seemed as though my foundation was brought to the test,
and I thought she was rightly led, whether I was or not.
Ah, me! what a poor soldier am I, if indeed I am one at all.
I have put on a cheerful countenance, and in some instances of late,
when in company with my valued brother, David Sands,
I have been roused and cheered a little; but still my heart has been sad.

"`14th.--Felt a little ray of light and sweetness on awaking this morning.
After breakfast looked over this book of my journeys, travels and conflicts,
to this time; and truly I think I am a poorer creature than heretofore.
O that I may be accounted worthy of the name of a servant of Christ.
Surely my state now resembles that of one laid aside; but dare I complain,
even if it should be the blessed Master`'s will to lay me aside!

"`15th.--Went to town with Thomas Horne and wife, and to Grace-church street meeting,
where I found David Sands, and it was a solid, silent time:
the adjournment of the monthly meeting was held at the close,
when a certificate was read and signed for George Dillwyn to visit Germany,
his wife being included in it.

"`19th,
first-day.--This morning Joseph Smith and David Sands stopped
with a postchaise and took me to Hartford meeting;
in which dear David was preciously enlarged, especially in the afternoon,
in a meeting appointed for the people of the town.

"`20th.--To the quarterly meeting,
which I hope was throughout a good time of encouragement.
David Sands and I visited the women`'s meeting.

"`21st.--David Sands and companion inclining to go to London,
to be at Devonshire house meeting,
and dear Sarah Harrison appearing under a close exercise to go to Brentford meeting,
I felt at liberty to accompany her: and though I had nothing to communicate,
yet was willing to bear up her hands, and got back to Tottenham in good season.
Felt my mind, this evening, drawn much inward, under close exercise,
and was shut up from conversation; and when we sat down to supper,
was favoured to prostrate in humble supplication.
It was a time of baptism, I trust to be remembered.
After which I lay down more sweet and comfortable than for a long time.
O what a favour once more vouchsafed to poor unworthy me.

"`22nd.--A sweet refreshing night, and comfort extended when awake.
Awake then, O my soul, and listen to the voice of your beloved, who has not cast you off;
look forward with humble, depending patience, and hope in his mercy.

"`24th.--Attended the scholars`' meeting at Clerkenwell;
there were not many men Friends there;
but to me it was an open comfortable time with the children:
afterwards I stepped over among the poor women in the Alms house,
and had a tendering time.
In the evening went to an appointed meeting for Sarah Harrison,
held in a barn about two miles from Tottenham; it was large, and I hope to profit.

"`25th.--At Tottenham meeting, both morning and afternoon, which were favoured seasons;
David Sands and I returned to Thomas Horne`'s together,
and after supper he was much opened in conversing on some passages of Scripture,
to our edification and comfort; and in the close a sweet covering of good,
more and more spread, and I kneeled down in supplication;
dear Sarah followed in the same line, and it was indeed a memorable evening.

"`27th.--To London quarterly select meeting; and in it I felt unwell and much exercised.

"`28th.--To the quarterly meeting for business,
and hope I was favoured rightly to bend in supplication;
and this was all that fell to my share, either in the public meeting,
or in the business part.`"

From the 29th of sixth to 10th of seventh month,
was mostly spent in visiting the meetings in the vicinity of London,
particularly Tottenham; and also a considerable number of families,
in which he was favoured with ability to open the states of individuals,
and administer proper religious counsel;
describing them as being frequently heart-melting, humbling or tendering seasons.

[.offset]
From London he addressed a letter to his friend Rebecca Jones, dated seventh month, 1796,
from which the following is extracted.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to Rebecca Jones

[.salutation]
My very dear friend,

Your letter, which came safely to hand,
is a fresh proof of your sisterly sympathy and love, and has done me much good.
It was pleasant to find that you had been to New York and Rahway,
the latter a place both of exercise and of favour to me in days past.
From what I have lately heard, I do not marvel that your sorrow has been great,
and the language of my soul at this moment is, not only on your account, but also my own,
'`Lord, bring me out of my distresses,
and preserve through all that you in your wisdom may permit to come upon us.`'
And, my dear friend, my faith is renewed on your account,
that your feet will not be moved from the sure foundation; and after saying so much,
it is in my heart to add, remember poor me.

Very pleasant to me was your account of the young preachers.
I rejoice in their growth; remembering, and humblingly so,
how mercifully I was cared for in the day when, like a little child, I tottered along,
and sometimes slipped, and fell and bruised myself thereby;
yet help was reached forth both immediately and instrumentally.
When we remember those seasons, who can grudge or deal hardly with any of the little ones.
I was glad to hear so good an account of dear J. W.,
he was near to my best life before I left you,
and I thought what has happened would come to pass, and told him so.
May the great Master of the family and Shepherd of the sheep,
preserve all on the right foundation,
and enable them to spread his name abroad in due time.

O what stripping has there been among you, since I saw your faces!
I have had many humbling thoughts in looking at these things,
but have consoled myself in the persuasion,
that the God of the whole earth doubtless does right.
I request you to call and, as ability is afforded,
yield the sympathy of your spirit to my dear wife and aged mother;
and when you have a little of heavenly good,
do not withhold it from your poor and often tried friend,
who needs your sympathy and prayers for his support, and probably may yet more need them.

--

"`Seventh month 10th,
first-day.--Having heard that Wahham Abbey meeting was to be opened this day,
for the few living in that neighbourhood and Epping,
I felt a freedom to go and sit with them, and was accompanied by Thomas Horne,
wife and daughter S. Soon after I sat down among the little company,
some encouragement spread over my mind,
and after a time I arose on my feet and endeavoured to express it;
and before I had done a number of persons of other societies came in,
and I hope on the whole it ended well.

"`We stopped at John Burgess`', and after some time spent in conversation,
my heart was filled up,
and broken under a sense of the Lord`'s mercies to me from my youth,
in leading me about and instructing me to that moment,
I had an opportunity to express some of the feelings of my mind;
and it opened an effectual door for my exercised friend to relieve her mind,
in which I rejoiced.
Returned back with sweetness of mind,
and had another opportunity at Thomas Horne`'s with a number of youth;
here I learned that William Savery had arrived in London.

"`11th.--Set off rather earlier in order to see dear William before meeting,
but found he had gone.
How were my feelings awakened in several respects,
on dear William`'s certificate being read,
and the prospect of his accompanying David Sands and George Dillwyn into a strange land;
mine in that respect closed up.
I desire to wait on Him who has, in abundant mercy, made hard things easy,
and bitter things sweet.
The sorrows of my heart have of late been great, and yet not without a mixture of joy,
for which I bow, I hope with reverence and awe, knowing I cannot add anything,
neither diminish.
Surely it is of the Lord`'s goodness I am not confounded.
Attended the school meeting at Clerkenwell, and an examination of the scholars.
William and David had good opportunities with the children.

"`15th.--Went on board the ship William Penn with Nicholas Wain, my father David Bacon,
Sarah Harrison, George Dillwyn and wife, David Sands, William Savery, and others.
Nicholas Wain appeared easy to take his passage.
After dinner retired for the purpose of writing.`"

[.offset]
In a letter to his son, dated the 16th,
in alluding to the circumstance of a house in the vicinity of his own,
being struck with lightning, he says:

[.embedded-content-document.letter]
--

I notice with renewed thankfulness, your preservation '`from the arrow that flies by day.`'
We have been kept in a season when terror was in the night;
and when the pestilence walked in darkness, and destruction wasted at noonday.
Many have fallen at our right hand and at our side,
and only with our eyes have we so far beheld his marvellous work.
O may you all keep this so great mercy in view,
not knowing how soon it may be the pleasure of
Omnipotence again to visit with these things.
And if both I and you, of my dear family, are concerned to make the Lord our refuge,
even the Most High our habitation, he will then, doubtless,
condescend to keep us in all our ways, and direct our steps aright;
and whether sooner or later, make all our bed in sickness.
This is what often occupies my mind; for indeed,
to be favoured in time to be the servant of the Lord, doing his will, and not our own,
and to seek earnestly after a habitation with the just,
is worth living and suffering for, according to his will, often bearing in remembrance,
that here we have no continuing city.

I am comforted in the persuasion, that you will not lose sight of these important things;
and if so happily favoured,
then I know that the Lord will bless you and give you enough of the earth,
for the cattle of a thousand hills are his, and he gives and dispenses at his pleasure.
Therefore, seek first the kingdom of God, and the righteousness thereof,
and all things necessary will be added.

--

"`17th, first-day.--This morning I felt most easy to go to Ratcliff meeting:
my father-in-law, David Bacon, and Joseph Smith accompanied me;
and we were favoured with an open good time;
and in the close requested Friends would take
pains and invite their neighbours to the meeting,
my dear friend and brother David Sands, intending to sit with them.
To the meeting at six o`'clock, where I had some little to communicate,
and David a large time, and I hope it was to profit.

"`18th, second-day.--To morning meeting,
and at six o`'clock to a large meeting held in a barn near Blackwall,
appointed by Sarah Harrison, which was a satisfactory time.

"`19th.--To Devonshire house meeting, where I found William Savery, who was silent.
I had a good time, also dear George Dillwyn.
William appointed a meeting at six o`'clock, for the inhabitants.
Went home and dined, and after a heart humbling season,
wherein both David Sands and Sarah Harrison appeared in
prayer for the preservation of the poor labourers,
etc., and taking an affectionate farewell, my father David Bacon,
accompanied me to Thomas Horne`'s; soon after which,
came in Thomas Phillips and several others, with whom, and this family,
I had a tendering time, and after it spent the evening sweetly.`"

[.offset]
The following extract is taken from a letter addressed
to him by his beloved friend Mary Dudley,
dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ross, Seventh month 2nd, 1796.

[.salutation]
Beloved friend,

When I was in this place some weeks ago,
the stream of precious fellowship ran so strongly in inclination to salute you,
that I have often since regretted that I did not yield to it;
not that I then knew I had anything good in possession,
nor am I now sensible of any qualification, but the renewing of the same feeling,
and the continuance of that love,
which I trust will never be quenched by any of the waters of trial or waves of conflict,
with which the poor vessel may yet be tossed in
its probationary passage to the land of rest.
Surely, if ever I am favoured to enter the harbour, it will be through abundant mercy;
for at seasons, so many are the fears attendant on the path allotted me,
that the grain of faith seems too small to keep
in steady hope of everlastingly anchoring there:
nevertheless, when favoured to get into the region of calm resignation,
faith strengthens and hope revives;
and knowing that the Lord sits above the water floods, and remains King forever,
the burden is, I trust, acceptably cast on him, and a consoling persuasion experienced,
that he continues to care for me.
These are things mostly worn within, but to you, my dear brother,
it is no marvel if the heart should get a little vent,
seeing how wondrously your mind has been dipped in relation to a subject, wherein,
like the roll written within and without,
my meditations are employed oftener than the returning day,
though I thought not of touching upon it just now.

It was a sort of sad communication which my spirit seemed holding with yours,
and the uniting feeling inclined me thus to tell you so;
believing yours is truly a path of deep exercising travail,
wherein perhaps the tracks of many footsteps are not seen--a
line wherein you are made to resemble your great Master,
who '`was a man of sorrows, and acquainted with grief.`'
Well, this you know is the acceptable way to '`fill up that which is
behind of the afflictions of Christ for the body`'s sake,
which is the church.`'
And O, says my soul,
that great was the addition to the church militant of
such members as were resigned to these dispensations,
and willing to be plunged deep enough to complete this measure of inward suffering.
But do not fear, I speak freely what I have said in my heart often,
that there is much of a dwelling on the surface, not only in people, but in the ministry?
Are the different states visited by all thus concerned,
as their various exigencies require?
The ground of true ministry appears increasingly awful to my view,
and '`Who is sufficient for the work,`" is the frequent inquiry raised;
and who can be fitted,
but such as are willing to drink of the cup and bear the repeated
baptisms. These bear about in the body the marks of the Lord Jesus,
and these availingly visit the sick and imprisoned seed, even in silent travail,
when deep only utters unto deep.
Well, my endeared friend, great is the liberty of the truth,
and much the freedom with which I address you, as though conversing, or,
as dear Esther Tuke used to say, '`thinking aloud.`'

--

"`20th.--Set off this morning about eight o`'clock, with my dear father,
who has given up to accompany me a little on my journey, and several other Friends;
put up at Benjamin Finsham`'s, and attended the meeting of Friends.
Appointed one for the town`'s people at six o`'clock.
Went to James Haley`'s, where came his brother and sister Coxhead,
with whom I had a religious opportunity, and it appeared to be well received.
He is called sir John, and is a member of Parliament; she, a plain woman.

"`21st.--This morning we stepped into most of the families of Friends.
Dined at Thomas Coxhead`'s, with his wife and several others, he being gone to London;
and after it my spirit was broken and humbled so much as to bring me on my knees.
I remembered a circumstance which occurred,
when I set out with David Brooks for New England;
we had stopped at a house several days`' journey from home,
and taking up an old Testament, I attempted to read;
but my spirit was swallowed up with such a weight and solemnity, and,
as I then apprehended,
the spirit of supplication was poured out on me as I had never felt it before,
that I could not read; and laying down my book, sat in an awful state of mind,
until called to dinner, and then gave way to my exercise; and after it my elder brother,
David Brooks, continued the same.
Ah! surely it was a moment not to be forgotten by me, in my then infant state.
And how earnestly did my soul crave preservation in this season now vouchsafed,
both for myself and for others in an infant state.

"`22nd.--To Benjamin Finsham`'s. Here we obtained
liberty to go and set in the chamber of a sick daughter,
where we had father and mother, son and daughter together,
and my friend Susanna Horne was favoured fully to relieve her mind, for which I rejoiced;
and taking an affectionate leave,
my father and I mounted our horses and pursued our journey.
Stopped on our way about four miles, and visited a widow and daughter-in-law, which,
I hope was a time of encouragement.
Got to Bishop Stortford about two o`'clock,
and soon after gave liberty to invite their neighbours,
to come together at meeting at six o`'clock.
I admire at the kindness shown me of latter days.
My burden has been lightened and I moved on cheerfully this day,
accompanied by my dear father.
The appointed meeting was large, and to me a laborious one, but was favoured,
after a considerable time of silence, to begin in great weakness, and got through.
When I was coming out, I met with a large number of poor,
shabby looking youth on the stairs, who stopped, and some also were near the door,
and I had to encourage them to be good children, that so they might be made great;
having had in the course of my testimony to address such,
and told them that God was able to raise up from the stones of the street,
children unto Abraham.

"`24th.--To meeting at Saffron Walden,
and was favoured with an open precious time of encouragement,
and at the close appointed one for the town,
which was a season of much enlargement in testimony with me,
and I had a sweet refreshing time.
After getting home and sitting quiet, a humble hope revived,
that the Lord my heavenly Master would not leave me,
though he may see fit yet to prove and try my faith, patience and love.

"`26th.--To the monthly meeting, which was larger than usual,
and attended by several youth from a distance;
in the forepart of it my soul was humbled and prostrated in prayer for myself,
fellow-labourers in this land and others, with those left behind at home;
and afterwards I had a pretty large time in testimony.
The business was sweetly conducted in brotherly love;
we dined at George Gibson`'s with a number of Friends, after which came in several more,
and among them I had a full good time, tendering the minds of several of the youth;
soon after which had to part from my dear father David Bacon,
he setting off with William Grover and wife, with a view of returning to London,
and I am left behind without a companion; but not like a partridge on the mountain,
or a sparrow on the house top, because sustaining help has been near,
and still remains to be so at this moment.
Thanks be rendered where they are due:
and O may my poor soul trust in the Lord throughout the present journey,
and to the end of my pilgrimage in this land, come whatever may be permitted to come,
to try me.

"`27th.--Arose in a poor and stripped state, and went to the week-day meeting,
where I was soon favoured with such a sweet silence,
and in it had to look towards my dear wife,
with faith to believe that the Almighty arm is near to sweeten her mind,
and protect those I have left behind, in life or in death,
that I could have sat contentedly through the meeting in silence.
But after a season I was favoured to minister a word of encouragement to my friends;
and surely there is need of humble thankfulness
for the favours I have experienced of late,
and since coming to this place.`"

On the 28th he was at Stansted; 29th at Thaxted; 30th at Dunmow; and the 31st, first-day,
at the meeting at Chelmsford, in which he says,
"`Elizabeth and George Gibson had a little to communicate,
and I thought in the forepart something would have fallen to my share,
but all was dried up, and I sat the meeting through in silence.
In the afternoon my mind was drawn to look toward my dear wife and family,
far separated in body from me.
How has my spirit been present with them,
accompanied with prayers and supplications to the Father of mercies on their account,
and with sweetness and assurance that the Preserver of men is near and will be so:
this has often been the case, and yet when thoughts deeply impress my soul,
that if it should be ordered in the counsel of our God,
that my dear companion and I meet not again in this world,
surely I have believed that we shall in the world to come,
where there is neither marrying nor giving in marriage,
as says our blessed Redeemer and Saviour;
and where such as finish their course with joy in this world,
are to be as the angels in heaven.
Even so be it, O God, with humble submission says my soul,
whether such a baptism be to try my faith and love and the stroke be deferred,
or whether I may be as a sign to the people in this land, as the prophet was in his day.
O my God, favour me as much as is profitable for your servant,
to put sorrow away from my heart,
that both with flesh and heart I may seek your face continually,
and be favoured to do and suffer your blessed will,
which will be my sanctification--Amen.`"

[.offset]
While here he addressed the following letter to Sarah Cresson,
who had been but a short time in the station of a minister:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Robert Marriage`'s, near Chelmsford, Essex, Eighth month 1st, 1796.

[.salutation]
Dear Cousin,

Having left most of my letters in my trunk in London, and yours among them,
I have it not with me; but thinking much of you this morning,
which I may tell you I have done at other times, with near and tender affection,
I concluded to take up my pen and tell you so.

Many and various are the trials which such poor things as I am,
separated from near and dear connections, have to pass through;
and they have a tendency to dip the mind into a feeling sympathy with
and for those who have set out in the same blessed work.
The desire of my soul is, that you,
with all those who are called of our heavenly Father to labour in his vineyard,
may keep steady to the work; for blessed are they who keep their hands to the plough,
looking and pressing forwards, under the direction of their Holy Head and High priest.
These will meet with sufficient encouragement by the way:--remember then, dear child,
the way to profit is to give yourself wholly to the work,
so will your profiting appear to all;
study to show yourself approved unto the Lord your God,
a workwoman in his house and family that need not be
ashamed,--rightly dividing the word of Truth,
unto which service you are beyond any doubt in my mind called.
Let not little acts of faith and love, in the gospel of him,
who has called you and sanctified you for his work, pass by undone;
for a cheerful surrender of your will and faculties in little acts of obedience,
will make way for more, so wilt you know your day`'s work keeping pace with the day,
and then you may look forward to the end, which crowns all,
even a finishing of your work and course with joy, and receive that crown,
which is laid up in store for all such as love the Lord Jesus Christ, and do his will.
Love retirement and reading the Holy Scriptures.
Treasure up such parts of them as forcibly strike your mind,
and then at seasons you will witness the key of David handed to you,
which will unlock your little treasury, and open the mysteries with more enlargement,
for the help and benefit of others, who are ignorant and unlearned.
Here is the use and end of a gospel ministry, which is not received of man, but of God;
and that which is received in secret, quiet retirement, revives in meetings and families,
and commandment is given to proclaim it abroad.

Therefore, as a beloved younger sister in the work,
I charge and counsel you to give yourself to reading, meditation and prayer,
and may your God and mine give you wisdom in all things,
to go in and out before the people.
Let no one despise your youth; neither let in discouragement from this quarter;
but in humility and reverence, seek for a qualification to say, Here am I Lord,
first prepare and then send me.

I have now, while writing, the pleasant company of my valuable friend and mother,
Elizabeth Gibson: she and her husband have both been with me nearly a week.
He has gone to a monthly meeting about eighteen miles off,
and has left me at his son-in-law`'s to rest,--
and if they do not both go on with me tomorrow,
I expect dear George will, and for all I see, go with me through this county.
He is indeed, in my opinion, a choice-spirited Friend,
and a comfortable couple they both appear to be, much beloved by their friends.
Two nieces of his live with them,
who have been as affectionate to me while at their house,
as I could look for my own children to be;
and very comfortable I felt under their uncle`'s roof.
I thought this account would be pleasing to your dear mother,
to whom present my continued love and sympathy; and tell her,
that it was good house-keeping formerly, when the prophet kept the widow`'s house;
and my desire is, that the great Prophet of prophets,
may yet have room in her house and heart.
My dear love to your brother Ebenezer,--tell him,
though I have not felt qualified to answer his affectionate letter,
yet he may be assured that he has a place in the mind of his absent relation,
who has rejoiced in hearing that he was dear J. W.`'s armour bearer.
And O that he and my dear son,
may be companions in the way that leads to the everlasting kingdom.

My love to all the rest of the precious lesser plants in the family.
O that they may grow up as plants in their youth,
and know a being dignified by the Truth in their day.
May you and your dear mother be encouraged to continue labour towards them,
to bend the tender twigs and form the mind.
Ah! how my heart yearns towards my own likewise, for whom my prayers are put up,
that they may be the Lord`'s children.
In near and tender love I salute you once more,
who am your affectionate friend and relation,

[.signed-section-signature]
Thomas Scattergood.

--

"`Eighth month 2nd.--After attending the meeting at Maiden,
which I trust was a profitable one, rode to the widow Hurnard`'s.

"`3rd.--A solid opportunity with this family, including the servant maid,
who was very much tendered, even to weeping aloud.
Went to meeting at Witham, where I understood was a Roman priest,
one of the emigrants from France, a curate, and various persons of note,
among them a physician, who had been much prejudiced against Friends;
he stood most of the time, and appeared considerably tendered.
A Friend meeting him afterward, he was broken, and sent his love and good wishes to me,
and appeared much satisfied in being at meeting.
The Lord be praised for the manifestations of his goodness to my soul,
both in the meeting and since, by shining through the cloud.
Were it not for a draught of living water from the brook by the way,
what would become of such a poor lonely creature!

"`4th.--To the meeting at Kelvedon, which was large, and an open favoured time;
the people behaved well.
The people in the streets, as we passed along,
were very respectful and kind in noticing me, and I felt much love to them.
A number of poor children were at the meeting,
and I hope from among this class the Lord will raise up, in time, children unto Abraham,
even`' as from among the stones.
A number of persons of higher degree attended also,
and I trust it was a meeting which will be remembered--
the Lord be praised for the help extended.

"`5th.--Attended the meeting at Coggeshall, and though I had a large time,
it was not so open as yesterday:
the circumstance of James Parnell being taken up in this place, revived in my mind,
and I had to mention it; also the great sufferings of Friends in those days,
and now how we are favoured:
I was in no danger of a prison for preaching the gospel of life and salvation.
After dismissing those not of our Society, I stopped with Friends,
and had a tendering good time.

"`6th.--Although favoured in meetings and in sittings,
and with a quiet mind at other times of late;
yet I could not but weep on my pillow this morning on looking forward.
O for purity of heart!
Surely, if this gives us to see the face of a merciful God,
it will have a tendency also to open the eye to see our duty clearly in all things.
The meeting at Copford was an open good time,
wherein I found it much easier to get relief than I often do.
Dined at an inn near by, and afterwards rode to John Kendall`'s at Colchester, who,
with his wife were at the meeting.
After tea I took a walk with George Gibson and John Kendall to the castle,
and went over the old ruins, where I was shown the hole in the wall,
from which it is supposed dear James Parnell fell when confined in this place; and also,
his apartment below, which looks like a baker`'s oven;
the thickness of the wall being about four times the length of my walking stick.
Went into the library, and saw among many old books, a number of Friends`' writings.

"`7th, first-day.--The meeting was largely attended by Friends and various others,
and I had a full good opportunity; at the close,
appointed one at six o`'clock in the evening, which was very large, and an open,
relieving time; in the course of which, I had to mention the sufferings of the martyrs,
and of our Friends in the beginning,
and particularly of that innocent youth James Parnell, in this place,
and advised the people to read his writings,
and seek and inquire after the truth for themselves.
They behaved remarkably solid, and left the meeting so,
even those who stood out of doors, who were many.
One person in the morning was much affected, and refused to go away,
though his companion urged him to leave the meeting--twice coming back for the purpose.

"`9th.--To a meeting held in a barn at Manningtree, which was large,
and an open good time: the people manifested much kindness,
several of them taking me by the hand and expressing it.
Rode to Harwich in the evening, and lodged at an inn.

"`10th.--To a large meeting in the market place, which was solid and comfortable;
the people showing much kindness and respect.

"`12th.--To a meeting at Halstead, which was nearly filled up with the town`'s people,
and a pretty open time: stopped with Friends afterwards,
and was engaged to stir them up to maintain the
precious testimonies given us as a people to bear,
and also to encourage the mournful travellers.

"`13th.--Went to a meeting at Colne under pretty close exercise and thoughtfulness,
respecting the uncertainty of all earthly comfort, and soon had to begin on this subject.
It was a tendering season to some.
There were present a number of poor aged people, leaning on their staves, one blind,
etc., and I was ready to think the plunge I had before the meeting,
and in the forepart of it, brought me into sympathy with such.
After dinner we rode to Halstead, and after tea to Joseph Smith`'s, near Stebbing.

"`14th, first-day.--Attended Stebbing meeting,
which was filled up with Friends from different places, and many of the town`'s people;
among whom I went poor and stripped, and continued so for some time; but afterwards,
strength arising, I had an open time.

"`15th.--After resting the greater part of this day we moved to E. Knight`'s,
at a little village called Fenchingfield.
This kind Friend, after the meeting on first-day,
mentioned his desire that I would have a meeting in this place:
it does not appear there ever was a Friends`' meeting held here,
and none but himself and wife, under our name, reside in the village.
When we came to his house,
he took us to see an old bark house which he had fitted up with seats and a gallery,
and he was out until after ten o`'clock giving notice,--
going about five miles off after we arrived.
May the Lord bless his faith and love to the cause in which I have embarked.

"`16th.--Went to the meeting, which was very large,
many being out doors--and it proved a favoured, open time; in which, through holy help,
my heart was much enlarged, and the people behaved solidly.
I remembered these expressions; '`I am the Lord that heals you,
that teaches you to profit; and which leads you in the way by which you shouldest go.`'
Notwithstanding I exerted myself for a long time,
I felt much better than I did before meeting--the pain in my breast,
which I had had before, being removed.
In the evening had an opportunity with E. Knight, wife and daughter, to my satisfaction.
I have not met with greater faith and love, I think in this land,
than this Friend has manifested.
I thought of the governor of the island of Tortola,
who caused seats to be carried many miles on men`'s
heads to accommodate a meeting held by Thomas Chalkley.
+++[+++See [.book-title]#Friends Library#, vol. 6, p. 114.]

"`19th.--A struggling, humbling night:
and though I felt very poor and unworthy in the morning of this day,
and went so to the meeting at Haverhill, nevertheless,
I was much enlarged in a full meeting for the town; the house not containing the people.
I was informed that this was a place of suffering to our forefathers--now, what a change.
A priest attended the meeting, as well as a doctor and lawyer, and it was a solid time.

"`21st, first-day,--Went to Cambridge with James Wright and daughter,
where I met with George Gibson and wife.
When we went to the meeting, a multitude were gathered in the street and passage near,
and after the doors were opened, they soon filled the house, and it proved a solid time.
Dined at the inn with nearly forty Friends,
and had an opportunity with this large company,
wherein I endeavoured to persuade them to hold up their light before the people:
near the close several neighbours came in, to whom my mind was afresh turned.
After I had parted with dear George Gibson,
and he had rode about a mile on his way to Walden, he was not easy without following me,
and he overtook us and accompanied me to his nephew`'s at Royston.

"`22nd.--I find this morning that there is a little company under our name in this place,
and after some thoughtful exercise I was most easy to see them by themselves.
I accordingly had an opportunity with them; and a full, close time it was,
and dear George rejoiced that he came to us.
We then went to Hitchin and put up at Rudd Wheeler`'s.

"`24th.--Feeling easy to move from this place, Hitchin,
and mentioning it to Rudd Wheeler, he prepared to go with me.
We got into Amersham near dark, after riding about thirty miles.

"`25th.--Attended the week-day meeting; several of the town came in, and I had an open,
good meeting.
This is the town where the corpse, mentioned in Thomas Ellwood`'s journal,
+++[+++See [.book-title]#Friends Library#, vol, 7, p. 394,]
was thrown from Friends`' shoulders and laid in the street some time; and Isaac Penington,
Thomas Ellwood and others were put into prison for attending the funeral.
I was shown the place, near the market house.
After tea we went to High Wiccomb.

"`26th.--To the meeting at High Wiccomb,
and on the 27th got into Oxford and put up at an inn.
On entering into this town we were mocked by the children;
and I have not noticed more drunkenness anywhere in this land,
than in walking through this place this evening.

"`28th, first-day.--Went to meeting poor and stripped; it was very large and crowded.
A remarkable quiet attended the gathering, and continued throughout;
and the people parted with much solidity, to my humbling admiration; for it was an open,
good time to me, and I hope to many others.
At the close I stopped the few Friends that live in this place,
and we had a comfortable time together.
After dining we set off, passing through Witney, and arrived at Burford,
where we met a kind reception from Thomas and Elizabeth Minchell.

"`30th,--After a silent sitting with T. Huntley`'s scholars,
and the few Friends who live in this place,
I felt easy to move on,--passed through Tilbury,
where stands an old meetinghouse of Friends, but no meeting is held in it.

"`31st.--Proceeded to Cirencester and put up with Thomas Brown.
To the week-day meeting at this place, which was a pretty open time:
in the afternoon went on to Bristol, where we arrived towards evening.

"`Ninth month 1st.--To Thomas Phillips`', near the Wells,
where came the widow Usher and daughter,
who are attending upon a daughter in a consumption, and near her end;
and a sweet season we had together.
When I met with them in Waterford, Ireland, they were gay women,
now so friendly and plain that I did not know them.

"`6th.--The meeting here was large, and I had a pretty open, relieving time,
though close to some states, yet a comfortable opening toward the visited youth.`"

[.offset]
While at Bristol he wrote a letter to his friend Susanna Horne, dated ninth month 7th,
from which the following is taken:

[.embedded-content-document.letter]
--

I parted from you with a cheerful mind, believing your stay with us was right,
and it was not long before a vacancy was felt by me,
who am frequently a poor blind creature,
but endeavouring to cast my care on the great Caretaker and Preserver of his servants,
I moved on from place to place, as way opened.
I had to admire how my spirit was supported in the season of
parting from my affectionate father and friend +++[+++David Bacon;]
the Shepherd of Israel being my support in that hour, enabling me to resign up wife,
children, and, I trust, all into his hands, who knows best what is best for us.

You have been favoured with a sense of my state in coming to this place,
and I seem at some loss how to describe the feelings of my mind.
However, this is the sum:
it was like going down into the valley and shadow of death,--O
the buffetings and inward presentations of evil,
both night and day, that I experienced; so that I have been ready to say,
Surely my soul dwells among lions.
At times all seems gone, and fear surprises me as in the night;
when former experiences are called in question,
and sometimes the apprehension stares me in the face, that,
after all I have passed through, deceit may so enter that I shall fail.
Such close things have escaped my lips, in two meetings I have attended,
that I have in some degree trembled in myself; and surely I have need,
considering what a poor creature I am.

--

"`8th.--To the meeting at six o`'clock, and after sitting a considerable time silent,
felt a portion of encouragement to hold forth to the sincere seekers and mourners;
having first been favoured with a ray of light and encouragement myself.

"`11th.--Attended meeting here again, which was large, and a remarkable time.
O what a mercy and favour; and yet, afterwards the tempter was near,
who would whisper this language; '`Well done; you have had a large time.`'
O may my soul be prostrated!
The widow Usher and daughter Lucy, and other Friends dined with us,
and when we sat down to table I ventured to appear in prayer,
which proved a tendering season; the Lord be praised, and the creature abased.

"`12th.--A tendering time at breakfast, with a large number of Friends.
Two seeking people came to see me; one of whom went with me into another room,
and opened her condition, which was remarkable;
and said she never had felt so comfortable before in
the company of any people as this morning with Friends.
Attended the select meeting for this place, and I was brought into a state of trembling,
soon after sitting down,--remembering the language of the Master, where he said,
'`With desire I have desired to eat this passover with you;
one of you has lifted up the heel against me,`' etc., and had to express it with more:
and now I saw measurably into my exercise when standing at the grave of an individual,
whose funeral I attended a few days ago, and which continued upon me for some time after.
We could not get forward,
and so adjourned the meeting that more might be together next time.

"`13th.--To meeting, which was large, and a very open, precious time.
Sat with the members of the select meeting,
and before they got through the business I requested leave to withdraw;
this was a time to be remembered,--close and searching.
Feel much relief of mind, for which I know I ought to be, and hope I am,
thankful to the Father of living mercies, and willing to move on to the next work,
which may in wisdom be opened.

"`14th.--Had a solemn time in prayer with a number of Friends,
among whom were several tender minds; and it was a time to be remembered.
A young man who is under convincement came in, with whom I had a tendering time alone.
Parted sweetly from my friends at Bristol, and journeyed on to Bath, where we dined,
and reached Melkshara, twenty-four miles.`"

"`16th.--Got to Hungerford, and 17th to Reading;
where he tarried a few days to rest and wait for the holding of the quarterly meeting.

"`20th.--To the quarterly meeting;
and soon after sitting down my mind was brought under exercise,
and it proved a tendering time, but not a long meeting.
In that for business, I was favoured in testimony to the humbling of several present,
which was acknowledged to; and although things are low,
yet there seemed some ground gained against opposers.`"

[.offset]
The next day they got to Uxbridge, and on the 22nd to London.
In a letter to Rebecca Jones, written from London, he says:

[.embedded-content-document.letter]
--

It was pleasant to find you had got through your arduous task,
and to hear from others that you are cheerful.
You remain as a seal upon my spirit,
as one whom the Father of mercies was pleased to baptize in an eminent degree,
into a sense of my state before leaving home,--
`'By one spirit you are all baptized into one body,
and made to drink into one spirit;`'
and O that I may be accounted worthy to experience this baptism while in this land,
and to the end of my pilgrimage.

The love which flows in my heart reaches forth towards all the children and
servants of our heavenly Father`'s family in my native land,
as well as here.
There is a precious remnant preserved here, among all classes,
and great has been the love I have felt to the youth in this city,
both in meetings and in families.
If I may speak as an instrument employed in the Lord`'s work, I would add,
that there is a precious visitation extended to this class.
O the tenderness and gravity I have seen in some who are very young in years; so much so,
that I have been ready to say in the secret of my heart,
surely the Lord has begun a work in the minds of the children by the power of his love,
which will in time spread to the astonishment, as well as the comfort, of many.
Indeed, at times, I have almost been induced, in the opening which has presented,
to lay my hand upon the heads of some,
and tell them what good things are in store for them.
On the other hand, I have found your sisterly advice good,
not to be afraid of the rich and great.
Dear Rebecca, if my knees have not smitten together, they have at least trembled,
and Habakkuk`'s experience been mine, in degree,
when in the families of the great and towering ones,
desiring that they might find a resting place in the day of trouble,
which may be nearer at hand than many careless sons and daughters are aware of.
I magnify not the officer, but the office, and that adorable Hand,
who commissions and sends forth his servants; yes, I bless his name,
in that he is raising up labourers, one here and another there, in this land,
who appear hopeful.

--

"`27th, third-day.--To London quarterly meeting, which was large,
many of the youth being present: dear S. H. opened a door for me,
and I had an enlarged time of encouragement to all, but especially to the youth;
and I sat through the rest of the meeting for business,
with greater sweetness and composure of mind than I have experienced of late;
I also rejoiced with much joy,
to behold that weight had increased in this quarterly
meeting,--the business was conducted comfortably.

"`Tenth month 5th.--This morning feel more serenity and
calmness of mind than I have experienced for a length of time;
and now while making this note,
am anxiously desirous to cast away that labour and toil which have made my way,
at seasons, uncomfortable.
O that my heart may be lifted up to God in faith;
and in all things be given up to his blessed will,
that so I may be favoured from season to season, not only to know it, but also to do it.
Attended Grace-church street meeting; and it was an awful time, at least to me,
from these words; '`As I live, says the Lord, every knee shall bow to me,
and every tongue shall confess to God.`'

"`6th.--To the monthly meeting at Tottenham,
before which Susanna Horne spread her prospect of visiting the
families within Horsleydown monthly meeting,
and a minute was made setting her at liberty.

"`10th.--Wait on your God, O my soul, for the further unfoldings of his will;
who can turn his dispensations, as a man turns his water courses in his field;
and remember, that if the Lord`'s will is done, it is your sanctification and redemption,
under all trouble, whether outward or hidden.

"`11th.--To Horsleydown monthly meeting,
where I opened my concern to visit their families,
to the men and women before they separated;
my friend Susanna Horne following in the same manner; both were minuted,
and Benjamin Simkins appointed to accompany me, and Mary Smith, Anna Kay,
and Elizabeth Hobson, to accompany my female friend.
Dear Richard Chester came to this meeting, and expressed his sympathy.
In the first meeting I ventured to prostrate myself in supplication.

"`12th.--Very deep were my struggles and conflicts this morning: however,
they in some degree passed over before noon; about which time,
I took a walk to Thomas Phillips`' and dined,
and had a tendering opportunity with the family; in my walk back, which was a lonely one,
my heart was tendered and broken,
and a language of sweet encouragement sprang up before I reached home.
But ah! how often do such sensations get dissipated.
Spent the evening, however,
more free from that weight of distress which has long been my humbling companion.

"`16th, first-day.--Felt my mind turned to sit with Friends at Horsleydown;
and it was a pretty comfortable time:
in the close mentioned a desire to see their neighbours together in the afternoon.
Many came, and I sat most of the time in silence, until several left the meeting;
but near the close I had to tell them how it was with me.
O that there was more of a true hungering and thirsting
after righteousness among the people in this city.
How little is done when the people`'s minds are turned outward.
In the evening the committee to arrange the families, met with us.`"

[.offset]
On the next day they commenced the family visit,
and although he had to labour along under much exercise, among many that he visited,
yet he, as well as his beloved friend,
were favoured to hold forth the language of reproof, encouragement, and instruction,
in the demonstration of the spirit, and with power.
From this period until the 8th of the following month,
he continued without much intermission, engaged in this service;
when they concluded to break off for two days and go to Tottenham.

"`Eleventh month 9th.--This afternoon I am tried with the prospect of more work,
in company with Susanna Horne,
our prospects being the same respecting visiting the families of Friends at Ratcliff,
and she is now returning home to attend the monthly meeting,
to open her concern and obtain further liberty and enlargement.

"`10th.--Went to Waltham very low in mind; indeed,
it seemed as if I could hold out little or no encouragement to my friend; she, however,
spread her prospect solidly before her friends, and it was united with.
This evening deep thoughtfulness attends me;
O that these fears and cares may prove my preservation,
by having a tendency to direct the mind to the only Helper.`"

[.offset]
The next day they resumed their labours within
the compass of Horsleydown monthly meeting,
which they finished on the 19th.

"`22nd.--To Horsleydown week-day meeting,
notice having been given on first-day for all the members to attend,
as well as such as are looking towards our Society: it was a very full meeting,
and I trust a solid one,
affording an opportunity to both of us fully to relieve our minds,
and it ended sweetly and comfortably.
Dined at Anna Kay`'s, the kind Friend who accompanied us, with Benjamin Simkins,
Hagger Allen, and various others; after which, I had a solid religious opportunity,
wherein these expressions impressed my mind; '`My peace I leave with you,`' etc.;
and in my quiet sitting I remembered the last of the same chapter,
as I found afterwards on looking for it,
which seemed to me applicable to this finishing stroke, '`Arise, let us go hence.`'

"`24th.--Attended Ratcliff meeting,
and after sitting most of the time under close exercise of mind,
I was favoured in looking over my stoppings of late, with a pretty composed mind,
and ventured to bend the knee in prayer for preservation; and after it,
there being a comfortable quiet over the meeting,
I opened my prospect before the men and women, of going from house to house among them;
and when the men met in their apartment they took it up,
and after expressions of unity and sympathy with me, it was minuted;
at which time my friend Susanna Horne came in and opened her prospect,
in a feeling manner, which was united with, and minuted also.
After meeting met the committee appointed to make arrangements for us.`"

On the 25th they commenced visiting within the limits of this meeting; on the 27th,
first-day, were at the morning and afternoon meeting, both of which were large,
and he remarks, "`I humbly hope were to profit,
although singular things escaped my lips in the last;
with a prospect that a day of distress is coming on the false teachers in the land,
and that the Lord will redeem his sheep out of their hands.
On the 29th, were with J. C.`'s family, whom I visited sometime ago,
in company with Simon Bayley; it was then a singular time, and now also,
a tendering opportunity.
This has been a memorable day, and the opportunity at the widow P.`'s,
like a seal that we have been rightly directed in labour together.
On the 1st of twelfth month, being fifth-day, attended Ratcliff meeting,
which was truly a remarkable time.

"`Twelfth month 4th, first-day.--To Ratcliff meeting, which was pretty large;
a number of neighbours coming in, and it was an open time.
In the afternoon the house was also filled up, in part, with strangers,
and I had a very relieving time.
A person who has taken down several testimonies in short hand, came here for the purpose,
but was persuaded to desist.

"`6th.--To the meetinghouse at ten o`'clock,
and met a number of persons mostly of our Society; and although,
when I arose this morning, and also in the forepart of this sitting, I was low in mind,
yet we had a satisfactory time.

"`7th.--This morning our kind host J. H., took us to Tottenham,
where we attended the select meeting;
in which Susanna Horne mentioned her prospect of accompanying
me into the families of Peel and Westminster monthly meetings,
and they set her at liberty to open it in the monthly meeting tomorrow.

"`8th.--My mind was humbled, and I ventured to bend the knee in prayer.
Susanna Horne came into the men`'s meeting, accompanied by her mother and Mary Smith;
and in a tender feeling manner opened her concern, which was united with,
and my mind is much relieved.

"`10th.--Spent most of this morning in getting ready to leave town,
and after dinner set off with George and Mary Stacey, in a post chaise for Uxbridge;
the chaise broke down with us by the way, which did not detain us long,
and about four o`'clock we arrived at our friend Thomas Hull`'s, and met a kind reception.

"`11th, first-day.--Passed the meeting through in silence and much exercise.

"`12th.--O for more purity of heart in God`'s sight; that I may see my way,
and be favoured with armour to resist the wicked one.
Surely he has power to sift me as he did Peter.
O Lord forgive, empty me, and wash and sanctify me for your work.

"`13th.--Awoke in distress; but since breakfast, I feel a little more easy.
O that condescending love may vouchsafe to wash my feet,
and shoe me again with the preparation of the gospel for his work and service;
and if I am not abased enough, make me so.
I dread, I fear, knowing the slippery places there are to walk through:
'`cleanse me from secret faults, let them not have dominion over me.`'`"

[.offset]
The following is taken from a letter addressed
to him by his beloved friend Rebecca Jones,
dated,

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, tenth month 26th, 1796.

[.salutation]
Dear Thomas,

Your few lines of the seventh month, dictated in brotherly regard and sympathy,
came duly to hand, and like your personal visits formerly,
had a consoling effect,--my mind being often low and depressed,
yet not without a degree of humble trust in the goodness and mercy of an Almighty helper,
who has done great things for me--holy and reverend is his name, says my soul.
I rejoice in believing that the same good hand is with you,
and will be with you during your arduous journey; and when it is accomplished,
if I am in the body,
I shall be truly glad in your return to your dear family and native country,
with sheaves of enriching peace.
This will also, I trust, be granted to all my fellow-labourers from America,
now in Europe, some of whom I hear are doing valiantly.
You were all brought livingly into my view about two weeks ago,
under the influence of the spirit of supplication in our North meeting;
when a living hope was raised, that the Shepherd of Israel, who put forth,
will go before, and as he is listened to and faithfully followed, will give eternal life,
and none shall be able to pluck out of his holy hand.

--

"`15th.--In a poor and stripped condition I went to the week-day meeting in this place;
not knowing but that I should pass it in silent sorrow and mourning,
and so through the remainder of the day.
My spirit was bowed in secret humble supplication during most of the meeting,
and frequently thought I would have to go down on my knees, but the exercise lessened,
and such a sweet calm covered me towards the last,
accompanied with a humble hope that mercy was extended to me,
that my soul was thankful for this ray of light and love once more vouchsafed,
and withal felt a gentle pressure to stand up with a few lively expressions,
which I delivered, respecting silent worship and sympathy one with another under it.
After I sat down my companion Mary Stacey appeared in supplication,
and the meeting closed comfortably, I trust to more than myself.`"

[.offset]
From Uxbridge he went to Staines, to attend the monthly meeting;
and while there he wrote a letter, from which the following is extracted;

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Staines, Twelfth month 16th, 1796.

Although I parted from you and left your father`'s comfortable habitation,
with seeming cheerfulness, yet,
I seem as if I can hardly forbear describing in
some degree the state I have been in since.
I thought I had seen an opening to leave London and spend some time at Uxbridge, Staines,
etc. and so pushed off in a very stripped condition indeed;
George Stacey and dear Mary accompanied me to Uxbridge.
But such a day as last first-day was, I have not often experienced; no,
I know not that at any time in this land, I have had a greater plunge.
I have not language, at present to set forth, and indeed,
it would not be profitable to endeavour to express,
the deep wading of my poor oppressed soul;
and in this scene I have passed through I even feared I
had not helped you forward in all respects,
on your journey, so you may see what a poor prop I am;
lean not to it any further than your Master gives liberty.
I had not the least opening,
either in the meeting or in any family--we came to this place to monthly meeting,
and here I was also emptied.

--

"`18th, first-day.--To the morning and afternoon meeting at Uxbridge,
which were seasons of close thoughtfulness.
I had a small communication near the close of the first, and was shut up in the last.
Drank tea at Thomas Finch`'s, and then stepped in to see Thomas Ashby`'s weakly wife,
and here I had to remember freshly,
my own tried state when in the chamber of a declining precious companion,
and the evidence I was favoured with in that day of her
being accepted of her God--and also had to mention it.

"`19th.--Spent this morning pretty much in reading,
and at three o`'clock Mary Stacey and I set off in the coach,
and got to their house in Westminster about seven o`'clock.

"`21st.--To Peel monthly meeting, in which I was silently shut up:
opened a prospect of visiting them in their families,
and my friend Susanna Horne also came into the men`'s
meeting and laid a like concern before them:
both were united with and minuted, and John Bevans appointed to accompany me:
but a low dull time to me.

"`22nd.--A very conflicting night, wherein jealousy, doubts and fears were my companions.
I have thought of late,
that I should be most miserable indeed if left to myself and forsaken
of my God,--if the potter should lay aside the lump of clay.
O for more watchfulness, reverence and becoming fear.
Will it not be better to lay down my life than live to dishonour that
truth which I have been favoured at seasons to espouse and plead for?
O the deceitfulness of the heart of man.
Lord have mercy, and help me through all that is yet to be endured.
That which I see not, teach me; and if I have done iniquity,
strength is only with you to preserve from doing more.
I hope my soul is humbled this morning.
To meeting and was favoured to get into a quiet and resigned state,
which indeed is a mercy.

"`24th.--This morning came Mary Stacey and her daughter Mary Ann,
who has been low in mind, and some communication arose freshly in my heart towards her,
in an encouraging line, and it had a tendency a little to raise my spirits;
for I have indeed felt, and may I not say been, an unworthy creature.
O how sweet is a little portion of heavenly bread.

"`25th, first-day.
It has been a very cold snowy time of late,
the thermometer this morning down to three degrees.
Thanks to the Father and fountain of mercy,
my mind feels more cheered and comforted than for a long time.
O that it may be a day of renewal of my espousals,
and may it please my good Master to strengthen me for further labour, if it be his will,
that so my task in this land may be accomplished to my own peace.
Why am I so much shut up?
Are there not some active minds that may be profited by me as a sign to look at?
Attended morning and afternoon meeting, and in the first felt enlargement in testimony,
and in the afternoon was quiet and comfortable.

"`26th.--To the select quarterly meeting,
and next day to the quarterly meeting for business,
and was once more favoured with an open time in the meeting for worship,
and found an opportunity to relieve my mind; also in the meeting for business,
respecting tithes, etc.
Dined at home, and after it had an open opportunity with a number of Friends,
among whom was P. B., a dear young woman in a tender state of mind.
Went to the adjournment, and here again relieved my mind.

"`28th.--To Peel meeting, in a low condition, accompanied by Rachel Smith,
where I met my beloved friend and fellow helper Susanna Horne.
I was somewhat relieved by prostration in prayer: dined at John Bevans`',
at whose house we have taken up our quarters;
and in the afternoon began the family visit, accompanied by John Bevans and Mary Stacey.

"`30th.--Had an open time in the meeting at Clerkenwell school, both among those met,
and with the scholars: dined at the school,
and after it had a precious opportunity with the family, tutors and servants,
without the children; after which visited the old people, both men and women,
in the other house; and had a pretty satisfactory time;
and finding my companion`'s mind was not clear respecting the children,
we collected them together and had a good time;
and although one or two families were laid out,
I felt so spent that I was most easy to wind up for the evening,
and I hope the day`'s work will prove encouraging to them and us.

"`First month 1st, 1797, first-day: opens another year,
and very likely further trials may come upon me.
Went to meeting, and was shut up in silence.
Near the close of the afternoon meeting very close things escaped my lips,
and such was the weight and concern that rested on me after returning home,
that I could say but little, nor be cheerful in the midst of a large company;
and at six o`'clock felt most easy to visit a family that was laid out for us,
which was a memorable time.

"`3rd.--After dinner set off in a post chaise to Uxbridge,
with a view of attending the burial of Thomas Ashby`'s wife, at Staines,
on fifth-day next: arrived at Samuel Hull`'s before night,
and felt a liberty to encourage Friends to invite their neighbours.
Spent the evening at Thomas Hull`'s, pretty calm and resigned, except one little miss,
for which I was humbled after lying down.
O how watchful a minister, a pastor, should be in all his conduct.

"`4th.--To meeting, at which a considerable number were collected: E. Bevington,
who is out on a visit to the meetings in Middlesex, was there and appeared;
but my mind was closed up again in silent conflict.
O what shall be done for the people in this land in places,
and when will the book of prophecy be opened, and their hearts also.
After dinner took post chaise and went to Staines.

"`5th.--To meeting, where the body was brought, and it was a crowded meeting,
but a very low time to me; I laboured in weakness, but to little relief:
doubting and fears very much prevailed in my mind, whether I was in my place.
After dinner we had a sitting with a large company,
wherein my companion appeared in prayer, and E. Bevington in testimony;
but I felt like a book sealed in this opportunity,
but some time after the company being more thinned,
my mind was suddenly brought under exercise, and I felt some ease by expression,
and again after tea, felt some enlargement in testimony.

"`6th.--Returned to Westminster.

"`8th, first-day.--Felt poor, and went so to Peel meeting and sat it through in silence.
In the afternoon meeting was also shut up in silence, viewing my steps,
when a total stop appeared necessary;
and my mind turned toward the monthly meeting at Westminster next fifth-day,
and see if way will open to make a beginning in that quarter.
From the first, both that meeting and this, seemed pretty much as one,
so far as regarded my concern; so I felt a liberty to tell my companions my thoughts,
and also the committee in waiting to lay out more families,
that the cloud rested on the tabernacle and it was safest to stand still.
Struggled along through the evening nearly as well as I knew how.
This evening a portion of Scripture was read, which is a practice I unite with.

"`9th, second-day.--To morning meeting, and sat it pretty quietly:
went afterwards with my companion and paid a sweet visit to S. R.,
her sister Sarah and sister-in-law.
After it, stopped a little while with two goodly servant maids,
and my mind has not been so refreshed for some time past, as it was under this roof.
Spent the afternoon and evening more free from depression, and before going to bed,
after the eldest daughter had read a chapter in the bible, we had a sitting,
in which we were both favoured to hand out suitable counsel.

"`10th, third-day.--Some little opening on my bed, into a further dispensation,
I hope of more light and liberty: but stop--why such anxiety?
Are not these dark and cloudy seasons profitable?
And can you not keep the faith, and also the patience, O my tossed soul?
O that this may be mercifully granted to poor unworthy me,
has been the language of my heart this morning; and may I be favoured,
to persevere through all; and may the Lord, in the riches of his love,
be pleased to grant me the blessing of preservation,
that I faint not;--then I know that all trials will work together for good in the end.
Here we are standing, I hope as servants in waiting; no way opening into any family,
and I am comforted in the remembrance of these expressions;
'`Let your conduct be without covetousness,
and be content with such things as you have;`' for he has said,
'`I will never leave you nor forsake you;`' so that we may boldly say,
the Lord is my helper, and I will not fear what man shall do unto me.

"`12th.--To Westminster monthly meeting, where we found William Rickman:
H+++.+++ F. appeared in a few words in supplication,
and my companion Susanna Horne immediately after her--
and then I had an open good time in testimony.
We laid our prospect of visiting them in their families, together with Mary Stacey,
before the meeting, which was united with,
and Josiah Messer and Lydia Forster named to accompany us.
Found letters from my dear Sarah and others,
and my spirit is bowed and humbled on looking towards home, and begs for faith,
patience and preservation.
O my dear wife,
how has the prayer of my heart gone forth to the Father
and fountain of all our mercies on your account,
that he may be your husband, your preserver, and your redeemer.
This day commenced visiting families.

"`15th, first-day.--To Westminster meeting,
and was favoured with an open time of enlargement in testimony,
much to the relief of my own mind.
Dined at George Stacey`'s, and accompanied by him, with my companion Susanna Horne,
went to the Park meeting, where the body of Francis Merrick was brought;
a Friend whom we visited in the course of our engagement in that meeting.
This was a remarkable meeting to me,
having to reason with the auditory concerning righteousness, temperance,
and judgment to come;--my mind was brought low and humbled after it.

"`22nd, first-day.--Went to Westminster meeting under feelings of poverty;
and to my admiration was strengthened to labour, both morning and afternoon,
largely and relievingly, and afterwards in an opportunity with F. S.`'s large family,
where we had a precious time, so that I thought after getting home,
it was little short of a miracle of mercy extended to me this day.
Laid down peaceful and quiet, and thought I might soon retire into a comfortable sleep;
but in a little time it departed from me.
Thoughts of a humbling and trying nature were my companions,
but trust my will was reduced and resigned to the will
of Him who commissioned me to come into this land;
and has strengthened me to labour from time to time in it.
O the close and trying prospects that open, and yet I have no reason to murmur or repine;
for if the Lord my heavenly master does but go with me in them, I hope all will be well.

"`Second month,
2nd.--A degree of comfort on waking this morning in looking forward to future service,
with respect to which, I have of late been much blinded.
A little reviving hope, however, has sprung up, that way will be made, and the prayer,
I trust the upright prayer, of my heart has been for the blessing of preservation.
I covet not riches, or honour, or applause,
but the guidance of the good Spirit until the end come.
As some of our friends had been talking of attending Ratcliff week-day meeting,
I felt an openness in my mind to go and sit with them:
proceeding in the family visit in this place seems sealed up as yet.
I went accordingly to meeting,
and had a language of encouragement to hold out to those who are mourners like myself.`"

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Charter-house Square, Second month 5th, 1797.

[.salutation]
Dear friend,

Your acceptable letter, enclosing one from Samuel Couch, came to hand a few days ago,
and although long on the way, was yet seasonable, though indeed when I read it,
I seemed hardly to have a capacity afforded fully to understand it.
My experience in this land has often been, and continues to be,
that of being stripped and baptized;
and yet I hope there remain so much honesty and
uprightness in my poor and often wading mind,
that I dare not disbelieve, that although the Lord may be pleased,
for wise purposes sometimes unknown, but to be waited on to see the end,
to feed his messengers with the bread of adversity,
and give them the waters of affliction to drink, yet as says the prophet,
'`your eye shall see your teacher.`'
O blessed teaching has this been to me in days past, and surely I could not have done,
and cannot do yet, without it.
You have a little encouraged me by this language: '`Shall the exercised servants,
who are baptized into the state and condition of the people, conclude it is of no avail?
Necessary is it to guard against the grand discourager of all good,
and his subtle reasonings: the work that he would mar is often in as prosperous a way,
when hidden from our eye; so that there is encouragement to endeavour,
in simplicity and godly sincerity, to break up the fallow ground,
leaving the increase thereof to the great and good Husbandman.
From the faithful labourer sheaves of peace will not be withheld.`'
Well, my beloved sympathizing friend, in reading these lines over,
and now again on penning them, I am willing to say.

Go on, O my soul, to the end of your journey here, and beg assistance to endure,
through all states what your wise and gracious Master may appoint.
Ah! here`'s the thing;
when I am favoured to see that my various baptisms are of his appointment,
then I do know that his will ever proved my sanctification.
But again, what is to be done when we are shut up in a close prison house,
and can hardly see any light through the grates?
I write to one who knows that his brethren in the ministry go
down in this day into the prison house,--surely then,
'`the captive exile hastens, that he may be loosed, and that he should not die in the pit,
nor that his bread should fail.`'
No mortal, dear Henry,
knows what I have passed through since putting my feet on the British shore; yes,
in my going off from home, and in the passage over the waters;
the thought of it at times humbles my mind.
I suppose I should not have written after this manner to you at some other times,
but am apt to do it as I feel.

I have gone through most or all of the families of Friends in this city,
except in one monthly meeting.
The wind has taken me ahead and I cannot move,
and am patiently (at least I hope so,) waiting for it to come fair for a movement.
What in the ordering of divine Providence may be my lot,
when this arduous business is got through with, is at present pretty much hid;
though I have not been without glimmerings in more favoured seasons:
did I say favoured--are they not all so?
O yes.

--

"`5th, first-day.--I went to meeting poor, but was favoured with a relieving time,
though very closely exercised with regard to various states.
In the afternoon meeting I was also much enlarged to the seekers present.
In the evening had several precious religious opportunities.
Heard after morning meeting, that dear old John Hill died this day.
Precious soul, may mine inherit the same as yours,
when divine Goodness may be pleased to end my day.
I loved you much in this world of trials and conflicts.

"`6th.--Began our family visit again, and on the 20th finished this service.`"

[.offset]
Having taken a very heavy cold a short time before they finished the visit,
he was confined to the house for several days from the effects of it;
on the 13th of the third month, in writing to his son, he says;

[.embedded-content-document.letter]
--

I do not remember to have had a heavier cold, or more pain in my head and face,
since I have been in England.
I was very carefully nursed at my friend John Bevans`', Charter-house square, London;
not only by his wife and daughters, but my valued companion,
who though we had gone through our visit to that meeting, was not easy to leave me;
and when I was able to go out,
her mother and sister came for me and brought me to their
quiet and hospitable habitation in White Heart Lane,
Tottenham; where I have been mostly since.
I account it a favour that I am here in a state of retirement:
I have got so used to this kind family, and they to me, my strippings and baptisms,
that when I am here I feel under no bonds.
To give a little idea of my present state,
I have compared myself to a vessel that has been tossed in a voyage at sea,
and is unloaded, and repairs found necessary to be done, even to the keel;
and if I am again counted worthy to be equipped and sent off on another embassy,
it will be of the Lord`'s mercy.
I might enlarge on the subject, but am willing to leave it now,
and when further openings of duty present, I hope with cheerfulness to be enabled to say.
Here am I, send me.

--

[.offset]
In reference to his outward affairs, of which his son had the management, he says;

[.embedded-content-document.letter]
--

Dear David Sands told me once in New England, that what we do not gain in pence,
we may gain in experience.
May it be so with you, and may you be favoured to get on irreproachably.
It is a notable saying of the apostle, that '`They that will be rich,
fall into various temptations and a snare,`' etc.: and I fear, now while writing,
that some of the young merchants among you,
who dare venture to trade above what they have of their own, and to a large amount too,
will be left to smart deeply when it may be too late.
O how sweet is a little of one`'s own, with content.
I never coveted to be rich and great in this world, neither do I covet it for you,
my son; and I comfortingly hope you believe me,
and are measurably convinced in yourself of that way in which you should go.
May the Lord, my blessed helper, strengthen, stablish,
and more and more settle you on the living foundation, to my rejoicing,
and to the rejoicing of his church and people.

--

[.offset]
In a letter of the same date, addressed to his much loved friend Rebecca Jones, he says:

[.embedded-content-document.letter]
--

"`Your acceptable letter came to hand the 13th of the first month,
just as I was entering into a family visit within Westminster quarter,
accompanied by Mary Stacey and Susanna Horne; since which,
I have gone through those of the Peel, which finishes the families of London,
making between five and six hundred sittings; and now after this arduous labour,
I feel myself a poor unprofitable servant.
Frequently have I remembered your counsel, not to be afraid of the rich and great;
and I trust, through marvellous condescending help, this has been my experience;
and very close things have escaped my lips, sometimes to my own astonishment,
and I suppose to that of others; and I have thought, that for some of those things,
Satan, the adversary, has envied my poor, wading soul, and by various stratagems,
siftings and buffetings,
(for indeed he has been permitted to be a sore thorn in my
flesh,) has endeavoured to draw me down to destruction.
O, my dear sister, I cannot describe on paper, where I have been in this respect.
I have been examining and reexamining, and though weakness and infirmity are mine,
yet I trust I can say, I have not wickedly departed from the law and the testimony;
and have been led to beg that every corner of my deceitful heart might be searched.

Well, it has been so, and a degree of sweetness springs out of these bitters.
Have you experienced such a state as this, when abroad in this land,
when all seemed gone, and you could lay hold on nothing?
When heaven and earth were wrapped up as a scroll,
and you had again to wait for the creation of a new heaven!
O the unsearchable wisdom of the Lord, whose ways are past finding out.
If this has been your experience at any time, and surely I think it has,
then can you sympathize with me:
and O that you may be favoured still to pray to the Helper of Israel,
that the feet of your poor feeble friend and brother may not slide.

I do not write murmuringly, but I hope with a mind so far devoted,
that when I can be favoured to hear the language,
'`whom shall we send, and who will go for us?`'
I can say,
'`Here am I Lord, send me.`'
O may my soul be preserved here, until the latest period of my life;
ever sensible that they who run, and the Lord sends not, cannot profit the great cause.
I have frequently visited dear Thomas Phillips in his illness,
who departed this morning about four o`'clock.
He has been a deeply sympathizing elder to me;
and among other precious things he dropped,
said that he hoped the Lord would carry me through all my trials in this land;
and I think it was yesterday, after I left him, he had me called back, and said,
'`Give my love to Friends in America; though I do not personally know them,
I sympathize with them in their late troubles.`'
Some days before, while sitting by him, he said with tenderness,
'`It is a low time among us: things are trying,
but there is a better day ahead for the young people.
What a comfortable thing to die in this faith--I
have loved the truth and good Friends,`' etc.

Tell my dear absent family, that my prayers have been, at seasons, put up for them,
when so favoured, that that blessing which makes truly rich,
and which must be left to an all-wise Providence to dispense, when and how he pleases,
may be their happy experience.

--

"`Third month 31st.--Attended the burial of Thomas Hull, at Uxbridge:
we had a very crowded meeting, and in it I felt some enlargement to speak to the people.
Sarah Harrison was here also, and appeared after me.
Dined at the house of the deceased, and afterwards my companion and Mary Stacey, and I,
had an opportunity of relieving our minds among the relations.
I have not been opened in any public meeting or opportunity, except a few words,
since the 20th of last month, which closed our family visit.

"`Fourth month 1st.--Returned to London after an early dinner, and got there in good time.

"`2nd, first-day.--Went to Grace-church street meeting,
and O what a close time it was in pleading with the loose professors;
among other things that arose in my mind, was this, to advise them to read,
and let their children read also, that excellent epistle of Stephen Crisp`'s,
respecting the present and succeeding times, and also the trembling prophet Habakkuk;
and I felt some ease and relief.
Went to meeting in the afternoon, I trust, with a dedicated heart;
and though there appeared to be many strangers there, all was sealed up.
I could do nothing; but stopped after meeting and encouraged one of this number,
who kept his seat, and told me he was expecting something.
I commended him to the grace of God for his teacher.

"`Fifth month 3rd.--Spent the time between the
3rd of fourth month and this period at London,
Newington, etc., in a low, exercised state; and it is this day five months,
if I remember right, since the date of the last letter from my wife;
of whom I have thought with much anxiety and solicitude:
it is not unlikely that my letters may have miscarried,
as we learn the American vessels of late are taken.
This morning felt my spirit much oppressed; took a lonely, solitary walk into the fields,
and there poured out my sighs and tears to the Father and Fountain of my mercies;
I remembered his gracious dealings with me when
in the wilderness of Carolina and Georgia,
and how often, when riding in lonely places on the road, London was set before me,
and that I was to hasten to prepare for the voyage to this place.
But O, the strippings of favour I have experienced since being in this land!
The buffetings of Satan; the thorn in the flesh--the fears,
lest I have slipped in some degree; yes, that I have not at all times stepped aright.
My soul was poured out in prayer for mercy and forgiveness,
and for patience to endure the singular trials I have to encounter,
and was favoured with a secret, soul-sustaining hope, that although I have long had,
and it may yet be continued, to walk through the valley and shadow of death,
that my most merciful Lord will give me to experience a
table spread in the presence of my enemies;
and that the bitter cup will be sweetened,
so far as to enable me yet to drink thereof to some profit.
I humbly hope I can make this appeal unto him;
'`You know I neither seek nor desire either outward or inward great riches,
but of your appointment, and to be led in a plain path, because of my enemies;
therefore, O Lord, sanctify the present dispensation, and forgive all my secret faults.

"`Sixth month 9th.--No settled and fixed prospect since
finishing the family visit in Peel monthly meeting,
which is now between three and four months; and since yearly meeting was over,
my mind has been very deeply exercised and tried.
Some little opening towards a movement has presented, but it lasted not long,
and has closed up, and now my condition, in a state of blindness,
is very trying to the man`'s part.
Sometimes for a little moment there has been such resignation,
faith and patience experienced, as have hushed all; and again,
when I consider the distance I am from my home, and how long I have been away,
and no clear opening to move out of the neighbourhood
of London,--fears and doubtings arising,
as to what man may think or say of me.
I have slidden into a low spot.
O that I was more steady, and bore up under all my weights more uprightly!
O my soul, banish as much as possible a murmuring spirit.

"`11th, first-day.--Arose in a low state this morning:
David Sands set off soon after breakfast, accompanied by Joseph Smith,
to Wandsworth meeting, and requested I would come to him in the afternoon,
he having some thoughts of a public meeting in that neighbourhood.
After he was gone I took courage and went to Ratcliff, accompanied by Thomas Richardson,
and through the renewed extension of divine love, had an open, comfortable time:
some strangers came in, and one man appeared much affected.
About three o`'clock Truman Harford and I started for Wandsworth,
and found a meeting appointed at five o`'clock; it was pretty largely attended,
and I was silent.

"`12th.--T. H. took me to London in his chaise, to attend the select meeting,
where William Savery mentioned his distress at
finding one of his testimonies was published,
by a man,
who for sometime has been employed in taking
down what has been delivered in our meetings,
which does not meet with our approbation.`"

[.offset]
The following extract is from a letter to him, dated, Uxbridge, sixth month 10th, 1797,
written by Ann Crowley:

[.embedded-content-document.letter]
--

I trust my beloved friend will excuse me for troubling him with a few lines,
which I believe I should not have done,
but from an apprehension that liberty is felt to
communicate a little of my tried situation,
to one who often travels in the deeps,
and is thereby qualified to administer a word of
counsel to those who may have had less experience.
Such has been the stripped state of my mind for a long season,
that I have often been tempted to let go my confidence,
and conclude it was impossible to hold on my way,
and that I must inevitably fall by the hand of my enemy.
At other times, am ready to think that I have been under a delusion,
and have not yet distinguished the voice of the true Shepherd; and thus,
as well as with various other discouraging circumstances, has my faith been tried,
until it is reduced to a very low ebb.
The language formerly expressed by one, who no doubt felt his lonely situation,
often seems applicable to me,
'`I am like a pelican of the wilderness--I am like an owl of the desert; I watch,
and am as a sparrow alone upon the house top.`'
None seems to fathom the exercise of my tribulated soul,
nor knows the bitterness of my heart:
yet it is possible this may all be ordered in best wisdom,
and sometimes I am ready to hope it is; for if these trials are rightly abode under,
I have little doubt but they will tend to drive
the soul home to that safe place of shelter,
which I believe has been found by many to be a secure hiding place,
even from the greatest storms.
Here our dependence becomes more solidly fixed on that all-sufficient Arm of help,
which is able to support in the needful time; when, perhaps,
if greater opportunity was afforded, I might be induced, from a hope of getting relief,
improperly to disclose the painful situation of my mind, and seek for inferior help,
when nothing short of that divine consolation,
which comes from the Fountain of inexhaustible good, immediately handed to my soul,
might be permitted to prove sufficient to revive the mind in hope.
Thus I am enabled, at seasons, to endeavour to reconcile my mind to my tried allotment.
I sincerely wish, my dear friend,
to be preserved from saying anything which may increase my own poverty,
or give uneasiness to your feeling mind, and if I have done so,
I am quite willing to stand reproved, and desire your entire freedom herein.

I frequently wished, during my late stay in London,
to spend a little time in your instructive company;
but feeling myself unworthy of the conversation and society of
those whom I so greatly preferred in the truth,
to myself, I had not courage to seek it, but retired much alone,
bemoaning my own weakness and poverty, concluding that none knew how it fared with me.
When I heard some of my beloved friends expressing the overshadowing of
divine good which was so largely to be felt in some of our gatherings,
and the sense of gratitude which dwelt on their minds for such favours,
my soul was introduced into a state of lamentation,
fearing that my heart was become obdurate,
because I could not sensibly partake of that
heavenly enjoyment and soul-sustaining virtue,
which many others appeared to share, and whereby the soul is kept alive unto God.
But through all, I am ready, at seasons, to lay hold on the hope,
that a state of poverty and desertion is seen to be most profitable for me,
and that these proving seasons are not always intended as a rod of chastisement.
I think I can, at times, feelingly breathe this language; '`Search me, O Lord,
and try me and know my way,
and if there be anything in me which prevents
your great work from going forward in my heart,
do away with it: let not thy hand spare, nor your eye pity,
until you have made me what you would have me to be.`'

It is not my intention, by thus addressing my endeared friend,
to be pouring out the language of complaint,
for I am truly sensible that I have been made partaker
of many more favours than my little dedication merits;
but being fully convinced that you are one of
those who have passed through many tribulations,
and whose baptisms have been of a fiery nature,
I thought I felt something more than a bare liberty to
unbosom a little to you the tried state of my mind,
believing that deep can utter unto deep, and that it is those only,
who have trodden the same suffering path,
who can availingly sympathize with minds buried in suffering and death.

It may seem presuming in me, whose experience in divine mysteries is so small, to say,
that my beloved friend has often been brought near in sympathetic remembrance,
and according to my small measure I have felt strong desires that you
may experience a daily increase of that faith and patience,
which enabled many of our ancient worthies to bear the burden in the heat of the day.
When favoured to look a little beyond the present day of suffering,
and call to mind that at the end of the race,
a crown immortal is given to all the faithful dedicated servants in the Father`'s family,
it animates us to press through the many crowds of difficulties which arise in the way.

--

"`20th.--David Sands and I had some instructive
conversation together respecting several matters,
and hope I have gained something by it.
Returned to my chamber from a secret impression on my mind,
in order to prostrate myself at the footstool of my gracious Lord and Master,
and felt some relief.
O how precious is one little ray of light and life dispensed, and a living hope revived,
which enables me to say, Lord I desire to wait your time for enlargement.
Ah! it is good to be content, even to be shut up as in prison,
and not to cast away confidence then, though the doors may appear to be fast secured.
No way opens clearly, either to go home to my family and friends,
or to any place in this nation; and what can I do but endeavour after resignation.
So be it--stand fast, O my soul, and yet look up unto your only sure Helper,
who has forgiven you much, and has done much for you in past days, and even in this land,
in keeping you from sinking in the hour of trial.

"`22nd.--To Ratcliff monthly meeting with E. Janson, Phebe Speakman, and M. Horne,
where we met Mary Watson and sister.
Dined at Truman Harford`'s, and a singular opportunity occurred,
in which I thought Phebe Speakman was much favoured to
speak to the state of the heads of this family;
something like giving in my witness, appeared to be my duty,
and Mary Watson concluded the opportunity sweetly, I thought, in prayer.

"`28th.--Went with Sarah Harrison to Grace-church street meeting,
where I poured out my tears, and after it prostrated myself in prayer.
Felt a willingness to go with Sarah Harrison as far as Uxbridge,
and leave London in such a way as not to return, if way should open.`"

[.offset]
The following is taken from a letter addressed to him by his beloved friend Mary Dudley,
dated Bristol, sixth month 23rd, 1797.

[.embedded-content-document.letter]
--

Your farewell salutation, handed me on the evening previous to my leaving London,
was truly cordial to my mind, which had been so much with you,
that I was about setting out to seek a little of your valued society.
However gratifying this might have been to me, I was content, and I may say, thankful,
in being remembered by you, as you have been by me, in a nearly uniting manner;
and several times have I wished to salute you as an endeared
brother in the fellowship and tribulations of the gospel.
This is a track in which from feeling sympathy, I do believe your exercised spirit moves,
and through which perhaps, in like degree, many are not passing,
although each one may conclude his own burden enough.
I remember while writing the language, '`He trod the wine press alone,
and of the people there was none with him,`' and believe there may be, in measure,
a similar experience in the line of painful exercise,
although in the present superficial slate of things
such may appear to have neither form nor comeliness,
like their blessed Master.

Well, my dear friend, '`You, O God, see me,`' is a precious appeal,
and what an abundant mercy that he peculiarly regards
and owns such as are resigned thus to be baptized,
and with heartfelt submission drink the cup of suffering: these will not only know him,
their suffering Lord, and the fellowship of his sufferings,
being made conformable to his death,
but will also assuredly experience the power of his resurrection,
and after these baptisms unto death, feel an increase of pure spiritual life.
But why should my pen run on thus, as though such a poor creature as I am,
could administer any relief or encouragement to your tried mind,
which has been so abundantly instructed from on high, for the sake of others,
so that I have often said, you need not to be ashamed.
He who, by His own divine power,
has caused you hitherto to bring forth these things out of your treasury,
designs not now to shut up any longer than may
qualify for increasing faithfulness in his work;
and though I can often scarcely discern my own way one step,
I have so much faith respecting your way clearing up, that I was ready to say,
that perhaps even now, the renewings of the heavenly commission await you;
and though I feelingly observed the declension of your bodily strength,
surely the great healer of breaches can do all in this respect, as you and I,
my dear friend, have had cause often to acknowledge.`"

--

"`30th.--Went with Phebe Speakman and Ann Crowley to a little meeting at Rickmansworth,
eight miles from Uxbridge, held in the parlour of Emmet Skidmore,
in which dear Ann was drawn forth in an extraordinary manner;
and returned back in the evening to Uxbridge.

"`Seventh month 3rd.--After rising this morning I felt more cheerful and resigned,
and this little pleasant feeling causes thankfulness.
O how easy a thing it would be to the great
Disposer of events to change the dispensation,
even as streams in the south; and thereby cheer and comfort my wading mind.
Forgive, O Lord,
and have mercy on me,--then might I be favoured to teach transgressors your way,
and by the help of omnipotent power, sinners might be converted.
O that the dispensation I am now passing through may be looked at hereafter,
if my life is spared a little longer, and do me good in the latter end.

"`4th.--Drove Ann Crowley to Jordan`'s to a meeting,
appointed by Ann Alexander and company;
we found a rough way for a few miles of the latter part;
Ann and her sister and Ann Crowley appeared, and I was shut up in silence.
The house was nearly full, and mostly made up of women of the middle or lower rank,
some few excepted, who came in light and airy; a few men of the first description,
and less of those of higher rank.
I thought as I sat among them, what a change!--
probably I sat in or near the place where those favoured men,
Isaac Penington and William Penn formerly did,
when they could look over a large gathering of living professors,
and very likely often handed forth to them living food from the Lord`'s heavenly table,
to their mutual refreshment.
Now, if the few Friends were away from before me,
there would appear few or none but women with scarlet cloaks,
in a raw undisciplined state.
Alas! how has the crown fallen from off the head;
and yet what evident marks of the footsteps to be seen.
A neater meetinghouse is not often to be seen, and many conveniences about it;
and the graveyard is in nice order.
We ate our dinners in an upper chamber, a cold fare, but to me it relished well,
and reminded me of many such occasions in the wilderness of America.
I learn that two ancient men keep up this meeting twice a week.
I returned back to Uxbridge with my friend, and Ann Alexander went to Wiccomb.

"`6th.--Truly I am a poor creature,
and seemed this morning as though I could hardly lift a finger towards prayer;
like one that had become bankrupt--broken to pieces: perhaps when this is truly so,
my good Master may graciously be pleased again to make me up.
I am ready to query whether ever there was such a one sent over sea; and yet,
O that I may be favoured even in the fires to glorify His great name,
whose work and word is a deep mystery.
After dinner Ann Crowley proposed a ride, with which I closed;
and she and R. Hull and I rode as far as where Isaac Penington used to live,
within sight of Chalfont.
It is a pleasant rural spot, with a deep valley not far from it,
and a grove of fine trees in and around it.
The ancient garden walls are standing,
and the one next the road is built partly of small flint stones and partly of brick:
it is about two miles from Jordans.

"`8th.--I hear that Ann Alexander and sister, and David Sands, are not far from us,
appointing meetings among other professors; and here I am, blind, poor and naked,
but not miserable; because I humbly trust I am not standing still thus, from day to day,
in my own will.

"`13th.--Took a solitary walk on the commons, in a low exercised state of mind,
and endeavoured to cast my whole self on the everlasting helper of his people.
O how often could I fall prostrate on the earth, and bewail my state;
but there is a secret stay and a language, be patient--be still.
After dinner I again took my lonely walk--my bodily strength seems recruited,
and O that patience may have its perfect work respecting my spiritual strength,
or so much as the Lord in mercy may please to grant.
I cannot move in my own will or desire, to his praise and honour.
O that I may not bring reproach on that ever blessed truth,
which I hope and trust has been espoused by me through holy help in days past;
and I dare not believe otherwise now, though my little preaching seems to be, as it were,
out of the prison window,
or through the iron grating,--for soon after I am shut up again.

"`17th.--To Tottenham and met with George and Sarah Dillwyn, Phebe Speakman,
and her companion Ann Crowley.
After dinner dear George supplicated, and my mind was tendered,
and once more had a small Pisgah sight of good things.
It was indeed pleasant to have a little prospect of what gospel ministry is,
and I ventured to hand forth some encouragement to those afresh setting out,
although so shut up myself.

"`23rd, first-day.--Did not feel so much oppression as sometimes on awaking this morning.
O that I might be favoured this day to cast away the labour
and toil that have so often made me feel uncomfortable,
and lift up my heart to God in faith;
feeling a holy resolution formed by it to give
up in all things to the Lord most merciful,
to follow on to know him.
Surely in the midst of all these deep plunges, my soul craves this,
and dare not let him go.
Better is it to die than to bring dishonour to the great name.
O you searcher of hearts, and trier of the reins of men,
you know my condition and can speak to it.
Turn out every wrong thing from my heart--root out every wrong plant,
and grant me contentment under your humbling hand.
I went to Tottenham meeting, where I found Mary Watson; a quiet,
calm resignation spread over my mind in my walk there, and soon after sitting down,
an exercise spread, and the sight of the people assembled added weight to it,
some of whom were at the last meeting I attended at Grace-church street,
which was a remarkable time.
My exercise increased,
and cleansing virtue from the divine presence was experienced in my own particular.
O! I thought,
what a mercy once more to see the goodness of the Lord in the land of the living;
and feeling strength and boldness given me, I stood up with these words:
'`he that has a dream let him tell his dream; and he that has the word of the Lord,
let him speak it faithfully; for what is the chaff to the wheat, says the Lord.`'
But what most rested on my mind, was the fresh revival of these expressions, '`Son of man,
behold I take away from you, the desire of your eyes,
with a stroke;`' and as my soul has of later months been
made so deeply sensible of this taking away,
and even my pleasantest enjoyments have been crumbled as into the earth,
I had not only to humble myself in telling the assembly so,
but to reason with them of righteousness, temperance and judgment to come.
Mary Watson concluded the meeting in prayer, and in the little pause before we separated,
my heart was thankful that these words were made good to me:
'`But you are washed, but you are sanctified, but you are justified,
in the name of the Lord Jesus, and by the spirit of our God,`'
even by the washing of regeneration and the renewing of the Holy Spirit.
It is indeed a miracle of mercy--let reverence possess my soul,
and a willingness to bow to His sovereign will and pleasure, from hence forward,
and guard against a murmuring uneasy spirit, I trust that through all,
this has not been charged against me, even in the midst of extremity,
for there has been something which has kept my head above the waters;
and I have been afraid of appearing to others, in this uncommon detention,
to be a man at ease.
The afternoon meeting was large, and in it I also laboured.

"`27th.--It is an easy thing in the sight of the Lord even
suddenly to make a poor man rich:--these expressions have
revived this morning on getting up and making this note.
Truly my detention after this manner is very
marvellous--it is a trial of faith and patience;
yet I am much more favoured than I deserve.
Went to meeting at Tottenham and was largely exercised in testimony to various classes,
and felt comfortable and quiet after it.

"`28th.--Awoke and arose quiet and more easy in mind, and my soul craved ability to say,
I will trust in and rely on you, O my God.

"`30th, first-day.--To Tottenham meeting once more.
I could not persuade myself that I was worthy to stand forth;
but as there were so many of the gay and rich, etc., I endeavoured to discharge myself,
and was very closely engaged on the subject of death.
In the afternoon was again exercised in testimony, it being a large meeting.

"`Eighth month 1st.--In the night season, I had a little to rejoice in the prospect that,
after all, the Lord can make things new; and if it is his divine pleasure,
fit me and send me into some part of this island to labour,
and in the conclusion favour me to return home with peace.
O my travailing soul, wait on God, who will strengthen you, and be ready to go forward,
when the cloud is taken up, if even but a little: and O, says my soul,
that if there are fellow servants preparing to accompany me to my native land,
that the great Master will be pleased to accomplish his work in them,
and cause them to be in readiness.

"`My beloved friend and fellow traveller and labourer, and I,
had an opportunity this morning of conversing together,
and my soul craves that our care and sympathy may not go beyond the altar,
but that through all, preservation may be graciously granted,
even unto the everlasting kingdom, where I trust my dear Elizabeth, the wife of my youth,
has gone,
and where I have been favoured with strong confidence to believe my
dear Sarah will be favoured to arrive in the Lord`'s time.
My inward cries were put up in the night season,
that almighty Goodness would bless my dear children
with a more abundant knowledge of his ways.
I trust I can appeal unto Him and say.
You know I covet not great things in this world for them,
but that if their lives and mine are spared,
(and these I desire to resign up) they may cause my
soul to rejoice in beholding them your servants.

"`My desires have also gone forth at seasons for my dear aged parent,
that the Lord may more and more prepare her,
as a shock of corn fit for the everlasting garner,--so be it, O merciful One; and,
for your name and mercy`'s sake, look down upon your struggling servant and forgive,
and do and give what you, in your unsearchable wisdom, see to be best for him.

"`3rd.--Lay awake for hours last night, pondering my ways,
and the cause that such a path is my lot;
and although these things are too mighty for me fully to comprehend,
yet I hope my soul was brought measurably into a contrite state,
with feelings of holy fear and resignation, which were exceedingly pleasant,
even in the midst of the fires.
Sometimes I am ready to break forth and say.
You know, O Lord, I am willing to follow you into any part of this land, or further,
if it is your will, and your presence goes with me;
but even here I am stopped with a humbling sense, that I know not what to ask for,
without it is faith and patience to endure what the Lord may see best for me,
either in staying or going.
I went to the week-day meeting, and was favoured with a good degree of quiet throughout,
and a humble hope and trust revived, that if the patience is kept, way will open.

"`4th, sixth-day.--I hope I am in a waiting state,
with a willing mind to go at my divine Master`'s command;
and yet such is the weakness of my mind, that I fear there has been,
and perhaps may now be, a lack of faith to set out.
But surely it has been my soul`'s delight to move in the living faith,
and to be employed in so glorious a work as preaching the gospel.
O that it may in mercy be granted again, in the Lord`'s time, not my time.
It is close work to keep the patience in extreme poverty, week after week.
Notwithstanding all, this springs up as a comfort,
that if I am favoured to travel along and bow to the heavenly will,
all things will work together for my good at last.

"`7th.--O that I could be favoured once more with a ray of living hope,
and a belief that I am the Lord`'s servant; worthy to be further entrusted in his work,
that I could forget, as much as is right and profitable, the things that are behind;
things acted and transacted heretofore,
and experience the mantle of adorable love and mercy cast over all my infirmities,
which appear to be not a few,
and be favoured patiently to wait the Lord`'s time for
further opening into service in this land,
if further labour is my lot.
I cannot hasten his coming--O for trembling submission to the Lord`'s blessed will.

"`8th.--O adorable High Priest, your mercy,
pity and love are an over-balance to all that my wading soul meets with; therefore,
it has not sunk into despair.
Forgive all my iniquities, that have so closely encompassed me about: I cannot,
I dare not, hide anything from you, you all-seeing Judge,
for your penetrating eye goes through the whole earth.
O Lord, continue your protecting care and mercy to those whom your poor,
unworthy servant has left behind, for I desire to hope and trust in you, O my God.
Amen.

"`20th.--To Tottenham meeting, which was large; and I had once more a full and open time.
I ventured also, to bend in supplication, not only for myself, but for others;
begging for the blessing of preservation, and the forgiveness of sins and iniquities;
and that this meeting might be a time to look
back at in seasons of stripping and desertion,
as one of mercy and kindness.
To afternoon meeting at four o`'clock,
and had to address the visited children of our heavenly Father,
several of whom I had cause to apprehend were there.
In the evening felt comfortable.
O what a miracle of mercy, extended to such an unworthy one!
The Lord be praised,--and O for steady faith and
reliance on the divine Arm--come what will.

"`22nd.--Took leave of the family of Thomas Horne, who have shown me much kindness;
it appearing to me that my time was nearly run out in this place,--Tottenham;
where my soul has been deeply plunged.
O Lord, be pleased to reach forth your forgiveness, mercy and truth,
and open the way for your poor, unworthy servant.
Grant me ability to leave the things that are behind,
and reach forward in an upright desire to do your will only:
without you I can do nothing to profit or peace,--but by and through your power,
all things are accomplished that tend to your honour.

"`23rd.--Went to Grace-church street meeting, and sat it in pensive silence,
but was favoured so far as to see it right to go to Uxbridge.

"`26th.--Set off with Joseph and Rachel Smith, and arrived safely at Uxbridge,
and lodged at John Hull`'s.

"`27th.--Attended the meeting, where was Sarah Lynes from London,
who is on a visit to the north; she appeared in the ministry, but I was silent,
as well as in the evening meeting.

"`28th.--I have looked to see whether any known duty has been shrunk from in this land;
even when the hand of the Lord has been heavy on me,
and my soul has been bowed down under temptations and
trials which have been permitted to assail me,
and I see none.
I felt pleasant in two visits made to E. W. and family, and W. F. and wife;
children whom the Lord has favoured me in days
past measurably to beget through the gospel.

"`29th.--Felt a comfortable calm this morning, with liberty to go as far as High Wiccomb,
fourteen miles, where I rode on horse back.
In the afternoon several Friends stepped in to see me, with whom I had a pretty open time.

"`30th.--Attended the week-day meeting, and pretty soon after it was gathered,
Sarah Lynes and Elizabeth Stephens came in, and likewise a number of the town`'s people,
and we both had communications.
After dinner I had a religious opportunity with a number of Friends,
and then set out for Oxford,--and on descending Church hill,
was shown a place called Crowell, near which, in the valley,
I was informed Thomas Ellwood`'s father lived: the prospect around was beautiful indeed.

"`31st--After breakfast, accompanied by William Hull,
proceeded on our journey to Chipping Norton, where we put up at William Atkins`', who,
with his wife and children received us gladly.

"`Ninth month 1st.--Attended the week-day meeting, which was a pretty tendering time;
and on the 2nd we set off about eight o`'clock,
having first had a sweet religious opportunity with the family,
and arrived at Birmingham about dusk, having travelled forty-two miles:
here we found Ann and William Alexander.

"`3rd, first-day.--In the meeting, which was large, I had to sound an alarm to some,
and to offer consolation to another state: and in the afternoon had a full,
comfortable time, many of the town`'s people being collected;
my two female friends had also a share in the labour.

"`5th.--Left Birmingham about eleven o`'clock, accompanied by Joseph Shipton for a guide,
(a young lawyer,
who came into the Society by convincement:) William Hull also was with us,
Stopped at Litchfield and dined;
after which took a walk to the market place and town hall,
where we understood William Savery had a meeting.
We lodged at Burton on Trent.

"`6th.--Went on about seven miles, and stopped at Derby to breakfast;
and while Joseph Smith was transacting a little business, I took a walk into the town,
through the graveyard, and to a great building with a high steeple.
My spirits were oppressed, and I felt dejected and low.
My thoughts turned to George Fox and his imprisonment;
and if my exercise has been in sympathy and
feeling with a state of deep trial and suffering,
into which he and some of our forefathers were largely introduced, I am content;
for I can feel little opening towards the people at large.
O Lord, hasten the day of Zion`'s redemption and prosperity:
bring down pride and haughtiness, and that ranting, unbelieving spirit,
which is so prevalent in this land,
and set up your ensign of righteousness more conspicuously;
and grant that my soul may still be supported to answer your requirings,
either in doing or suffering.
The country round about Derby is very fine, but the road to this place hilly.
After dinner we proceeded on, and arrived at Chesterfield, where we lodged.

"`7th.--Sat with Friends in their week-day meeting, which was small;
and though I felt much weakness, ventured to express my feelings.
After dinner we rode to Sheffield, where William Fairbank and wife received us kindly.
In the evening a large number of Friends came in, with whom I had a religious opportunity.

"`8th.--Went on, accompanied by William Fairbank, passing through Wakefield,
and arrived at Christiana Hustler`'s after night,
where we found a pretty large company of Friends,
it being the day on which their monthly meeting was held.
Felt my mind light and easy; but when I laid down did not feel so well,
fearing that in this state of liberty, I in some degree broke bounds:
O the necessity of watching at all times.

"`9th.--Left Christiana Hustler`'s about eleven o`'clock,
and passed through Keighley and Thornton to Martha Smith`'s, sister of my kind landlord,
who, with his wife, are still with me.
We crossed a steep mountain,
which reminded me of my journey over the Alleghany mountains in America.
We passed through a fine country lying to the north--saw the town of Skipton,
and the village called Carlton, about one mile from it;
the last place is where Markham lived,
the priest who cast Friends of Lotherdale into prison at York.

"`10th, first-day.--Was accompanied by our London friends, Joseph and Rachel Smith,
and others, into the dale called Lotherdale,
where we found a pretty large gathering of Friends and others; and I had an open,
tendering opportunity among them.
We dined at Mary Stanfield`'s, whose husband, John Stanfield, is a prisoner at York,
for tithes, at the suit of priest Markham;
after which took a walk with Joseph Smith to the old meetinghouse,
to look at the ground, they proposing to build a new one.
My heart went forth in love to dear Joseph,
while he was sitting by my side in the meeting, on remembering to have heard him say,
that he intended to build a new house for these poor Friends in this place;
and I did believe, that in so doing, the Almighty would bless him.
I felt comfortable and easy among this peeled little company;
who live in a vale as poor and lonely, I thought,
as some places on our Alleghany mountains.

"`12th.--My mind has been turned this morning, towards my dear wife, children and family;
and as respects some of them, with sighs and tears; and yet with desire, I trust,
uprightly to say, '`Your will be done, O God, and let mine submit in obedience to it.
O preserve your servant in this his lonely state.`'
We rode to Settle, and got to the select monthly meeting about five o`'clock.

"`13th.--Arose low and poor.
If the Lord keep not the city, the watchman wakes but in vain;
except the Lord build the house, they labour in vain who build it.
May I cast myself, therefore, on him,
hoping and trusting still in his mercy and goodness; for indeed I am often a poor,
solitary one.
Attended the monthly meeting at eleven o`'clock,
and had to communicate pretty largely to several states.
Two women walked, yesterday, from the Dale, about seventeen miles, in the rain,
thunder and lightning, to attend the meeting.

"`14th.--Felt a little revival of hope before leaving my bed this morning.
How often have I been tried with respect to some singular testimonies which
I had to bear in London,--when my mind has been almost ready to sink;
and yet, through all, I hope and trust I can say,
it has been the desire of my soul to act and speak uprightly,
and I must leave the result to the Lord most merciful.
I recollect particularly, what a very painful, wakeful night I had,
previous to one of the last opportunities at Grace-church street,
when Ezekiel`'s situation was revived, and I handed it forth.
My spirit was pressed down with it in the night while lying on my bed.
I have thought my spiritual state, for months past, has resembled that of the prophet,
when the widow fed him--his was an outward need,
as expressed in the Old Testament,--mine is inward; he was fed by the widow,
who had naught but a little meal in the barrel, and oil in the cruse,
and yet it held out through a time of drought.
O that the great Prophet may be pleased to sustain and
help me through this time of stripping and famine,
who am mostly in a state of much weakness and blindness,
and yet trust a little portion of faith and hope yet remains,
although it be comparable to the handful of meal in the barrel,
and a little oil in the cruse.
Returned to Martha Smith`'s at Thornton.

"`16th.--Felt no opening to appoint a meeting in this neighbourhood,
and seem much a blank; yet hope, that as a scholar in the school of Christ,
I am getting this lesson by heart,--Your will be done.

"`17th, first-day.--Joseph Smith went yesterday to Skipton, and before he set off,
after endeavouring to get enough into the quiet to hear the Shepherd`'s voice,
I ventured to encourage him to appoint a public
meeting to be held there on second-day morning,
and another at Lotherdale, to be held this morning, with which I felt easy.
After breakfast, accompanied by Joseph Smith, got into the Dale about ten o`'clock,
and climbed up a steep, slippery hill,
and had a satisfactory opportunity with a large
number of what are called Sunday scholars.
Some tenderness appeared among them,
but I was much spent from the closeness of the room, and the breath of so many.
Went to the meeting at eleven o`'clock, which was very large,
and an open relieving time--the people behaved solidly; I felt much fatigued, yet,
after a tendering time with the exercised woman
whose husband is in York castle for tithes,
and others who came in, I set off across the mountains, the near way for Thornton.

"`18th--Got into Skipton about ten o`'clock,
and found that our meeting was to be held in a Methodist meetinghouse,
the one belonging to Friends being small,
and as the other had been offered to Sarah Harrison when here, and the same person,
a considerable man in the town, offering it again for our meeting,
Friends were free to accept it.
It is very commodious, and I had an open, comfortable time in the meeting,
and hope it was so to several who were gathered.
The name of the person who offered the house is Peter Garforth;
and I learn that his sister built it,
and that a goodly solid woman who was at our meeting,
proposes building one a little distance from this place.

"`22nd.--To Kendal week-day meeting; and though for sometime I sat in poverty,
yet afterwards was a little comforted and cheered, and set at liberty,
not only to warn the unruly, but to hand forth some comfort to the feeble-minded.
Dined at George and Deborah Braithwaite`'s with several Friends, and after it,
Joseph Smith, George and I, took a walk to the old castle, and looked over the town;
we also went into the large old steeple house,
and I had the curiosity to step it on the inside, and made it 144 feet by 105.

"`24th, first-day.--The meeting today was but a low, exercising time in the beginning:
I laboured earnestly among them, and very closely, from these expressions,
with which E. Robinson, a young woman lately convinced,
closed her testimony before I arose '`Bring forth, therefore,
fruits fit for repentance,`' etc.
This young woman, I am informed,
is turned out of doors by her mother for coming among Friends.
The evening meeting was put off until six o`'clock,
and though I gave no liberty to invite any, yet it was large,
and very close and exercising labour fell to my lot from these words;
'`Seek not death in the error of your life.`'

"`25th.--A pretty calm mind this morning, though under conflict on my bed,
in reflecting upon the little effect which religious labour
seems to have on the minds of the people in the present day.
O the independent, atheistical spirit that prevails over many,
and has even entered and gained some ground in our religious Society.
How often is my soul afflicted and bowed under a
consideration of the state of the high towering ones,
who know so little of the afflictions of Joseph, or the imprisoned seed.

"`27th.--We got to Cockermouth, having rode forty-two miles.

"`28th.--Attended the select quarterly meeting, which was large,
and it fell to my lot to be closely engaged in a searching manner.
At two o`'clock, went to the quarterly meeting, in which I had a full,
relieving opportunity, both in the meeting for worship and that for discipline.
We had the company, at dinner and tea, of Sarah Talbot,
and her companion Sarah Shackleton of Ireland, and Mary Sterry and Mary Watson,
much to my comfort; and when we sat down to dine,
my heart was enlarged in prayer for myself and fellow-labourers,--and
that the young people of this family might be blessed;
and that we might be favoured in the present quarterly meeting, etc.

"`29th.--To the parting meeting at nine o`'clock,
and after all my friends had an opportunity to relieve their minds, I had a full,
relieving time, and Mary Watson closed in prayer.

"`30th.--Rested pretty well,
and through favour feel my mind calm and resigned to the will of my heavenly Master,
with breathing desires that I may be favoured to know him to go before,
and to know his voice; then surely, let what requiring soever be opened,
it will be my duty to say, '`Here am I, send me!`'
So be it, says my soul, in humility and reverence.
After breakfast we left Cockermouth, and passing through Preston, arrived at Whitehaven,
where we put up at the widow Jane Pearson`'s.

"`Tenth month 2nd.--Had a singular opportunity with three of Jane`'s grandchildren,
who though at first, light, were brought plentifully to their tears; after which set off,
stopping at Keswick to dine, and got into Hawkshead late, where we lodged.
This was a lonely but instructive ride to me,
among the mountains--many sheep were feeding on the sides of the hills,
and interspersed among them are lakes of considerable extent.

"`3rd.--Drank tea at Clement Satterthwail`'s, where I had a satisfactory opportunity,
in which a dear Friend, Hannah Wilson, who is eighty years old,
and lively and green in her old age, joined in a short testimony.
How comfortable to find a seed preserved, who are accounted for a remnant.

"`4th.--Took a walk over the meetinghouse and
graveyard--the latter had seats of stone all around it,
fixed in the wall; and in the middle a wall about as high as a seat,
which the old Friend told us after we returned, was so constructed, she understood,
in order to hold meetings there, in ancient times.
In coming to this place the day before yesterday,
we rode for sometime in sight of a hill called Pardsay Cragg,
perhaps ten miles from Cockermouth, where Friends in the beginning,
held their meetings in the open air--when the wind and rain beat on one side of the hill,
they removed to the other, and it appeared to have ridges one above another, like steps,
as if formed for the purpose of seats.
Dined early and set off, and got to the ferry house at Windermere lake,
kept by a blind man.
Our horses were taken over in a large boat, and the rest of the company,
with our friend John Bragg, took to a smaller one, and rowed around Curwen`'s Island.
The prospect is beautiful indeed to the eye,
the land surrounding it being covered with shrubbery, fruit trees,
and a comfortable looking house;
but when I heard that the person who owns it was offered 20,000 for it,
and would not take it, although containing only about forty-two acres,
I thought what a pity so much should lie as it were dormant, when there are so many poor,
so many widows and fatherless children ready to perish.
After landing we found there was no post chaise to be had, so my kind London friends,
Joseph and Rachel Smith,
were obliged to put up with a cart and a boy to drive them nine miles to Kendal,
and it was a mountainous ride, and very entertaining.

"`5th.--To the select quarterly meeting, where very singular things were delivered by me,
although an utter stranger; but I heard afterwards, that they were pertinent:
here I was met by Mary Sterry and Mary Watson.
The quarterly select meeting was held at three o`'clock in the afternoon,
and the monthly meeting for Kendal in the morning at ten o`'clock.

"`6th.--To quarterly meeting, where the labour fell mostly on me,
and I was favoured with a full, relieving time, both in the meeting for worship,
and afterwards in that for discipline.
I went also, into the women`'s meeting with Simon Harker,
who expressed a concern in a lively, tender manner, to visit families.
Attended the parting meeting at six o`'clock,
and we sat nearly or quite two hours in silence, and to me it was a sweet,
refreshing time, such as I have not frequently been indulged with; and in the close,
I had a short testimony to deliver.`"

[.offset]
In a letter from this place, dated tenth month 8th, 1797, he says:

[.embedded-content-document.letter]
--

"`Which way I shall move from this place, I know not at present,
and am content with my allotment, even when going a zig-zag course.
I have been used to it in my native land, and through mercy it is made easy enough now,
and I am daily trying to learn this important lesson, '`Your will, and not mine, O God,
be done;`' and if preserved here, whether heights or depths, principalities or powers,
life or death, may, in unsearchable wisdom be dispensed,
all things will work together for good.
I may just add, and that with humility and thankfulness of heart,
that I have been favoured with much enlargement in these two quarterly meetings, namely:
Cumberland and Northumberland and Kendal, and trust,
acceptance in the minds of my friends.`"

--

"`10th.--To the week-day meeting, which I sat through in silence,
and felt content and cheerful after it.
Soon after dinner set off, accompanied by Joseph Smith and George Braithwaite,
all on horse back, to Ulverstone; we had a mountainous ride of twenty-one miles,
and crossed lake Windermere, and got into town after night, about seven o`'clock.

"`11th.--Attended Swarthmore meeting, about a mile out of town; and after it,
took a walk over to see the remains of the old hall, where judge Fell lived.
It is in a ruinous condition, having gone much to decay;
the room where they used to hold meetings, and which stood on the left of the entrance,
is quite dilapidated.
The entrance is paved with flag stone;
on the right hand is a large room with a curious old fashioned window,
somewhat like the modern projecting bow window; it is two steps up,
and in it stands an old chair,
on which was marked "`T. T. 1642,`" There is curious wrought work, in parts of the room,
and I think it was flagged.
The staircase is a very singular one, with curious carved work, and goes up to the roof.
One of the chambers has very old fashioned cut work over the chimney place,
and around it, and on the edge of the hearth stone.
The once beautiful garden and orchard, and the walls round them are all in ruins.
The meetinghouse is neat and comfortable, much such a one as that at Jordan`'s:
there is a good wall around a large graveyard, with trees about the house,
the two nearest the door not much unlike our pines or firs.
Over the door is inscribed "`Ex. dono G. F.,
1688;`" and I was informed he purchased the ground of one of his daughters-in-law,
and ordered the house to be built, but never saw it.
+++[+++See Friends`' Library, vol. I. p. 96, 97,]
There are yet two very old fashioned oaken chairs in the small part of the meetinghouse,
which he gave to Friends.
One of them Robert Widders used to occupy, and John Taylor, of this country, the other;
both are of very curious workmanship.
There was but a small company of people at the meeting,
but with thankfulness I may record, that both on going up the road to meeting,
and soon after taking my seat, my mind was comforted.
After dear George Braithwaite had spoken my feelings in a few words,
the meeting was gathered into a comfortable frame,
and I ventured to bend in supplication;
and then was pretty largely engaged in an encouraging line, especially to the youth.

"`I thought I had a prospect of a renewed visitation to this place in a day to come,
and mentioned somewhat of it to the meeting.
In the silent part, I remembered a portion of the ninety-first psalm,
and had a secret hope that I might lay hold of it for my encouragement;
for indeed I was once more favoured to feel the salvation of God near;
even Him who is the blotter out of sin, and the forgiver of past transgressions;
and who said '`I will show him my salvation.`'
In the evening, after walking up a high hill and taking a view of the town,
the bay and the place where George Fox was dragged by the rude,
persecuting people and nearly killed, and looking into the old steeple house,
I had a solid religious opportunity with several Friends.

"`12th.--After breakfast my mind was impressed with a
prospect of going again to Swarthmore hall,
for when we left it yesterday, as the woman who keeps it, let us out of the gate,
my mind was rather unusually turned towards her,
and as this concern remained with me on my bed,
both on lying down and during my wakeful moments in the night,
I told my companions I must go back--so they, with Elijah Salthouse the elder,
went with me.
Soon after getting in,
I asked her if she was willing to send for her sons out of the harvest field,
(for they were drawing oats,) and with her two grown-up daughters,
sat with us for half an hour in a religious way.
She soon had her sons in, with one other young man and a lad,
with whom we had a baptizing time.
One of the grown-up sons had lately returned from off a man-of-war,
on board of which he had been decoyed: he was much broken into tenderness and tears,
in the opportunity, and told me on parting,
he was disposed to remain and help his mother,
his father having recently died after a short illness,
O the sweet peace I felt in and near these old ruins, as well as after I left them,
from an honest discharge of duty.
We left Ulverstone, stopping near lake Windermere to tea, and got to Kendal about dusk.

"`14th.--I have occasion to acknowledge that the Lord has been my strength and my song,
and also my salvation: he has opened and enlarged my heart in this north country,
and wrought a willingness in me to follow him further, if the way should open.
I had this morning a baptizing tendering time on my bed, with humbling prospects,
and many tears.
O may I be favoured to abide constantly in the will of God, who has led,
and also fed me in this land, with food suitable and convenient for me,
although it has been the bread of adversity, and at times,
the bitter water of affliction; yet my eye still beholds my teacher; and now,
instead of going further north, I must turn a little back,
and what matter if it be by the way of the wilderness,
so as it is the way of my heavenly Master`'s good pleasure;
then by following on fully and faithfully,
all my trials and deep inward conflicts will no doubt be blessed and sanctified to me.

"`After several religious opportunities in families, we set off,
and passing through Yealand, we got to Lancaster, and put up at David Dockray`'s,
and soon after we got in, a newspaper was put into my hands,
containing an account of the yellow fever having appeared in Philadelphia.

"`15th, first-day.--Attended the meeting, and was favoured to relieve my mind,
first with a language of encouragement and consolation to the children,
babes and sucklings in the church, and afterwards with a rod to false professors.
In the afternoon at three o`'clock, most, if not all of the morning company came again,
with the addition of some strangers, and I had a large, open and relieving time;
so much so, that I not only thought, while speaking,
but said that it looked likely my stay would not be long in this place;
for in other cases where there has been an opening and strength given to relieve my mind,
there has been liberty also to go pretty soon.
Drank tea at W. Jepson`'s, and soon after, there came in some orphan children,
grand-daughters of Elizabeth Wilkinson, who was in America with Alice Hall;
and I felt very sweet and comfortable toward them,
and had encouragement to hold forth to them, but otherwise to another state present.
O how this unbelieving, independent spirit grieves and pains my best life.
In the evening a Friend came in, who had with him New York papers,
giving a further account of the fever, of which about sixty persons had died;
it appears to be much like that of `'93.

"`16th,
second-day.--I hardly knew whether my mind was most in sympathy with
the sick and distressed in Philadelphia yesterday,
or dipped into the state of the meeting here, as I found it when among them:
I had to tell some of the company, that they were wearing linsey woolsey garments,
sowing their fields with various sorts of grain, and ploughing with an ox and ass, etc.,
and my labour was close indeed.
Today a Friend told me that there is a young man here who is convinced,
and comes to this meeting, whose mother threatened him much if he thou`'d her, etc.,
which he believed it was his duty to do.
She went to some of the gay Friends belonging here, to make her complaint,
and said to them, she wished, if her son must go to meeting,
that he might be such a Quaker as they were, who could attend meeting, and yet say you,
and use the world`'s language in other respects.

"`What a rebuke this was.
After dinner, parted with my friends, George Braithwaite and J. W.;
I felt easy to go towards Sheffield, and set off and rode twenty-two miles to Preston,
and met an open, kind reception from William Brown and his sister Alice.
I had a sweet ride here, because of that ease and peace of mind I enjoyed.

"`17th.--We passed through Blackburn and Haslenden, and arrived at Todmorden,
where we lodged.

"`18th.--Awoke stripped and poor this morning,
and endeavoured to prostrate myself in humble prayer to my great and Almighty helper,
and trust I heard the still small voice, saying, '`Go to Sheffield.`'
Samuel Greenwood, a young man of this place, offering to accompany me,
we journeyed on to High Flats, and just before we got there,
I thought I had the most extensive prospect of any I had seen in this land,
from a barren, high hill.
We arrived at Sheffield after forty-six miles ride,
and put up with my kind friends William and Mary Fairbank.

"`19th.--Arose this morning fresh and well, and now a consideration arises,
why such haste to get back to this place?
O my soul, wait in patience, for there is peace administered thus far.
In my lonely ride, and especially during the latter part of the day,
my thoughts were turned home to my family, and poor Philadelphia;
and such has been the favour vouchsafed amidst my deep conflict,
that there has been a fixed evidence sealed on my mind,
that if an all-wise Providence calls some of my dear family hence,
and I should not be permitted in this life again to enjoy their society,
there is a place of rest and peace prepared.
What a consolation this has been, at seasons, to my wading mind.
O then let me leave these things to Him who judges righteously.
Attended the week-day meeting, and was favoured with a satisfactory time.
I told them that I had come nearly one hundred miles to attend this meeting;
and in the close felt liberty to say,
that it would be pleasant to have the neighbours
invited to come and sit with them on first-day.

"`21st.--Was informed that Friends have provided
a large building formerly used as a foundery,
about 32 yards by 20, and fitted it up with benches and a gallery,
to accommodate the meeting on first-day; their own house being small.

"`22nd, first-day.--Attended two very large meetings.
It was computed that three thousand people were at the one held in the afternoon.
Both of them were very satisfactory to my mind.
After the morning meeting a captain of horse in this place,
came and attempted to speak to me, but when he took me by the hand,
he turned away and left me--he came again in the afternoon,
and then told me his heart was too full to speak to me in the morning.
In the evening we had a sweet religious opportunity in
prayer and testimony at William Fairbank`'s.

"`25th, fourth-day.--To meeting,
which was thought to be three-fourths filled with journeymen, apprentice lads, etc.;
it was solid, and they left it in a commendable manner,
affording considerable relief to my mind.

"`26th.--To week-day meeting held in the large house, many of the inhabitants attended,
and it was satisfactory to me, finding much enlargement.
At the close I appointed one for female servants, etc., to be held tomorrow afternoon.

"`27th.--At eleven, accompanied by William Fairbank and Thomas Colley,
I went to the work-house, and had a meeting with the poor people,
and a large number of poor children;
which was to satisfaction,--several of the overseers or managers being also present,
who were respectful after the opportunity.
At three o`'clock, attended the meeting appointed for female servants, etc.,
which was much crowded, and on the whole a satisfactory, relieving time,
though I had to stand up in much weakness.
The people were long in getting out,
and towards the last the tutoress of a school for poor girls,
who had brought her scholars to meeting,
and had seated them in the back part of the house, came forward with them,
and placed them before me, under the gallery,
and I had a satisfactory opportunity with them.`"

[.offset]
In a letter to George Dillwyn, dated the 28th of this month,
after speaking of his release from London, etc., he says:

[.embedded-content-document.letter]
--

When I returned last to Kendal, my way seemed closing up respecting the north,
and opened towards Lancaster: this seemed like going back,
but as the prospect fixed pleasantly on my mind, giving up thereto afforded sweet peace.
From there, this place opened,
and fastened with more weight than any prospect for some time,
and what appeared singular was, that I must hasten, and be at their week-day meeting.
Some reasoning took place on the way; what should be the cause I knew not,
whether to go into sickness myself,
or hear of the sickness or death of some of my friends;
but being favoured with strength to perform the journey,
as the intimation to my mind was, so it has been performed.
'`Go to Sheffield and it shall be shown you what to do.`'
I found much to do, and have been helped, if not to much profit to others,
yet to the relief of my own mind.

--

[.offset]
After speaking of "`the faith and zeal`" of Friends in fitting up the large building,
and the character of the meetings, which is described pretty much as in his diary,
he says:

[.embedded-content-document.letter]
--

Dear George, this is a singular line in which I am led; yet,
let the wits of this world say what they may,
and I have been often deeply tried with this spirit, so prevalent with some,
my mind has been convinced and confirmed in the belief,
that the revelation of the mind and will of a most glorious High Priest, has not ceased,
but is continued, more or less, in his church, and to his humble depending children.
I have been querying why I should write thus:
is there not occasion for such a poor thing as I to lay my mouth as in the dust?
Yes, and it has been so often, in this land of high profession;
but surely there is still a power sufficient to make the very stones cry out.

--

[.offset]
The following account of this visit to Sheffield is from another hand:

[.embedded-content-document.letter]
--

On the 18th of tenth month, 1797, Thomas Scattergood came to Sheffield,
and attended our week-day meeting next day, where he had much service,
principally addressed to the youth;
and at the conclusion mentioned his intention of staying over first-day,
requesting that Friends would invite their neighbours to come and sit with us.
As our meetinghouse was not large enough to
accommodate a great many more than our usual attenders.
Friends obtained a very large building, erected for an iron foundery,
which was unoccupied, fitted it up with a gallery and comfortable seats,
and met there on first-day.
The meeting was very largely attended by the inhabitants of our populous town,
and Thomas was remarkably led to speak with convincing authority,
awfully calling on the company to consider the uncertainty of time,
and prepare to meet their God;
telling us in how singular a manner he had been drawn
here,--that when about one hundred miles distant,
he felt a strong and forcible attraction to Sheffield,
accompanied with an intelligible language in the secret of his heart,
which followed him day and night, '`Go to Sheffield, go to Sheffield,
and there it shall be shown you what you shall do: hasten you, hasten you.`'
It was truly awful, and seemed to spread seriousness over the assembly;
his testimony was long and very powerful.
The afternoon meeting was still more crowded,
it being estimated that three thousand persons were there;
and in that meeting also his services were very great.
To the surprise of the audience, the voice of our dear friend held out wonderfully,
and in the evening his very countenance bespoke the peace of his dedicated mind:
a remarkable degree of solemnity prevailed in both these meetings.
After supper he had a memorable opportunity in my father`'s family,
several young Friends being present;
and after commemorating the greatness of divine power displayed that day,
he addressed several persons in affectionate and encouraging language.

On fourth-day morning, the 25th, another meeting was appointed at our friend`'s request,
and held in the same large building, for the male sex solely,
chiefly apprentices and working men of the manufactories in the town;
and it was attended by a large number.
On fifth-day, our usual meeting-day, a large number collected,
and he was again enabled to minister to the various states of the people,
to the admiration of many.
At the conclusion of the meeting he expressed a
desire to see the lower class of the female sex,
such as servants, etc., exclusively, the next afternoon at three o`'clock.
The meeting was accordingly appointed, and a large number collected;
it was computed that more than two thousand women were present;
they were called upon by our dear friend in an awakening manner,
to prepare for their latter end,
and various states and stations were feelingly addressed:
the girls of a charity school present, with their teacher, were particularly addressed,
and the children reminded that women were the first promulgators of the gospel.

In the forenoon of the same day,
Thomas had a meeting in the poor-house with the families, pensioners, and a few others.
On first-day, 29th, had two other very crowded meetings,
attended by (it was believed) three thousand persons,
in each of which he preached in the demonstration of the spirit, and with power,
imparting many gospel truths, and touching upon the subjects of baptism,
spiritual worship and our belief that revelation has not ceased.
In the afternoon he was led to explain some of our peculiar tenets; among others,
disapprobation of oaths and war, the latter of which,
he said was one of the noblest testimonies we have to bear.`"

--

[.offset]
In a letter to his wife about this date,
after alluding to the accounts which had reached him,
of the progress of the yellow fever in Philadelphia, he says:

[.embedded-content-document.letter]
--

This seems more than a bare report, and if true, is awful indeed.
I have gone through abundance, in deep thoughtfulness about home, etc.,
frequently in this land, and could write much about it; but it may suffice to say,
that since this account has reached me, my mind has been closely exercised; and yet,
through mercy, and indeed to my humble admiration,
possessing much quiet and resignation to the will of Him who judges righteously,
and does all things well; and I know I cannot add to, or diminish by taking thought.
You may naturally think, my dear,
that I shall be under much anxiety to hear and
know how things go with you in Philadelphia,
and in my family; and if you are spared, it will be of adorable mercy;
and if so ordered that some of us never meet again in mutability,
strong has been my faith at times, when looking towards you,
that our heavenly Father is near, and that whether in life or death, all would be well.
This has cheered my drooping soul, when looking towards my family,
and I have had renewed cause of late,
after a very great conflict which was heavy upon me for months,
to believe that I am in my allotment, and trust,
under the protection of Him who feeds the ravens, and without whose notice,
not a sparrow can fall to the ground; and if further trials await,
O that my soul may be favoured to say in truth and with uprightness, '`Not my will,
O Lord, but yours be done.`'

--

"`29th, first-day.--Unwell last evening, with some cold and sore throat,
which increased in the night, and feel poor in spirit this morning, and humbled.
I trust mercy and kindness is with the Lord, who can heal and help.
Went to meeting, which was very large, and a fine open time of much enlargement,
for which I felt very thankful to the Lord, my most merciful, holy and mighty helper.
O that my soul may feel after preservation in the future, come what may.
To afternoon meeting, which was also very much crowded, and to my great admiration,
a time of enlargement.
O what a favour to get well through such large meetings.

"`Eleventh month 1st.--Very weak and poor with respect to moving on, yet Derby, Derby,
seems to sound in my ears in the same manner as this place did a week or two ago.
About eleven o`'clock, after some close thoughtfulness, came to a conclusion to go,
and my kind host William Fairbank, inclining to accompany me,
we rode to Chesterfield and were kindly cared for by Mary Storrs,
her husband being with Ann Alexander and sister Mary in Wales.
Before we proceeded any further,
I thought best to authorize her to write to Friends at Nottingham,
to engage them to go to Derby and procure a large place for a meeting,
and invite the inhabitants to come together on first-day next,
after which we rode to Mansfield.

"`3rd.--Spent this day pretty quietly at Richard Leaver`'s,
except taking a little walk through the town, and found it pretty much in confusion,
it being the day that servants, both male and female, come to offer themselves to hire.

"`4th.--This morning my soul has craved animating strength,
and I am ready to say forgiveness also; fearing there has been too much indulgence.
We set off for Derby, and got in about dusk, and found several Friends there,
who had procured the county hall, and fitted it up with seats.
This evening we had a meeting at the inn with most of the professors in this place,
to satisfaction.

"`5th, first-day.--Held two large meetings, much to the relief of my mind;
a very great crowd attended in the afternoon,
and though there was much unsettlement at first, I was favoured to get along,
and the meeting ended well,--Truth being in dominion over lightness.

"`6th.--Felt an openness to go into the families of the few professors in this place,
and accordingly visited seven or eight families;
on the whole my services have yielded solid comfort and peace to my mind,
and now the query arises.
Lord, what further would you have me to do?

"`7th.--Felt a liberty to move on to Castle Donnington,
where we had a religious opportunity in the family of George and Ruth Follows.

"`8th.--Went to meeting and a considerable number of the town`'s people came in;
Ruth Follows opened a door for me to preach the gospel,
and it was a tendering opportunity towards the close, I hope to satisfaction.
After this my mind was turned towards Nottingham,
though it appeared like going back again; and we arrived there a little after night.

"`9th.--Went to meeting in a low condition and sat long in silence,
but towards the close had some very close things to say,
and afterwards encouragement and consolation to the widows and fatherless,
and exercised ones.

"`10th.--I took a lonely walk in the park back of the castle and dropped a silent tear,
and was comforted in being thus alone, and yet not altogether alone,
for I remembered with sweetness this passage,
'`thus says the high and lofty one that inhabits eternity, whose name is Holy;
I dwell in the high and holy place, with him also that is poor and of a contrite spirit,
and who trembles at my word.`'
O how sweet is retirement;
here I remembered the many lonely and deeply exercising
times I had when walking near Tottenham;
and also some of the walks on Uxbridge common; how my way was hedged up at times,
and at others,
some sweet moments in submitting to the dispensation of an all-wise Providence,
and yielding up my will to the trying prospects that frequently presented.
In my lonely walk this morning my soul bowed in prostration,
and begged for preservation to the end of this pilgrim journey,
and was favoured in some degree to see the good land afar off.

"`12th,
first-day.--This meeting was a singular one--my
heart was much enlarged to various states,
and I had to reason with some concerning righteousness, temperance, and judgment to come.
It was a tendering meeting, and a Friend told me that a youth said,
he could not attend to business after meeting on fifth-day last, he was so affected.
The Lord have the praise of his own work.
To afternoon meeting at half past two o`'clock,
which was pretty much filled up with strangers, I thought of a serious class,
and it proved a satisfactory time.

"`15th.--Attended the meeting at Mansfield, and had a pretty open time, and on the 16th,
was at meeting at Sutton, where considerable tenderness and solidity appeared.
Thomas Kirksham, who had been a priest, and was well acquainted with Friends`' principles,
seeing there was room in the house, sent for his scholars, and when they came in,
my heart seemed moved within me in love towards them.
The goodly master rejoiced particularly on seeing one
of the wildest boys much reached and tendered.
The meeting was a comfortable strengthening one to me,
and in the close I prostrated myself in prayer.
William Fox told me there was an atheist at Derby meeting,
who said there must have been something supernatural
attending such a discourse as was delivered there.
I presume it is the same one who said he did not think
it possible to be so reached by the ministry of any man.
'`Rejoice not, says our Saviour, in that the devils are made subject unto you,
but rather rejoice that your names are written in heaven.`'
May the Lord have the praise, and man`'s mouth be laid in the dust, as mine often is.

"`17th.--To a very large meeting held in a malt-house;
it was supposed that not much short of two thousand people were present,
and it was an open, solid and satisfactory time, of much enlargement to me;
several persons on coming out expressed their satisfaction, and blessed me in their way;
but the Lord have the praise who helped me much.

"`18th.--In our ride to Litchfield today, we saw the place where George Fox was born.

"`19th, first-day.--Went to a meeting in a dissenters`' meetinghouse;
Friends had it cleaned out and fitted up with seats very commodiously.
The people were slow and long in gathering, but it was a pretty thorough time,
in which I had to mention the remarkable circumstance
of George Fox`'s going through their market place.
Dined at the inn with upwards of thirty Friends,
and had a singularly tendering opportunity with them,
opening the importance of their setting a good example in trade, dealing, etc.,
after which I felt easy to proceed to Sutton, and then to Birmingham.
This was a sweet and pleasant ride to me,
and I received a full reward at the hands of my Lord and Master,
for labouring to fulfill my duty in going the late round, ending at Litchfield.

"`22nd.--Attended a meeting appointed about a mile and a half out of town,
which was large, some of the principal inhabitants being at it,
and it proved an open and relieving time, several subjects being treated on,
and I trust a solemn alarm sounded.
I had to tell them,
that however some in our Society were as a stink in the
nostrils of God and man in consequence of their evil conduct,
yet there would be a gathering to this people,
for the Lord had raised them up to bear testimony to his truth, and would support them.

"`23rd.--We set off after seven o`'clock, in a post chaise,
and passing through Stratford on Avon and Skipton, arrived at Chipping Norton,
and went to William Watkins`', where we found Friends had not appointed a meeting,
it being "`fair-day,`" and they had held their week-day meeting today on this account.
The thought struck my mind rather singularly on coming into the town,
whether a meeting had been appointed, and I thought if Friends had not done so,
that the prospect was likely to be taken away, and so it proved;
for on hearing they had put it off until they saw me, I felt easy to pass on.

"`24th.--We got into Oxford about four o`'clock,
and being unable to procure the town hall for a meeting, or any place sufficiently large,
felt easy to go to High Wiccomb, where we arrived on the 25th.

"`26th, first-day.--Attended meeting and it was a refreshing time of encouragement.
I was glad once more to sit quietly for a season among a little company of Friends;
after which, both Mary Pryor and I had religious communication,
and considerable brokenness appeared.

"`29th.--Went to a meeting held in the town hall at Aylesbury,
which was pretty much filled up with people of several descriptions:
Mary Pryor opened the service in a short testimony,
which had a tendency to quiet the meeting,
and I thought it right to avail myself of the opportunity,
before any unsettlement again took place;
so I stood up in a state of weakness with the words of the most High through the prophet,
'`Behold I will send for many fishers, says the Lord, and they shall fish them;
and I will send for many hunters, and they shall hunt them,
from every mountain and from every hill, and out of the holes of the rocks.`'
It was a very laborious, trying time,
and I did not feel that relief and comfort which I have done in some that are over;
however, there were, I hope, some tender minds;
in the forepart of my testimony I was led to open the state of a true
gospel minister and I heard afterward that several priests were present.
After dinner we rode to Amefsham,
which was a mournful ride to me--the land lies open and
dreary in these parts and without fences,
so also are the minds of many of the people.

"`30th.--Feeling no opening this morning to appoint a public meeting,
I attended the week-day meeting, which was a quiet comfortable time,
and I hope I was in the way of my duty: after dinner went to Uxbridge,
accompanied by William Hull.
I have felt myself little and solitary today.
My labours since leaving this place several months ago,
though they were heavy in the north, yet yielded me peace;
and now they appear like a dream.
O what sorrowful moments, may I not say hours, have I passed at Uxbridge,
and now am again here, a poor, helpless servant;
unless my Master is pleased again to give forth the word of command,
and freshly anoint and appoint me to his service.
I desire to trust in the Lord, who has been my helper hitherto,
and endeavour to do my allotted duty,
that so I may be favoured to dwell in the land of spiritual life,
and be fed with food convenient for me.
It has been a dull time with me of late--what next--and where next?
is the language of my soul.
Is a further baptism necessary to fit me for further labour?
O the mystery of that way in which a true gospel minister is led and fed.
I hope that at least I desire to be still rightly led about and instructed.

"`Twelfth month 3rd, first-day.--To meeting in very great strippedness and poverty;
and got some relief by unfolding some of my prospects in a close line.

[.offset]
From a letter received from his friend David Brooks, of North Carolina,
dated twelfth month, 1797, to whom he looked up as a father in the truth,
the following extracts are taken:

[.embedded-content-document.letter]
--

I received your cordial letter, dated first month 31st,
1797,--I had then obtained a certificate to come northward,
and was just coming out of the furnace.
I am now at Baltimore, and there appearing a favourable conveyance,
I felt free to inform you, that through mercy I am yet in the body,
and moving about in the exercise of my small gift.
This town has lately been visited +++[+++with the yellow fever]
by Him who remains to be terrible in judgment as well as glorious in holiness,
and fearful in praises.
I meet with a remnant in my passing up and down, with whom I have sweet fellowship,
and sometimes can join them in weeping, as between the porch and the altar,
under a painful sense of the poor, languishing state of the church, with a mental prayer,
that the Lord may yet pity his people and spare his heritage.
I am often led down into suffering with the pure seed which lies under oppression,
and have to speak a word of comfort to the mourners.
Dear Charity Cook, I expect is by this time on that island, +++[+++Great Britain]
and if you meet her remember my kind love to her,
and let her know she has had my sympathy.

Dear friend, the length of time, and the distance of the way we are separated,
only serves to strengthen the bond of gospel love, in a measure of which I salute you,
with desires that we may always wait at wisdom`'s gate to feel the fire burn,
and the offering prepared and sanctified:
for the main-spring that moves everything into action
which meets with the approbation of the great Shepherd,
who bled for the flock, is in many places very low and weak;
and we well know that nothing but the genuine product
of his own spirit can ever promote his glorious cause,
in which I trust we have embarked.
Many in our land remember you with great sweetness.
Your letter was seasonable and comforting to me,
coming at a time when I was ready to cry out in
the bitterness of my spirit as Elisha did,
when he returned from following his master, who was taken up in the chariot of fire,
and smote the water with the mantle and cried out, '`Where is the Lord God of Elijah?`'
Where is that power which cut Rahab and wounded the dragon,
and caused the prophet Habakkuk to tremble, and his lips to quiver?
Glory be to Israel`'s King forever,
our trials are often sanctified to our growth and experience in the truth:
farewell--approve yourself to be a workman in the holy building,
that needs not to be ashamed.

--

"`4th.--I felt easy to go to Tottenham this morning, and found Thomas Horne better.
In the evening a religious opportunity occurred in his sick chamber,
in which it seemed to me his removal would not be sudden,
and I thought there was yet some further work for him to do, which I expressed.

"`6th.--This morning I could not help giving vent to my tears,
both in my chamber and after coming downstairs, and got a little relief.
These things appear too mighty for me;
and really I fear sinking into such a low spot as to
think too little of past labours and services;
for surely I must have been helped with a little help from on high,
to go through what has been my lot of late months.
O, I could fall prostrate and say, Lord forgive,
sanctify and help me over my difficulties.
'`Surely it is right to be said unto God, I have borne chastisement,
I will not offend any more.`'
'`That which I see not, teach me, and if I have done iniquity I will do so no more.`'
But ah! who can adopt the last expressions?
it is the Lord alone who can enable any to do it.

"`7th.--Went to the monthly meeting at Tottenham,
and to my admiration I felt an opening to religious communication.
The meeting for business was truly a very distressing one; duty neglected brings poverty,
and what is worse, death.
I hope I laboured honestly.

"`8th.--A wakeful and thoughtful night, and I scattered my tears this morning:
when I look on the right and left, and forward,
it seems as if both Friends and the people at large,
are wrapped in a thick cloud that I cannot come at them, as to any religious service,
and the weight of oppression that lays upon me is great.
I endeavour to be cheerful at times, and do not show much of my feelings to others,
and yet am ready often to say, what shall I do?
'`I am oppressed; I am distressed; O Lord leave me not,
but condescend to wash and cleanse, and undertake for me.`'
'`Give ear to my prayer, O God, and hide not yourself from my supplication.
Attend unto me and hear me--I mourn in my complaint, and make a noise,
because of the voice of the enemy; because of the oppression of the wicked:
for they cast iniquity upon me, and in wrath they hate me.
My heart is sore pained within me, and the terrors of death are fallen upon me;
fearfulness and trembling are come upon me, and horror has overwhelmed me.`'

"`9th.--Took a lonely walk after breakfast,
and on hearing that the vicar of Tottenham is ill,
I could not be easy without calling to see him.
His wife came downstairs, and was much agitated and affected.
I told her that hearing of her husband`'s illness, I felt love towards him,
and could not be easy without calling in, and wished to see him, if it was agreeable.
She went up, and after awhile returned, and excused my seeing him at this time,
but wished me to call tomorrow.
I told her I felt a motion of love in my heart,
and found it right to attend to such intimations,
and if I felt the same concern I should call again, and so came away.
I felt a degree of sweetness attending this manifestation of duty, although in the cross:
on returning I met Joseph Bevan and Richard Chester,
the latter I informed of a prospect that had been at times on my mind to go to Hartford,
and have a public meeting; and that I thought of going tomorrow.

"`10th,
first-day.--How can I describe the pangs of exercise and conflict that I felt last night.
When I awoke I thought I would endeavour as much as
possible to forget and leave the things that are behind,
and felt a little more composed.
Went to meeting under exercise, much humbled,
and again had a very close and searching testimony to bear.
I was glad to feel the stirrings of life even in this trying way;
and afterwards prostrated in prayer for forgiveness of sins,
and for the blessing of preservation.
O that more in the meeting had felt as I did!
Before dinner I could not feel easy without offering
another visit to the parson near Thomas Horne`'s,
whom I went to see yesterday, and had not admittance, but now went up into his room,
and told him what was on my mind; he received the visit kindly, and I felt peace.
After dinner got to Hartford about five o`'clock,
and got through the meeting there to satisfaction; and laid down more comfortable.

"`11th, second-day.--I hope I can say my soul was humbled on waking this morning,
and desirous of renewing my covenant with my God.
After a while company came in,
but I felt as though I could retire alone and prostrate myself,
rather than be in company.

"`12th.--A stormy, rainy morning, and my eyes are not open to see the way I am to go,
and have been labouring after contentment.
Through favour I have a more quiet mind.
O what a lesson to learn.
Your will be done.
It was the subject of my communication on first-day evening among the people,
and may I be favoured more and more to learn it myself;
then I humbly trust my bonds will break, and my chains be loosened in due time.
A number of Friends came and drank tea with us.
I sat with them in silent conflict and sorrow.
I was glad to retire,
and spent the remainder of the evening in reading William Penn`'s works,
which were sweet to my taste;
and had also some religious conversation with the son of this family.

"`13th.--'`Who is so blind as your servant:`' if I am one of these,
it is my duty surely to be content;
for what greater honour can be paid to a master
than submitting to his will in all dispensations.
Went to the week-day meeting, where I begged for condescending mercy,
that all my giving way, or flinching in my trials, even in thought, might be forgiven;
and when it appeared nearly time to break up,
I feared to leave the meeting without telling them that
my soul had been let down into the deeps,
and that I had seen a time when husband would have to take leave of wife,
and wife of husband; a time such as that spoken of formerly,
'`Rachel weeping for her children,
and would not be comforted because they were not;`' and I
called on the youth to renew their covenants with the Lord.
I remembered also, and told them, what an enlarged, open time it was to me,
the first meeting I was at in this place,
and that I did believe there was then present a precious seed,
that the good Master saw fit should be visited; and now had to call some to mourning,
as the true way to a state of rejoicing.

"`When I sat down it appeared as if a little shower or cloud had emptied itself;
so much tenderness appeared.
I hope some were baptized, and I left the meeting more lightsome and easy.
Dined at Robert Manners`'; and the way seemed to open to move on to Chelmsford.
O the very deep plunge my poor soul had there when visiting Essex,
and I think it is the only place where I had not a public meeting;
but I sat the meetings on first-day morning and afternoon in silence.
O Lord,
may I still entertain a hope that it is your wisdom and
power that is leading me about and instructing me;
my soul craves ability to look up to you,
and if you ordain yet greater trials of my faith and patience,
grant your servant strength to say.
Your will be done.

"`14th fifth-day.--Set off early this morning,
accompanied by M. Phillips and James Brown, to Chelmsford.
Went round by Waltham Abbey and Epping, and found the waters very high;
passed by one house on the way to Epping surrounded by water.
Reached Chelmsford between three and four o`'clock,
where we stopped at Robert Greenwood`'s, and I desired Friends to be sent for;
several came, and I told them my wish to have a meeting in the morning at ten o`'clock,
to which they made objections, saying it was market day.
After night, several country Friends came in, with some others,
and began to talk again about the meeting, which I found they had not begun to invite to,
except one young man, who willingly engaged in it,
and had rode seven miles out and back to inform a family.
I was told that it was not likely the people would come,
and there was a fear that Friends would not,
but if I was not easy to have a meeting after market, in the afternoon, they would try,
but the neighbours were not very free to come, etc.
This cast a damp on my prospect,
and after sitting some time in silent thought and conflict,
I told them the prospect had left me, and I must wait until morning, and so we broke up.

"`15th, sixth-day.--After breakfast I felt easy to move on,
and got to the ferry opposite Gravesend, twenty-three miles, about three o`'clock,
but could not get over until night, and then rode seven miles to Rochester.
Lodged at Dr. Cowper`'s, who with his wife and sister received us kindly.

"`16th.--Yesterday I had thoughts of going to some further meetings, but now it closed up.

"`17th, first-day.--Sat both meetings in silent conflict.
In the evening went to William Rickman`'s and drank tea,--soon after which I
felt a little to communicate to a state among the youth present,
as I apprehended, and while I was trying to get the little company still, others came in,
and had like to have prevented me; however, I measurably relieved my mind,
and then went into the school room, and had a pretty full time with the boys.
I ventured also to kneel down and pray for the raising up and sending forth of labourers,
even from among them, to lands afar off,
afterwards had a comfortable time with a few young people.

"`19th.--Went to William Rickman`'s and spent some time;
after which took a walk for health.
I also went to see several persons, and at some of the places had religious opportunities.
In the evening my mind became exercised to speak to the company,
and I was much turned towards the doctor`'s assistant, a gay,
but apparently a goodly young man.

"`20th.--Very stripped and poor,
and I have need to exercise the little faith and patience left.
I dined at home, and took a lonely walk along the river.
O the oppression and death that I felt.

"`21st.--I concluded to set off this morning for London;
when I drew near and was entering it,
language fails to express the pangs of my travailing soul.
'`Who shall dwell with devouring fire?
Who shall dwell with everlasting burning?`'
I remembered what the royal Psalmist says; '`You will not leave my soul in hell.`'
And at times of late I have been ready to query in myself,
is there such a thing possible as to live without faith and without hope?
Surely when the latter is deferred it makes the heart sick.
Shall I ever more be favoured to witness the annexed part,
'`When the desire comes it is as a tree of life.`'
I seem as if I knew not what to ask for, without it is patience to bear all,
and yet to hope all things.
O may a poor, tried creature say,
will it not be better to lay down the life of this body,
for many spiritual deaths have been my portion,
than to live to dishonour the noble and eternal truth of God, which my soul has espoused.
Lord, do according to your wisdom and mercy;
and O that you would be pleased to enable me to finish your work,
and if more suffering be allotted, that it may be for the seed`'s sake;
and preserve your servant, O God.

"`24th.--Went to the burial of Foster Reynolds,
and I do not remember when I felt more free from this load of oppression and death,
that has so much pressed upon me, than on the road this morning.
I felt a living motion in the meeting, and rejoiced in it,
to minister in a very close manner; and after George Dillwyn had also been engaged,
I bent in supplication.
After dinner had a singular, and I trust,
profitable opportunity with the children and other relations at the house of the widow.
Some sweetness has been infused in my bitter cup,
and I receive it with gratitude and thankfulness, at my Lord and Master`'s hand,
and beg for becoming patience to bear all things, and hope all things in time to come.
I feel an awful calm and solemnity now in being alone.
O sweet resignation! what a favour to receive the counsel of God.

"`25th.--Rode to London with Thomas Shillitoe,
and got there in time to attend the select quarterly meeting.
I felt a sweet calm and composure on the way,
and was very closely exercised in the meeting; and yet cannot say I felt fully relieved,
although pretty comfortable.
Went home with my kind friends, John and Tabitha Bevan,
and after dinner had an encouraging, open time in communication,
especially to the children.
O how desirable to be guided in the midst of the paths of judgment and truth.
I have my fears, and may they beget a care, and preserve in it.

"`26th.--To the quarterly meeting,
and both in the first and second meetings I had close and searching things to deliver.
O my Lord and Master, you favoured me a few evenings ago with a precious calm,
and the opening of vision again, in which moment my soul reverenced your name;
and you gave me boldness and assurance to plead your cause once more this day,
giving me to see you had not forsaken me, in which my soul rejoiced.
O continue the blessing of preservation, and open the way further to labour in this land,
if it be your will, that I may experience peace in the end.
My beloved friend Susanna Horne came into the men`'s meeting and spread a concern
before us to have a meeting appointed for the youth tomorrow at ten o`'clock,
which was united with, and afterwards prayed for us; the Lord answer the petition.

"`27th.--On awaking, and before leaving my chamber,
my prayer was for preservation and help this day.
Went to the youths`' meeting, which was large,
and the Friend who was concerned to appoint it, was largely opened for a strippling,
and favoured, I trust,
with sweet peace in an honest discharge of duty--a share also fell on me,
with a few expressions also from several of the youth,
and I hope and trust it was a solid, instructive time.
If it is your blessed will, O Lord, again to exercise your servant,
gird him about with strength sufficient for the day;
for you have enabled me to set up my Ebenezer once more this day, in a public manner.

"`28th.--This morning a prospect of duty was renewed to
hold a public meeting in the evening at Westminster.
I went, accompanied by Joseph Smith, and sat with them in their week-day meeting:
George Dillwyn and Sarah Fairbank were there,
and it was a season of encouragement to the weary travellers.
The meeting in Westminster meetinghouse was large, and I thought but a low,
laborious time;
I could not be easy without inviting the people to come
and set with us on first-day morning next.

"`29th.--To Clerkenwell meeting for the school children.
Here, as often before, I felt openness and some enlargement,
and hope my confidence was renewed,
and also a willingness to trust my divine Master in the future stoppings along in life,
to dispense whatever may be consistent with his will and pleasure;
if I may but be accounted worthy rightly to suffer,
and with humility and fear to rejoice.
Appointed a meeting to be held here this evening.
Went and dined with Joseph Savory`'s daughters, and believe I was in my place,
having a tendering, and I hope, an instructive time with them.
A large meeting at six o`'clock, and it was an exercising, laborious time,
but Friends thought truth gained the victory; the people were quiet at the close,
and departed so.

"`31st, first-day.--I am going to Westminster meeting,
having invited the people to come and sit with me.
O for sustaining help to part with my own will, and be given up to the divine disposal.
The meeting was pretty large, and a solid time; and I invited them to come again,
not to hear preaching, for I told them I could not do that;
but such as were free to come at six o`'clock in the evening, it would be pleasant to see.
Dined at Ann Fothergill`'s, and afterwards had a religious opportunity.
The meeting was held long in silence, and was thought to be a solemn one;
and towards the close, a time of instruction in religious communication,
and the people departed very quietly and solid.
