== Chapter X

In a letter to his son, dated Waltham, William Dillwyn`'s, tenth month 13th, 1798,
he says:

[.embedded-content-document.letter]
--

It is now more than six months since I last came into London,
and I have been there and near it, most of the time since, and perhaps I may say,
that I never experienced a more humbling, trying dispensation; no way opening from hence,
either to any part of the kingdom which I have not visited, or to go home.
I humbly trust I am as a servant in waiting;
and if my heavenly Master is pleased to accept of suffering, buffetings, siftings,
and deep and close trials, as work done, or as filling up my measure,
then there is a hope that joy will spring up in the morning,
after the night of darkness passes away.
My mind has been turned toward you for months past,
and as I looked out of my chamber window this frosty morning, I thought,
how is it in Philadelphia?
have hundreds been numbered to the grave?
has the cold hand of death been laid on my family and relations,
or is the sickness once more removed by frosty weather?
I have earnestly laboured for months past after a qualification, morning by morning,
and often with tears of exercise and conflict, to say, '`not my will, but yours, O Lord,
be done, respecting me and all that appertains to me;`' and here I have left you,
under the care and protection of Him who numbers the hairs of our head,
and without whose notice not a sparrow can fall to the ground;
and if he is pleased to permit me to see and enjoy you in a state of mutability,
any or all of you, I have said in my heart,
it will be a mercy--a favour to be acknowledged;
and if otherwise,--if the all-wise and merciful Being
is pleased to take any of you to a better place,
even a more enriching and enduring habitation.
His will be done.

I salute you with tender solicitude and love, desiring to hear from you soon,
and have yet a hope in due time, of seeing the way open with clearness to return.
Time is the Lord`'s, and through all I hope he has not cast me off from being his servant.
Blessed be his holy name, my soul yet craves ability to glorify him, even in the fires.

--

"`14th, first-day.--Joseph Smith accompanied me to Devonshire meeting.
I felt very low on going, and for some time after I sat down in it;
but life and strength arose,
and I had a pretty open time in ministering to a state under trials and temptations.
Near the close an opening to the people at large presented quite unexpectedly,
and I was favoured with cheerfulness and resignation to give up to it,
and appoint a meeting at six o`'clock.
In the afternoon meeting was silent.
At the appointed meeting I was favoured with a comfortable relieving time.
How wonderful are the works of God in leading, instructing and feeding his messengers,
and qualifying them to speak to the people.
I was favoured to give up immediately, without consulting with flesh and blood,
to the holding of this meeting,
and had amongst other things to speak of Paul`'s so yielding to the heavenly vision.

"`30th.--Another humbling, heart-searching, heart-breaking morning.
The gathering of manna is a daily work; and if I can be enabled to say,
'`Your will be done and not mine,`' morning by morning, and evening by evening,
this is manna enough.
This has been a day of sorrow, and yet may I be truly content,
or as much so as such a poor creature dare to look for.
'`I cry unto you, O Lord, and you do not hear me: I stand up, and you regard me not.`'
'`You lift me up to the wind; you cause me to ride upon it, and dissolve my substance.`'
'`When I looked for good, then evil came unto me: and when I waited for light,
there came darkness.
My bowels boiled, and rested not: the days of affliction prevented me.`'
How descriptive of a state of desertion, seeming desertion to us.
Even our adorable High Priest cried out in agony, '`My God, why have you forsaken me?`'
and again at another time, '`I know that you hear me always.`'
Why may we not believe, that by and through the intercession of so great a High Priest,
our prayers and our secret cries are heard and noticed.
Lord, I believe, help my unbelief.

"`31st.--I crave to be favoured to know an increase in this experience;
to be careful for nothing, but in every thing with prayers and supplications,
with thanksgiving, to let my needs be known unto God.
Notwithstanding all I meet with, there is abundance to be thankful for.
Lord, forgive me my frowardness and uneasiness in this sifting, proving time;
wherein my faith and confidence in your protection and care have indeed been proved.

"`Eleventh month 2nd.--I remembered these expressions of afflicted Job,
on lying down this afternoon; '`terrors are come upon me, they pursue my soul as the wind,
and my welfare passes away as a cloud,`' etc.
In the evening T. H. brought me a letter from E. Cadbury, to Joseph Smith,
enclosing a paragraph of a letter from her sister, at Burlington, giving an account,
that my wife, son and daughter Mary had had the yellow fever.
My dear Mary closed her life on the 3rd of ninth month in the morning;
and it was thought my beloved Sarah and son Joseph were on the recovery.
I trembled when the letter was put into my hands to read;
having had a hint of its contents before from my friend.
After pausing a while, took it up again, and made another attempt, but failed,
and got M. Horne to read it to me.
My dear friends fell into silent sympathy with me,
and I not only thought with afflicted Job, but expressed it;
'`the Lord gave and the Lord has taken away; blessed be the name of the Lord.`'`"

[.offset]
The following extracts from a letter from Rebecca Jones, dated Burlington,
ninth month 26th, 1798, will give some further particulars:

[.embedded-content-document.letter]
--

[.salutation]
My beloved friend and brother,

It came into my mind this morning, feeling you preciously brought into view,
to spend a little time in thus communing with you.
I find by accounts lately received from England by several Friends here,
that you as yet do not find a door of escape from the arduous field,
in which you have been engaged honestly to labour upwards of four years,--so that,
though we are looking for the return of dear William Savery,
(who has professed himself clear,) our expectation and
hope is suppressed concerning your returning with him.
Fervent is my solicitude on your account, dear Thomas, that your sheaves may be full,
whenever the Master may be pleased to say to your exercised spirit, '`it is enough,
go in peace.`'
Dear Sarah Harrison, we hear, is unexpectedly drawn towards Germany,
and Mary Swett with her; this will be a fresh trial of faith and patience to her,
and to her beloved husband: if you write her, do hand to her and Mary Swett,
the salutation of my endeared love.

You wilt hear by other letters,
that our city has been permitted once more to
feel the dire effects of the contagious disease,
which carried off so many in 1793, and again the last year.
This then is the third stroke of the kind, and by all accounts,
more severe than the two preceding, by which many are numbered to the silent grave,
both in our city and in New York, where also it spreads rapidly.
Chester and Wilmington also are under the same humbling hand.
From all these places, the greater part of the inhabitants removed early:
but of those who remained, many have died, though many have also recovered,
and some of these left their homes soon after.

As you are more qualified to enter into our feelings than some others,
by having been amongst us in the year 1793, I need not say a great deal on that head,
and yet it will excite the tribute of gratitude
and thanksgiving to the Father of mercies,
to know that your dear wife and son,
and several other Friends who are near and dear to us,
have been safely brought through the disease: several known to you in New York,
as well as Philadelphia, etc. have fared otherwise;
concerning several of them it is sealed upon my spirit,
that they have in a state of innocency, and measurable preparation of soul,
passed quietly out of this vale of tears, into a joyous eternity of bliss and happiness.

The time for holding our yearly meeting in course, is this week;
but so few Friends are in the city, and the disease is so very heavy,
that a few of the representatives met last second-day,
and have believed it best to adjourn to the second week in next twelfth month;
and their so doing has been truly relieving to the minds of many Friends in the country,
as well as citizens that are out.
Yet, that there should be so solemn and trying a cause for it,
is deeply affecting to many of us,
who see with awfulness the renewed judgments of the Almighty displayed,
and still have reason to fear the people in general are not learning righteousness!
But the subject, my dear friend, is too heavy for me to enlarge upon at present.

I spent second-day at your father Hoskins`',
and found your dear Sarah and your aged mother,
who though much weakened in her faculties, is innocent and in good health,
so that it would have been quite pleasant being with them, but for thinking of you,
and that your mind would be affected when you hear the sequel of the account,
that your precious daughter Mary is removed to a better inheritance.
She did not lay many days struggling with the disease;
her dear mother laying ill at the same time, was not acquainted with the solemn event,
until she gained a little strength, and then bore it like a Christian,
as I much desire and believe you wilt, though nature will feel on the occasion.
I believe your dear child was in a state of innocence,
and I had several times of late noticed her improvement
in solidity as she advanced in growth,
nearly to the stature of a young woman; and her tenderness for her dear mother was such,
that though they wished her to stay at Burlington, where she was a few weeks before,
she entreated them to let her go and be with her connections in the city.

My desire is, that this circumstance may not improperly affect or discourage you,
so as to prevent your proceeding with diligence to finish what
appears to remain of the work given you to do;
which when completed,
your dear connections and friends will rejoice to receive you again amongst them.

[.signed-section-signature]
Rebecca Jones.

--

[.offset]
The reader will also be interested, it is thought,
in the following additional remarks from another hand:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Burlington, ninth month 30th, 1798.

[.salutation]
Dear Cousin:

It is from a renewed feeling of best love, I trust,
that I am engaged to address you in this way, though in weakness.
Frequently during your absence from this land, I have in my small measure,
affectionately sympathized with you in your arduous
engagement to promote the reign of peace on earth:
And although from a fear of improperly intruding upon your attention,
I have hitherto been deterred from writing,
it is not the first time I have had it impressively on my mind.
However sensible, that to me belongs blushing and confusion of face,
in the prospect of multiplied defections from the right way of the Lord,
and this more in the way of secret faults,
and what by some might be esteemed things of no moment,
than of open violations of the law and the commandment,
yet being through the mercy and loving kindness of the Father of us all,
at seasons quickened to an ardency of desire,
that I may more and more aspire after further attainments in,
and a deeper acquaintance with the work of sanctification in the soul,
I have likewise felt a degree of solicitude,
that thousands who are yet strangers to the blessed
principle of light and grace inwardly revealed,
may not only be brought to behold its unspeakable excellency, but to close in with it,
and become subject to its blessed government.

Hence I have found my heart to flow with love inexpressible towards those who are
called conspicuously to hold up the standard of righteousness to the nations,
and publish the glad tidings of the gospel to near and to distant lands.
It has appeared to me a time of great commotion in the world,
perhaps unequalled by any which has existed at any former period;
not only wars and rumours of wars mournfully prevail,
but opinions and systems which have not the stamp of irrefutable certainty,
are made to totter on their bases; the chains which have enslaved men`'s minds for ages,
are measurably loosened, and unlimited freedom of inquiry, spreads far and wide.
It is however to be lamented,
that the spirit of the age has extended too far into the other extreme;
and instead of bigotry and superstition,
unrestrained licentiousness seems ready to overwhelm the people,
and to lead them still further from the knowledge of the true God.
Nevertheless,
I believe that the faithful are at seasons favoured to behold a divine hand through all,
and that it is the gracious intention of the all-seeing One,
to bring about great and marvellous acts:
and O! how important has it appeared in my view,
that the professors of Christianity every where, more especially within our pale,
withdraw themselves from every thing that defiles,
so as to exhibit to the world in its native dignity and purity,
the peaceful nature of the religion of Jesus;
thus becoming instrumental by the sufficiency of his grace,
to promote his work and advance his kingdom.

And beloved cousin, however deep the baptisms, and closely trying the exercises,
which those who are sent on the Lord`'s errands in this day have to undergo,
yet I have thought, that over and above the secret sustaining support which never fails,
even in times of the greatest extremity, there is great encouragement to such,
in the reflection,
that it is a day in which way is making in the hearts
of many for a more ready reception of the truth,
and wherein its messengers may be more distinguishedly
instrumental in bringing people home to its saving efficacy.
Is it not to be supposed,
that notwithstanding the vast strides which vice and profligacy have made,
the number of those among various classes is great,
who seeing the fallacy of mere forms and creeds and professions of religion,
are led to seek after something that will afford their
unsettled minds real consolation and support?

The sound of war which has so long disturbed the tranquility of Europe,
has at length also reached our borders;
whether it will be permitted to increase to any very alarming degree,
is not for us at present to know; but be this as it may,
we have awful proof that the Majesty on high,
can use other means for the punishment of a gainsaying and backsliding people.
Poor Philadelphia is a melancholy instance;
again has the pestilential cloud broken upon her;
again have her streets become almost desolate, and the voice of sadness is heard therein.
The yellow fever in its highest malignancy has
now prevailed`' there for nearly two months,
and it is generally allowed, to a pitch far exceeding the memorable year 1793,
so that notwithstanding the citizens have, in a more general manner,
left it than at any former similar period,
the number of deaths considerably exceed that of '`93, within the same dates.
New York is at this time, and has been for several weeks past,
in a situation not far behind it in distress,
and the desertion thereof by the inhabitants nearly as extensive.
Boston has likewise had a share of the calamity, though in a less degree;
also Portsmouth in New Hampshire, and New London in Connecticut.
At Chester and Wilmington it has raged, it is thought,
proportionately to the number of inhabitants, at least to a degree equal to Philadelphia;
and at several places, both in Pennsylvania and this state, it has made its appearance.
Thus you wilt perceive,
in what a solemn manner the sword of chastisement has again been unsheathed,
and ah! that it may be effectual to humble the haughtiness of man--to show
the children of folly and disobedience the emptiness of every mundane hope,
and induce them to repentance and amendment of life.

Among a large number of fugitives that have come here for shelter,
are about twenty Friends`' families, among which is our beloved Sarah Scattergood,
with your mother, Joseph, Rebecca and the young woman.
You wilt no doubt, by other channels, be informed of many particulars respecting them,
but I apprehend it would be right for me to attempt to communicate something,
and indeed this is a principal motive of my writing at this time.
They remained in the city until within about two or three weeks of the present time,
and experienced a most trying, exercising season;
for although it appears they were favoured with a
remarkable degree of staidness and resignation,
yet the consideration of what would be best for them,
relative to staying or leaving town, became a close trial.
This will best appear by a letter which I received from your precious son Joseph,
whose conduct during this dispensation of divine Providence,
has been comfortably rejoicing to his friends;
I shall transcribe a part as follows:--"`Eighth month 28th.--Having a short
space of time to spare previous to the gathering of our meeting this morning,
I thought I could do no less than acknowledge the receipt of
your truly affectionate and sympathizing lines.
To be apprised of the remembrance and love of our
friends at such a trying season as the present,
is peculiarly grateful.
Mother also received a letter from aunt Mary Newbold,
expressive of the strong desire of our friends for our retreat from the city;
it was put into her hands just as she was going into select meeting yesterday,
after which we were both at grandfather Bacon`'s,
and he strongly recommended a compliance with the request.
While we were engaged on the subject,
uncle Jonathan Evans came in and earnestly joined in the same sentiment,
acknowledging he had been some time uneasy about us, and wished much that we were gone.
After all that, the matter seemed to devolve solely upon ourselves,
and mother passed through an afternoon of exercise,
and perhaps I may venture to say I was not altogether void of feeling on the occasion:
no strength was afforded to engage in the business.
Well, dear cousin, I feel it to be a time of uncertainty with us,
and my heart and eyes are frequently afflicted
when I contemplate the scene that is around me;
I now feel more than I have language to express,
so must affectionately bid you for the present, farewell.`"
A note at the bottom of the same letter, says:
"`Since closing the foregoing I went into the house and found mother in bed with a chill,
etc.: if you think it will do,
mention it with caution--thus trials are multiplying fast upon us.`"

While at meeting he began to be unwell himself,
which terminated in the prevailing disorder, and Mary was taken down about the same time,
so that indeed they became a very afflicted family.
But yet they were not forsaken or neglected; the faithful woman who lived with them,
and who did not take the disorder, was very attentive and useful in taking care of them.
Also Edward Garrigues and Nathan A. Smith, evinced on the occasion,
as well as many others during the calamity, a truly Christian tenderness and sympathy,
providing them with nurses, necessary things, and visiting them daily.
Joseph had a pretty smart turn of it,
yet his symptoms were thought to be rather of the more favourable kind;
but cousin Sarah and Mary were severely attacked,--the first
lay several days so low that her recovery seemed doubtful,
and when she arrived to a state of convalescence, she acquired her strength but slowly.
But lovely, innocent Mary--how shall I speak of her!
I feel near sympathy with you on her account, and yet you well know,
that He whose dispensations are all in wisdom,
has a right to dispose of us as he sees fit,
and that when he inclines to take even such as are most near to us, unto himself,
it is rather a cause of rejoicing than of grief.
After struggling with the disorder for several days,
she was taken from a world of temptation, to join, I trust,
the blessed in the realms of purity and love.
We are sweetly confirmed in this persuasion,
in remembering that her conduct and deportment of later time evidenced an improvement,
and that although her disposition was naturally volatile,
her mind was in a great measure kept free from the taints of impurity.
Consonant herewith is the opinion of Thomas Moore, a valuable religious young Englishman,
with whom I understand you were acquainted in England.

Being in company with him at Darby, where he at present sojourns,
our conversation turned upon your family, and speaking of Mary,
he remarked in substance thus, '`As I was sitting with the family,
a short time before I left the city, and observing her innocent deportment and solidity,
it rejoiced me to think she was improving,
and what a comfort she was likely to be to her father on his return.`'
An extract from another letter of Joseph`'s to cousin Rachel Hoskins,
directly after his getting out the first time, I am induced also to transcribe,
as follows:

"`Ninth month 9th.--Having arrived through favour,
at a state of pretty tolerable strength, I feel my mind influenced, I trust,
in best love again to address my dear cousin in this way,
I feel as if I could not enter into a very minute detail of the afflictive dispensation,
which no doubt in the ordering of best wisdom, has, within these two weeks past,
fallen to our lot; indeed I am ready to conclude it is hardly necessary,
as I have but little doubt you have received nearly every particular from
the pens of our truly kind and attentive friends E. Garrigues and N. Smith;
they have been indefatigable in their attention, by visiting us several times in a day,
and in procuring necessaries.
I hope and believe their reward is sure.
I got down stairs last fifth-day,
but was very weak,--have been mending fast ever since--got out this morning to meeting,
being the longest walk I had taken, but find myself not the worse for it.
When I first went out, I think there was not a person to be seen in the street,
and as I passed along my own footsteps sounded solemnly in my ears;
truly I thought that none but those who are actually on the spot could form
an adequate idea of the solemnity of the scene which our distressed,
depopulated city exhibits.
I have also the satisfaction of informing you that dear mother is mending:
yesterday was the first of her being apprised of the death of dear
sister Mary--she bears it with fortitude beyond what we expected;
her weak state would not admit of an earlier discovery.
The day of her decease was the first of my attempting to set up,
and though so weak as to be just able to move a little about the room,
I could not be easy without trying to get down to see her remains--which I effected,
and beheld them decently laid out; her countenance was exceedingly yellow,
but a pleasing innocence was fixed thereon, and an evidence seemed to possess my mind,
that she was taken from the evil to come, and out of the way of many temptations,
into those perpetually abiding habitations, where joy and peace forever dwell; therefore,
what excuse is there for mourning?`"

After cousin Sarah and Joseph had pretty well recovered,
the way opened for the family`'s coming to this place,
which was accomplished without much difficulty.
Her accustomed meekness and serenity did not forsake her in this time of affliction,
her mind being strengthened and supported by that Almighty Power,
who fails not to be strength in weakness,
and an impregnable fortress to which the righteous may flee,
and find safety in times of trouble; so that she might adopt the language,
(as dear Samuel Emlen told her in my hearing,) "`All
your waves and your billows passed over me.`"

--

"`21st. fourth-day.--To Peel monthly meeting, where dear George Stacey,
who returned last first-day from Germany,
gave in an account of his travels there with Sarah Harrison, Charity Cook,
and Mary Swett, and he being encouraged to go to the women`'s meeting,
I felt a liberty to go and set by him: and after he had given in his account there,
I felt a motion to kneel down and return thanks for their preservation,
and to pray that the Almighty might be pleased to protect all his
servants and messengers whom he has sent forth in this land.

"`22nd.--I feel deeply for the inhabitants of this city, and sorrow for them at seasons.
Attended meeting at Westminster with Mary Stacey,
where tears with anguish of soul were my portion;
until a young man kneeled down in supplication, and appeared dipped into my feelings;
and having before apprehended that duty would
fall on me before the conclusion of the meeting,
upon his closing I gave up to it,
and felt enlargement to pray for the inhabitants of this city, for the poor amongst men,
who have no helper but the Lord, and that if it was his pleasure, in unspeakable wisdom,
to humble and bend the sturdy oaks, he may be pleased also thus to manifest his mercy.

"`23rd.--This has been a day of retirement,
in which I have felt a comfortable degree of resignation and quiet;
and in reading the Bible, some passages in Revelations, etc.,
were more opened to my view than ever before.
I trust that in this deep plunging season for many months past,
I have had a degree of fellowship with the sufferers in ages past, such as, David, Job,
Jeremiah, etc., and also with my Lord and Saviour Jesus Christ;
and O how I should rejoice in being favoured once more with strength
to go forth and publish with the voice of thanksgiving,
and tell of the wondrous works of the Lord.
This I know the mighty One of Israel can accomplish in me and for me, if it be his will.
But, if it is his pleasure to strip me longer, and that I must yet remain desolate,
sitting on the ground, '`Not my will, but yours be done, O God,`' Pardon me,
and cast all my iniquities behind your back.`"

[.offset]
In a letter dated eleventh month 28th, 1798, at London, to his family, he says:

[.embedded-content-document.letter]
--

Great indeed has been the travail of my soul in secret for six months past.
I could copy many things from my little diary which
would convince my friends that I have not been idle,
and I have thought sometimes if it was my Master`'s good
pleasure to remove me from my troubles here,
the account of my time spent from day to day would witness for me;
for indeed I have been a mournful Jeremiah in and near London,
and but little can I do but weep, and wait for those days to be over,
and to hear this language, '`It is enough.`'
I have not drawn back from any labour which was clearly pointed out in my own land,
neither do I find this charge against me here,
though of late weeks it has been a time of as deep
searching of heart as ever my soul has experienced.
Yet after all, with deep humility I acknowledge I have not been faultless.
What a hard thing it is, when plunged into the deeps, to be content in the will of God.
What a hard thing for the unsubjected will, wit,
and reason of man to become a fool--one of no reputation.
Truly I have thought, my soul never was made so sensible of what the patriarchs,
prophets, and mournful sufferers in their day and generation passed through,
and of the agonizing pangs of Him unto whom the heathen was given for an inheritance,
and the uttermost parts of the earth for a possession,
who also gave his cheeks to the smiter, and his face to them that plucked off the hair,
who hid not his face from shame and spitting,
nor withheld his head from the crown of thorns, or his body from the cross;
and all this willingly for our sakes;
unto whom I beg ability to look up in all my struggles and trials.
My soul can say of late with the royal Psalmist, '`O Lord God of my salvation,
I have cried day and night before you; let my prayer come before you;
incline your ear unto my cry: for my soul is full of troubles,
and my life draws nigh unto the grave.
I am counted with them that go down into the pit: I am as a man that has no strength:
free among the dead, like the slain that lay in the grave, whom you remember no more,
and they are cut off by your hand: your hand lays hard upon me,
you have afflicted me with all your waves:
you have put away mine acquaintance far from me, I am shut up; I cannot come forth.`'

--

"`25th, third-day.--Awoke early this morning and arose more calm and quiet,
and I hope truly disposed to say.
Here am I, Lord, send me.
How precious to feel this even for a little moment: how comfortable in the outward,
after a storm of tossing and danger, to experience an easy breeze;
and so it is in a religious sense.
I have had days of tossing and trouble for many months past,
and now if it should consist with the will of the Lord,
to grant me some ease and liberty of spirit, how thankful ought my soul to be.
But it is not for me to judge: if more suffering is best,
I ought likewise to be resigned to say.
Here am I: Your will be done, my heavenly Master.
Keep your tried servant from falling.

"`Attended the quarterly meeting, which was very large;
and to my thankful and humble admiration, much labour fell to my lot;
my heart being opened and enlarged, both in testimony and in supplication.
The business was conducted comfortably, and the meeting ended so.
I felt a change in my situation last evening before I lay down,
and went to bed more calm and comfortable in mind,
when an opening presented of enlargement in the quarterly meeting,
which has now been fulfilled;
also the renewal of a prospect which has for some months been presented to my mind,
and then died away and left me; that is, to visit the prisons of this city.
This prospect seemed so fixed and sealed on my mind,
that I stopped some Friends after meeting,
and laid it before them for their concurrence and help in the arduous work.

"`26th, fourth-day.--Empty and poor this morning, but I desire to be so,
that I may be qualified to render up my will and affections unto my God,
that he may be pleased to guide my feet aright.
I desire ability to say, day by day, Your will be done.
Attended Grace-church street meeting and laboured in testimony.

"`28th.--Spent this evening more lightsome and
comfortable than has often been my experience:
feeling resigned to whatever kind Providence may be pleased to permit; yes,
the cup he gives I am willing to drink.
Lord, bless it, sanctify it, and preserve your servant over and through all.
O preserve me to the end of my days,
and grant that in passing through tribulation and distress here,
I may wash my garments in the blood of the Lamb.

"`29th, seventh-day.--To a meeting appointed for the children of criminals,
at the Philanthropist Reform, there were about one hundred and two.
They were arranged in ranks before me, and stood.
It was an open time, and when I kneeled down in supplication they went down also.
Several of the committee who have the care of them, also the governor,
and the masters who teach the boys their trades, attended, and were kind and respectful.

"`After the opportunity we went to the girls`' apartment,
and had a pretty good time with about fifty of them.
Some were noticed to weep, and I left them relieved in mind.
Dined at Thomas Sturges`' with Joseph Smith and Wilson Birkbeck,
who accompanied me in this visit.

"`30th, first-day.--Joseph Smith,
Wilson Birkbeck and Thomas Sturges accompanied me to the House of correction.
Had an opportunity with about fourteen men in a dismal place--however,
it was relieving to my mind: the poor creatures behaved well,
and I was dipped into sympathy with them,
and hope it will prove a time of some profit and encouragement to individuals among them.
Some of them on parting sent their blessing after me.
Went into the women`'s room and had a satisfactory time with about eight or ten of them;
some of whom appeared tender: from there we stepped into a school for girls,
where there were about fifty, and I had a satisfactory opportunity among them.
After dinner endeavoured to obtain a meeting at the Asylum for poor orphan children,
but failed, and though I felt a great weight and exercise on my spirit on returning home,
as I frequently have done in walking London streets, yet after reading with the family,
I feel pretty comfortable and easy, for which favour I am thankful.

"`31st, second-day; and the last day in the year.
I had a comfortable night, and I awoke and arose so.
But O what a baptism I passed through afterwards! how is it possible to describe it,
except in David`'s words in the seventy-seventh psalm,
on which I opened in my distress upon taking up the blessed book to read.
O Lord, my soul is bowed down because of oppression.
Remember me and search me--let nothing remain unjudged,
that I may stand before you with acceptance,
and be accounted worthy to promote your cause and truth in the earth.
Help me through my difficulties; wean me from all letting and hindering things.
For your mercy`'s sake,
grant that I may leave that labour and toil that
has made me to walk uncomfortably in the way,
and lift up my heart to you in faith and confidence,
and give up in all things to do your blessed will,
that so I may yet be found doing your work in my day and generation.
Send forth the covering of your righteousness.
Strip me of all my filthy garments, and clothe your servant with a change of raiment.
You know the unutterable pangs of distress I have passed through for many months past,
and I humbly hope my soul lies prostrate in dust and ashes before you.
Restore unto me peace and comfort.

"`1799, first month 3rd,
fifth-day.--I have had occasion to praise the Lord for ease of spirit this morning;
that is,
if we are to rejoice in ease and quietness of
mind more than in dispensations more trying.
The cloud separates, and a little light spreads.
I desire to receive it with fear and trembling, for baptism, deep baptism is profitable.
Went to the new jail for the county of Surrey,
where I had an open time with about two hundred prisoners, much to the relief of my mind.
Went afterwards to the Clink prison,
where we found only two prisoners--a little arose on my mind for them.`"

[.offset]
In relation to this visit he remarks in a letter of this date.

[.embedded-content-document.letter]
--

This day accompanied by my kind friends, I visited the prisoners in the new jail:
a most extraordinary building indeed, I suppose we had all sorts, and truly I may say,
such was the love and desire I felt for them when amongst them,
and the enlargement of heart, that I forgot my own troubles,
and how long I had been as it were in the pit.
Tenderness was apparent in some, and a secret hope prevailed in my mind,
that the opportunity would be, at least to some, like bread cast on the waters,
found after many days.

--

[.offset]
He adds,

[.embedded-content-document.letter]
--

I expect and look for deep labour and travail before
the door will open peacefully to leave this city;
how far I may be engaged in this arduous work, or what will next open,
I feel disposed to leave to Him,
who marvellously leads the blind by a way that they know not,
and in paths they have not seen.`"

--

"`4th.--Attended the meeting for sufferings.
I am informed that the committee meet with much difficulty to obtain leave for me
to go into the prisons--and no more business can be laid out this week.

"`6th, first-day.--To Grace-church street meeting,
low in mind but had to labour once more in a close line.
Appointed a public meeting to be held at six o`'clock in the evening.
Attended afternoon meeting at two o`'clock,
and a little arose on my mind to impart to the youth.
In the appointed meeting, which was large, I was altogether shut up.
Charity Cook preached early, and after a considerable time of silence,
dear George Dillwyn took the service of the meeting entirely off my mind,
and I felt content and easy.

"`10th.--I opened the Bible on Job, sixth chapter,
which is descriptive of my often tried state.
Charity Cook, Mary Swett and Ann Crowley paid me an acceptable visit,
in which my mind was comforted, and its burden a little removed.
Is then faith, even when no more than a grain of mustard seed, able to remove a mountain?
Yes, and it seems as though it was possible to live under the weight of a mountain,
when this little grain is hid out of sight; yet, if it is hid in the heart, it is enough.

"`12th.--A quiet day--a sweet calm spread over my mind while
sitting by the fire side of my kind friend Truman Harford.
I received a note from J. B.,
informing that they will not let me proceed further in visiting prisons.
I received the account with composure of mind, for which I feel thankful.

"`13th, first-day.--Went to Ratcliff meeting and had an open time in testimony.
I was much abased on going to the afternoon meeting, but a solemnity soon spread,
and I bent in supplication in a broken manner, with tears.
I prayed fervently for strength and ability to
drink the remainder of the cup of suffering,
even the dregs of it, in this city, and subscribe to the Lord`'s will.
M+++.+++ Ransom had a good time after; and before the meeting broke up, I was enlarged,
and much tenderness appeared.
Spent the evening in pleasant conversation, and lay down pretty easy and comfortable.`"

[.embedded-content-document.letter]
--

[.letter-heading]
David Sands to Thomas Scattergood

[.signed-section-context-open]
Dublin, First month 2nd, 1799.

[.salutation]
Dear Thomas,

My long silence has not been for lack of near sympathy, nor true brotherly love,
as I know of no brother that I am more united to in the bond of gospel fellowship.
Your last letter was the most satisfactory that I ever received from you;
nor do I think it could have been penned more suitably to my then situation.
You mentioned your deep trials,
in which you felt as though you were plunged into the
horrible pit and sunk to the bottom of it.
When I read this part of your letter I was filled with a mixture of sorrow and joy;
sorrow on your account, that your sufferings were so great, and joy on my own,
to find I had the company of so dear a brother,
travelling in a way I thought almost untrodden by any.

I may acknowledge that my trials since in Ireland,
have been like the loosening of new seals of the book of religious experience.
But hitherto I have been helped and carried through every afflictive dispensation,
and am at present in better health of body than when I first landed in Europe,
and find much greater openness amongst people of
every rank than when I first entered Ireland.
I have lately visited most of the towns and places where the
greatest destruction of lives and property occurred,
and found many seeking people, whose former rests appeared to be much shaken,
if not broken up; and with these I have had many refreshing seasons.
Public meetings are generally crowded by the better sort of people,
whose behaviour is very becoming the occasion.
I have also visited most of the families of
Friends where the greatest trials have appeared,
as Carlow, Ballitore, Rathangan, etc., and returned to this city a few days since.
What may open as the line of duty, I do not clearly see at present;
but as i did not visit all the families before I left this city,
I may likely do a little more in that way before I go to the northern parts the nation.

My detention in this land has been very trying to me,
as I seemed exposed to every kind of danger, not only by robbers and murderers,
confusions and tumults of various kinds, but by unfeeling professors,
who have greatly departed from the faith of their worthy forefathers,
and yet desire to be called the children of Abraham:
but I believe my trials of this sort are nearly over,
as many who have been hidden are now made manifest,
and of the more undesigning and simple hearted are favoured to see the snare,
and many have escaped from the wreck,
and I humbly hope all may be gathered into the faith once delivered to the saints,
and the prey be taken from the jaws of the devourer: but this must be the Lord`'s work,
for none but him can do it.

The general state of society appears to me but low,
yet there are many precious plants in Ireland, and I think their number will increase,
and is now increasing.
Many enquire after you with much affection and love.

I have heard of your late trial in the loss of your dear daughter,
and I believe do sympathize with you in that and other afflictive dispensations,
yet have not the least doubt but all those things that we meet with,
and which may seem little else to our taste than the wormwood and gall,
are but like the strong winds sent to bring the leaky ship to a safe port.
As I remember to have heard dear George Dillwyn say when in America,
to an afflicted Friend,
'`Our proper business at such times is to keep the head of the vessel the right way,
and if we did so, we should gain by such dispensations.`'
I have not heard much from America respecting the state of our Friends,
that I cannot tell who are removed or who are left,
but have heard of some valuable Friends being removed from works to rewards.
Having given you a sketch of matters,
I conclude in that brotherly love that many waters cannot quench,
and rest your affectionate friend and brother,

[.signed-section-signature]
David Sands.

--

"`19th.--Took post chaise and rode to Canterbury to attend the funeral of William Elgar.

"`20th, first-day.--To the burial house,
and accompanied the corpse along the street to the meeting-house,
which was much filled up with the town`'s people.
Here I met dear Richard Baker, who was pretty largely engaged in the meeting.
Tears were my food in the fore part of it,
and I was glad of the company and help of such a fellow labourer.
Near the close I bent in prayer,
and before the meeting broke up was most easy to appoint a meeting,
although in much weakness, to be held at six o`'clock in the evening.
We followed the corpse a long way through the city,
and a pretty long one out of the gate thereof; and a crowd gathered round the grave,
beside Friends, of whom there was a reputable company.
I laboured among them from these expressions; '`Fear God, and give glory to his name,
for the hour of his judgments is come,`' etc.
It was a quiet time, to Friends`' admiration,
for in former years there had been sad doings,
even to the pulling of ministering Friends down, etc.
I dined at the burial house,
and at the table I prayed that truth might not fall in the streets here;
and also for the son of the deceased, in a particular manner.
Afterward a large number of Friends came in,
and I was favoured with much enlargement of heart in speaking to them.
To the evening meeting, which was an open, solid time, and broke up so.
Supped at our lodgings,
and after it had an opportunity with the gay children of this widow,
who have gone off from Society.
After this day`'s work feel easy in mind.

"`21st, second-day.--Went to William Patterson`'s and visited his wife,
who is declining fast; here came Richard Baker, and we were favoured together, I hope,
with the breaking of spiritual bread.
Went again to the house of the deceased, and had a solid opportunity with various Friends.
Set off about one o`'clock in a chaise for Dover,
and met a very kind reception from the wife and children of Richard Baker.

"`27th,
first-day.--Set off soon after breakfast in a post chaise with R. H. and Richard Baker,
for Folkstone, where a meeting had been appointed, which was large and solid.
It was comfortable to visit a simple-hearted people,
and it seemed as if they were reluctant to break up meeting and depart.
Dined at W. M.`'s, and afterwards had a sweet, refreshing opportunity.
Went back to Richard Baker`'s, time enough to attend the evening meeting,
which was much crowded, and closed in a solemn manner.
I spent a sweet, refreshing evening after it at Richard Baker`'s,
where we had a religious opportunity, in which he appeared in testimony,
and I was engaged in supplication, with a thankful heart,
and lay down under this feeling.`"

[.offset]
In a letter addressed to his family, dated 28th of this month,
after informing them of the preceding meetings, he says:

[.embedded-content-document.letter]
--

Yesterday`'s labour and the sweet reward annexed, have set me up a little,
and I fervently beg support, not only to the end of this journey,
but to the end of my days,
and that the Lord may have the honour and praise of his own work,
in and by all his dedicated servants and messengers I
hear likewise of the decease of M. B.,
only son of M.,--he has, by account, left great concerns behind.
The last meeting I was at with him at Gilford, about nine or ten months ago,
was a memorable one to me; indeed,
I have often remembered the impression then made on my mind,
and which I had to express concerning some then present.
The uncertainty of visible enjoyments is often uppermost with me in this land, and,
my dwelling has been much, if may so express it, as among the dead.
'`Free among the dead, like the slain that lie in the grave, whom you remember no more,
and they are cut off by your hand.
You have laid me in the lowest pit, in darkness in the deeps.
You have put away mine acquaintance far from me;
you have made me an abomination unto them.
I am shut up, I cannot come forth.`'
This was David`'s experience in his state of affliction;
and I have often read him and Job in the line of experience.
But after all, this is the sum; I think I cannot, I must not,
be without such trying dispensations.
The Lord knows best what is best, and his sovereign, blessed will be done.

--

"`30th.--Attended an appointed meeting held in the town hall at Deal,
The people were slow in coming, and for a considerable time there were but few.
Richard Baker stood in testimony for some time, during which others came in.
Seeing a crowd near the stairs, and feeling love in my heart toward all,
I stood up and with considerable pains got them to come forward, and make way for others,
until at length the house was pretty full; and I was favoured with an open time.
In the afternoon rode to Margate, and met a kind reception at the widow Newby`'s.

"`31st.--To an appointed meeting in a large assembly room.
Richard Baker had the labour, and my share was in supplication,
and I felt most easy to appoint another at six o`'clock in the evening.
It was small, occasioned by a great snow storm,
and I was much shut up for nearly two hours;
but at length had a satisfactory time with such as met.

"`Third month 1st.--J. C. a fisherman and preacher among the Methodists came to see us,
with whom we had some satisfactory conversation: he is a loving, goodly man,
and proposed my having a meeting in their chapel this evening, which I declined.
After meeting last evening, another Methodist preacher came to me,
and I suppose was sensible that I had been disappointed
in not seeing so many people together as I desired,
and wished me not to be discouraged.

"`2nd, seventh-day.---Feeling easy with respect to this place,
I set off in a post chaise for Canterbury, and got to Dover about dusk.

"`11th.--To Folkstone to the burial of John Elgar at eleven o`'clock.
The new unfinished meeting house was fitted up with seats, and much crowded.
It proved an open time: several serious soldiers were present.
After dinner I had a remarkable religious opportunity,
in which the builder of the meeting-house was much tendered and reached.
Went to see the parents and children of the deceased, and had a comfortable opportunity.
Walked to the sea side and met with the mayor of the town,
who came to me in a kind manner, and expressed his satisfaction with the meeting,
and said he hoped it would be profitable, especially to the young people;
whose minds were uncultivated.
He is a goodly man.`"

[.embedded-content-document.letter]
--

[.letter-heading]
+++_______+++ to Thomas Scattergood

[.signed-section-context-open]
Holdgate, Second month 7th, 1799.

[.salutation]
Beloved friend T. S.

I trust our love and friendship is founded on a basis that admits of perfect freedom;
and in this persuasion I feel encouraged to address you at this season,
though not without the recollection of having already
demonstrated my continued remembrance of you,
since favoured with a letter from you.
But as the pure cementing union of gospel fellowship, far exceeds all ceremonies,
I shall not attempt much apology for the present mark of freedom,
but in simplicity and sincerity take this method of convincing my endeared friend,
that length of separation, either in distance or time,
has by no means erased him out of my memory,
nor caused any diminution of that love which first united our spirits.
I have, at seasons, felt near love and sympathy with your exercised mind,
so that notwithstanding many have been my own conflicts and probations,
yet I have thought, if it were possible,
I could joyfully take part of your burden on my own shoulder,
that your mind might in some degree be relieved.
I esteem it an unspeakable favour, to feel such a degree of spiritual union,
as to enable in some measure, to dip into fellow feeling with tribulated spirits.

I know nothing that qualifies Christian travellers to
sympathize with the tossed and afflicted,
more than a large degree of suffering themselves; because what we have tasted,
what our hands have handled, we can speak of experimentally.
These, and similar considerations, have at times,
encouraged me to labour after a state of contentment
and endeavour to bear all things patiently,
trying to believe in that blessed assertion; '`All things shall work together for good,
to those that love and fear God.`'
The last account of you furnished me with tidings of your
engagement in visiting the prisons in the city of London;
an arduous work for a feeling mind, who is coveting above all things,
the health and salvation of the souls of mankind;
and consequently must be dipped into a state of deep suffering
in feeling the great departure from purity and holiness,
and the degeneracy of the human race.
Oh! what cause is still administered by the deep revolting, backsliding professors,
for the Lord`'s exercised servants and ministers, to put on the garment of sackcloth,
weeping as between the porch and the altar, interceding with Omnipotence,
for the continuation of his merciful regard towards the workmanship of his holy Hand!

My soul is often bowed in humble contrition,
when I feel the deplorable state of those who are saying,
in the expressive language of conduct,
'`We will not have this man to rule over us;`'
remembering that the Lord has pleaded in mercy,
not only immediately by the revelation of his own pure Spirit,
but has caused the alarming trumpet to be sounded in Zion by his instruments;
and his judgments for transgressions declared on his holy mountain.

May not the language be adopted, '`What more could the Lord have done for his vineyard?`'
Surely he has dealt bountifully with his creature man;
but O how obvious are the returns of ingratitude,
instead of the dedication of the whole heart to
serve the King of kings with perfect obedience.
Are there not those in the present day who can say with the mournful prophet,
'`For these things I weep, mine eye runs down with water.`'
Though we are made abundantly sensible, that true religion is a heart felt,
individual work;
and that however solicitous we may feel for the spiritual welfare one of another,
it is not possible for any man to redeem his brother,
or give to God a ransom for his soul; yet,
how does the universal love of our heavenly Father,
so abound in the hearts of his disciples,
that they are made willing to spend and be spent,
in calling to repentance and amendment of life.
And if through the efficacy of the Lord`'s mighty power,
such are made instruments in his holy hand,
to turn one soul unto righteousness and holiness of life,
it will amply compensate for the labour, deep exercises and fiery baptisms,
which I believe accompany all those who are rightly qualified to advocate a
cause dignified with immortality and crowned with eternal life.

Well then, dear friend, may you and I put on strength in the name of the Lord,
and do whatsoever our hands find to do with all our might;
remembering that after having done the will of God,
we have need of patience to receive the promise.
I seem to feel so much of that love to flow in
my heart towards my beloved fellow pilgrim,
which leads to perfect freedom,
that I am almost ready to forget I am writing to a father in Israel.
Doubtless you have heard, before this period,
that my feeble frame has once more been reduced to a state of great weakness,
insomuch that my recovery appeared for a time very doubtful.
During the time of this affliction, my mind was mostly preserved in a state of calmness,
though I felt no great redundancy of heavenly good,
nor sensible feeling of the presence of Him whom my soul loves; but was enabled,
through holy help, to lift up my head, at seasons, in hope,
remembering that I was in the hands of a gracious Creator; and that it became me,
as a dependent servant, patiently to suffer his will, whether in life or death.
After my disorder took a favourable turn, and my strength a little increased,
the situation of my mind became very trying, so as not to be fully expressed in words,
or comprehended by the natural understanding but such a deeply exercised
mind as my endeared friend`'s may be capable of fathoming in degree,
what I have had to pass through, and in measure, am now wading under; when I tell him,
hope of salvation for mine own soul has hung upon so slender a thread,
that I have been near letting go my confidence;
uttering this language in the secret of my heart, '`Surely my God has forsaken me,
he has hid his face from me.`'
O the anguish of my stripped mind,
when not able to put up a single petition for the help of Omnipotence,
nor feel his protecting Arm underneath for my support; instead of this holy confidence,
I was temped to call in question all former experiences
of the Lord`'s gracious dealings with me,
apprehending I never was commissioned,
nor rightly prepared and qualified to preach the everlasting gospel.
The enemy of my soul`'s salvation, uses every stratagem to cast down below measure,
and thereby keep from serving the Lord with a cheerful heart, and willing mind.
I believe you can read me in the line of deep experience;
the consideration of which gives liberty for free communication:
for these are mysteries not understood to the full,
only by such as have trod in similar footsteps.

--

"`12th.--Attended the monthly meeting held at the new house, where several goodly people,
beside Friends came, and also two serious soldiers.
It was a sweet time, and these men were very tender.
I had also an open opportunity in the men`'s meeting.
After dinner the two soldiers came to us,
and we had a precious season with them on parting.
O what tenderness they evinced, and what sweetness and love was to be felt.
The Lord be praised for this manifestation of merciful regard.
Returned to Dover with Richard Baker and Sarah Talbot, in a post chaise,
and was at a meeting appointed by Sarah Talbot.
A few seeking people came in, and much solemnity prevailed;
and now after so many meetings of exertion my bodily powers are broken down,
and my voice much gone, yet the peace I feel is more than a reward for all.
Blessed be the name of the Lord therefor.`"

[.offset]
The following extracts from a letter addressed to Rebecca Jones,
though chiefly a repetition of his engagements, may not be uninteresting:

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to Rebecca Jones

[.signed-section-context-open]
Dover, Second month 13th, 1799.

[.salutation]
My dear friend,

Although it is some time since you have heard from me in this way,
you may rest assured I have not forgotten you: no, my beloved, sympathizing sister,
you have been as a seal on my heart in labours and travels,
watchings and tears in this land,
and I now feel a little strength and willingness once more to tell you so.

I once entrusted you with some of my painful experience not long before we parted,
by showing some of my daily notes; and may yet inform,
that the same tribulated path has been assigned to your poor brother in this land.
Deep have been the wadings of my soul for months past,
and at seasons I have thought my faith and hope have been tried almost to the uttermost;
but surely underneath must have been the Everlasting Arm,
or else I should have fainted by the way.
I think I have been made sensible of your afflictions at large in Philadelphia,
as well as that portion, which, no doubt in all-wise disposal,
has fallen to the lot of my dear family;
and I have been favoured with so much resignation of mind as to be able to say,
'`The Lord gives, and the Lord takes away,
blessed be the name of the Lord;`'--and here I am disposed to leave it,
for it has sometimes been almost too much for my thoughts to dwell upon.
'`The works of the Lord, they are wonderful, and his works among men are hidden.`'

You wilt very likely hear, not only by my letters to my beloved Sarah, but others,
that my mind has been turned to visit the miserable among my fellow creatures,
shut up in prison houses, etc,; and I proceeded as far, in this arduous business,
as way could be procured for me by my kind friends.
As far as I went in the service, it was comfortable to my own mind,
and I have no cause to doubt but that it was productive of some consolation,
at least to some of the visited.
Here once more I was thrown out of business, and in this state my friend Robert Howard,
who, with dear Joseph Gurney Bevan, had been kindly interested in trying to make way,
came to visit me.
When I saw him coming in, the thought arose,
whether he had not found some more work in the jails; but he soon informed me,
that he was going to Canterbury to attend the burial of William Elgar,
the principal Friend in that city, and was disposed to take me with him;
and having had thoughts that there was some further labour assigned me, in that county,
and seeing a little light shine on this movement, I took courage and set off with him,
though under discouragement and depression of mind.
However, through the Lord`'s goodness, light has continued,
and here in this county of Kent, a new and unforeseen field of service has opened,
very different from that which I was engaged in this time twelve months ago.
I then saw little further than visiting the meetings of Friends,
and only had one amongst others at Folkstone, which was satisfactory.
Now the way has opened in a different line.

The corpse of this Friend was taken to the little meeting-house,
which was pretty much filled up, and we had a long walk to the grave,
through one of the streets of the city.
Numbers who were not Friends followed on the opposite side of the street,
and I rejoiced in having so large a company at the grave.
The people behaved solidly, which I have been informed has often been far otherwise.
Since that, I have had several public meetings at Dover, one at Deal, and two at Margate.

Last first-day I attended the burial of our ancient friend Sarah Beck.
The house was filled up pretty much by the town`'s people,
and I had a public meeting in the evening,--both favoured seasons.

On second-day went to the burial of John Elgar, Folkstone,
who died of a scrofulous complaint;
and I trust his light afflictions have not only worked for his good,
but have been and will be a blessing to the rest of the family.
Friends are building a new meetinghouse,
and the carpenters were willingly disposed to
fit it up for the accommodation of a meeting;
and some of them, I have heard, said,
all they desired was to be able to get in and occupy
one of the seats they had made for the purpose.
The corpse was put into the ground first,
and afterwards such an eagerness to get into the house I have not often seen;
and it was a large, crowded and good meeting.
The mayor of the town, whom I met with afterwards on the sea shore,
expressed his satisfaction, and said he hoped it would be profitable,
especially to the young people, for they were raw and uncultivated, etc.
There were also several goodly soldiers at meeting.
Yesterday was their monthly meeting at Folkstone--some few of the neighbours attended,
and two soldiers; the latter came to the Friend`'s house where we dined,
and a memorable opportunity we had with them on parting.
O the sweetness, meekness, and love that was to be felt in their minds,
though to outward appearance mighty men.
Great have been the sympathy and love I have felt for this class of people,
and I should not wonder if they are numbered amongst the first fruits
of a precious visitation approaching toward this favoured island.
The Lord in his infinite love hasten it.

I am now at my dear friend Richard Baker`'s,
who with his wife are like a father and mother,
and their dear girls as sisters or daughters to me.
Here I stopped, and turning to Richard Baker`'s two daughters,
told them I was writing to Rebecca Jones.
The girls answered, '`Do give our dear love, and mother, if here would send hers also.
Richard says, '`I have just been thinking of her since dinner,
and I will give you something to insert;
and here I copy it from his memorandum handed me.
"`Richard Baker desires his very dear love to be remembered to Rebecca Jones,
and who frequently has revived in his remembrance profitably,
and wishes her to be informed for her encouragement,
to attend to impressions that may sometimes appear small;
that the single sentence she delivered to him without any comment thereon,
on meeting him in a street,
has been made more profitable to him than some whole volumes he has read, which was this:
Blessed are they that mourn, for they shall be comforted.`"

Pray for me my dear friend, that my head may be kept above water,
and that I may answer the Lord`'s requirings in this land, whether in further suffering,
or whatever labour may be pointed out!
O this is the breathing desire of your deeply conflicting friend, who loves you.

[.signed-section-signature]
Thomas Scattergood.

--

"`14th, fifth-day.--To the week-day meeting at Dover;
towards the close stood up in testimony, and endeavoured to encourage those present.
I appointed a meeting to be held at six o`'clock, which was crowded, and a quiet,
solemn time.

"`15th.--Are you able to drink the cup that I drink of,
and to be baptized with the baptism with which I am baptized?
They hardly knew whereof they spoke, when they said, '`We are able.`'
O the feelings of this hour with my wading soul.
Lord God Almighty, you,
and you alone can enable me to drink the cup with becoming submission and resignation.
Send forth help from your holy sanctuary, and strengthen me out of Zion.
Open the way and go before your servant,
and favour me to accomplish the day`'s work with the day.
How unsearchable is your wisdom; and your judgments and ways are past finding out.

"`16th.--Paid a sweet visit to the boarding school kept by E. Kelly;
and both mistress and children were much tendered.
After dinner took Richard Baker with me and paid a visit to King, a play actor,
who received me kindly.
E+++.+++ Kelly`'s husband told me he lay in the barracks near my house in the year 1772.`"

[.offset]
On the 17th he attended a funeral at Canterbury;
and on the 18th went to Rochester and consulted Friends about a meeting at Sheerness.

"`19th.--It seems almost as if the two meetings in view
were as the last handful of meal in the barrel,
and all the little oil left in the cruse Called in and
sat with a Friend whom we found very poorly,
and had a baptizing opportunity in her chamber,
and then accompanied by Dr. Cowper and Richard Baker, went to Sheerness.
We were kindly noticed by several inhabitants,
and the meeting was held in a large and commodious
Methodist meeting-house and proved a favoured time;
the people were open and kind after it--some stopped me and expressed their satisfaction.
I do not learn that there ever was a meeting held here by a Friend before.

"`20th.--Got to Rochester to dinner,
and requested Friends to collect the people of the
place at half past six o`'clock in the evening;
which proved a laborious time,
but towards the close more comfort and enlargement were experienced.

"`21st.--The week-day meeting was a comfortable time,
and soon after dinner set off in a post chaise for London.

"`22nd.--Went to Tottenham meeting in a very low state, where was a marriage,
and I went and dined with the company.
After tea the guests were collected into one room, and we had a solemn time,
in which I found some relief by pouring out my soul in supplication and
afterwards had a remarkable tendering season while addressing the children.
It is marvellous to me that it should be so,
and that the water of weakness and great discouragement should
for a moment be turned into the wine of refreshment.

"`23rd.--How blind and stripped I am, and I trust disposed to say, Your will, O Lord,
and not mine be done.
O the mystery of this work, in being thus abased from day to day.

"`Third month 14th, fifth-day.--Feel a secret hope reviving,
that it is right to go to Suffolk quarterly meeting.
After meeting went home with William Dillwyn,
and having received a note from dear John Bevans,
desiring I would come to London this afternoon, S. D. and children went with me.
After conferring with him respecting accompanying me, if I must go further north,
we went into the room to Sarah Talbot and companion, George Stacey, and others, etc.,
and had a sitting,
in which Sarah Shackleton spoke concerning the enemy tempting our Lord to
command that the stones might be made bread to satisfy his hunger;
after which I kneeled down and prayed, and felt some relief.
A prospect was renewed on my mind to have a public meeting at Chelmsford,
of which I desired George Stacey to write to a Friend there.

"`15th.--Set off accompanied by my kind friends William Forster and M. Philips,
and arrived at Chelmsford about five o`'clock;
not without a weight of sorrow and exercise, especially on entering the place once more;
however, I endeavoured to bear up and anoint and wash.
Went to the meeting at six o`'clock, in a very low state,
in which I had to stand up and labour.
Many soldiers came in: I hope it was a time of some profit.

"`16th.--After two family opportunities, set off for Kelvedon.

"`17th, first-day.--To meeting at Kelvedon, which was small,
and most of the time I felt poor.
Tears of exercise were my food--towards the close, I felt a little opening to labour.
I told them amongst other things, that dear Stephen Crisp, who lived and died here,
had come freshly into remembrance,
and that as a part of his prospects respecting this land had already been fulfilled,
I believed more would be.
I was most easy to appoint a meeting for the inhabitants, to be held at six o`'clock,
though in great weakness, and so I attended it.
For nearly an hour after sitting down in this very crowded gathering,
I thought myself never more stripped, but at length in great weakness I stood up,
and it broke up solidly, and the people behaved well.

"`18th.--I move under great strippedness and poverty,
with a great burden of exercise still to carry.
Nothing short of the omnipotent Arm will bring me safely through and over all,
to the end of my days.
Remember your tried servant, O Lord, in mercy, this day,
and let your will be done in and by me.
Concluded to stay monthly meeting in this place.
It was solid, and the business was conducted with sweetness and harmony,
and I ventured to bend in supplication.
Soon after dinner I set off to Dykes Alexander`'s at Needham.
Here I met with a number of dear friends, and a kind reception from the family.
Went to select meeting and then to see Sarah Harrison,
and had I hope a baptising time in her sick room,
with which she appeared strengthened and comforted.

"`19th.--To quarterly meeting;
W+++.+++ C. appeared early in supplication and afterwards I stood up in testimony;
after dinner had a memorable opportunity with a few friends.

"`20th.--Had a time of weeping and conflict on my bed this morning,
but was favoured to resign myself to divine disposal,
and feel a willingness to go forth as Abraham did, not knowing where,
endeavouring to leave that to the Lord,
to lead and guide me in the midst of the path of judgment.
I trust the upright language of my soul is; '`If you go not with me in this journey,
take me not up from here;`' and on the contrary,
if you wilt condescend to the low estate of your servant,
and vouchsafe your good presence, be it unto me according to your word.

"`21st.--To Needham week-day meeting, where I found Sarah Harrison,
and was concerned to pray for the preservation of myself and
fellow servants--dined at William Alexander`'s. Went to Bury,
eighteen miles.

"`22nd.--In the evening as we entered Godmanchester,
my mare being tied behind our chaise, took fright and turned us over,
and we had a narrow escape with our lives.
I was deeply sensible of it in the time of extremity, when the breathing cry arose,
'`Lord save us;`' and was favoured to get but little hurt:
when I got into Samuel Blakely`'s I found my dear friend and companion, John Bevans,
and also met a kind reception from friends.

"`20th.--Went to Leeds, and on the 27th attended York quarterly meeting,
which was a comfortable time.

"`28th.--Was at two sittings of the quarterly meeting, a meeting for worship,
and also a meeting for ministers and elders; which ended satisfactorily,
and I trust I have been in my place.

"`29th.--After a favoured opportunity with a number of Friends set off for York,
and got to Lindley Murray`'s to a late dinner; here I found Ann Crowley;
had a comfortable, religious time,
and afterwards visited the Retreat and boarding school;
returned to Lindley Murray`'s and lodged.

"`30th.--Got to Edward Pease`'s at Darlington about dusk, and met a kind reception.

"`31st, first-day.--Went to meeting and was exercised with the unsettlement of many.
I laboured honestly among them,
and had also a word of consolation for the burden bearers and mourners.
Appointed a meeting to be held at six o`'clock, which was very large,
open and satisfactory.

"`Fourth month 1st.--Went to Sunderland, to our friend Solomon Chapman`'s;
and at six o`'clock went to the meeting for ministers and elders.
In the fore part of it I was concerned in prayer,
and afterwards was drawn forth in close testimony.

"`2nd.--Attended the quarterly meeting,
in which I had much labour in an encouraging line to the youth.
The first of this month we drove through snow drifts up
to the hub of the wheels of the post chaise.

"`4th.--Felt openness in supplication at the week-day meeting,
and after it a pointing towards a public meeting, which was held at six o`'clock.
It was large and solid.

"`6th.--Got to our friends H. and M. Bragg`'s before night, at Newcastle.

"`7th, first-day.--To meeting, and sat in a very stripped condition,
but after a time stood up, and had to bear a singular testimony.
Some gay Friends, beside many strangers were present, and I felt openness toward them.
Was not easy without appointing a meeting to be held in the evening at six o`'clock.
I went to it in great feebleness, and stood up and laboured for some time,
and to my admiration it was a season of divine favour toward the close,
and great solemnity prevailed after I sat down, and it concluded so.

"`8th.--O my soul, sanctify the name of the Lord, and let him be your fear and dread;
and also seek him for your comfort and consolation.
How shall I go into Scotland amongst a wise people in this poor state,
has often been the language of my mind.
Lord, if you go with me it will be enough--then out of
weakness your strength will be made known.

"`Rode to Shields monthly meeting, eight miles,
with M. Bragg and my companion and had a time of enlargement in speaking.
After dinner had a solid religious opportunity.

"`9th.--Took a walk after breakfast along the sea coast to Teignmouth castle.
Here are the remains of an old abbey; some of the lofty walls are still standing,
and at the end next the sea is a small room very much decorated with carved work.
It seemed as though the images of the apostles were cut out of stone in the ceiling.

"`At seven in the evening attended a meeting held in the Methodist house,
which was a remarkably solid time, and ended so.
It is marvellous to me, and cause of deep thankfulness and encouragement also,
that after feeling so poor this day, and going to meeting so,
fresh strength should be vouchsafed.
The Lord be praised for his goodness.

"`10th.--To the week-day meeting, which was small,
and I felt some encouragement respecting myself.
Bent in supplication, and afterwards endeavoured to encourage a few youthful minds,
and to warn others,
lest by slighting the day of visitation their crowns
should be taken away and be put on the heads of others.
In the afternoon came to Newcastle.
To a large meeting at seven o`'clock, in a new Methodist meeting-house;
having had an open, kind invitation to hold it there from three men of that body.
It was solid and quiet, and separated so.

"`11th.--At the week-day meeting I sat nearly or quite two hours in silence,
a part thereof with tears, in viewing my own state;
and yet toward the close a little encouragement was handed forth to this small company.

"`12th.--There appears no opening to move from this place.

"`13th, seventh-day.--In the evening Joseph Clark,
who is a preacher among the Methodists, and in whose house we had a meeting,
came in with one of his friends; they staid and supped,
and afterwards we dropped into silence,
and I was engaged in prayer they appeared to be solid men.

"`14th, first-day.--Received an affectionate letter from Joseph Clark,
enclosing one for Richard Annett, who lives about thirty miles on the way to Scotland.
Went to meeting; many strangers came in, and it proved a tendering time.
The meeting at six o`'clock was a full one, and much labour fell upon me,
and it ended in a solid, comfortable manner.

"`15th.--A solid parting time with this family and servants.
Rode thirty-four miles to Alnwick:
on the way a desire was felt that mercy and forbearing kindness may accompany,
and enable me to offer up body and soul into the care of him,
who has helped and supported hitherto in great straits and trials.

"`16th.--Breakfasted with Richard Annett and wife, and had a solid religious opportunity.
Dined at Belford, sixteen miles, and got into Berwick before night.

"`17th.--Got into Haddington, where we lodged.
Soon after we put up a man came, who sent the waiter to call me out,
and said he wanted some conversation with the Quaker gentleman,
and if agreeable would go and bring a brother with him.
Some time after he returned with a young man, and they proposed several questions to us,
which we endeavoured to answer, and were surprised to find them such conscientious men,
from whose outward appearance little or nothing of the kind could be expected.

"`18th.--Arose early and got to our friend George Miller`'s at Edinburgh, to breakfast.
Went to meeting at ten o`'clock, and sat in silence until near the close.
Took a walk through the town, where we were much stared at.
I fear there is too much lack of humility in this city, the metropolis of Scotland.
I felt like a blank this morning in the meeting; and yet apprehended I saw,
and told them so,
that there is a precious seed sown in this place that will not be rooted out.

"`21st, first-day.--A number of strangers came into the meeting this morning.
Dear Elizabeth Wigham uttered a few lively expressions, and said,
perhaps it was necessary for some to experience a further
baptism and refinement to fit for further service.
I was engaged in prayer the latter part of the meeting,
and interceded for myself and those left behind--for the little
remnant planted as a seed in this highly professing city,
and for the inhabitants thereof.
To meeting again at half-past two o`'clock,
where dear John Wigham had an instructive time, but all closed up with me.

"`25th.--Attended their monthly meeting, where only about twelve friends were present;
the business was conducted with a good degree of weight.

"`27th, seventh-day.--Attended the select half year`'s meeting, at which were six members.

"`28th, first-day.--I thought it was a low time at meeting this morning,
but I expressed a few sentences, tending to stir up Friends against they came again.
In the afternoon meeting I was exercised in supplication,
and afterwards appointed a meeting at six o`'clock,
which was pretty full and crowded--though there
were lightness and talking in the beginning,
yet afterwards it was quiet, and I had a comfortable relieving time,
and we parted in a solid manner to my joy.

"`29th.--Trust in the Lord, O my soul,
and forget not his benefits bestowed in past seasons.
Trust in the Lord and wait on him, to enable you to do good in your station.
A number of strangers came to the meeting, mostly of the poorer sort,
to whom I felt much love and enlargement.
Friends concluded to adjourn to meet at three o`'clock,
when the business was conducted comfortably.
Dear John Wigham expressed his unity with our visit in a very feeling manner,
especially with the silent part of meetings in this place;
and when my certificates were read,
my heart was humbled on remembering the date of
them and how long I have been in this land.
Had an opportunity with the son of A. L. and others in the evening--
another with several convinced people not yet joined in membership;
and on the whole it has been a day of lifting up my head a little in hope.

"`30th.--The half year`'s meeting having concluded,
I am waiting to see what further is required.
O Lord, remember me according to your good hand upon me.`"

[.offset]
While here he received a letter from his beloved friend Mary Dudley,
from which the following is taken;

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Bristol, Fourth month 25th, 1799.

[.salutation]
My very dear friend,

Though your last truly valued communications have long laid unacknowledged,
they have been to me not only as a precious memorial of your regard and confidence,
as it respects a friendship which I covet to be so preserved as not to forfeit,
but truly may I say, that, if ever enabled to enter into that sympathy,
where "`deep utters unto deep,
because of the noise of water spouts,`" my soul therein could,
proportionably to its capacity, comprehend your unutterable exercise.
But never, in the midst of all, when beholding you enclosed as in the prison house,
have I been divested of sustaining and consoling hope, that He,
who only can availingly preach deliverance, would bring you forth to His own praise,
and the increasing help of His church and people:
for surely such as are resigned to go down to the sea,
and occupy their business in great waters, will see the goodness of the Lord,
and his wonders in the deep; and then, in renewed deliverance,
are qualified to tell of his love to the inhabitants of His earth,
I was prepared to hear of your enlargement; and though the spirit continues to testify,
that "`bonds and afflictions still await,`" let a poor little sister,
in a measure of these, say to you, my beloved brother, lift up your head in hope, yes,
thank God and take courage, knowing assuredly, there is none like the God of Jeshurun,
who yet makes, and will make the clouds of deep heart-humbling baptism his chariot,
and rides upon the wings of the winds; and this, that His angels may be spirits,
and His ministers a flame of fire.

I wish this to meet you in Edinburgh, therefore forbear entering into some subjects,
whereon I could freely converse with you, through this, or a more desirable medium,
that of personal communion, which I once had a hope I might be again indulged with,
perhaps if able to get to the approaching yearly meeting;
but my very debilitated frame is not likely to be equal to such an exertion,
nor do I yet know, that it would be in the line of duty.
As your feet are once more loosened from the stocks, I hardly expect your return to it,
when such a field as that where you now are, is open to your view.
As I have a particular desire to know whether a
proceedure therein is likely to be your lot,
or the annual solemnity more weightily attractive; I should be gratified,
if by your own acceptable pen (if at liberty to use it,)
you would inform me what your prospect is,
and however or wherever it unfolds, may you, my dear friend, resignedly say,
'`Your will be done,`' This is a language, which,
though my mind at seasons longs to feel its own,
I may acknowledge to you is a state not attained to; and so great is my weakness,
that even respecting the discoveries of light,
without the present requisition to follow it,
I sometimes fear a turning away or a disposition opposed thereto.
Thus am I often halting, yet here I have been, and am still in bonds,
and in the midst of bodily and mental weakness,
sometimes seeking their being loosened by feeble
endeavours to do the little pointed out.

My friends at home have left me at full liberty for extensive movements,
but I apprehend they will be much circumscribed;
perhaps only a little further into the adjacent counties,
then if strength should be vouchsafed, I have looked westward,
I mean to the western counties, such as Devon, etc.;
but should my health continue as feeble as it now is, rather expect a release,
and liberty to return home,
and perhaps obtain before long a final dismission from further exercise:
what an abundant mercy, if it prove a peaceful retreat.

I think I heard dear John Bevans was your present helper,
to whom I wish to be cordially remembered; we have known each other long,
and have each much to commemorate of abundant mercy,
which having found us in the wilderness, in the land of great drought, has yet preserved;
and thereby hope is revived, that the morning light will be the evening song.
And now my beloved brother, farewell; which I have no doubt you wilt,
in heights and depths, in life and death, yes,
that nothing shall separate from the continuance of divine love and life.
I am your poor little sister, but sympathizing friend, in gospel and affectionate love,

[.signed-section-signature]
Mary Dudley.

--

"`Fifth month 2nd, fifth-day.--Went to the week-day meeting,
and in consequence of the half year`'s meeting having formerly been held at this time,
many people were present.
Several young women were laughing and talking together, with which my mind was grieved,
and after a time I stood up and reproved them,
and told them that my employment in such meetings often was in sorrow and tears;
also mentioned the distress I had been witness to,
when the pestilence that walks in darkness was going through the city where I dwelt;
and how different it would be in this place,
if the Lord should see fit to visit them in the same way,
then they might have to mourn a father or mother, a brother or sister, etc., and say,
Alas! for me.
After I sat down, dear John Wigham had an acceptable time,
and Friends afterwards remarked,
that the meeting at this time never broke up so solidly before.
In the evening I was brought very low,
and retired to my chamber and offered up my prayers and tears,
with strong cries in secret.

"`3rd.--The accuser of the brethren is permitted to come up against me,
and I see no opening to return, and greatly fear going forward unsent.
Your sovereign will, O Lord, be done,
only be pleased to keep the head of your servant above the waters.
Felt more contented and resigned this afternoon and evening.
This is a favour, even to sink down into nothingness, emptiness and poverty,
and bear it in a becoming manner.

"`4th.--I felt a little openness to give liberty
to invite the neighbours to meeting tomorrow.

"`5th, first-day.--Very stripped and poor indeed.
I hope my soul longs in all things to be resigned and content;
and were it not for such prevalent thoughts so continually coming up against me,
(like this,) '`You are deluded, you are deceived,
or it would not be so with you,`' I am ready to think I
could sink down and bear all things patiently.
Indeed, it seems as if there was no other way for me,
than to bear this unutterable conflict with patience, and willingness also.
O Lord, you know all things,--you know that my soul desires to love you,
and do and submit to your will.
Went to meeting, and after a time felt an openness in my heart toward the people,
a number of whom came; and although there appeared much lightness at first,
we had a solid meeting, and it concluded so.
I ventured to invite them to come again at six o`'clock; which was a full meeting,
and to my humble admiration I was favoured to hold forth the truths of the gospel.
Tenderness and solidity were prevalent; the meeting closed well,
and my soul was measurably filled with thankfulness.
My dear companion on lying down, appeared much broken and tendered,
under the sense that Truth had eminently prevailed in this last meeting.

"`6th.--Comfortable and quiet in mind; but yet under exercise.
Sat down with the family and several Friends,
and felt my mind drawn to supplicate the Almighty Helper to go with us,
and to bless this family; my companion`'s and my own also were fervently remembered.
Took leave and rode to Queen`'s ferry, nine miles, and two miles over,
and may record with thankfulness that it has been a sweet ride,
in the fulfilment of that saying; '`For you shall go out with joy,
and be led forth with peace.`'
Thanks for this morning`'s portion--dined at the ferry house,
and put up for the night at Kinross, fifteen miles.
We have George Miller for our guide and companion.

"`7th, third-day.--Rode in the rain to Perth.
To a meeting held at James Fitchey`'s, where there were about fourteen persons,
and a pretty open time.
A young man who, I was afterwards informed, had drawn back from his profession,
told me after meeting, that he had desires before we met to converse with me,
but his doubts and difficulties had been spoken to, and he was measurably relieved.

"`8th.--A pleasant ride to Dundee, twenty-two miles,
and had a satisfactory meeting with the little company who meet in this place.

"`9th, fifth-day.--Breakfasted with Lewis Evans, where we had a dispute with James Scott,
a preacher among the Glassites, and after he was gone,
a satisfactory opportunity with the man and wife.
It appears he was reached by William Savery.
I went afterwards and had an opportunity with William Smith and wife to satisfaction.
There are four or five men not yet joined in membership,
who hold meetings in this town in the way of Friends.
Got to Montrose, and the ride today has been pleasant: at times we came near the sea,
and before we got into the town we passed over a small river, and then over an island.
Soon after putting up our horses, we took a walk to Mary Mills`'s and drank tea;
she and her daughter are the only two Friends in town.
Had a religious opportunity,
in which I had a singular communication from that passage concerning the shepherd`'s
taking two legs and a piece of an ear out of the mouth of the lion, etc.
The situation of Lot in Sodom was also mentioned: in the evening afterwards,
George Miller told me it was strikingly appropriate.
This ancient widow in younger life was zealous,
and frequently walked twelve or fourteen miles to meeting.
She afterwards married unsuitably; her husband failed and brought her into difficulties;
and yet, through it she has been measurably preserved.
I thought there appeared something of the right stamp about her.

"`10th, sixth-day.--Rode to Inverbervey to breakfast.
Dined at Stonehaven and got to Aberdeen, where we put up at an in.

"`11th.--Rode in the rain fourteen miles to Kinmuck,
and met a hearty reception at John Crook`'s,
and I soon forgot my troubles in this lowly habitation.

"`12th, first-day.--To meeting,
which was filled up pretty soon with well behaved neighbours and Friends,
and my mind was soon sweetened with a sense of the love of God;
and under it I kneeled down in supplication,
and afterwards had an open time in testimony.
I desired Friends to stop when others withdrew, and had a sweet, tendering time with them.
In the beginning of this meeting my mind and prospects were enlarged,
and I felt earnest to move on toward the Orkneys.
My friends and family at home came into view,
and with silent tears I put up my prayers for them, and for my own preservation;
that the Lord Almighty might be pleased to renew the
visitations of his love and mercy to my remaining children,
and I was favoured to believe it would be so Thus the bonds of sorrow,
mourning and death were removed, and my soul given up to do the Lord`'s blessed will.
O Lord God, you have supported in the deep, and I can say with Jacob,
you were in the place where darkness surrounded, when the stone was my pillow,
when I had hardly faith to believe in your Providence--
sanctified and glorified be your name.
I spent a pleasant afternoon and evening--many Friends called in to see us;
and lay down and rested sweetly in our little berth, which reminded me of a ship`'s cabin.

"`13th.--Breakfasted at John Morris`'s,
and called in to see several Friends in their little cabins.
I was particularly interested in an old woman, not a Friend,
whom I observed when she came into the meeting
with a Scotch plaid over her head and shoulders;
she lives in a poor little smoky cabin, without any window in it, and entirely alone,
yet appeared to be happy in her situation.
O, me thought, when a day of searching and trial comes on the land,
when the time arrives which that faithful servant of the Lord, Stephen Crisp speaks of,
when '`they shall go through hard bestead; they shall seek death rather than life,
and not be able to find it;`' or in the words of the prophet,
when '`they shall pine away in their iniquities,
and mourn one towards another:`' how many would be glad
to be as comfortable as this poor cottager.
It is evident there is such a thing as having the mind
brought into contentment with a very little.
O Lord, in your just anger against pride and high-mindedness,
and the many loudly crying sins which prevail, be pleased to remember mercy.
Rode to Old Meldrum and attended meeting, which was made up of the poorer sort,
and was a laborious time, yet hope to some profit.
In the evening I was closely exercised with desires to be right, to think right,
and act so.
I desire to be favoured simply and singly to attend to opening prospects.

"`14th.--We are told that the snow has not laid on the
mountains so much at this time of the year for seventeen years.
The people at Huntley, where we dined, looked clean and so do those of this town,
(Keith,) where we are to put up for the night.

"`15th.--Took a walk out of town soon after I arose
from my bed and looked over this little place,
I trust in the love of God; and although I felt no opening to have a meeting,
yet there is a pleasant feeling.
I said in my heart this morning,
when will a living army of serious Christians arise and
march through the length and breadth of the land,
from this north country.
I hope there will a precious seed spring up in Scotland.
My mind seems pressed to hasten forward for several days past,
since the way opened to the Orkneys.
To Fochabers near the river Spey.
This has been a nine miles ride of pleasing rural prospects.
We noticed a large hill or mountain, which is the shape of a whale,
with snow on the top and sides; and in the distance mountains of snow were observed.
It has been a very cold ride: we saw a number of hearty looking children,
the little boys dressed in the highland fashion.
The duke of Gordon`'s seat is near this village,
and on the opposite side of the river are beautiful red rocks.
We got tea and fed our horses at Elgan,
which appears to be an ancient place by the remains of an old cathedral and
a dismal looking prison nearly opposite the window where I write,
and a guard before the door.

"`16th.--Started at six o`'clock, and had a very cold ride to Nairn along the bay coast.
Before we got into this little town, and just upon coming to a river,
we met a good looking man, who told us the bridge was not passable with horses;
and after going to the ford with us,
said if we would go to James Brander`'s inn we would meet with kind attention;
he lived there, and would go over the bridge and meet us, which he did,
and we found he was the landlord.
While at breakfast, inquiring of him concerning the road,
he said he had a good post chaise and two good horses,
and a careful driver acquainted with roads and ferrys part of the way.
We accordingly hired the chaise until our return,
and sent our horses back with John Cruikshank.
Proceeded to Fort George, eleven miles, and the wind being ahead,
it was very tedious crossing at this ferry.
Rode on ten miles to Invergardon, where there is another ferry nearly two miles over.
It was between nine and ten o`'clock before we left this place,
there appearing no probability of our being accommodated with lodging, and rode to Tain,
to which we got by twelve o`'clock.
The innkeeper and wife and servants got up and met us with pleasant countenances,
apologizing for being in bed.
We got to bed before two o`'clock and slept soundly.
This has been a day to be remembered--what but a
sense of duty to the Preserver of my life,
and love to the precious seed in the hearts of my fellow creatures,
could induce me to travel in this manner?
Lord, your encompassing power and providence is every where, grant me strength to say.
Your will be done.

"`17th.--Set off about eleven o`'clock, and rode to the ferry, five miles,
but could not get over, and were obliged to return back to our inn.
I felt fatigued and poorly; about seven o`'clock went down to the ferry again,
and waited some time before we got over--rode five miles along the coast to Dornoch,
where we got some supper and to bed near twelve o`'clock.

"`18th, seventh-day.--This place is pleasantly situated near the sea,
but the houses appear to be fast going to decay.
There are here ruins of an old abbey and steeple house,
the grave yard of which is open and waste,
and it is probable that it was once the seat of a bishop.
About seven and a half miles distant we came to a ferry,
where we had to wait some time for the boat,
and encountered a soaking rain from the neighbouring mountains.
When we got over I stepped into a house filled with smoke,
the fire being in the middle and a hole through the roof for a ventilator.
The pot was over the fire and the poor mother and children around it.
She told me she was a widow and had seven children.
We dined at a public house at Golspie--set off about two o`'clock,
and still coasted for about eight miles along the sea,
and stopped at another public house and got tea.
This as well as the last stands open to the sea.
In this ride we passed over a very poor country--the hills are mostly very barren;
and in the valleys where we rode are many huts built entirely of sods.
Some of them are quite humble, but others are in some style in their way,
having a porch or entry with an arch over it.
I counted near fifty of these huts not far distant from each other,
and was at a loss to know how the people live.
I felt for them,
and have thought it probable that in a day to come some young
ministers may be raised up and sent into this poor highland country.
Lord prosper the work, and bring many to the knowledge of your ways,
that so the increase of pure obedience from simple
upright hearts may be offered to your name,
from the rising of the sun to the going down of the same;
and appoint the share of work to your servant in this land,
according to your blessed will, who knows best what is best for me.
The remembrance of precious John Pemberton, whose track we are now in, is sweet.
How different are my feelings here in this land of poverty,
and partaking of barley bread, to what they were in London, where good living abounds.
I look towards you, O London, with a trembling heart.
At eight o`'clock we arrived at our inn, but the room being occupied by fishermen,
we took a walk out on the shore.
My mind is calm and resigned, believing I am in my place,
although like a pilgrim and stranger on the earth.

"`19th, first-day.--Arose about six o`'clock, and got away about half past seven.
At Burydale, about eight miles, we put up to feed and got our breakfast,
which consisted of a cup of tea, barley and oat bread with eggs.
My companion rather fails this morning, not being able to relish the provisions:
my mind and body seem marvellously supported.
We had to walk most of the way to this place, the road was so very steep and stony.
Just as we got to the inn we saw many people collected,
some appeared to have come a long way, to hear a sermon in the Erse language,
and one after in English.
I felt my mind turned toward them, and after we got in,
George Miller asked me about a meeting,
and I encouraged him to go and speak to the minister,
and he consented to our having the house at three o`'clock;
at which time we met with a number of the people to some satisfaction,
but when we got back to our inn, intending to have a cup of tea,
found our room filled up with people,
and nothing could be done but set off another stage; which was a trying one,
having to walk again in the rain, wet and slush:
descended a very steep hill to the river, and found the bridge gone and the water up.
The landlord called from the other side, and told us we could not get over,
but must go back from where we came.
It was trying indeed to think of encountering such difficulties,
faint and tired as we were, at least my companion was so, from loss of sleep, etc.
However, a kind man came to us and told us we might get over,
so we went into the chaise and sat in it until the shower was over,
then our coachman and the kind man who came almost all this day`'s journey on foot,
took our horses over a large hill, and found a fording for them,
and our guide took us along the side of a very steep and slippery hill,
to a place in the river, where he could take us one by one on his back,
which he kindly did, leaving our chaise behind.
We were content,
and I may say I was glad to get into a house and find I could have a bed to lie upon.
We spent a pleasant evening, and lay down so.

"`20th, second-day.--Arose fresh and well this morning, with a mind resigned, I trust,
to the will of my heavenly Father--what a favour to sleep so sweetly.
In a mile or two we came to another river,
where the bridge had been carried away last winter;
the water was low and my companions had passed it, but I waited to see the carriage over,
and seeing a man coming down the hill with the driver,
I thought it was another poor man who came to assist us; but when he came up to me,
found him to be, by his dress, above the common level in this country.
He was kind in directing to the best ford, and after the chaise was safely over,
he helped me over the rocks in the water,
and desired when we came back that I would call on him,
saying he lived in that house on the hill, pointing to it, which we had noticed before,
as a pretty capital building.
I asked him if he remembered John Pemberton, and found he did,
and when I told him of his death, he appeared affected.

"`We rode about eight miles through a dreary land, and at length we came to Clitha,
a more fertile neighbourhood, and upon enquiring for an inn to put up at,
were directed to a large house near the sea.
When we rode up to the door, a well dressed man came out and told us it was no inn,
neither was there any in the place;
but as we were strangers he desired us to get out of our carriage and come in,
which we did, and he gave us a good dinner.
We had the lovely children called in afterwards, and the servants also;
with whom we had a comfortable opportunity:
on parting we received a kind invitation to call upon our return and lodge,
and have a meeting.
Left this place about four o`'clock and rode twelve miles to Wick,
through a barren country indeed;
here we found a town consisting of about one thousand inhabitants.

"`21st, third-day.--Felt poorly, and did not rest so well as usual: however,
my mind was supported and borne up, and disposed to follow on still, in the will of God,
toward the islands.
We were detained until about eleven o`'clock, and were on the road until seven;
there was no house to stop at by the way, and a dreary wilderness to pass over,
in which we lost our way.
Put up in the town of Stromness, and were much tried in getting to this place,
the street being so narrow and difficult,
that it was a mercy we did not overset our chaise.
We crossed a tide river at the entrance of this place, and also one last evening;
the tide being down we got over well;
and now my mind is exercised to know how to move and act
according to the divine will having arrived at the land`'s end.

"`22nd.--Yearly meeting at London, and my mind has been with my friends there.
How differently circumstanced are they--here I am alone
at an inn in the northernmost part of the land.
My companion is gone to see about a place for holding a meeting this evening.
Having caught a cold, I feel poorly and fatigued, and am sunk very low; however,
I believe it was a necessary baptism to prepare for the meeting, which was crowded,
and though very laborious to me, was solid and tender, and ended comfortably;
and we were treated with respect.
We sent for a number of the inhabitants, when we proposed this meeting,
and read my certificates to them, which appeared satisfactory.

"`23rd.--A poorly night--my companions discouraged my going across the water today,
and so concluded to wait.
Took a walk to the water side, and saw women unloading a vessel.
They carry a hundred weight of salt at a time up the shore among the stones bare foot.

"`24th.--Arose and breakfasted sooner than usual.
Our kind landlord accompanied us to the ferry, sometimes walking,
and at others riding behind our carriage.
We had to wait until high water; the wind was north-west,
and our course was nearly north, the distance about twenty miles across.
The boat was about twenty feet long and six or seven wide,
with a little square sail and four men, who rowed us out of the harbour`'s mouth,
over the breakers, which I believe was trying to all of us;
afterwards they put up the sail and laid our course
until we came near the north point of Ronaldsha;
the men then rowed us across to a small island,
after which we lay our course to Kirkwall.
We were tossing on the water from a quarter past one until near ten o`'clock.
One of the ferry men carried us on shore, and we were conducted to James Scarth`'s inn.

"`When we got into the house we found they were about moving,
and had given up the business, but the woman desired us to wait, and finding her husband,
asked him whether we could not be kept this night;
that although they had sold their beds, they had not been taken away,
nor the bedsteads taken down.
They provided for us comfortably,
and the woman afterwards said that she was
struck with our appearance soon after she saw us,
and thought we were some of Mr. Pemberton`'s friends,
and she was not easy to let us go away.
This has been a day of trial to my faith.
O how poor I felt after leaving the shore;
and when tossing in the little open boat on the mighty waters,
was ready to question what I was there for;
though before we set off I felt like a simple child, and no anxiety about the voyage,
believing it right to make a beginning in the place we now are.
It was trying to lie and lean in a cramped posture in the bottom of the little boat,
during so many hours, but it being a fine day and cool, it was more tolerable:
my companions were both sick--John Bevans much so, almost all the passage.
I got over my unpleasant feelings soon, and then was favoured with a cheerful, easy mind,

"`25th, seventh-day,--We did not get to bed last night until nearly one o`'clock,
and having a cold before, I awoke very stiff and poorly; however,
after breakfast we took a walk through the town,
and were stopped and treated respectfully by several.
The boys as well as some others gathered round to gaze upon us,
as they have done in some other places we have lately passed through.
After dinner I got some sleep while my companions went
out to see about a meeting for tomorrow morning.
They were told by one of the magistrates that we
could not have the town-house until evening,
which is discouraging,.

"`26th, first-day.--A pretty comfortable night,
but felt very low and discouraged this morning; nothing opens, O Lord,
I desire to submit my all to you; I am distressed, undertake for me.
Before dinner William Mansen called to see us, and sat with us some time.
I feel a little opening towards a meeting in the town-house this evening,
and notice is to be given, my companions encouraging it,
and our landlord is friendly and assisting.

"`Drank tea at William Mansen`'s, and at six o`'clock,
my two friends said they would go and open the doors of the house for the people,
but soon returned and told me there was such a crowd in the street
that they feared the house would not contain them by many;
and that they had met with several who proposed our going into the great kirk house.
Our friend William Mansen went with them and got liberty, and a great gathering we had.
It was very laborious for me to speak, my cold so pressed upon me; however,
it was a satisfactory time: we returned and supped with our friend William Mansen,
and the young man who had preached twice in the same house this day was with us;
he appears a modest well behaved person.
Returned to our inn and lodged:
the dear old mother provided me with some drink for my cold,
and the son and daughter are affectionately kind.

"`27th, second-day.--I continue hoarse, and nothing as yet opens,
but am labouring to be content in the will of God, believing I am in my place.
We removed our lodgings from our inn to William Mansen`'s.

"`28th.--A poorly night,
and very much stripped and divested of any religious prospect this day.

"`29th.--Poor and blind this morning,
and I cannot go forth into work and service unless I feel the Lord
putting me forth--great discouragements come up against me,
and I feel like one broken up.
O Lord, enable your poor servant to say.
Your will, and not mine, be done, however trying my situation may be.
Took up the blessed book and opened on the forty-ninth of Isaiah.
O when shall my soul experience more of the sweet consolations of the gospel?
May I suffer rightly for the seed`'s sake.
Favour me, gracious God, to do your blessed will on these islands,
whether it be little or more--accept the free will offering of
my lips in a greater or smaller congregation,
and if mortification, stripping and further abasement in poverty is good for me,
grant that my little stock of patience and hope fail not.

"`30th.--Lay down and slept through the night, and felt pretty well upon awaking;
but yet am as a book sealed.
This is indeed a mystery: never did my soul experience such plunges,
such descendings as into the deeps when on religious journeys in America,
and why is it so now!
Hold fast, O my soul, hold fast.
You often remember your humble Lord and Saviour, who suffered for your sake,
and for poor, lost rebellious man`'s sake.
May I be accounted worthy to suffer in my small measure
for his sake--rather let my hand forget its cunning,
'`and my tongue cleave to the roof of my mouth,`' than that I
should not be willing to do and suffer the will of my God.
O you all-powerful One, help your servant through; let me not fall in the day of trial,
and so reproach your name and truth.
I desire to love and honour you: enable me to turn away from, and to forget things past,
put them out of remembrance; and reanimate my soul,
if any labour is allotted me on this island.
I believe that you are able to heal and raise up both soul and body;
but if it is your will that I should yet suffer in both, even though you hide the cause,
may my soul sink down and say sincerely before you, Not my will, but yours be done,
O God.

"`31st.--It is a great trial thus to lie still in the house of a stranger.
After breakfast my companions and I took a walk on the hill,
and as I inclined to go by myself they left me.
I walked to the shore, where we landed:
I looked over the wide waters we had crossed this day a
week ago with a degree of awe on my mind,
remembering the preservation we experienced in the boat.
I poured out my tears with strong cries unto the God of my life.
O Lord, for your great mercy`'s sake, send forth your light--send forth your truth,
and so satisfy my soul, that it may be reanimated and take fresh courage,
to finish your work in this land, so as to feel quietness and peace in returning home.
You who know all things, know what lodges in me; purify my soul and let your will be done.

"`Sixth month 1st, seventh-day.--Wait in patience, O my tribulated soul,
and look up unto your Saviour, whose life was a life of sorrow;
'`A man of sorrow and acquainted with grief,`'
from whom the sons of men turn away their faces.
O the infidelity and unbelief in the land, and the just punishment due for it.
The wretched state of those that forget God, and how little considered by many.

"`The master of the public grammar school came and breakfasted with us,
and between ten and eleven o`'clock we paid a visit to the school; the boys behaved well,
and I have a hope the opportunity will not be forgotten by some at least.
O says my soul, that I might be favoured, through the Lord`'s assistance,
to sow a little seed on this island, either in the minds of children,
or such who are further advanced in years.
We made an attempt to visit another smaller school of boys,
whose parents are in greater affluence, but the master being a deputy preacher,
was afraid to give liberty.
All our religious acts or duties must be performed in the name of Jesus,
in his power and strength.
If this was waited for by active man, less would be done to appearance,
but what was done would be done to more effect; the Lord will bless his own work.
Not thousands of rams, nor ten thousands of rivers of oil, are what is needed, etc.,
not a great appearance of doing, and saying '`Lord,
Lord;`' but doing and suffering the will of God.
This mysterious work is confounding to man`'s wisdom and activity!
Lord, keep my feet from sliding in slippery places--grant your power,
mercy and love to go with me, that I may move with it, and stay with it.
Is your seed under suffering--is religion low amongst men?
Grant ability to say in sincerity, Where you are, there let your servant be,
even if it is in suffering and death.
In the afternoon felt more ease and composure of mind:
we walked a little out of town to a place where poor children are taught,
but the school was broken up.

"`Went to J. Scarth`'s and drank tea, our friend William Mansen also accompanying us,
and afterwards we had a religious opportunity;
and way opened to look toward a meeting tomorrow morning,
and we have accepted this kind man`'s house for the purpose.

"`2nd, first-day.--Feel more light and easy this morning, which is a mercy and favour.
To the little meeting appointed at J. Scarth`'s there came about twenty,
and we thought it a solid, comfortable time:
after it was over my mind was again turned towards the people at large,
and mentioned my thoughts of having an opportunity at seven o`'clock in the large house.
William Mansen sent a note to the parson of the parish to get liberty,
and also desired him to use some means to quiet the boys if they attended.
After dinner, on the opening of the book of prophecy,
some pleasant prospects presented like a mitigation of my deep afflictions, in due time.
Thus the testimony of Jesus is the spirit of prophecy, thanks therefor;
when I came down stairs, William Mansen showed me a note he received from the priest,
refusing us the place, or his sympathy or assistance.
I felt calm and easy, and all concern was taken away about a meeting,
and thought it was likely the burden might be transferred to him,
and he would more or less feel it, and that good would spring up out of this opposition.
I told my friends I was easy, I thought, without a meeting.
My two companions went out about half past six o`'clock,
and found many people gathered in the street,
who by some means had heard there was to be another opportunity in the kirk,
and when they were told it was refused us, they expressed their uneasiness;
they were told that I should be consulted, and they might wait.
I was walking the garden with William Mansen when they returned and told me,
and after a time felt a liberty to go into the street,
and as we passed along encouraged the people to follow.
They appeared much pleased, especially one elderly woman,
who in pretty full terms expressed her satisfaction.
I went upon the steps of the kirk, and the people gathered around,
and after a time had an open opportunity, and then kneeled down and prayed for them.
This last exercise, my companions said, produced much awe over the people,
even the children:
I heard afterward that the people in their houses on
the opposite side of the way heard and were affected.
The company dispersed in a solid manner,
and I returned to my lodgings and spent a comfortable evening.

"`3rd.--Appointed a meeting to be held at seven o`'clock
in the town-house for the children of the town,
which was held to satisfaction; a good many others came also--the house notwithstanding,
was not full, in consequence, it was supposed,
of a meeting for catechising children at the Seceders`' meeting at six o`'clock.
We drank tea at William and Barbara Patterson`'s, brother and sister of William Mansen`'s,
with whom, and the mother and sister, we had a sweet, tendering opportunity.

"`4th, third-day.--Applied for the new meeting-house to hold a meeting in,
but it was denied.
In the afternoon visited the family of Hester Richan, wife of William,
who is in the navy; she had her children called, and also servants,
and it was a memorable time; tenderness appeared in the mistress,
children and servants--one of the last description, a young woman, was much affected.
Drank tea with a widow and her two daughters,
one of whom is a teacher of girls in this place,
whose school we visited the other day to satisfaction.

"`Called by the way upon George Boocha and wife;
she hearing of our disappointment of a meeting place, said we should have their house.
On returning home found Mary Mansen, a maiden sister of our friend`'s,
and in a little time my mind became exercised to speak to her in a particular manner,
and also to the whole of the relations present;
and after supper we had a memorable time with the master of this family, wife,
mother and sister, and after the friends were gone to bed, another with him alone;
he acknowledged that we were sent for his sake--he was much broken and tendered,
and after it I lay down with sweet ease and peace of mind.
O the adorable mercy of God, through Christ his Son.

"`5th.--Awoke and rose pleasant and easy in mind this morning;
though nothing clearly opens, yet I see no way to move from this town.
We meet with disappointments, but trust it will turn to profit in the end.
A young clergyman, who lives about five miles off, came and dined with us;
at half past six o`'clock went to meeting in the town-house,
which was filled up with people.
They were long in coming--the poorer came first,
and did not behave so soberly as could be wished,
and I had to stand up under great disadvantage, like working through a cloud of darkness,
lightness and chaffiness; but thanks be to the Lord, who gave strength,
and it proved a marvellous time.
I think in all the testimonies I have been strengthened to bear in public,
the state of priests and false teachers never was more clearly opened to my view,
and strength was given me to declare it,
and I find since that the nail was hit on the head.
My mind was calm and easy after it.

"`6th, fifth-day.--Quiet and easy in mind, though with aches and pains of body;
for before the meeting yesterday, my body suffered in measure like one going;
to be laid on a bed of sickness.
Lord, favour with strength in the time of need, the time of deep trial,
whether this day or in a day to come; whether inwardly or outwardly, or both united.
Favour me in the season when the adversary may be
permitted to come in like a flood with discouragements,
bringing a cloud of death and darkness with him.
O Lord, you have favoured me hitherto--shelter and protect still; and your will be done.
My companions having heard that the Antiburgher preacher had spoken
against me and the doctrine I was concerned to hold forth,
and had given us a challenge to meet and dispute with him before the people,
and afterward sent a note, desiring a conference with me or all of us;
I requested my friends to go and tell him,
I was willing to meet him in their large meeting-house
and invite all the inhabitants of the place;
but this has been declined by him.
At six o`'clock we had another large meeting in the town-house, to satisfaction,
and in the close I took the liberty to mention what had
passed between the above mentioned preacher and us,
who are strangers;
and that we were not afraid or ashamed to meet him and the people at large,
and give an account of the hope that is in us.
We drank tea with Casper Thrails, the old justice,
and had a little religious opportunity; his wife appears to be a solid woman,
and some of the children and grand-children are hopeful.

"`7th, sixth-day.--I know not but I am fully clear of this place;
having laboured fervently among them.
May the Lord bless it and raise up a seed to the praise of his name,
in this town of Kirkwall, which shall branch forth and spread to other islands hereaway,
says my soul.
We were busily employed until about one o`'clock in preparing for a move,
and sat down with William Mansen`'s family and had a comfortable parting time.
I felt an opening to kneel down and pray for this family and the inhabitants universally.
The dear old woman, our hostess, and her sister, and I think the servants,
also followed the example, and went down on their knees, and after it we parted sweetly.
We had a message from Hester Richan,
desiring we would call and see her on the way out of town.
She had a table spread with coffee, etc., to refresh us,
which with the kindness of several in the streets,
who seemed disposed to send a blessing after us, was grateful.
S+++.+++ Mansen and her niece, with most of Hester Richan`'s children,
accompanied us some distance out of town.
We walked about three miles to William Lindsay`'s, an ancient man,
who kindly noticed dear John Pemberton:
here we refreshed ourselves with provisions which William Mansen`'s wife had put up,
and proceeded toward Stromness, about twelve rniles further.
We had hired a man and a horse with a little cart,
and expected he would take one of us in it, beside our luggage,
but our kind friend Hester Richan had provided a little Shetland pony,
which I rode most of the way.
William Lindsay provided one horse, and we hired another: it proved a rainy afternoon,
but before night we got into pretty comfortable quarters.

"`8th.--Walked up the hill with our landlord after breakfast,
and saw the large mountain of Hoy, the Western ocean and the mouth of the harbour.
The harbour is a very fine one indeed,
which is amongst the numerous blessings of Providence
to seafaring men in this northern clime.
A person named Geddes came and dined with us,
who is a brother to captain Geddes of Philadelphia:
he has procured a meeting place for us,
and while my companions are gone to see the parson, I have sallied out along the coast,
and am now sitting on a rock opposite to the great mountain over the Firth,
and open to the bay and Western ocean.

"`Dear Philadelphia comes up into view, and the prospect of embarking looks pleasant.
O Father of mercies, who have led me about for years in this land,
wilt you indeed waft me safely over the deeps?
Wilt you be my protector and preserver?
My soul craves ability to believe and trust in the sufficiency of your power and love.
How warming and comfortable is the outward sun,
now shining on my feeble body,--how pleasant also the gentle breeze from the sea.
O for the shining forth of the Sun of Righteousness--O
for the quickening virtue that proceeds from you,
you everlasting Fountain of all good.
In walking along the shore, I saw men gathering weed to make kelp,
the lads catching fish, and women collecting shellfish from the rocks, and I said,
how good is the Lord to the inhabitants of this island,
in so bountifully providing for their needs.
I have viewed the rapid tide and great swelling of the sea meeting it,
and have said in my heart; How wonderful and manifold are your works, O God;
in wisdom have you made them all.
I am comfortable in your presence: thanks, thanks be unto you.

"`Attended a meeting held in a ware-house: it was pretty large,
and although most of the people had to stand, it was solid for the most part,
and ended well.

"`9th, first-day.--Felt fatigued and propose resting until evening,
when there is another meeting appointed.
Found no opening to any meeting this morning, and spent it quietly at the inn.
After dinner took a walk along the coast to the ruins of an old kirk and burial ground,
where they now inter the dead.
I was instructed, and feel a sweet and quiet mind.
Drank tea at David Geddes`',
and at half past six o`'clock went to meeting in the ware-house.
It was very large and proved an open, tendering, and I trust instructive time;
had a pretty full opportunity with William Mansen,
and did not get to bed until near twelve o`'clock.

"`10th, second-day.--About seven o`'clock set off in a small boat with four men;
it being a fine day, came around the Hoy,
which is in the Western ocean,--saw a rock called the Man of Hoy;
in one position it looked much like a large and high chimney;
and in another it appeared like a giant, standing in an erect posture,
and we could discern some resemblance to a head and features.
We were until half past two o`'clock in crossing,
and it was called by the boatmen an easy passage.
My companion was very sick:
I feel thankful for the preservation back to Caithness and for an easy mind,
and I trust nothing has been left undone which was commanded me to do.

"`Went to meeting at seven o`'clock, which was not so large as the former one,
and there was much unsettlement for a time;
but on the whole it afforded peace to my mind.
When will the day arrive,
in which the people will be livingly convinced and settled on the ancient foundation?
Many are tender and loving, and some appear satisfied,
and yet in some places take but little notice of us afterward,
so we are necessitated to leave them and trust to the Lord.

"`11th.--Set off between nine and ten o`'clock.
P+++.+++ Swannis came and breakfasted with us,
to whom we endeavoured to explain our principles and views respecting the Lord`'s supper:
he appeal`'s a good man.
Our kind host accompanied us over the river on our way.
We had a pleasant ride to Wisk, twenty miles, and found a great alteration in the roads;
yet vegetation appears backward, the grain just coming up, very little grass for cattle,
and snow on the mountains yet visible; and I noticed at Kirkwall,
that the currants were just forming on the bushes.
In consequence of fatigue I was sick on the way this morning, but enjoy an easy mind:
dined at Wisk--wrote to E. Elmsley to send our horses to Clythe,
and were kindly taken in by our friend Benjamin Henderson.
I was much overdone, having had very little appetite for days past.

"`12th.--Collected the neighbours together about ten o`'clock,
and had a satisfactory meeting in Benjamin Henderson`'s malt house,
and afterwards rode about six miles to John Reid`'s,
the friendly man who so kindly invited me to call and see him on our way back.
Here we met a kind reception from his wife and her sister,
and spent the evening with them agreeably.

"`13th.--Had a sitting with this family and parted with affection.
Rode on to Berydeal, a place where we had a meeting, and found when we came to our inn,
that the landlord lay a corpse.
There was very little water to interrupt our crossing Dunbeath, for we walked over it.
We rode and walked across the Ord of Caithness mountain; when we got to the ford,
about one mile from Helmsdale, found the tide up,
and left our man and carriage to wait and come after us when the tide was down.
We walked on, and our landlord took us in kindly,
but had no great variety of provisions for us;
but with the help of some butter we brought from Thursa, we made out,
and I feel much better after my fatiguing walk today.

"`14th.--Started pretty early and breakfasted on the way,--crossed
two ferries and arrived at Tain between nine and ten o`'clock.
This has been a fatiguing day, and trying to our spirits;
weariness of body seems to affect the mind also,
but my soul craves ability to hold fast through all that is to be met with.

"`15th.--Arose early in order to go one stage further this day.
I see nothing,
and feel nothing for several days past with respect to holding meetings for the people;
and am content.
There is much snow yet on the mountains at a distance,
but the fruit trees are in blossom in the gardens.
The grass is about six inches long, and one field of wheat about six or eight inches up.
After crossing Cromaties`' ferry, and Fort George ferry,
we reached Nairn about eleven o`'clock,
and put up with the person from whom we hired the carriage, who received us kindly.

"`16th, first-day.--Feel much recruited with a night`'s rest,
and thankful for favours received.
The last has truly been a week of toil and fatigue to body and mind.
O for the continuation of the waters of purification and cleansing for us all;
that as a little band we may be favoured to say,
It is good we gave up to this piece of religious duty.
A quiet pause this morning after breakfast, while my companions were writing,
wherein my faith and confidence in the divine Arm were renewed,
for which I feel thankful, and for all the mercies received of the Lord.
My mind is still turned towards England and home, but in the Lord`'s time, not mine.
We took our chaise and driver on to Elgin, and had comfortable lodgings.

"`17th.--Went with the chaise to the ferry opposite to Fochabers, and there left it:
passed over the river and walked near a mile, the driver carrying our luggage.
Here we settled with him and hired a chaise to go forward to Keith, where we dined;
and there being no likelihood of our getting beds, we went on to Huntley,
and were kindly taken in.

"`18th, third-day.--I took a lonely walk to an old castle, and spent about an hour,
in which a good degree of sweetness covered my mind.
Philadelphia came freshly into view, and my prayers were put up for her.
I thought how many innocent persons had been cut off in
her borders within these seven years of distress;
and a secret craving arose in my soul,
that it might please the Lord for the present to accept their lives, in some degree,
as a sacrifice for others,
and try the inhabitants a little longer with the
enjoyment of health and the blessings attending it,
as in years past.
I thought also of the state of the nations of Europe,
and how the dragon`'s chain is loosened; what wars and desolations prevail,
and what a torrent of blood has been spilt.
O poor England,
is your day yet to come! you who have contributed so much fuel to this fire.
Through all this, my soul has beheld, this day,
that the glory of the Lord shall be seen to shine through and over all these shakings.
I have seen that the Lamb`'s war will go forward in the earth,
after the dragon and his cruel war--the one being for the destruction of men`'s lives,
the other not only for the saving of the precious soul, but also for the body.
Lord, hasten the coming of this glorious, peaceful day and dispensation,
if it be your blessed will.
As our horses had not come, we got dinner at this comfortable inn,
and parted from the goodly women who kept it:
took tea at Old Meldrum and arrived at John Cruikshank`'s before night,
and met a kind reception.

"`19th.--To the week-day meeting, which, towards the close, was a tendering season.
After dining at our kind old friend John Cruikshank`'s, at Kinmuck,
we had a religious opportunity in the family, and called by the way at Amos Wigham`'s,
and here we also had a sitting with the family.

"`20th.--To Old Meldrum to monthly meeting, where my heart was humbled,
and I was brought on my knees in supplication, and afterwards engaged in testimony:
got to Aberdeen, seventeen miles, about dusk, and put up at an inn.

"`21st.--Rode thirty-seven miles to Montrose: took breakfast at Stonehaven,
near which is Ury, the seat of Robert Barclay.
We saw his house and the family burial ground from a hill, soon after leaving this place.
Weary on getting in this evening, but find the people kind.

"`22nd, seventh-day.--Proceeded to Dundee, twenty-nine miles; and after getting in,
Lewis Evans and William Smith called to see us,
and we appointed a meeting to be held in the morning at the Tradesman Hall.

"`23rd, first-day.--Went to the meeting, which was held opposite our inn,
in Tradesman Hall, and trust it was to some profit.
Saw no opening to any other in the evening, though some expected and desired it.
Left the place about three o`'clock, and rode to Perth, twenty miles.
Lewis Evans and William Smith accompanied us, and after supper had them and together,
and hope that a long subsisting difference was in good degree healed.

"`24th.--Started about eight o`'clock, and rode fifteen miles to an inn and dined;
I feel easy in thus moving on, which is a favour.
We had a long ride of forty miles today; crossed Queen`'s ferry, and I walked up the hill,
and felt so little tired I thought I could have walked the last stage of ten miles.
On getting to George Miller`'s at Edinburgh, I received several letters from my friends,
but none from America--it seems that some have gone to the Orkneys for me.

"`25th, third-day.--An exercising day,
and could see no opening to any religious service in this city.

"`26th.--Set off after dinner, having Andrew Reid for a guide,
and Joseph and Margaret Flintoff of Manchester, in company:
stopped at Haddington and took tea, and lodged at Dunbar,
where it was with some difficulty we got accommodated.

"`27th.--Got to Berwick and lodged; sighing and tears were my portion this day,
and I left my companions after dinner, and walked several miles in great thoughtfulness.

"`28th.--A refreshing night`'s sleep,
and awoke with a degree of sweetness in remembering God.
Went on fifteen miles towards Belford:
I lagged behind my company and felt very pensive--going
home came up with weight--also my wife,
connexions and friends in America.
My cry to the God of my life was for right direction and resignation.
I looked at the labours of dear Sarah Lynes as we left the place this morning,
and at Holy Isle, where she went, and other places also, but all was closed up to me;
yet I endeavoured to stand open and resigned to religious duty, when it may present:
O my soul, trust in God.

"`29th.--We lodged at Alnwick, and were comfortably entertained.
This morning`'s ride of nine miles has been with weeping and tears.
We arrived at H. Bragg`'s at Newcastle, before night, and met a kind reception.

"`30th.--After dinner I received letters which had gone to Kirkenwall,
two of which were from my son.
Attended the afternoon meeting, under great pressure of soul,
and prostrated myself in prayer, and afterwards had some communication,
particularly to the youth.
Laboured to bear up in the midst of company who drank tea with us,
and felt more relieved and easy on lying down; my faith being renewed in God.

"`Seventh month 1st,
second-day.--A comfortable degree of faith and confidence vouchsafed,
which calmed my mmd on arising.
I crave this blessing at the hand of my God,
to be favoured to centre and resign my will to his will: it is the Lord,
let him do what seems him good.
If he has pleasure in me, I shall yet see the ark of his strength and his holy habitation.
Had a pleasant ride to Durham: put up at an inn not far from meeting,
and at six o`'clock attended the quarterly meeting for ministers and elders,
which was open and baptizing beyond my expectation, and my soul was humbled.

"`2nd, third-day.--The quarterly meeting was a remarkably open time,
both in that for worship and also for discipline: dined at the inn with many Friends,
and had a tendering time afterward.
Parted with my dear friends H. and M. Bragg, with much affection,
and accompanied by B. Pease and others rode to Darlington, eighteen miles,
and felt fatigued with this day`'s exercise.

"`3rd.--Made several visits to Friends, and had two religious opportunities.

"`4th.--To a pretty large meeting held in an assembly room: it was open and comfortable,
after which we proceeded about twenty-three miles on the way to Ackworth.

"`5th, sixth-day.--Proceeded on our journey, and the weather being warm, I was fatigued,
but feel, I hope in the line of duty, in moving on towards Ackworth, where we arrived,
and had an opportunity with the boys after supper.

"`7th, first-day.--An open time at meeting this morning, and after dinner went to Leeds,
to an appointed meeting at six o`'clock, which was very large and an open time.
Lodged at Joseph Jewitt`'s, and was very kindly noticed and cared for.
Returned to Ackworth,
and on sixth-day evening one of the lads read a portion in Sewel`'s History,
and closed with that memorable epistle of Francis Howgill to his friends,
in which he opened his prospects respecting the people he had made profession among.
I had a little to communicate after it,
and proposed to the boys that the next evening
this excellent epistle should be read again;
and on seventh-day evening we began with reading it.
Jonathan Binns, the oldest son of the superintendent, read it in a feeling manner,
and it was a memorable time: we went also among the girls,
and one of the mistresses read the same,
but was obliged to stop for tenderness of mind,--this was also a favoured opportunity.

"`8th.--Rode to Settle, forty-two miles, which we reached about dusk,
and were kindly taken in by John and Mary Birkbeck.

"`9th.--Proceeded and got to Lancaster,
time enough to attend the select meeting at five o`'clock; here I met with Martha Routh,
Deborah Braithwaite and sister Sarah.
It was a searching meeting.

"`10th.--To the quarterly meeting, in which I was largely engaged, I hope to some profit.
The meeting adjourned to afternoon, and ended solidly.

"`11th.--Staid the week-day meeting, and was again largely exercised in testimony,
and appointed a meeting at six o`'clock in the evening: dined at W. Jessop`'s,
and had a singular time after dinner with a number of youth.
A tender young man came also to pour his afflictions into my bosom.
The meeting was a very trying one; it seemed to me, much of the time,
like fighting with beasts at Ephesus, of which Paul speaks.
I was much distressed: one tender woman, however, came to me after the meeting broke up,
which was some consolation.

"`12th.--Arose this morning with desires to push on,
trusting in the arm of all-sufficient strength to support in further trials.
We had Samuel Fielding for a guide,
the young man who kindly accompanied me before
when I set out from this place for Sheffield.
We got to Preston about five o`'clock, and notice was given of a meeting at seven,
which was pretty large and satisfactory.
I stopped the little company of Friends after it, and had another tendering time.

"`13th.--Rode thirty-two miles to Liverpool, and got into Robert Benson`'s in good time:
here we found Sarah Harrison, Christiana Hustler and daughter, etc.
Met with a very kind reception from my dear friends Robert and S. Benson.

"`14th, first-day.--To meeting, and for the first time,
had my mouth opened in public in this place.
It was a pretty relieving time, and at the close I appointed a meeting at six o`'clock,
which was well attended, and I was largely exercised in testimony,
on the necessity of being prepared for death.

"`16th.--Attended the monthly meeting, where a share of labour fell to my lot.
After dinner went with Sarah Harrison and John Hall to
the vessel in which they think of embarking,
and with Martha Routh, Christiana Hustler, my companion, and several others,
we had a solid time.
I knelt in prayer for them, that the good hand might go with them,
who were set at liberty, and preserve my life in this land,
if a portion of the bitter cup is yet to be drank.
Dear Martha Routh spoke encouragingly to me respecting my bonds being broken.

"`18th.--To meeting, where several testimonies were borne,
but I was shut up in silent exercise and conflict.`"

[.offset]
The following is taken from a letter received from his friend Ann Crowley, dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Shillingford, Seventh month 18th, 1799.

My mind has been so much with my beloved friend`'s exercised spirit of late,
that it seems as if I could scarcely forbear, in sisterly freedom, testifying the same,
with the heartfelt expression of continued love and sympathy.

From the information received a day or two back,
it appears uncertain whether any communication of this
sort may reach your hands this side the Atlantic;
but as I am well aware,
travellers are often detained longer than they may at first expect,
shall venture to send one more letter,
acknowledging the receipt of your kind testimonials of
continued affectionate remembrance;
both which came safe to hand, and met a welcome reception.
I renewedly thought the comparison of the wise man was indeed just; '`Words fitly spoken,
are like apples of gold in pictures of silver,`' so valuable and precious.
May the God and Father of all our mercies, favour with an increase of living,
saving faith, to believe the encouraging language administered in the needful time;
for verily, my beloved friend, I can assure you,
your expressions were so well adapted to the state of my mind,
that I could say of a truth, Deep utters unto deep.
Oh! the blessed privileges true gospel ministers possess;
my mind is bowed at this very season,
under a fresh sense thereof--these are made present in spirit, though absent in body;
can feel the suffering state of exercised mourners in Zion,
and dip into sympathy with such, under their probations, and thereby are often enabled,
in the wisdom of Truth, to hand forth words in due season,
which so effectually reach the witness, as to raise this acknowledgment,
'`It is the Lord`'s doings, and marvellous in mine eyes.`'
I have had frequent cause to adopt this language,
and admire the mercy and goodness of a kind Benefactor,
who has liberally conveyed counsel and encouragement,
through the medium of his chosen servants,
when they have known nothing of my mournful state, but by the revelation of divine light.
These are favours that loudly call for perfect
dedication of heart to the noblest of causes,
even that which is dignified with immortality and crowned with eternal life.
I feel renewed desires raised in my soul, that a fresh supply of those heavenly gifts,
which only can qualify for the Lord`'s work, may be mercifully granted,
that the remainder of my days may be employed to his honour;
who is worthy of all praise and adoration, forever and ever.
Amen.

I heard, a few days back,
my endeared friend has a prospect of a speedy release from further service in this land:
the thought of your departure, without the privilege of another personal interview,
feels trying; nevertheless,
if your great and good Master is pleased to liberate your deeply exercised spirit,
from the conflicts and trials which have fallen to your lot in this land,
and set you at liberty to return once more to beloved relatives,
my heart can feelingly say,
'`Loose him and let him go:`' and may the God of all grace and consolation go with you;
crowning your labour of love with that peace and joy, which man by nature knows not of.
Your exemplary patience and resignation under the proving,
trying dispensations allotted by unerring wisdom, for wise purposes,
hid from the natural understanding, have been, and will I trust, remain to be,
lessons of deep instruction to my frequently discouraged mind; and I am bold to say,
from what I feel, that many have abundant cause to acknowledge with myself,
that it has indeed been good for us,
that we were mercifully favoured with your instructive,
edifying company,--it has often preached the loudest language words can set forth.

It is likely my beloved friend will have heard before this reaches his hands,
that I have parted with my credentials,
and am for the present set a little at liberty from the
arduous engagement of visiting the churches.
It was no small exercise to my mind before a final conclusion took place;
many fears presented lest I should be unwisely, in the will of the creature,
drawing my shoulders from the burden, and my hand from the work assigned;
but with deep humility and thankfulness of heart I can say,
peace has been the clothing of my mind since the determination;
and this language sweetly arose in my heart on reaching my home, '`Return unto your rest,
O my soul, for the Lord has dealt bountifully with you.`'

The last account I received from my late beloved companion P. S.,
her health was somewhat improved;
a Friend from York monthly meeting has obtained a certificate to unite in further
service,--I trust it will prove satisfactory and relieving to them both;
and that my dear friend, and late fellow traveller,
will be enabled to complete her visit of love to Friends of this nation,
to her own solid comfort and peace,
and to the edification of the churches where her lot may be cast.
I am comforted in believing she is provided with
a friend more capable of assisting her many ways,
than I had ability for; but I trust I endeavoured to do my best,
though conscious of having lacked, through the prevalence of much weakness,
both of body and mind.
Though my body is now exempt from the constant fatigue of travelling,
my mind continues in daily exercise,
and perhaps never more deeply dipped into a secret engagement of heart for poor Zion;
being sensible her ways mourn,
because so few come up with holy dignity to her solemn feasts.
Please to accept of as much love and sympathy as you can,
from one who sincerely covets your preservation, comfort and peace,
both in time and eternity; your friend and exercised, poor sister,
says farewell in the Lord; so be it says my soul,

[.signed-section-signature]
Ann Crowley.

--

"`21st, first-day.--I had considerable labour in meeting today,
to stir Friends up to a sense of duty,
especially that of diligently attending week-day meetings.
Put off the afternoon meeting until six o`'clock; which was largely attended,
and a very laborious time to me.
I had to remind them of the grave, and to declare against atheism and deism;
returned home heavy, not having obtained that relief which my soul longs for.

"`22nd, second-day.--After an opportunity with this large family and other Friends,
I took leave, and got to our friend John Bludwick`'s a little after five o`'clock,
and at six went to a public meeting.
It was laborious to me, feeling unwell and fatigued in body, and low and tried in mind.

"`23rd.--To meeting at ten o`'clock, and was soon broken into tears of contrition,
in contemplating the Lord`'s dealings with me.
I wept, and said in my heart, I desire to trust you still, my Lord and Master;
and afterwards stood up with a tendering testimony, which I hope was to profit,
feeling nearly united to a tender remnant; some of whom, I trust,
are among the beloved youth.
When will my bonds be broken, and my captive soul set at liberty; wait on your God,
who is all-seeing and merciful.
Rode to Manchester after dinner, accompanied by Samuel Forster,
and put up at R. Routh`'s. John Thorp came and spent the evening pleasantly with us,
and I felt cheerful.

"`24th.--Went to meeting and sat two hours in silent poverty,
and after it had a pretty tendering time.

"`25th.--After a wet ride of twenty-five miles we got into Huddersfield.

"`26th.--Rode about three miles with my kind companion John Bevans, and then we parted,
urgent business calling him home.

"`28th, first-day.--Attended morning and afternoon meetings at Ackworth,
which were comfortable times, I hope to most or all; and in the course of the evening,
after a portion of scripture was read to the boys and girls,
I had a time in testimony and supplication.`"

[.offset]
From the 28th of the seventh month to the 4th of
the ninth month he remained at Ackworth school,
seeing no clear opening into any other service.
From his daily notes during that period,
he appears to have been very constantly occupied in attending upon the scholars,
with whom he had many tendering religious opportunities.
His labours of love, and kind advice and sympathy,
with those who had charge of that institution, were strengthening and acceptable to them.
Under date of eighth month 21st, he wrote as follows;
which appears to be a summary of his labours there, both before and after that date.

"`Eighth month 21st,
fourth-day.--It is now more than five years and three months
since I have seen my place of abode in Philadelphia,
or my parent, wife and children.
Many painful days and wearisome nights have I passed through in this land.
I awoke this morning with greater quietness and
sweetness of mind than frequently has been the case,
and in this humble, quiet frame, my will was resigned up to the divine will.
I have spent some weeks in this place,
and do not know that there has been so much health of body experienced,
for the same length of time, in this land.
I have visited the schools almost daily,
and have taken delight (at least as much so as my exercised state of mind would
bear) in instructing some of the children in reading and writing--have played with
them a little at times--mixed with the boys and girls in their walks in the yard,
in pleasant conversation, and also been favoured with tendering religious opportunities,
not only in meetings, but in the collecting rooms.

"`When I view my situation, when I consider the distance I am from home,
how long I have been absent, the afflictions I have passed through,
and also those of my family, especially this time twelve months ago,
with the pestilence invading their dwellings and taking off my
precious daughter--my companion in life reduced to a low state,
by complicated trials in this long absence--a dear mother nearly eighty years old,
and in a childish state;--my heart has been sometimes almost overwhelmed.
I hastened from Scotland to be ready, if any opening presented, to go home;
but here I am yet, as a prisoner in bonds, and I humbly hope, resigned to my allotment.
Often have I been in distress unutterable; and I thank my God, my helper and preserver,
for support hitherto, and for so much ease and quiet of mind in the present moment.
And now seeing no way opens with clearness to leave this land, what can such a poor,
abased servant do, but with humility acknowledge,
that great and marvellous are your works.
Lord God Almighty, just and true are all your ways, you King of saints;
shall I not then fear before you and glorify your name?
O yes,--grant it may yet be permitted,
even if it is your will to try my faith and allegiance still further
in this land,--even if I must yet appear vile in my own eyes,
and the eyes of others: Lord, grant that your servant may take courage,
and set out again under this resolution, whenever you may be pleased to open the way;
and my soul craves that I may be able to leave my toil about my absent family,
and commend them to your Providential care and regard, whether in life or in death.
Grant this for your name and mercy sake, through my suffering Lord and Saviour; Amen.`"
