== Chapter XI

On the 9th of eighth month, he addressed a letter to a Friend,
about entering on a religious visit, from which the following is extracted:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ackworth school, 9th of Eighth month, 1799.

This morning, in my lonely, exercised state, you, my beloved friend,
came fresh into view, and your prospect, as contained in your last,
of setting off soon on another visit to the churches,
if approved by your monthly meeting, has frequently, since you wrote me,
exercised my mind with thoughtfulness and solicitude on your account.
I am sensible that it is a weighty and necessary
thing to experience a right putting forth;
and when out on visits of this kind, to know where, and what, and when,
to offer our gifts;
as well as to be favoured to steer a steady course
through all the ups and downs which are to be met with;
to bear with becoming patience those dispensations that
tend deeply to humble and abase the creature;
and also to view with an eye kept single,
some of the pleasing prospects that may at times await.
Many are pleased when the servants have a song,
and they can be delighted with and in some degree joy in it;
they see a beauty and comeliness, and gather near, and are ready to say, Well done.
And a few there are that can go, and are willing to set down by the waters of Babylon,
and sympathize with those whose harps are hung on the willows.
If you are set at liberty by your friends to proceed on this journey,
my soul craves ability to say, Go in this your might,
and the Lord accompany you by his goodness,
and preserve you on the right hand and on the left,
through all you may have to meet with,
and bring you back again to your father`'s house with peace in your bosom.

As to myself, here I am, left by all my friends,
and yet through favour my mind has been supported so far,
and borne up with a comfortable degree of cheerfulness;
perhaps my being so much among the dear children has helped:
we have experienced many tendering opportunities,
both when separate in their own apartments,
and also together in meetings.--came here from Leeds on third-day evening,
and requested a meeting next day, which was held, and after dinner, he,
with his companion took post chaise for Doncaster.
It was some comfort to my tried and shut up mind to hear say,
that I was in my place by staying at this institution;
feeling at the same time a little secret evidence also in myself,
has had a tendency to settle and balance me.

I see no opening to move: is not such a dispensation proving?
Who, just placed in my circumstance, for more than two years past,
to say nothing of what I passed through before, even a stronger bodied,
and stronger spirited man than myself,
but what would acknowledge his measure was nearly full?
But stop,--does not this border on murmuring and
repining at the dispensations of Providence?
Forbid it, O my soul! sink down to your Rock, your Creator, and crave ability to say.
Not my will, but yours, O God, be done.

I have lately written both Sarah Harrison and John Hall a farewell salutation,
but know not whether they have yet sailed.
And am thankful I feel so quiet and easy with respect to their leaving me.

--

"`Ninth month 4th.--Went to High Flats with James Buck and Jonathan Binns,
and on the 5th attended the select meeting, which was a poor time indeed.
To the monthly meeting, and sat the forepart through in distress and sorrow,
but when the meeting was emptied of strangers, I had a relieving time;
for my mind was exercised with a sense that love and unity were lacking:
considerable tenderness appeared.
After dinner met two old Friends who were at variance, accompanied by several others,
and got them so near again before we parted, as to take each other by the hand.

"`6th.--Rode to Sheffield, and on the 8th, first-day,
attended the morning and afternoon meetings, which were large,
and open times in testimony, to my admiration,
after having lately felt so poor and stripped.
Dear Thomas Colley is a beloved brother, and much in sympathy with me.
I ventured to appoint a meeting to be held tomorrow evening at six o`'clock.

"`9th.--Cast down, but I hope not forsaken.
Lord, help through this one day more.
Attended a large meeting in the assembly room at six o`'clock, where I had much labour;
it was quiet and solid, but I felt very poor after it.

"`10th.--O for strength and courage to hold fast a little longer, and say,
Your sovereign will be done in all things.

"`12th.--Awoke in deep thought, and prostrated myself in prayer.
The secret cry still is, '`How long, O Lord, how long?
and yet in the midst of all, and through all,
there is an invisible sustaining hope--thanks be to the God of my life,
or else I should have fainted before this time.
Went to the week-day meeting, and was comforted under the ministry of E. Hoyland,
and afterwards appeared in the same line.

"`15th,
first-day.--In the morning meeting had much
labour,--in the afternoon silent as to testimony.
It was very large.

"`19th.--To meeting, and had a laborious time among Friends.
In much weakness appointed a meeting to be held at six o`'clock, for apprentice lads,
both Friends and others.
The house was filled up, and there were some in the adjoining room.
It proved a quiet time, and ended so,
considering how many raw boys of different descriptions were together;
and I felt relieved.
At the close I appointed one to be held tomorrow evening, for females only.

"`20th, sixth-day.--I feel easy and resigned, which is a mercy.
The evening meeting was pretty full, and although many, and perhaps most of them,
were raw, and very likely, much unacquainted with our manner, yet it proved a solid,
and I trust, edifying time.
I obtained much relief, and did not know but it might be the last meeting.
It so happened that there was a meeting appointed at the same time in the adjoining room,
called the card room, for some card players; and Friends appeared uneasy about it,
but I felt otherwise, and matters worked round pleasantly--they gave way,
and some of them stood at the door most of the time of our meeting,
and conducted themselves civilly.

"`22nd, first-day.--The meeting was large and a precious solid time,
for which I know I ought to be thankful.
After dinner went to Ackworth in a post chaise, and got a boy to ride my beast.
My dear friends are very kind, and I feel a grateful heart for such favours:
we got in before reading time,
and had a tendering season with the children and family collected,
and afterwards another opportunity with part of the family.

"`23rd.--Stiff and sore this morning, but easy and quiet in mind.
In the evening we had a sitting with the family and servants, which was a singular time,
and hope it will be to profit.
I went to the girls`' reading, but could say but little and could not bid them farewell,
not knowing but I must come again; such has been my exercise this afternoon.

"`24th, third-day.--Arose early and packed up my things, and got to Lindley Murray`'s,
near York, and lodged.

"`25th.--To quarterly meeting, and had a very close time in the first meeting.
Dined at Henry Tuke`'s, and had a singular testimony in a sitting afterwards.
To the adjournment at five o`'clock, which was a very trying sitting,
and a time of conflict to me.

"`26th.--To a parting meeting: I had nothing to communicate, and sunk very low after it.
I went to the girls`' school and dined with William Tuke,
and felt a concern to go to the Retreat,
a place where about thirty of our Society are taken in, being disordered in mind.
We got most of them together, and after we had sat a little in quiet,
and I had vented a few tears, I was engaged in supplication.
Returned back to the school and drank tea, and after night to Lindley Murray`'s.

"`28th.--Got to my kind friends J. and G. Jowitt`'s, at Leeds,
where I met with my dear friends Joseph and Rachel Smith, very unexpectedly.

"`29th,
first-day.--Yesterday on the road my thoughts were
turned toward the little meeting at Wakefield,
about ten miles from this place, and it came up again this morning,
but with much weakness,
and on my bed I had doubts and fears lest I was wrong in turning about to this place.
This followed me on the road to Wakefield, to which I went;
fears and discouragements surrounded me as I sat among the little company,
so that I was almost overwhelmed,
and yet at the bottom of all there was a disposition to trust my God with my all;
and I ventured to stand up with a little encouragement to a small number.
We went to John Robinson`'s and dined: I still felt low and distressed,
and also very feeble in body.
Some time after dinner, a Friend who lives next door, an entire stranger, came in:
I noticed at different times, the tears running from her eyes,
and after a time in some little conversation,
she took courage and told me what sympathy she had felt with me, saying,
she had wished to see me at this place,
but being informed after York quarterly meeting
that there was little or no probability of it,
had pretty much given it out.
I was baptized into tears, and truly it was a time of mutual fellowship, I thought,
in the bonds of the gospel.
We were all much tendered, and I parted very sweetly from them, and derived encouragement.
We got back to Leeds and attended a meeting appointed at six o`'clock,
in which I was greatly enlarged on these expressions; '`I have fought the good fight,
I have kept the faith,`' etc.
I was astonished to find such a change:
thanks be to God for his unspeakable mercy in thus breaking my bonds for the present.
Phebe Blakes concluded the meeting in prayer, such a one as I have not often heard;
she prayed for me, and that the testimony of Truth might be blessed with success.
It was a sweet meeting throughout, and I spent the evening pleasantly after it,
in company with many Friends, and had a religious time with many youth.

"`30th, second-day.--Arose with a degree of courage and cheerfulness,
and after breakfast had a singularly open time of stirring up, with encouragement,
in the family of P. N.; also a tendering opportunity at Benjamin Jowitt`'s,
and one at our lodgings.
In the afternoon P. N. accompanied me to Christiana Hustler`'s,
where we had the company of several Friends.
We dropped into silence after supper, and my mind was covered with unusual weight,
and under it I kneeled down in supplication.

"`Tenth month 1st.--Went to Manchester and attended a
meeting of ministers and elders at five o`'clock,
where I met with Deborah Darby and Rebecca Young, also M. Hoyland, from Ireland:
it was a low time to me, my exercise being great, but I endeavoured to bear up.

"`2nd fourth-day.--A very memorable day.
Martha Routh opened the meeting in prayer,
and afterwards I was favoured with an enlarged testimony.
Deborah Darby followed, and owned me as a brother and fellow-labourer,
with sympathetic expressions; and the closing part fell on me, in supplication.
The two sittings of men Friends were solid and preciously uniting: in the last,
Susanna Horne came in, accompanied by Martha Routh, and requested a meeting,
which was appointed at six o`'clock in the evening.
In this meeting I was soon brought on my knees in supplication: dear Susanna had an open,
good time, and several young ones also appeared.
A little fell to my lot near the close,
and Rebecca Young concluded the meeting in supplication, and we returned, I hope,
pretty universally rejoicing.

"`3rd.--Accompanied by John Taylor and Samuel Watkins, went to Stockport,
and had a large and satisfactory meeting at six o`'clock, in a cotton room,
where I met with M. Hoyland, who closed the meeting in prayer: lodged at George Jones`'.

"`4th.--After breakfast returned to Manchester and attended an appointed meeting,
at seven o`'clock, in Friends`' meeting-house, which was large and solid.

"`5th.--Dined at R. and H. Barnard`'s with Deborah Darby and Rebecca Young,
and afterwards had a solid sitting,
wherein dear Deborah was sweetly drawn forth in testimony.
I felt her sympathy, and ventured to conclude the opportunity in prayer.

"`6th, first-day.--To meeting at ten o`'clock, which was pretty much filled up,
although a rainy time, and I felt considerable openness to the people.
The meeting at six o`'clock was full, both houses being open,
and a very solid opportunity it was, and much to the relief of my mind.
John Thorp appeared in prayer, and John Taylor in testimony;
and both of these Friends came afterwards and spent the remainder of the evening with me.

"`7th.--Comfortable and easy this morning; feel relieved in good degree,
and desire to stand open to further presentations of religious duty.
A rainy day, and spent it mostly within doors: no opening to appoint another meeting,
and feel content, I humbly hope and trust, in the divine will.

"`8th.--Exercised in looking over the inhabitants of this town,
and went with Friends to look at several large buildings with a view to a meeting.

"`9th.--To a week-day meeting, and silent;
thought much of a public meeting to relieve my mind.
After tea felt an opening to give liberty to invite the people,
tomorrow evening at six o`'clock, to Friends`' meeting-house.

"`10th.--After breakfast walked to Daniel Holt`'s, a mile and a half out of town,
with John Thorp, and dined:
went to see his cotton works--he and partners employ six hundred persons.
The evening meeting was large, and though laborious, ended solidly;
many of the principal persons of the town came.

"`11th.--A conflicting time before I left my bed,
but upon endeavouring to resign all up to boundless mercy and goodness,
I felt easier and relieved with respect to the inhabitants of Manchester.
O what wadings I have to go through sometimes,
before I can appoint and get through but one meeting.
Set off about eleven o`'clock with Isaac Hadwin, in his chaise,
and arrived at our friend John Wood`'s, at Bolton, about one o`'clock,
there being a meeting appointed at six, to be held in a barn which was long in gathering,
but concluded solidly and satisfactorily.

"`12th.--After a tendering opportunity in John Wood`'s family,
with several who stepped in, Isaac Hadwin brought me to Liverpool, about thirty miles,
and arrived about five o`'clock, and those dear friends, Robert and S. Benson,
received me once more under their hospitable roof, with much kindness.
After supper we dropped into silence, and in it my mind was sweetly calmed and refreshed,
and hope some of us were baptized by the one true baptism,
and enabled to drink into one spirit in a good degree.

"`A paragraph in the paper today, states that a letter has been received from Baltimore,
giving an account of the fever having broken out in Philadelphia;
and that in consequence, the public offices are all shut, and the city nearly deserted.
It is an alarming account, but I am not disposed fully to believe it.

"`13th, first-day.--To meeting, and was comfortably opened so as to relieve my mind.
Susanna Horne appeared in supplication for infidels, etc.
The afternoon meeting was put off until six o`'clock, and was large and laborious,
yet pretty comfortably relieving.
When I got into Robert Benson`'s after the meeting,
an exercise which had impressed my mind since leaving Manchester quarterly meeting,
of going to Ulverstone, revived so pressingly, that I opened it to my friends.

"`14th.--Set off between ten and eleven o`'clock,
accompanied by Robert Benson in his chaise, and lodged at Preston.

"`15th.--We arrived at David Dockray`'s, at Lancaster, before dinner,
and found there was no crossing the sands to Ulverstone this day.
In the afternoon took a walk with my companion and John Dockray to see the castle.
We saw the room where they say George Fox and others were confined.
Thanks for so quiet and resigned a mind;
and my soul craves ability to advance in the Christian race,
so as to be able to adopt the Apostle`'s advice; '`ln everything give thanks.`'
Surely there is occasion so to do, when I can only believe with tried Jacob;
'`The Lord is in this place.`'
The Lord has been near my soul when plunged in the deeps;
when wave followed wave,--when the weeds were wrapped about my head.
O for continued ability to say in sincerity, and in deep abasement and humility,
'`Your will, O God, be done.`'
Subject mine unto it--then let what will come, your name will be sanctified,
and my soul purified in the furnace of affliction.
Grant this, for your name and your mercy sake.

"`16th.--Was called up about half past four o`'clock, and between five and six set off,
accompanied by George Barrow:
we crossed the sands and got to Ulverstone near an hour after meeting time;
it was much such a season as at this time two years ago.
Some time after I sat down, I went on my knees and prayed for poor mournful Zion,
that her gates, yes, her very dust, might be remembered,
and afterwards told Friends I had a prospect of a better day,
and held forth encouragement to old and young.
After meeting I went to the old house where Judge Fell lived;
and being told that the widow and children whom I visited when here before, had removed,
and that the man who took the place died about two months ago, and has left a widow;
I called to see her,
but she appeared very raw and very little of that tenderness so manifest in the other,
who to my comfort continues loving to Friends.
Attended a full meeting in an assembly room at six o`'clock.

"`17th.--Set off in a post chaise, and had a very pleasant ride to Kendal,
and gave liberty to invite the neighbours together at six o`'clock,
in which I was as open as I had any expectation of, although not large;
however my mind was relieved.

"`19th.--Reached Liverpool about four o`'clock, after a pleasant ride,
and I feel satisfied that it was right to go this little tour.

"`20th, first-day.--Attended the morning meeting,
where my friend Susanna Horne had considerable labour in a close line,
and some also fell to my lot.
Appointed a meeting at six o`'clock and requested
friends to give notice to the upper class of people,
slave importers, etc.; it was large,
and a number of the description I wanted to see attended,
and it was a relieving opportunity.

"`21st.--All seems closed up with respect to
Liverpool;--I desire ability to say in sincerity,
'`Not my will, but yours be done, O Lord.`'

"`22nd.--Awoke in sorrow of heart.
O that it were the Lord`'s will this mountain of exercise might be removed.
But if there is yet a measure, even of more bitter suffering to be filled up,
may my soul be favoured to say, your will be done.
Purge me from iniquity, and extend your mercy, O Lord, or I faint and fail by the way.

"`24th.--Awoke early, and trouble awoke with me.
I was as a spring shut up, a fountain sealed.
Attended week-day meeting,
and on returning endeavoured to anoint my head and wash my face,
and ate what dinner I could; and afterwards my soul was exercised,
and venturing to call the family of my dear friends Robert and S. Benson together,
I poured it out in supplication for ourselves as travellers, for the parents, children,
and servants, and for the inhabitants of the town; and then set off,
accompanied by my friends Susanna Horne, Joseph Smith, and John Hadwin to Warrington.

"`25th.--Joseph Smith and James Foster accompanied us to Leek: we put up at T. Chorley`'s,
and although he is gone to London, we were kindly provided for:--a day of great exercise,
in which the cry of my soul has been, Lord, help through and over all,
that I may not be swallowed up.

"`26th.--Struggled along through this one day more--got into Derby before night,
and found several Friends there from Nottingham.`"

[.offset]
The following is extracted from a letter addressed to him by his friend Sarah Talbot,
from America, then on a religious visit to Friends in England;

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Warrington, seventh-day morning, Tenth month, 1799.

[.salutation]
My dear friend, Thomas Scattergood,

I received your letter yesterday morning, and it was very gratifying to me,
but it would have been more so to have had an interview with you;
but pleasant things are not always best for me.
I feel much for you and do sympathise with you, believing you to be greatly tried;
but it is in my heart to say to you, '`be encouraged, and trust in God;
for He has been your helper,
and I verily believe will continue to help you through all and over all,
to your peace of mind and His own glory.`'
Therefore, my dear friend, have patience and stay your appointed time for your release;
which I believe you wilt be favoured to see with clearness,
when your great and good Master shall say you have done enough; for I verily believe,
all things will work together for good, unto all those that love and serve God.
My hopes and fears have been more than they ought to have been,
about your going with me across the sea; but when I may go, I know not,
for I expect the Liverpool packet will sail before I am ready, if it goes in one week,
as we have eleven meetings yet to visit, which will take us nearly two weeks.
When they are visited, I have thought from the feeling of my mind,
that I might be at liberty to return home,
and no Friend`'s company in England would be as acceptable to me as yours.
If we had been informed that your stay at Warrington had been so short,
we should have met you there, but it is now over,
and I feel a hope that we shall meet when our
religious labour in this land is accomplished,
in the enjoyment of sweet peace of mind: yes, my dear friend,
I verily believe this will be your experience, if you abide in patience.

--

"`27th, first-day.--I said in my heart,
how is it possible to get through the meeting I have appointed?
To believe and trust, when hope is cut off;--'`our hope is cut off,
we are like a dry withered branch.`'
Language fails to set forth my state this morning,
and yet I went to the meeting appointed, and laboured largely.
This is a mystery indeed, and I thought myself a very unworthy creature.
In the evening we had the little company of Friends in this place together,
in an upper chamber at the Bell inn.
It was a singular time, and my companion was opened with much clearness;
some labour fell to my lot; and now, after supper,
I feel much lightened from the burden and oppression I have waded under for days.
'`Hope deferred makes the heart sick.`'
How thankful I feel for this little ease:--Lord, my God, your will be done.
You have an undoubted right to do with your creatures as you please.
Take not your Holy Spirit from me; take not your loving kindness from me.`"

[.offset]
In a letter dated eleventh month 4th, to his son, he says;

[.embedded-content-document.letter]
--

There are several in Derby who have applied to be taken into membership,
there being a little company who have met in the way of Friends for some time past.
When I was there two years ago, I visited them in their families,
and one of the oldest now tells me,
that the number who meet has increased in these two years to double.
It has been a comfort to my often depressed and exercised mind, to find here and there,
by going over the ground again, some fruits--some convincements: the Lord be praised,
whose work it is.

--

[.offset]
After some remarks respecting returning to America with Sarah Talbot he says;

[.embedded-content-document.letter]
--

I had set my mind on going with her as much as was profitable, and how it may be yet,
is uncertain.
Let us all endeavour to dwell in faith and patience.
I have been marvellously tried about home, the sickness at Philadelphia, etc.,
and when favoured to resign all up, there has been a comfortable portion of peace.
I desire to stand in my allotment,
even though it has been in the watch-tower in the day time,
and as it were in the ward whole nights.
The Lord restrain the murmurer and repiner,
and mercifully keep me on the bottom and ground of truth, in and through all;
that neither winds, nor rains, nor floods may overturn my foundation.
I think I can say with uprightness, it is my desire to get home in the Lord`'s time,
not my own; whose servant my soul desires yet to remain.

--

"`28th.--Took an affectionate farewell of the landlord,
whose heart is much opened towards me, and arrived at Litchfield about three o`'clock,
and my friends who accompanied me, with Richard Leaver,
were industrious in getting a place to meet and inviting the people.
This meeting was held in the town-hall, and a great concourse of people there was,
and much was on my mind to express,
although in a weak state and still under great exercise of mind.

"`29th, third-day.--Moved on to Birmingham and had an evening meeting;
many of the people attended, and here again I had much labour.

"`30th.--This morning set off early by coach for Chippingnorton, and after breakfast,
accompanied by George Boon, I went to Worcester and had an evening meeting;
it was laborious, and I felt unworthy to move in this line.

"`31st.--Accompanied by Richard Burlingham and nephew,
went near forty miles to Chippingnorton, a meeting being appointed there;
felt very low and poor indeed, and was content in silence,
my friend having most of the labour.

"`Eleventh month 1st.--My beloved friend William Hull having met me last evening,
I rode with him to Oxford.
How shall I describe my feelings of late;--I am now at an inn in this place,
a lonely poor pilgrim.
One more meeting appointed at Jordans, and my feelings, I think,
resemble those of the poor woman, who was gathering a few sticks to bake her last cake,
and then lie down and die, as she thought.
How did Ezekiel feel when he baked the cakes and ate them?
and when he lay so many days on his side, bearing the sin of Israel?
O why am I a man of such sorrow?
Is it all a fruitless thing?
Lord, God, almighty and powerful, who can resist your will?
Look down in mercy upon me, a poor stripped creature, and help me through all,
and over all; for I faint and fail without you.

"`2nd.--Went to Adey Bellamy`'s, at High Wiccomb, and was kindly cared for,
and I felt more ease of mind: many friends called in the evening and sat with us,
among whom I had some religious communication.

"`3rd, first-day.--Had a pretty full meeting at Jordans,
but almost all was sealed up as to myself.
My friend Susanna Horne had considerable to communicate,
and appeared also in supplication.
I advised the people at the close of the meeting, to inquire for,
and read the writings of Isaac Penington, William Penn, and Thomas Ellwood,
who very probably had often sat in this house, which is now mostly deserted and shut up.
I told them, likewise, of instances where meeting houses had been closed for a time,
and that by the religious concern of one individual only,
who felt it a duty to go and set alone to worship the Almighty,
the meeting had been revived and numbers added.
Most of the people appeared very raw; my own conflict was great,
and my situation trying indeed.
After the meeting we proceeded to Uxbridge,
and put up at Samuel Hull`'s. Parted from my beloved sister, Susanna Horne:
she proposes going to London with S. Hull,
having her mind charged with a prospect of a family visit to Grace-church street meeting;
may the Almighty go with and help her through this and all others,
and give her a reward when the race of life is run, is the craving of my soul.

"`4th, second-day.--After resigning myself quietly to stop here,
I lay down pretty comfortably: awoke, and lay about two hours in deep thoughtfulness,
and yet accompanied with more than usual settlement and quiet.
I took a retrospect of my journeying and prospects of later months,
having now got through what opened sometime back, concerning Manchester, Liverpool,
Derby, Litchfield, Worcester, Chippingnorton, and Jordans;
and though my soul has been let down very low, I thought,
how could I have done otherwise in my journeyings.
Deep were the searchings of heart, in looking over my steppings,
and I besought the Lord for a covering of mercy and love;
and that I might be favoured to experience more settlement and peace.
My wife and home, etc., came up, and my soul craved ability to offer up all,
and that my feeble desires might meet with acceptance before the throne.
Is there a baptism for me to be baptised with in this land, in London?
Is there a cup to drink of; and am I yet to remain a prisoner in bonds?
Lord, only grant me remission, wash away all guilt and stain,
and receive me graciously into favour,--point out the way and go before,
and behold your servant, your tribulated servant,
be it unto him according to your will and your word,
in further steppings along in this land,
and grant that I may clearly see the time to leave it, and that it may be in peace,
after so many years of deep conflict.
All this you can accomplish--do it in your own way and time,
and humble my soul into submission to your sovereign will.
I thank you.
Lord and Master, for support in the deepest trials; yet with blushing and confusion,
when I view my strugglings and lack of fully exercising faith.
O extend your free mercy:--O Lord, protect and preserve my children;
let them be yours in life and in death.
It has been a day of some ease, from that oppression and death often felt.
I endeavoured to anoint my head and wash my face.

"`6th.--Attended week-day meeting,
and was favoured with a comfortable degree of calm upon looking over my accounts;
but much humbled.
Stood up in the latter part of the meeting and had some religious communication,
which appeared to have a tendering, humbling effect,
and I felt quiet and calm after it.`"

[.offset]
The following is an extract of a letter, addressed to his beloved friend Susanna Horne,
dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Uxbridge, eleventh month 6th, 1799.

[.salutation]
My dear friend,

I know it is an arduous work to visit families, yet believe it to be a blessed one,
and it has proved so to some.
Take up then your penny received, after getting through the meeting; it is lawful,
and sometimes expedient so to do, and view it carefully, and observe the image;
a small piece with the King`'s stamp, is sufficient.
May your Divine master grant you a larger portion, if it be his will,
when you have performed this present engagement.
Be faithful in the work, remembering it is not a concern of yesterday;
fear not with man`'s fear, least you be confounded.
Your soul has been humbled of late--may such dispensations fit you for the Lord`'s work;
you must expect it will be so.
These humble ones are taught in the way often times, though it is a trying one,
and the meek are led in the paths of judgment.
I have been a tried man since we parted, and you know much so since we left Liverpool;
and through mercy I hope my all is given up.
I told you no way opened further than this place, and so it remains.
It seemed like coming up to a wall, without a gate way through.
O may my poor oppressed soul yet trust in God,
and wait patiently upon him all the days of my appointed time, until a change come.
My love to your dear father, and tell him I have a hope I shall yet see him,
and be with him to our mutual comfort and consolation; the Lord grant it may be so,
and that we may obtain a mansion of rest together,
when done with the fading enjoyments of this world; this is not the thought of a moment,
but at times, when further absent.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Thomas Scattergood.

--

"`7th.--To High Wiccomb monthly meeting, accompanied by Samuel Hull in his chaise.
I went in a humbled state, and sat along side of my dear brother George Dillwyn.
My soul craved a seal of some encouragement,--and was favoured with a view,
that the great and good Master would bring to pass his purposes,
which at times had opened on my mind, in which I felt calm and content;
and after dear George got through his exercise in the ministry,
I kneeled down in supplication, and felt calm and easy through the business.
After dinner a number of friends came in, and my mind was stirred up to speak,
and tenderness and brokenness appeared.
I had to address M. E., who is in a very low state,
and now lives separate from her husband and children.
Rode to Amersham and put up at R. E.`'s.

"`8th.--Dined at E. Raper`'s with George Dillwyn and wife and others,
after which we were favoured with a comfortable uniting opportunity together.
Soon after this returned to Uxbridge.`"

[.small-break]
'''

He remained in Uxbridge until the 21st of the twelfth month,
and at times in a very exercised state of mind,
in consequence of having no clear opening to move in any religious service.
Several prospects presented during this period, but were either soon removed,
or did not continue with sufficient weight and clearness,
to induce him to believe it would be right to pursue them.
In this tried state, his prevailing desire appears to have been,
to be favoured with patience and resignation to the Lord`'s will,
and to be preserved from doing or moving, except under Divine guidance.
He appears, however, to have been impressed with a belief,
that he should be obliged to go again to London,--which with the remembrance
of the trials and deep baptisms he had passed through in that city,
about a year previously, no doubt had a tendency at times to depress his spirits.
Notwithstanding this prospect was extremely trying,
he was earnestly desirous of performing faithfully the whole
service which his Divine master required of him in that land,
which led him often to pray for Divine direction,
though frequently silent in the meetings, which he regularly attended in this place;
yet he appears to have been, at times, very considerably enlarged in them,
as well as in private opportunities; many of which he describes as solid,
tendering While here, he received the following letter,
giving an account of the departure of Sarah Talbot for her native land:

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Talbot to Thomas Scattergood

[.signed-section-context-open]
Liverpool, eleventh month 10th, 1799.

[.salutation]
My dear friend, Thomas Scattergood,

Your acceptable letter I received since I came here,
where I am waiting for the wind to change,
it being contrary to leave this port for America;
for which I now think I feel at liberty to embark in the Liverpool packet,
bound for New York, which it was said was ready to sail when we got here,
and the Captain said he would sail yesterday a week ago;
but when we came to Robert Benson`'s, found to the contrary,
and have been endeavouring to get ready.
I believe I shall be at liberty, for anything that I now see,
to leave this land with peace of mind;
though I do surely know that I am a poor unworthy servant,
if worthy to be called a servant, and have not anything to boast of, no verily;
yet may say to you, my beloved friend and brother,
that the peace and quietude of mind I have felt since I came here,
have bowed my heart in thankfulness before Him who has been with me,
and helped me to do the work appointed: and I verily believe He will be with you,
and enable you to do his will: your work is great in this land,
and if it should be lengthened out some time longer,
may you be favoured with patience to hold out to the end,
for it is the end which crowns all.
If it had been the will of Him who knows all hearts,
and undoubtedly orders all things right,
that you and I should have gone together over the waters,
it would have been very desirable to me to have had so dear a brother on the seas;
but how different is it likely to be: no friend or acquaintance going, and but one woman,
and she as a steerage passenger;
so you may see that I am likely to have a lonely time of it,
but I feel resigned and not much discouraged,
and hope that He who cares for the sparrows, will care for me.

--

[.offset]
Her companion, Sarah Shackleton, adds:

[.embedded-content-document.letter]
--

Although I feel myself in a very bereaved state,
and as much as I can do to keep up a suitable appearance,
having lost a precious companion, whom I have experienced to be a nursing mother,
who preached continually to me in the expressive language of example;
yet I am unwilling to detain her letter, or the news of her being on shipboard.
Orders were received to come on board, for the ship was on her way,
while we were sitting quietly at our work yesterday morning.
It was thought best for no friend but Robert Benson (who was the only
man friend there) to go with her in a boat to the ship:
we saw her safely on board, and the vessel sail beautifully down the river,
on a very smooth sea, but had not been long returned to Robert Benson`'s,
before an awful storm came on, which continued several hours.
I should have been thankful either to have had her here, or to have been with her there;
we suppose the ship has cast anchor at the Rock, about three miles from this place.
Perhaps I may have more certain intelligence before I need seal this.
The sky begins to look again as it did yesterday evening,
and I expect another storm is coming: how distressing to have her lying so near us,
and she without an intimate friend to speak to.
She reminded me yesterday of an obedient dependent child,
throwing itself into the arms of its father,
trusting that he would protect from all danger.

Sixth-day, 15th.--After some trying days,
we have received the agreeable news of the Liverpool packet
having really sailed away with a pretty fair wind.
I had a letter from dear Sarah yesterday, which says,
'`Before dinner was done (the 12th) the storm began; I was in my chair,
and between the table and a chest; the table was lashed, or I could not have sat:
the things began to tumble about from side to side as the storm increased,
so that the carpenter was ordered to be at hand with his axe, in case of extremity,
to cut away the mast, that the vessel might drive before the wind.
But He who cares for the sparrows, caused the wind to shift,
and then they made towards land.
On inquiry I was informed, that we were going for Liverpool, of which I was glad.
I did not think that we should perish,
but it was a very alarming time until about midnight, when we got in here.
I am not much discouraged about my companions, although we have card players on board.
Five or six vessels have been much injured, and one wrecked;
what cause have we to be thankful in being thus wonderfully preserved from harm,
only some of our rigging taken away.

[.signed-section-signature]
Sarah Shackleton

--

"`20th.--The way to London felt open and clear this evening,
and I rejoiced to feel and see it so, and said in my heart, '`Lord, if you go not with me,
take me not up from here;`' preserve me in my place.

"`21st.--This has been an open day pretty much throughout.
Left Uxbridge, accompanied by Samuel Hull, and got into Joseph Smith`'s, London,
soon after four o`'clock: felt cheerful and well on setting out, and most of the way;
but when I entered London, began to sink, and spent the evening with Susanna Horne,
Sarah Lynes and others, low and exercised.

"`22nd, first-day.--A night of exercise to what I have experienced of late;
but through all, endeavoured to cast my care on the Lord, the only sure helper,
and experienced a comfortable support.
To morning meeting at Grace-church street, under close exercise;
and stood up once more with a searching testimony in the beginning,
but toward the close I hope the oil of divine consolation ran
from the Fountain into some drooping hearts,
as well as my own.
I remembered and expressed John Woolman`'s prospect, '`that the time was coming,
when he that was wisest in earthly policy would become
the greatest fool;`' and also a prospect of a searching,
trying day approaching.
The afternoon meeting was a precious one to me, and hope also to others;
it was a time of encouragement.
I lay down sweet and easy after this day`'s work, being much relieved thereby.

"`23rd.--A comfortable night, and though when I awoke this morning,
a degree of trembling seized on me, yet it was mixed with that holy fear,
that broke and tendered my heart, in a sense of the preservations I have met with.
Attended the select quarterly meeting, and laboured therein to satisfaction;
and after it broke up, many Friends expressed their pleasure in seeing me once more,
which was encouraging to me.

"`24th.--My mind was enlarged in the quarterly meeting,
in which there were several new appearances.
The business was comfortably conducted,
and in the close I had another satisfactory time with the youth present.
Many Friends dined with us, with whom I had an opportunity to some relief.

"`25th.--After dinner my own situation came humblingly over me.
O Lord, bear me up in patient resignation, to do and to suffer your will.
Preserve me from the fear of the enemy.
My home is closed up and hid from me, and a humbling weight yet rests on my soul,
with respect to the inhabitants of this great city, and no opening to get clear of it.
May I with humility say, Why is my pain perpetual,
and my wound ceased to be healed`'.`' Why go I mourning all the day,
as with a sword piercing my soul,
and in the night season often times such trembling of heart?
You, the Almighty one, know, and my soul craves patience to endure until you remove it.

"`29th, first-day.--I attended Devonshire house meeting,
and after sitting nearly two hours, felt some openness to stand up,
endeavouring to encourage some seeking, sorrowful souls,
and felt an opening to appoint a public meeting at six o`'clock.
Went to Grace-church street meeting in the afternoon,
and had to speak encouragingly to some seekers present.
In the large assembly convened at six o`'clock, I laboured some time, but felt a stop,
and told the meeting so, believing it not right to exceed the gift and feeling;
and after a time Sarah Lynes stood up and was much enlarged.

"`31st.--O Lord, have mercy on me and save me,
seems to be the prevalent cry of my poor travailing soul.

"`1800, first month, 2nd.--When I reflect how little I am engaged in actual service,
it appeal`'s sometimes as if I was an idler away of time; but then again,
are not the conflicts I have endured for years to be esteemed labour?
It seems like the war we read of between Michael and his angels,
against the Devil and his.
O that he was cast out, and if consistent with the divine will,
my soul was set at liberty.
When in meeting there is an opening to speak, I fear to forbear, and it is a mercy,
that in this respect no disobedience comes up against me.
Rather let my life go, than that I should reproach the Truth, or dishonour God,
I went to Tottenham meeting, and was favoured with sweetness and calmness of mind,
wherein my faith was renewed in the all-sufficient power and mercy of God,
to carry me through my conflicts in this land,
and to enable me to fulfill all his requirings.
When faith is raised, which is only the gift of God, how it renews that hope,
which is an anchor to the soul.
I was thankful, and had to speak encouragingly to others; for which the Lord be praised,
and let him be waited on in all trials, and in all desertions.

"`4th.--A secret hope spreads on my mind, that the time is drawing near,
when there will be an opening towards home;
and if it is the Lord`'s will that I must leave this land without a full discharge,
and even if my foolishness appear to myself and others, your sovereign will be done.
I crave ability to trust in you, and lie prostrate at your feet.
You, and you only can change my wilderness into a more fruitful field.
How pleasant the thought of being favoured to move towards America in peace: yes,
it is pleasant to feel a disposition and willingness to trust in God,--to cast body,
soul and spirit on his goodness and power.
What are words, what are memorandums?
As respects the latter, perhaps I may have to look over them in a day to come,
and be humbled, as I feel at this present moment.
O Lord, enable me to bind your dispensations,
proving and trying to uneasy flesh as they are, as jewels and chains about my neck.
O that I might be favoured to declare in the congregations of the people,
that you are good when you give, and also when you take away.
My soul desires to say, Blessed be your name, even with tears and a broken heart,
for you are the healer of the broken in heart, and the binder up of their wounds.

"`5th, first-day.--To Grace-church street meeting,
where Sarah Lynes had a very enlarged time.
I sat content under it; her companion also appeared in testimony and supplication.
After dinner I felt so oppressed that I went up to my chamber,
and prostrated myself in awfulness and trembling before the Lord;
afterwards went to meeting, where P. Chester and Susanna Horne appeared in testimony,
and in the close, remembering the Apostle`'s advice, '`He that is afflicted,
let him pray,`' I ventured to bend once more in supplication.

"`9th, fifth-day,--To Ratcliff meeting; sat long in silent travail and conflict,
and towards the close had to speak of the trials to be met with, etc,;
my faith was revived, and I felt pretty cheerful and comfortable afterward.

"`12th.--Recruited in health this morning and my mind more at ease,
for which favour I feel thankful, I hope humbly so.
Went to Grace-church street meeting,
and am ready to think it was the very closest time I ever had in this place:
I believe some opposed and fought against the communication, but I felt easy.
Went again in the afternoon, and both on the way there, and in the meeting,
my mind felt easy.
It was a time of encouragement, there being a class present,
different from some in the morning: drank tea at William Phillips`',
and after it had a comfortable sitting.

"`13th, second-day.--Attended the morning meeting, and felt very poor;
yet in a comfortable degree quiet.
Sarah Lynes and Susanna Horne completed their visits, and I came to Tottenham with them.

"`14th, third-day.--Is it not good to dwell in a broken state, and be able to say,
Your will be done; and when called on, to be found like the spouse in the Canticles,
who says; '`I have put off my coat, how shall I put it on; I have washed my feet,
how shall I defile them?
I hope and desire to be right, and to be in my place,
even though it may be that afflictions abide me wherever I go.

"`16th, fifth-day.--Had a few words to offer in meeting from these expressions;
'`My soul is athirst for God.`'
Susanna Horne closed the meeting in supplication.

"`19th, first-day.--Sat the meeting through in silence.
Susanna Horne appeared with an encouraging testimony.
In the afternoon meeting the cloud was lifted up,
and I felt an openness and some enlargement of heart, and stood up in this sense,
with a language of encouragement to the widows, the desolate,
and the fatherless children, and spent a pleasant evening afterwards.

"`21st, third-day--A night of exercise, both in sleep and when awake:
I strove to to be resigned and bear my burden with patience,
and hope I was favoured to say, in the secret of my heart, on leaving my bed, '`Your will,
O Lord, be done;`' grant me patience to wait on you,
and that I may not bring reproach on the blessed Truth I came to promote.
Arose measurably resigned to suffer in silence.
After breakfast took up the Bible,
and on opening it my eye fixed on the seventh verse of the fiftieth chapter of Isaiah;
'`For the Lord God will help me; therefore shall I not be confounded:
therefore have I set my face like a flint, and I know that I shall not be ashamed.`'

"`23rd.--Much exercised this morning, and a sweetness attended;
went to meeting and had an open time in testimony.

"`Second month 2nd,
first-day.--It is truly cause of thankfulness that my
mind was favoured with so much calm last evening.
O Lord, my desire in the deeps has been unto you, and the remembrance of your holiness;
and the cry of my soul has been, '`Be my physician,
and heal me,`' I crave ability to resign up all, both body and soul,
to your providential care.
If you had not cared for me I surely should have fainted and failed: time is yours,
and though it appears to be a long time I have spent in this land,
and mostly in silent sorrow and suffering; yet, if you please to accept my offerings,
even in sorrow of soul, let your will be done.
I attended Tottenham meeting, and was much enlarged;
and after dinner attended the burial of the eldest son of Dr. Letsom,
where I was again opened amongst a numerous company of Friends and others, who attended,
and returned to Whitehart Lane, after drinking tea at William Forster`'s,
and having an opportunity, and was particularly led to visit a little son of J. H.,
who was much broken:
had also a religious time in the family of my dear friend Thomas Horne;
and it is marvellous it should be thus, after the distress I have felt.

"`4th, third-day.--Sweetness of mind on awaking:
my soul bows in thankfulness for this portion of ease.
Worship with fear, and rejoice with trembling.

"`7th.--O that this mountain was dissolved by the Lord`'s power,
and that more continued ease and freedom of spirit was granted:
this has been often my desire.
But stop, my tried soul, and be willing yet to suffer.
It is not suffering when we fully see and feel what we suffer for;
but when we have to live by faith alone, and by hope alone,
that that there will be a change.
O then, not my will, but yours be done, O God: all power and strength is yours.

"`8th.--Am I filling up my measure in thus moving and acting from day to day?
If I am not in suffering and pain for the inhabitants of this island,
then deceit has entered.
Lord, keep me patiently resigned to your will, in suffering; for little else can I see.

"`9th, first-day.--In the morning meeting I was silent,
and in the afternoon was opened to the youth, in a manner beyond my expectation.
Drank tea at William Forster`'s, and here again, with a large company,
I had a satisfactory opportunity.

"`10th.--To London, and attended morning meeting,
where I found Thomas Colley on a religious visit to this city and neighbourhood.

"`11th.--To Devonshire house meeting, and had an open time.
Mary Sterry closed the meeting in prayer.

"`12th.--Accompanied Thomas Colley to Peel meeting;
he spoke to a tried state from these expressious:
'`There is a life that can live in the midst of death.`'
I felt a little toward the close, to offer in the same line.

"`13th.--To Westminster monthly meeting with Thomas Colley and R. L.: I was silent.
Thomas Colley began with these expressions; '`They that sow in tears, shall reap in joy.`'

"`20th.--O London! what I have passed through in you!
Where will your haughty sons and daughters appear when
the Almighty and just One visits and humbles you?
My desire is to your name, and to the remembrance of you, O Lord, in the deeps.
I went with Joseph and Rachel Smith to Westminster meeting, and felt an opening to speak,
and relief was administered.
T+++.+++ C. and R. H. were married; I dined with the wedding company,
and in the evening had an opportunity with them.
The cloud of distress was removed for a season,
and I worshipped in prostration under this sense.

"`21st.--Quiet and resigned, I wait daily to feel my way rightly,
and it is a mercy I am not overwhelmed.
In company with my friend Joseph Smith, I went on board the ship Kensington,
bound for Philadelphia, with a view of feeling how it may be respecting going home.
After sitting alone, and weighing and considering things,
there appears no opening to make a move homewards,
although I have been six years from wife and family and friends.
It seems as though there was yet something to accomplish, and whether it be in doing,
or whether in filling up the measure of suffering;
whether more of the roll is to be eaten, or more of the little book is to be digested,
in order to prophesy, I know not.
O for patience when nothing is to be seen,
and that I may yet be preserved to walk by faith, and know purification thereby.
All things are yours, you Saviour of men, and you give as you please of your blessings;
enable me to bless your name when you withdraws or withholds.

"`23rd.--Attended Peel meeting in the morning, and had a pretty relieving time:
was at Grace-church street in the afternoon, and a very large meeting for the youth,
in the evening, wherein I had a share of labour with Thomas Colley,
W+++.+++ C. and Sarah Lynes.

"`25th.--Was favoured with an opening, tendering time at Devonshire house.

"`28th.--To Clerkenwell children`'s meeting, and an open opportunity.
My heart is thankful to feel a little change of dispensation:
may I be favoured not to abuse the liberty.

[verse]
____
"`Good when thou gives, supremely good,
Nor less when thou denies;
Crosses and exercises in your sovereign hand
Are blessings in disguise.`"
____

"`Third month 2nd.--Attended Devonshire house in the morning,
and Grace-church street in the afternoon; also the burial of a clerk, who died suddenly;
and in the evening at six o`'clock, went to a meeting in the new house at the Park;
in all which I was exercised to my own peace and comfort.

"`3rd.--I find no discharge from this warfare; but if I am an enlisted soldier,
I shall be cared and provided for.
Lord, I believe, help my unbelief.
I went with Ann Christy to Wandsworth, with Thomas Colley in company, and had a low,
silent time; there were only three men Friends at meeting.
To an evening meeting at six o`'clock, which was pretty full,
and Thomas Colley laboured amongst them.
Stopped at C. West`'s school, where I felt an exercise,
and was favoured to relieve my mind; the widow of a late lord mayor was present,
and much affected.

"`6th.--Attended monthly meeting at Croydon, where a little labour fell to my lot.
It was close to some, but hope the oil of consolation was administered to a few,
and felt by them.
O poor county of Sussex! how mammon and the wisdom of this world have
spoiled your sons and daughters making profession with us.

"`7th.--Went to Kingston, accompanied by Thomas Colley and John Townsend,
and put up at the widow Rachel Owens`', opposite the meeting-house:
we sat with three women and one man, beside three Friends from Esher.
It was a meeting of trouble to me; I sat and thought of George Fox and others,
who used to meet here, and mourned over the state of our Society;
yet felt but little or no strength to say anything.
Thomas Colley was silent, but I told them some of my thoughts.
I trust the time will come when the command, the sweet command, will be heard; '`Arise,
Zion and shine, for your light is come.
Arise, and put on your beautiful garments.`'
But there must he a shaking of the dry bones first: the Lord hasten the day,
for my soul longed, as I sat in this meeting, to behold it with my eyes.
To a meeting at six o`'clock, which was pretty large,
and dear Thomas Colley had a full time, which appeared satisfactory:
silent burden bearing was my portion.
To Esher and lodged.

"`9th, first-day.--To Wandsworth meeting, where was a company of gay, flashy people.
I felt discouraged at first; but after a time was enabled pretty fully to relieve my mind.
Various Friends came to see me in the evening, with whom I had a tendering time.

"`15th.--Felt a little opening towards Hartford quarterly meeting;
and Mary Sterry took me in a post chaise; we got to our friends,
John and Mary Pryor`'s after night, and I was unwell with a cold.

"`16th, first-day.--I was much opened and enlarged in both meetings today,
and felt some freedom in the quarterly select meeting also, which began at six o`'clock.

"`17th.--Went to quarterly meeting, and to my admiration had an open time,
though in much weakness of body.
I had to revive the memory of John Crook.
Left the meeting before it was over, and came home oppressed with a cold.
O Lord, I am yet oppressed in soul; deliver me, I pray you;
keep me in patient resignation to your will, and preserve from deceit.
How my faith is tried--how hard I find it to believe.
After an opportunity with a number of young Friends,
feel a little lightened and relieved;
but there is yet a cloud to pass through and be baptized in.

"`18th.--Stayed in all day, poorly, but pretty easy and comfortable,
for which thankfulness covers my mind.

"`19th.--Mary Scott took Mary Pryor and me to Ware week-day meeting;
several came from Hartford,
and several after the interment of a corpse in the grave yard.
Mary Pryor had a close, yet sweet time, and I felt some openness also,
though it was with difficulty I could speak to be heard.

"`20th.--After breakfast, as dear Mary Pryor and I were sitting alone together,
she began in the line of religious communication, and said,
I had been much the companion of her thoughts in the night; not in sleep,
but in wakeful moments.
Expressed the sympathy she had felt for me in my
sufferings for the inhabitants of this land,
and that she believed the time was near when I should be set at liberty to go home,
and meet a kind reception,
and be made instrumental in watering the seed in
my own land--there being a work to be done:
she said she had prayed for me, that my voyage might be safe and prosperous,
and be made a blessing to the poor sailors;
that my prospects and labours would not be lost in this land,
for I had been made instrumental in speaking of a day of trial coming,
because of wickedness; and that it was her firm belief,
the Lord would carry me through and over all, to the end, and crown it with peace.
Lord, help my travailing soul to believe, not only in you, but your prophets;
and fulfill your purposes concerning your servant.
Here am I, prepare for what you have yet for me to do, and let your will be done.
Amen.

"`21st.--Spent this morning mostly in reading; dined at Mary Scott`'s,
the widow of Samuel Scott, who died about seven years ago.
She brought some of his memorandums in manuscript, which afforded me instruction.
They say of him, that he was a lively minister;
but I find he had a low opinion of himself.
A man weak in body, and often depressed in mind: his widow is about sixty-eight,
and appears to enjoy a comfortable share of health and spirits.
O this changeable world! how many ups and downs in it:
how uncertain are the best of blessings--that of husband and wife;
and what a mercy to be favoured at last, when troubles are at an end,
to join the company of those who are fixed, where there is neither marrying,
nor giving in marriage, but who are as the angels in heaven,
peacefully under the dominion and care of the everlasting Shepherd,
who laid down his life for us all.
Lord, grant that this may be my happy portion,
and those you have blessed me with in this life.

"`23rd.--I have spent one more week of my life in a poorly, broken down state of body;
but it has not been the most unpleasant.
O that this day I may be favoured so to wait upon the Lord,
as to know my strength renewed;
that I may experience more of an establishment in faith and patience,
and keep fast hold on hope, the anchor of the tried and tossed soul.
Attended both meetings: was silent in the morning,
but towards the close of the afternoon meeting a little arose on my mind to express.

"`24th.--After dinner dear Mary Pryor again broke forth
with a language of encouragement to me,
believing the Lord would not leave me, but bless in basket and store;
to all which I felt disposed to say, Amen.
Left Hartford after two o`'clock, and arrived at Joseph Smith`'s, London, after tea,
where I found Thomas Colley.

"`25th.--To quarterly meeting,
and after Thomas Colley had pretty fully relieved his mind,
I stood up with an encouraging testimony to the youth, to some satisfaction.
To the adjournment at five o`'clock, and had communication on various matters,
and felt satisfied.

"`27th, fifth-day.--Went with Thomas Colley to Tottenham,
and expected he would have had a public meeting, but the prospect died away with him.
Some light, and hope, and peace, sprang up near the close of this little week-day meeting.

"`29th.--Seeing no opening for present service in London,
and having a freedom to accept the kind offer of my friend John Hull,
I left the city in a post chaise, and arrived at Uxbridge to tea.

"`30th, first-day.--To meeting in a weeping state, and remained so most of the time,
and then went on my knees and begged that the Lord would be pleased to open my eyes.
O, if such a poor, humbled, reduced creature may ask, would it not be,
that I may not return to London again, unless there is a work to be done; and if so,
to be favoured to see it with clearness, and have strength to perform it; nevertheless,
not my will, but yours be done.
To afternoon meeting and was silent.

"`31st.--My friend John Hull took me to High Wiccomb, and lodged at Adey Bellamy`'s,
whose kindness appeared as great as ever.

"`Fourth month 1st.--Before meeting George Dillwyn came from a visit to Norfolk.
Went to meeting, where tears were my food for a considerable time;
dear George appeared in testimony, and my heart was broken,
under which I was engaged in supplication; and just as the meeting was closing,
I stood up with a few words, and was enlarged; much brokenness appeared,
as also again in the men`'s meeting for business;
and I admired much at the tears which dropped like rain from eyes present.
O Lord, preserve me, and go with me, according to your good hand upon me;
remove my iniquity, and bear with my infirmities;
make me more and more what I ought to be in your sight.

"`2nd.--To meeting, and I passed it in silence: dear George Dillwyn,
E+++.+++ Raper and C. Whiting had the service.

"`3rd.--The monthly meeting was to me a humbling time;
dear Adey Bellamy stood forth in a feeling, lively manner,
and spoke to such as were under trial, and after him George Dillwyn appeared,
and towards the close I knelt in supplication, and felt some relief;
the business was conducted comfortably.
After tea, J. H., E. Raper and I, went into a sick Friend`'s chamber,
and had a religious opportunity with her, which proved a tendering one.
The circumstance of Jesus visiting Martha, Mary and Lazarus, was mentioned;
and in the close our sick sister took me by the hand and said,
she believed I was a deeply exercised servant of the Most High,
and that there was in store for me, a hundred fold in this life,
and in the world to come, life everlasting,--and I said, The Lord grant it may be so;
being willing to believe that out of the mouth of two
or three witnesses the truth is established.
Spent the evening pleasantly in company with my beloved brother, George Dillwyn, wife, etc.

"`4th.--Returned to Uxbridge, and attended an evening meeting appointed for Thomas Colley.
This has been a comfortable day of rest in mind.

"`6th, first-day.--Went to a meeting at Jordans, and sat by Thomas Colley,
who was large in testimony.
Adey Bellamy also, appeared early in the meeting, but silence was my portion.
Returned to tea at D. Moline`'s, and attended a meeting at five o`'clock,
where there seemed some little revival of faith in my own particular,
and I stood up and encouraged others, and spent the evening pleasantly.

"`15th.--My heart expands with gratitude and thankfulness in
being favoured to arise from my bed with so much ease,
and also for the opening last evening.
If there is then more for me to do in a different manner, than I ever yet experienced,
and these deep wadings and baptisms are to prepare me for it,
so help me everlasting Father.

"`16th.--Attended monthly meeting, and was opened in testimony to a degree of comfort,
and felt my mind turned towards Kent quarterly meeting.
This has been a day of the lifting up the cloud, and I lay down comfortably.

"`17th.--An intimation was given me on awaking, of receiving tidings from home;
and I thought if it was another messenger of death,
whether I should be warranted in going the little journey in prospect; it disappeared,
and I endeavoured to arise with a resolution to hold up my head.
When I came down stairs I found a letter from my son, inclosed in one from Joseph Smith,
giving an account of the quiet departure of my dear aged mother;
she died on the 22nd of the second month.
I have frequently thought since I parted from her, as well as at the time,
that I should be favoured to see her close, and receive her blessing,
and now am a little straitened about it; but perhaps it was wisely so ordered.
The Lord`'s will be done, for there has been a sweetness accompanying my mind,
in a hope that it is well with her soul; yes, at seasons,
under deep conflict and prayer on my own account, and on hers,
there has been an answer of peace.`"

[.offset]
On the 16th he thus writes to a dear friend in the ministry:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Uxbridge, fourth month 16th, 1800.

I have had thoughts for days past of sending you a few lines, my beloved friend;
but being reduced very low, was discouraged.
I should be ungrateful, if I was not now and then to send a paper messenger,
after this sort, remembering the great kindness I have experienced at your hands,
and from your dear father and sisters.
Ah! my friend, I have been in the deeps since I parted from you, but underneath yet,
is the everlasting arm, or surely I had fainted.
A little relief has, been vouchsafed, for which my soul bows in thankfulness,
and receives it with a degree of trembling.

There is but little presents to write,
more than that I feel anxiously solicitous for your welfare
every way,--that you may deepen in religious experience;
that by descending into Jordan and there abiding, and rightly so,
you may yet be favoured to come up with your stones of living memorial.
You must experience the furnace; this is still the doctrine I have to hold forth to you,
and when I have seen you in it, my heart has sympathised,
and been more knit and united to you, than when in the greatest pleasantness and joy.
You have put your hand to the plough; go forward,
and the Lord redeem you from all that lets and hinders.

--

"`18th.--Set off after breakfast accompanied by William Hull and wife,
in a post chaise to London, in a low condition.

"`19th.--Started about six o`'clock, and got to Dover about seven in the evening,
and met a kind reception from Richard Baker and wife.

"`20th, first-day.--To Folkstone meeting, and was silent in the morning;
in the afternoon many neighbours came, and I was much enlarged in communication,
and felt relieved.

"`21st.--To quarterly meeting; many neighbours came, and I had a tendering time.
Many tears, I believe, were dropped, and on the whole, the quarterly meeting, I hope,
was to profit.

"`22nd.--J. B. and wife came, and I had a tendering opportunity: he has been a soldier,
and was so when I was here last, and now attends meeting as well as his wife,
and they appear hopeful.
After these went away, S. T. eighty-two years old,
and another ancient woman came to see me, the latter,
the widow of the principal gunner at the battery.
It was pleasant to find so much love in the hearts of strangers.
Went to the meeting, which was very crowded, and I had a relieving time,
although much spent afterwards, but felt easy and relieved.

"`23rd.--Comforted respecting my dear mother, and also respecting my wife and family;
and desire to leave the things that are behind.
I remembered that passage, '`He shall not fail nor be discouraged,`' etc.:
seeing then that help is laid on one so mighty, O, may I lay aside these weights,
and endeavour still to run the race before me with patience.
The promise of openness and enlargement while at Uxbridge,
has been fulfilled in several meetings.
After a seasonable opportunity with T. E. and wife,
and a tendering time with various Friends at our lodgings,
we left Folkstone and got into Dover to dinner, easy in mind.

"`Much freed from labour and toil of mind.
O how comfortable, and yet must I not learn in all states to be content.
Yes, I long for it, and to be able at all times, and on all occasions to say,
your will be done.
To meeting, which was small, but I felt considerable openness and enlargement.

"`25th.--I looked yesterday towards calling the town`'s people together in the evening,
but it left me.

"`26th.--But dull and low this evening; two days more spent,
and not one religious opportunity in a family; yet hope and trust I have not been idle.

"`27th, first-day.--Feed me with convenient food this day, and let your will be done.
Attended both meetings in silence: Richard Baker and daughter, and two others,
had the labour.
In the evening many friends called, and I felt openness towards various states,
and relieved my mind; I was again exercised in supplication at supper, and lay down easy.

"`28th.--Spent this day under close exercise.

"`29th.--See no opening towards the people at large,
nor anything to do in a more select manner.
Set off in a post chaise, and got to Rochester in the evening,
and met a kind reception at William Cowper`'s.

"`30th.--At meeting my soul was humbled into tears of contrition.
I remembered the first time I came to this place, and how I had to turn back to London,
and the singular occurrence which took place.
This is the fourth time I have been here, and some liberty of soul was experienced,
for which thankfulness was felt;
and towards the close of the meeting I had a tendering opportunity.

"`Fifth month 1st.--Met some friends at seven o`'clock,
in order to get them reconciled one to another; again at ten o`'clock,
and also at two o`'clock, and in some good measure saw the end of our labour answered,
and feel comfortable now while making this note.
My mind is easy and faith renewed.

"`2nd.--Arose early and with an easy mind, finding no more to do here,
but an opportunity with Henry +++_______+++,
who attends meetings and appears sober and hopeful.
I am now again at Dartford, where I have been greatly afflicted in times past,
when my face has been turned towards London; it was so the last time I was here.
I had a pretty comfortable entry into London, and dined at Joseph Smith`'s,
whose kind notice and attention, with that of his wife,
had a tendency to comfort and cheer my mind; he went with me to John Bevans`',
from which I took chaise and proceeded to Uxbridge.

"`3rd.--The language of my heart has been, '`Teach me your way, O Lord,
and lead me in a plain path, because of mine enemies.`'

"`4th, first-day.--Sweet and easy on awaking after a comfortable sleep.
My heart is thankful,
and desires to be preserved in watchfulness and resignation to the Divine will.
At meeting; I thought Ann Crowley appeared in a sweet and lively manner;
soon after which a dark cloud gathered in the outward heavens,
and spread with some thunder; and while I was on my feet the wind increased,
and hail stones came so powerfully against the window, etc.,
that the attention of some was turned away, and I sat down.
Silent in the afternoon meeting.

"`6th, third-day.--I have been reading and walking with an exercised mind;
and this precious thought is sweet, that I cannot do without affliction: I feel content.
Beautiful, indeed, does the creation appear this day.
In the midst of these pleasant pictures, I cast an eye on home, once my pleasant abode,
but from which I am now far separated, and in a stripped and tried condition.
It is the Lord, let him do what seems him good, let his will be done,
and all will work in the end for my good.

"`7th.--Was singularly concerned in communication in meeting to
address various states--last first-day`'s concern was revived.

"`10th.--I have been greatly tried with the veiling of the light of God`'s countenance,
for which I have long and often mourned in this land; but through it all,
what a favour not to lose all faith.
What has supported unto this day but goodness and mercy, though sometimes much hid.
I bless the name of the Lord, in that He is favouring me to believe in His name.
Surely I am yet a weak Christian, to mourn when tried, as I have done.
It is said of the eagle, that though ever so hungry, she makes no noise:
when will the time come that I shall bear all things, and hope all things.

"`13th.--Again at my friend Samuel Hull`'s, after a little visit to London.
I attended the burial of Sarah Row, the day before yesterday,
and was largely exercised in testimony at Devonshire house, where the corps was brought;
and again in the afternoon pretty much so at Grace-church street;
and some openness yesterday at the morning meeting, but have returned low and exercised;
it seems like a remand back to the prison-house.
Lord, help.

"`18th, first-day.--Mary Watson, and Mary Alexander, R. Fowler and wife,
with several others were at meeting, but not a line in the way of ministry.
My employment was to trace back my path to the first yearly meeting I attended;
and although I have been greatly tried since, in various ways,
I hope no willful transgressions stand against me.
To afternoon meeting, in which I had not long sat down,
before my mind was favoured with an opening,
and brought into sympathy with the oppressed and exercised.
I remembered, and also mentioned, how gladdening it is to mariners at sea,
after being driven here and there by high winds, and having had many cloudy days,
so that no observation could be taken; when another ship, perhaps equally distressed,
may have been favoured with the sight of the sun, and taken an observation;
and when these meet at sea, and inquire what latitude and compare notes,
and gain some information, how joyfully they again proceed on their voyage.
What a joyful sound it was to the poor disciples, when the Master saluted them with,
all hail!

"`19th,
second-day.--Attended both of the sittings of the
yearly meeting of ministers and elders in London,
and was very poor.`"

[.offset]
The following letter was received from his friend Mary Dudley:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Suirville near Clonmel, 18th of fifth month, 1800.

[.salutation]
My much beloved friend,

How has your sympathising, your cordial salutation many weeks ago received,
been apparently neglected and unacknowledged;
but how different from appearance have been the real feelings of my heart, which,
burdened and longing for some relief, sought in vain for it.
Yet no ability has it found to pour forth its sorrows,
and such a restraint I know not that I ever
experienced from holding converse in this way,
so that I have for many months past,
been like an ungrateful receiver of many affectionate
tokens of unmerited regard from some near my best life.
The purgings of my poor tried spirit have been and continue unutterable: in this state,
sick in bed one morning, your valued lines met me, like deep uttering unto deep;
and was I not afraid to say, thankfulness was the covering of my mind,
stripped and divested as it feels of any sensible fruit of righteousness,
and every word sunk into an almost broken heart.

On your account, my long suffering brother, I could and did say, this has God wrought,
having introduced you into these afflictions,
and then causing you to partake of the consolations of the Gospel of his dear Son,
that thereby full conformity to Him might be effected,
and the purpose of His holy will through you wrought out.
Never did I question this would be the blessed
consequence of your deep and almost constant travail,
nor that the path of consecrated suffering would lead
to deeper unfoldings into the mystery of godliness;
and O! that whatever remains to be partaken of for your own and the church`'s good,
you may have in addition, the sustaining efficacy of continued everlasting love;
whatever becomes of your poor friend and little sister,
whose way is closed up on every side,
and in the depth of astonishment utters at seasons this language:
'`Is Your mercy clean gone forever; wilt You be favourable no more?`'
Your query, my dear friend, deeply penetrated my heart,
'`What are you about!`' Trying to stand against a host of difficulties within and without;
against a torrent of temptation (if it be so) from the adversary of all good;
often fearing I have introduced myself and others into an increase of suffering,
more than might have come in holy appointment, by overlooking the right time,
and by waiting for more light, when a sufficiency was vouchsafed;
or by not abiding where there was at seasons a gathering, even into that spot,
that longed-for state, where '`not my will but yours be done,`' arises:
yet though often tossed in a manner not to be set forth,
gracious mercy withholds condemnation;
I feel not the dreadful weight of reproach from an ever-loving Father,
but at times a hope, that feeling a degree of resignation,
and not standing opposed to His revealed will,
He will either in abundant mercy accept the imperfect sacrifice,
or in His own way and time burst my bonds, and proclaim liberty to the captive.
If I am just lifted out of the dungeon with any little message to the people,
and while in commission the vessel feels a little strength,
soon is it gone and darkness covers the earth,
as though the sun would no more shine upon me.

I am here in this land of commotion and bloodshed, a suffering stranger,
to my own feeling, weaned as I long since told you (in the confidence I felt) from it,
and looking to a residence on the other side of the water,
when a detention (very unexpectedly) of several months in the last year,
confirmed my feelings in its being the best for us all.
Self, and what attaches to it,
has driven me farther than I had any view of when I sat down;
but it has not so fully occupied, as to hide you and your views, my beloved brother,
from my sight.
Much do I long to know how you are likely to be disposed of;
and O how should I be comforted by a little of your society,
previous to a separation by the great deep; at one time it looked rather probable,
that at this season I might be so indulged, but that is over,
and I can only hope through your own kind pen to know whether
a peaceful retreat has been sounded in your ears:
if so, may the Lord go with you,
and His Spirit give you rest--preserve on the mighty waters,
and restore you to your endeared connections with the joy of harvest,
and unbroken sheaves of soul-enriching peace.
I would request your kind host and wife, Joseph and Rachel Smith,
to accept my and my Robert Dudley`'s love, and your dear country folk near you.
I shall hope, little as I deserve it,
for a line from you when your case is determined as to moving or staying.

--

"`Sixth month 14th.--I am now again at my friend J. H.`'s, Uxbridge;
many days have passed since I made any record;--have got through the
yearly meeting with a pretty comfortable share of health and strength,
and trust I laboured to be found in my proper allotment:
although trying things have occurred,
yet it has been thought on the whole the most solid meeting ever remembered.
What a favour,
what a consolation to see the church advancing as out of the
wilderness! this I think my eyes have seen since being in this land,
and have rejoiced in it.
I left London under pressure of soul;
and thought on sitting down in the meeting at Brentford, a few days since,
that my state resembled a field laid open without fence or wall;
and under this sense I wept much,
and continued weeping until I felt strength to bend in fervent supplication;
and afterwards by some communication, got much relief.
Sweet was the calmness that covered my mind for a season,
while sitting in the men`'s meeting,
which in some degree continued through the remainder of the day.
Here I am again, shut up a prisoner, but not altogether without hope,
though I have had a deep plunge since returning.

"`16th.--Week-day meeting was a humbling one; my faith was renewed in silent travail,
and I was favoured with openings.
The Lord continue his good hand upon me,
and enable me to believe and put my trust in him, and to wait on him.
Humbling prospects opened a little to my view respecting the king and London,
and I lay down resigned to whatever allotment Divine Providence may permit.

"`23rd.--London quarterly meeting of ministers and elders was but a flat dull time,
and the general quarterly meeting, held on the 24th,
was a very low time in the first part:
I feared there was not a digging for the fresh springs of life;
and throughout the business there seemed very little life stirring.
Is it not a sifting, proving time, in which the prudent men keep silence.

"`26th.--Had a trying time on my bed;
the state of society and individuals pressed me sorely.

"`29th, first-day.--Empty and poor on awaking; yet hope, in prostration and abasement,
I felt desirous to subscribe to the Lord`'s will.
I long to experience his favour,
and the lifting up of the precious light of life in my soul,
and to feel more liberty of spirit.
I long to see the way home, how and when;
and yet I desire also to lay abased and humbled,
so as to be willing to be dashed to pieces, and yet more broken,
if it is the Lord`'s blessed will; believing his power is able to make me up anew.
Attended both meetings, and was shut up in silent sorrow.

"`Seventh month 1st.--To Southwark meeting, in which I felt a concern to labour,
and it was to some satisfaction.

"`3rd.--Awoke about one o`'clock, and it was a very singular time of opening prospects;
and thanks be to God,
my mind was brought into resignation and willingness to submit to his will--perhaps
I hardly ever had a clearer opening into the agony of my Saviour in the garden,
and also his crucifixion; he emptied himself--he stooped to the cross,
and who can declare his generation, for his life was taken from the earth.

"`6th, first-day.--Attended Grace-church street meeting, and dined at Wilson Birkbeck`'s,
accompanied by Ann Crowley,
and after dinner my mind was turned towards the son in a particular manner,
and afterwards to the goodly old Friend, the grand mother;
and M. Bevans closed the opportunity by prayer for the youth.^
footnote:[Who died soon after.]
To Grace-church street meeting again in the afternoon, and sat it in painful silence.

"`7th.--Received a letter from Samuel Smith; he, Richard Jordan,
and Gerves Johnson arrived at Liverpool the 3rd of this month.
Attended a special meeting today on account of Hannah Barnard.^
footnote:[Hannah Barnard, who resided in the State of New York,
was an acknowledged minister in the Society of Friends,
possessed of talents considerably above the ordinary level,
with a force of imagination and power of language which were
quite attractive to her youthful and inexperienced hearers.
Yet some of the more discerning and considerate class regarded her,
as one (to use an old but expressive phrase) who was carrying more sail than ballast.
She came to Great Britain as a minister with proper certificates from America,
but during her travels developed unsoundness in doctrine,
similar to those opinions which had just before been
manifested in Ireland (i.e. denying the Godhead of Christ,
His propitiatory sacrifice,
the Divine authority and inspiration of the Scriptures of truth, etc.)
Her case obtained the attention of the Morning Meeting in London,
which took proper steps to prevent her further traveling in the ministry;
and she was dealt with for her unscriptural opinions.
She appealed against the disciplinary proceedings which
had become necessary in thus restricting her,
to the yearly meeting in 1801; which, after a weighty and solemn deliberation,
decided against her;
and she was ultimately disowned as a member of our religious society
by the monthly meeting in America to which she belonged.
A few were carried away by the plausibility of her public addresses,
during her stay in England:
but they were in several instances known to be unsatisfactory
to those of other religious denominations,
as well as to Friends.]
I have felt more ease of spirit these two days past, and have rested on my bed,
for which thankfulness of heart is experienced.

"`12th.--Had a tender opportunity with one I longed to see.
Packed up my things in trunks and saddle bags, and now I have said in my heart,
what wait I for, but the signature and seal of permission to go home.
Spent the evening quiet and easy, and lay down so, insomuch as to adopt this language:
'`You are my Father; you are my Judge, and my Law-giver; you are my King,
and you wilt save me.`'
O for faith to hold fast such a confidence as this.

"`13th.--Still feel a comfortable reviving degree of faith and hope;
O may it give courage and boldness.
Two open times in meeting today, to my admiration.

"`14th.--Attended morning meeting in London, which was exercising,
and yet I was favoured to bear up under complicated trials.

[.offset]
In the evening answered George Dillwyn`'s letter, which is as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tottenham, seventh month 14th, 1800.

[.salutation]
My beloved friend,

Since your letter was put into my hands at the close of the meeting this morning,
I have been looking it over again and again, musing and pondering its contents;
and the more I think of it and of you, my dear feeling brother,
the more I am induced to believe you were assisted with
best help to pour a little oil into these wounds,
that I have sometimes ventured to believe, were made as by fetters of iron;
for on looking over the precious encouraging portion of scripture you sent,
and turning my eyes to the margin, I there read,
'`His soul came into iron;`' and I gained instruction thereby.
How I have longed, both in lonely places in the day time,
and upon my bed in the night season,
when almost every brook or stream of comfort was dried up, that the King immortal,
and everlastingly glorious, might be pleased to loose my imprisoned spirit,
and let me go free; therefore, to this little portion which you sent me,
with the greatest sincerity I can say.
Amen.

You are, I think, just right with respect to comparing,
or bringing us back to youthful days, I was a diver,
and you and I have had our dips under the water together,
since the day we met in this land.
How singular, and yet how comfortable was it, on reading your lines,
to remember afresh the thoughts of my heart respecting you,
within these few days past--they came up somewhat after this manner;
for I may assure you, I have had a very deep plunge:
'`There is my friend and brother George Dillwyn, who appears to be bearing me company,
and seems like another Ezekiel; he has prepared his stuff, and has removed;
he has had a singular life in this land, much like mine; he has returned again,
and though settled as to appearance--and though I am separated from wife and children,
etc., yet he appears like one bound as I am.
I have seen him as a mark that has been shot at, and the archers have wounded him.`'
From thoughts like these my mind was brought into near fellowship with you;
was not this like diving under the water, and touching?
Can you recollect that we can see one another under water, when we cannot speak?
I have often wanted to say more to you, but when with you have been restrained.

I was at Tottenham yesterday,
and in both meetings favoured with enlargement in testimony;
it seemed like a farewell service,
and afforded much comfort and relief to my mind And now I may conclude by assuring you,
that no part of your precious letter was more sweet than the close,
whereby you felt liberty to own me as a brother
in the sympathy and fellowship of the gospel:
and as far as I dare venture in this my imprisoned state,
I can dearly salute you in a measure of the same.

[.signed-section-signature]
Thomas Scattergood.

--

"`15th.--Awoke early, and the situation of Hannah Barnard awoke with me,
and pressed hard on my mind; which, with other prospects relating to myself,
brought me into prostration and tears.

"`20th, first-day.--To Grace-church street meeting, which was silent on my part:
dined at S. Southall`'s, and had a tendering opportunity with the family.
To Grace-church street meeting at three o`'clock, and had a comfortable time in prayer,
and afterwards in testimony, particularly toward the dear youth.
Slept into William Allen`'s and took some refreshment;
here I met with my dear sympathizing friend Joseph Gurney Bevan,
much to my comfort and refreshment.
To Devonshire house at five o`'clock, where the body of the widow Elliott was brought;
it was a large and mixed meeting, and very unsettled.
H+++.+++ B. pretty soon stood up to define the difference between a wise man and a fool.
Special West afterward preached salvation only by and through faith in Christ,
received by faith in the heart--it was a trying time.

"`23rd.--What a mercy to be favoured with a little ease of spirit!
My soul longs for deliverance from this great city;
yet I trust in the Lord`'s way and time.
O for greater sanctification of spirit and purity of heart,
so as to be favoured to see God, to know his will and do it.

"`24th.--The situation of afflicted Job opened last night on my bed:
how stripped was he of all his living, and reduced to lie on a dunghill,
or to sit among ashes.
Surely in a spiritual sense he could say, he had eaten ashes like bread.
Soon after breakfast Mary Pryor came from Hartford to see me.
In a little sitting she told me how much her thoughts were
with me as she sat in her week-day meeting yesterday,
and therefore wanted to see me; that it had passed through her mind,
and with much fear and care she mentioned it: '`You are my servant;
I have chosen you in the furnace of affliction; I will keep you in all places,
whithersoever you go.`'
Soon after this opportunity I received a letter
from Uxbridge with nearly the same expressions.
I dropped my tears, and was willing to say, So be it, good Lord.

"`27th.--I felt some openness in both meetings, especially that in the morning,
with the rich and gay, and felt relief.

"`29th.--To a meeting of ministers and elders called on my account,
where I opened my prospects of returning home.
A committee was appointed to prepare an endorsement for my certificate.
It was a comfortable time,--I found sympathizers.
After meeting I opened to a few Friends another weighty concern,
respecting visiting the king.

"`31st.--Set off in a post chaise about eight o`'clock,
accompanied by my friends Richard Chester and John Elliott, for Weymouth,
to endeavour to obtain an interview with the king.
Got on our way about sixty-six miles to Winchester: I felt quiet and resigned on the way,
and pretty cheerful.

"`Eighth month 1st.--Got to our journey`'s end, starting about six o`'clock,
and arrived about sunset, seventy miles.
My weakness, and great infirmity stared me full in the face, and it was trying.
I felt very unworthy this day, but endeavoured to look forward.

"`2nd.--Waited until near eleven o`'clock before
anything opened to make way for my concern.
In the evening Richard Chester and John Elliott
walked on the esplanade and met with the king,
and requested for me an opportunity with him, his consort, etc., but got no answer;
they were kindly noticed.
During their absence my mind was closely exercised, being left alone at the inn.
Sometime after they returned I walked to the pier-head, and looked toward the sea,
and deep and pensive were my thoughts respecting this island and its inhabitants.

"`3rd, first-day.--Endeavoured to put on strength, I hope, in the divine Arm:
about eight o`'clock, accompanied by my two friends, I walked along the sea shore,
and saw the king with several of his officers, walking the esplanade.
On their return we met them, and I had a full opportunity to ease my mind.
Returned to the inn peaceful and easy as I could wish or desire;
and about ten o`'clock set off and rode this day about halfway back towards London.`"

[.small-break]
'''

It will be proper to observe,
that in the interview which his companions had with one of the king`'s advisers,
to whom they had applied for permission to visit him,
they were informed that it was not likely he would consent; alledging as a reason,
his unwillingness to see any strangers,
in consequence of attempts which had recently been made upon his life.
He however suggested,
that as he regularly walked on the esplanade at a certain time in the day,
they might have an opportunity then, if they thought that would answer.

When they met,
Thomas Scattergood was introduced to the king as
a much loved minister of the gospel from America,
who had been engaged in a religious visit to the Society of Friends in England.
Thomas then took off his hat and said, "`I have a message from the Lord to you, O king.`"
The king instantly uncovered his head, also his attendants,
and made a full stop at this salutation,
and listened with respectful attention to what Thomas said.
When he concluded, the king said to him,
"`I thank you,`"--and instead of pursuing his walk, returned at once to his apartment.

[.small-break]
'''

"`4th.--Dined at Egham near Staines.
On entering the room I saw a Bible laying on the table,
and opened on the twenty-ninth chapter of Isaiah, and felt encouraged in reading it,
for my mind has been closely exercised respecting
another prospect which has long been upon my mind.
Got into London about six o`'clock: the last ten miles stage into London was a trying one;
and it has often been so on entering this place, but this exceeds all,
from a prospect of mortifying service opening and pressing very heavily upon my mind.

"`6th.--Slept pretty well, and I feel cheerfully resigned, I hope,
to do what has opened as a religious duty.
Met a number of Friends at Grace-church street meeting-house,
and laid before them a prospect of going to the Royal exchange.
It was a solid, uniting time, and I found sympathizers:
none could see their way to accompany me in the exercise,
and as the way did not open in their minds, I got eased of my burden, and left it.
Attended meeting, which was pretty large, and many young people present.
I began with some expressions which I heard T. Gawthrop dropped on leaving Philadelphia:
'`Master said, you came poor amongst them, be content to leave them so.`'
Tenderness appeared in the meeting, and after it was over I was saluted by many,
old and young.
Went to Tottenham to lodge.

"`7th.--After breakfast I took my farewell of this very kind family,
(Thomas Horne`'s,) and went to London to the Alien-office, and after waiting some time,
got my passport.
Dined at J. Bevans`' with a number of Friends, Joseph Bevans and wife amongst them,
and after a tendering time with a pretty large circle, set off,
and accompanied by my kind friends E. Janson and sister, Martha Horne, in a post chaise,
and J. Bevans, wife and son, to Uxbridge, where several called in and took leave.

"`8th.--An opportunity with several Friends, and started about half past six o`'clock,
and breakfasted at Adey Bellamy`'s, High Wiccomb,
where dear George Dillwyn and wife met us.
We had another opportunity, and passed on through Oxford, Chippingnorton to Skipton,
and on the 9th as far as Newcastle and lodged.

"`10th.--Got to John Bludwich`'s, at Warrington, about two o`'clock,
and to meeting with them at three, and about five set off,
and arrived at Liverpool a little after dark, where I met with Joseph and Rachel Smith,
and pretty soon after I got in,
was informed that Phebe Speakman had sailed early in the morning of this day,
which gave me a little shock for a moment; but felt easy in a belief it is well.

"`11th.--Spent this morning at Robert Benson`'s,
and in the afternoon went on board S. Coflin`'s ship,
and sat down with a number of Friends in quiet,
I told the company I felt easy to go in this vessel,
and cast myself on divine Providence; that I had been a prisoner for years in this land,
and this ship seemed like removing into a small compass, etc.

"`13th.--No prospect of sailing for several days, and I feel content.

"`16th.--I feel at liberty to cross the great deep again,
and to look towards my native land.
Surely I may say this morning, I feel myself an unworthy creature;
yet I hope I desire to trust in God for mercy, deliverance and salvation:
grant it may be so, and my soul yet more humbled and abased in truth.

"`17th, first-day.--Am yet at Liverpool.
There is occasion to lie humble, as with my mouth in the dust.
Went to meeting and prayed for myself and others, after which I felt a little lightened.
In the afternoon meeting I laboured, and bid farewell, and felt more ease of spirit.
It has been a hurrying time of late.
O for sustaining comfort to accompany on board of ship, and over the sea.
I hope my views are not great; quiet and ease of mind,
and a sense of forgiveness of all my weakness, infirmities and iniquity;
I desire to trust.

"`18th.--Better in health and spirits; wrote to several friends,
and feel relieved and lightened.

"`19th.--A prospect of sailing was given out last night,
and my mind became more fully charged, and did not sleep so well as nights past.
After breakfast sat down in Robert Benson`'s parlour, with him, wife and children,
Joseph and Rachel Smith, E. Janson, Martha Horne, etc., when a quiet, and I trust,
a solemnity covered us: it was the testimony of Robert Benson it was so,
and after we broke up, Robert Benson also expressed the same.
I wept in the opportunity, but felt resigned to my allotment,
believing the time was come to leave this land, and expressed it:
when we got down with my sea stores, the ship was getting out of the dock;
the pilot would not come to,
and so we were under the necessity of taking a
boat and following her a considerable distance,
which was trying, as I wanted some of my dear friends to have gone on board with me.
Parted with them at the pier-head, much as I parted from Friends in New York,
and accompanied by Robert Sutcliff, of Sheflield, the only cabin passenger,
got safely on board about eleven o`'clock, and after sailing about thirty miles,
anchored until night.

"`20th.--Fair wind but light: my heart feels heavy at times,
not only in looking towards shore, but also to my native land:
great have been my conflicts since I left New York, to which place I am now bound,
if the Lord permit; unto whose keeping and care I crave ability to commit body,
soul and spirit, as into the hands of a merciful Creator,
for there appears nothing to recommend me, a poor unworthy servant, but mercy in Christ.
O then let me settle down into it.
O my God, visit and revisit my soul; cast me not out of your presence.
I am weak, and have been greatly loaded with infirmity.
Look once more on my afflictions and my pains,
and forgive all my sins--keep my soul and deliver me,
let me not be ashamed and confounded;
for I dare not do otherwise than put my trust in you, and believe and hope in you.

"`Two o`'clock.--Fresh wind and fair, and a fine day: not far from Holyhead.
I look at Wales with love,
a part of the island I have not visited in this long detention in this land.
O that the seed may be visited and cared for.

"`22nd.--I have felt lively sensations on looking towards my dear friends parted from,
and to whom I am going.
Even in these few day`'s tossing, I may adopt David`'s language;
'`Unless the Lord had been my help, my soul had almost dwelt in silence.
When I said my foot slipped, your mercy, O Lord, held me up.
In the multitude of my thoughts within me, your comforts delight my soul.`'

"`25th.--O how pleasant and how desirable is it to be continued under divine favour,
and to be acknowledged as one of the Lord`'s servants.
Had a refreshing night`'s sleep,
and awoke with a degree of courage and confidence in the divine Arm,
You can change the wilderness of great trial into a fruitful field, at your pleasure.
I crave ability to wait on you, my Creator and Preserver, I opened the blessed book,
and cast my eyes again on the ninety-first Psalm; '`I will say of the Lord,
he is my refuge and my fortress, my God, in him will I trust,`'

"`27th.--A calm night, and now the wind has shifted to S. W.,
and it is a very fine morning: my mind is calm, and I feel pretty easy in my allotment.
I trust I have been favoured to come off in the right time:
never did I see the way open before.
It is the Lord alone who can heal the broken in heart, and bind up their wounds.

"`31st, first-day.--A brisk wind this morning, but increased in the afternoon,
so as to require the topsails to be reefed.
I sat on deck most of the day,
the sailors having put up a piece of a sail on the quarter rail to break off the wind.
When I saw the sailors on the yards taking in sail, so exposed to danger,
I thought surely the watchful eye that is over the sparrow,
is also over them to preserve them; the thought was sweet,
and love flowed in my heart towards them, although no opening for a meeting presented.

"`Ninth month 1st.--The wind increased to a storm last night,
and between ten and twelve o`'clock the ship lay to.
The captain ordered the dead lights put in, and it was well he did,
as he afterwards said; for although the ship lay easy yet the wind dying away suddenly,
and then shifting to an opposite point, she got into the trough of the sea,
and at times the waves beat against the stern, and would have washed us in the cabin,
if this precaution had not been taken.
Got under sail again in the morning, but had a very heavy sea.

"`2nd.--There was a time during this long detention in Great Britain,
when the waves of the sea appeared terrible and insurmountable;
so did the prospect of being captured at sea: now they are very little to me, no fear,
even the night before last, in the greatest seeming trial, possessed my mind.

"`3rd.--I have been instructed this day by observing
the weather and outward elements on this wide sea,
which surely resembles my life of ups and downs.
This morning, after I came out of my little confined cabin, upon deck,
the clouds were thick, the wind ahead, and it was oppressively close.
In a little time the wind came more northerly, a pleasant, clear horizon appeared,
and a cool, refreshing air sprung up.
I wait on Him who holds the winds in his fists, to change my spiritual dispensation.

"`4th.--Spoke the ship Rose from Philadelphia for Liverpool, twenty-one days out.
I feel thankful that my mind is so easy and quiet.
O for a day of liberty to serve God without slavish fear.
I long for more of such a dispensation; '`My life, if you preserve my life,
your sacrifice shall be.`'
I trust this is the upright language of my tribulated soul; desirous to say.
Not mine, but your will, O God, be done today, and to the end of my days here,
and forever.

"`6th.--Beating against the wind--how much this
resembles my track through this vale of tears.
'`You have need of patience after you have done the will of God, to receive the promise.`'

"`8th.--It is a favour worthy of recording,
that I feel so quiet and resigned in my present allotment,
and that I can sleep so well in the night season,
with little care upon me as to the voyage; thanks be rendered where they are due.

"`18th.--About sunrise it began to blow; we soon had a very heavy wind, and lay to.
I enjoy a calm and easy mind in the midst of a storm.
O London, London,
what unutterable conflicts have I passed through in walking your streets!
Now, even when the waves run high, and stormy winds rage,
so as to make the sea like a boiling pot,
my spirit is at rest and centred in the Creator of sea and land.
Bless his name, O my soul.

"`22nd.---Last evening before night, put the ship about, and laid our course south,
with very little west--the captain thought it best to stand no further north:
between seven and eight o`'clock this morning lay the ship to,
and the hands went to fishing, we being on the Banks.
I remembered, I hope, instructively and encouragingly this language;
'`God spared not his own Son, but freely gave him up for us all.`'
O the mystery of the redemption of lost man!
Great is the mystery of the work of Truth.
About ten o`'clock put the ship about on the starboard tack, and lay a N. W. course by W.,
with a light wind.
Our fresh cod-fish dinner was very grateful.

"`24th.--A calm covered my mind on awaking this morning,
and continues with a revival of faith and hope.
A little after twelve o`'clock, as we were sitting at dinner, it suddenly began to rain,
the first mate sprang from his seat, saying,
'`What`'s this,`'--he found the wind had suddenly died away,
and a squall came up from the north.
The helmsman was confused, and put the helm the wrong way: the hands were all at dinner,
except the helmsman and the cook.
There was such a stir on deck as quickly sent up the captain: I followed,
and was sensible of the difficulty, seeing so much sail out; however,
by keeping the ship before the wind, for the captain took the helm,
the sailors got in sail,
and by this time the wind got round to N. E. Went under a close reeled topsail,
foresail and main-topsail,
and in a little time were sailing at the rate of eight or nine knots.
When the captain and mate came down to finish their dinner,
he remarked he had never been caught so suddenly before,
for when he left the deck there was no such appearance.
I felt thankful that my mind was so calm and easy in this bustle: poor sailors,
what a wet condition they were in, and how cheerfully they went to their work.

"`28th, first-day.--I have been walking the deck;
and a number of my dear friends left behind have come nearly into remembrance.
I have been thinking of holding a meeting with the ship`'s company, both yesterday,
and also upon my pillow, and since getting up, but do not feel an opening.

"`Tenth month 3rd.--The wind continued brisk
until between eleven and twelve o`'clock at night,
and then suddenly came round to N. W. There was a bustle on deck: I dressed and went up,
and found we had stood on within six or seven miles of Long Island.
It being moonlight we could see it plainly,
and a sweet smell like fresh hay regaled our senses: the sailors caught a woodpecker,
blown off, no doubt, by the north-wester.
We are now, after breakfast, out of sight of Long Island:
what joy was manifest last night among the mariners on sight of land.
I felt calm and easy, and when at breakfast this morning,
some were speaking of the head wind taking us, I felt resigned,
and expressed that I felt at home, and had been so since coming on board this ship;
and yet I have been and am a tried man,
and frequently have broken forth in this confinement in the language of the Psalmist,
the type of the suffering Saviour--the type of the church under her trials also:
'`How long wilt you forget me, O Lord; forever?
how long wilt you hide your face from me?
how long shall I take counsel in my soul, having sorrow in my heart daily?
how long shall mine enemy be exalted over me?
Consider and hear me, O Lord my God: enlighten my eyes,
lest I sleep the sleep of death--lest mine enemy say, I have prevailed against him,
and those that trouble me, rejoice when I am moved.`'
Then let me trust in your mercy, that I may have yet to rejoice in your salvation, O God.
We have been beating all day opposite Black Point, wind right ahead.

"`4th.--About three o`'clock this morning a pilot came on board,
and now we are beating up with a small head wind.
I am once more in sight of my native land,
and to all appearance delivered from the dangers of the sea,
I feel at the present moment a poor unworthy creature, abashed and humbled,
and yet I trust there is a tribute of thanksgiving arises unto the Lord,
for favours vouchsafed on the mighty waters;
and it seems as if I must go home as I left it, in a humbled condition: well,
the divine will be done, and mine reduced--so be it.
Got up to New York about nine o`'clock; came to anchor,
and soon after the captain ordered the boat and took Robert Sutcliff and myself ashore.
On the wharf I was met by my kind friend Isaac Collins, who had been watching for me,
and conducted me home with him, where I had an open reception,
and before bed time a sweet religious opportunity; forty-seven days on the voyage.

"`5th, first-day.--To both meetings, and felt openness to labour tenderly.
My heart was broken, and mine eyes flowed with tears.
Friends appeared glad to see me, several of whom I visited in the course of the day,
and had a remarkable opportunity with J. M. and daughter, at Isaac Collins`'.

"`6th, second-day.--Spent considerable of this day in getting through the custom house, etc.

"`7th.--After breakfast went on board ship with Robert Sutcliff and
distributed some little presents amongst the sailors,
and had also an opportunity to relieve my mind.
Dined at R. Pearsall`'s, and soon after set off with Isaac Collins in his chaise,
and got as far as Rahway.

"`8th.--Several friends called in this morning, and we had a religious opportunity;
then proceeded as far as Stonybrook, where I met my father David Bacon, and son Joseph.

"`9th.--Left our carriage and horses at Bristol, went over to Burlington and dined,
and got home after night.`"
