== Chapter XII

After returning from England he remained mostly at his own residence until 1801,
not being called to any religious service out of his native city,
except an occasional visit to neighbouring quarterly or other meetings.

As he kept no memorandums during this period, little further is known respecting him,
than what is contained in the following extracts of letters:

[.embedded-content-document.letter]
--

[.letter-heading]
Addressed to a Friend in England.

[.signed-section-context-open]
Philadelphia, Eleventh month 5th, 1800.

[.salutation]
My dear friend,

I trust the time had come for me to leave that land;
and though I left my beloved friends at the pier-head with my heart full,
yet the watery element was made easy to me; yes,
more so than at one time I could believe.
O what fears dwelt on my mind at seasons on looking toward the ocean,
with desires to be going when there was no clearance: then it was terrible indeed,
as also when I thought of going as a prisoner to France, in such a sifted,
tried condition.
If I could hardly bear up among such feeling, sympathizing friends as I had in England,
I thought, what should I do among strangers,
to be a prisoner spiritually and outwardly.
All these cogitations and fears were removed; and though I had very humbling thoughts,
and tossings of mind at times during the voyage,
it was as prosperous as I could wish for.
I landed at New York in forty-seven days from Liverpool,
and met a kind reception in that place.

I had no opportunity in the way of meetings during the voyage; I could not get at it.
I was very poor;
but before I left New York I went on board ship and had a full opportunity with mates,
sailors, cabin boys and cook, all together, to much satisfaction,
and I have cause to believe they love me.

And now I may tell you,
that the desire of my heart continues for your
preservation and advancement in the way everlasting.
Put on the breast plate of faith,
and follow the Captain of your salvation fully and perfectly.
There is need to be girt about; and if I mistake not, there will yet be more need.
O, it is a comfort to me to believe, to be assured you are not of the company,
nor in the least joined with those, who are denying a crucified Saviour,
and setting up something else instead.
Keep down in the quiet habitation,
and be willing to be baptised with the baptism of Christ,
that so your feet may be shod with the preparation of the gospel of peace,
that you may be able to travel through and over all the rough ways and stony places,
that may yet be cast up for the proving of your faith;
so wilt you honour the Lord with your all, and in and through all,
in being faithful to fulfill your duty, not only at home in your own particular meeting,
but to know when to go forth in little services, and how to move and conduct in them.
The Lord be near to you in all,
and guide you safely through all that he may be pleased to permit you to pass through,
and give you at last to sit down in the kingdom of peace and rest,
and grant that our spirits may unite in bliss.

I am comforted in observing one here and there of the female sex,
under the polishing hand, that are as plants sprung up since I have been away,
bright and clear in testimony for the Truth, who have been moving about,
and still continue to move, I trust as clouds waiting to be filled by him,
that sees to the ends of the earth, and looks under the whole heaven,
to make the weight for the wind, and brings it out of his treasury.

O what a spectacle I have been among you;
what an exercised creature--what lonely walks have I had in fields and gardens!
Was ever anyone so before?
Well, when I ponder and think,
and it is very likely I have sometimes done too much at this,
and I am striving to mend in this respect; I say, sometimes I query,
whether I could wish it should have been otherwise, and hardly dare say I do.
I am again among my own people,
and pray to be sustained by a few crumbs from the bountiful table; and may tell you,
my friend, that I have been able to come at little further at times,
both in meetings and out of them, than to breathe forth this mournful language;
'`have mercy on me, O Lord, and forgive all my weakness and infirmity,
and blot out all my iniquities, and favour with a place among your sons and daughters,
for I feel myself an unworthy and unprofitable servant;
and if all or any part of the deep sorrow I have passed through may stand in your sight,
it is all but little, and no more than a debt due.`'

I have no other view in thus writing, than that perhaps it may give some relief,
by a little vent to one who has often seen me enclosed as in the pit,
when the poor exile has been hastening not to die therein.
What will be the amount of all this?
I was deeply plunged before I offered to visit
the miserable in London--not for days or weeks:
long was it on my mind.
Long was I troubled in walking London streets.
The last exercise that I mentioned to Friends, was peculiarly singular;
but I have felt quiet and easy about it, and sometimes have thought,
that were I now in London, it is so gone, that I should feel different.
I love her inhabitants, and have been ready to say within myself since I got home,
and thought and said so among you; Surely they are not the worst of people,
there is much good; '`much that I love, and more that I admire.`'

Farewell, says one who prays you may be kept and preserved in and through all states,
which wisdom may see fit to permit, and remain your affectionate friend,

[.signed-section-signature]
Thomas Scattergood.

--

[.offset]
The following is taken from a letter addressed to him, by his friend Ann Crowley, dated:

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Crowley to Thomas Scattergood

[.signed-section-context-open]
Uxbridge, Eighth month 13th, 1801.

[.salutation]
Beloved friend, Thomas Scattergood,

As much time has elapsed since your departure from this land,
it may seem rather unseasonable to remark,
the satisfaction and comfort we experienced in hearing
of your safe arrival on your native shore,
and that a portion of the blessed legacy given to the disciples of old,
was vouchsafed at the winding up of your arduous labour.
Ah! my friend, I have not forgotten the many baptisms, the sore conflicts,
which attended your deeply exercised mind,
while engaged in the Master`'s service on this side the Atlantic;
they are profitably imprinted on my mind, and I trust,
lessons of great instruction were learned by some of us,
in reading your example of silent suffering with the seed of the kingdom.
What signifies how large a portion of suffering falls to our lot,
while conflicting with the clogs of humanity, if through all,
we are but made useful in the furtherance of the
work of the Lord in the hearts of his children;
it is a blessed experience to know assuredly, the virtue and efficacy of that baptism,
which crucifies the will of the creature, nails it to the cross, and reduces self,
until it becomes of no reputation; here the Lord alone is glorified,
his excellent name exalted, and his church edified.
It is good for us frequently to know a being buried with Christ in baptisms,
in order that we may experience renewed qualification
to preach his resurrection and life.
If, in the wisdom of truth,
it should be the lot of my endeared friend and father in the church,
to be again plunged into many tribulations,
let him keep in remembrance for his encouragement, that tribulation works patience,
and patience experience, and experience hope, which makes not ashamed;
because the love of God is shed abroad in the heart.
It is those that are willing to abide with their
spiritual feet fixed on the bottom of Jordan,
until the Lord calls them forth,
that are enabled to bring up stones of memorial to his praise.
Let us then unitedly thank God,
in that he has thought us worthy to suffer for his
blessed cause of truth and righteousness sake.

I write not thus from feeling a redundancy of good in my heart,
or that it is a time of feasting; no, verily, the Lord only knows the many trials,
discouragements, and mournful exercises, that attend my mind; but I thought a cheering,
animating language seemed due to your feeling spirit; believing,
without any manner of doubt, that your deep conflicts will redound to the honour of God,
and your own perfect purification;
so that if true patience is permitted to have its perfect work,
you wilt most assuredly have to adopt the language of an eminent apostle,
near the close of time, '`I have fought the good fight, I have kept the faith,
I have finished my course; henceforth there is laid up for me a crown of righteousness,
which the Lord, the righteous judge, will give me at that day.`'
I never could let go the hope, that you would be favoured at last to know your bonds broken,
and liberty proclaimed to return in safety to your near kindred after the flesh,
carrying sheaves of enriching peace with you,
which would be so manifested to your fellow believers,
that they would have no room to doubt,
but you had been employed in doing the Master`'s will;
and my heart is made to rejoice in the persuasion that this was the case,
and now solid satisfaction is your blessed enjoyment.
We have abundant cause to be thankful that our lot was cast among tender care-takers;
but O, the poverty which I feel, of a real sense of true gratitude of heart,
which ought to ascend to the Father and Fountain of all good.

As I believe you are interested in our welfare, I may inform you,
that although we often set in low places,
experiencing the immortal spring of life to be exceedingly deep,
and little ability to draw water out of the well of salvation;
yet such is the condescending goodness of a gracious God,
that he is pleased at seasons to own us by the fresh incomes of his life-giving presence,
which melts the heart into humble contrition,
so that we have been unitedly enabled to say,
the Lord is still remembering the very dust of Zion,
and willing to satisfy all her poor with bread.
I have not been out with a certificate since we parted with you,
but have attended some neighbouring quarterly, monthly and other meetings,
accompanied mostly by our mutually beloved friend John Hull,
who I feel increasingly bound to, in the covenant of love and life,
believing he is deepening in the immortal root of life.
I feel much sympathy for him, knowing his baptisms to be many; but have no doubt,
if he patiently abide under these conflicts, his bonds will yet be broken,
and he will be enabled to come forth as gold seven times purified,
fitted and prepared to declare of the Lord`'s wonders experienced in the deeps.
I am about leaving home, once more to engage in the Master`'s service.
O the awfulness of such an engagement;
how does the prospect frequently weigh down my spirit into fear and trembling,
lest through any degree of unwatchfulness the work of the Lord should be marred.
Beloved friend, let me beseech you, when favoured to approach the throne of grace,
to put up your secret petition,
that the blessing of preservation may be mine through all the remainder of my pilgrimage;
that so the Lord`'s name may be glorified, and my peace established forever.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to Ann Crowley

[.signed-section-context-open]
Philadelphia, Eleventh month 29th, 1801.

Your letter, my beloved friend, came safely to hand a few days ago,
and as the ship Rose is to sail in a few days for London,
I was not easy to let slip the opportunity of telling you so.

I still feel interested in your concerns, and felt a wish, when I read your lines,
and frequently since, that you may witness preservation on the right ground;
and shall I add, let patience have its perfect work.
This is a great word for me in my present emptied state to adopt,
or recommend to another; but I know that we all have need of patience,
even after doing all that we see to be our duty, that we may receive the promise.
Is it not enough to wait day by day for the unfoldings of required duty and be faithful.
It is a great thing to be faithful, and manifest our allegiance even in the fire.
There is many a pang of conflict to be passed through,
previous to going forth into a fresh field of labour.
The vision may be for an appointed time, and this must be waited for:
some by over anxiety, have, it is to be feared, even dared to hasten,
or strive to hasten.
I am ready to say, why write I thus?
I had little or nothing to make a beginning with, and even this day,
such has been my reduced state,
that I was thinking of closing my correspondence with my friends on your side,
for a time, having so little to spare; but truly I love numbers in that land.

Twelfth month 3rd.--You have manifested much sympathy
and love towards me on various occasions,
and I often remember it and you.
Did you ever see me much more reduced, perplexed and troubled on every side,
than in the tour from Liverpool towards London, excepting the season previous to,
and about the time of receiving such mournful intelligence in ninth and tenth months,
1798?
My faith, hope, confidence, patience, and all that I once thought I was in possession of,
was tried to the very bottom and foundation.
Surely, often then and since, I have been ready to say, how has my foolishness appeared.
Lord, extend your mercy--I often begged for it.

I feel willing to turn back again with a mind possessed with earnest
desires for your safe guidance through this vale of uncertainty,
tears and sorrow; that you may be favoured so to dwell with your gift,
as to be enabled to get your work done in the day time,
by labouring to keep the single eye.
This will be your preservation through all storms and tempests;
this will show you what state in life will be most pleasing to your heavenly Father,
conducive to his honour, and be most profitable to yourself; so that in all your getting,
you may get wisdom and understanding in the law of life;
and if I am favoured to keep the foundation,
I shall yet have to rejoice in your prosperity.

--

[.offset]
From a letter written to him by Ann Crowley, dated, Uxbridge, tenth month 29th, 1803,
the following is extracted.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Uxbridge, Tenth month 29th, 1803.

I humbly trust, it is in the renewings of that love,
which unites Christian travellers the world over,
in the precious union of gospel fellowship,
that I feel once more influenced to salute my
endeared friend with an epistolary communication;
not with an apprehension that I possess a mind fraught with goodly treasure,
but from a desire to evince that you are still alive in
the affectionate remembrance of those who have,
in days that are passed, prized the privilege of your instructive society,
and esteemed it a favour when enabled in any degree, to share by sympathy,
the deep exercises permitted, in unfathomable wisdom, to attend you,
while visiting the seed of the kingdom on this side of the Atlantic.

O, my beloved friend, I have often been humbled in spirit,
when favoured with ability to take a retrospective view of the
heart-tendering seasons we have mercifully been favoured together,
when in the liberty of the ever blessed truth we
have communed of things that are excellent,
hid with Christ in God, and only revealed by the renewings of that divine light,
which discovers the deep things that belong to
the eternal well being of the immortal part.
The fresh recollection of seasons,
wherein we were permitted to ascend the holy hill of Zion in company,
and wait together at Wisdom`'s gate for the renewed unfolding of heavenly counsel,
seems to contrite my spirit,
and enables to subscribe to the truth of that ancient declaration; '`The Lord is good,
and worthy to be had in everlasting remembrance.`'
Perhaps I may safely venture to say,
that no seasons have made more profitable impression on my exercised mind,
than those wherein I was made sensible that your faith and patience were deeply tried,
in order to prepare for fresh service in the great Master`'s house.
I have said in my heart, it is good to be afflicted; for whom the Lord loves he chastens,
and teaches them by his fiery baptisms,
to place all confidence on his Arm of Omnipotency in the day of battle:
and as these are concerned to keep the word of his patience,
endeavouring to possess their minds in humble quiet, they can feelingly say with Job;
'`He knows the way that I take, and when he has tried me I shall come forth as gold.`'
Ah! my beloved friend, may not a similar language to what was formerly expressed,
be still uttered in the camp of God`'s Israel; '`Many are the afflictions of the righteous,
but the Lord delivers out of them all.`'
In the little ability which has been graciously afforded
mentally to visit your deeply exercised spirit,
it livingly arose in my heart; '`Behold, I have refined you, but not with silver,
I have chosen you in the furnace of affliction;`' by trying
dispensations has the Lord purified and sanctified the vessel,
enabling it to show forth his praise; therefore, fear not dearly beloved friend,
though you may still have, at seasons, to pass through the valley of the shadow of death,
and know a being baptised into deep suffering for the seed`'s sake,
for all these trials will ultimately work together,
to the deepening in the immortal root of life,
and qualifying for further usefulness in the
dignified service you are undoubtedly called to.
There are living witnesses who can acknowledge,
with a sense of gratitude to the efficacy of that power which
prepared you an instrument of great use in this land;
not only by diffusing the truths of the everlasting gospel of light and salvation,
in the demonstration of the eternal Spirit, but by a circumspect conduct,
regulated by unmixed wisdom.
What preaching can more effectually set forth the excellency of saving grace,
or exalt its virtue, than a humble, patient, self-denying life?
Such preachers of righteousness, of which number, I verily believe you may be ranked,
evince to carnal professors,
that there is a God who still rules in the hearts of the children of men,
and if yielded to, effects the great and glorious work of sanctification.
Without premeditation have I scribbled the above,
which I hope will be received with the same cordiality
as you heretofore accepted my free conversation.

Your last kind testimonial of continued affectionate remembrance, came to hand,
as your letters have ever done, in a very acceptable season,
and tended much to my encouragement in giving up to a
weighty service I had long believed required of me,
even to pay a religious visit to all the meetings that
constitute London quarterly meeting;
a work you wilt readily conclude,
arduous enough for a poor little strippling to encounter, among the wise and great.
But thanks be ascribed to Him,
who is still manifesting himself to be strength in weakness, riches in poverty,
and a present helper in every time of trial, for his unspeakable mercy,
in that he enabled secretly to utter the language, '`Return unto your rest, O my soul;
for the Lord has dealt bountifully with you.`'

I had a kind, sympathizing companion in dear D. Moline,
through that momentous undertaking,
and I humbly hope this fresh act of dedication was accepted by the divine Master,
as it has tended a little to break her bonds,
and to the acceptable enlargement of her gift.
O how repugnant to human nature to become a fool for Christ`'s and the gospel`'s sake!
May the Lord so operate by his redeeming, purifying hand,
as to enable each of us in our several capacities to say in all things, '`Not my will,
but yours be done, O you ever adorable Master.`'
I have lately been spending a few weeks with my relations at Shillingford, Reading,
and Staines; and though this visit was professedly in the line of friendship,
yet a large portion of secret exercise, and some public labour fell to my lot.
It has been a time of trial, both of faith and patience,
in which I have found the necessity to renew my covenant with a covenant keeping God:
there is much cause administered in the present
day of great degeneracy from the purity of truth,
for lamentation and mourning;
and may the God of all grace enable his devoted
servants to stand fast in their allotments,
patiently filling up their measure of suffering for the precious seed`'s sake.
I believe you wilt be truly glad to hear, that our mutually beloved friend T. H.,
continues growing in the root of life,
and has publicly avowed his allegiance to the King immortal.
He is as a father among the few poor scattered sheep hereaway.
O that wisdom and strength may still be granted,
to enable him to keep his rank in righteousness.

--

[.offset]
The following are to Susanna Horne:

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to Susanna Horne

[.signed-section-context-open]
Philadelphia, Fifth month 9th, 1804.

[.salutation]
Dear friend,

You may rest assured, that since the arrival of your last, and also before that,
you have been often the companion of my mind, and under the sense also,
that it follows you in all your exercises and religious movements,
with desires you may be preserved on that foundation that stands sure,
faithfully following your heavenly Guide, to the finishing of all the work allotted you;
and that we may be happy enjoyers of that rest,
which is prepared for such as hold out unto the end.
I feel for my part, like a vessel much laid by: great,
you know was the travail and exercise I had to wade through when among you,
and great was your sympathy and care towards me.
None perhaps have beheld me in greater weakness, fear and trembling than you.
I cannot forget the wormwood and the gall,
and yet feel disposed to believe I could not have done without it;
and have a humble hope, that all my misgivings and lack of faith and firmness,
in seasons of deepest trial and seeming desertion, will be blotted out of the book.
My little labours seem much confined to this place,
having very little openness to go from home,
and I esteem it a favour to have so comfortable a one&hellip;
They +++[+++his partners in business] have agreed to take the labouring oar,
and set me at liberty, much to my satisfaction;
and I hope the disposition of an old soldier who has been in many a warfare,
measurably prevails, even a willingness to go forth any where, at the word of command;
but may my soul ever be favoured with this, and not attempt to uphold the ark unbidden.

[.signed-section-signature]
Thomas Scattergood.

--

[.offset]
In the same year:

[.embedded-content-document.letter]
--

I feel near regard towards you in penning these lines,
with desires you may continue watchful and faithful to
the filling up of the measure of appointed duty,
that you may grow in grace and saving knowledge,
and then doubtless you wilt grow in the gift committed to your charge.
I think I can say that the desire of my soul has been on my own account,
from my little beginning, that I might be preserved from being a light, windy,
or frothy minister; but be favoured to wait for a commission sealed;
though I know there are times when we must move from very small impressions,
and there needs great care in moving in the dignified work of the gospel.
It is waiting for, and renewedly feeling, the touches of the live coal,
that makes words reach to the captive seed in others.

[.signed-section-signature]
T+++.+++ Scattergood.

--

[.offset]
The following letters will doubtless be acceptable to the reader:

[.embedded-content-document.letter]
--

[.letter-heading]
Ann Crowley to Thomas Scattergood

[.signed-section-context-open]
Uxbridge, Sixth month 20th, 1804.

[.salutation]
Beloved friend,

Having been renewedly favoured this morning,
to feel a revival of that love which reaches over sea and land,
and makes the disciples of Christ dear to each other,
I seem stimulated to embrace the present opportunity of convincing you,
that you are still preciously alive in the remembrance
of your friends on this side the Atlantic.
Perhaps I may, in much sincerity, venture to say,
that your poor friend is one of the number who, according to the capacity received,
feels you near in the blessed covenant of love and life: believing;
you are a chosen vessel of the Most High,
on whom the inscription of holiness unto the Lord, is written in legible characters.
O, says my spirit,
that the blessing of preservation may be mercifully granted through the
remaining rugged steps you may have to tread in this probationary state,
that so, by being enabled to keep the faith,
and fight the good fight under the banner of the Lamb, Christ Jesus,
a crown of ever-enduring peace may be your happy portion,
when the shackles of mortality may be removed,
and death swallowed up in a glorious victory.

It has afforded me much solid satisfaction to hear, through various channels,
that you have been favoured to enjoy a pretty good
share of health since returning to your native land,
and appeared to possess a serenity of mind,
which the reward for obedience does not fail to afford.
I have often had to remember,
how many deep draughts of the wormwood and gall you had to drink
while in our land,--how deeply were faith and patience tried,
yet through all the varied baptisms of the living Word,
the many descendings and fiery trials, which, in wisdom were permitted to overtake you,
you have abundant cause to erect your Ebenezer, and say,
'`Hitherto has the Lord helped;`' yes, and I am renewed in the belief,
that he will not fail to stretch forth his omnipotent Arm of
power to preserve in every dispensation of his Providence.
Have not many cups of sweet consolation been handed to you in secret,
by Him who still delights to succour his own flock,
and strengthen for every good word and work?
Be of good cheer then, my endeared friend, for verily, according to the promise,
He that has been the Alpha, will most assuredly be the Omega,
if we faithfully continue to manifest our allegiance to Him, who is King of kings,
by a circumspect walking in his fear.

Although I have not been favoured to receive any written testimonial
of your continued affectionate regard since my last communication,
yet I am ready to indulge a hope I am not wholly
forgotten by my much beloved exercised brother,
but that his solicitude for my preservation is unabated;
and though conscious of not meriting this privilege,
I dare not doubt possessing it in some degree,
believing our friendship to be founded on a basis too
permanent for the fluctuating things of time to shake,
or the changes of dispensation to weaken.
No, surely; I fully believe, as our abiding continues to be in the living vine,
and we are favoured, through adorable mercy,
to increase in the saving knowledge of redeeming love,
our hearts will be more closely bound together in the cementing virtue of gospel union,
and secret intercession will be made with the God of all grace,
that his all-powerful Arm of salvation may be vouchsafed, to keep in a humble dependence,
both in heights and in depths,
that no gilded bait or destroying weapon prepared by the cruel adversary,
may ever be able to exalt above measure,
or sink the poor tossed mind below a holy
confidence in Him who never was foiled in battle,
and remains to be the ever victorious Captain of the soul`'s salvation.

I seem to be furnished with very little consoling, comforting information;
having more often to sit down and lament over my own weaknesses and failings,
with those which are obvious among a highly professing people,
than to rejoice in the prosperity of Zion,
and joy in beholding the enlargement of her borders.
Yet I humbly trust, though things of a trying nature may be in our camp,
and the pure life of religion at a very low ebb, there are many preserved alive unto God,
who have not dared to bow the knee to Baal, or kiss his image;
but who are faithfully bound to the law and the testimonies,
counting not their lives dearer to them than the
blessed cause of truth and righteousness.
It seems to be a time of deep wading with such exercised minds,
because the beauty of Israel is much eclipsed,
and too few of her professed children are coming up to
the solemn feasts of the Lord with holy dignity.
Oh! when will an individual reformation take place,
that '`judgment may run down as waters,
and righteousness as a mighty stream;`' that the kingdoms of
this world may indeed become the Lord`'s and his Christ`'s.

[.signed-section-signature]
Ann Crowley.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Taber to Thomas Scattergood

[.signed-section-context-open]
Portland, Eighth month 9th, 1804.

[.salutation]
Dear friend,

As our friend Daniel Elliot is about leaving this place,
I feel as though I could not miss the opportunity of reviving the love and nearness,
I think we have in past times felt toward each other; and at this time,
as at many others,
you are brought very near to me in a belief that many and great have been your conflicts,
as well as mine, since we saw each other.
I may say, mine have often been so great,
that it has appeared there was but a step between me and spiritual death,
and that I should surely fall one day or other by the hand of Saul;
and I have my fears that it will yet be my case,
for lack of being sufficiently reduced to a willingness
to suffer with patience and resignation,
whatever may be my lot.
I have often thought of you in my greatest conflicts,
believing you are no stranger to deep baptisms,
but doubtless yours may be more on others account, and mine on my own;
but be that as it may,
I think the enemy of all good often takes the advantage at such times,
to cast out floods of discouragement, in order if possible, to swallow us up;
and sink we should, did not our blessed Master take compassion on us,
and reach out his hand, as he did to Peter, when his faith failed him,
and he was about to sink.

So that we have abundant cause to take courage and press forward, remembering,
as our day of trial is, so shall our strength be.
I write not to you with a view of instructing, but from a near fellow feeling with you,
which I think my mind has been dipped into this morning,
and I crave your prayers that my faith fail not; for it is often at a very low ebb,
and many fears encompass my feeble mind.
With near love to you and your dear wife, with which mine unites,
I remain your affectionate friend,

[.signed-section-signature]
John Taber.

--

[.offset]
The following letter from his friend David Brooks, is dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eighth month 15th, 1804.

I have not forgotten you nor your kindness to me when my lot was cast in your city:
there is One only who knows what I passed through there, I may say in a two-fold sense;
but I hope, and have some cause to believe that I was not altogether without companions.
I do not wish to complain or murmur,
for our afflictions are but light when compared to the sufferings of our blessed Saviour,
whose agony was so great that sweat, as it were,
great drops of blood rolled from his sacred face.

Dear friends, I often think of you with great sweetness,
and I feel an assurance that you are going on your way mourning,
as with your hands on your loins, and passing through dark and lonesome places;
but we may remember, there is no beast of prey to devour in the Lord`'s highway,
I sometimes have faith to believe, that the Lord`'s candle will be again lighted,
and hope we shall be enabled to wait patiently all his appointed time,
for he I that believes makes not haste; and he that runs when he is not sent,
will not be likely to profit the people.
A superficial ministry has a powerful tendency to close up and stop the sweet,
living spring of true gospel ministry.
It is a great lesson to learn to bear trials properly as they arise,
and I am sometimes afraid of myself,
I can bear so little with the Christian fortitude which becomes a soldier of the Lamb.
Dear friends, the distance of the way and the length of time,
only serve to strengthen the bond of that love
which stands in the power of an endless life,
in which I nearly salute you, and bid you farewell.

--

[.offset]
The following is taken from a letter written by him to Susanna Horne:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Fifth month 24th, 1805.

There is a secret rejoicing accompanying my mind,
in hearing of your industry to get forward in your day`'s work.
It is a pleasant thing to look back and remember the
willingness wrought in the mind to labour in the morning.
I feel it so, as one to whom the afternoon has come; there seems little to open with me,
except now and then to a quarterly meeting, but much at home.
Go on in fear and trembling still,--expect to meet with your various trials; wait,
I beseech you,
as one desirous you may be numbered among the true born
children--wait for the renewed touches of the live coal;
wait for the seal and evidence: this will make your language drop as dew,
to the consolation of the mourners and tried burden bearers,
and you wilt grow in your gift;
sound judgment will be experienced also to know what is sealed or seasoned,
where to deliver or scatter it, and also the time when; so living without carefulness,
in due time the Lord gives a right issue.

--

[.offset]
The following is extracted from a letter from his friend John Bevans, dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Plaistow, 1st of Second month, 1805.

[.salutation]
Dear friend,

It would have been very pleasant to me to have written to you before now,
but feeling my mind often clothed with much deep poverty,
it seemed as though I could not, either profitably to myself or to others,
take up the pen.
But from some little renewal of that brotherly love which unites the
Lord`'s children in that life which is better felt than expressed,
I can at this time salute you my beloved friend.
Trying times have been the portion of many brethren on
this side the water since you left us.
You and others have had your perils by land and perils by water,
but ours have been by false brethren, who,
by fair speeches and great pretensions to liberality,
have deceived and misled some in many places.
But I hope the firmness of Friends pretty generally on this side the water and on yours,
will in good measure put a stop to this delusive spirit.
These things have brought to my mind the deep
exercises you were often under while among us,
and particularly in our great city.
I believe there was a cause, which was not then altogether manifest,
but has since burst upon us as a gathered cloud; and I fear not a few,
more particularly among our wise men, are carried away with it.
At the same time, it is no small consolation,
that there are among us many faithful brethren,
and it is to be hoped that others have been stirred up to try their foundations;
and to such we may hope it will ultimately prove profitable.

I had written the above a considerable time since,
but feeling again too much discouragement from a variety of causes, I could not proceed.
Your last letter was very acceptable,
and the recollection that I had not acknowledged the former, has been painful to me;
yet it is not for lack of an affectionate remembrance,
but writing is become more a task to me, and living in this retired spot,
I see and hear much less of our friends than we were accustomed to do.
William Jackson paid our meeting an acceptable visit a short time since;
Ann Crowley has also been with us in the same way.
Thomas Colley has been much engaged among those not of our Society for sometime;
he was lately at Birmingham, where he had several public meetings,
to much satisfaction some of those meetings were held at
dissenting meeting-houses in different parts of the town,
for their accommodation.
Perhaps you may know that some of the disaffected among us have been very active,
and have published several pieces,
greatly misrepresenting the conduct of Society in the case of Hannah Barnard;
and also by mutilating the writings of our ancient Friends,
have made them to speak a language they neither intended nor thought of.
They have likewise endeavoured to invalidate several
parts of the Scriptures of the Old and New Testaments.
The above publications have much tendency to
turn the feet of the unwary out of the right way,
making the offence of the cross to cease,
and the path wide enough for the old corrupt man to walk safely in,
without danger of alarm, it being in their view,
sufficient to preserve a fair moral conduct before men,
without being shackled with the mistaken notions of a new birth from above,
and the necessity of an inward and vital change, which the humble,
self-denying Christian considers essential to his eternal well being.
They tell us our reason is the primary gift of God, and able to guide us safely along,
in all that is necessary to salvation,
rejecting the sacrifice and atonement of Christ as absurd.
Thus deluded and deceived, they attempt to mislead and deceive others,
and it is to be feared that too many are readily caught in the snare.

The account you have given of yourself since your return to your own quiet habitation,
has been very pleasant to us;
and that you have had to enjoy domestic comforts after much exercise, toil and labour.
The language of the prophet occurring, I shall insert it:
'`The work of righteousness shall be peace, and the effect of righteousness,
quietness and assurance forever.
And my people shall dwell in a peaceable habitation, and in sure dwellings,
and in quiet resting places.`'
The application I leave to my dear friend;
I believe this you can do from heartfelt experience.

[.signed-section-signature]
John Bevans.

--

From an apprehension of religious duty,
he spent the summers of 1805 and 1806 at West-town boarding school,
sometimes assisting in teaching, as well as in the care of the pupils.
He was very fond of the society of children,
and deeply interested in their eternal welfare: he freely mingled with the pupils,
and participated frequently in their amusements,
which gained their confidence and affectionate regard,
and enabled him to exercise an important and valuable influence upon them.
His religious counsel was also very strengthening and
encouraging to the teachers and others,
who found in him a true sympathizer in the arduous duties of their important stations.

A Friend who resided at the Institution at that period, speaking of his services there,
remarks, that "`he was concerned to enter closely into the care, the exercises,
and trials under which the caretakers were then wading;
and very useful and beneficial were his labours,
not only in their schools and private collections, from which he was seldom missing,
but in their religious meetings also; as many of those there in that day can testify,
to their great comfort.
From my distinct remembrance of his gospel labours, I then believed they were owned,
and now at this day can say,
I believe they have been crowned with success in many instances.
He was greatly favoured and enlarged in testimony in their religious meetings,
many times to the tendering and contriting of the minds
of those present who were of susceptible feelings;
and often was favoured in supplication with near access to the throne of grace,
to the comfort and bowing of every contrite soul.
Ah! these opportunities cannot be forgotten.`"

His interest in the institution continued to the time of his decease.
After returning from there, the last time in 1806,
he addressed a letter to the teachers through one of their number,
from which the following extracts are taken:

[.embedded-content-document.letter]
--

The plan you sent me met my approbation,
and immediately my thoughts were turned toward all the thoughtfully exercised teachers;
and I said in my heart, go on precious servants as you have begun,
and doubtless you will prosper.
Your station and work is honourable, and no doubt remains on my mind,
but that you are watched over and cared for by the great Shepherd of Israel, who said,
'`feed my sheep.`'
This is your employ; let your hands be strong in the work,
and resist all those discouragements, both within and without, which at times,
very likely, assail you.
I am not a stranger to your exercises, having been sensibly dipped with you.
Yes, you will believe me when I say my mind was exercised, feelingly so,
and plunged into most or all your trials, when with you,
and how preciously comfortable was the little fragment of my pilgrimage there filled up.
Many comfortable moments I enjoyed;
many pleasant prospects were opened respecting the rising of the church out of Babylon;
and I have, since that day, said in my heart,
O that there were many schools erected for children`'s guarded education.
As I have told you, your work is honourable, so I believe a precious reward awaits,
for giving up the prime of your days to perform it.
It is an easy thing in the sight of the Lord, even sometimes of a sudden,
to enrich for little acts of faith, and labours of love.
I frequently look at you with sweetness, and send this little messenger,
desiring it may prove, in some degree, an encouragement to you all,
on both sides of the house, to continue in the way of your known duty, continuing to be,
according to present ability,--your affectionate and sympathizing friend,

[.signed-section-signature]
Thomas Scattergood.

[.signed-section-context-close]
First month 6th, 1806.

--

From his labours at West-town, and the above letter,
it will be seen that he felt a lively concern for the religious,
guarded education of the youth of our Society,
being fully aware of the important influence such a course of
instruction would exercise upon them in after life.
His interest in schools, and the course of education, was not, however,
confined to any particular class.
He felt for all descriptions of his fellow men,
and was ready to promote their welfare in every right way.
He was especially qualified to feel for and sympathize with the poor,
among whom he was a very frequent visitor,
whose needs he was enabled largely to relieve by the assistance of his friends,
who frequently sent him sums of money to be appropriated for this purpose,
at his discretion.
His visits among the poor,
afforded him a good opportunity of observing the idle
habits and neglected education of their children,
which he saw led them into many immoral practices.
Being much impressed with the demoralizing
influences attending the situation of this class,
he communicated his feelings to a number of Friends,
and proposed to them to unite in an effort to establish a school for such,
on the Lancasterian system, which was then just claiming attention.
Having succeeded in interesting several in such an undertaking,
a meeting of Friends was called, in the ninth month, 1807,
to consider the propriety of forming an association to carry out their benevolent object.
The plan was cordially approved,
and in the next month the association was duly organised,
and was subsequently chartered by the Supreme court,
under the name of "`The Association of Friends for the instruction of poor children.`"
It was found necessary, in a short time,
to build a house for the purpose of accommodating the
large number of children who applied for admission.
Thomas Scattergood and another Friend gave the association a lot for this purpose,
and early in 1809 a building was erected,
in which the school was continued for nine years,
affording the blessing of moral and literary instruction to many destitute children.
In 1818, the education of the poor being adequately provided for by law,
the school was discontinued,
and the funds of the association allowed to accumulate for four years,
when they were appropriated for the instruction of poor coloured children,
for which object they continue to be very usefully applied.

The following are extracts from letters, addressed by him to his friend Susanna Horne:

[.embedded-content-document.letter]
--

1806+++.+++--I have done but little at writing of late, and feel but small ability,
nevertheless my thoughts often waft over to you,
and I still feel interested in your welfare,
though much as one on whom the ends of the world is come.
This you know was much the case once, and what marvel, when it has been,
and very likely must be, the experience again of many in your land.
Wherefore do I see every man with his hands on his loins?
etc.; this is the portion of Zion that dwells in the midst of Babylon;
and when the dispensation is yet more fully known,
there will be a rising and shaking of the dry bones.
I am glad you remain desirous to be one of her exercised travailers; go on and prosper,
and fulfill your task, while strength of body and mind is vouchsafed;
and you wilt never have cause to repent your enlistment into such a work.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Sixth month 9th, 1809.

Leaving the things that are behind, let us press forward:
O that the blessed Master may account us worthy to be
employed in his work during our few remaining days.
As for you, you seem to be going from one little service and journey to another, much,
I think, as I was when about your age, I seem, at least sometimes,
like a vessel laid up in dock.
Perhaps this may be more your state bye and bye,
and if you are upright and honest in the present season, it will be no matter then.
Though the body has been much stationary, yet my mind is often far off from it.
My exercise was not small when among you, in often mentally visiting the continent,
and beholding the distress began and coming more upon nations and kingdoms;
and I am still often abroad in mind.
Surely, I have said in my heart, the Lord has arisen,
and is shaking the foundations of the earth: this,
I think was more like a promise than otherwise,
that the heavens and earth should be shaken,
that so that which could not be shaken might remain;
but how little is this seen into by many.
May we, dear friend, be washed from every defilement, both of flesh and spirit;
and press after holiness--press after a settled stable mind,
in which the divine will is given up to, is the desire of your friend,
on his own account, and also on account of you, whose welfare is very near to him,
and who yet remains your affectionate friend,

[.signed-section-signature]
Thomas Scattergood.

--

In the fourth month, 1811,
he obtained the necessary certificates of unity with his prospect to pay a
religious visit to the yearly meetings of New York and Rhode Island,
and some of the meetings composing them.

In this journey he accompanied his beloved friend Susanna Horne, from England,
who was then engaged in a religious visit to this country.
The first memorandum of this visit commences at Lynn, and is as follows:

[.small-break]
'''

"`Seventh month 21st, first-day.--Attended two meetings at Lynn; on the 23rd,
a meeting at Salem, which was a comfortable time;
and on the 25th had a meeting in the large Methodist house at Boston, at four o`'clock,
which was satisfactory.

"`28th, first-day.--Went to Salem meeting, where I was silent,
and it was a very low time with me.
The afternoon meeting was largely attended by people of other societies,
and I was favoured with enlargement toward them.

"`29th.--To Amesbury, to old Jacob Rowell`'s; he is in his eighty-eighth,
and his wife in her eightieth year.
Stopped and dined at Newburyport, and as soon as I was out of the chaise,
I turned involuntarily down the street to view the ruins made by a late fire.
It appears to have consumed even to the water`'s edge,
and some of the wharves did not escape, about two hundred and fifty houses were burned.
We sent for some of the inhabitants; eight or ten of whom came,
and we proposed a meeting for tomorrow afternoon, to which they readily consented,
and the courthouse was procured.

"`30th.--Amesbury meeting was small and a poor low time;
after which proceeded to Newburyport, and had a very crowded meeting,
which was satisfactory--we were taken home by Ebenezer Wheelwright to tea,
where a number of the neighbours came in, and it was an agreeable time.

"`31st.--To meeting at Seabrook: it was a remarkably warm day, and the labour fell on me.
Susanna Horne was so overcome with the heat as to take to her bed for a time,
but afterwards she took courage and rode in the afternoon eighteen miles, to B. Folsom`'s,
at Epping.

"`Eighth month 1st.--To meeting at Epping, where several of the neighbours came in,
though it was a rainy morning, and it proved a pretty open time.
After dinner set off accompanied by Eli Beede,
and lodged at an inn about fifteen miles distant, where we met with poor accommodations,
but the kindness manifested made it easy.

"`2nd.--Rode to Henniker, over a rough road, eighteen miles,
and lodged at Pelatiah Purington`'s, which was a comfortable resting place.
Had a satisfactory meeting, and a good opportunity in the family.

"`4th, first-day.--To the meeting held in the north house at Weare; dined at W. D.`'s,
and before we set off had a tendering opportunity,
in which the old man was much affected.
At four o`'clock went to meeting in the south house,
about three miles off--both of these meetings were laborious and pretty large.

"`5th.--After a pretty early breakfast, and a good opportunity with this large,
and in good degree, well conducted family,
where there are hopeful children and careful parents, accompanied by David Gove,
we rode back to Concord.
Stopped at R. B.`'s, whose husband is not a member; she has seven miles to go to meeting:
here we had a little opportunity, which I hope was to some profit.
Dined at Abel Houghton`'s, and at four o`'clock went to a meeting in the courthouse:
there were about twelve or fifteen members, all women and children except two;
Susanna had a pretty relieving, good time.
I felt like a sign to be gazed and wondered at.
We detained the little company of members after the others were gone,
and had a comfortable opportunity with them.

"`6th.--Went to Pittsfield, and it was a pensive time to me,
and nothing to do in the meeting; being covered with a cloud of exercise,
and exceedingly empty and poor: I thought Susanna had a pretty open time.
After dinner rode to Gilmantown--put up at E. Hoyts`'s. This
Friend and his wife came into Society about sixteen years ago,
and since there has been a gathering to them of others convinced,
and some Friends who moved from other places.
When we were within a few miles of this place,
our guide proposed beginning to invite to a meeting to be held tomorrow,
but I felt an entire stop in my mind,
and on mentioning it to Susanna we freely agreed to go on to a Friend`'s house,
and wait there to see what would be best.

"`7th.--My mind was much exercised after getting up,
and I walked out pensively before breakfast,
and when we sat down to eat was engaged in supplication for our little band,
and all left behind--for this family, and for the enlargement of Zion`'s borders;
and felt more easy after it.
Yesterday afternoon I thought we were going to a Friend`'s
house which would be a resting place,--and so it proves,
and we need it.
After breakfast took a lonely walk,
and enjoyed the beautiful and extensive prospect which it afforded.
Sat down in inward retirement afterwards,
when the situation of some of the Lord`'s exercised prophets came into remembrance;
such as Elijah and others, who wandered about in desolate places;
as also the temptation of the greatest of all, even the Lord Jesus himself,
in the wilderness;
and I strove in his name to offer up a petition for the blessing of preservation,
through and over these besetments, which so cleave to me in this my pilgrimage state.

"`8th.--To a pretty large meeting, made up of the few Friends hereaway, and others.
It was laborious, and the service fell pretty much on me: we stopped Friends afterward,
and Susanna was favoured measurably to get relief.

"`9th.--Accompanied by our friend E. Hoyt, we rode to Sandwich, about thirty-one miles,
to Cyrus Beede`'s. It was a delightful hilly country, and a good road.

"`10th.--To a meeting about seven miles further,
held at Solomon Hoyt`'s. This was a time of favour and encouragement:
dined at John Folsom`'s,
and afterwards had a very satisfactory opportunity with the family.

"`11th, first-day.--After breakfast Benjamin Scribner came in;
he was much broken on meeting with me, and continued in this tender condition sometime.
Cyrus Beede related to me the following circumstance: when I was here before,
a man who lived at some distance, came into the meeting,
which was then held at Benjamin Scribner`'s, and endeavoured to get his brother,
Aaron Beede, to follow him out;
but upon every attempt Aaron motioned for him to sit down,
and at last prevailed on him so to do, and he stayed the meeting out.
In the course of the communication,
mention was made of the grievousness of the sin of injuring our neighbours,
and that such as did so, would be met with sooner or later.
This man, after getting home, which was immediately after meeting,
went to one of his neighbours, and told him that he had injured one of his oxen,
and hid him in the woods, and offered to make him restitution for the same.
It was not known what he wanted with Aaron Beede when he came to get him out of meeting.
The house at Sandwich could not contain the people who came to meeting.
This proved a tendering time; and we were both pretty largely engaged therein.
After meeting, Samuel, son of Benjamin Scribner,
was introduced to me as I came out the door;
his eyes overflowed on my saying a few words to him.
I was also introduced to several after meeting,
who remembered me when I was here twenty-seven years ago.

"`On being informed that the people who met in a large house not far distant,
would not come to our meeting,
some Friends went and proposed for them to consider
whether they would come in the afternoon to our meeting,
if they thought there would be room,
or give me an opportunity with them in their own house:
they thought the latter would be best, namely: for us to come to their house.
We went, and I got relief thereby;
my friend Susanna Horne did not feel much of this concern, yet bore me company.

"`12th.--Set off about eight o`'clock, accompanied by Nathan Beede to Wolfborough,
and got to Joseph Varney`'s. Paul Bunker met us here;
he went on yesterday afternoon and appointed a meeting in this house at three o`'clock.
In this meeting Susanna had all the labour:
we stopped the little company of Friends afterwards, and it was a tendering time,
as also next morning with this family, on parting.

"`14th.--Reached the monthly meeting at Middleburg, and then to Rochester and lodged.

"`15th.--To select monthly meeting at Berwick, fifteen miles.
This was a small meeting, but a time of some comfort and encouragement.

"`16th.--Very low and under discouragement this morning.
Trust in God, O my soul; I hope yet to praise him.
We attended the monthly meeting in this place, and found things low,
Joseph Savage spoke to me after meeting;
he was a captain in the artillery in the time of the war, and quartered at Burlington:
he appears measurably convinced of Friends`' principles.

"`17th.--To William Brown`'s near Dover, and on the 18th, first-day,
attended their meeting.
It was very large, though no liberty was given to invite the neighbours.
We learn that there is much division and unsettlement in this place;
no priest among them at present, and therefore no meeting.
It proved a pretty open time,
and this large assembly was recommended to the Lord Jesus Christ,
the everlasting Teacher and High Priest.
This has been a day of exercise to me on various accounts, but I trust profitable.

"`19th.--Stayed at William Brown`'s until about eleven o`'clock,
and then I rode with him to Rochester.

"`20th.--Had a favoured meeting, appointed at this place,
and in the afternoon went on toward Berwick again.
I lay down in sorrow, in consequence of not keeping the girdle of truth girt close enough.
Ah! what a little deviation affects a mind that is tender.
The cutting off but a small piece of Saul`'s garment by David, when he was in his power,
made his heart smite him, and so has mine, and I begged pardon almost immediately,
and yet I feared I should be set aside for a time for this.
O my God and Saviour!
I have covenanted to serve you all my days--preserve my feet from falling.

"`21st.--Meeting of ministers and elders,
and to my admiration I was exercised in it in the line of ministry.
Ah! here was no room for exaltation, neither on looking into myself, nor over the flock;
there is yet bitterness in my cup this evening.

"`22nd.--To a large congregation of Friends and others, assembled at quarterly meeting,
and we were pretty largely engaged therein;
it appeared to be a solid time for the most part.
We sat from eleven to near five o`'clock,
and at the close of this great day`'s labour I felt comfortable and thankful.

"`24th.--To Windham monthly meeting; where we had a good time in the first meeting.

"`25th, first-day,--To Falmouth, and I was shut up in silent exercise:
Susanna relieved her mind, and I was glad of it.
After meeting stopped at Stephen Monall`'s, and visited his sick wife in her chamber.
When I was in this land before, I had a remarkable opening at two different times,
as I sat in this meetinghouse.
One was to go directly back to Boston,
and then take such meetings as David Sands and I had left on our way here,
and also the monthly meetings, and among the places was Sandwich, then a wilderness;
all which was accomplished to my great peace and comfort,
for I got through the prospect that opened, and returned to Falmouth in one month,
and attended the quarterly meeting.
While sitting in that, I had an opening of the way home very clearly, even to a day,
and my soul, with thankfulness, remembers the favour while penning this note.
Now I am shut up--there are great changes in twenty-seven years,
and no virtue in meeting-houses, I find.
Dined at John Winslow`'s, and he and wife went with us to Portland,
to an afternoon meeting, where was a mixed company, and very unsettled.
Susanna had but an exercising time, and I was quite shut up.

"`26th.--We got into Joseph Douglass`' at Durham, before night.

"`27th.--After an opportunity with two widows and their children,
attended the meeting at Durham, which was large, and an open time.

"`28th.--To Amos Davis`', and put up before meeting, which was held in a school house,
an awkward place: Susanna Horne had all the labour.
I felt for her, and for this very little company of Friends,
but there was no food in my barn, nor wine in my press.
Proceeded on our journey and lodged at Joseph Samson`'s. This Friend, it appears,
was a soldier in the revolution, and settled here twenty-seven years ago.
The two first years he came and cut down a few trees, burnt the brush and upper limbs,
and planted a little corn without the use of plough or harrow,
for he had neither ox nor horse for some time: he then brought his wife,
after raising a small habitation for her,
and had to carry a bushel of corn eight or ten miles to mill on his shoulder,
and for seven years had not above one dollar in possession;
now he has a pretty large habitation.

"`29th.--To meeting at Leeds, and put up our horses near the meeting-house, at J. W.`'s,
on a remarkably high hill, from which there is an extensive prospect.
This was a good time, and after the meeting went back to J. W.`'s and dined;
with this family and some others we had a satisfactory opportunity before we parted.

"`30th.--This morning we paid a visit to two ancient Baptists,
living in a small adjoining house, and after I had delivered what was on my mind,
the old man preached us a little sermon.
The meeting was a good one, although small.
After dinner and a comfortable opportunity with the large family where we dined,
we took our departure again, and rode fourteen miles.
About half this distance we ascended a high hill, from the top of which Augusta,
on the Kennebeck river, opened to our view,
with the land on the other side--a very delightful prospect indeed;
nothing have I seen in this journey, that came nearer, in my view,
than this to some of the beautiful spots in England.
We got to our friend S. W.`'s, at Sidney, about dark, and met a kind reception.

"`31st.--To meeting, which was held in a comfortable house, and proved an open,
good time; we stopped in at the nearest house and had a tendering time with D. P.,
wife and children, and after dinner proceeded to Belgrave.

"`Ninth month 1st, first-day.--In the morning returned to W. D.`'s before meeting time;
this industrious,
goodly Friend fitted up his house with benches to pretty good advantage,
and we were favoured in a large meeting:
a motherly old woman came to me after it broke up, and inquired after David Sands,
saying, with the tears running down as she spoke,
'`Ah! he was the first that offered up public prayer for us in this remote country.`'
After dinner we proceeded to Fairfield, about twelve or fourteen miles.
This seemed to be the roughest ride we have experienced.
In one or two instances our guide endeavoured to hold
up our carriages to prevent them from overturning.

"`2nd.--To meeting in a comfortable meeting-house,
which I conclude has been the most enlarged
meeting we have had since we have been together.
Marvellous it was to me, to think of being here,
when I looked back and remembered being at Vassalborough years ago,
when nothing but trees and rocks were to be seen in these parts,
and now a large and open meeting.
We had some satisfactory conversation with a serious professor who requested it.

"`3rd.--Set off about eight o`'clock this morning, after a religious opportunity,
and rode about nineteen miles to Moses Sleeper`'s, at Vassalborough,
about two miles beyond the meeting-house.
This Friend was a soldier in the American war, and being convinced,
came among Friends a little before David Sands and I visited this neighbourhood.
I remember well the visit David and I paid him and wife, then lately married;
he had cleared about half an acre of land and built a small log house.

"`4th.--To select meeting--it was not large, but ended, I thought,
profitably and comfortable.
I took Susanna Horne and Mary Allinson in our chaise to it, about two miles.
On our way home, when within about half a mile of Moses Sleeper`'s,
the horse suddenly took fright,
and we appeared to have a very narrow escape from broken limbs, or death itself;
thanks be rendered where due.

"`5th.--To quarterly meeting, which was large;
and I thought Susanna Horne was much favoured:
the business was conducted with condescension,
and on the whole it was a satisfactory time;
we had the company of various Friends in the evening, and a religious opportunity.

"`6th.--To Haarlem meeting, on the far side of the Pond, twelve miles distant,
accompanied by Moses Sleeper; the house is not quite finished,
but pretty well fitted with benches, and we were favoured with a large meeting,
to my surprise.
I thought many goodly ones, both Friends and others, were there:
the labour of this day has fallen on me, and it was a memorable day to me,
both before and in the meeting.
We went in the afternoon to Moses Dow`'s and lodged, near the Pond meeting-house,
about five miles from Moses Sleeper`'s.

"`7th.--To the Pond meeting, which was large.
Susanna Horne spoke first, and had a favoured time,
and indeed it was a remarkable meeting;
there were two appearances from professors--the first short and the other long,
but we thought best to bear with them, and hope the meeting ended well.
We put up in a little village; and I am in admiration at the increase of the country.

"`8th.--Went to Kennebeck meeting, which proved a sweet parting time;
Susanna Horne opened it in supplication, which I felt not only on the way to meeting,
but soon after sitting down, and therefore could feelingly unite in it,
and trust encouragement and strength were administered
to us by the great and good Shepherd of Israel.
We rode in the afternoon seventeen miles, to George Randall`'s,
and called by the way see a man, by the name of Gitty,
who told me that he is one hundred and twenty-two years old.

"`9th.--Attended an appointed meeting in an unfinished Methodist meeting-house.
It was the day of general muster,
and but few came besides George Randall`'s family and one more,
but it proved a very solemn,
sweet opportunity--the service lay with Susanna Horne pretty much, and I felt content.
Low and poor this afternoon,
anxiously concerned rightly to see my way in further movements.

"`10th.--To Samuel Tobey`'s, at Bristol, about thirty-three miles:
part of the ride today was through a wilderness,
but in other parts there were remarkably good houses.
We stopped at Nobleborough and dined: here we met with uncommon accommodations;
the house being a very neat one, and the furniture in accordance with it.

"`11th.--To meeting about two miles distant: the house is opposite to Broad Cove.
The company was not large, and Susanna Horne had all the labour.
I was very poor.

"`12th.--Set off early, passed through Nobleborough and dined at Wiscassett, a seaport,
which appears to be a thriving place.
We lodged at village called Brunswick; this appears to be another thriving place,
and but lately cut out of the woods; they have already a pretty large college,
a president`'s house and chapel, on a very beautiful level.

"`13th.--Got a pretty early breakfast and proceeded to Portland;
found some difficulty when we came to North Yarmouth bridge,
and had to be ferried over the river.

"`14th.--A night of conflict when awake; I seem broken up as to moving on,
and O how I am veiled--I cannot go forth out of prison.
I have been thinking of the prophet`'s expressions, or the apostle quoting him,
respecting our blessed Lord and Saviour: '`In his humiliation his judgment was taken away,
and who can declare his generation; for his life was taken from the earth.`'
O that I might hold the mystery of faith in a more pure conscience;
then may my soul hope for deeper and more lasting
instruction by what is permitted to befal me.

"`15th, first-day.--Very close searching of heart upon my bed this morning,
and feel a little more peaceful and quiet:
what need of patience and resignation to wait the Lord`'s time, which cannot be hastened.
I passed through both the meetings in silent conflict, and Susanna Horne also.

"`16th,
second-day.--Susanna Horne has her mind turned toward a little company on
the Cape opposite this place +++[+++Portland]. I am very blind and cannot help it.

"`17th.--Resigned, I trust this morning, into the arms of Christ,
for protection and further help, who can anoint mine eye to see how to move,
and what to do.
Lord, I would most willingly resign my state, present and future, to your disposal.
I have been greatly distressed in this place.
I hear that there is great profession of religion,
and a great variety in this little town; but ah! the living, eternal Truth is but one:
the Lord, he is one, and his name one; bow then, unto him, O my soul,
and serve him the remainder of your days here on earth.
Before we set off to attend the meeting, held at Nathaniel Dyer`'s, on Cape Elizabeth,
we sat down with S. H. and family, and by this means my mind was greatly relieved,
and we parted in much brokenness and tenderness on the part of some.
Left my companion to see after mending the chaise, and R. Horton took me in his.
This has been an encouraging meeting,
and I have a hope there will be an increase hereaway.
We called by the way at W. F.`'s, who lately came into Society.
His aged parents live with him, and this dear old man was tendered, both in meeting,
and now in a sitting with the family; the case of good old Simeon being treated on:
he appears to love Friends and their company.
Parted tenderly from the family and reached Calvin Stuart`'s before night.
A great change in my feelings, but feel the effects of so deep a plunge;
surely I may say with David,
'`My heart and my flesh also fainted in the hour of conflict.`'

"`18th.--Susanna Horne had all the public labour in the meeting held today.
Soon after it broke my companion arrived, accompanied by Edward Cobb,
who continued with us to Kennebeck,

"`19th, fifth-day.--To Paul Rogers`' at Berwick, where we had a meeting,
made up chiefly of Friends.
Dear Susanna had an open, enlarged time.
It was a season of light, comfort and encouragement to me:
I remembered the remarkable tendering time we had in this house when with David Sands;
how exceedingly I was broken into tears, and which continued with me on the road;
how all my prospects closed up after getting into this house,
so that David Sands had to wait for me until morning;
the many baptisms I then passed through in this eastern country,
and also how marvellously my way opened to go home,
and the sweet peace I enjoyed for giving up to the service, together with prospects,
conflicts and exercises endured since, in Carolina and England,
and now of late continued.
I fell prostrate in humble acknowledgment to the great Author of all good,
thanked him for mercy and deliverances past,
and supplicated with brokenness of heart for the
continuation of support in all the future:
it was a day to be recorded, of release and relief.
After dinner we had a remarkable opportunity with the family and two other Friends,
and parted in great nearness, and accompanied by Paul Rogers,
proceeded to William Brown`'s at Dover.

"`20th.--To a meeting at Dover, appointed for Friends only,
which was an open satisfactory time.
Dined at M. Osburn`'s, and then rode to Seabrook, twenty-two miles.

"`21st.--After breakfast sat down with this family and
had a solid time--the labour fell on me.
I felt engaged to supplicate, and was very peaceful and easy on the way to Salem,
thirty-two miles; where we arrived about the fourth hour, and put up at our kind friends,
Matthew and Betsey Purington`'s.

"`22nd, first-day.--To Salem meeting, both morning and afternoon:
in the first I had a pretty relieving, satisfactory time.
I was favoured, I thought, in the afternoon, both in testimony and supplication.
We drank tea at A. Chase`'s.

"`23rd, second-day.--We rode to Boston, accompanied by William Brown, Jr.,
and Betsey Purington.
Put up at John Fry`'s, near the meeting-house,--an old man about eighty,
who lives in an ancient habitation.
He received us kindly, and we had a parting opportunity with him and his family.

"`26th.--To Smithfield monthly meeting, which was a satisfactory time;
I had a sweet opportunity after a solid pause in the close of the meeting for business.
We dined at Walter Allen`'s, and then moved on about four miles, to R. Southwick`'s,
and lodged.

"`27th.--To Uxbridge monthly meeting, held at North Bridge;
silent suffering and exercise were my portion throughout.

"`28th.--To Uxbridge, where we had a satisfactory time,
and in the evening went to Providence with our kind friends, Obadiah Brown and wife.

"`29th, first-day.--To meeting at Providence, morning and afternoon.

"`30th.--To Greenwich monthly meeting.
This was a remarkable meeting throughout; they looked and felt like Friends,
and conducted the business with weight.
We had a very sweet opportunity with a young man, who was invited into the meeting;
just at the close of the business, on the men`'s side of the house, I told Friends,
that if the women had done theirs, it would be pleasant to have the shutters opened.
They were, and we both had a relieving time; Susanna Horne in testimony,
and I in supplication, and the meeting closed sweetly.
After visiting a sick Friend returned back to Obadiah Brown`'s.

"`Tenth month 1st, third-day.
A meeting is appointed at six o`'clock this evening for the inhabitants of Providence.
Dined at Moses Brown`'s: I rode with him in his chaise,
and when we came in sight of his house,
my mind was affected in remembrance of past occurrences.
O how marvellous are the changes to be met with--yesterday I was greatly favoured,
was light and easy after so good a meeting;
this afternoon the sense and weight of death and darkness overspread.
I walked out and could have fallen prostrate on the earth,
if it would have been of any avail.
Went to the evening meeting low and tried here my female companion had a singular time,
and near the close I ventured to express a little of what impressed my mind,
and felt more easy.

"`2nd.--To a meeting appointed at Smithfield.
I rode with Moses Brown: it was a small meeting, and a low time in the beginning;
and for most of the time I thought there was no labour for me; but a little arose,
and I expressed it, and felt relief.
Dear Susanna followed; more light, life and comfort sprang up,
and under a sense of it my soul bowed in thankfulness, and had, before the close,
to acknowledge it in prayer: had a sweet ride back to Providence.
How different the feelings of my exercised mind, to what they were most of yesterday.

"`3rd, fifth-day.--After breakfast, and an opportunity with Obadiah Brown and family,
which was a tendering one, we went to Cumberland meeting, eleven miles:
this little company appear to be most of them convinced ones.
Several serious people dined with us at D. Metcalf`'s, near the meeting-house.
After which we went to Samuel Smith`'s, twelve miles, and lodged,
accompanied by Obadiah Brown.

"`4th.--To Mendon meeting, three miles.
It was long in gathering, and rather trying,
but closed solidly--Susanna Horne appeared in supplication.
In the afternoon rode to Worcester, eighteen miles,
after an opportunity with the family we dined with.

"`6th, first-day.--To Leicester meeting, which was pretty satisfactory:
dined at P. Earle`'s, after which had an opportunity.
Set off accompanied by Obadiah Brown, and got lost,
but after riding about ten miles we put up at a very comfortable inn.

"`7th.--Left this place early, and rode twelve miles to another inn,
where we had a religious opportunity with the innkeeper`'s family.
Alter breakfast proceeded, and on our way stopped to get some refreshment,
and had a sitting with a pretty large family; after which we rode to E. Cook`'s,
at Pelham, and met a kind reception.

"`8th.--A rainy day, and but few Friends at meeting,
and the other part of the company mostly raw looking people--a
number of women and girls without bonnets or caps.
We set, I believe, more than two hours in a very trying, cloudy silence,
and being near breaking up, E. Cook spoke a few words; '`That although Paul might plant,
and Apollos water,
it was God who gave the increase;`' after which a little more sprang up in my mind,
and an opening to minister, which, though trying work, was some relief to me.

"`10th.--To a large meeting at Richmond, which proved an open time.
We both had relieving service;
and supplication was offered for the extension of mercy and kindness to New England,
and thanksgiving for preservation in it.
Now we felt a release,
this being the last meeting within that yearly meeting which we are likely to attend.

"`11th.--To Rockingham, twenty-three miles, and dined, which was a pleasant ride.
This afternoon we rode eighteen miles over a turnpike through a wilderness country,
at least it appeared so, though we saw here and there a farm.
We put up before night at an inn in Cavendish, a pretty village.

"`12th.--Arose this morning, as we did yesterday, by candle light;
got our breakfast and rode twelve miles to Clark`'s inn, called Mount Holly.
I may with thankfulness, record this morning`'s ride, as being sweet and comfortable.
Got to Stephen Rogers`' in a pretty heavy rain, where we met a hearty reception.

"`13th, first-day.--After breakfast I walked to a woods on the hill,
and opposite to a high mountain: here my mind was brought into a calm,
and faith granted to believe I was here in the will of my God,--when desires arose,
that from henceforth in travels through this yearly meeting, his will manifested in me,
may be done by me, and thereby prove my sanctification.
Thanks be rendered for the renewed extension of mercy and favour.

"`To Danby meeting; and previous thereto,
felt liberty to encourage Stephen Rogers to mention our
being likely to attend it this day week.
Some close exercise, and also labour, fell to my share.
In the afternoon I had a very deep plunge, and for a time I was fearful it was all wrong,
and that I had been too presuming; and yet, on examination, could not accuse myself.
Was helped by Stephen Rogers in conversation in the evening.

"`14th.--Felt easy to have a meeting appointed at Wallingford, about eight miles off.
This meeting was held in a Presbyterian house, at two o`'clock.
Our friends thought it was a satisfactory one,
and we came back a few miles and lodged at N. Lapham`'s.

"`15th.--After breakfast went to Joseph Button`'s,
and concluded to have notice given of our intention of being at Granville tomorrow,
Pollet fifth-day, and Dorset sixth day.

"`16th.--There were but few of the neighbours came to the meeting at Granville,
and to me it was a distressing time, we were both silent,
A company came in and stayed some time, when one of them said, '`Let`'s go,
it`'s near dinner time,`' etc.
It was preparative meeting, at the close of which we had the shutters opened,
and a pretty good time with Friends.

"`17th.--To Pollet, and had a meeting in the Presbyterian meeting-house:
here the labour fell altogether on me, a poor stripped creature.
We dined at a friendly man`'s, belonging to the congregation, where came three men,
and had considerable conversation on points of doctrine;
to one of whom Stephen Rogers related a remarkable circumstance respecting an Indian.
The Indian wanted a pipe of tobacco,--one in company
put his hand in his pocket and gave him some.
The Indian turned away to fill his pipe and discovered a a small piece of silver among it.
The Indian expressed himself afterwards nearly in this manner, to some company;
'`Two men talk in my breast, the good man and the bad man; the good man say.
Carry the silver back; the man that had it did not mean to give you the silver.
The bad man say.
You fool what is freer than a gift, and you can buy a dram with it;
but the good man speak again, and says.
Do as you would be done by; the man did not mean to give you the silver.
Then I thought I would sleep upon it,
hoping I should be left quiet in my mind about the silver;
but I could not sleep--the two men talk so to me all night long:
in the morning I was made willing to carry back the silver, then I found peace.`'
Stephen Rogers then said to one of the most zealous and talkative,
'`Take this home with you, and weigh it carefully in your own mind, and when prepared,
I should be glad to see you at my house,
and inform me whether there can be found a better guide and director in any man,
than that which the poor savage Indian found.`'
We proceeded several miles to Dorset,
and put up at Sylvester Cheeseborough`'s. It was rather a trying evening;
my spirits were sunk before we got into this Friend`'s house, and I had a sleepless night,
many things crowding in upon my mind, so that I almost wished to be at home.

"`18th.--Went to a meeting held in an unfinished house,
where Susanna Horne had an enlarged opportunity, and I felt very content in silence.
We all dined at Sylvester Cheeseborough`'s, and afterwards had a religious opportunity.

"`19th.--Felt a sweet calm on waking; but why not give thanks for trials,
seeing the trial of our faith is precious: '`In everything give thanks,
for such is the will of God concerning you.`'

"`20th, first-day,--To a very large and satisfactory meeting at Danby,
where were many youth, I feel thankful we have got through this arduous week`'s exercise.
A large company came to see us in the evening,
among whom we had a religious opportunity.

"`21st.--Accompanied by Stephen Rogers, we rode this day to Cambridge.
Put up at Dr. Smith`'s, whose wife is a member:
here we met with a kind and hospitable reception.
Not long after we arrived,
two serious neighbours came in and spent a part of the evening with us,
having heard that some strangers were come;
they supposed it was Esther Griffin and Hannah Field, who, on their way to Canada,
lately visited families at White creek, about eight miles from here,
and had extended some visits to families not Friends, in or near this place.
Before these men left, we proposed a meeting, which was approved of.

"`22nd, third-day.--I feel placid and quiet in my present circumstance;
let us then wait for further manifestations of our heavenly Father`'s will,
and when favoured with them, cheerfully obey.
We had an opportunity with this family after we dined, and proceeded two miles,
to what is called the Checkered Inn, where the meeting was held in a large upper chamber.
It was filled with people, and was a satisfactory time, manifestly so,
by what was expressed at the close, as also the affectionate behaviour of the people.
The two friendly men who visited us last evening obtained this place to hold the meeting,
and it evidently appeared they took much pains to get their neighbours together.

"`23rd.--To Cambridge meeting, held in a school house, which was but a low time.
We had a sitting with this family and then rode to J. Dillingham`'s, at Easton, and lodged.

"`24th.--The remains of an ancient Friend named Gifford,
were buried before the meeting at Easton.
The company came into the meeting, which was mostly made up of Friends,
and it was a good time.
We returned to J. Dillingham`'s,
and had a comfortable sitting with his large family in the evening,
and felt much united to both parents and children.

"`25th.--Crossed the river and attended meeting at Saratoga, held for Friends only,
which was a singular time.

"`26th, seventh-day.--We rode to Troy: we were informed that twenty-six years ago,
there was only the ferry house and another in Troy.

"`27th, first-day.--To meeting in Troy;
and my mind singularly exercised with fears that all present did not
walk and act in the true faith once delivered to the saints,
and had a relieving time.
At the close we appointed a public meeting, to be held at six o`'clock;
which was an unsettled, trying, dull one to me--I felt entirely shut up.
'`If another shall come in his own name, him you will receive.`'

"`28th.--We could not get off according to expectation and desire this morning,
and so stayed until after dinner,
before which had a religious opportunity with J. G. Proceeded to Albany,
where a clever little company assembled in the evening,
and we encouraged them to consider whether it would not be right to sit together,
and keep up a meeting in this place.

"`29th.--After breakfast crossed the river at Albany and rode to Henry Marriott, Jr.`'s,
about twenty miles, and after a religious opportunity proceeded to Klinykill.

"`30th.--To Klinykill meeting, which was rather a laborious time.
We dined at A. Macey`'s,
and after a religious time with this large
family returned to Henry Marriott`'s and lodged;
here we had a religious opportunity before we retired.

"`31st.--Went to Hudson meeting, which was a solid, comfortable season.

"`Eleventh month 2nd.--Susanna Horne and companions set off for Nine Partners.
I tried it until our chaise was brought to the door,
and did not feel easy to leave this town.
After they left me we crossed the river to Athens, and went to John Alsop`'s:
while sitting there my thoughts were turned to
another family whose names I had heard mentioned,
and was free to go, and so went on from place to place,
until we visited all the families except one, being twelve in number.

"`3rd, first-day.--To meeting, and had a satisfactory, open time, much as last fifth-day.
After dinner went to visit the crippled and maimed.

"`On the 4th, accompanied by several Friends, we rode to Henry Hull`'s,
and on the 5th attended the select meeting at Nine Partners,
where we met with David Sands and wife.
It was a low time with me on the way to meeting this morning,
but I was raised up before it closed;
dear David being favoured to speak feelingly to my state, and I thought to my companion,
Susanna Horne`'s also, whom we met again at this place.
Dined at Isaac Thorn`'s,
and afterwards paid a visit to the Yearly meeting boarding school;
went through the different rooms among the children,
and had a meeting with them and the family in the evening.

"`6th, fourth-day.--To Nine Partners quarterly meeting, which was a favoured,
good time throughout.

"`7th.--To Stanford, to Henry Hull`'s, and walked to meeting,
which was a remarkable time of instruction and favour,--back and dined,
and drank tea at John Hull`'s, with many Friends,
and afterwards had a religious opportunity.

"`8th.--The quarterly meeting at Stanford was a remarkably favoured time.

"`9th.--To an appointed meeting at Pleasant Valley, which was small,
but a favoured season.

"`10th.--To meeting at Poughkeepsie, which was held in an upper room in a dwelling house.
In the evening to an appointed meeting in the courthouse, which was large,
and a quiet favoured season.

"`11th.--This morning David Sands and wife accompanied us to Marlborough,
where we had a satisfactory meeting.

"`12th.--To a meeting appointed at the Valley,
after which we rode to D. Birdsall`'s. I felt pilgrim-like on riding up to this house.
The hearty reception of this Friend measurably healed me.

"`13th.--After breakfast sat down with this large family and had a comfortable time.
Proceeded to Newburg, which I suppose is the spot where the American army lay,
when David Brooks and myself passed through it thirty-five years ago.
We had a meeting in the courthouse, which was very small, but a comfortable,
instructive season.
In the afternoon rode on to David Sands`',
where we were received with much affectionate kindness, and spent the evening pleasantly.

"`14th.--To meeting, which was large, and an open, satisfactory season;
much so it appeared to dear David Sands and wife.

"`15th, sixth-day.--After a very solemn time in the family,
wherein near sympathy was felt, we proceeded to an inn, about thirty-two miles.

"`16th.--Set off about daylight on our journey.
At Sussex courthouse we got directions about the way, which appeared not to be correct.
We got lost in the woods, and after riding several miles out of our way, we met two men,
who directed us across the country to an inn, where we were set right,
and arrived at our friend E. Wilson`'s, at Hardwick, near dusk.
This may be received as a favour throughout;
for if we had tarried in the morning one hour, and the same circumstance, happened,
we might have been in the woods all night.

"`17th, first-day.--To meeting at Hardwick, which was larger than I expected,
and an open, encouraging time; several, after meeting, appeared glad to see me.
We went home with G. Wilson.

"`18th.--Arose before day, and after we had eaten, had a comfortable,
encouraging time with this lovely family.
We moved on and got to our friend Henry Clifton`'s, at Kingwood, about sunset.
We rode through that part of the country which David Brooks and I did thirty years ago.
I remembered the stop we made at Watson`'s, whose house stood on a hill,
and before the door a very fine spring issued:
this was the place I first ventured to go down in awful supplication in public.
The precious feelings I had at that time, are remembered by me this day,
and how marvellously I have been led about since; '`I am not worthy,`' said Jacob,
on his journey back to his father`'s house; and so said I.

"`19th.--Some more light, ease and comfort this morning.
It was in Bucks county I began in the work of the ministry, and then came to this place;
a little similar to Elisha following Elijah.
The Lord preserve my dear aged friend and brother, David Brooks, unto the end,
and protect me in and through all yet to be met with: preserve me in integrity, Amen,
The meeting was larger than I expected, and a season of much encouragement.
Dined at Henry Clifton`'s,
and after it paid an acceptable visit to his brother William and family.

"`20th.--To Benjamin Clark`'s, Stonybrook; rode about thirty miles in the rain.

"`21st.--To Stonybrook meeting, which was a close, searching time.
Dear Susanna Horne prayed for them, and on the whole it was satisfactory.
In the evening had a religious opportunity:
the Lord is to be waited on for fulfilling his own will and purpose.

"`22nd.--To Dr. Taylor`'s, accompanied by Benjamin Clark; here we met a kind reception.
It is a day of exercise,
having written home respecting an opening to engage in
a family visit in the Northern district.

"`23rd.--To meeting at East Branch, +++[+++Robbins`']; a favoured time.
Benjamin Clark stayed with us, and I thought, had a good time near the close; indeed,
the meeting throughout was to my admiration.

"`24th, first-day.--To Crosswicks meeting, and favoured with an open season,
to satisfaction.

"`Second and third-days, attended Burlington quarterly meeting,
and on fourth-day evening arrived at my own habitation, a little after night,
and found my family in health.`"

[.small-break]
'''

In the twelfth month of this year,
he visited the families of the Northern district monthly meeting, to which he belonged,
in company with his friend Susanna Horne; and after this was accomplished,
a similar visit was made to the families of Philadelphia monthly meeting,
both of which were to the peace of his own mind, and the edification of the visited.

He remarks, in relation to these visits;
"`O the deep descendings I have experienced this last winter,
both on my bed and in families, and since.
While sitting in one of them, about third month 26th, of this year, 1812,
the very same prospects respecting the renewings
of hostilities on the continent of Europe,
opened and spread over my exercised mind, as did in the last conflict with Austria,
fourth month 2nd, 1809; and I know not how to record it better,
than to transcribe what Ezekiel mentions: '`Also, son of man, appoint you two ways,
that the sword of the king of Babylon may come:
both twain shall come forth out of one land: and choose a place,
choose it at the head of the way to the city,`' etc, etc, to the end.`"

Fifth month 12th, first-day, 1812.--He thus writes;
"`The descendings of my soul into darkness and the deeps, has been humblingly great,
and my trials such, as almost to induce me to entertain a belief I am forsaken.
I have queried again and again, why it should be so,
if I am indeed not cast off and out of mind of my heavenly Father; then surely I have,
must have, fellowship with such who have lived in dens and caves of the earth;
or with the prophet, who was fed by the ravens,
and travelled in the strength of the sustenance his Lord and Master ministered to him,
until he arrived at his destined place; where, after those alarming seasons of fire,
wind, and earthquake, he stood in the entrance of the cave,
wrapped his head in his mantle, and heard your voice, O Lord, intelligibly once more,
and was further commissioned in your blessed service.
O Lord, my God, my helper hitherto, you favoured me in New England,
and also in the late exercise gone through,
in the families of my fellow members and others.
If, at any time, your servant exceeded, forgive; and wash and purify me,
and make me more clean and pure: keep me in patient resignation to your will,
and be graciously pleased to open my state and condition once more to me;
but yet in your time, not mine; and your will be done.`"

The latter part of the year 1812, and the beginning of 1813,
he was engaged in a visit to the families of Friends
belonging to the Southern district monthly meeting,
Philadelphia, in company with Susanna Horne and her companion, Mary Allinson,
and Jonathan Evans; which he remarks, was a closely exercising time.

In the fifth month, 1813, he accompanied Susanna Horne to Bristol and Trenton meetings,
and back to Burlington.
He remarks, respecting this visit;
"`I was under great discouragement respecting going this little tour,
and hardly knew how to leave home, several circumstances combining to hinder.
But after setting out I felt comfortable, and may record, that the 17th,
and second-day of the week, was a day of days.
On my way to Trenton I had not a sensation of pain, either in body or soul;
and in the ride back in the afternoon, both the heavens above and the earth beneath,
to my outward view, were beautiful, cheering and pleasant;
and may I not venture to record, that such a holy sweetness and peace spread over all,
that it was as heaven upon earth to me.
I returned home peaceful, and with a sufficient reward,
which with thankfulness is recorded.`"

On the 15th of the sixth month following, he writes: "`To meeting, but all closed up,
and has been pretty much so of late;
yet not without some little peep through the cloud at times.
It is trying to live in death, and yet I crave ability so to do;
for man can do nothing aright, without Christ his Lord.
I say in secret oftentimes, in low places,
O when will my poor travailing soul know more of an emancipation from fetters,
bonds and chains.
I long for ability to serve God with greater freedom; but why should I desire even this,
so desirable, if it is not safe for me.
I might be in danger of taking the precious jewels of peace and liberty,
and play the harlot with them.
You, O my heavenly Father, know best what is best for me.
This I crave of you, to be enabled to fulfill your will in suffering: '`Sigh, therefore,
you son of man, with the breaking of your loins;
and with bitterness sigh before their eyes.`' Ezekiel 21:6.
Why did this exercised prophet sigh?
'`For the tidings; because it comes: and every heart shall melt,
and all hands shall be feeble, and every spirit shall faint,
and all knees shall be weak as water:
behold it comes, and shall be brought to pass,`' etc.`"

In the seventh month of this year,
he went to New York to be with Susanna Horne and Elizabeth Coggeshall,
at the time of their embarking for England.
He says in relation to it:

[.small-break]
'''

"`As I sat in our adjourned monthly meeting, sixth month 29th,
after many tears of contrition, I felt an opening,
accompanied with a degree of sweetness, to go to New York.

"`Seventh month 7th.--Attended the monthly meeting of New York,
which was a remarkable time.
Susanna Horne opened the service, Elizabeth Coggeshall followed,
and I bent in supplication.

"`11th, first-day.--Orders were given to go to the ship,
which had dropped down to the watering place, seven or nine miles off.
Samuel Emlen +++[+++Jr.], John Warder, William Allinson and I, with several New York Friends,
accompanied them aboard.
Stayed about an hour and a half with them, and parted with near sympathetic affection.`"

[.small-break]
'''

The next day he set off for home, where he arrived on the 13th.

In the twelfth month, 1813, he paid his last visit to West-town boarding school,
an institution in which he had long been deeply interested,
and where his labours had been blessed.
At this time he had some precious religious opportunities with the teachers and children,
both in the school rooms and at meeting.
In one of the former, his mind was led into close feeling with one of the teachers,
under an apprehension that she was called to the work of the ministry,
which he found it his place to communicate to her,
speaking in a very impressive manner on those words of our dear Lord to Peter;
"`Feed my sheep.`"

The event proved that his impressions were correct,
the Friend appearing in prayer at the meeting on the following fifth-day,
and being afterwards acknowledged as a minister in the Society of Friends.
Shortly after his return home he addressed the following letter to her:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, First month 5th, 1814.

[.salutation]
Dear friend,

Your letter came to hand this day, and after perusing it,
I felt a portion of the same freedom you expressed, to set down and answer it;
for as in a glass face answers to face, so does the heart of man to man;
such salutations proceeding from exercised children in the heavenly Father`'s family,
brought forth by and through many baptisms, cannot fail to unite.
I have looked back at the little visit paid you at West-town with sweetness,
and the opportunity of expressing what impressed my mind in your school room;
and finding soon afterwards I was not mistaken, is one more seal, added to others,
graciously vouchsafed me.
I rejoiced over you in your appearance in the meeting and afterwards,
as much as I could have done for a new born babe; yes, more so; and as I perceive,
by your plaintive letter,
you are desirous of being preserved so as to abide in
that lot which your divine Master may apportion you,
and I have no doubt of the sincerity of your humbled soul,
it arises in my heart to encourage you to be faithful; remembering,
that it is the faithful who are to abound with blessings.
Remember, dear child, in all your movements in so weighty a work,
how it was with you that day, what carefulness to move aright.
Well then, be watchful, be vigilant;
wait in the assemblies of the Lord`'s people for
the same renewed touches of that live coal;
and after you have, through holy help, turned the fleece and tried it both wet and dry,
and feels the evidence of the requiring, then hesitate no longer,
and even if your going forth in the work may be in fear and
trembling--words thus spoken will reach the witness in others,
and by faithfulness your gift will be enlarged; and when it is so,
render all the praise to the great and bountiful giver: seek his praise,
and not the praise of men.
May the Lord preserve you in humility, reverence and fear, all the days of your life;
so wilt you have occasion to bless his holy Name.
This is written with fear and care, by no means to exalt the creature; but that,
as expressed above, you may be kept in lowliness and fear.
So craves for himself, and for you, your affectionate and sympathizing friend,

[.signed-section-signature]
Thomas Scattergood.

--

Thomas Scattergood was taken sick on the night of the 20th of the Fourth month, 1814,
with typhus fever, which soon greatly prostrated his strength.
It was during the time of the yearly meeting,
the several sittings of which he had attended until fourth-day evening;
and in conversation with his son he expressed his satisfaction in believing,
that so far it had been owned by the overshadowing of heavenly good,
which he hoped might continue to be the case to the end; adding,
"`though I cannot be with you personally, my mind will be there,
with desires that best wisdom may direct you.`"
He made inquiry respecting a subject pending in the yearly meeting,
which occasioned much exercise to his mind, and remarked,
"`I fear there is too much of a disposition in many Friends of the present day,
to have liberty,
and to trample under foot the testimonies and judgment of our worthy predecessors.`"

On sixth-day evening the yearly meeting closed;
and he inquired cheerfully how the several subjects
which had engaged its attention since he left it,
had been disposed of; and manifested his satisfaction in hearing,
especially that our testimony against distilling
or using spirituous liquors had been revived,
and claimed weighty attention.

On seventh-day, a friend sitting by his bed side,
expressed that he felt his mind covered with a calming and peaceful solemnity;
on which Thomas took him by the hand and replied,
"`so do I--my mind is centered in quiet, peaceful resignation.`"

A friend calling to see him, in whom he was much interested,
he expressed his satisfaction in seeing her; saying,
"`I have much desired your preservation every way.
I hope you wilt be preserved in the innocency and sweetness.`"
Upon her remarking, that the great Shepherd of Israel was near him,
and she believed would be to the end, he replied with much animation,
"`He is near me--I feel quiet and sweet.`"

Although his weakness had much increased, so that he was scarcely able to help himself,
yet he wished to sit up out of bed;--and though the exertion evidently fatigued him,
yet he felt the change to be reviving to him.
He took food with a good relish,
and passed the night without any apparent change for the worse, until near morning,
when one of those sinking spells came on, which are so common in this disease.

One or other of his physicians were with him
pretty constantly through first-day the 24th,
and all was done for his relief which their skill and judgment dictated;
but his constitution was unable to sustain the load of disease,
and respond favourably to the remedies used.

In the afternoon he remarked in substance;
"`This is the last piece of the garment that is to be worked up,
and if I can be favoured to join the righteous of every generation, it will be enough.`"
Shortly after he said, "`I don`'t know that I have much to say for myself;
I leave it to the Lord, the Shepherd that sleeps not by day, nor slumbers by night,
who watches over his children, and over his flock.`"
On taking some drink, he remarked;
"`A cup of cold water in the name of a disciple is pleasant;`" and presently after,
"`I hope a righteous generation will be raised up and preserved as a seed.`"
Remaining a little while in silence, he added; "`O,
if we can but be favoured to take some of this love with us.`"
"`I have been thinking of Josiah Bunting;
and hope and believe he made a good end--it is
the end crowns all--I have nothing to boast of.`"

His vital powers now appeared to be fast sinking,
and his speedy departure was looked for; but reviving a little he said,
"`I do not expect I am going now, that is, suddenly,--if so,
it is hid from me among the rest of the Lord`'s secrets.
I have been baptized into many low places and raised up again.`"

After some time of silence, and when very near his close, he said with some emphasis,
"`I will lead them`"--and again "`O, who will stand?`"
He peacefully departed about twenty minutes after seven o`'clock in the evening,
(24th of fourth month,
1814) in the 66th year of his age--having endeavoured
to serve his generation according to the will of God,
and been faithful in the occupancy of the gift bestowed upon him,
we have the consoling assurance, that he is numbered among those at the right hand,
and has received the welcome sentence, "`enter into the joy of your Lord.`"
