== Chapter I.

[.centered]
=== Preface

The memoranda from which the following account of our beloved friend,
Thomas Scattergood, is chiefly drawn,
appear to have been penned for the information of his
family and his own instruction and improvement,
without any view to their being made public.
They enter more into private and personal details than
would be proper to meet the public eye,
and often with a degree of minuteness which would be tedious to the general reader.
It was therefore necessary to omit much of this description of matter;
to correct some grammatical inaccuracies and sometimes
to transpose a sentence for the sake of perspicuity.

The reader will perceive that our dear friend was one of those who knew what it was
to be "`in deaths oft;`" to be brought very low after seasons of divine favour,
and often to partake, according to his measure,
of that bitter cup which was drunk in its fulness by his Lord and Saviour.
But these seasons of conflict and suffering,
painful as they might be at the time were blessed to him, as a means of preservation,
and of preparing him,
not only to minister more effectually to the suffering and oppressed seed of God;
but also to partake more largely of those consolations which are in Christ,
when He in whose hand are the times and seasons, saw meet to change the dispensation,
and permit him to partake with his blessed Lord
in his resurrection into dominion and glory.
Few persons, it is believed,
were preserved more steadily in a state of inward exercise and retirement of spirit,
waiting on the Lord, or given to see more clearly, or to minister more pertinently to,
the states of meetings and individuals,--and few have left behind them more
seals to the baptizing and convincing power of their gospel ministry.

[.centered]
=== The Journal of Thomas Scattergood

Thomas Scattergood, son of Joseph and Rebecca Scattergood, was born in Burlington,
New Jersey, on the 23rd of first month, 1748.
His parents were members of the religious Society of Friends,
and his father was indentured to Thomas Chalkley to learn the business of a mariner,
with whom he performed several voyages.
After coming of age,
he appears to have had the command of a vessel which sailed from Burlington;
but he soon left this occupation and studied law,
which he continued to practice until his death, which occurred in 1754.
After this event, the care of Thomas`' education devolved upon his mother,
who manifested an earnest solicitude for his best welfare,
and by tender counsel and judicious management,
endeavoured to shield him from the snares and temptations incident to youth,
and to lead him in the paths of piety.
His literary instruction would seem not to have
exceeded the common branches of an English education,
of which he acquired a competent knowledge.

Of his boyhood, little is known, though from some hints he has left respecting it,
he seems to have been favoured, as early as when six years old,
with seasons of serious thoughtfulness;
but not giving heed to the secret reproofs of instruction,
or to the admonitions of his concerned mother,
he yielded to the corrupt inclinations of the vain mind,
indulging in folly and forming associations,
the tendency of which was to alienate him from a serious and self-denying life.
His turn of mind rendered his company peculiarly acceptable to his associates,
among whom he was generally a leader in their youthful diversions;
and although it does not appear that his conduct was marked by
any flagrant departure from the path of rectitude,
yet he became much estranged from the yoke and cross of Christ.

About the fourteenth year of his age,
he was placed apprentice in the city of Philadelphia,
with a Friend in mercantile business; but the occupation not suiting him,
he remained in it but a short time.
He afterward went to learn the trade of a hatter,
and continued at it until about nineteen years old, when his master dying,
he quit the employment and learned to be a tanner,
in which business he continued during the remainder of his life.
The temptations to which he was exposed in the city,
and the facility there afforded for gratifying the inclinations of the carnal mind,
led him still further from the way of holiness;
but amid all his deviations he appears to have been watched over and cared
for by that compassionate Being who is a father to the fatherless,
and whose gracious visitations were at times powerfully extended,
in order to rescue him from the pit of pollution,
and make him a chosen vessel in his house.

He was sometimes in the practice of spending first-day afternoon with his
companions in sailing on the Delaware--an amusement in which he took much delight;
and on one occasion when employed in this manner,
his mind became so deeply impressed with the sinfulness of thus spending the day,
that he induced his comrades to set him ashore before they reached the place of
their destination,--nor did he ever afterward spend that day in a similar manner.
He was often heard to speak of this incident,
as a remarkable instance of the secret pleadings of the
divine witness in the breasts of even the young,
and there is reason to believe that soon after it,
he was made willing to bow to the tendering
visitations of divine love and mercy to his soul,
and taking up his daily cross, to follow Jesus in the regeneration.

It would be interesting and instructive to trace his progress in a religious life,
through its early stages,
and to mark the exercises and baptisms by which he was gradually prepared
for an instrument of remarkable usefulness in the church of Christ;
but he has left no record of this important period of his life,
nor are there materials to make up even an outline of it.
From some remarks which he made at different times,
there is ground to conclude that his inward conflicts and provings were many,
and that he was then no stranger to that deep and weighty exercise of spirit,
which so remarkably characterized the later periods of his life.

It appears from the records of the monthly meeting of which he was a member,
that soon after attaining to manhood,
he was brought into usefulness in the concerns of the church,
and employed in some important services for the Society.

In the tenth month, 1772, he was married to Elizabeth, the daughter of David Bacon,
who proved a helpmeet to him; but they were separated by death in about eight years,
which proved a close trial to him.
One son, Joseph Scattergood, was the only child who survived her.

During the commotions attendant on the war of the revolution,
the Society of Friends in Philadelphia were subjected to much suffering and many trials,
owing to their conscientious objection to everything of a warlike nature,
which exposed them to much jealousy and suspicion,
and often rendered them the subjects of unrighteous and oppressive exactions.
These difficulties, growing out of various causes,
brought Friends very near to each other in spirit, broke down the barriers of prejudice,
and produced that humility and tenderness of spirit,
in which they could feelingly sympathize with one another,
and were ready cheerfully to contribute of their substance for
the help of those more destitute and stripped than themselves.
Committees were appointed in the monthly meetings to
inquire into the situation of their members,
and afford the requisite relief wherever it was needed.
In this work of love and mercy, Thomas Scattergood was a diligent labourer,
and he was no less zealous in encouraging his fellow professors to maintain
faithfully their testimony to the peaceable reign of the Messiah,
and in endeavouring to convince others of the inconsistency of
all wars and fightings with the benign nature of the gospel,
which ever breathes peace on earth and good will to men.

In the tenth month, 1778, with the consent of his monthly meeting,
he accompanied a ministering Friend to some meetings in Maryland and Virginia;
in which service he was engaged about six weeks.

With the approbation of his friends, and to use his own words,
"`in a degree of tenderness of heart,`" he set out with Samuel Emlen
and George Dillwyn to attend the quarterly meeting of Fairfax,
in Virginia, in the twelfth month, 1779.
The account of this journey is the first which he appears to have kept,
but as it is little more than a notice of the different stages where they stopped,
it seems unnecessary to transcribe it here.
Throughout the visit he seems to have been under
close exercise respecting his own condition,
which induced him often to seek solitary places
where he might commune with his own heart,
and pour out his prayers and tears before the Lord.
In a memorandum made the 18th of twelfth month, he says,
"`Attended the committee on Reformation,^
footnote:[The sufferings of Friends during the Revolution,
not only tended to increase their love for each other,
but also led into close self-examination,
in order to ascertain wherein they had departed from the law and the testimony;
and in their conduct, pursuits, or manner of living,
had lowered the standard of purity which the gospel and our high profession enjoin.
In order more effectually to carry on this good work,
committees were appointed in many of the quarterly
meetings to promote a reformation among Friends,
and endeavour to encourage one another to greater faithfulness
in the support of the precious testimonies of Truth.
It is probably to a committee of this description, that Thomas Scattergood here alludes.]
in the afternoon.
Here I was bowed under a sense of my past disobedience
and want of entire resignation to the divine will.`"

"`21st.--Attended the youths`' meeting.
My beloved friends were favoured in this and the preceding meeting; but as for me,
I was reduced very low; yet am a little comforted under the tendering power of truth;
our esteemed friend W. M.,
speaking a little to my condition in a sitting we had at Abel Janney`'s.

"`First month 9th, 1780.--Being first-day,
attended Fairfax meeting under much distress of mind, and so continued until evening,
when a little ease was graciously granted me, for which I am thankful.
On taking the Bible and reading our dear Lord`'s sermon on the mount,
a serious thought took hold of my mind,
respecting doing to others as I would be done unto.
The remembrance of several men, to whom I paid money in days back, came before me,
with desires that I might fulfill the law of Christ,
in doing unto all men as I should desire them to do to me.`"

This uneasiness appears to have arisen from his having used
the "`Continental money`" in the payment of some of his debts;
and although it was a full settlement and discharge according to law,
yet he was fearful that he should not be acting in
accordance with the gospel rule of strict justice,
unless he made them some compensation for the loss they
probably sustained by its great depreciation.
He therefore records his desire that "`for the sake of peace of mind,`" a
certain sum might be paid to individuals whom he names,
in order to make up the deficiency.

Where unreserved obedience is yielded to the
manifestations of the light of Christ Jesus in the soul,
it brings under a deep and humbling sense of past transgressions;
begets a godly sorrow for sin, bringing into view those long since committed,
and perhaps forgotten; under the pressure of which,
the awakened mind is bowed in great humiliation and
made willing not only to confess its wrong doing,
but as far as may be in its power, to make restitution also.
An instance of the tenderness of conscience and nice sense of
justice which is thus produced in the disciple of Christ,
is related of Thomas Scattergood.
When a school boy at Burlington,
he had occasionally taken some apples from an orchard which
lay on the side of the road leading to the school-house;
and when in after life he came to see the exceeding sinfulness of sin,
this circumstance became a burden to his tender conscience.
He therefore requested a friend to endeavour to ascertain who
was the owner of the orchard at the time he took the apples,
remarking that he should feel most easy to remunerate
him for the fruit he had taken without permission.

On the 25th of first month, 1780, he returned from the visit to Fairfax quarter,
and soon after was appointed an overseer of the
monthly meeting of Friends of Philadelphia,
for the Northern district.
In the tenth month, his affectionate and beloved wife was removed by death,
a loss which he deeply felt, she being a woman of a tender and sympathizing spirit,
well qualified to feel with him under his various exercises and trials.
In the following year he joined David Brooks and Seth Coffin, of North Carolina,
in a religious visit to some parts of Pennsylvania, New York and New England,
and while engaged in this service, he first appeared in the ministry.

The following extract of a letter written to Henry Drinker,
a beloved and honoured Friend and elder of Philadelphia, conveys in his own language,
his exercises on the occasion.
It is dated at Moses Brown`'s, Providence, R. I., fourth month 2nd, 1781.
After giving some account of the meetings they had been at, he says:

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Scattergood to Henry Drinker

And now, dear friend, seeing thou hast used brotherly freedom with me,
I feel something of the same, to inform thee of my state of mind.
I have been long in a wilderness travel,
or rather partly in Egypt and partly in the wilderness, if I may so term it;
and a persuasion for years past has possessed my mind,
that a dispensation of the gospel would be committed to my charge, but how, when,
or where, was hidden from me.
Sometimes I expected the time was nearly come,
having had my mind impressed with words in meeting, but not with sufficient clearness;
and at other times,
through unfaithfulness and not being enough willing to abide the fire,
I have almost lost sight of it.
In some of these seasons I believe I could have borne a
separation from having any thing to do in Society affairs,
being so sensible of my wretched and unworthy condition;
and when I had thought of accompanying these Friends a little on their journey,
my mind was turned toward the baptized condition I was in,
when with Samuel Emlen in Virginia, which was a time of great distress,
and I was fearful of being burdensome if I went with them.
In this state of mind I left you and got pretty
cheerful by the time we reached North Wales,
in which meeting a few words came up in my mind by way of encouragement to some there,
which I have since thought I might have dropped peacefully to myself.
In the meeting for business I said something in some zeal;
which I fear wanted to be tempered with more charity.

I had thought of endeavouring to see Friends at Hardwich, some time before I left home,
and it being a favourable time,
I proceeded to our friend Robert Kirkbride`'s. In the evening my beloved
friend David Brooks was uncommonly free in conversation with me,
in an encouraging way; opening his experience to me,
though I did not inform him of my exercise; and next day on our way to Plumstead meeting,
our ancient Friend, J. Forman rode up alongside of me,
and told me whatever my hands found to do,
to do it with all my might and not to fear the presence of any who were there.
My mind was exercised again in this meeting, with a few words to deliver:
I was burdened with a profession that wanted the possession of godliness,
and the different states of the publican and pharisee opening in my view to deliver;
I sat some time, fearing I was under a delusion,
I endeavoured to settle down into stillness, and as I was favoured to get there,
I apprehended I heard this language, '`Be faithful; there shall be peace in it.`'
So I gave up, and stammered out what had impressed my mind;
but when I got down on my seat, confusion surrounded me; but by settling down to my gift,
the peace that was promised I experienced;
and being afterwards told by my dear companions that it was well, I rested easy.
Thus I first opened my mouth at a place, where some years ago,
I behaved in such a manner as was a reproach; it being at the marriage of a near friend.

We attended Kingwood meeting, at which place I was silent.
Next day set off for Hardwich,
proposing to stop to see a few scattered Friends
that live about half way between the two places.
We had a lonesome ride this morning,
wherein little conversation passed and my mind was exercised to know my way,
whether to return home to my family after being at Hardwich,
join as a companion to our friend J. Forman,
if he inclined to visit any more meetings in the Jerseys,
or proceed on with David and Seth to Nantucket;
and as I was measurably favoured with resignation of mind,
I believed it was best for me to join the two last mentioned Friends in their visit.
We stopped at Aaron Watson`'s,
and I had not sat long in the house before David came and sat down by me;
and on telling him I had thought of keeping on with him to Nantucket,
he freely told me he could think of little else in our lonesome ride, but my going,
and believed truth would make way for itself.
My mind was bowed in awfulness,
and as I apprehended I felt something of the spirit of prayer and supplication,
I endeavoured to keep under it until we sat down to eat,
at which time I ventured to prostrate myself before Him who had been
graciously pleased to open a spring of consolation in a desert land;
and dear David told me afterwards, it had a tendency to open the same spring in him,
as he began after I concluded;
and we had a solemn time together in this wilderness place,
where we were altogether strangers except our guide.
This season of divine favour, dear Henry, has been a time for me to look back at since,
when I have been ready to question all.
Thus I have simply laid my state before thee,
as one who is authorized by his station to care for me; and being absent,
I apprehend I can do it more freely than if I were present.

--

In the course of the journey, which occupied several months,
he passed through much exercise of spirit and was often brought very low,
yet it proved a satisfactory and instructive season;
and in alluding to it several years after, he says: "`It was the Lord`'s doing I believe,
to send me with this experienced brother, +++[+++David Brooks,]
and marvellous was his supporting hand throughout the
journey;--I hope never to be forgotten by me,
for he brought my wading soul out of great tribulation,
and to the praise of his holy name be it uttered,
he opened the way for me not only in the minds of elders and brethren at home,
but also abroad.`"

After returning home, he continued to appear at times in the ministry,
which was satisfactory to his friends,
who felt unity and sympathy with him in this weighty work.
The following memorandums show that he endured
many fiery baptisms and close conflicts of mind,
which tended to deepen him in the root of divine life,
and prepare him for more extensive usefulness in
the solemn service whereunto he was called.
Being brought into a state of humble dependence upon
the openings and leadings of the Holy Spirit,
and reverent waiting upon Christ Jesus, the Minister of ministers,
he was made of quick understanding in the fear of the Lord,
and careful to wait for the fresh extending of
heavenly help before he engaged in testimony;
and thus keeping, in simplicity and singleness of heart, to the gift bestowed upon him,
he was often enabled, as a good steward of the manifold grace of God,
to bring forth out of the treasury things new and old,
to the edification and comfort of his hearers.
He was acknowledged by his monthly meeting as a minister, in the first month, 1783.

Under date of twelfth month 17th, 1782, he writes:
"`I feel like a poor creature--after a time of favour,
stripping and trial come--so I have experienced.
It has of late been a time comparable to a sabbath day.

"`19th.--O how near is my lurking enemy to draw into a love to the creature.
I was favoured today with a few expressions to
drop for the encouragement of such as myself,
who are much in debt and have naught to pay with.

"`21st.--On looking back at this past week, I find the hand of mercy has been near,
but truly I have nothing to boast of.
It is admirable to me,
that such an one as I should be so bold as to venture to instruct others,
while I get along so heavily myself.
Lord animate me to press forward.

"`30th.--A day of sorrow;
yet this evening I feel a broken heart and am baptized into tears.
For such an one as I, this is a great favour, worthy of recording.
O Lord, my God, thou hast not forsaken me, though I have strayed far from thee.
Renew thy promises as in former years.
I am unworthy to ask thy blessing, yet I desire to wait for it.

"`First month 5th, 1783.--Some brokenness and contrition experienced today,
and a desire raised to be more circumspect this week, if life is spared.

"`10th.--O what pain a small deviation from the strict law causes to a quickened,
feeling mind.
Lord help me to know and keep thy law more and more.

"`11th.--How apt is one deviation, though it may seem as only from a tittle of the law,
to beget another.
When an old beloved lust, in some degree mortified, puts up its head,
what is then to be done but to know it bruised.
O when shall I know my beloved lusts so put down, as not to be able to rise.
Lord enable me to bear the rod and suffer it to do its office,
that peace may again spring up through it.

"`12th.--A day of fasting and prayer, and I hope of true mortification.
I desire to see the death of some potent enemies, though it may be perfected by famine.

"`17th.--What wouldst thou have me to do Lord?
When wilt thou be graciously pleased to favour with the
lifting up of the light of thy heavenly countenance,
and destroy my enemies?
Be pleased to preserve me through the close exercises of my soul;
manifest thy will clearly to thy servant, and uphold me in it; enable me to bear,
and spare not.
O Lord, that I may experience thy goodness as in the land of the living.

"`21st.--A little opened today at meeting, where I had something to deliver;
and also in a transient visit to a family.
I ventured to prostrate myself before God, and beg for protection and preservation.
How thankfully doth the panting soul receive a little ease, refreshment and encouragement.

"`22nd.--A secret trust and hope lives in my heart:
how was David`'s life hunted in the wilderness, on the mountain, and amongst the rocks;
yet he was delivered.
O my soul, hope thou and trust in the same merciful deliverer.

"`23rd.--Favoured to encourage the mournful travellers.--Admirable that such an one as I,
should be thus led in public.

"`26th.--A day of more ease under the yoke,
and I feel desires kept alive and hope quickened, to press on,
endeavouring to eye my Captain and preserver.

"`27th.--It is pleasant to have a way cast up, and to be found walking therein.
Today I have, in some degree witnessed that saying fulfilled,
'`the effect of righteousness is peace.`'

"`Second month 5th and 6th.--Not much to note,
only some ease of spirit to what I have of late experienced.
O that I may be kept attentive to Wisdom`'s voice, prepared at all times to say here am I.

"`10th.--Introduced to the meeting of ministers and elders.
Felt poor; little more about me than a desire to be what the Lord would have me to be;
however, am thankful that I was there.
O that I may be enabled more and more clearly to know and understand Wisdom`'s voice,
and to follow it even again and again into suffering.

"`11th.--What need of mercy and remission I feel this morning.
I hope that in due time my soul`'s desire will be answered, as Jabez`'s was.
O that thou wouldst bless me indeed, and enlarge my coast and keep me from evil,
that it may not grieve me.

"`13th.--Attended meeting, and near the close had something to say.
How am I tried with presentations of false visions, and at times narrow is my escape.
O that my gracious Master may preserve me from putting forth a hand to steal,
in the poverty that is necessary for me.

"`14th.--Felt my enemy gaining upon me, by lulling into ease.
Thanks be to the Lord, I feel more animated, and hope to resist him.
This is an old and sore evil;--slothful in business,
and not enough fervent in spirit serving God.
O for more animation in time to come, and forgiveness of past defects.

"`Second month 28th.--Spent this day alone in some quietness in my own habitation,
and find occasion of humbling.
O Lord, continue to enlighten and settle me; thou knowest my buffetings and trials.

"`Third month 5th.--Spent some time with Sarah Harrison with unusual openness,
in comparing our getting along in a religious sense.

"`10th.--I am, indeed, a buffeted and sifted servant.
O Lord, forgive me the sins of my youth.
I have often and again slidden into folly,
and what have I to lean upon but thy arm of mercy.
Be graciously pleased to open a way where there appears none;
preserve me from dishonouring thee!
Continue to send a little help, and enlighten my darkness.
O my feebleness!
I hardly durst say I will trust in God, though I desire to do so.

"`11th.--Awoke this morning with a calm and easy mind,
when this encouraging language revived; '`I am the Lord that healeth thee,
and teacheth thee to profit, and leadeth thee in the way thou shouldst go.`'

"`16th.--A quiet silent day;
wherein an animating desire was felt to be more vigilant and more industrious.
Soul, watch thou that thy resolution may be kept this ensuing week, if life is spared.

"`20th.--Thankful for favours received--found bodily exercise in labour profitable.
He that will be Jesus`' disciple must deny himself, take up his cross and follow him.
What a favour to be instructed what this means, sell that thou hast;
what a lesson to learn.
I hope for more victory through faith, though I seem to make but a slow progress.

"`24th.--Felt my lurking subtle enemy very near, endeavouring to trip up my heels.
Oh! the mercy and kindness of my blessed helper, in assisting me to resist him,
so that I do not get so defiled and overpowered with weakness,
as has been my condition in days past.
May I still be enabled to maintain the warfare,
through him who has indeed showed me kindness--thanks be rendered to his name.

"`Fourth month 9th.--O wretched man that I am,
who shall deliver me from this body of death and sorrow of heart?
Is there not virtue in him who is called the Prince of Peace,
to dispense peace to such a poor cast down one?
O yes, there is, but I cannot command it.
Lord preserve me from taking flight in this winter season.
Preserve me in the faith, and be pleased to increase it;
make me worthy to receive redemption and mercy by thy washing, preparing hand:
be pleased to blot out of thy remembrance the sins of my youth;
my frequent backslidings and my neglect of thy law.
O Lord, I am miserable without thee! look down upon me.
I dare not seek pleasure away from thee,--I believe
thou canst change my misery into comfort in a moment,
if thou please.
I hope in thy tender mercy, and though I am thus cast down,
I will endeavour to trust in thee.

"`13th.--I feel an humble hope if the thread of my life is cut,
there is mercy reserved for me.
O may I be kept until the end without despairing.

"`14th.--Through mercy I feel my way more clearly cast up.
I have not walked enough with full dedication of heart,--and have
been too uneasy under the fiery law that must be submitted to,
for removing all my corruptions.
O Lord that thou wouldst animate, enlighten and keep me under it,
until its office is finished.

"`16th.--Hope I have felt something of the same healing virtue that went forth to him,
whose withered hand was healed upon stretching it out at the divine command.
Under the cross springs the crown of peace; but nothing is due to the creature:
neither is it of him that willeth,
nor of him who runneth,--although there is much required for the poor creature to do.

"`20th.--Concerned three times in public testimony:
at the lower meeting in the morning in a few words in testimony; after which,
dear Nicholas Wain, I thought, had a good time,
and was favoured to lift me up a little therein.
I was engaged afterward in supplication, to my comfort.
Attended Market street meeting in the afternoon,
where I was exercised in a close testimony to a libertine spirit:
believe the favoured meeting in the morning was some support to me in this.
Nicholas Wain had a precious time in the evening meeting,
after which I was concerned to endeavour to clinch the nail.
Nothing due to man.

"`21st.--With a reverent thankful mind, I may say, it is a holy day,
created anew by Him that hath the times and seasons in his own power,
and wherein I am eased from that weight of oppression and sorrow which I have been under.
The Lord only be praised, and my poor soul be made willing to return to labour again,
when this graciously afforded sabbath is past.

"`Fifth month 1st.--O Thou that art all wisdom, strength and power, enable me so to walk,
as to experience an advancement to thy praise.
What a favour to have the eye of the soul anointed to behold
the dear Son of God as our advocate in affliction.

"`12th.--I think my poor soul has been this day, as with Joseph in the prison house.
In the Lord`'s season he was delivered, and set above his enemies.
Trust in the Lord thy God, O my soul;
though he may see meet to hide his comforts from thee,--hope in his rich mercy still.`"

On the 15th of fifth month, 1783, he was married to Sarah Hoskins,
daughter of John Hoskins, of Burlington, New Jersey,
respecting which event he writes:--"`A day of covenant
in the Lord`'s fear with my dear and virtuous friend.
I was a little strengthened by the fresh revival of these expressions in my
mind;--'`Be content with such things as you have:`' and it was satisfactory to
hear dear George Dillwyn make use of the same for our encouragement.
G+++.+++ B. opened the public service with these expressions; '`Peace is sown for the righteous,
and joy and gladness for the upright in heart;`' and afterward George
Dillwyn told us the same expressions soon struck his mind,
and out of the mouth of two or three witnesses every word was to be established.

"`20th.--Went to preparative meeting in an humble waiting frame,
and therein my Master was graciously pleased to hear my petition,
and cast up a way to walk in.
May I ever be preserved from stepping out of it.

"`Sixth month 1st.--A day of some enlargement;
spoke in testimony at our own meeting in the morning,
and also a few words in the early part of the evening meeting,
which seemed as a text for dear Nicholas Wain to enlarge much upon; who it is probable,
may not soon have the like opportunity amongst us in that meeting.^
footnote:[He was soon to embark for England,
on a religious visit to the churches in Great Britain and Ireland.]
It was encouraging, thus as it were,
to have a mantle thrown over me by an experienced elder brother.

"`3rd.--A parting meeting with Nicholas Wain--a low time with me in the forepart,
but dropped a few tears under that dear friend`'s
instructive testimony in the latter part of it;
and afterward took my leave of him.

"`10th.--Several changes today, yet trust I have not given place to the subtle serpent,
with whom my poor tried soul has such a controversy.
O that the protecting arm may still be near.

"`19th.--A dull heavy meeting today: it is a day of outward ease again;
and there is a great stir in this populous city in trading and business;
but where are the poor baptized mournful travellers to
be found?--I believe there is a remnant preserved.

"`22nd.--Apprehended it my duty to go to the middle meeting.
It was exercising to me to pass by my own, and be engaged in such mortifying labour;
but hope I complied with a good degree of cheerfulness.
O that I might be enabled to feel more content in my allotment,
seeing I dare not climb up another way.
I could rather desire my natural life might go for a sacrifice,
than live to dishonour my God, after appearing in so high a station.
Lord! preserve me--my desire is toward thee; enable me to love and cleave to thee,
that in due time I may come to experience thy blessing,

"`Seventh month 2nd.--O my soul, endeavour to persevere in patience under thy burden.
If the Lord delight in thee, he can bring thee unto what thou pants after.
If faith and patience be graciously afforded, then let the fire burn.`"

In the year 1784, with the concurrence of his monthly meeting,
he paid a visit to the meetings composing the yearly meeting of New England.
He attended the yearly meeting at Newport, Rhode Island, on his way;
and learning that David Sands had obtained a
certificate to visit the meetings in New England,
he seemed to be impressed with a belief that it
would be right for them to travel together.
Under date of sixth month 3rd, he writes to his wife:

"`O may my dear Master, who has seen meet to suffer near trials to beset me in days past,
and has measurably preserved me as I clave to him, still be with me and provide for me,
if it is his will that I should be longer from thee.
I desire, in resignation and submission, to recommend thee, with my own soul,
to his gracious care and protection.`"

After the yearly meeting closed,
it was some time before he could see which way it would be right for him to move;
as the following extract of a letter, dated sixth month 16th, indicates.

"`I humbly trust my being here has been in the will of the Lord;
having been measurably favoured with enlargement, both in meetings and in some families,
to my own comfort and the satisfaction of my friends; although I came poor amongst them,
and now the meeting is over, have to return to the same safe spot again,
I told Friends of the select meeting, near the conclusion,
that they might find by the care in wording my certificate,
how thoughtful my friends at home were about my right moving amongst them.
That I felt like one who had left his father`'s house,
and Friends of this meeting seemed like my friends at home,
on whom I desired to cast myself; not seeing it safe to return home,
and further service amongst them did not clearly open.
I find that thus simply casting my burden amongst them,
has gained me some near sympathizers.`"

After holding a conference with several Friends,
the prospect of joining David Sands in visiting the
meetings in the eastern part of the yearly meeting,
seemed to open with the most clearness;
and David Sands having intimated to him that his company would be truly acceptable,
they set off together.

In a letter to his wife dated at Boston, seventh month 20th, 1784,
he thus speaks of their progress.

[.embedded-content-document.letter]
--

We have been kindly received by our friends in this place,
whose families we have visited, and got through yesterday,
and in the evening went to see a family about six miles out of town,
where a few days past we had a meeting,
amongst a people that I do not learn ever had the like appointed amongst them before.

I have been pretty much exercised in my mind in this town.
But thanks be to my kind Master, I have had renewedly to rejoice this day,
in that he hath enabled me to labour in my little services in this place,
to a degree of comfort and satisfaction,
so that my mind is measurably set at liberty and my health renewed.
We propose leaving this place in the morning to go on east, having had divers meetings,
wherein considerable numbers of the gay inhabitants
have given their company and conducted very commendably;
and indeed I may say, we have been treated very respectfully by them.
The services of my dear brother, David Sands, have been extensive,
and I believe well accepted.
I trust we increase in uniting love, and I have humblingly to hope at seasons,
I shall be enabled to get through my services in these parts, and return in peace.

My heart is at seasons in company with thee, in such a manner as to revive my hope,
that divine Goodness is not wanting to support thee; and thou hast my prayers for thee,
though my bodily presence is wanting.
Lift up thy head in hope, and still stretch heavenward in the desire of thy mind,
believing that it is easy with the Lord to turn our wilderness into a fruitful field,
after he hath sufficiently tried us.
I have cause to speak well of his excellent name,
who is my sufficiency in all my exercises;
and no doubt it will be a comfort to thee to know that I have been so far helped,
as not knowingly to omit any little service I have apprehended myself called to perform.
We have met with divers friendly people here,
with whom we have had some baptizing seasons;
and I find as much engagement as ever to see the
people in the back parts of New England.

--

On the 21st, they set off in accordance with their prospect,
to visit the eastern settlements of Maine; in the performance of which service,
it being an unsettled and wilderness country, they found considerable difficulty;
having to swim their horses over rivers,
and to lodge in cabins and other poorly sheltered places;
notwithstanding which they were favoured with health and strength,
and reached Vassalborough on the 18th of the eighth month,
where the following memorandum was made.

"`Almost, or may be quite, at the far end of our journey in a wilderness land,
where my mind is pleasantly turned home this first-day morning,
to take a view of my dear family, feeling my heart a little comforted and strengthened,
after many trying seasons.
O may our dear Master be our comfort and strength; and if it be his will,
bring us together again and more and more unite us in best love.`"

In a letter dated at Boston, ninth month 6th, 1784, he thus describes this visit:
after speaking of a meeting held at Falmouth,
in which he had an open encouraging opportunity, he says:

[.embedded-content-document.letter]
--

It was like a time of healing,
after many proving seasons since I left this place before.
The close exercise I was under,
I expect thou might easily discover from the contents of my letter,
written from here before going eastward;
wherein I mentioned that I believed it was required of me to stand
resigned to labour in these parts until the quarterly meeting.
I gave up with a good degree of cheerfulness to accompany my dear companion, David Sands,
and have been pretty nearly through that wilderness country.
I have passed through close trials of faith and love, in this journey;
and have also found my gracious Master to be near in them, who hath from time to time,
as I was willing to be emptied, caused the heavenly oil to fill the empty vessel,
both to discharge the debt, and afford some to live on myself.
Blessed be his name for his mercy and care over me,
one of the least and most unworthy of his servants.
A monthly meeting coming on, I found my mind drawn to attend it,
as also the preparative meeting, held about twenty-five miles nearer.
We left Vassalborough, accompanied by divers Friends who intended for those meetings,
and rode to a new settlement called Winthrop,
where we were taken in and kindly entertained by a friendly man;
had a sitting with him and family next morning,
when my mind was strongly engaged to be at their meeting of business;
and David found a full stop in his mind, and told us,
that with the friendly man`'s consent, he must stay and have a meeting at his house,
but was very free for me to go forward.
I did not see, when I parted with him,
but that I should return and join him again after monthly meeting;
though I understood by one of the Friends who came with me,
that he said he did not expect to meet me again.
We parted in that near love and affection in which we were favoured to travel together;
one of the Friends staying to accompany him, and two others came on with me.

--

He thus describes his subsequent engagement:

[.embedded-content-document.letter]
--

A dear friend who came from Kennebec with me, had it on his mind to bear me company,
and I believe was at that time dipped into my exercise, and has given up,
with Friends`' approbation, to accompany me, though not without some cost,
and proves a valuable feeling yokemate.
I have ventured in my journeying this way,
to appoint meetings where David and I have not been;
and hope I was favoured to get through to a good degree of satisfaction,
both to Friends and myself; it was a new scene, and I have not been without trials in it.
I reached this town last seventh-day afternoon,
and was with much affection received by my kind friends, John and Rebecca Dean,
who seem desirous I should stay until their monthly meeting at Lynn comes on,
and rest myself.
I found a considerable draught to this town,
and sat with Friends yesterday in two meetings.
There seems to be considerable openness and love amongst them, and also other societies,
that is very encouraging and comforting.

--

The remaining memorandums of this visit are principally an
account of the different families with whom they put up.
On the 28th of the tenth month, 1784, he arrived at his own residence, as he says,
"`in peace.`"
