== Chapter V.

Under date of tenth month 6th, 1793, the following memorandum occurs,
which appears to be the first made after his return from the above visit;
giving a brief summary of his religious labours for some years previous,
and commemorating the mercy and goodness of his Lord and Saviour.

"`Ten years have passed over since I was laid on a bed of sickness,
and brought near to the gates of death.
It was indeed a very humbling, proving dispensation; inwardly,
because of great poverty and stripping,--and outwardly,
because of sore and long continued weakness.
But the Lord raised me up, and sent me into the back parts of New England,
and brought me home in peace.
Since that time I have been strengthened to perform a pretty general visit,
as before mentioned, to Friends in the government of New York,
with my beloved friend James Mott; and again,
into some of those parts with my beloved friend John Cox, of Burlington;
and on our return attended Rahway quarterly meeting, where I was singularly exercised,
and a sorrowful circumstance afterward occurred;
and also visited most of the little towns in that neighbourhood.
Shortly after, I visited New Jersey, in company with my friends John Cox, Nathan Smith,
and James Whitall; also Bucks County, with Nathan Smith.
Last year I went through the southern governments as far as Georgia,
accompanied by my dear friend Josiah Bunting,
who was a true yoke mate--returning from this
last long journey of nearly thirteen months,
in the sixth month last.
In all these I may humbly and with reverence acknowledge,
that the Lord was my helper and preserver through many and very singular trials,
and always brought me home in peace:
and now there is a fresh scene of trial open in this city,
such as neither we nor our fathers ever saw.
The awful messenger of death is travelling through the streets, as from house to house,
and removing from works to rewards, many not only of the inhabitants at large,
but also of the members of our religious Society, some of whom I nearly loved,
and who promised to fill up with propriety,
their stations in the church militant on earth.
Not a few of our brethren have left the city, so that we are reducing daily,
by deaths and removals into the country.
A sense of all these things has closely exercised my mind from day to day,
for some time past,
and I have seen nothing better than quietly to remain in my habitation,
where I have had frequent occasion to believe divine Providence has placed me;
and daily to feel after a qualification, through holy help, to say,
Lord preserve me on the living and sure foundation,
that my faith in thy all-sufficiency may not fail.
Thou hast been my protection and help through many trials, inward and outward,
in days past; and now, dearest Father, look down in tender mercy on me and my family,
and enable me, with the wife of my bosom,
to resign our own and one another`'s lives to thee,
and if thou art pleased to call for mother, son, or daughter,
O sanctify and prepare our hearts for such a dispensation;
or if in thy unsearchable wisdom and mercy,
thou art pleased to continue any or all of us a little longer on earth,
may devotion and dedication of heart be mine and theirs; and so thy will be done.`"

[.offset]
Thomas Scattergood remained in the city during the yellow fever of 1793,
and although some allusion is made to the disease in his memorandums,
yet it has been thought a more particular account would be acceptable,
and the following brief narrative has therefore been prepared:

[.embedded-content-document.paper]
--

So many years have elapsed since the general prevalence
of the yellow fever in our highly favoured city,
that but few of the present generation can have an adequate idea of the
alarm and distress produced by this awful dispensation of divine Providence.

This malignant disorder, which, in the space of about three months,
swept away nearly four thousand persons,
made its appearance in the latter end of the seventh month, in Water street,
between Mulberry and Sassafras streets.
It was some time before it attracted much attention,
but it gradually extended to Front street and other parts adjacent--
its greatest ravages being nearest the river Delaware;
and by the middle of the eighth month,
considerable alarm began to appear among the citizens,
many of whom fled to the country and other places,
where they supposed they would be secure from its attack.
The number of deaths continued to increase--during the eighth month,
the daily average was about eleven,--in the ninth month it was nearly fifty;
the greatest number being ninety-six, and on two other days eighty-one and ninety-two;
and in the tenth month it was nearly sixty;
the highest number being one hundred and nineteen,
and on the days preceding and subsequent,
one hundred and eleven and one hundred and four persons respectively, died.
When we consider the comparative smallness of the population in the city at that time,
it is not surprising that the steady progress of the disease and its
great mortality should have spread terror among the inhabitants.
The shops were shut up, the streets very much deserted,
so that few persons or vehicles were to be seen in them,
save the wheels on which were conveyed the dead to the grave,
and the persons who attended them.
All pomp and show at funerals were dispensed with,
and the remains of the most worthy and respectable citizens
were committed to the earth in the most simple manner,
and in the presence of few if any more than necessity required.
Pride and ostentation were laid in the dust,--the high and the low,
the rich and the poor, were reduced to a common level;
and the anxious inquiring thought of most minds seemed to be, "`Who will go next?
Will it be me?`"

The disorder being considered contagious, the fear of contracting it, in many instances,
overcame the feelings of natural affection;
and persons who had been accustomed to all the comforts and attentions which
wealth and the tenderest connections in life could bestow,
on being seized with the malady were wholly deserted and left to die alone;
or abandoned to the care of mercenary nurses,
whose chief object was their own ease and emolument,
and who often neglected the unhappy invalids entrusted to their care.
Some died entirely alone, and the houses where they were, being deserted,
the first intimation that a dead body was there,
was the noisome effluvia it emitted while undergoing decomposition.

A person employed in carrying the sick and dead, passing along the street,
heard the cry of some one in great distress, and the neighbours informed him,
that the family had been ill for some days,
but that the fear of the disease had prevented them from venturing to examine the house.
The man cheerfully undertook the benevolent task, and on going upstairs,
he found the father of the family dead, who had been lying on the floor some days;
two children near him also dead; the mother, who was very ill,
gave birth to another child, which, with herself also died while he remained;
thus making five persons dead in one house at the same time.
This event, among many others of somewhat similar character,
will give a better idea of the awful and heartrending scenes exhibited,
during the prevalence of this humbling and distressing calamity,
than any description that can be written.
It is calculated deeply and seriously to impress the
mind with the weakness and helplessness of man,
when the judgments of the Almighty are poured out;
and also with a sense of his great mercy in sparing us
of the present day from such suffering,
not because we are more righteous, but because He is long-suffering and slow to anger.

The general consternation became so great,
that those whose particular province it was to have the oversight of the poor,
all fled except three;
and the distress and suffering among this destitute class of citizens became so urgent,
that a public meeting was called to devise measures for their relief and assistance.
At this meeting ten persons voluntarily offered
their services to aid the overseers of the poor;
and at a subsequent meeting others were appointed, making the whole number twenty-seven;
but owing to sickness, death and other causes, the work chiefly devolved on twelve, who,
with some others that afterwards offered their services, laboured daily,
with untiring zeal, in this work of benevolence,
and were the instruments of affording essential
benefits to their suffering fellow creatures.
Of the whole number thus employed, but one now survives,
our aged and beloved friend Thomas Wistar; his last companion, John Letchworth,
having deceased about a year ago.
Daniel Offley, an eminent and beloved minister in our Society,
impressed with a sense of religious duty,
and commiserating the accumulating distresses of his fellow citizens,
offered his services to the committee on the 30th of the ninth month,
and from that time continued to exert himself indefatigably in
this work of humanity until he was seized with the distemper,
which, in a few days brought him to the grave, deeply lamented by all who knew him.
A few days before his death, being in company with Thomas Wistar and another Friend,
when they were about to part, he solemnly observed to his companions,
"`The language of this dispensation to each of us is, '`Be ye also ready,
for at such an hour as we expect not,
the messenger of death may be sent to our houses.`'`"
They separated never to meet again in mutability,
both the others dying in a few days.
Daniel Offley was taken ill on the 3rd of the tenth month,
and throughout his sickness evinced a cheerful serenity of mind,
being entirely resigned to the will of God, in whom his confidence appeared unshaken;
and on the 11th of the same month, in the thirty-seventh year of his age,
he quietly departed, to inherit a crown of glory that shall never fade away.

Charles Williams, another valued minister,
who was companion to Thomas Scattergood in his journey to Hopewell and Redstone,
in the year 1787, also died with the yellow fever on the 9th of the tenth month 1793,
aged twenty-nine years, and about the ninth of his appearance in the ministry.
Being of a tender and sympathizing disposition,
and his heart softened and animated by divine love,
he was a kind friend to the poor and those under affliction, whom he often visited;
and in the time of the great mortality,
he was much devoted to the relief and assistance of the sick,
to whom he was indeed a messenger of consolation.
The following memorandum made by him, is worthy of note:

"`Ninth month 1st, 1793.
It is affecting to observe the change which has taken place in this industrious city,
where business appeared to be the life of many,
and each one strove to exceed his neighbour in care to gather wealth.
Now a stop is put to this,--little business is transacted,
and the minds of many are awakened to consider what is
the state of their last and solemn account.
A serious solemnity appears on almost every countenance; and I hope,
by myself and others, this visitation may never be forgotten.`"

During his illness he was favoured with a blessed confidence in divine mercy,
which took away all fear of death, and his spirit departed to a better inheritance,
in peace with God and man.

A number of other valuable Friends, including several ministers and elders,
were removed by the disease, but even when it was at the worst.
Friends kept up their meetings for divine worship; and though they were often small,
yet they were crowned with a solemnity,
in some degree corresponding to the greatness of the sacrifice in going to them,
and were often seasons of humbling contrition.

A number of Friends whose minds were deeply exercised
with regard to remaining in the city or going away,
and who were engaged to "`seek the Lord, for a right way for themselves,
their wives and their little ones,`" had a clear
sense given them that it was their duty to stay.

The yearly meeting occurred during the time the disorder was prevailing;
and a number of Friends from the country attended,
being impressed with a sense of religious duty to do so;--and the
several sittings were considered peculiarly solemn and favoured.

[.offset]
_Elizabeth Collins thus notices it in her memorandums, viz:_

"`In the ninth month 1793, I attended the yearly meeting in the time of the sickness,
called the yellow fever.
On seventh-day crossed the river and attended the select yearly meeting,
which was a good one,
our hearts being bowed in thankfulness to the Father of all our mercies.
First-day attended Newtown meeting to good satisfaction:
hearing some very discouraging accounts, +++[+++respecting the sickness,]
I felt great weakness and stripping, yea, leanness of spirit,
and my faith seemed taken from me.
Before I left home my great and good Master had condescended to inform me,
that if I would go and keep my place, my life should be given me for a prey,
and that according to my faith so should it be unto me.
I spent the night without sleep until near day,
when my faith again revived and I got some sleep:
awoke with thankfulness of heart to the Author of all good.

"`Second-day morning crossed the river with bowedness of spirit,
and attended the forenoon meeting, which was a solid time.
The representatives being called, but few answered to their names,
and from three of the quarters, not one.

"`Third-day morning at eight o`'clock, went to select meeting,
wherein our hearts were bowed in humble thankfulness before the Lord,
for his abundant mercies bestowed upon us.
At three in the afternoon Friends met... this was a comfortable meeting,
several living testimonies being borne,
to the humbling of our hearts together into contrition and holy fear.

"`Fourth-day morning, some memorials of deceased Friends were read and approved,
tending to incite to faithfulness.
In the afternoon was the parting meeting,
a highly favoured season... we were favoured to part in that near fellowship,
which is not to be expressed.
May we be thankful therefor to the Author of all good.
This is a solemn time in this city, wherein many houses, great and fair,
are left without inhabitants, many faces gather paleness,
and many hearts are filled with sadness.
Many I believe, as was formerly recommended,
are standing as between the porch and the altar, crying, '`Spare thy people, O Lord,
and give not thy heritage to reproach.`'
I have entered this city and remained in it without fear, except the fear of the Lord,
which at times fills the hearts of his humble dependent children.
May I be truly thankful for this and every other mercy.`"

Toward the latter end of the tenth month the disorder began to abate,
and in a few days the improvement was very striking,
the number of deaths being greatly diminished, the new cases very few,
and a great many recovering.
This was not owing to any assignable natural cause,
or to any new discovery in the mode of treating the disease,
but evidently to the immediate interposition of Him who, in the midst of judgment,
remembers mercy.
On the 14th of eleventh month the committee for the relief of the sick and poor,
published an address to their fellow citizens,
informing that the disease had nearly subsided,
and that the city was restored to as great a degree of
health as was usual at that season of the year;
and shortly after this it wholly disappeared.]

--

[.offset]
_Thomas Scattergood`'s journal continues:_

"`Tenth month 10th.--Felt a little revived this morning;
and after waiting until meeting time,
for my beloved friend Charles William`'s corpse to be brought past my habitation,
and it not coming in time,
I was most easy to go and sit with the little company at the market street house,
which was small indeed; S. Clark, Richard Jones and myself,
sat in the front of the meeting on one side,
Mary England and Mary Cresson on the other side of the house,
with some scattering ones over the meeting; amongst them I hope some precious youth.
I laboured in weakness, and am frequently jealous of myself,
as there has been hardly a meeting but what I
have publicly laboured in for the past month.
O may I be willing to be searched; and if it is my lot to be numbered to my grave,
may my merciful Lord and Saviour be graciously pleased to receive me.

"`11th.--Have been engaged in considering what are we,
amongst such an innumerable company of servants who are
doing their Master`'s will in heaven and on earth;
and why should such atoms mourn when the Lord of the universe is
pleased to remove some from the temptations and trials of time,
and gather them into rest,--seeing it is an easy
thing with Him to raise up and qualify many,
many more, and send them forth.
O for strength to offer up my all to my great and merciful Lord; that if life is spared,
it may yet be devoted to serve Him.
Dear Daniel Offley departed this life about ten o`'clock.

"`20th.--A comfortable day, laboured in my own meeting, morning and afternoon,
and was favoured with an open opportunity in the evening.

"`23rd.--Called to see Rebecca Jones, who was seized with great pain,
and could hardly talk to me through extreme suffering,
though the day before she seemed bravely.

"`24th.--Dear Rebecca Jones appeared under much
discouragement respecting getting about again;
but was in a heavenly frame of mind and glad to see me;
telling me that I felt like bone of her bone.
On my telling her that I had not seen but that she might be
raised up to bear testimony to the Lord`'s goodness and truth,
she replied, '`I am a poor atom, unworthy to be employed in the Lord`'s work.
Dear Thomas, many have fled from the Truth, but the Lord will meet with them.
I have been an exercised woman for thirty years past,
and often grieved to see the pride and forgetfulness of many in our Society;
the multiplying of pleasure carriages, formal visiting, etc.;`' and at another time,
when with her, she said,
'`there is another dispensation in store for this people--depend upon it,
repeating it more than once, if the people are not humbled by the present.`'

"`25th.--Went to Philadelphia monthly meeting, which was a comfortable time;
and most of those who were appointed to services being out of town and sick,
the business was summed up in one minute, except the answers to the three queries,
and the appointment of a number of Friends to join with the few left,
in the care of the poor and distressed.
I called to see dear Rebecca Jones, who lay with her eyes almost closed;
and although I spoke to her and took her by the hand, she answered not,
which was affecting.
After meeting I went again, and on going near the foot of the bed, she said,
'`dear Thomas, I saw thee, (alluding to the morning visit,) but I could not speak:
I am in waiting, there is nothing to do.`'
She lifted up her hands, and seemed to wish to say more,
and several times gave us a look of much sweetness and love;
and at length looking up again, she said, '`Go and the Lord go with thee.`'
Being with her again in the afternoon, she said, '`dear Thomas,
if the Master renews thy commission, and should send thee over the water,
mind the time and do not deal it out to individuals, but spread it before thy friends,
and thou wilt find sympathizers; and when thou gets there,
remember the poor servants in families,
they are too often neglected--the Lord dealt bountifully with me in that land,
and I have had comfortable seasons with such.`'
I asked her what she had in view in the morning when she looked up at me, and said,
go and the Lord go with thee?--she replied, '`I could not tell thee before J. J.,
though I love him, but I alluded to thy going over the great waters.
The Lord has in some instances entrusted me with his secrets,
and I have not betrayed them.`'
After some more conversation, she appearing inclined to sleep,
I left her with much sweetness, and could say in my heart,
that flesh and blood had not revealed these things unto her, but our heavenly Father,
for my confirmation and encouragement.

"`Twelfth month 4th.--About the time the last note was made, the sickness abated,
and now has nearly or quite disappeared.
Most of our Society and other inhabitants of the city are returned.
Dear Rebecca Jones was so well as to attend our meeting last first-day morning,
and bore testimony to the goodness and mercy of God;
but a different dispensation has of late taken place with me.
In the time of sickness, when fear and dismay spread over many,
my mind was wonderfully supported and borne up above the waves,
and I had faith at seasons to believe,
that if it had been my lot to be numbered to the grave,
mercy everlasting would have been my portion;
and in this sense I was favoured to rest my soul from one
season to another;--but leanness and poverty have succeeded;
and the enemy is suffered to come near,
insomuch that I feel like one waiting for some humbling dispensation to come,
in order to refine me.
O Heavenly Father, who hast seen meet to honour thy unworthy servant in days past,
led me forth, gone before me,
and hast brought me back again with sheaves of
soul-enriching peace--what shall I answer thee?
Thou hast preserved my life in a wonderful manner--thou
hast entrusted me a little longer with an helpmeet,
and lengthened out the lives of my children;
grant me clearness of sight and enable me to say, thy will be done.`"

His mind had been exercised at times for some years,
with an apprehension that it was required of him to pay a religious
visit to Friends and others in Great Britain and Ireland;
and patiently abiding under the preparatory
dispensations for this weighty and important service,
he was favoured to see with clearness, the proper season for opening it to his brethren,
for their solid consideration and judgment.
It was during this period of preparation,
and before he had disclosed his prospect to any one,
that his beloved and honoured friend Rebecca Jones,
had a sense divinely communicated to her of his being called to this engagement,
and as has been already related, imparted her feelings to him,
which appears to have had a confirming and strengthening effect upon his mind.

In the tenth month, 1793,
he spread before his friends of the Northern district monthly meeting,
this prospect of extensive and arduous labour in a foreign land;
which after solid deliberation was united with, and the requisite certificate granted.

Having obtained certificates of the unity and sympathy of the quarterly and
general spring meeting of ministers and elders in this concern,
he left Philadelphia on the 11th of the fifth month, 1794,
and next day embarked at New York, on board the ship Ohio, bound for Liverpool.
He was accompanied on board by several of his friends, from whom he remarks,
"`I parted with an overflowing heart,
willingly submitting myself to the care and protection of the Lord my God.`"
On the 13th they weighed anchor and got under way;
on this day he writes,--"`Met a kind reception from Judge Jay,^
footnote:[Minister Plenipotentiary from the United States to England,
who went passenger in the same ship.]
his secretary and others on board.
My cup has been full this morning, in remembering those I have left behind; and also,
what a pilgrim`'s life I have entered upon.
But who can describe the feelings on such a separation,
to one who is in such a lonely state as I feel mine to be?
O what would be the consequence,
was my Lord and Saviour to withdraw himself at such a time,
and leave me to combat with the weakness of the flesh.`"

[.offset]
The following extracts are taken from a letter written to him by Rebecca Jones,
dated 10th of fifth month, 1794, and endorsed, "`To be opened when at sea,
and recurred to in Great Britain and Ireland.`"

[.embedded-content-document.letter]
--

After leaving thy house last evening,
my mind was swallowed up in that love and friendship which is better felt than expressed;
and now, in the greatest sincerity, and under that influence, my heart bids thee '`Go,
and the Lord God go with thee.`'

When thou arrivest on the British shores, remember me, and pray for me when thou canst,
for though I have been, through the Lord`'s ever adorable mercy,
favoured to see for and feel with thee, yet now under the prospect of a family visit,
I am ready to sink,
and very much doubt my ability to get through to the honour of my great and good Master,
being a much poorer creature every way than thou hast any idea of.

May the Lord on high, who is mightier than the noise of many waters,
be thy bow and battle axe, thy shield, and thy exceeding great reward.
When thou meetest with my friends, say to them for me,
that my love for them and for the ever-blessed Truth, remains unimpaired;
but that being lately raised from the brink of the grave,
they must not expect many more written testimonials of my love to them; because,
being near the end of the painful journey of life,
I have less time and ability for writing,
and am strictly enjoined to salute but few by the way.

My sincere and ardent desire is,
that in those towns and places where Friends are numerous,
thou mayest remember that valuable class in society, who are hired in families, called,
in that country, servants; among whom there is a number of valuable,
tender-spirited Friends, with whom I had some precious meetings;
the remembrance whereof is pleasant at this moment.

And now under a renewed hope and persuasion,
that all things necessary will be furnished thee,
by Him who hath so evidently put thee forth, my whole heart salutes thee,
and bids thee endearedly farewell in the Lord, and am thy sister,
in unfeigned regard and true Christian fellowship.

P+++.+++ S.--Don`'t be afraid to trust thy good Master,
if he enjoins upon thee to hold meetings in the cabin;
he will make way for thee in this and every other work he may assign thee.
Do not be dismayed at the sight of the great, as thou journeyest amongst them;
but quit thyself like a man, enduring hardness as a good soldier,
and the very God of peace and consolation be with thee.
Amen.

--

"`15th.--What is man that thou art mindful of him,
or the son of man that thou visitest him?

"`16th.--My feelings have been much awakened at seasons since I got on board this ship,
and if I had not a small portion of faith left to believe that the Lord is on my side,
surely fear and dismay would be my portion.
How comfortable and cheering would the company of some
one of my dear friends now be as a companion.
How singular a movement from home it seems, to be put on board ship alone;
altogether among strangers, a stranger in the midst of the sea.
Well, the Lord was with Jonah when in a worse condition than mine;
may it be his blessed will to strengthen my faith, patience and confidence in him,
through this voyage, and be my leader and feeder on the land.
The respectful, kind treatment of judge Jay and my fellow-passengers,
is comfortable indeed.
Tears have been my meat,
and probably might have been more so had I given full vent to them.
What an atom am I to attempt such a work--this is the greatest task ever assigned me:
O that the Lord my God may be pleased to be a husband to my dear wife,
and more than a son to my aged mother, and bless my children.

"`20th.--A moderate breeze yesterday from N. N. E., so that we nearly laid our course,
and I endeavoured with all my might to keep the faith and patience.
Retired to my berth with heaviness, and had a tossing night, not of body, but of mind.
O what will be the issue of all this deep and very humiliating scene!
My companions can be cheerful,
but the fresh pangs of death and sorrow which have taken hold on me this morning!
Have I taken heed to a false light in my setting off from home?
have I not kept in the patience?
Judge me, O Lord; rip open my heart! show me my condition as it really is in thy sight.
Suffer thy servant to spread forth his hands and pour out his
heart towards thy holy habitation--hear thou in heaven,
thy dwelling place, and forgive if I have sinned,
for thou only knowest the hearts of the children of men.
Afternoon.--Faith, we are told, is the substance of things hoped for,
the evidence of things not seen: my sight seems at times gone.

"`21st, fourth-day.--Had rather a struggling night in my lonely creaking bed-chamber.
A little more quieted in mind on waking this morning, which I have esteemed a favour,
and a little hope and confidence have revived whilst sitting on deck after breakfast.
O that I may be prepared through this proving scene, as a vessel rinsed and cleansed out,
and fit for the heavenly Master`'s use.
Surely pride is hid and I see what a poor, very poor, creature I am.
A fair wind last night, and today S. W.: spoke a vessel from Ireland early this morning,
bound for Philadelphia, six weeks out.
A pleasant, warm day.
The wind continues fair this afternoon: opened dear Rebecca Jones`' letter,
received in twelfth month, J. C.`'s in the same month,
and J. Hunt`'s written after he got home from the Spring meeting,
wherein he sends me the twentieth Psalm to peruse.
Dear Rebecca Jones mentions the same in hers,
and I am thankful that I can take a little encouragement therefrom:
this has been a day of the most light, ease and quiet of mind, since I came on board.

O Lord, what a comfort it is to be in the least favoured,
livingly to believe that everything is the work of thy Almighty hand,
and that thou art nearer to thy servants than they are to themselves.
Gracious Fountain of sustaining help,
I bless thy name for this little portion of comfort vouchsafed to me,
a poor and desolate creature,
in the midst of the sea--be pleased to remember my dear wife, aged mother, and children;
my heart yearns toward them with tenderness and love.`"

[.offset]
The letter of Rebecca Jones, above alluded to, appears to be the following, viz:

[.embedded-content-document.letter]
--

[.salutation]
Dear Thomas,

I have been travelling with thee in spirit for several days,
even before I received thy plaintive note;
and as I do believe the everlasting arm of ancient, all-sufficient help is underneath,
in thy present conflict, I feel a liberty in the truth to tell thee so,
even in the language of dear John Woolman to Sarah Morris,
at a time when she was under a trying dispensation,
in the prospect of her being called to labour in a foreign land,--to wit;
'`He will bring thee through more purified.`'
So, my dear friend, lift up thy head in hope,
as thou hast often encouraged me and others to do.
And just now, the substance of the twentieth Psalm occurs very livingly to my mind;
turn to it and read it,
and apply it as a portion which has opened for
me to send thee in the love and life of Truth,
in which I salute thee, and remain thy poor and weak, yet affectionate sister,

[.signed-section-signature]
Rebecca Jones.

--

"`22nd.--Light wind and fair, last night, and continues so this morning.
Slept pretty well, and awoke with some encouraging hope;
since which I have sat down in the cabin and penned a few lines to dear Rebecca Jones:
may sustaining help be near her, and all my dear friends left behind.
O Lord, grant a portion of bread this day to sustain my tossed mind!
Afternoon.--Cast down,
but hope not forsaken--home and near connections frequently in view.
I find retirement, in deep thoughtfulness, is profitable:
O that the children of men were more acquainted with such a state!
Acquaint thyself, O my soul, with God and be at peace.

"`23rd, sixth-day.--Strong wind at south,
and continues so this morning--we have gone from eight to nine and a
half knots--passed the Banks--a wakeful tossing night--Lord thou hast
been the strength of the poor and needy in all generations;
before the mountains were brought forth, or hills were made, thou art God!
Thou hast been strength to the poor and needy in their distress, a refuge from the storm,
a covert from the heat,
when the blast of the terrible ones has beat as a storm against the wall;
condescend to bear up my drooping mind,
and all such as are engaged to seek thy face and do thy will.
O Lord, cause thy face to shine on my dear aged brother left behind;
guide him by the right arm of thy strength through this vale of trials and tears,
and bring him to inherit thy glory.
Let thy will prove our sanctification and redemption.
O for a portion of sustaining bread this day!

"`24th.--An unusually comfortable night`'s rest in my confined berth.
O what a poor creature I look like, to go to that great city of London,
and without any companion.
Did ever any poor servant set out like me, and feel as stripped and as poor as I do?
Lord, help me.
After dinner, I went to my stateroom and lay down,
where my mind was covered with sweetness and love,
on looking toward my dear connections and friends, both in the city and out of it,
whom I have visited in days past, in the love of the gospel.
Wherein the Lord helped me, showing me the time to go forth,
and also causing me to return with sweet enriching peace.
O that this may be granted through the present errand!
I have had such a hope, I trust a living hope,
renewed this afternoon--all things work together
for good to them that love God--so be it:
rest in quiet confidence, O my soul.

"`25th, first-day.--After breakfast, sat down with judge Jay and son, in the cabin;
and my mind was drawn into solid retirement,
wherein my spirit saluted my family and friends.
I remembered the North meeting,
and that my dear friends were collecting for yearly meeting at New York;
and although I dropped some tears on the floor,
I was a little comforted in remembering this precious passage;
'`Thus saith the high and lofty One that inhabiteth eternity,
whose name is holy,--I dwell in the high and holy place; with him also,
that is poor and of a contrite spirit; to revive the spirit of the humble,
and to revive the heart of the contrite ones.`'
Dare I, a poor worm, draw any encouragement from this?
O yes; although I confess my shortness and backslidings many a time, in a day of ease.
Guide me, O Lord, by thy wisdom;
grant that I may yet be favoured to be directed by thy Spirit.
Thou, whose eye goeth to and fro throughout the whole earth and sea,
in order to show thyself strong on behalf of those who put their trust in thee,
grant me an upright heart to the end of this arduous journey.

"`Afternoon.--A tossing time; some of the passengers are gone to bed,
and such as could sit up, went on deck, and it was pleasant to behold the sun once more,
which has not shone for some days past.
Saw a school of porpoises playing alongside and around the ship,
and some brown birds flying above the waves.
Methought what a life this is, to have no more comfortable resting place than a wave,
a boisterous wave of the sea;
and yet how comfortable it is made to these little inhabitants,
by an all-wise Providence; rest then, O my soul, in patience, in thy present allotment,
believing thou art where thy all-wise Creator would that thou should be;
who can in his time, which is the best, make things appear more pleasant.

"`26th.--Never more, I think,
even in the time of distress lately passed through in Philadelphia,
+++[+++from the yellow fever,]
has my spirit been broken than at seasons in my berth,
in looking over the graves of my dear brethren, who are removed from works to rewards;
and here am I, a poor worm, ransomed from death.
O the adorable mercy and goodness shown to me and my family, at that time!
May I, and all those that I have left behind, live in a sense of it,
that if we are favoured to meet again in this world,
it may be in a sense of the love and goodness of God.
How could I bear up under the dispensations allotted me,
were I not favoured livingly to remember,
that Christ Jesus our Lord was a man of sorrows, and acquainted with grief:
how little many of the children of men appear
acquainted with the baptism that he was baptised with,
and with the cup of which he drank.
O that I may be favoured with a willingness to drink of it to the end of my time here;
and if a day of enlargement is granted, after this dispensation, that I may be humble.

"`27th.--But little sleep last night.
O for patience and contentment in the will of God!
Great are the privileges many enjoy on land and
it is to be feared they are not enough prized.
I often have mournfully to acknowledge, Lord I am poor and sorrowful;
shall I again be found worthy of the annexed part?
Let thy salvation set me up on high;
set me above my doubts and fears.
I have undertaken a great work, for which I feel my unworthiness, and my weakness.
Afternoon.--The wind high and the sea rough,
so that it was with difficulty we ate our dinners.
The captain told us a little afterwards, we were going eleven knots an hour.
It is a favour that we are carried along so safely and rapidly through the ocean;
'`The way of a ship in the sea,`' is indeed a wonder, and I am a wonder to myself.
Ah me, how little can I see before me:
it seems as though my condition resembles the sea now in view from the cabin windows;
wave follows wave, and billow succeeds billow.
Remember, O my tossed soul, that Jesus, thy Lord and Saviour, walked on the sea;
and he has been with thee and supported hitherto,--has rebuked the winds and the waves,
and caused a calm.
May my weary, tossed mind find rest in him.

"`29th.--A pleasant morning with a fine breeze,
and I have been favoured to look forward in hope.
It is a great trial to part with wife and children, father and mother,
brothers and sisters, houses and land; although of the latter,
possessing not so much as many enjoy;
but I remembered on laying down my wearied head to rest last night,
and now again it revives with some comfort, that our merciful Lord said to Peter,
'`Such should have an hundred fold in this life, and in the world to come,
life everlasting;`' that is,
if they were parted with for his sake and the
gospel`'s. O that I may to the end of my days,
be found simple-hearted enough to come under this description; then all will be well.
The angel of the Lord encampeth round about them that fear him, and saveth them.
What a favour to have faith in thy most excellent name, O Lord my God!

"`How sweet is the remembrance of the labourers in the
harvest field now in Great Britain from my native land,
and how I have longed of latter time to see them and enjoy their company,
in the love and life of truth.
Lord, raise up and send forth more labourers from the land of my nativity,
if it be thy blessed will; water thy tender plants, and cause them to grow,
and make them fruit bearing branches in the living vine.
Let the sound of thy everlasting gospel go forth unto all nations.
It is thou who appoints unto every servant his portion.
Thou art served in suffering, as well as in rejoicing.
Whom have I to look to, or to trust in, but thee, to keep and preserve me,
and open a way to the end of this present engagement.
I hope, I trust in thee.

"`30th, sixth-day.--The wind shifted toward morning to S. E. and is now heavy,
with a rough sea and rain; but O, how sweet to be favoured to look upon Zion,
the city of the saints solemnity; how precious to believe in God, the Father Almighty,
and in Jesus Christ his son; and at seasons to be favoured with the communion of saints.
Surely there is such a thing;
for how sweet is the remembrance of some who are in their fixed, happy places of abode,
as well as those who are still on earth.
O that the Lord my God may be pleased to make me an instrument of good,
if it be only to an individual in Great Britain;
will it not be enough to compensate for all I
have undergone or yet may yet have to endure,
to be thus honoured as a servant of God.
O Lord my God, who hast been my helper and support through many baptisms,
be graciously pleased to bless and favour my dear aged parent
with a more abundant knowledge of the way of peace,
that her last days may be her best days,
and the day of her death better than the day of her birth.

"`31st.--A squally night--a great stir on deck about twelve o`'clock, taking in sail.
Our fore-topsail yard was carried away, and the sail torn to pieces.
It was a favour that I could lay quietly in the midst of apparent danger,
the waves rolling and dashing violently against the side of the ship,
and it is likely my little berth was below them.
But what is all this when a quiet mind is mercifully granted;
when balmy sleep puts an end for the present, to trouble.
There is a baptism into which the Lord is pleased, in wisdom, to introduce his servants,
a measure doubtless of the same cup that was
allotted to Christ Jesus our Lord and lawgiver,
for our sakes.
Know ye not says the apostle, that as many as were baptised into Christ,
were baptised into his death?
What are all outward washings compared to a living experience of this?
O the unutterable misery of that soul from whom the Lord hides his face,
and because of disobedience and rebellion will be merciful to it no more:
and how little is this thought of by vain and heedless mortals.

"`Sixth month 1st, first-day.--Ship goes easy to day, not much swell, and some sunshine.
I have been sitting since dinner,
pensively musing and thinking of my family and North meeting.
My heart was broken into tenderness--how near my
dear friends left behind feel at seasons,
and how one and another comes into view.
O how desolate and proved has been the state of my mind since
I so preciously parted from my dear wife and family,
this day three weeks ago, when I could say,
in humble acknowledgment to the God of my life,
that he was my light and my song--my shepherd and I should not want.
Blessed be his great and holy name, in that he has vouchsafed a little to renew my faith,
opening to me Jacob`'s vision,--poor worm Jacob,
when travelling from his father`'s comfortable house,
in the wilderness of this uncertain transitory world,
was favoured to behold God`'s preserving power and providence, and his spirit was cheered;
also,
when the prophet`'s servant`'s eyes were opened to
see the mount full of chariots and horses,
he said, it is enough.
Lord, I believe, help thou my unbelief.

"`2nd.--A still night, and a fine calm day.
Began a letter to my dear wife, and feel comfortably resigned to my situation:
thanks be rendered where due.

"`3rd.--Light wind to day and ahead:
have sailed only ten miles on our way for the last twenty-four hours.
Some impatience appears among the company,
but I am thankful for a quiet and resigned mind.

"`6th.--The wind breezed up fair about twelve o`'clock last night,
and this morning we are sailing about seven knots an hour.
I am thankful that I was resigned when we were becalmed,
and feel tranquil now that we are moving more swiftly towards our desired port.
The works of the Lord in bis providence over us, are just and equal.

"`7th.--At one o`'clock one of the sailors aloft cried
out '`land,`' which proved to be the Scilly Islands,
to the windward of us.
The captain has outrun his reckoning.
Several of our company are busy packing up to go on shore at Falmouth tomorrow,
and from thence by land to London.
I feel pretty quiet, though poor, and do not see my way on shore yet.

"`8th, first day.--Awoke this morning poorly and have felt so most of the day.
We were in company with a fleet last night and this morning,
and the wind first dying away and then coming ahead,
were until near sunset before we came into Falmouth harbour, where John Jay,
his son and a few other passengers went on shore, in order to take passage by land.
The captain and all the rest of the passengers being gone,
I sat down in the cabin and poured forth a few tears,--but it has
been a time of solemnity to me since the ship cast her anchor,
wherein I trust I have experienced that which is an anchor to the soul,
sure and steadfast.
I remembered this precious promise, '`I will not leave you comfortless,
but will come again unto you;`' so I can sit down alone sweetly composed,
and make this note.
Soon after making the foregoing note,
a friendly man came on board in G. Fox`'s boat with a letter from him,
kindly inviting me on shore, which was pleasant, as also the company of the messenger.
I wrote a respectful answer acknowledging his kindness.
He left me,
and I walked the quarter deck until the captain and steerage passengers came on board,
and he soon ordered the anchor up, and we put out with a fair wind.

"`9th.--Refreshed this morning, and felt comforted both inwardly and outwardly,
and my soul has been revived in a fresh and living
sense of the lovingkindness of my Lord and Master,
which makes my lonely confinement truly pleasant.

"`13th.--Weighed anchor about eight o`'clock,
and about two o`'clock came to again at Gravesend,
the wind springing up fair just as we got under way.
This has been a day of exercise in approaching
near to the great city--O for sustaining help.
There are many beautiful spots along the river which please the eye.
In the evening, the pilots who had gone on shore came back,
and we weighed anchor about eight o`'clock.
About twelve o`'clock I awoke with the bustle and noise on deck,
and found they were coming to anchor, between Greenwich and Blackwall,
where we lay until nine o`'clock in the morning.

"`14th.--I had an opportunity of seeing the city almost up to London bridge;
and although my situation on board was not the most pleasant,
neither some things which my eyes beheld on shore,
nevertheless I believe it was right that I stayed in the ship.
Between two and three o`'clock, Joseph Smith,
a kind Friend came and met the ship one and a half miles from her intended station,
and took me home with him,
where I found dear Samuel Emlen and George Dillwyn waiting for me,
and met an open kind reception from Joseph`'s wife, who is a daughter of Rachel Wilson.`"

[.offset]
Extracts from a letter to Rebecca Jones, begun at sea, near the banks of Newfoundland,
fifth month 22nd, 1794.

[.embedded-content-document.letter]
--

Thou hast been so much the companion of my
exercised mind since I came on board this ship,
and peculiarly so this morning,
that I thought I must salute thee in that love which baptized us together,
when thou wast favoured through holy help to unfold my state to me,
and in which thou hast since been made as bone of my bone and flesh of my flesh.
How shall I open to thee, my dear friend, the feelings of my mind since we parted,
and particularly since I came on board this floating bark.
Stripped of all enjoyment of the company of my beloved connections and friends,
and delivered into the hands of strangers,
not knowing the face of an individual on board, except my kind friend John Jay,
and him I never saw but once before;
I have not language fully to express the feelings which
were awakened in my depressed mind,
after we put to sea, when every prop seemed to be knocked away,
and for some days and nights I was left to struggle
with a sense of extreme weakness and dismay;
yea, I thought not far from the pit of despair.
For although some of you who love me, and myself also,
thought the way clearly and plainly opened before me,
and I was favoured to part so sweetly from my dear Sarah,
my mother and the rest of my family and friends,
and felt cheerful and easy as I passed along the road,
in company with my dear friends who gave up to see me on board;
and even until I got into the ship, I felt like one pressing toward his home;
after all this, O the unutterable pangs which came upon me,
and continued for several days.
My condition was veiled, and in the depth of my sorrow I was ready to cry out,
'`why have I done thus?`'
In this mournful state of mind, I opened thy affectionate letter and read and wept,
but seemed as though I could hardly believe so as to derive any encouragement from it.
Since then I have read it again, and also that sent me in the twelfth month,
and one from dear J. Hunt, in which he refers me to the twentieth Psalm;
all which I have read with a degree of encouraging hope,
the clouds of dismay having in some degree broken away,
and love to my dear friends sprung up in my tribulated soul.
O how near and dear some of you feel to me, now whilst I am writing--I pray for thee,
that the Lord may strengthen thy hands to war, and thy fingers to fight;
support thee throughout thy present undertaking, +++[+++a family visit]
and be thy exceeding great reward, when it is accomplished.
Still remember me, thy poor brother,
and desire for me that I may experience all the old dregs to be rinsed away,
and through adorable mercy be made a clean and upright-hearted instrument,
if favoured to labour in a foreign land--this is the desire of my soul.
Feed the flock over which the Holy Spirit has made thee an overseer;
and may all the faithful labourers be strengthened by the mighty God of Jacob,
and their feet be so established as not to be moved.
For those dear and precious children in the city,
who have been rightly brought forth in the work
of the ministry of peace and reconciliation,
my desire is that their feet may more and more be shod
with the preparation of the gospel of peace.
Never more feelingly, than since being under a measure of the dispensation of sorrow,
in this watery journey, has my mind been dipped into sympathy with the afflicted.
O may the Lord God of everlasting compassion, look down upon and help those everywhere,
who are helpless, and grant them that hope which will be an anchor to the soul.

Dear Rebecca, thou hast been and I trust remain to be a sister in sympathy with me,
and thou wilt not reject the simplicity of this plaintive note--it
will give thee to see that thou art not alone in travail and exercise,
and verily I dare not believe otherwise,
than that it is more or less the experience of all the Lord`'s truly baptized ministers.

--

[.offset]
Sixth month 8th, he adds;

[.embedded-content-document.letter]
--

Just dropped anchor in Falmouth harbour--all the passengers are gone ashore,
as well as the captain with the letter bags.
After I parted from my kind friend John Jay and his son,
who are going to take coach to London,
I came down into the cabin and endeavoured to turn my
mind to the Fountain of all-sustaining help;
and living hope sprang up, which is as an anchor indeed,
sure and steadfast in the time of trouble, and which through this trying voyage,
has brought up my poor little bark to the winds and waves, and so far, through mercy,
I have lived through it.
Whilst sitting here alone,
I have had sweetly and encouragingly to remember the gracious promise,
'`I will not leave you comfortless,`' etc.

I have received a kind letter from George Fox inviting me to come on shore to his house,
which was cheering to my lonely mind, as was also the company of the friendly messenger,
who brought it, especially when he told me there were many valuable Friends in the town,
and some of them just returned from yearly meeting.
But the captain having told me he should return soon, in order to set sail,
the wind being fair, I wrote a respectful reply, desiring my love to Friends.
And now being again left alone, I have thankfully to say in the secret of my soul,
'`Good and gracious art thou,
O thou who art the helper of all them that look unto and trust in thee.`'
A living hope revives, that thy words my dear friend, will in due time be made good,
that I shall find sympathizers in this land--so be it.

--

[.offset]
On the 20th he makes another addition--

[.embedded-content-document.letter]
--

On seventh-day last about two o`'clock, Joseph Smith came on board the ship,
about a mile and a half from London bridge, and brought me to his house,
and both he and his affectionate wife, treat me as a brother.
Dear Sarah Harrison and Elizabeth Drinker, are in the city,
the latter very poorly and under the doctor`'s hands.^
footnote:[She died in London soon after.]
I have been at several meetings, but have not had much to say, and feel willing,
if it is the Master`'s will, to pass along so for a season,
and am earnestly desirous that my spiritual senses may be so exercised,
as that I may be favoured in the right time,
with a right knowledge of the beginning corner.
Pray for me that I may be preserved among this people,
who abound with temporal good things; that I may be kept in the littleness,
and faithful to the unfoldings of divine counsel, as it may be graciously opened.

--
