== Chapter VII

His bodily health having become much weakened by arduous labour and exercise,
and no religious service opening,
he retired to his friend William Dillwyn`'s in the vicinity of London,
with a view to recruit.
At the hospitable mansion of this friend,
and others in that neighbourhood and at Tottenham, he remained for three weeks,
when he returned to London, and in a letter dated the 21st of the fourth month,
after referring to the improvement of his health and respite from labour, he says;
"`I desire to attribute it to the mercy and condescending love of the great Shepherd,
who still sustains the character anciently given; I am the Lord that healeth thee;
which teacheth thee to profit;
which leadeth thee by the way thou shouldest go--surely I may say,
it was so on first-day last,
having laboured in Grace-church street meeting both morning and afternoon,
and to my admiration was strengthened to speak to a great crowd of people,
at the burial of an ancient Friend, (J. Hagan) in the evening,
in which I was exercised in a close and awful manner.

"`I am now out of business--have attended all the monthly meetings in this city,
and trust I stood resigned to labour as way might open.
My friends say I have need of rest to recruit my health, but for all that,
I am almost ready sometimes to let in the thought that I am too much of a loiterer,
when considering how much time has slipt away.`"

[.offset]
The following letter from George Dillwyn, dated Redruth, fourth month 18th, 1795,
will serve as a specimen of his laconic style.

[.embedded-content-document.letter]
--

[.salutation]
Dear Thomas,

Thou and I correspond, in the letter way, like poor day labourers,
who have but little to spare to each other.
The sparing of that little, however, seems to be saying,
'`if I had more thou shouldst be heartily welcome to it.`'
For my part, when I have told my friends where I have been; where I am;
and (if I can) whither I am likely to go,
the end of writing is nearly answered and my budget exhausted.
I may congratulate thee on thy finish at Devonshire house, +++[+++the family visit]
and was pleased with thy retreat into the country;
though such little recesses from service often remind
me of a speech of the mate of the ship Pigou,
one morning to the sailors; "`come lads,
step down and get your breakfasts as quick as you can,
and then you will have nothing to do but to work.`"
I have mentioned to my brother that I am now engaged in a
visit to the families within the western division of Cornwall.
We have just finished at this place, and after staying to the meeting on fifth-day,
and a public meeting appointed for the inhabitants tomorrow,
expect to proceed to Marazion and Penzance the day following; but how afterwards,
this deponent saith not.
Thy affectionate remembrance of me and my dear Sarah is very acceptable,
and we hope will continue.
As to outward and visible signs of it, though we do not pretend they are objectionable,
we do not by any means consider them as essential to the
friendship most surely subsisting (and long may it continue)
between thee and thy sympathizing fellow-servants.

[.signed-section-signature]
George and Sarah Dillwyn.

--

"`Fifth month 16th.--To the opening of the select
yearly meeting in London,--felt poor and unworthy;
sat in silent abasement and felt content in that condition.

"`17th, first-day.--Went to Westminster meeting in a low state of body;
and had an open time, particularly to the youth.

"`18th.--To the adjournment of the select meeting,
and at four to the opening of the yearly meeting for business.
Felt a willingness to bear my burden and exercise in silence, and did so for some time,
but at length seemed as though I could not avoid
bearing testimony against a forward active spirit.

"`19th.--A time of exercise, not only on my own account,
but also for the right moving of the yearly meeting.
Went to the adjournment at ten o`'clock, and had something to say in the forepart,
expressive of my exercise that the meeting might be preserved solid;
which was in good degree the case.

"`20th.--The meeting for business at four o`'clock, was a good time.
I also visited the women, accompanied by William Tuke, to my satisfaction.

"`23rd.--Ventured, although feeble, to go and sit the meeting,
which was the most solid time, I think, that we have had.
The minutes of the meeting for sufferings were read,
and the slate of the little society at Pyrmont, in Germany, came under consideration,
and Friends`' attention was turned toward visiting them.
Dined at Thomas Horne`'s with dear John Storer and many others,
and after dinner I had a singular time of communication,
and my heart was measurably melted within me.
Lord keep me in the hour of trial, I pray thee, if thou suffer it to come:
thou knowest what is best for me.

"`24th, first-day.--To Devonshire house meeting, which was large;
Susanna Horne appeared in supplication, and I had a thorough time of relief.
To Grace-church street afternoon meeting; was very large,
many strangers not of our Society being there, with whom I had a full opportunity.

"`25th.--An humbling heart tendering morning to me,
with prospects of service opening to my view.
Thou, Lord, knowest what is best for me,--O how can I move a finger without thy help.
O keep me firm on the ground of Truth, come what will.

"`27th.--I sat about an hour and a half with the committee on Ackworth school,
and withdrew weak and poorly--Lord support me to the end;
and if thy blessed will is done all will then be well.
Went to meeting at the fourth hour, and soon after it was settled,
the clerk revived the concern which had been spread before a former sitting,
respecting a visit to the little company in Germany, which held some time;
and the way closed up for making such a visit,
and it was recommended to the attention of the meeting for sufferings.

"`28th.--To the last sitting of the select meeting,
where I had an opportunity pretty fully to relieve my mind,
and in the afternoon attended a special meeting for sufferings.
I am glad and thankful that my mind is resigned and easy.

"`31st.--Went to Tottenham meeting in poverty and a sense of much unworthiness,
and ventured to bend in supplication, and found relief.
I also reminded that assembly of the many opportunities I had had among them,
and that this was not likely to be the case again soon,
and probably some of them might see my face no more in this world.
I thought a solemnity spread over the meeting,
and divers other Friends appeared in testimony, much to the same purport.

"`Sixth month 1st.--Went to London with William Dillwyn and wife, to morning meeting;
where were a number of country Friends.
I poured forth my tears in silence,
under a sense of how near the enemy was permitted to come,
in order to overturn and lay waste the work of Truth in my heart.
'`Blessed are the pure in heart;`' this language has been frequently in my mind of late.

"`2nd.--To Devonshire house meeting, which was small,
but I hope a time of some comfort and encouragement,
and I found an opportunity to salute the youth in particular, and bid them farewell.

"`3rd, fourth-day.--Attended Grace-church street meeting,
and had a pretty open time to take leave of my friends.`"

[.offset]
Under date of sixth month 4th, in a letter to his wife, he says:

[.embedded-content-document.letter]
--

I was much exercised during the yearly meeting, and my health impaired,
but as soon as it was over I went to Tottenham, my usual resting place,
and spent a few days at Thomas Horne`'s and William Dillwyn`'s, and I am now, I think,
as well as I was the first week I landed.
Whilst making a note in my diary to day, I was told there was one waiting to see me.
I found it to be a youth, who has of late attended Devonshire house meeting.
He appears convinced and turned in mind to the divine principle of light and grace.
My heart rejoiced in his company, and at this time rejoices, in that,
however poor and tried an instrument I have been in this land,
the Lord my helper is in some instances, in degree, crowning my labours with success.
The praise is His due:
I may not forget some of the baptizing opportunities I
have been favoured with in this great city,
and when permitted to behold some fruits, I feel encouraged.

--

"`5th, sixth-day.--Left London after breakfast,
in order to attend the quarterly meeting at Colchester.
Put up at John Kendall`'s, and here met with Ann Tuke and companion,
and a number of other Friends.

"`7th, first-day.--To meeting, and was favoured to pour out my exercise in public prayer,
and found some relief.
The afternoon meeting was large and mixed,
and I sat nearly or quite two hours in silence, and then a little opening presented,
through much exercise, and trust it was profitable.

"`8th.--Attended the quarterly meeting and an adjournment.
In which I had some service.

"`9th.--To the parting meeting, the labour of which fell on me,
and through divine help it was, I trust, a good solid time.
Dined at John Kendall`'s; after which many Friends came in,
and I had a full opportunity to relieve my mind,
to a state which I apprehended was under the anointing for
gospel service,--exhorting not to put off out of season,
but when the way clearly opened to make trial.
Parted with near affection from my dear friends Joseph and Rachel Smith and sister,
Mary Stacey, who came thus far with me; and accompanied by my friend George Stacey,
who has given up to go with me for some time, proceeded on our journey.

"`10th.--Attended the week-day meeting at Ipswich, and was silent:
in the afternoon went to Needham.

"`11th.--To Needham week-day meeting, and was engaged to speak a little, near the close;
and in the evening to an appointed meeting, in which I was silent.

"`12th.--To Ipswich monthly meeting:
heard that dear John Storer died on his way from yearly meeting,
within thirty miles of home.

"`14th, first-day.--To Ipswich meeting, and had an open time;
in the evening was a public meeting for the town`'s people, which was very large,
and although laborious, proved a good time: after which,
a precious season with a number of Friends.

"`15th.--In the evening at five we were at Woodbridge meeting,
where we put up at Benjamin Evans`'. As I was sitting in
this meeting my mind was comforted in a belief,
that although there was the alarm of war and confusion in the land,
the Lord would remember poor desolate Zion, and in a time to come,
build up her walls and set up her gates: I had to mention my prospect to Friends,
and it was a sweet tendering time to some of us.

"`16th, third-day.--To Suffolk quarterly meeting, at nine o`'clock, which held until two:
and to the adjournment at four o`'clock.
It was an open time, wherein much encouragement was administered;
and although but a small company, there are precious plants among them.

"`17th.--To what is called the parting meeting, which was a sweet encouraging time;
and at the close appointed one for the town`'s people, at six o`'clock, which was large,
but a very trying one.
O the thick darkness that covers the minds of many; however,
strength was afforded to labour.

"`18th.--To Listen, and put up at an inn: the meeting was an encouraging time,
and some tenderness appeared: after meeting rode to the widow Sarah Jessup`'s,
and after dinner we called the servants in, and had a good religious opportunity.
Here Ann Tuke`'s mind was impressed with a prospect of
having a meeting at a town called Oxford,
five miles on the way, and our kind friend Dykes Alexander and others,
went on to get a place.
To which we went,
and held the meeting in a large room at the inn,--it was filled up with people,
and though laborious, ended well.

"`19th.--To Beccles, and attended meeting; very few of the town`'s people came.
Here is a pretty neat little meeting-house, but religion very low.
Though I had to mourn the desolate state of Zion, on sitting down,
I thought that if I was the only one in the town,
I would cheerfully sit down in that place and worship; and I had to testify,
that when the Lord turns again the captivity of his people, Judah shall rejoice,
and Israel shall be glad.
Had a religious opportunity with the family and such Friends as came in,
belonging to the meeting.
After tea went to Lowestoft, near the sea.
Dykes Alexander and others having gone before, to see after a meeting place;
and having found a large building which was fitting up for a play-house,
we held the meeting in it.
It was filled up,
and though there appeared a disposition to lightness and laughter in some,
at first sitting down, yet it proved a solid good time,
and afforded me much satisfaction.
We returned to Pakefield, a little village two miles distant, and lodged.

"`20th.--We had a small meeting this morning, which was open and comfortable,--some goodly,
sober looking people attended, and among them the priest of the parish,
who was exemplary in his sitting.
After dinner went to Yarmouth, about ten miles, near the sea.

"`21st, first-day.--To meeting, where I had to bear a remarkably close testimony.
In the afternoon meeting I was silent, but Ann Tuke appeared in a lively manner.
She had thought of having a meeting at a little village called Gall`'s-town,
and some Friends went to get a place to hold it in this evening, but could not succeed.

"`22nd.--Set off early, and got into Norwich by eleven o`'clock, to select meeting;
and again to quarterly meeting at five o`'clock.
The men met in one house, and the women in another, a mile distant.

"`23rd.--To the adjournment of the quarterly meeting, at ten o`'clock,
which was a close time: I went also to the women`'s meeting and relieved my mind;
after which, retired to Edmund Peckover`'s,
being so spent as to conclude it not prudent to return to the men`'s meeting.
To a large public meeting at six o`'clock.
Ann Tuke appeared, but I was shut up in silence, and sweetly contented.

"`24th.--To a large meeting at ten o`'clock, in which I was engaged in the ministry,
much to the relief of my own mind.
Went to Joseph Gurney`'s, and dined with Joseph Gurney Bevan, wife, and others,
and had a satisfactory religious opportunity afterward;
there appearing something good at work in the minds of these young people.
May such seasons of love be blessed to them all.

"`25th.--In the afternoon went to Lammas, to an appointed meeting at five o`'clock,
and it proved a distressing time; from thence to North Walshara,
and lodged at John Ransom`'s.

"`26th.--To meeting about a mile out of the town, held in a neat meeting-house.
A number of the neighbours came in, and it was an open time: after dinner,
rode to Norwich, and attended the week-day meeting at six o`'clock,
where I had a very close testimony to bear.

"`28th, first-day.--To meeting at ten o`'clock, and had very searching service.
After lying down and being refreshed, went to the large meeting-house at five o`'clock,
the meeting being put off from two to that hour by my request; it was very large,
and I was helped greatly to relieve my mind.
At night I lay down weary, but in peace.

"`29th.--Richard Gurney sent for us to dine with him, a few miles out of town;
where we found David Barclay, an ancient Friend, much afflicted:
after dinner had a religious opportunity, to the relief of my mind,
and then went to his brother John`'s; had a solid time with this family,
wherein all our little band, even William Alexander and George Stacey,
had some communications: returned home, and I feel a very poor creature,
having been humbled this day.

"`30th.--To the week-day meeting at Norwich,
wherein I was brought into a state of trembling,
and remembered the prophet Habakkuk:--I hope it was to profit.
Dined at Thomas Bland`'s;
and after being favoured with a precious parting season with the family and servants,
and a number of Friends, went about two miles out of town.

"`Seventh month 1st.--Had a painful time at Wymondam meeting,
being distressed with a spirit of infidelity.

"`2nd.--To Tivetshall,
and had a laborious season in pleading with the stout-hearted youth;
then attended an evening meeting at Diss, which was a comfortable open time,
from the subject of the patriarch Jacob`'s vision and journey, etc.;
after which had a memorable opportunity in a Friend`'s family: O may it be kept in view,
and improvement made.

"`3rd.--The meeting at Attleborough was held in a private house,
and was open and relieving.
After a solid time with the Friends belonging to this meeting and neighbourhood,
went to John Bouswell`'s.

"`4th.--To Mattishall, which was a low time, and did not seem much like a meeting to me:
I suffered in silence.

"`5th.--First-day, to the general meeting at Downham, at which place no Friend lives.
Stopped at an inn, and met a large committee of the quarterly meeting,
who were appointed to attend it.
But few of the neighbours came to the meeting,
and in the fore part of it my mind was opened to look back at the state of
the children of Israel in Egypt--at Abraham`'s vision respecting them,
when an horror of darkness overspread him--also the gathering of our early
Friends from different societies--George Fox being by himself on a hill,
and proclaiming the day of the Lord,
and the prospect he had of the seed of the
kingdom lying thick on the ground and sparkling,
etc.: and although here was great desolation, this meeting being gone to decay,
I had a comfortable prospect of a day approaching,
when the seed would spring as out of the dry ground and spread;
with which prospect I stood up and told Friends I knew not what we had met for,
but to see our nakedness, and for our humiliation.
Near the close I stood up again,
and I thought my testimony had some effect on a few individuals not of our Society;
though here, as also in some other places, some persons left in the midst of my labour,
who, I fear, are not willing to endure sound doctrine.
Went to Finsham, where there are no Friends, and had a large meeting in a barn,
I hope to profit.

"`6th.--To a meeting at Swaffham,
consisting of only one family and some of the neighbours, and it proved a good time.
Then to an evening meeting at Fakenham, where there are but two members:
a person left the meeting while I was speaking concerning righteousness,
temperance and judgment to come; but another met me as I was going out of the house,
and said he hoped we should meet in heaven.

"`7th.--To the monthly meeting at Wells, where there were but few Friends,
and these in a weak state; but I was glad in finding tenderness,
and I hope some desire to improve:
after dinner had a solid opportunity with a number of Friends.

"`8th.--To a meeting at Holt; and though I went to it under discouragement,
it was a good time; many neighbours came in and behaved well, and some soldiers.
After dinner went to Walsingham, to an evening meeting in a public building,
which was large, and I hope to profit.

"`12th, first-day.--I have had a fatiguing time for weeks past,
and awoke this morning in a low and tried state of mind:
when I came down stairs found letters from my dear wife, son, and several friends.
Went to meeting at Bury,
and though at the beginning there appeared a small opening into the state of the people,
and I was ready to conclude that I might minister to them, it closed up,
and I poured out my tears until I wet the floor.
At two o`'clock went to the afternoon meeting,
and there also bonds and afflictions continued upon me,
and though I was silent throughout, Ann Tuke appeared acceptably in the morning.
O Lord, remember me in thy wonted love, and continue thy good hand upon me,
that my soul may not faint in the day of trial.`"

[.offset]
At this place, the following letter from his friend, the late John Elliott, of this city,
was received.

[.embedded-content-document.letter]
--

[.letter-heading]
John Elliott to Thomas Scattergood

[.signed-section-context-open]
Philadelphia, Sixth month 6th, 1795.

[.salutation]
Dear friend,

I cannot let this opportunity pass without giving thee
a token of my affectionate remembrance,
having often thought of thee since thou left us,
and at times have felt sincere desires for thy preservation,
and that thou mayest be supported from day to day,
and strengthened to persevere in accomplishing the arduous task thou art engaged in.
If it was in my power secretly to assist in holding up thy hands,
I should be glad to afford my feeble endeavours in that way,
but am sensible of my own poverty and inability;
being persuaded that it is only in proportion as we walk in the light,
that the true union and fellowship are to be felt.
Where this is really the case, I believe the outward distance whereby we are separated,
cannot obstruct the current of that divine love, which, when together,
has been known to flow from vessel to vessel;
and if we were always watchful and careful to keep out every thing of a defiling nature,
the consolating stream would undoubtedly be more frequently witnessed to circulate.
But the world and its cumbering cares have the same effect now,
as the labours of the Philistines formerly, viz., to stop up the wells;
which makes renewed labour necessary to dig them again,
in order to come at the spring of life.

It is indeed, as our Lord said, "`The cares of this life, the deceitfulness of riches,
and the love of other things, choke the good seed and cause it to become unfruitful.`"
I feel it to be so in myself,
and fear it is too much the case with many others of our Society,
both in this land and in my native country, where thy lot is now cast;
a land that was eminently blest about a century ago,
with the revival of the gospel in its primitive purity, after a long time of darkness.
From thence were transplanted into this country, some of the choicest vines; but low,
both here and there,
instead of fruits being brought forth to the praise of the good Husbandman,
many wild grapes are produced, and much unfruitfulness is apparent.

Yet it appears the vineyard is not forsaken;
the labourers are sent forth from time to time with a renewed invitation,
and it will be comfortable to hear that they are favoured to
see of the travail of their souls and be satisfied;
but if that should not be the case so fully as is desirable, this is certain,
the faithful labourers will have their wages.

Our dear friend Nicholas Wain, is now about to embark for Europe,
and thy worthy father-in-law, David Bacon, has given up to accompany him,
which I hope will be mutually comfortable and satisfactory,
both to themselves and Friends where they come.
I expect it will be so to thee to see them;
and I believe I may say it is so much so to us,
(except the loss of their company and services,) that we are
made willing to part with them for the great work`'s sake.
If the way should clearly open,
and any of you find a draft of love toward the Friends in the South of France,
I hope you will not come home with a burden, for want of giving up thereto.
I should be glad to hear of such a visit being performed,
which I have no doubt would be very acceptable to them.

--

"`14th.--Went to Mildenhall,
which proved a trying meeting to me in various
respects--very few members or others present.
It seems as though in some places the lame and the blind were the guards of the house,
instead of David`'s valiant men.
Mary Alexander, from Needham, rode with George Stacey;
she has joined Ann Tuke as a companion in further service in these parts,
and the public service fell on them.
I was plunged into deep exercise.
O what can be the cause that this has been so frequently the case of late.
Lord, favour with ability to offer up my will to thy divine will,
that so the work thou hast allotted me to do may not be marred.

"`16th.--To the week-day meeting at Bury, which was open and comfortable to me:
I found enlargement of heart, and at the close appointed one to be held in the evening,
for the town`'s-people.
Ann Tuke and companion set off to attend an evening
meeting they had appointed about sixteen miles distant,
and we went to our meeting, which was well attended,
and my heart was enlarged to preach the gospel;
and the people behaved with much sobriety.

"`19th, first-day.--At Oakham.
I feel renewed in my bodily powers, by travelling and fresh country air.
O my gracious Lord and Master,
suffer not the enemy to prevail and bring a cloud over
my mind--thou knowest how it is with me,
and has been of late.
Sat the two meetings in silence.

"`After passing through Nottingham, Mansfield, and Chesterfield,
arrived at Sheffield on the 24th.

"`26th, first-day.--Went to meeting morning and evening,
in both of which I was exercised in testimony.

"`28th.--Got to Ackworth, and in the afternoon sat with the committee.

"`29th.--Attended the public meeting, which was very large, and laboured in it,
but mostly to people of other societies.

"`30th.--Sat again with the committee, and spent the day at the institution:
the business being ended,
many Friends left--in the evening we had a pretty solid opportunity
with several of the family and other Friends who came in to see us.

"`31st.--This morning the poor in the neighbourhood came to get the
broken victuals which Friends purchased of the inn-keeper,
and whilst I wrote a letter,
another Friend had a religious opportunity with them in the yard.

"`Eighth month 1st.--Took post-chaise to Tadcaster; after which,
to our friend Lindley Murray`'s, near York, where I met a kind reception.

"`2nd, first-day.--To meeting, and was silent; things appear low,
and I had a pretty deep plunge.
Went to the meeting in the castle, held with the prisoners,
accompanied by Joseph and Rachel Smith, etc.,
which was a pretty satisfactory time--was shown the tower from
which William Dewsbury preached to the people,
and one of Friends`' books, among others,
which were presented to the prisoners in this place,
upwards of one hundred years ago--they yet remain for the same use.

"`3rd.--Spent the morning in writing drank tea at Henry Tuke`'s,
and walked on the walls of the city and crossed the water in a boat,
and then to his father`'s, and looked into the grave-yard,
where I was told John Woolman and Thomas Ross were buried.

"`5th.--To meeting at Leeds, which was large,
and my mind was exercised to stand up with these expressions,
'`They spend their days in wealth,
and in a moment they go down to the grave;`' and it
appeared right to plead with the rich and full.
After dinner we rode to Christiana Hustler`'s, at Undercliff,
and attended an evening meeting at this place, called Bradford,
in which I was much shut up and very poor,

"`7th.--Went to monthly meeting held near Todmorden, almost twenty miles distant.
I had nothing to say until near the close of the last meeting,
and then had to bear testimony against a contentious spirit,
in one who had been displaced as a minister:--returned to Christiana Hustler`'s.

"`8th.--Felt weary with my journey yesterday, and in a low spot this day throughout.
O for greater purity of heart and more of the spirit of prayer.
O Lord, suffer me not to forsake thee.

"`9th, first-day.--To the meeting at eleven o`'clock--passed through it in silence.
After tea,
Christiana Hustler came and told me it was their practice to
call the family together on first-day afternoon or evening,
with which I united; and they were called in, and I sat with the company,
which was large, and after a time my mouth was opened,
and favoured with so much enlargement as to give some relief to my mind.

"`10th.--Nothing opening, spent this day with our hospitable friend Christiana Hustler,
and on the whole it has not been the most unpleasant,
but hope a little ray of light has dawned.
O what a brave thing to be truly resigned in patience and contentment, even in poverty.

"`11th.--Went to Manchester, and on the 12th attended meeting there;
in which I felt an exercise to prostrate myself in supplication on my own account,
and also on behalf of my fellow labourers in the harvest field,
both in this land and in America,
and that mercy and truth might be near to support those left at home,
and bear up under all trials which may attend them;
and also that the exercised children whom the divine Master is fitting, and hath fitted,
to enter the field, might be preserved.`"

[.offset]
On the 15th he arrived at Liverpool, where he remained about two weeks,
attending the meetings as they came in course, although much indisposed.
On the 29th, he embarked in a vessel bound for Dublin, where he arrived on the 31st,
and was kindly received by Thomas Bewley and family.

Ninth month 1st,--He says, "`To the weekday meeting held in the Meath street house;
in which I ventured on my bended knees to pour out supplication for
support under the future baptisms to be met with in this land;
and it appeared to be a tendering season over the meeting,`" In a letter dated this day,
he says, "`My own conflicting tossed condition came feelingly into view;
I remembered what I had passed through for months,
when a language arose after this manner, '`O Lord,
help me to bear up under whatever thou mayest be pleased to permit to come
upon me on this island;`' and there was immediately an answer as on this wise;
'`have I ever failed thee in the greatest strait?`'
in which my soul was willing to lay hold of a little encouragement.
I remembered Jonah and his prayer, and opened the good book and read it at large,
as therein left, no doubt for the strength and encouragement of all such poor messengers,
from that time to this.
For when my soul fainted within me,
I remembered the Lord--and my soul desires to sacrifice unto Him in Ireland,
and to perform all my vows.

"`9th.--To Baltiboys meeting, which was but small; after which went to Ballitore,
to the widow Shackleton`'s; had a very wearisome night,
having rode the greatest part of the way on horse-back.

"`10th.--Very weary and sore;
went to meeting and sat in silence--dined at Abraham Shackleton`'s at the school,
after which visited an ancient Friend.

"`11th.--To Carlow monthly meeting, and in it I had a close testimony,
which was relieving to my mind;
and in the meeting for business felt fresh courage to appoint a public meeting,
which was filled;
and it was supposed that three hundred persons were unable to get into the house.
It was a satisfactory time to me.
Several officers of the army, soldiers,
and some of the principal inhabitants of the town, were there.
They behaved well in the house, but outside there was some disturbance, in consequence,
it was thought, of a desire to get in.

"`12th.--Rode to Castledermot to a meeting for the town,
but although Friends took much pains to go round and invite the people,
but few came--however, it was a good time to me:
I remembered how the Lord led his people out of Egypt, gave a law unto Jacob,
and statutes to Israel,
and brought them into the land of promise--that ail the days of Joshua,
and the elders that outlived Joshua, they kept measurably unto it; and after this,
when they forsook their King and Shepherd,
they were sold into the hands of their enemies,
and delivered again when they cried unto him in distress.
I had to mention what a low state of things existed in the days of Saul, when he,
with his little band of men stood trembling under the oak; how the Lord chose David,
and caused the state of that people to flourish under him,
and more so under peaceable Solomon;
when that dispensation came to its summit:--how the Lord raised up valiants in this land,
and his gathering, sustaining arm was near to support so long as they leaned upon it.
And I did not question but that precious seasons of mercy and love had been experienced,
even in that old house, which had not been opened but once for years,
no meeting being now held in it: yea, I thought even the steps before me,
that led into the gallery,
had been occupied by those who had broken hearts and contrite spirits.
But now, alas! how the crown is fallen from off the head.
Nevertheless, there was a glance into the opening of better days.
I remembered the day that William Edmundson spoke of,
when land was to be had there at a low rate,
and then there was a danger of Friends becoming rich and forgetting themselves,
which it is to be feared too many did in that day.
But O, precious was it, as I sat, a little to behold the opening of a day,
when oppression will be removed, and patrons of the poor will be raised up.
In that day the poor, even the poor amongst men, shall increase their joy in the Lord.
We dined at an inn,
and after it I returned to Ballitore in company with Thomas Bewley and A. Shackleton.
On opening William Edmundson`'s journal, I found that Friends in the beginning had sweet,
heavenly, refreshing times at Castledermot.

"`13th.--To the meeting at Ballitore, which was low in the beginning,
and too much of a restless state prevailed in old and young: however,
I was enabled to stand up, though in weakness, and after some close labour with states,
which I apprehended were present, I felt more openness toward the close,
particularly to the school boys,
and at the conclusion of the meeting appointed one for the inhabitants of the town;
and to my admiration the house was pretty full, and a number out of doors;
and I trust the gospel of life and salvation was freely preached and owned by some,
and my mind was much relieved.

"`14th.--Returned to Dublin.

"`15th.--Tried this morning with a prospect that probably I
must offer myself to go from family to family in this place,
which has frequently of late darted into my mind.
O for wisdom and an understanding heart to go in and out before the people,
has been the prevailing language since I awoke:
may I be favoured with a clear prospect of duty,
let it be whatever the Master may appoint.
Went to the monthly meeting held in Meath street.

"`16th.--To the adjournment of the monthly meeting, which was small;
about thirty-three Friends present.
Soon after we sat down I found some openness towards this little band,
which appeared like that of Gideon, reduced less and less:
I was led in an encouraging line,
and in the conclusion told them that I could not see my way out of Dublin,
and was willing to unfold my state and some
little prospect that had opened to stay awhile,
and to visit either some or all of them in their families,
or such other religious service as might turn up.
It was a tendering season; my certificates were minuted,
and they left me at liberty to proceed as way might open amongst them:
before the meeting closed I felt most easy to appoint a
meeting for the youth to be held this day week.

"`18th.--The meeting to day was an exercising time,
and no opening to minister until near the close,
when I spread my thoughts before Friends, after which I felt a little relief.
Took tea at Samuel Stevens`', and as I went into the door of the parlour,
I cast my eye on a person who sat som distance from it,
but owing to the room being dark I could not obtain a full view of his features,
but was struck with his resemblance to my father-in-law, David Bacon;^
footnote:[He had recently arrived in company with Nicholas Wain,
a valued and beloved minister of Philadelphia,
who went on a religious visit to that country.]
and as I approached nearer he arose and met me,
when I found to my surprise it was indeed he.

"`20th, first-day,--At meeting today,
my mind was unexpectedly exercised to stand up with these expressions; '`I cannot,
I dare not, disbelieve the being of a powerful, just and merciful God.`'
It was a season of relief and much sweetness;
more than I had before experienced in this land.
The days of my youth came into remembrance,
and the Lord`'s gracious dealings with me from my childhood;
and near the close this precious language came sweetly into view;
'`It is finished:`' when I was ready to query, what?
And although it is a very pleasant thing even for a moment,
thus to have the burden removed off the shoulders,
and a day of sabbath and ease experienced, yet I dared not to covet that it might last,
but rather that the Lord my God might be pleased still, as hitherto,
to preserve in and through all the trials he may permit, who knows what is best for me.
O how my mind has been beset at times since the yearly meeting at London;
and these words,
'`It is finished;`' was the language of the divine Master after a time of agony: wait then,
O my soul, on thy God.
To afternoon meeting, and sat silently content--spent the evening at home.
What need to watch and keep the garment undefiled in conversation.

"`21st.--To an appointed meeting for heads of families,
which was an open relieving time to me, and I trust satisfactory to Friends.

"`27th, first-day.--To meeting at Moate, which was large,
and most of the labour fell on me, from the words, '`By the rivers of Babylon,
there we sat down; yea, we wept when we remembered Zion.
We hung our harps on the willows in the midst thereof.`'

"`28th.--To quarterly meeting at ten; the men met by themselves,
and it was a remarkable time to me.
I had to stand up with this language,--'`When the
sons of God presented themselves before him,
Satan came also amongst them;`' etc., and though such was my exercise in the meeting,
I had secretly to acknowledge that the Lord was good,
and a hope revived that I should not be forsaken in troubles and trials yet to come.
Went to the adjournment at four o`'clock,--sat it through in silence:
Nicholas Wain went with David Bacon into the women`'s meeting,
and had a large and good time, and when he returned, spirited friends on to business.

"`29th.--To what is called the parting meeting, which was large;
and dear Nicholas Wain was favoured with a thorough, awful and awakening time,
in pleading with the free thinkers in our Society.

"`Tenth month 2nd.--I am shut up in spirit at J. Clibborn`'s, near Moate, and may say,
the pursuer seems at times near upon my heels,
and surely nothing short of the renewed extension of divine
mercy and love will keep and preserve--I can do nothing:
wait then, still wait, in patient resignation, O my soul,
and heed not what man shall say or think; the sufficiency of a gospel minister is of God.

"`4th, first-day.--To Moate meeting, and was enlarged, especially towards the youth,
and had to point out the dangerous situation some were in, and to encourage others;
and if I have been favoured to engage some one to leave the tree of knowledge,
of pleasure, or carnal gratification, surely my being shut up for several days past,
as in a prison house, ought not to be discouragingly looked at;
and if only for my own mortification and instruction, with reverence may I say, so be it.
Near the close I mentioned to Friends a prospect
of seeing their neighbours in the evening,
at five o`'clock: when we went into the house it was crowded, and many could not get in:
and thanks be rendered to Him who is ever worthy,
he favoured me with strength to preach the everlasting gospel; the people behaved well,
and I left the house in peace.

"`5th.--A struggling, wearisome night;
and way seems opening this morning to go into some families.
Visited six, of which some were pretty open, and I had both encouragement,
exhortation and reproof to hold forth; but in the others was shut up in silent,
painful conflict.

"`6th.--After breakfast took a lonely walk in the garden,
when the very same prospects which have often come upon me, were renewed:
'`He shall take of mine and show it unto you, and he shall show you things to come.`'
Thy wisdom, O Lord, is unsearchable, and thy ways past finding out:
take not thy love and forbearance from me, and it will be enough:
though sorrow may yet be my portion, forsake not thy poor tossed servant.
Called to see most, or all the rest of the families that live in town,
and in some of them had something to offer.

"`7th.--To the monthly meeting; in the fore part of which, I was favoured with an open,
large time, of much encouragement;
and in that for business had likewise to speak encouragingly,
and I thought the little handful present were favoured with that which sweetens,
and some with tenderness and brokenness of heart.

"`8th.--Saw my way this morning to go toward Dublin, and set off,
and got twenty-two miles before night, and bore this day`'s ride pretty well;
sweet peace and comfort was my companion, so that I can now, this evening,
feelingly adopt this language, '`The Lord is good to Israel,
and fully rewards his servants:`' my heart is thankful for such a renewed sense.
On sitting down quietly by the fire-side,
my mind was turned to look at the various baptisms and
conflicts I have had to pass through.
I remembered the tried condition I was plunged into but a few weeks ago,
on alighting from my horse and sitting down in this room; now a sweetness accompanied,
and with resignation, spread itself over my mind.
Often has Ezekiel`'s case come up into remembrance in this land,
when He who hath an undoubted right to enjoin what he pleases, was pleased to say,
(and who dare say to Him, What doest thou?) '`Son of man,
behold I take away the desire of thine eyes with a stroke;`'
and even under this sore dispensation '`he was not to mourn,
nor let his tears run down, etc.`'
And the query has arisen, if my heavenly Master should be pleased to do so by me,
could I support under the dispensation, and submit with cheerfulness?
Surely I may be indulged to offer a sigh, even at the thought.
The Lord knows best what is best for me,
and my soul is led with earnestness to covet the seal of his love and approbation,
come what may come, to the end of my probation here.
O what a favour to have this seal in the forehead!
And what is this?
has been an humbling inquiry.--Answer, '`The Lord knoweth them that are his.`'
He knows how to keep his flock, and lead and feed them like a shepherd.
O then my soul lean upon him, drink down heavenly wisdom and instruction,
and crave assistance to do so in and through every dispensation yet allotted,
that thy end may be peace.
Thus I seem carried along, and I hope, feel mercy and sustaining help near to animate,
yet know not what proving may come, or what step or baptism into usual blindness,
weakness and want, may be dispensed; though at present,
I see so far as to invite Friends of this place to come together,
and sit with me tomorrow.

"`9th.--To meeting at Edenderry; which was an open, good time,
and my heart was enlarged to my own, and I believe, to my friends`' satisfaction.

"`11th,
first-day,--Ventured out to meeting (in Dublin,)
and although I sat pretty long in silent poverty,
at length I was favoured with a baptizing opportunity.
A Friend informed me, that accounts have been received,
that the yellow fever has broken out in New York.
Ah, what will the trying thoughts which have impressed my mind respecting home,
of latter months, amount to!
Mercy and truth are with the Lord, and forgiveness, that he may be feared.

"`13th.--An uneasy, painful night; lay much awake, and was tried with many thoughts,
and yet when spreading my trials before my great Helper, received this answer,
'`Have I ever failed thee, or what hast thou lacked?`'
to which my soul was favoured with a degree of brokenness to answer, '`Nothing Lord.`'
Went to meeting,
where my heart was uncommonly enlarged to speak to a state under trial and temptations,
and afterwards sat the meeting of business through, which was largely attended.
Here my heart was again filled with matter to deliver respecting discipline,
encouraging Friends likewise to stand shod and prepared for a day of sifting and trial,
believing even this people will be sifted.
Attended the adjournment at six o`'clock, and sat it nearly through; it was a good time,
the meeting well attended,
and I hope the hearts of some of the young men were
stirred up to move forward in the cause of truth.

"`15th.--Attended a public meeting, and was disappointed in seeing so few gathered,
and more so, in sitting so long waiting for others--the house was not half filled;
however, it was a quiet, and I hope, solid meeting, wherein I got relief among those met.

"`16th.--To an appointed meeting at Sycamore alley,
which was larger than the one yesterday, but the house not full by many:
it proved a solid, good meeting, in which my heart was enlarged.

"`20th.--Went to meeting, which was a season of great enlargement of heart,
and through divine favour, I trust, a baptizing time:
left the meeting-house in much peace; after which,
a number of Friends came to our lodgings,
and here again I had to speak to the states of some present.
Let the praise and honour be rendered to the Lord,
the mighty helper of his poor exercised servants engaged in his work,
and may my soul be humbled.

"`24th, seventh-day,--To the national meeting of ministers and elders, which was a close,
searching time: here I met with my father David Bacon, and Nicholas Wain.

"`25th, first-day.--Attended Heath street meeting, which was large and crowded,
many not of our Society being there.
I was drawn forth pretty largely to preach Christ Jesus,
the word nigh in the mouth and heart,
as the only sure teacher and baptizer in this glorious gospel day.
Attended Sycamore alley meeting in the afternoon, which was likewise large,
and in the fore part I had a short testimony,
but the chief labour fell upon Nicholas Wain,
and trust it was a good satisfactory meeting.

"`26th.--To the national meeting for business at ten o`'clock, which adjourned till four.
Here Nicholas Wain was concerned to speak respecting the fondness to collect manuscripts,
and copying and reading such pieces,
to the neglect of reading the Holy Scriptures and our ancient Friends`' writings.

"`27th.--To the public meeting at Meath street house, where I had but little labour.
Nicholas Wain appeared, also Ann Robinson.
At four in the afternoon met a committee appointed to consider the state of Society,
and also at six o`'clock in the evening.

"`28th.--Went and sat with the committee of the national meeting;
and when the state of Society came closely under consideration,
I felt uneasy with knowing it,
and told Friends that I had endeavoured in my travels
not to be anxious to hear things by the outward ear,
but to attend to the openings of Truth: so I left the meeting,
and Nicholas Wain followed me out.
Attended the burial of Hannah Simmons at ten o`'clock.
There was a considerable collection of people, and I had an open time in communication.
To the adjournment of the national meeting at four o`'clock,
which was solid and satisfactory, and concluded comfortably.

"`29th.--To the parting meeting, which was large and solid;
most of the labour fell on me, and it was a good time: after which,
the meeting of ministers and elders met for the last time, and it proved a solid season.

"`30th.--To meeting in Sycamore alley, where most of the public labour fell on me.
In the evening took leave of my father David Bacon, and Nicholas Wain,
who intend setting off for Cork tomorrow.

"`Eleventh month 1st, first-day.--To meeting;
where I was looking for contentment in silence; but soon after I sat down,
I felt such a flow of love, that I longed for the meeting to be gathered,
that I might ease my mind;
and once more was favoured with a full opportunity in a large meeting.
In the afternoon attended at Sycamore alley,
which I sat through in sweet refreshing silence.

"`11th.--On examination, though with thankfulness I can acknowledge,
that the good hand has been near to help this day,
yet am conscious that more care and circumspection in speech,
less quickness and fewer offhand remarks, would tend to more peace.
When I am off my guard, and slip but a little in conversation, it brings the rod.

"`14th.--I am tried with staying so long in this place; and yet see little to do,
and no way opens with clearness to move, if my leg would admit,
which has been sore so as to lame me.
Spent most of this day retired in my chamber, which was sweet and comfortable.

"`15th, first-day.--Feel much recruited in my bodily powers this morning,
and could say I felt no pain: went to meeting, and my heart was much enlarged,
and my tongue loosened, to the comfort of my own mind,
and trust to the awakening and encouragement of others.
Rode to Sycamore alley meeting, which was pretty largely attended by Friends and others,
and it proved an open time from these expressions,
'`I am a debtor both to the Jew and to the Greek, to the learned and unlearned,`' etc.

"`22nd.--Attended the meeting in Meath street,
which was again an open enlarged time with me, but felt poor after it,
and had thoughts of omitting the afternoon meeting, as my leg by using it,
appeared much worse.
However, I went in a carriage, and a considerable number of strangers being there,
was much enlarged towards them;
one of them came in the evening and acknowledged
that I had been made instrumental this day,
in opening his eyes and removing his doubts;
and that he could scarcely forbear standing up in the meeting to acknowledge it.

"`23rd.--Poor and stripped in mind and weak in body,
but I feel rejoiced that I am made to see myself such a poor creature.
O that the Lord, my heavenly Master,
may be pleased to support through all that is yet to be met with,
both in heights and in depths,
and ever give me to see that the grace and good spirit thus conferred on me,
with the added gift of utterance to speak forth his praise, is not mine but his.
O how great has been thy mercy and kindness to me in this city, thou Helper of thy people.

"`24th.--Attended meeting, which was a sweet silent one, for the most part,
wherein my own family connections and friends at home,
and others came up into remembrance,
when I ventured to pour out my soul in supplication for my own and their preservation,
with the visited children of our heavenly Father in this place.

"`26th.--Whilst sitting alone in my chamber this evening,
I poured out a few tears on looking towards my dear wife, children and mother,
with a secret prayer for my daughter Mary,
who is rising up into the slippery path of youth;
and what can I say more at such a distance, than '`thy will, O Father,
be done,`' whose power and divine presence is everywhere.
Thou hast indeed wrought wonders for me--O that my dear
children may all be remembered in mercy by thee.
Spent most of this day in my chamber, and on the whole it was satisfactory,
and with some comfort and consolation administered, for which I feel thankful.

"`27th.--Was discouraged from going to meeting, in consequence of my leg being painful;
but as J. S. and wife called for me, I ventured to go,
and it was in the fore part a sweet silent one to me,
wherein secret breathings were raised in my heart on account of those left behind,
and by giving way to silent mental prayer for a season,
I was strengthened to bend in public prostration at the footstool of divine mercy,
and after it, felt a language of encouragement to express in the hearing of my friends.

"`29th, first-day.--Attended both meetings, and sat them through in silence,
except near the close of the morning meeting, endeavoured in a few words,
to stir up Friends to a more punctual attendance.
This passage was uppermost part of this day, in meeting;
'`I saw the tents of Cushan in affliction.`'
Joseph Williams observed in the morning meeting, that his state,
when about sixteen years of age, so revived in his remembrance,
that he was fearful of omitting mentioning it in the hearing of that gathering,
nearly I think, as follows: '`A Friend from America was then on a visit to this nation,
who was detained in the city of Dublin for some months,
and laboured from meeting to meeting.
In one of the meetings his testimony so reached his heart,
that it brought him under much exercise and conflict of mind,
which he endeavoured to struggle against and shut out.
Soon after this he obtained leave of his father to go into the country,
and there getting into company with his acquaintances,
he lost much of the savour of this visitation, and on his return back to the city,
was in hopes the Friend was gone.
When he went to the meeting again, he took a seat as near the door as he could,
that he might slip out; but the stranger being there, and being, as was thought,
the last meeting he would attend, Joseph remained, and his state was again spoken to,
and he was told of his trying to flee from his best friend, the Lord,
who was convincing him of the evil of his ways.
This opportunity was a blessing to him, and he said, probably if he had withstood it,
he might not have been favoured again.
He then exhorted some present, who were in the like condition,
not to put away the Lord`'s mercy and kindness to their souls.`'
Dear John Abbott, I thought, had also a sweet testimony to bear.
Returned to my chamber alone, and after a time company came,
but my mind was much shut up under exercise--favoured
to drop the silent tear:--Jesus wept over Lazarus.

"`Twelfth month 3rd.--Set off about daybreak,
accompanied by Samuel Bewley and Robert Fayle, for our guides,
with divers others who went with us a few miles, and lodged at Castle Bellingham.

"`4th.--As John Abbott and I rode along in the morning of this day in the chaise,
we saw a company of people following a corpse into a cabin;
John said he believed he must stop there, and I did not feel easy to let him go alone;
so we left the carriage in care of Robert Fayle, and went into the house.
The coffin was laid in the middle of the floor,
and the house much filled up with men and women talking Irish.
John requested them to be still a few minutes, which they did,
and then began to talk again: he again desired them to be still, but one of the men said,
we suppose you want to preach--we will not hear you,
go out of the house--and they began to push us out.
They pushed me quite out of the door, and in a little time John came out also,
there being a number out doors.
I told them, perhaps they might have heard something to their profit; but was answered,
'`We do not want to hear you.`'
John told them it was a solemn occasion,
and they ought to consider that in a little time they would have to die also,
when the soul must be either happy or miserable, to all eternity.
'`Who sent you to preach?
said one.
I answered, '`Jesus Christ,`' I was then asked, whose successors we were?
and I think I answered, '`Of Christ and his apostles,
and righteous men of all generations.`'
'`You are but lay-men,`' said one of them,
'`and I can pick out of this company those that are better preachers than you.`'
I turned to some of the young men and lads present,
and said I believed the time was coming and would come,
when the children would be favoured to see better things than some of the old men;
for which I was accused as a liar, by an old man.
I observed to them, that our minds were turned in love to them,
that seeing they would not hear us, we would leave them,
which we did with sorrowful hearts, being grieved with such blindness and prejudice.
We got to our friend James Christy`'s after night,
where we met with Anne Taverner and Susan Bewley.

"`5th.--Rode to Lurgan with Anne Taverner to select quarterly meeting at one o`'clock;
it was a close time.

"`7th.--To the meeting for business: the women met apart,
and I got some relief amongst them in both meetings.
A committee was appointed to consider the state of Society,
and the meeting adjourned until four o`'clock, when our certificates were read.
In the evening I felt a sweet calm over my mind.

"`8th.--Met the committee, and had an exercising time in considering the state of Society.
It was proposed to nominate a few Friends to visit the monthly and preparative meetings,
etc., and I felt a necessity to offer myself to join them,
after which John Abbott expressed a similar prospect;
it was laid before the quarterly meeting and united with.

"`9th.--Met the school committee at nine o`'clock,
and went to the parting meeting at eleven, in which I was silent.
Sat with the committee of men and women Friends, in order to see our way to move,
wherein I was concerned to pray for us all.`"

[.offset]
On the 12th, in company with the committee,
they attended the preparative meeting at Lisburn; on the 15th to Mile-cross and Belfast.
18th, to Hillsborough preparative meeting.
19th, to Ballinderry preparative meeting, 20th, first-day, to Lisburn,
and the next day to the monthly meeting.

"`On the 23rd went to Rathfriland, and the next day attended that meeting,
where there were but three men and one lad, and about as many women;
although things looked discouraging, on the whole it was a good, and in some degree,
a tendering time; and on the 26th went to their preparative meeting at Lurgan.
28th, to Moyallen, and in the evening had a conference,
in which our way appeared closed up.

"`29th.--The committee sat down again, and had an humbling, searching season;
and we were not able to see any way to move,
except to appoint the time for the monthly meeting to be held,
as it was adjourned on our account.
Before Friends separated to their several homes, we came together again;
and this was a contriting season, for which my soul rejoiced,
as we were likely to part in love.
In the evening received letters from home,
which conveyed sorrowful tidings of the removal, by the yellow fever,
of several relatives, neighbours and friends;
and that my own family had been visited with the sickness, yet so far,
were mercifully preserved in the land of the living;--my spirit was somewhat eased,
and the contents of my dear Sarah`'s letter were very sweet,
conveying an idea of the calmness and resignation in
which her mind was preserved under the trials allotted.
The Lord be magnified and bowed before, whether in suffering or rejoicing,
sickness or health, life or death; and O that my tried soul may still be favoured to say,
Thy will, O Lord, and not mine be done.`"

[.offset]
On the 4th of the first month, 1796, after conferring together,
the committee concluded to move on.
They attended the monthly meeting at Coothill on the 7th,
composed of seven men and four women; where the queries were read and answered.
On the 8th they collected the few Friends together at Castleshane,
consisting of three women and three children.
On first-day, 10th, were at Grange meeting; and the next day at the preparative meeting.
On the 12th, to Cabarah, where a few families of Friends live in cabins;
in getting there they had to leave the carriage in the road,
"`and the women were conveyed behind the men on horseback,
some distance through the slush, to the cabin in which the meeting was held;
which was a dull, poor time,`" wherein he had nothing to communicate.

"`On the 13th, to the week-day meeting at Grange;
in which my mind was exercised to stand up with these expressions:
'`Hell and destruction are open before the eyes of the Lord:
how much more the hearts of the children of men:`' and that it was not my faith,
neither had I so learned Christ, as to believe that he does all without us;
but that when we have missed our way through disobedience,
we must know a fresh dispensation of repentance and amendment of life,
through the power of the Holy Spirit in the heart.
After dinner went over with John Abbott to T. G.`'s, where we dropped into silence,
and these expressions arose for delivery;
'`Without faithfulness we cannot find an interest in Christ;
and those who have vowed a vow unto the Lord, should pay it,
for the Lord has no pleasure in fools, etc.`'
Pain and distress have been my condition, wherein I might say measurably,
that my God has humbled me among this people.

"`14th.--To Rich Hill monthly meeting.
The queries were read and answered whilst the women stayed,
and I trust some solid and instructive remarks were made for their improvement.
The meeting held until dark,
and then adjourned to the close of one appointed to be held tomorrow.
After dinner sat with the overseers, both men and women,
and imparted such counsel as occurred, and after that, with the two men elders.

"`15th.--Went to an appointed meeting, which was large and mixed;
and I got through it to my humbling admiration.
There was a raw, inexperienced company assembled, some gay people,
and one Highland officer.
After which the monthly meeting concluded its business,
first appointing a few Friends to go from family to family,
and inspect into their condition,
particularly with regard to the testimony against war and fighting;
and to endeavour to persuade Friends to put away all
instruments of destruction and death out of their houses,
in this time of commotion amongst their neighbours;
it appears that several who had joined in those things, and were brought under dealing,
had condemned it.

"`16th.--To the monthly meeting at Moyallen, which was a time of enlargement to me,
wherein I was favoured to relieve my mind, both in the meeting for worship and business,
and things appeared hopeful.

"`17th.--A tossing night; and when I awoke, felt very poor and helpless; however,
I was favoured to put up a secret petition for protection and help before I arose.
Dear John Abbott came into my room to inquire which way I was going,
he inclining to go to Lurgan, and after breakfast I felt easy to go with him.
We got to our friend John Davis`' about a half an hour before meeting time.
In this meeting; I was favoured with much enlargement, to my comfort and relief;
some brokenness appeared.
O how good it is to wait in patience, and depend upon that divine fountain that fails not.

"`19th.--To meeting at Antrim, which was small, and the house was damp,
having an earthen floor: about four men, some children, and seven women,
besides the committee, constituted the meeting, and it was a low time.

"`20th.--Set off pretty early, and rode nine miles to Grange meeting;
five men and four women made up the meeting when
it separated for the transaction of business;
the queries were read, and it was a very low time.
The gallery where we sat appeared tumbling down, and a damp earthen floor.
When the query respecting bearing arms and paying fines for war, etc., was read,
an old woman openly acknowledged, after her husband said he had not paid such a fine,
that she did; and made light of it, concluding it would not stand in her way.

"`21st.--Rode to Ballynacree, and on the 22nd held the preparative meeting.
This meeting-house joins a dwelling, and on sitting down,
it seemed like sitting in a cellar: two men, two women and three children composed it,
besides six of the committee.
My mind was exercised with the low state of things;
but was favoured soon to gain a state of quietude,
when the remembrance of these expressions was pleasant; '`The Lord liveth,
that bringeth the seed of Abraham, or house of Israel, out of the north country,
and every country where they have been scattered;`' and again, said the Prophet,
'`The Lord will comfort Zion; he will comfort all her waste places,`' etc.;
and my soul craved that this day might hasten.
After dinner rode to Colerain, to W. Gregg`'s; drank tea,
and then went to the meeting-house, and sat with him and his brother Dominick and wife,
who are all the members in this town: the queries were read and answered,
and my mind was not so oppressed as in some other places.

"`23rd.--The monthly meeting was held, consisting of seven men and three women;
and in the evening the committee sat down together to prepare a report.

"`24th, first-day.--To meeting; some few strangers came in,--I pitied them,
but had nothing for them: my condition as to ministry in this north part of Ireland,
seems as a book sealed; and I have been, and am favoured with contentment.

"`27th.--To Lurgan week-day meeting, and on the 28th to Moyallen;
after which went to my kind friend Mary Phelps`'.`"

[.offset]
In a letter dated the 29th, from the home of Mary Phelps, he says:

[.embedded-content-document.letter]
--

I am now waiting for John Abbott to join me in going towards the south;
we have been together ever since we left Dublin, in the beginning of the twelfth month,
and have gone through the north part of the island.
I have mourned under a sense of the darkness that prevails;
and when I have looked toward the people at large, feeling, I trust,
a willingness to preach the gospel among them,
I have remembered part of Elizabeth Webb`'s prospect concerning some,
when she had been querying whether the visitation of life and salvation was toward them;
the answer seems to be, that '`the buckets are frozen.`'

There are parties raising up against each other in these parts,
and we hear of their going to houses in the night,
and murdering the dwellers in them--breaking their windows, and undermining their houses,
and ordering the inhabitants to leave the neighbourhood,
and sometimes in open battle against one another;
and the magistrates seem at a loss to know what to do;
but we have travelled without molestation, which is a favour.
I am not much, thou knowest, concerned about informing of outward commotions,
and yet I thought so much occurred,
and things look very serious in this land,--
bringing to my mind Archbishop Usher`'s prophecy,
which if suffered to be fulfilled, will be dreadful indeed.
I have been favoured with some precious open meetings in some parts, as Dublin, etc.,
but truly here in the north, am like a sealed book; many silent ones; but through all,
have had to rejoice in that the great Master has a precious seed preserved,
and which I trust will be watered and made fruitful in due time.

--

Second month 2nd.--They arrived in Dublin, where they remained until the 7th,
when in company with his friend John Abbott,
he set off with a view of taking the meetings of the southern part of Ireland.
They attended the meeting at Wicklow on the 9th,
and in the evening got to one at Ballycane, on the 11th at Ballinsore,
on the 12th to Enniscorthy, and the 13th to Forrest meeting; "`in the fore part of which,
he says, the testimony was close to libertines,
yet was favoured with a portion of oil to the burden-bearers, especially the dear youth;
amongst whom, since leaving Dublin, my heart has been much enlarged,
and in some meetings considerable contrition appeared.
After this meeting, in which I laboured under the heavy weight of an increasing cold,
I rode home with Jacob Gough`'s wife and daughter, in a closed carriage,
and after dinner had a precious parting season offender love,
and I thought dear John Abbott had something precious to say.
He has been mostly silent since we left Dublin, Rode to Ross,
and put up with our friend John Cullymore,
who has been our kind companion and guide from Dublin.

"`14th, first-day.--Attended both morning and afternoon meeting,
in a weak state of body but was favoured with much enlargement of heart in both,
there appearing a visited little company, especially among the youth.

"`15th, second-day.--Rode ten miles to Waterford, and after tea, in the evening,
a large number of Friends came to see us,
and we were favoured together with the breaking of heavenly bread.

"`16th, third-day.--To meeting at Waterford, which was large, and an open time,
though weak in body.
After it to William Penrose`'s, who lives a little out of town,
and dined with several Friends; amongst the number was a youth under convincement,
not of our Society, who appears remarkably grave:
here I had another religious opportunity.

"`18th.--To Clonmel, and put up at the school; the meeting here was a close,
searching time--it being an adjournment of the monthly meeting.
I had afterwards some encouraging language to express in the men`'s meeting,
and then went into the women`'s. We dined at the school,
and had a sitting with the scholars, and then went to meet a committee,
and hope we were made useful to Friends.

"`19th.--I felt so unwell after dinner that I lay down, and was much refreshed.
Drank tea at Samuel Davis`', after which, came Robert Dudley and wife, and several others;
and here we had a good time amongst them.
Mary Dudley appeared sweetly, and my companion also;
after which we had a tendering time with the scholars,
who waited for us with their governors, and divers Friends that came to see us.

"`20th.--Went to Robert Dudley`'s and dined.
Sat down with this family, and had an open time amongst them.
Dear Mary poured out her supplications in the close for the children,
and that the Lord would be pleased to bless our
families with the same blessing hers was favoured with.

"`21st, first-day.--Felt very poor this morning when I arose,
and went to meeting in this state;
but had not sat long before a degree of light and life sprang up in my heart,
and was favoured to minister to a pretty large meeting.
The afternoon meeting was a large mixed one, and I had again an open time.
In the evening sat down with the children at the school, and a large number of Friends,
among whom were many youth;
when I requested some of the children might read
the 5th and 6th chapters of second Kings,
which two of them did, and it afforded me another full opportunity to discharge my mind.
John Abbott and Mary Dudley both appeared,--dear Sarah Grubb`'s remembrance was revived,
and I hope it was a baptizing season, to be remembered by many.`"

[.offset]
Extract from a letter dated Clonmel-school, second month 23rd, 1796, to George Dillwyn,
then in London.

[.embedded-content-document.letter]
--

Indeed I may say,
that my mind has been more at liberty since coming under this roof than for some time:
some precious and memorable seasons we have been favoured with,
both in this large family and with others in this town.
O how sweet has been the remembrance of dear Sarah Grubb; as unknown, and yet well known.
Things are sweet and savoury, and I trust her prayers have been heard,
and are and will be answered.

I have been frequently in company with dear Mary Dudley,
and esteem it a favour to be noticed and owned by such as she,
and other fellow servants in this land.
Very close were my trials in the north; and when returned to Dublin,
and looking towards these parts, it was trying to my exercised mind,
and I think I may be free to say to thee, my brother, that I came forth weeping,
and it was good for me; for having been agreeably disappointed,
my heart has been humbled, and I find it good to trust in the Lord,
and not lean to my own understanding.
We had some precious meetings on the way from Dublin, as well as some trying ones.
There appears to be a number of youth under visitation, and when I meet with such,
either in meetings or families, it is like marrow to my bones As to myself,
I cannot let thee into my secret with respect to returning, if happily favoured to do so:
if I saw the time near, perhaps I might be so free with one,
who several years ago gave me an instructive lesson, and which I have since,
pretty uniformly kept to, and found great profit in it; that was:
'`When thy mind is exercised with a prospect of going abroad,
do not deal it out by piecemeal,
but wait on the blessed Master until he ripen it in thy mind,
and then spread it before thy friends; and if there is life in it,
they will be sensible of it.`'
Happier, I have thought, it would be for many amongst us,
if they knew how to keep their own, the king`'s, and the secrets of others, discreetly.

--

"`24th.--Got to Garryroan meeting in good time, which was a very close, exercising time.

"`26th.--Went to Limerick meeting in a low state, and sat so through the fore part of it,
but through favour was enabled to divide the word to various states present.

"`28th, first-day.--Attended the morning and afternoon meetings at Limerick,
and found much to do in both,
and I hope to some comfort and edification both of Friends and others,
and to the peace of my own mind.
In the evening, as I was sitting at our lodging with between thirty and forty Friends,
I felt sweetness cover my mind: my dear companion laboured amongst them in the fore part,
and I did not know but that I might be excused, but ventured to bow in supplication,
and afterwards was engaged in testimony.

"`29th.--Set off this morning, accompanied by Joseph Harvey and Jeremiah Morris.
Went to Charleville and dined; near this place, in which was once a meeting,
stood the house of the earl of Cork; of which John Exham, a valuable Friend,
prophesied the destruction; but for the kindness the earl showed to him,
he returned and told him the evil should not be in his day: all which was fulfilled,
and I do not find any trace of the house at this time.
In the last stage of our day`'s ride,
we passed through a part of what is called the Golden valley, or very rich land,
where stands the ruins of an old abbey.
In some of the ancient buildings in the town near it, called Killmallock,
is very curious hewn stone work,
and also the remains of a palace of one of the ancient kings.

"`Third month 1st,--Set off early, and got into Cork, to John Morris`' before dinner;
felt stripped and exercised on coming to this place.

"`2nd.--Set off early this morning for Bandon meeting, in which I was shut up in silence;
and afterwards rode back to Cork.

"`3rd.--To meeting, and shut up.
4th.--In a stripped condition, and much so since coming into this place.

"`6th, first-day.--To Cork meeting, and sat some time in silence and poverty,
under an apprehension that too many were looking for words, and when I stood up,
was for some time without words to begin with; and yet, after a close, searching time,
I was favoured to get along in testimony, and relieve my mind pretty freely.
In the afternoon meeting I was again much exercised in testimony, and felt relieved.
After tea a considerable number called in,
and I was drawn forth in testimony amongst them, and took my leave,
the way opening for moving on in the morning.

"`8th.--To Youghall monthly meeting, where I sat pretty long in silence,
and was ready to conclude I should have finished so,
but near the close could not feel easy without saying some very close things.

"`9th.--After breakfast felt a liberty to call and sit with several Friends.
Spent the evening at George Peat`'s, in the house E. Richardson lived in, who,
though not in affluent circumstances,
entertained most of the travellers that came on truth`'s account to this place,
and the meeting used to be held in her parlour: several Friends came in,
and we had a solid opportunity.

"`10th.--To meeting, and it was a pretty comfortable time;
John Abbott appeared in prayer, and afterwards in testimony.

"`11th.--Set off early this morning for Waterford,
and stopped about eight miles on our way and refreshed.
Whilst here I discovered that the iron axle-tree of our chaise was considerably cracked,
and we were detained some time to get it bound up.
At the last stage we found a man and a fresh horse,
sent by John Courtney to put to our chaise, and before nine o`'clock at night,
we got into our old lodgings at this Friend`'s house in Waterford,
where we were kindly received.
Rode this day about fifty English miles.
The accommodations were so poor on the road, that we brought provisions with us.

"`13th, first-day.--This has been a laborious day to me,
being largely exercised in both morning and afternoon meeting,
and two sittings in the evening at our lodgings.

"`14th.--We drank tea at Mary Watson`'s, with several Friends,
and after it I had a full opportunity to speak to the states of several.

"`15th.--Went to meeting, where the labour fell on me, and it was a pretty open time.
Stopped in at William Penrose`'s, and hope it was a profitable tendering season;
after which we went to the widow Ussher`'s, who has three daughters,
and here we had a memorable time indeed.
Very soon after we sat down, tenderness and contrition appeared,
and I admired whilst speaking, to see such brokenness.
Dined at Joseph Hoyland`'s; after which divers Friends stepped in,
and I had a religious opportunity, and another on our return to our lodgings.

"`16th.--Dear Mary Dudley and several others, came and breakfasted with us;
after which I had the servants called in and had a religious opportunity;
then went to the widow Ussher`'s, where I was comforted,
and took an affectionate leave of her and dear children;
she confessed with tenderness to the Lord`'s
goodness in sending his servants to visit them.
After dinner and bidding several families farewell, we rode to Ross.

"`17th.--Went to meeting at Ross, in a low condition,
where I found a considerable collection of other societies,
and amongst the rest Richard Rowe, who had been a priest, but had given up his living;
it proved a good time, and in the afternoon went to see this goodly man,
and was pleased with the visit; he appeared to receive us with gladness.

"`18th.--This morning we could not be easy without seeing another sober man,
who with two daughters, called upon us; and we had a tendering time;
the father and oldest child seemed much broken; the wife was unwell,
but after returning home he sent us word that she would see us,
and we went and had another tender time;
and came away from Ross pretty comfortable in mind.

"`19th.--Went to Killconnor meeting in a poor stripped state;
there was a number not of our Society at it--my companion appeared,
and after him I had a tendering time with some,
though there were others who were cause of grief and pain to my mind.
To this meeting John Cullimore came from his own home,
in order to accompany us to the quarterly meeting at Mount-mellick.

"`20th, first-day.--A night of conflict,
and was very poor and stripped this morning before I arose,
under some painful apprehension that I had not kept the
girdle of truth so close to my loins as I ought.
What a precious thing it is to be preserved tender--in this
state we are favoured soon to see the outgoing of the mind,
and feel a check even in the thoughts.
I went to meeting poor and humbled,
and to my admiration was strengthened to minister to the poor,
as well as to warn the unruly.
After dinner went seven miles to Athy meeting, at four o`'clock.
I had no expectation of seeing so many of other societies, and was in a low state;
however, strength and courage were given me, and hope it was a time of profit.

"`22nd.--Found freedom to send and collect the few Friends together at Timahoe,
and on the 23rd, accompanied by W. and J. Pimm, attended the meeting;
there was but a small company, only two men who were members, and about seven women;
several neighbours came in, to whom both my companion and I had something to communicate,
and after they left us had a close time with such as were members.
One of the members, about a month ago,
was much wounded by a party of men coming to his house to demand arms.
We understand he made resistance,
and one of the balls fired at him lodged in his spectacle case in his pocket.
How happy for those, who in trying times can truly say, I am a Christian,
therefore I cannot fight.

"`24th.--To Rathangan meeting, where a number of strangers came in,
and I had to reason with those present, concerning temperance, righteousness,
and judgment to come, and hope the word was divided to the different states.
Drank tea at Jane Watson`'s, where was a number of Friends,
with whom I had a religious opportunity.

"`25th.--Set off for Mount-mellick, where we arrived before night and put up at J. G.`'s,
Mary Ridgway`'s home.

"`27th, first-day.--A little better in health today,
and ventured out to meeting with muffling up; and very close things occurred to deliver.
In the afternoon meeting was silent,
but had two opportunities in the evening with some youth.

"`28th.--To meeting for business, and the adjournment at three o`'clock,
wherein very close things escaped my lips,
and in the evening was not only much spent but humbled.

"`29th.--To another adjournment at ten o`'clock, wherein my mind was lifted up a little,
and I thought the precious testimonies of truth
appeared to be growing in importance in Friends`' minds.
At five o`'clock went to what is called the parting meeting; in which I was silent.

"`30th.--To the week-day meeting, and was silent.
In the afternoon the select meeting met, the fore part of which was a dull time,
but it ended comfortably, and a minute was made in acknowledgment of the favour;
my heart was in some degree enlarged: went through the schools,
and came home in the evening under a load of exercise,
and in a religious opportunity bowed in supplication; and there appeared a cause,
not only on my own account, but that of others.

"`Fourth month 3rd, first-day.--Although much unwell this day,
yet was favoured to relieve my mind amongst Friends in the morning meeting,
and appointed one for the town, to be held at five o`'clock in the evening:
it was very large, so that the house could not hold the people,
and I trust it was favoured.
The people were solid and still, and remained so after going out.
A number of gay people came and took me by the hand at the close,
and appeared thankful for the opportunity.

"`4th.--Went on towards Birr; stopped at a poor inn by the way,
and refreshed ourselves with some provisions which Friends gave us;
and afterwards had a religious opportunity with the inn-keeper, his wife and family,
to our satisfaction.

"`5th.--To the meeting at Birr, where many strangers came in,
with whom I had a pretty good time.

"`6th.--In the meeting at Roscrea, I was silently shut up;
and in an evening meeting at Knockballymaher, great dullness appeared,
and nothing for me to do.

"`7th.--To the meeting at Mountrath, which was large and mixed;
I was favoured soon to feel that there were some precious plants there,
among whom I had a good time.
John Abbott also had a share in the labour,
and I ventured to conclude the meeting by prayer.

"`8th.--To Ballinakill meeting, which was a time of suffering;
there was a poor little company of Friends, and some few others stepped in;
after some considerable time of silent exercise,
I ventured to prostrate myself and supplicate the Lord to remember poor desolate Zion, etc.
Before the meeting concluded, divers others with some soldiers coming in,
I felt for and addressed them.
After dinner, accompanied by several Friends, rode to Kilkenny.

"`9th.--Arrived at Anner-mills, twenty-two miles.
I feel much recruited in my bodily powers,
and believe I should have felt pleasanter if I had been more watchful last evening.
O what a poor weak and feeble creature I am,
when the divine arm is but a little withdrawn to prove me;
and what state is more safe than a broken contrite one--learn contentment therein,
O my soul.

"`10th, first-day.--Rode to meeting with Sarah Grubb and her sister, E. Pimm,
and was favoured with a relieving time;
and in the afternoon meeting had an opportunity to open the
principles of truth to a number of soldiers and others who came in,
and behaved solidly; then back to Sarah Grubb`'s,
and in the evening the family was called in,
when a portion of the Holy Scriptures was read by the children--a commendable practice.

"`15th.--Surely it is not of him that willeth, nor of him that runneth,
but of God that showeth mercy.
O how gloomy have prospects been of late to my mind! what a poor,
and if it may not be too nearly reflecting on divine Goodness,
what a wretched man I have often felt myself I have cause to be thankful in feeling so,
that afterward the riches of divine love and mercy may be more magnified.
May I then wait and watch in patience; for when the Sun of righteousness shines forth,
these clouds disappear: sorrow continueth for a night, but joy cometh in the morning;
and I am thankful to find a liberty to think and hope so much as this.`"

[.offset]
In a letter written from this place, fourth month 15th, to his father-in-law,
David Bacon, he says:

[.embedded-content-document.letter]
--

"`We have been pretty busily employed since I wrote thee my last,
and I think there is but one meeting of Friends in this nation but what I have been at,
and some of them divers times over.
I have had deeply to feel of late,
the force and truth of the dear Master`'s language to his disciples;
'`After ye have done all that I have commanded you,
say we are unprofitable servants,`' etc., feeling myself often a very poor creature;
sometimes I think, like a vessel that has been beating about in the sea,
and wants refitting.
Well, if I can but be so preserved as to retain my faith in his holy Name,
and to believe that he will yet preserve the little bark,
and trust it again on the waters to the peace of my poor tribulated soul in the end,
and to the praise of his ever excellent name, to whom belongs the praise of his own work,
both in time and eternity,--it is all I desire.
Through holy help I have been favoured to behold
some fruits of fervent labour in this land;
yea, I trust I have seen at seasons,
that the labours of the servants who have of
late been sent into this land have been blessed.
I went to see a widow of considerable note in Waterford, who,
with three lovely daughters have attended Friends`' meetings for some months past,
and paid them two tendering visits.
I have met with nothing in all my travels,
more like what we read of in the beginning of our forefathers`' labours,
than our first visit to this tender family,--though in gay life,
yet to behold the brokenness, even before words were uttered, was to my admiration.

The last time we were at Ross, there came in several goodly people,
to whom I felt the love of the gospel flow,
and after the meeting we visited two of them in their families.
The first was a young clergyman,
who has been so brought under a right exercise and concern,
that sometime back he called his flock together and took leave of them;
informing them that he had not a right commission to preach.
He has given up his living also, and entered into the corn business,
in partnership with a neighbour; he appears under much exercise of mind,
and I thought it was evident he received us with gladness.
The other is a merchant, who, I was informed, had been brought up to the law:
in the opportunity with him he was much broken,
and it was also remarked that one of the children particularly, was much tendered.
O, saith my soul, and all that is living within me,
that the great Lord of the harvest would hasten the day,
when more precious fruits may appear in the earth:
that more sons and daughters may come under this description mentioned by the prophet;
'`It shall come, that I will gather all nations and tongues; and they shall come,
and see my glory.
And I will set a sign among them,
and I will send those that escape of them unto the nations, to Tarshish, Pul, and Lud,
that draw the bow, to Tubal, and Javan, to the isles afar off,
that have not heard my fame, neither have seen my glory;
and they shall declare my glory among the Gentiles.`'

--

"`18th.--Went to quarterly meeting, and had to labour among the men in a close manner;
afterwards went into the women`'s meeting, and had an open time.

"`19th.--Still close and exercising times in the adjournment:
the meeting ended this evening.
When the subject respecting bearing arms was brought before the meeting,
a precious covering was over it; gainsaying spirits were silenced,
and a minute was made to stir up overseers to visit
such as have destructive weapons in their habitations,
and induce them to destroy them;
and Friends are about establishing another boarding school:`'
on the whole it gave me joy and comfort to see that truth and
righteousness are thriving over all opposition in Ireland.

"`20th.--Attended the parting meeting; and though a close and searching time,
I hope it was profitable; dear M. Dudley summed up the exercises in the close,
to my comfort.
After sitting with the select members in the adjournment of that meeting,
which was a season to be remembered, and may my soul be humbled,
Mary took me to Anner-mills in her carriage;
and it was a time wherein we poor exercised labourers
were brought into great nearness and fellowship.`"

[.offset]
After this he proceeded through Kilkenny and Ballitore, and on the 22nd arrived in Dublin.

"`24th, first-day.--I am a poor unworthy creature,
and if again favoured to stand forth in the noble cause of truth and righteousness,
surely it must be of the Lord`'s mercy.
I am looking: and feeling,
in order to ascertain whether way will open after this national meeting,
to return to England.
Sometimes the query arises in my heart,
shall I be favoured to see my dear aged mother in this world?
If not, O that we may be favoured, through adorable mercy, to meet in the world to come,
in happiness and peace.
Went to Sycamore alley meeting; and though it was small,
I was favoured with an open time,
and in the close desired Friends to invite their neighbours to the afternoon meeting;
when we had a large gathering, and though a laborious time,
with some dark spirits to deal with, yet hope it was a time of profit,
tending to exalt the name of Christ Jesus my Lord and Saviour.
In the evening felt easy and quiet in mind,
and as comfortable in body as I could wish for.

"`25th, second-day.--To the men`'s national meeting for business, held in Meath street,
both morning and afternoon, in which I was much engaged,
and felt a fear lest I dealt rather closely with
some who appeared to move in too shallow water.
Consider, O my soul, that thou art liable to temptation!

"`Fifth month 1st.--Meeting for business ended late on fifth-day evening,
and sixth-day was the parting meeting,
and the meeting for ministers and elders,--and my mind
has been so taken up with the service of them,
etc., that I have made no memorandums.
Let it suffice that I have been favoured to travel through; and today, first-day,
attended very large meetings, and much labour has fallen to my share,
and sweet enriching peace is my portion this evening,
which is better than any thing this world can afford.

"`3rd.--To meeting, which was very large, and I had an open time to my great admiration,
considering what an unworthy,
poor creature I felt like when I arose from my bed and went to the meeting;
divers Friends stopped in after meeting, and I had another opportunity.`"

On the 4th he embarked for Liverpool, in company with twenty-five Friends,
where they arrived on the 7th. On the 8th, first-day,
he attended both meetings at Liverpool, and was "`shut up in silent poverty.`"
On the 12th he reached London,
and was kindly received by his friends Joseph and Rachel Smith,
where David Sands also arrived in the evening, and took up his lodgings.

"`15th, first-day,--I went to Grace-church street meeting, and had an open,
relieving time; dined at George Stacey`'s with David Sands,
who attended Devonshire house meeting, and we went to Westminster together.`"
