== Chapter IX

"`1798, first month 1st, second day.--Had a refreshing night`'s sleep,
and feel a quiet mind this morning, though nothing presents as a religious requiring.
Here is the beginning of another year; and O if my life is preserved through it,
that it may be spent to the honour and glory of my heavenly Master, Christ Jesus my Lord.
Came to Joseph Smith`'s and heard that John Wright yesterday fell from his horse dead.
He was at the burial of Foster Reynolds last first-day week,
where I had to sound a solemn warning to prepare for death,
and in a particular manner to the aged.

"`3rd.--Went to Grace-church street meeting low and poor,
but had an arousing testimony to bear to some, and encouragement to hand to others.

"`4th.--Feeling a desire to go to Ratcliff, I gave up to it,
and dear Joseph Smith went with me.
I dropped my tears in exercise, not only on my own account, but for others,
and bent in supplication, and afterwards my line of communication was singular.
O gracious Lord fulfill thy purposes in thy own way and time,
and keep thy servant from falling or letting go
his faith in thy all-sufficient power and love.
Returned home and spent part of the evening in reading
Catherine (Payton) Phillips`' journal to my kind landlady,
and feel rather lightened of my burden.

"`5th, sixth-day.--Attended the meeting for sufferings,
and it was evident that earthly wisdom '`prevailed; may it not be exalted over heavenly:
and yet in the midst, my mind for a small space was favoured with a comfortable calm,
and I saw that a purging time must and would overtake this part of the family.
O how my soul longs, and has done so before in this city,
that ancient simplicity and solidity might be restored.

"`6th.--My prospects of public meetings closed with the last on first-day evening;
and it is some encouragement to find that the
labour in that was not as water spilt on a stone.
A man who sat in the gallery, and for a time was noisy and unruly, went away thoughtful.
He had been a great swearer, but has not been heard to use an oath since,
fn the beginning of the meeting two other men were light and airy, talking, etc.,
but before it closed tears flowed from one of them,
and others expressed their satisfaction with the meeting,
and admiration at the long solemn silence.
The works of the Lord are indeed wonderful and hidden;--Lord,
condescend to continue to be the keeper of thy servant, and open the way,
in thy way and time, and grant me patience to wait for it.

"`7th, first-day.-- I felt very poor and empty on getting up this morning,
but hope I was favoured with a right qualification of mind to beg for help;
'`Give us this day our daily bread.`'
Attended Devonshire house meeting, accompanied by Joseph Smith, which was an open time,
and I requested Friends to invite their neighbours.
A number came in the afternoon, and I had another open opportunity,
and appointed a meeting for strangers on third-day evening at six o`'clock.

"`9th.--I went to Devonshire house weekday meeting, which was a favoured time.
In the evening at six o`'clock, attended a large meeting of other societies held there;
the house was full, or nearly so, and I got through to my own peace and satisfaction.
Mary Stacey and Margaret Allen, were fellow-labourers with me.

"`10th.--I went this morning to Peel meeting, and it was a sweet,
contemplative season in silence, wherein my faith was renewed.

"`11th.--To Tottenham monthly meeting, held at Waltham Abbey,
where Ann Christy came with a minute to visit the families of Friends,
and Susanna Horne and Sarah Fairbank laid a concern to go into the counties of Kent,
Surry and Hampshire, which was united with.

"`12th.--Had a quiet and pretty comfortable time at the Peel meeting,
but nothing further presented with respect to public meetings.
I was in degree astonished on looking over the exercises I
have passed through in the course of one month:
'`I will lead the blind by a way which they know not, and in paths they have not seen.`'
Surely this has been my case--I endeavoured to pursue
my journey into some counties the other side of London,
but found I must turn back, and have been convinced of being in my place.
O for protection and help against the adversary,
and to stand prepared for further openings of duty.
The washing pool and furnace are necessary for such a poor thing as I am,
and I think I need them frequently.

"`14th, first-day.--I thought it right to go to the Peel meeting,
where I had a close testimony to deliver.
I thought I was a poor creature,
but these expressions impressed my mind soon after sitting down in meeting;
'`Let us search and try our ways,`' etc., and felt a willingness for mine to be so,
and endeavoured to examine my own account,
and before the meeting closed was engaged to put others in remembrance thereof,
believing that the accounts of some present were not in readiness,
either inwardly or outwardly, who were too much glued to the world;
and though they loved to hear words, yet it was not pleasant to be searched.
The afternoon meeting was nearly silent.

"`16th.--Went to Devonshire house meeting,
and soon after sitting down my mind became calm and comfortable.
I was concerned to labour in an encouraging line, to my own comfort,
and I hope that of others, particularly the youth.

"`17th.--I went to the Peel meeting, desirous to be in the way of duty,
and if any thing should open towards inviting the people at large, I felt resigned.
It was silent, and my way closed up.

"`18th.--Went to Ratcliff, which was a small meeting,
and I had to persuade some to more faithfulness in little things.
Went to Thomas Horne`'s and dined, and had a serious opportunity with him and wife,
I hope and trust he is growing in the root under deep exercise.
O may he be kept under it the Lord`'s time, and may his companion give up to be his helper.

"`19th.--To meeting for sufferings.
I thought there was a sweetness and solemnity spread in the gathering,
and silent forepart; but it was not preserved and kept to.
I found a time near the close to relieve my mind,
and it opened a door for Joseph Gurney Bevan and George Dillwyn to do the same,
and we were favoured in the close; for which I was thankful.

"`21st, first-day.--To Devonshire house meeting,
which was pretty much crowded by many strangers, and proved an open enlarged opportunity;
several came and spoke tenderly and affectionately to me after meeting,
and one pretty finely dressed but goodly man, taking me by the hand, said;
'`the Lord send forth more such preachers and prosper his work:`' may it be so say I also,
for the praise belongs to him.
The afternoon meeting was put off to three o`'clock--many people came again,
and much labour fell on me, to the spending of my strength and voice.
In the evening I was informed that dear Mary Horne died about two o`'clock.

"`22nd.--A pretty comfortable night`'s sleep; and on waking,
my thoughts were soon turned to my afflicted Tottenham friends,
and hearing of an opportunity to go and see them, I embraced it;
nothing opening in London, I have concluded to stay,
my voice being much gone by yesterday`'s exertions in part,
and with the remains of a cold.

"`23rd.--Had a wakeful tossing night;
doubts and fears accompanying my weakness and infirmities,
and I feared some of them prevailed too much, for which I was much abased.
Had an opportunity with the surviving parent and all the children after dinner,
but in much weakness, and I could hardly speak.

"`24th.--Tears were my meat this morning on rising from my bed, with strong cries;
clouds of distress gather about me,
and nothing short of omnipotent help can preserve me to the end.
O how empty and poor I feel yes, such was my exercise,
that I was ready to look on myself as vile,
and yet I may not reproach or reflect on my Divine Master.
Silence, then, ye troubling thoughts, and may my soul possess a calm,
more so than has frequently of late been experienced,
and be found yet a learner in the school of Christ, which only fits for gospel ministry.
I spent a part of this evening in reading a work,
wherein I found this remark on a passage of scripture, that took my attention;
'`Then did they spit in his face and buffeted him;
and others smote him with the palms of their hands:`' Matthew 26:67.
This is incontestable truth;
he who is now sitting at the right hand of God; he whom all the angels adore;
he who could say, '`behold, at my rebuke I dry up the sea,
I make the rivers a wilderness; &hellip; I clothe the heavens with blackness,
and I make sackcloth their covering,`' Isaiah 1:3-4,
fulfills the words of an ancient prophecy; '`I gave my back to the smiters,
and my cheeks to them that plucked off the hair:
I hid not my face from shame and spitting.`'
'`He whose name is unutterable, suffered himself to be ill treated,
in the most shameful agonizing and disgusting manner, by the meanest wretches,
and he was silent: no ray of his omnipotence struck his creatures dead.
He concealed the power which created worlds.
What feelings suffice to adore in a proper manner the greatness of that divine virtue.`'
I admire at the way in which I go shut up here from day to day.
My voice is much gone in consequence of a cold, and exertion of late in speaking.
When I examine and look back,
I cannot find that my mind has shrunk or turned away from revealed duty,
and yet what fears and cares accompany me lest
the truth should be evilly spoken of by my means.
This family is in a state of mourning,
and I am comforted and instructed in seeing and feeling such quiet,
and such tenderness manifested to the surviving parent, who is preserved calm,
and I hope resigned to his allotment.
O may the Lord prepare to open the way for me a poor servant,
and grant me a sufficient portion of faith and
patience to endure what may yet be to come.

"`25th.--My cold and sore throat are better,
and I feel measurably resigned to my present state;
nothing opens but to attend week-day meeting here to day,
and wait to accompany the remains of my friend to the meeting on first-day next.
In her life time she owned me for a child,
and as a mother sympathized with me under my trials, and her memory is precious.
O that all her children may walk in the truth,
and in the end of time close their days in peace.

"`26th.--I spent my time to day in extracting some parts of holy scripture.
Afterwards walked in the garden for health and meditation;
I thought if there is nothing in such stops as this,
surely then my faith and hope in the divine arm are vain: I cannot, I dare not,
give up to believe so.
O then grant me patience, with all other necessary virtues to endure; for thou only,
O Lord, canst turn my wilderness into a fruitful field at thy pleasure.

"`27th.--One word dropped last evening was an affliction to me.
If for every idle word which man shall speak he must give an account,
how awful is the reckoning.
O that I could arrive at a more fixed habit of righteousness and purity of heart;
for blessed are such, they shall enjoy greater union and communion with God.
What are words or such memorandums as these, but as mementos to look back at.
They are made in much simplicity, sometimes, it may be frequently,
not remembering what passed yesterday, or not looking back to ascertain.
I desire to be more industrious,
and improve the time in these stops from travelling and ministerial labour.
Singular indeed have been the stops and stays I have experienced in this land,
and even in this house.
O Lord, break or loosen the chain that has held me; not in my time and will,
but in thine; and preserve my poor soul from sinking under the temptations,
conflicts and trials that have so long been permitted to assail.
O Fountain of mercy and life,
didst thou not enable thy servant when leaving
that comfortable dwelling thou affordest me,
parent, wife and children, and all,
to follow thee whithersoever thou mightest be pleased to lead,
and into what thou might be pleased to appoint--O then forsake me not.

"`28th, first-day.--I rose with more calmness than some times of late.
After breakfast walked the garden until some of the relations came to attend the burial;
I followed the remains of the deceased to Tottenham meeting,
where my mind was exercised and impressed with weight which soon ripened into duty,
after sitting down amongst a large company.
The language of our Saviour to those who did not understand what the
woman was doing in anointing his head with the precious ointment,
was presented as the subject to begin with, viz; '`Why trouble ye the woman,
for she hath wrought a good work upon me.
For in that she poured the ointment on my body, she did it for my burial.`'
What a small service is acceptable when performed in sincerity,
though at the same time with a trembling hand and heart.
I saw no opening after meeting to go to the ground in Southwark, but returned home,
where I found the husband and daughter Martha.

"`29th.--A great favour I thought to feel so quiet and
such a degree of renewed comfort extended;
my mind was gathered into a calm this morning.
I record it as a favour thus to feel,
and yet do I not fall short of that resignation which receives all
dispensations with becoming cheerfulness at the hand of the Lord.
O, I hope, I trust, my soul has been secretly supported above murmuring or repining,
though it is trying to walk in darkness and see but little light.
Praise the Lord, O my soul, through all, and forget not the benefits bestowed.
As I walked the garden after breakfast,
a prospect was renewed which had fastened on my
mind in a time of prostration in my chamber,
viz. to join company with those females (Susanna Horne and
Sarah Fairbank) and begin where they left off some weeks ago,
and lay the prospect before John Bevans to accompany me.
My heart leaped for joy within me in the prospect of a way opening into further labour,
because he that laboureth, or reapeth,
receiveth wages and gathereth fruit unto everlasting life.
May my soul delight in doing the Lord`'s work so long as strength and faculties permit,
and until the great Lord of the harvest may be pleased to say it is enough.

"`30th.--The same prospect opened as yesterday morning on rising,
and I left my chamber more cheerful.
My soul craves preservation through all, and that I may not be permitted to mar the work.
Went to town, and on going to Devonshire house meeting, found my friend and neighbour,
William Savery, there.
It was a silent meeting--went with him to Joseph Savory`'s and dined.

"`31st.--To Grace-church street meeting; dear George Dillwyn, I thought,
had a sweet time, and I ventured to prostrate myself in prayer, and my faith was renewed.

"`Second month 1st.--Felt content at home,
when I received letters from my dear wife and mother.
They were of an old date, but enclosed in one from my son, dated first month 1st,
acceptable tokens of remembrance.
In the afternoon accompanied by Joseph Smith, went to the burial of the widow Perry,
and had to hand forth a little in much weakness.

"`4th, first-day.--Went to Grace-church street meeting,
and again was exercised in a very close testimony to the great and gay, etc.;
after afternoon meeting, in which I was silent, went to a burial in Bunhill Fields,
and felt an exercise while standing at the grave to address the children,
a number of whom were there.

"`5th.--Much exercised this morning whether to go with George Dillwyn to Chelmsford,
etc.,
or move on towards Rochester with Susanna Horne and Sarah Fairbank After a
time of conflict and going through a little piece of mortifying service,
though there was but little time to get ready,
yet by setting about it in earnest I soon accomplished it,
and set off about two o`'clock with them and William Forster,
and got into Rochester between nine and ten o`'clock, a distance of thirty miles.
I put up at my old quarters, Dr. Cowper`'s, and the women at William Rickman`'s;
still under much exercise and depression of mind.

"`6th.--Attended the monthly meeting,
and my two friends I thought spoke to the state of the meeting,
and it was my lot again to sit in silent conflict,
but before the business was concluded I laboured amongst the men.

"`7th.--Our women inclining to goto the week-day meeting at Canterbury,
and two chaises being provided, I drove one and Richard Weston the other;
we had a very fine warm day, and got to William Elgar`'s a little after night,
and were kindly received.

"`8th.--Was favoured with a degree of sweet calm in the morning before I rose.
Attended the week-day meeting, which was very small,
and I laboured among them in poverty as well as I could.
Sarah Fairbank had a short testimony, and Susanna Horne closed in prayer.
I hope it was a meeting to some profit, or may prove so in days to come,
if the fault is not their own; returned to our quarters and dined.

"`9th.---Rode back to Rochester twenty-six miles,
and soon after arriving John Bevans came, in order to accompany me.
In the evening dropped into silence, in which I ventured to labour amongst the company,
and in particular, was turned toward a young married couple.
Ah! how very poor and stripped I feel of later days,
and admire that any good thing should arise out of it.

"`11th.--Sat the morning meeting silent; my two sisters laboured in a close manner,
but I sat in usual poverty.
Dined at William Cooper`'s, and afterwards we all stepped in to see T. White and daughter,
and my mind was so clothed with sympathy as not to be easy without expressing it.
Soon after I sat down in the afternoon meeting, a thought impressed me,
that perhaps I might soon be enabled to relieve my mind amongst Friends,
and then desire them to go to the dock yard and invite the people there,
and others to come; but I had to conflict with my exercise a considerable time.
O how my own infirmity came up and stared me in the face,
and it was hard work to get at any thing.
At last I ventured to labour, and that in a close line for the most part,
with some encouragement to the visited ones; and also with the children:
this meeting held late.
Drank tea at R. Horsnail, Jr.`'s, and afterwards went to the school,
where I had some communication to the boys; but that which gave me most ease of mind,
was what I had afterwards to say to the female servants in the family,
who came and sat with us,
together with a tender young person who keeps shop for William Horsnail.
O Lord, if it is thy will that I should go on further,
be pleased to accompany me and bear up my mind,
and preserve it subjectly given up to thy will, through what is yet to be met with.
O that of living without carefulness, as the lilies of the field grow,
and to depend on Him who feeds the ravens: what greater blessing!
I sometimes endeavour to encourage others so to do,
and yet how poor and feeble in my own particular.

"`12th.--Set off about seven o`'clock, and put up at William Marsh`'s at Folkstone,
soon after which, came in Joseph Elgar, his sister, and several others,
with whom I had a religious opportunity,--pretty open.

"`13th.--To the monthly meeting, in which my mind was opened and enlarged in testimony,
and found work also in the business part, I hope to some profit.
In the evening had one for the neighbourhood, which was largely attended;
and after sitting about two hours in silence,
I stood up in weakness and poverty and laboured amongst them.

"`14th.--Friends were so kind as to send us to Dover in a post chaise.
After dining at Richard Baker`'s,
a number of us took a walk along the sea shore as far as the castle, etc.
I feel poor and oppressed, although I am in a sweet family and comfortable as to them.
How often is this language uppermost, and is it not necessary for me:
'`Wash me in the laver of regeneration.`'

"`15th.--I have a pleasant lodging room next the sea,
and some serious reflections impressed my mind this morning.
I remembered what S. C. says concerning outward defence and armies;
and on mentioning it to my host, he told me he often thought of it.
Went to meeting, and I sat in silence nearly or quite two hours; my female friends,
Richard Baker and daughter Mary, with William Rickman, all had communications;
and at last I stood up with a few expressions, comparing myself to Obadiah,
who fed the Lord`'s prophets in a cave,
and my condition seems like going into a cave to visit the honest seed which lies hid.
My mind was pretty much opened and enlarged, and the meeting was in a comfortable,
solid state, and I hope ended so.
Dined at Richard Baker`'s, and felt poorly after dinner.
O that I may be preserved worthy to have the divine will accomplished in and by me,
in what may yet be to come.
My way home in the right time, is what my soul seeks and craves at the divine hand,
as has in mercy been granted in former journeys in the land of my nativity.`"

[.offset]
The following is an extract from a letter to his wife, dated;

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Dover, Second month 16th, 1798.

[.salutation]
My dear,

The sympathetic feelings expressed in thy last letter were comfortable,
and there is yet reason to continue them,
as my path still differs from most of my fellow-labourers in this land.
I went as far north as I could see my way with clearness, and it was admirable to me,
that in attending the two quarterly meetings at Kendal and Cockermouth,
I felt such enlargement of heart,
that it appeared pretty clear to me I should not
be required to visit all the particular meetings;
and so it turned out.
After those meetings were over I felt quite easy
to go towards London and its neighbourhood;
and with thankfulness I may acknowledge, my way was made prosperous,
and in some places I experienced much enlargement;
but on approaching the before mentioned place,
I thought it seemed like going down again into suffering; and may I not add, into death.
My last letter, by Mary Pryor, was written at her house.
She was in London waiting to embark; and while there I experienced a season which,
amongst many others passed through, is worthy to be remembered.
From thence I passed into Essex, to Chelmsford, thinking to have a meeting there,
it being the only place in that county where I omitted
having a public meeting when I visited Friends;
and here again I missed my aim, and felt easy to move on without it for the present,
a little circumstance turning up that put it by.
We crossed over the river Thames at Gravesend, and rode after night to Rochester,
about seven miles, and about thirty from London,
and put up at William Cowper`'s. I had thoughts
of going on to the further end of this county,
to places I have lately been at, but my way closed up.
I was in a low, exercised state, and remained over their first-day meetings,
and until the middle of the week following,--silent in the meetings, and shut up.
At length way opened to go back to the great city,
into which I entered under a load of conflict,
but was kindly received by my dear friends Joseph and Rachel Smith.
Here I spent several days, and hearing of the burial of Foster Reynolds,
about ten miles out of London, my way opened to attend it.
The corpse was taken into the meeting-house, and after being shut up,
in meeting after meeting, for several days,
I was favoured with what I thought rather a powerful opening,
to reason with some as Paul did with Felix;
and afterwards obtained much relief in an opportunity in the family of the deceased,
and felt very calm, with much sweetness of mind in the evening.

A few days after came on the quarterly meeting for London,
which I felt my mind pressed to attend, and trust I was in my place.
Since then I have been carefully feeling my way to appoint public meetings in London,
a service which never opened before; and in several places I have been helped through,
I trust, so as not to dishonour the cause.
Thou wilt find by mine by Mary Pryor, that I had been spending some days at Tottenham,
my kind friend Thomas Horne having been, in the apprehension of the family,
near death`'s door.
I found him on the recovery, and indeed I did believe he would be restored to his family,
and told them my thoughts, but with respect to his dear, weakly wife, it was hid from me.
She appeared uncommonly well during his illness, and after that flagged and failed,
and slipped away almost at unawares from them, but I trust as a shock of corn fully ripe.
She was a sympathizer with me in my exercises, and I loved her;
and it fell to my lot to be at her burial, first month 28th.

I had this prospect of visiting Kent, etc., when at Sheffield,
and have made the second attempt to do so.
I am now in company with Susanna Horne and Sarah Fairbank,
who had mentioned their prospect to the monthly meeting,
of going this journey into the counties of Kent, Sussex and Hampshire,
before the decease of Mary Horne.
We have been to several meetings together;
and whether I shall go any further than through this county,
and then return back to London, I cannot see at present.
Things are very low in some places, and my mind is low also,
and I have been comparing my state to that of Obadiah,
whose work was to feed the prophets in the cave.
It is trying work to go as into the earth, and into caves and rocks,
but I labour after a qualification daily to say, '`Thy will, and not mine be done.`'
I have John Bevans, the Friend at whose house I made my home last winter in London,
when visiting families, as a companion, who is a valuable elder of Peel meeting.
I am now at Richard Baker`'s at Dover,
and while taking a walk before breakfast this morning along the sea coast,
I could see the French shore, and my mind was pretty strongly turned towards home,
but there is a great sea between us, and so I must try to bound my thoughts,
and bear with patience the painful conflicts that will arise.
O that it may be with becoming patience, considering that if it is the Lord`'s will,
he can as safely conduct me back, as he brought me here;
whose will is our sanctification,
and unto whose almighty protection and help I am desirous of commending thee,
my dear wife, my aged mother, children, relations and friends,
who am thy exercised and oft tried husband,

[.signed-section-signature]
Thomas Scattergood.

--

"`17th.--I felt in a low state this morning, and saw no opening to move this day.
We dined at Deborah Beck`'s, and had a religious opportunity,
in which I had divers things to express to different states, from the aged grandmother,
to the grandchild, and was also turned rather particularly to an apprentice.
I felt some liberty last evening and this morning,
to give some account of my travels in America, with a degree of cheerfulness attending;
and I think dear Richard Baker is considerably raised out of a very low state,
in which we found him.
Saw this afternoon a fleet of upwards of one hundred vessels off the harbour,
going down the channel.

"`18th, first-day.--Bonds and afflictions still continue to await me.
I heard yesterday that my friend and brother William Savery is
likely to go for Liverpool in less than two weeks,
in order to embark for home.
I see no opening, and very little ahead in this land,
so after endeavouring to lift up my soul in prayer to God,
not to be forsaken in the midst of the trials and temptations I have to conflict with,
and for ability to cast myself on the mighty Helper,
whose providence is extended over the whole earth, I arose under exercise; cast down,
but I hope not forsaken.
Went to the morning and afternoon meetings, and laboured in both,
as also did my fellow helpers:
spent the evening at home--a number of Friends
came in and we had a religious opportunity.
My companion told me that there was at meeting on fifth-day last,
a person who had been heard to say, that he could make Scripture;
and in the course of my communication I made use of the same expression,
signifying the possibility of getting into such a depraved state,
as to be bold enough not only to deny that good book, but even to speak on this wise.
I had to labour to dissuade another from the spirit of war and fighting;
he was closely spoken to, and his condition opened.
Yesterday was a laborious one, and close work.

"`19th.--I have had close exercise in this place,
but my little room next the sea has been in degree like the prophet`'s room.
My body has been refreshed, and this morning my mind also, in good degree.
After breakfast Richard Baker had the two women and I apart,
and handed forth some seasonable advice to those young plants to encourage them;
and I had a good time on parting, mostly addressed to Richard`'s wife.
We stopped at Sandwich to dine, and arrived at Margate before night.

"`20th.--No way opened towards a meeting, so we visited all the members in their houses.

"`21st.--Felt so poorly this morning that I thought of lying in bed,
but I struggled along, and after breakfast we had a sitting,
in which I was engaged in a very close line, and again before we set off,
in an encouraging way to three of the widow Newby`'s children:
I felt great relief of mind.
The ride of seventeen miles to Canterbury was a sweet one to me.
O the works of the Lord are wonderful!
Last evening I admired that I could not relieve my mind in the widow`'s family,
and this morning several of the children were cast in my way.
So it was with regard to two other states, and they were also brought in my way.
When I met with J. Newby at the burial of Samuel Spavold, she was in much gaiety,
as her sisters now are, and now she appears to be an ornament to society;
and I hope her next sister is coming on in her footsteps.
Went to Ashford, fifteen miles, and arrived a little after night.

"`22nd.--There was but a small company at meeting: I stood up first,
and addressed some aged persons present,
with desires that they might be ready to give up their account when called for.
Susanna Horne had a good time, much in the same line,
and Sarah Fairbank was concerned in supplication.
Afterwards I requested that such as were not members would withdraw,
and had something for the younger class; and again desiring a further selection,
I got pretty fully relieved.
To the meeting this morning came T. F., about thirty years old,
who some time after the expiration of his apprenticeship entered into the army,
and was disowned by that meeting.
He was also with us in the evening,
and all of us were favoured to hand forth instructive remarks to him.
He put a letter into my hands this morning,
from which it appears that he is under great exercise of mind,
and says I was favoured to find him out in meeting and in the sitting afterwards.
My soul craves that he may be favoured rightly to get through his present conflict,
and in days to come make a valuable, useful member of society.
Yesterday and last evening I endeavoured to feel my way
respecting going into a neighbouring county,
remembering the exercise I passed through previous to entering this;
but as my divine Master has favoured with evidences of being right so far,
I felt encouraged to proceed into Sussex, and this day am pretty comfortable.

"`24th.--We set off between eight and nine o`'clock, and a more stormy,
rainy ride I have not had, I think in this land: put up at Richard Rickman`'s, Lewes.
In the afternoon my prospects were more clouded,
but on the whole am pretty comfortable this evening.

"`25th,
first-day.--Went to meeting and found it was the
day on which they hold their preparative meeting,
and have no meeting in the afternoon.
I have been concerned about the practice of holding such meetings on first-day; however,
I thought it right to endeavour to see it out,
and as I felt nothing to communicate in the first,
I proposed that men and women should sit together,
and hear the queries read and answered,
as it was previous to quarterly and yearly meetings.
I sat pretty quietly until that concerning plainness, etc., came on:
the clerk made a modest answer,
but one or two whose appearance did not strike me pleasantly, even to the outward eye,
proposed that it should be more full, and say, generally careful.
I felt much on this occasion, and indeed before,
and had to query who there was amongst them that looked like Friends,
with more of a very close nature.

"`26th.--To breakfast with S. C. and had a sitting with her and two daughters;
both our female Friends had a pretty full opportunity,
and I had also to address one of them in a few words.
To S. R.`'s, where Sarah Fairbank had most of the labour; after the opportunity was over,
she said she felt, comfortable, etc.;
which afforded me an opportunity to tell her that I wished it was otherwise;
for how could any rightly concerned Friend feel comfortable,
when the walls and gates of Zion were laid waste, as in this place.
To C. S.`'s, where much ignorance and rawness appeared; but I was enjoined to be tender,
remembering the words of the Apostle, on some having compassion making a difference.
To J. R.`'s, where we dined, and had an opportunity: the labour fell on my two friends.
O the stripped state I have been in today;
so mournful and heavy that I could have broken away
from my company and gone into the fields alone,
to pour out my soul.`"

[.offset]
In a letter addressed to his son, dated second month 27th, 1798, at Lewes, he says:

[.embedded-content-document.letter]
--

I am labouring along in much weakness, and perhaps I may safely add,
at seasons in fear and trembling.
Things are very low in some places, and I have to go down as into the grave;
yet in some others, there has been a happy resurrection into life, and sweet peace,
and my soul is thankful for the preservation experienced so far.
May thou, my dear son, increase in the increases of thy heavenly Father`'s love,
is the desire of thy father.

--

"`28th.--Went to meeting, where I was shut up in silence.
Rode to Brighton to John Glaisyer`'s,--felt more comfortable on the road.
We had a sitting after supper, in which I had considerable to communicate,
and felt love to this family, and liberty and ease in it.
We walked to see the sea by moonlight, which was a very beautiful sight.
This town is situated on the bank near the sea.

"`Third month 1st.--We all took a walk before meeting along the sea-side.
It was a pensive and mournful one to me: at meeting all of us were silent.
Several Friends dined with us, after which I broke away and strolled along the sea coast.
O me, what a walk!
The Lord hid his face, and my soul was troubled.

"`2nd.--I am upwards of three thousand miles from my family,
and a wanderer in the fields, to seek relief,
by endeavouring to prostrate myself before the Lord.
I took a solitary walk before dinner, and felt no opening to go into the families,
or to appoint a meeting.
How am I wrapt about with darkness and sorrow, and can have little delight in what many,
it is to be feared, freely indulge in, at this place so noted for pleasure.

"`3rd.--I omitted to mention that last even we sat in John Glaisyer`'s family;
he being in the practice of calling them together and sitting down with them,
two evenings in the week.
My companions had something to offer, and I was glad of such a quiet opportunity.

"`I arose this morning under exercise, and after breakfast set off,
accompanied by John Glaisyer and rode to Arundle, twenty miles:
put up at the widow Sarah Horne`'s. I laboured after resignation on the road,
having endeavoured to see and feel my way to this place before I set off.
May I be favoured to bear with patience the burden that continues on me,
until it be removed, for I do not see that I can remove it.
'`All the days of my appointed time will I wait, until my change come.`'
What could afflicted Job do better than to form such a resolution as this.
Soon after getting into this place, John Bevans and John Glaisyer and I,
took a walk along the river, and on our way home went into the castle gate.
This is the castle where Mary Penington`'s first husband was ill, when she went to him.
Soon after we got into the yard we met the owner, the duke of Norfolk,
who behaved very courteously, and bid his servant show us inside the house, etc.
I informed him where I came from, and he took me to see a stuffed moose,
which he said came from my country.

"`4th, first-day.--A night of labour and some pain.
I thought myself a poor creature on awaking,
having little or no prospect of being favoured
to do any thing this day in a religious way;
however, endeavoured to wash and anoint.
It was the time of their holding both the meeting of ministers and elders,
and also the monthly meeting; the first began at nine o`'clock,
and held until near eleven; the monthly meeting began at eleven, and held late.
There was some opening to labour in both;
in the forepart of the second meeting a number of town`'s people came in,
and after Sarah Fairbank had addressed her fellow professors,
I felt my mind drawn forth in love to the others;
and as she had mentioned the situation of Naaman, I believed it right to revive it again,
and hope to some profit.
They behaved solidly, and Friends were desired to stop, both men and women,
and I thought Susanna Horne had a good time amongst them.
John Bevans and I also laboured, I hope to some profit, in the business part,
and the meeting ended well.
Dined at Sarah Horne`'s with a considerable number of Friends,
and was favoured afterward with a conspicuously baptizing time.
This was cause of admiration to me, who for days past have been so wrapt up as in a cloud.
O Brighton! shall I soon forget my feelings, my humbling, bitter feelings in thee?

"`Went afterwards with the company to see Tryphena Halloway,
a widow near one hundred and two years of age.
She had just gone to bed, but we were admitted up to see her,
and I was glad to find so much sensibility,
and such a thankful heart for favours received.
It was to my admiration,
and a treat to me to sit by such a fellow pilgrim so far advanced in age.
It is said she well remembers William Penn.

"`5th.--Went to Chichester, accompanied by John Glaisyer,
where we attended the burial of Mary Heath, who lived in Friends`' meetinghouse:
after the corpse was laid in the ground, Friends retired into the meeting-house,
and it was pretty much filled up with people of other societies.
Soon after we were gathered,
I thought there was a silence and degree of solemnity prevailed,
and Susanna Horne appeared in prayer,--Sarah Fairbank in a lively little testimony.
Afterwards much unsettlement appeared, and my mind was plunged very low,
perhaps in part on my own account, and partly for the people.
When we broke up the meeting,
with much feebleness I requested the little company of Friends to stop,
and I hope it proved a time of baptism.
We dined with James Hack, Sr., and after dinner my mind was again engaged to minister;
and I thought if it was a living bud or branch,
it sprang up suddenly out of the dry and barren ground.
This is a mystery; that I should at times feel, in my own apprehension,
so wretched and miserable, loaded with, or surrounded by temptation,
and yet be made instrumental to bring others into tears and tenderness.
Well, the Lord have the praise of his own work.

"`6th.--My heart is measurably thankful for sustaining help to carry me through,
and bear up my drooping mind over all the conflicts yet to be met with.
This one day more may bread sufficient to keep alive,
and a little portion of peace be my lot;
and O that the same may be the portion of all my companions in labour,
and that we may be safely directed in the work we are engaged in,
whether to go forward or back, whether to stay together or separate.
We went to see all the families in this place,
and my mind is more lifted up above my trials than I have experienced for some time past.
In some families we had pretty close labour.

"`7th.--Went to Brighton to the monthly meeting.
On the road I lagged behind, and had a quiet, thoughtful time.
It is the day appointed for a general fast, so called,
and for humiliation for the sins of the nation;
but to me it is a little like the lifting up of the head; I have had many fasting,
humbling seasons since coming into this land.
The just are to live by faith: O that I may yet be favoured to live by a measure thereof.
Very little pleasant bread have I eaten for three years and upwards,
and it is good to be content,
well knowing the Almighty can cause a change of feelings at his pleasure;
he can change the dispensation as a water course is turned in a field.
O for watchfulness and care in stepping along,
that the divine will may be done in and by me, a poor, unworthy servant.

"`We got into Brighton before night; put up at John Glaisyer`'s.

"`8th.--The monthly meeting was very small:
I counted about twelve men after the women left.
At the close I felt a little matter to arise, and stopped those who were going away;
it was staggering work, but a little increase of strength was given me,
and there appeared to be an increase of weight:
after I had closed Susanna Horne had a pretty good time.
Things are very low in this place, and we endeavoured to lend a helping hand.

"`9th.--Took a walk to the sea before breakfast and feel refreshed:
we proposed setting off for Horsham, but our friend Susanna Horne is poorly.
After breakfast felt so much love to spring up towards William Savery,
as to induce me to sit down and write to him.
Took another lonely walk along Brighton shore,
in which my thoughts were turned over the sea,
and my soul craves the continuation of the protecting power and providence of God.
Man knows not my tried state; and when I view it,
I am brought into a degree of trembling,
and were it not that the fountain of mercy remains open to wash in, I should fail;
but of late I have remembered the promise made me on setting
off on this journey as a little inward intimation.
The remainder of this day I thought but a broken one.
John Glaisyer sat down with his family in the evening,
and a number of neighbours came in, but to me there appeared neither dew nor rain.

"`10th.--We all set off accompanied by our kind friend John Glaisyer as guide,
to Horsham, twenty miles.
I seemed refreshed in my body with the ride, but it has been a dull time otherwise,
since making the above note on the sea shore.

"`11th,
first-day.--I fear that I let my tongue go too freely in conversation last evening,
considering my state.
What need of watchfulness, circumspection and care!
I hope my mind has been measurably prostrated this morning.
Ah!
I should faint and fall if the Lord helped me not secretly.
Dare I lift up mine eyes and soul to him?
O yes!
I must not, dare not, forbear doing so.
Attended both meetings, and sat them through in silence:
my companions laboured in the morning: I went in a low condition,
particularly in the morning, and found there was nothing for me to do.
I remembered my parting from my home, and my strippings since,
and I wet the floor with my tears.
Well, my soul desires to lay hold of the Lord`'s promise,
to be with and support my wife and bless my children--to help me,
even though it may be through the correction of his rod, in this land,
hoping and believing that the staff also will not fail in time of need.
Drank tea at W. D.`'s, where my companions had close communication,
and I feared wholly to omit labouring also: came home and felt rather more easy.

"`13th.--From Horsham to Ifield, twelve miles; put up at W. T.`'s, a baker;
both he and his wife are concerned Friends.

"`14th.--Walked to Ifield meeting; the select meeting began at nine o`'clock,
and the monthly meeting at eleven.
I found some openness to labour in the first,
and also when I sat down in the large meeting-house,
my thoughts were turned to look back and remember the
state of society in the coming forth of Friends,
and afterwards, and I had to mention it.
It proved to my admiration a pretty open time.
We laboured honestly in the business part, and on the whole felt easy.

"`15th.--Set off about ten o`'clock, after a sitting with the family where we lodged,
and arrived at Brighton before night, having rode twenty-seven miles.

"`16th.--Feel much recruited in strength this morning.
Our beloved Susanna Horne is poorly, and nursing her cold,
which she has been troubled with for some days past.
Here we are again at Brighton.
We sat with the family in the evening, and I was glad of having a little time of quiet.

"`17th.--I took a lonely walk along the sea shore,
and from thence up a valley between the hills, and had a pensive, thoughtful time.
Humbled in examining my accounts, yet do not feel condemnation,
as though any religious service had been omitted.

"`18th, first-day.--Many Friends attended the meeting, and it was filled up with others:
my way closed up in silence, not of the pleasantest kind.
After dinner had an opportunity with some young people, which proved a tendering time.
Went to afternoon meeting at three o`'clock,
and after sitting until I thought it was time to conclude,
looking over the meeting and seeing how thickly the people stood,
and with what patience and quiet some behaved, though others were light part of the time,
my heart yearned towards the goodly ones, and I was not easy without expressing a little,
which little made way for more, and I hope it was to profit.
The select meeting was held in the evening at seven o`'clock.
This was a very searching time, and very close expressions escaped my lips.

"`19th.--To quarterly meeting, where many strangers attended;
in the early part Susanna Horne had some lively communication,
and I was ready to conclude it would have fallen on me to continue the labour,
but it died away.
Sometime after T. Summer stood up,
and after he had closed I wished Friends to go to the business,
for my mind seemed pressed down,
and I looked to get relief amongst them when more select, which I was favoured to do,
though in a very close way, both in the men`'s and women`'s meeting, and I trust,
towards the close the precious oil was felt to flow, and truth was measurably over all;
I was very much relieved, though weary.
Came home to dine,
and afterwards had several sweet opportunities with Friends who came in.
My female companions dined out, but came in to tea,
and we had a sitting with the family and others.
Dear Susanna Horne had a very enlarged time, and I felt an opening to follow:
in this season it was opened to me, that it was likely to be a parting opportunity to us,
though at times there has been some glimmering
prospect of going with them into Hampshire;
but now it looks likely they must try that county by themselves,
and perhaps way will be made for me to get relieved
from the people at large in Brighton--so be it.
This I mentioned apart to Susanna Horne,
and it is a comfort that her mind is prepared to receive it.

"`20th.--Set off this morning with the women Friends and stopped at Thomas Leadbeater`'s,
and had a sweet opportunity in his wife`'s sick room with her two daughters;
love flowed freely.
To W. G.`'s and dined, and after I had got through my exercise in this convinced family,
we had a sweet parting season.
Soon after, the women set off for Chichester, and I returned to Brighton,
weary with this day`'s ride, but comfortable in mind.

"`21st.--Feel oppressed with a cold this morning,
but as my thoughts have been frequently turned toward the inhabitants of this place,
we sent for a Friend last night, and consulted about a suitable place for a meeting.
A pretty large, convenient house, which had been occupied by the Presbyterians,
but not used lately, was thought of, and as some of the members have offered it freely,
it has been accepted, and a meeting appointed at six o`'clock this evening.
Much fatigued most of this day, I expect from yesterday`'s exertion and having caught cold.
I felt so dull and heavy, that though I endeavoured to read,
seemed as if I could not understand.
Went to the meeting, which was much crowded, and forgot my infirmities,
and it proved an open, relieving opportunity.
In the close appointed another at the same hour tomorrow evening;
returned home and felt pretty well and comfortable, and lay down so.
Thanks be rendered to the Lord my helper.

"`22nd.--To the week-day meeting, where some few neighbours came in,
and I had an instructive time of enlargement.
The meeting at six o`'clock was long in gathering, but crowded at last,
and a very full opportunity to me; ending solidly and well.

"`23rd.--My mind has been turned at times since coming into this place,
towards the fishermen, and this morning after breakfast,
Friends took upon them to go around to their houses and
request the attendance of their wives and children,
and as many of the husbands also as were on shore.
The time fixed was five o`'clock, as that seemed to suit best for this class of people.
Many came, and some late, so that the meeting was long, perhaps nearly two hours,
in gathering: it was trying to me to labour under such unsettlement; however,
feeling love to them, I began and endeavoured to lead their minds into staidness;
and though for a season it was hard work,
and it seemed as if I had to encounter a dead mass, hard to get over,
yet after this time of conflict, my heart was much enlarged, and tongue loosened;
and I trust through divine favour extended, it was a good time to many,
holding near four hours; and my mind was much relieved--the Lord have the praise.

"`24th.--Not apprehending myself clear of this place, and several Friends being with me,
I mentioned it to them,
and proposed holding a meeting in the house we have occupied of late;
with which they united,
and the people were encouraged to come at eleven o`'clock tomorrow,
especially the fishermen.
This has been a pretty quiet day.
Took a walk for health along the shore, and the fishermen seemed to know me,
and were respectful.

"`25th, first-day.--Half year`'s meeting in Philadelphia; and the enquiry is,
how fare my dear wife, children, and aged mother,
and other relations and friends left behind?
It is now nearly three months since my last letter from home was dated.
I have endeavoured to resign up all into the hands of an overruling,
wise and merciful Lord and Master, who was pleased to separate me from them.
Divers of my friends,
neighbours and acquaintances have been removed away from this stage of action since,
and very likely more will be before I reach home,
even if it is the Lord`'s will I should do so.
What better then than to labour after resignation, and be favoured to say,
'`Thy heavenly will be done, by and towards us all.`'

"`To meeting at the Presbyterian meetinghouse.
It soon gathered, and was an open, enlarged time in testimony amongst them.
I invited them to come again at the sixth hour.
Dined at E. M.`'s, and afterwards had a religious opportunity with the family,
in which a youth who is apprenticed to him, lately from Ackworth school, was much broken.
At six o`'clock went to the meeting, which was uncommonly crowded;
it seemed to me that if the house had been as
large again it would probably have been filled:
it held until past eight o`'clock.
Another much enlarged time, though pretty close work to begin, and it ended comfortably.
At the close of it I took my farewell of the inhabitants,
and told them there was but one thing more that rested on my mind, and that was,
to see the children of various descriptions together tomorrow evening at six o`'clock;
for I had observed how many of them crowded at times into those we held,
and some others at the gate, who were not permitted to come in.

"`26th.--This morning feel refreshed and well, favoured with a ray of light,
life and comfort on my bed.
Thanks be to God, who giveth us victory and peace, through our Lord Jesus Christ, his Son.
After breakfast W. W., a gaily dressed person called in, and we had agreeable,
open conversation.
He appears to be an enlightened man, and is desirous of more meetings being held:
he invited us to dine with him tomorrow.
After he went away, there came in a poor Welsh woman,
who appeared much tendered--not talkative, but quiet;
and as we sat in stillness together, my thoughts were turned towards a people afar off,
and I was comforted in the prospect of the possibility of having those raised up,
even amongst the poor, who would own me, and care for me.

"`When she departed she desired the Lord might go with and bless me.
I took a walk for nearly two hours along the sea shore,
and on my return a woman with ribbons about her head, came to see me,
and said she wanted to take me by the hand,
and signified her thankfulness for the opportunities she had had at the meetings,
but rendered the praise unto God,
and requested she might be permitted to be at the children`'s meeting.
We went at six o`'clock, and I felt very poorly.
There was a very great collection indeed.
When we went in, there was much buzz and noise among those in the galleries, etc.,
and John Bevans endeavoured to quiet them by speaking to them,
but it appeared to me to be of but little use, the meeting not being full,
and many came in afterwards.
I thought it best to try to get under exercise, and feel for the inward balance.

"`The house was crowded with people of many sorts, of the upper, middle, and lower ranks.
After some time I felt strength to stand up, though in much bodily weakness,
hardly able to speak, in consequence of being so hoarse;
but I told them in the beginning, that though many of them were noisy and rude,
I felt love to them through all.
There was a pretty great calm and quiet soon after I began to speak,
for I stood some time first; and it continued,
and though I laboured in great bodily weakness, and felt much spent afterwards,
it afforded me much relief, and considering all things was a pretty good meeting.

"`Several spoke to me on coming out: one goodly woman,
who appeared to have the care of some children of the upper rank,
desired a blessing might go with me.
I felt, when I got home, as though a fit of illness was coming on,
and that I must go to bed, but in a little time, by taking something warm,
it seemed like a cordial, and brought me to.
O what sweet peace flowed into my mind on the breaking up of this last finishing meeting!
I thought that if sickness, or any thing else in the ordering of Providence,
came upon Brighton, I was clear of their blood.

"`27th.--Felt peaceful and comfortable on awaking this morning.
After breakfast went with my companion to see a public housekeeper,
who was sick of a fever, and had a good time in his chamber--it was at his request.
Afterwards went to Dr. H.`'s, whose wife I heard was in a desponding, low way;
here we had a comfortable time; both husband and wife were loving,
and he wished more meetings to be held, as have others also.
After an opportunity with a number of Friends who stepped in, I took leave;
we mounted our horses, and accompanied by John Glaisyer, got to W. G.`'s, sixteen miles.
On the way divers fishermen, etc., saluted me, and a man on horseback, as we passed him,
said to us, '`Are you going on?
On telling him we were, he desired with tears that the Lord would bless me.
This morning`'s ride has been a sweet one, for I feel recruited in bodily health,
and sweet peace covers my mind on leaving Brighton.
Remember it, O my soul, in low, stripping seasons: sanctify the Lord thy God,
let him be thy fear and dread, who has been thy helper through deep baptisms of late,
and unto whom belongs honour and glory, thanksgiving and praise,
who only and alone is worthy, and nothing due to man.

"`During this scene at Brighton, my mind has been turned toward our dear companions,
from whom we parted for the work`'s sake:
may the same Almighty hand which has graciously helped me, protect and preserve them.
Not far from the place where W. G. lives, is the seat of Roger Clough,
where William Penn used to live, called Worminghurst.

"`28th.--Set off about seven o`'clock.
On taking leave of a daughter about ten years old,
I told her my desire was that she might be dutiful to her parents,
loving to her brother and sisters,
and particularly to set a good example to her younger sisters;
and that when the evil one tempted her to do what was not right,
she should resist him and not yield, and then he would leave her,
and she would feel sweet and comfortable.
She broke forth into tears, and said,
'`O he does tempt and try me:`' and I learned by her parents,
that she complains of the temptations wherewith she is beset.
I have not often met with such a child.
We proceeded on to Alton, where we found our friends Susanna Horne and Sarah Fairbank:
a number of Friends spent the evening with us,
and I thought I was quite as cheerful during this day`'s ride,
and also since coming into this place last evening, as was profitable for me.
Surely I have need to be watchful, not only in the winter season,
but also on the summer`'s day, lest my garments get defiled.
I trust my mind is humbled this morning.

"`29th.--To the select meeting at eight o`'clock, and afterwards to the quarterly meeting.
The public labour fell on Susanna Horne.
I felt nothing to communicate until the queries were answered in the men`'s meeting;
and I thought myself a poor thing to say any thing amongst Friends,
for I felt like one going down again into sorrow and exercise.
We dined at E. and H. Marshall`'s, and afterwards went to Deborah Merryweather`'s,
where a number came, and my soul was much clothed with sorrow and exercise,
and I ventured to bend in supplication, and afterwards to speak to a very tried state.
I thought there was need for me to cry out for myself.

"`30th.--Went to divers families with Susanna Horne and Sarah Fairbank,
but no communication was laid on me.
I accompanied our women Friends to Samuel May`'s,
where we had a memorable time after dinner; and I may with gratitude acknowledge,
that after I had ventured to bend in supplication, I say ventured,
because it is an awful thing, and afterwards in communication,
my mind obtained considerable relief, and felt more easy.
Marvellous are the dispensations of Providence.
No way opens further into this county, or further westward.
I feel glad and well satisfied that I am here,
having fulfilled pretty much what opened on my mind when in the north,
respecting the meetings through the counties where my lot of late has been cast,
even with respect to the public ones.
The Lord is a merciful and tender master,
and has accepted my feeble endeavours to serve him.
Stand resigned then, O my soul, to whatever further dispensations may be meted out.
Drank tea at W. C.`'s, and had a tendering opportunity,
and believe some of them were strengthened by it.
Returned home;
and though I have had some religious communication in the opportunities this day,
yet felt very poor and solitary in the evening.

"`31st.--Our women Friends having seen their way to move, are gone; mine seems hedged up.
I struggled along until after dinner,
and I hope did not much appear to the company to fast.
Soon after John Bevans, my patient, kind companion and I,
accompanied by Samuel May as guide, took horse for Godalming.
It was pleasant once more to be on horseback, and for a little time I felt more lightsome.
In this eighteen or nineteen miles ride we had to go over a pretty large heath,
or tract of poor land.
I lagged behind my company under much exercise of mind,
and thought I could have laid prostrate on the earth, with my mouth in the dust,
if so be there might be hope.
Put up at the widow Mary Waring`'s, where I met with a very affectionate reception.

"`Fourth month 1st, first-day.--I feel disposed to say, through best help extended,
I will wait and I will hope; often coming to the conclusion,
that it is not meet for me to be long without such strippings;
and in the midst of them believe I do not feel a murmuring thought;
and indeed why should I, when I have experienced so often,
that the will of the Lord is my sanctification.
Went to meeting and sat it through in silence, and felt content.

"`To afternoon meeting,
and was led in a particular manner to address the youth under visitation,
and to deal pretty closely with some other states.
The meeting of ministers and elders began at six o`'clock, and held late, which was,
I thought, a satisfactory time.

"`2nd.--To quarterly meeting, where I sat nearly two hours,
with nothing stirring as to the ministry.
Elizabeth Waring appeared in a few words, also Hannah Pryor, and Ann Christy.
Soon after I felt an opening to stand up, and had a pretty tendering time.
The business did not end until about four o`'clock; but it was a satisfactory meeting,
in which some ground was gained.
A committee was appointed to help the monthly meetings to labour with respect to tithes.
Dined at home,
and had a tendering opportunity with a pretty large company of youth and others.

"`3rd.--I sat the monthly meeting in much quiet, under exercise.
Dear Hannah Pryor, who still continues in the neighbourhood,
I thought had a lively communication.
In the business part of the meeting I felt desirous that
individuals should prepare their spiritual accounts,
which I expressed, and I was humbled into tears,
in resignation to the Lord`'s blessed will.
My way closes in this neighbourhood, and seems opening towards London again,
O Lord my God, to thee I look, to thee I cry:
hitherto thou hast helped and sustained my wading soul,
and for this favour I bless thy name,--even for so much
quietude of mind as I feel at this present moment.
Today I heard of fresh fears and cares possessing the
public mind respecting the state of affairs.
I have heard very little of late respecting things in this land,
or the commotions and stirrings further off;
yet it seems as if my mind was in sympathy with the nation at large.
But these things I leave to the great and merciful Judge of all the earth,
and proceed to my feelings respecting myself and getting on.
After dinner had a memorable opportunity with the
family where we have been kindly entertained,
and a number of others.
Left them very tender, and many of them in tears; mounted our horses and rode to Esher,
fourteen miles, and felt easy and comfortable.

"`4th.--Lodged in a room richly furnished; yellow silk damask curtains to my bed,
and silk curtains to the windows, etc., and on looking over the house this morning,
I do not find much difference between it and the duke of Norfolk`'s,
over which John Bevans, John Glaisyer, and I, went with the duke`'s servant,
by his orders, when at the castle at Arundel.

"`I have lodged in very mean habitations in time past,
and was favoured with sweet peace and content.
Lord, preserve in what may yet be meted out, that thy will may prove my sanctification.
'`Verily I say unto you, there is no man that hath left house or brethren, or sisters,
or father, or mother, or wife, or children, or lands, for my sake and the gospel`'s,
but he shall received an hundred fold now in this time, houses and brethren, and sisters,
and mothers, and children, and lands, with persecutions, and in the world to come,
life eternal.`'
I have enjoyed fruitful fields and beautiful gardens for a moment, perhaps as sweetly so,
from the great Giver of all good things, as some of the owners of them.
Thanks be given where they are due, saith my soul.

"`We attended the week-day meeting, which was a small one.
I sat nearly or quite two hours;
but towards the last felt an opening to minister to the states of others.
It was a quiet and pretty comfortable time.
In the afternoon rode to London.
My companion took me home with him to Charter-house square,
where we found Sarah Fairbank and Susanna Horne; they had not been long from Staines.
I stayed and drank tea,
and after a little sweet opportunity in the family of my friend and kind companion,
he sent me in a coach to Broad street, where I met an open,
kind reception from my beloved friends Joseph and Rachel Smith,
and lay me down quiet in mind,
having no cause to doubt my returning to London once more being right,
though I can see nothing fully at present.

"`5th.--Arose with a calm and resigned mind.
O then, that like a child, I may be favoured to behave myself resignedly,
given up to wait to know the Lord`'s will,
who has of late led me about and deeply instructed me.
Magnify his name, O my soul, and forget not his benefits.

"`6th.--Attended the meeting for sufferings,
and had to remind them of the day of sifting and trial coming, I endeavoured, I hope,
faithfully to clear my soul.
Went home with Truman Harford and lodged.

"`7th.--Tears were my meat on rising this morning, and viewing my condition.
O Lord! help still with a little of thy soul-sustaining help.
After dinner joined a committee of the monthly meeting in visiting a Methodist minister,
who is convinced of Friends`' principles,
and sat with them to a good degree of satisfaction.
I got safe home to Joseph Smith`'s,
and spent the remainder of the evening pleasantly with them.

"`8th, first-day.--To Grace-church street meeting,
and was largely engaged once more in pleading with the gay, first-day morning professors,
with encouragement both to them and those of a different description also,
to a good degree of satisfaction and relief.
In the afternoon attended the same meeting, where Mary Lloyd of Birmingham, sat by me,
and we were both led in the same line of communication, to a mourning, desolate state.

"`9th.--To morning meeting, exercised in mind--a little book on Tithes was read, etc.
In the afternoon to Tottenham with Susanna Horne,
and once more met an affectionate reception from the father and daughter Martha.`"

[.offset]
In a letter to his wife, dated fourth month 9th, 1798, at London, he says:

[.embedded-content-document.letter]
--

I came to London last week,
after an excursion of about two months into the counties of Kent, Sussex,
and part of Surrey and Hampshire,
and have had sweet peace in an honest discharge of duty, both amongst Friends and others;
having had six public meetings in the town of Brighton, on the sea coast,
before I could leave that place.
Whether I shall stay in or about London until after the yearly meeting,
I cannot fully see.
I believed it my place to enter into this great city again,
where clouds of exercise seem gathering around me;
and if it is my lot in the will of God to be here,
and suffer with my brethren and sisters, if suffering should be their lot,
I have no reason to question and say to my Master, '`Why dealest thou thus with me.`'
O may I still be favoured to sanctify the Lord my God,
and let him be my fear through the remainder of my pilgrimage in this land,
is my soul`'s desire.
The outgoings of my heart have been towards my dear companion in life,
with desires that Almighty God may sweeten every bitter cup to her.

--

"`10th.--I came back to London and its neighbourhood in resignation to the Lord`'s will,
ready and willing to refit and move on, if it is his will,
to the further part of the land;
having little desire to stay here and hereaway until after yearly meeting,
although thereby I may see many dear Friends, also some of my country folks.
A prospect has at different times opened, of some further service out of London.
But now all seems closed up as in times past, and I am again a poor blank.
Were it not for soul-sustaining help in some of those trying winter seasons,
I should fear getting into a state of despair; but hitherto the Lord has helped,
and I will endeavour still to trust Him,
though he may permit me to go down yet deeper into the valley and shadow of death.
May I wait for a day of deliverance, and be content with my bonds.

"`11th.--To the burial of James Townsend: the corpse was taken to Peel meeting.
My trouble multiplied on me.
I went to the ground, and though I felt a poor creature,
yet I ventured to stand forth amongst the people in a short testimony;
after which I returned with my very kind friend J. H. and children.

"`12th.--To meeting, which was altogether silent: my soul could do little more than cry.
Lord have mercy, and wash and cleanse me.

"`13th.--Spent this day pretty much in adjusting and endorsing my letters and papers.
Received a letter last evening from S. H.;
it appears by it that he was not satisfied with what I delivered in meeting.
Thus I get along--often a poor staggering one; through good and evil report,
and often weeping over my own infirmities.
My soul has this day craved mercy, with sighs and cries, in the language of the Psalmist;
'`Hear my voice, O God, in my prayer; preserve my life from the fear of the enemy.
Hide me from the secret council of the wicked;
from the insurrection of the workers of iniquity.`'

"`16th, second-day.--Went to London, and had a memorable ride;
the flesh warring against the spirit, to bring me into bondage.
After calling to see several Friends, I took a pensive, thoughtful walk over the fields,
and my sorrow was stirred within me,
and know not how to record my distress better than in David`'s words;
'`Give ear to my prayer, O God; and hide not thyself from my supplication.
Attend unto me, and hear me: I mourn in my complaint, and make a noise;
because of the voice of the enemy, because of the oppression of the wicked:
for they cast iniquity upon me, and in wrath they hate me.
My heart is sore pained within me: and the terrors of death are fallen upon me.
Fearfulness and trembling are come upon me, and horror hath overwhelmed me, or covered me.
And I said.
Oh that I had wings like a dove! for then would I fly away, and be at rest.
Lo, then would I wander far off, and remain in the wilderness,
I would hasten my escape from the windy storm and tempest,`'

"`18th.--Awoke pretty early, and lay in a pensive, thoughtful frame of mind,
looking over my movements, and felt an earnest solicitude and prayer arise,
that I might be favoured to settle down into greater resignation of soul,
and to bear with greater patience my yoke and bonds.
I have been struggling with a prospect that has at times opened,
to go again into the north of England on the opposite side of the island,
to that it was my lot to be in last summer,--to Scotland,
and even further if it is the will of God.
I came to London fully resigned, I trust, to this prospect,
and to refit and go off before yearly meeting;
but it appears the time is not yet fully come, if it does come at all,
and now the cloud rests upon my prospects.
No opening to religious service presents, and at seasons the lion roars against me.
O that I could be quiet and behave myself more like a weaned child,
with submissive dependence upon an all-wise Father:
this condition has looked very desirable this morning.
O then, my soul, seek for divine assistance to press more and more into it,
leaving those things that are behind, and the trying,
perplexing thoughts that so often set themselves in array against thee.
There is yet mercy, forgiveness and truth with the Lord, that he may be feared;
and with him is plenteous redemption.
Hope thou in him, that thou mayest praise him in a day to come,
and know him to be the health and light of thy countenance, and thy God,
who has helped thee over many difficulties in days and years past.
I desire to lay prostrate before him, humbled in dust and ashes.
There is no hiding from the all-seeing eye of Heaven.
The language of my soul is, '`Why hast thou forsaken me;
or wilt thou forsake or overlook thy poor servant;`' and yet,
is it not a great thing to be favoured to think, and to say, '`though thou slay me,
yet will I trust in thee.`'

"`19th.--In a lonely, pensive walk,
I was favoured to think how easy a thing it would be with the mighty
One of Israel to change the dispensation respecting my soul.
I thought,
how joyful it would be to live to see truth and
righteousness flourish in London and its neighbourhood,
and living zeal for the law and testimony increase,
and that I might joy and rejoice with them that rejoice.
Went to meeting and sat it through in thoughtful silence,
endeavouring to sum up my accounts since leaving Brighton, and settle them,
and hope my soul was truly humbled.

"`21st. seventh-day.--My soul is under oppression.
What a staggering condition I seem to be in,--like a drunken man, but not with wine,
but with the cup handed me by my gracious Lord to drink of.
The cup which my heavenly Master giveth, or sees cause to permit to be dispensed,
shall I not drink it?
yes; my soul craves ability to dwell here, all the Lord`'s time... I thought this day,
how willingly could I enter into any religious
service the Lord might be pleased to call for,
even the honourable service of the best of pay masters, either amongst my friends,
or amongst the people at large.
On the way home my mind became more calm, and Waltham Abbey meeting came into view,
and a willingness to go and sit quietly amongst the
little company that is to assemble there tomorrow.
My soul was bowed in thankfulness,
and spent the remainder of the evening quiet and serene.

"`22nd. first-day.--Arose with calmness and resignation.
A very fine morning as to the outward,--and may I say,
When shall I be favoured to behold the opening of another spring-time
in my soul! when will the singing of birds be heard,
with the voice of the turtle dove.
Is it not more fit and acceptable to say, '`Not my time and will, but thine, O Lord,
who doeth all things well:
fit and prepare my soul to bear with becoming
patience all the dispensations of thy providence,
whether spiritual or temporal.
Wash away my secret faults; cleanse me from them and thy will be done.

"`Went to Waltham, accompanied by W. F., his son William,
and J. W. I was silent in the meeting, yet favoured with some sight and prospect,
not the sign of the prophet Jonas, but that of Ezekiel.
O how little opening appears in places.
I have faith to believe it will not be so always;
but when the rod has been exercised for a time,
there will be an open door for the servants and messengers.
My soul craves a share of labour in this blessed day, yet with humble submission.
The opening I was favoured with was sweet,
and I thought if it was the Lord`'s will to remove me from my troubles here.
He who made me, and has thus far supported, borne up, and corrected me also,
would have mercy on me.
May thankfulness fill my soul for this sense.
J+++.+++ H. and daughter dined with us, and after dinner we dropped into silence,
in which he had some religious communication, much of which I thought fitted my state.
The afternoon meeting was dull and laborious,
but near the close J. H. spoke fitly to my tried state; it was reviving and encouraging,
and I felt willing to receive a crumb handed forth through a fellow servant,
and one who in man`'s estimation is weak.

"`24th.--O,
if the fat and full in this land are brought to feel the
situation my soul has laboured under for three years,
it will be a time of mourning indeed.
May such a sense, if permitted,
prove a time of enlightening and gathering to the true Shepherd and Bishop of souls.
The Lord hasten the blessed day of flocking unto Zion, as doves to the window of the ark.

"`25th.--Something like the lifting up of the head was my thankful experience today,
in a long and thoughtful walk.
I remembered this passage of Scripture, and when I returned read it to my comfort;
'`God hath spoken once, twice have I heard this, that power belongeth to God.`'
The Lord`'s servant breaks forth, both before and after these expressions, on this wise,
and it appears applicable to my state, viz; '`Hear my cry, O God; attend unto my prayer.
From the end of the earth will I cry unto thee, when my heart is overwhelmed:
lead me to the rock that is higher than I. God hath spoken once, twice have I heard this,
that power belongeth unto God: also unto thee, O Lord, belongeth mercy,
for thou renderest to every man according to his work.`'
These expressions also impressed my mind in my walk;
'`I stand continually upon the watch tower in the day time,
and am in my ward whole nights.`'

"`27th.--In the evening I felt my mind turned in near love and desire for the
preservation of B. B. I rejoiced in feeling once more the arising of love,
I trust gospel love, and to find a small return of the precious gift to me.
My heart was also broken in a sense of the great love and tenderness which
both of the parents and the children of this family had manifested to me.

"`Fifth month 6th,
first-day.--Thinking a little last evening of going to Grace-church street meeting,
and mentioning it to my kind friends, was encouraged; but on arising this morning,
such was the sense of my weakness and unworthiness,
that for a time I could not persuade myself it was
right to attend to the little motion felt last evening;
yet as the way seemed most open,
I set off accompanied by S. D. In the meeting I bent in supplication,
which much relieved my mind,
and again after a lively communication through
dear A. C. I ventured to utter a few sentences,
expressive of the love I felt to that assembly, and which,
thanks be to Him who is ever worthy, flowed through me to the king on the throne,
and also to the meanest of his subjects.
'`By this we know we have passed from death unto life, because we love the brethren.`'
To the afternoon meeting at Tottenham.
I had a pretty open time,
especially in love and sympathy towards some of the youth present.

"`10th.--Four years this day since I left my own habitation.
Went to Tottenham monthly meeting.

"`11th.--Not without a portion of sorrow and sadness on awaking this morning.
Bowed in prayer before leaving my chamber, begging for preservation.
I looked back to my conflicts this day four years: ah! it was a day to be remembered,
if I may indulge for a moment.
But is it not better to endeavour to forget the things that are behind, and press forward.
O that I may be accounted worthy to be yet numbered amongst the Lord`'s servants.
I have remembered the kind and consolatory expressions of our Lord to his disciples;
'`Ye are they which have continued with me in my temptations,
and I appoint unto you a kingdom; even as my Father hath appointed unto me.`'`"

[.offset]
The following is extracted from a letter addressed to him by his friend Ann Crowley,
dated:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Aylesbury, 10th of Fifth month, 1798.

[.salutation]
Dearly beloved friend,

Thy affectionate and sympathetic communication merited an earlier reply;
but I have no doubt thou wilt believe, and that because experience hath taught thee,
that minds occupied in a service so weighty and important as is our present calling,
meet with various occurrences to prevent writing,
even to those we dearly love and are nearly united to,
by the binding tie of gospel fellowship.
Thus from frequent exercises, and sensible feeling of great weakness of mind and body,
I have been prevented from acknowledging,
that thy token of continued remembrance and regard was
truly salutary to my tried and stripped mind;
and perhaps it could not have reached my hands at a season when more needed,
for it arrived just as I was sitting solitary and mournful,
not knowing which way to move, or what offering to make to obtain peace;
distress clothed my mind and darkness seemed on every hand.
The spring of gospel ministry had been long shut up, and appeared as a fountain sealed;
my mind was like a stranger and alien to the knowledge of divine things;
I thought as much so as though none of the mysteries of
the kingdom had ever been unfolded to me.
In this tried, proved state of mind, I found few could fathom my exercises,
though divers pitied,
and were ready to hand forth a little advice,--such as wishing me to be faithful,
and not carry such a burden from meeting to meeting, and thereby weaken my hands,
and similar communications; all which were administered in great tenderness and love,
and I could receive them as such; I thought they only tended to add to my tribulations,
for all was as much sealed from me,
as though I had never received any qualification or commission to preach the gospel.
I was ready to call all former experiences in question,
and to conclude I never had known a being anointed and appointed for that service.
This was my situation when thy kind letter came to hand, which felt like balm to my soul;
no doubt but thou wilt admit, if thou remembers what thou wrote,
that it was a suitable cup of consolation; it felt to me like a little brook by the way,
for which unmerited favour, gratitude was raised in my heart to the Lord,
and I was thankful to feel he had not forgotten to be gracious,
but had once more extended his never failing hand of help in the needful time.
I did believe it was of his goodness to put it in thy mind thus to address a poor,
weary traveller,
to whose frequent baptisms and exercises I believe my
beloved friend is not altogether a stranger;
for having trodden a trying path thyself,
thou canst more intimately dip into a sympathetic feeling with such,
who in some degree may have to walk in similar footsteps.
Yea, I verily believe the intercourse and communion of spirits is such,
that we are permitted sensibly to feel one another`'s exercises and trials,
before any outward information reaches our ears.
Great is the privilege; indeed I felt it so; for I can say in perfect freedom,
that in the course of all my travels I have not met with one
that could so feelingly fathom my state of mind,
as thou wast enabled to do, my endeared friend,
though we were so widely separated as to the body; may I ever walk worthy of such notice,
is the craving of my heart.

I wish not to dwell too much on a relation of the many probations and deep exercises,
which in unerring wisdom have fallen to my lot in the course of this journey,
but rather call to mind and commemorate the gracious
dealings of the Lord with us and with his people.
How wonderfully hath he at times opened both the door of utterance and entrance,
so that we have been constrained to acknowledge, '`Great and marvellous are thy works.
Lord God Almighty; just and true are all thy ways, thou King of saints.`'
Is he not working wonders in the earth`'.`' yea, verily, our eyes are made to behold,
as well as our faith renewed to believe;
so that at seasons we can bless and adore his holy name, and say,
'`Thou art a long-suffering, gracious God; inviting all, even the transgressors in Israel,
to return and come to thy banqueting house, where thy banner over them will be love.`'
It is probable my beloved friend may have heard,
that our line of labour has not been altogether confined to our religious Society;
but for the enjoyment of that peace,
which obedience to the renewed manifestations of duty can alone purchase,
we have been made willing to have public meetings in many places; this thou wilt,
I have no doubt, conclude has not been a little proving to my faith;
particularly as my much beloved companion has little draft this way,
though she has nearly and feelingly sympathized
and felt with me in this arduous engagement;
the secret travail of her spirit has been precious and strengthening to my mind.
When the burden of this concern came weightily on my shoulders, how did nature shrink,
so that I was ready to say, if it be possible let the cup pass from me;
for I am no way qualified,
and the undertaking is too mighty for one so little instructed in the
school of Christ;--there is great danger of my supporting,
or attempting to support the ark unbidden, and thereby bringing a reproach on the truth,
and condemnation to my own soul.
Such like reasonings took place;
but after consultations of this sort I plainly saw my peace of mind and health of body,
depended on obedience.
Then was I reduced into such a state of resignation, as enabled me to say,
as one formerly; '`If thou wilt give me bread to eat,
(spiritual bread,) and raiment to put on,
(the robes of righteousness and peace,) then shall the Lord be my God,
and I will obey him.`'
When brought into this state of mind, I experienced way to be made,
where I saw no way before; the mountains skipped like rams,
and the little hills like lambs.

I am ashamed of myself,
when I see the full dedication of heart dear Sarah Lynes manifests to the world,
by her resignation and obedience to such singular requirings; may she be preserved,
so as in the winding up of time, to experience the answer of, '`Well done,`' etc.,
is often the desire of my mind, as well as for myself, and all other exercised servants.
We have several times fallen in company with dear Charity Cook and Mary Swett;
I think them valuable, choice Friends:
I wish their honest labours of love may be blessed to
the inhabitants of this highly favoured nation.
Charity Cook`'s gift lies much amongst other societies;
Mary`'s much confined to our own band; however, they seem nearly united.
We parted from them at Warwick--they have gone the Oxford road to London.

--

"`15th.--What a scene I have passed through in the five months past!
What deep plunges at seasons--what stops and stays; what blindness, weakness and poverty;
and yet, not without intervals of light, life, strength and boldness.
My soul desires to know what true humility is,
and begs to be favoured to lay prostrate on the approach of the annual assembly,
that in and through that, I may be found in my allotment.
O Lord be merciful! wash and cleanse me;
grant more victory over weakness and frail nature--gird
me about with a portion of thy strength.

"`18th.--The opening of the yearly meeting, and I am in a very broken, poor condition.
The all-seeing eye knows how it is with me, and this has been some consolation:
I feel no disposition to hide.
What can such a weak creature do better,
than labour after ability to breathe forth this language in secret,
to him that sees in secret; '`Though thou slay me, yet will I trust in thee.`'
Attended a large meeting in one of the new houses.
My mind was bowed, and my heart in some degree broken;
and after a lively communication through my dear country-woman, Charity Cook,
I ventured to prostrate myself in supplication.
Martha Routh had a searching time, which was a relief to my mind,
Elizabeth Ussher uttered a few words in prayer near the close.

"`19th.--Having had my thoughts turned for several days toward Westminster,
I went thither this morning with Thomas Colley.
The labour fell on him, and I was content.
At the close I gave liberty to invite the people to come in the evening.
Went to meeting at five o`'clock, and had a pretty good time.
E+++.+++ H. from Ireland, was also engaged, and Martha Routh appeared in solemn prayer.

"`21st.--To select meeting,
where dear John Wigham and Martha Routh gave in their certificates,
and a sweet account of their visit to our country.
It was a good meeting.
The opening of the meeting for business at four o`'clock was a profitable, good sitting.

"`22nd.--Two sittings of the yearly meeting.
The time was spent in reading the answers to the queries, as far as Surrey,
and some good remarks were made: very little fell on me, and I had a quiet, peaceful day.

"`23rd.--To a meeting for worship at Devonshire house,
where I had a pretty open time of encouragement to the burden-bearers and tried ones.
Deborah Darby, and also my country-women.
Charity Cook and Mary Swett, had a share in the labour.
After which I went to William S. Fry`'s, where I found a large company,
and was exercised in religious communication.
In the afternoon meeting for business,
my mmd was engaged to speak in testimony against appointing such members as
are not faithful to support the precious testimonies of Truth at home;
and sending them to yearly meeting to open their mouths,
to the afflicting and wounding of their brethren.

"`24th.--Attended meeting, and also sat with the committee to prepare epistles,
in which an opportunity was given to relieve my mind of an exercise,
respecting those who were fit members for employment in the services of society,
and those who were not.

"`26th.--O humbling prospect! were it not that my soul has been given to believe,
that the everlasting Arm still remains to be underneath, should I not faint indeed!
Have faith in God then, O my tried soul.
I sat with the large committee, which got on comfortably with the business,
and at eleven o`'clock went to the yearly meeting.
After meeting,
I mentioned to Truman Harford a prospect I had
of seeing the neighbours together at Ratcliff,
and which weightily opened upon my mind in yearly meeting.

"`27th, first-day.--My exercise seems of late to begin with morning light.
O may I be favoured to turn my attention, with singleness of heart,
to the meeting appointed at Ratcliff,
that so through the Lord`'s help his holy name and truth may be honoured.
O Lord be pleased to help me.
Went to Ratcliff, accompanied by my friend Susanna Horne, where was a large meeting,
mostly made up of people of other societies.
It proved an open time,
from the passage of Scripture describing Peter`'s seeing the sheet let down,
and being fitted to go with the messengers.
The same good hand which worked in Peter`'s heart, and prepared him for the service,
opened also the heart of Cornelius to receive the message.
A young man came to me after meeting,
and said his doubts were now removed respecting our Society.
Attended an evening meeting in the same place, which was large,
and another favoured time, in which my mind was comfortably relieved.

"`28th.--Very much abased and prostrate this morning,
as on the bended knees of soul and body; and a little light and hope sprang up,
in which I was enabled to believe that the Lord would break my bonds,--and
the vision was as clear as that of my coming into this land.
O then, my most merciful and adorable Lord and Master,
let thy blessed will be done respecting me, and all that appertains to me.
Thou hast shown thy servant in the deeps that thy hand has been at work,
and underneath--thou hast shown me that thy mercy
reacheth forth towards my dear aged parent,
and that she is under thy protection;
and that thou hast provided an everlasting habitation for the wife of my bosom.
Lord, my soul is overcome in the sense of it.
Thou hast shown me, that thy tender notice and regard is toward my dear children.
O keep them, and let them be thine; and thou hast shown me,
that thou wilt yet provide for me; wilt give beauty for ashes,
the oil of joy for mourning, and the garment of praise for the spirit of heaviness.

"`29th.--The last sitting of the yearly meeting this afternoon,
closed under a solemn calm.
I have been a plentiful sharer in deep humility
through the several sittings of this meeting;
and have been favoured to speak to the relief of my mind,
and also rejoiced in seeing truth gain ground, and in our having a precious,
solid meeting; yet my conflicts and exercise are not removed.

"`31st.--This morning I poured out my tears of distress and sorrow.
I remembered the note made a few days ago,
(28th,) and longed for ability to cast away my labour and toil, and have faith in God.
I am now shut up as in a cloud.
I could not make mention to the yearly meeting about going home,
as my friends William Savery and Sarah Harrison did.
I felt quiet and easy in that respect,
and now am as blind as ever as to any further religious service in this land.
Lord, keep me from falling on this sea of glass mingled with fire.

"`Sixth month 1st.--O Lord God, remember me in my distress,
for my soul is almost overwhelmed; forgive all my iniquities,
sanctify and prepare me for further work, in thy way and in thy time,
if more thou hast allotted for me to do.

"`3rd, first-day.--I ventured on my knees in meeting,
to beg for preservation for myself and all the Lord`'s conflicting servants,
wherever their lot is cast.
David`'s state presented, when he said, '`be merciful unto me, O Lord; be merciful unto me,
for my soul trusteth in thee; yea, in the shadow of thy wing will I make my refuge,
until these calamities be overpast.`'`"

[.offset]
In a letter to his son, dated London, sixth month 5th, he thus writes:

[.embedded-content-document.letter]
--

I am yet in London, and indeed, discouragement would thicken upon me on this account,
finding it trying to you at home,
if I had occasion to conclude that it is not in the will of God:
there would then be cause indeed to mourn; but I trust it is not in my own will,
for I meet with many fiery trials, and ups and downs,
which tend to the breaking of that in pieces.
O may my soul be preserved to the end, is my fervent prayer.
Yearly meeting is over, and an evidence has been granted me that I have been in my place:
it was very large, and sweetly owned by the Master of assemblies.
I rejoice in seeing and believing that truth and righteousness
are spreading--there being many precious young plants.
I have met with Charity Cook, Mary Swett, Sarah Talbot, Phebe Speakman, William Savery,
and also Sarah Harrison, to my comfort.
In my former letters, if they have come to hand,
you will perceive that I had got on the south side of London:
I went through two counties fully, and part of another,
and have been comforted in finding or hearing that it
has not been in vain I am a servant in waiting:--wait,
then also, all you my dear family, who are so nearly interested in my welfare,
and pray for me when you can, that I may fulfill the task,
much whereof is drinking the cup of suffering.
The cup which my heavenly Father giveth me, or permitteth me, to drink,
shall I not drink it?
O yes! and that with resignation.
May the Lord on High, who is mightier than the noise of many waters, comfort, bear up,
and sustain all your minds and also be with me.

--

"`10th.--I went to meeting in a weak state.
Both morning and evening were deeply plunging times.
After Elizabeth Ussher had appeared in a short testimony,
toward the close of the meeting in the morning, applicable to my tried state,
I ventured to go down on my knees.
The afternoon meeting appeared to me to be a very solemn time,
and I ventured to tell the assembly so.

"`14th, fifth-day.--I have remembered this morning, that it is, I think,
four years this day, since I landed at Tower wharf, London.
O the scenes my soul has passed through in and about London since that time;
and could I wish or desire that it should have been otherwise?
O no.
If the Lord is pleased to carry me through to the end, I shall have occasion to say,
'`great and marvellous are thy works.
Lord God Almighty; just and true are all thy ways,
thou King of saints! who shall not fear before thee, and glorify thy name.`'

"`20th, fourth-day.--I have thought much of the poor and miserable people in Ireland,
who are called rebels, as well as others called protestants; the misery and sufferings,
unutterable perhaps, of many, as well as the deaths of not a few.
How has my heart throbbed within me, when I have read the account.
My mind has also been turned toward the rulers in this land; from the king on the throne,
to his ministers and servants, and I have seen that it is not fortifications,
either above or below the earth;
neither armies nor navies that will save this favoured land.
No, nothing short of the out-stretched arm of the Lord, and the people bowing before him,
and humbling themselves as in dust and ashes; keeping a fast from abominable wickedness,
and sincerely praying unto God, the only hope of salvation.

"`Seventh month, 1st, first-day.--Feel a willingness to endure all my trials,
and not to cast away my little grain of faith.
Lord, if I perish, I will perish at thy feet, has been the cry of my soul.
Went to meeting at Tottenham, and near the close I ventured to bend in prayer,
having had a little opening as out of the prison window, of a day of more enlargement.
After afternoon meeting went home with William Dillwyn.
O that misspending time may not be charged against me.
Many are the charges of the accuser of the brethren, at seasons,
when my soul is in a low condition.
O Fountain of mercy, be pleased to clear my way, even if it be through the fire;
let thy mercy go forth, and then my soul shall endure.
I long to be employed by thee in the work of the gospel.

"`3rd, third-day.--If I dare say that my sufferings in part are for others;
and that I am dipped into sympathy with the nation at large, and in a peculiar manner,
with the city of London, (yes,
O London! my soul has been abased within thee;) then most assuredly,
I believe the Lord will fulfill what he has shown to his servants the prophets.
O may my soul be favoured to partake resignedly of the cup of suffering meted out,
and not be cast off of my God.
If I am a sign to my brethren in this land, as a poor suffering servant;
Lord grant me the comfort of thy holy presence, to go with me, and it will be enough.
Thy power is above every power.

Draw away my affections from all hindering, earthly concerns.
Blot out and remove all my iniquities, and enable me to say.
Thy will be done I desired to pray for a clear evidence,
that I was in suffering for some good purpose; and was stopped by this reflection;
where then would be the exercise of faith?
and it appeared desirable to walk by faith, if only by a grain.
O then for resignation and more contentment in the divine will.
Man by his efforts can do nothing: lie prostrate, O my soul, let the waves pass over thee.
Walked over to High Cross,
and spent part of the afternoon with S. H. and W. F. At the boys`' school in the evening,
and felt more free from that inexpressible weight.`"

[.offset]
The following is extracted from a letter received while in London,
from his beloved friend Ann Crowley, viz:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Skipton, 6th of Seventh month, 1798.

[.salutation]
Beloved friend,

It seems as though I could scarcely forbear embracing a
few minutes of leisure to address thee,
though not from an apprehension that the expression of continued love and sympathy
can prove effectually consoling or strengthening to thy deeply exercised mind
especially as it comes from one whose experience in divine things,
is that of a child`'s; but having felt my mind increasingly bound to thee,
in the sweet fellowship of gospel love and life,
and an inclination arising time after time, to tell thee as much,
I thought it might afford me some relief to say,
how near and dear thou art to my best life.
I think I never felt it more so than of late, for which my soul is made thankful;
because, if my feelings have been right,
it is a union which will allow me to salute thee as a brother,
or should I not rather say, a father, in tribulation, in sore conflicts and trials;
when faith, patience and hope may be reduced to a low ebb.

I think I was never more sensibly impressed with an apprehension that
a large portion of suffering has fallen to thy lot,
than since we last parted in London; yea, surely it must have been so,
or I think I should not have been introduced into such a sympathetic engagement of heart,
for one whom I so dearly love, and whose firm standing and preservation,
through the various proving baptisms dispensed, I covet as my own;
knowing that nothing short of the invincible and invisible arm of God`'s salvation,
can support and bear up the tossed, tribulated mind, through the vicissitudes of time.
An establishment in this belief leads to a daily breathing in the pathetic language;
'`Arise O God! strengthen thy feeble servant with might in the inner man,
that so preservation and perseverance through all may be experienced.

But there are seasons when thy poor friend cannot lift
up her soul to Heaven and cry for daily bread;
but, feels hardness of heart,
and distress of mind,--can justly compare her state to the heath in the desert,
and knows not when good comes;
can hear her fellow travellers and friends tell of the
humbling seasons of refreshment they are made to partake of,
when she is not able to utter, scarcely a rightly begotten sigh or groan,
or shed a mournful tear;
but all that proceeds from the only source of good is veiled from her,
as things she had never partaken of in former seasons.

Is this an experience with which my beloved friend is experimentally acquainted?
Surely it feels to me, as if a similar bitter portion has been given him to drink,
in the course of his pilgrimage; and if this should have been the case,
it may afford me some encouragement; because I am firm in the belief,
that thy sufferings have not only abundantly qualified for service in the Lord`'s work,
but they have brightened thee, as a well polished instrument,
fitted to execute the office intended.

Therefore, suffer me to say in simplicity, though in integrity of heart; '`Be not afraid,
neither too much cast down or discouraged, for the God of Abraham, Isaac, and Jacob,
is thy God;`' He will be thy buckler, thy shield,
and thy battle axe,--that so no weapon formed against thee,
shall ever be able to prosper; but thou shalt be abundantly clothed upon with strength,
wisdom and understanding, so that in the midst of trials, baptisms and provings,
the acknowledgment will be raised, the Lord is worthy to be served,
to be honoured and obeyed; for though he hideth his face for a season,
yet at the break of day I see the Son of Righteousness arising;
and faith is given me to believe, healing virtue is on his wings.
Can the children of the bride chamber rejoice, when the bridegroom is not with them?
And is it not a day when the bridegroom of souls is
often withdrawing himself from his church and people,
because of the degeneracy,
the lukewarmness and indifferency of mind which is prevalent
amongst the high professing Christians`'? Can we wonder then,
that mourning should be the appointed garment of the Lord`'s exercised servants,
who are rightly dipped into the present bewildered state of the church,
and see with the eye of their mind, that the beauty is fallen from Israel,
as on the high places.
Cannot some of us say at seasons, '`For these things I weep;
my eye runneth down with water.`'
Well, dear friend, let not this cause us to faint,
for it is a precious thing to be counted worthy to
suffer for so noble a cause as righteousness and truth;
let us put on strength,
and in the name of the Lord press through every crowd of
difficulty and discouragement which may arise in the way;
working in the power of his might,
to the pulling down of the strong holds of sin and Satan, not only in ourselves,
but in our fellow creatures; and establishing the kingdom of God and his righteousness;
that so an addition to the church militant may
be made by the faithfulness of the Lord`'s chosen,
by and through whom he is working wonders, in order that his love,
mercy and goodness may be magnified, in gathering sons from far,
and daughters from the ends of the earth,
that so a glorious addition may be made to the church triumphant.
The praise of his own works belongs alone unto Him,
who is worthy to receive honour and glory, thanksgiving and high renown; may my soul,
with thousands more, be put in a fit capacity to ascribe it for ever and for ever.

I have written in great freedom,
which I hope will be received in that love I feel for thee,
though I know it looks a little presuming for a child
in experience to write thus to a father in the church;
but as things arose, I simply penned them.

--

"`13th.--On awaking this morning my exercise awoke with me.
O may I be favoured to believe that I am not cast out
of the notice and care of my heavenly Father!
May I be corrected, proved, sifted and tried, and brought into order at last.
Cleanse me from secret faults, O Lord: thou knowest my heart;
I cannot hide any thing from thee.
If more abasement is necessary, may it be my portion.
After breakfast went to see my country-woman, Mary Swett,
and found she was going with Sarah Harrison to look at a ship in the Thames,
bound for Germany.
I went along with them,
and they expressed peace and satisfaction while sitting in the cabin.
Tears were my food, but I endeavoured to sympathize with them,
and in a feeble manner expressed it.
After dinner accompanied several Friends to the
examination of the scholars at Clerkenwell,
and at the close ventured to address them.`"

[.offset]
The following is an extract of a letter, dated seventh month 23rd, 1798,
addressed to his wife:

[.embedded-content-document.letter]
--

I am yet in London, and when I shall feel clear and easy to leave it,
and when I shall be favoured to leave this land and return to my native one,
is at present hid from me.
My mind has passed through much exercise and conflict since yearly meeting,
and I endeavour as much as in me lies, to possess my soul in patience.
How frequently have I thought of Richmond, in Virginia;
how oft it was my lot to encompass that city about as a mountain, and a great one too;
and yet, at the last I left it as light, comparatively speaking, as a cork,
and never unto this day have I had a painful sensation respecting it.
A mercy, yea an unspeakable one it will be,
should my soul be thus favoured respecting this place,
into which I came early in the fourth month last.
I had been at Brighton, on the sea coast,
and passed through singular exercises in that place;
but after having five or six public meetings among them,
was favoured to leave the place with sweet enriching peace.
I saw this line of labour along the sea coast, when I was in the north last summer,
and admired how much less was accepted,
than was opened and magnified in my view at that time on looking forward.

After leaving Brighton, I went with my beloved friend John Bevans,
to Hampshire quarterly meeting,
and again met the women Friends with whom we set out from London.

After getting through the quarterly meeting,
I could not see my way into any meetings belonging to that meeting:
I looked towards Plymouth, Falmouth, etc., but all closed up; so leaving our company,
my beloved and tender companion (for so I esteemed him) and I moved on towards London,
taking the quarterly meeting of Surrey by the way, in which I thought I was in my place;
and from thence came to London.
I felt sweet peace on returning, and willingly disposed to refit,
and leave it before yearly meeting, if it was the Lord`'s will, but could not.
I thought I was in my place during the time of holding that solemnity; but since,
I have been shut up again, and am labouring after patient resignation to the divine will.
I admire at the love and kindness of my dear friends Joseph and Rachel Smith,
who continue to be tenderly sympathizing, as also others.
Sarah Harrison, Mary Swett, Charity Cook, and George Stacey,
started a few days ago for Germany.
I saw no opening for me to go, though dear Sarah Harrison seemed to look for it,
almost to the last.
The ways of divine Providence are a great deep; too deep for a poor mortal to fathom,
and my soul craves that neither heights nor depths, nor any other creature,
may ever separate me from the mercy and love of God in Christ Jesus my Lord;
but that my soul may wade through all, and in the end be favoured to say,
'`Great and marvellous are thy works.
Lord, God Almighty, just and true are all thy ways, thou King of saints;
who shall not fear before thee, and glorify thy name.`'

--

"`24th.--In low moments I appear to myself as an idler; but am I indeed so,
when my feelings are so unutterable from day to day?
Will not my feeble efforts in this deep suffering,
be accounted as work done in the sight of the great Master?
O that it may be so,
and that I may be favoured to cease in due time from this labour and toil.
I crave daily strength to say, Thy will be done,
and for patience to endure this fight of affliction.
Attended Devonshire house meeting, and soon after I sat down,
on seeing an individual come in, this language impressed my mind,
and continued so with me, that at length I stood up with it,
and endeavoured to encourage a state which is under buffeting and trials:
'`Behold the man:`' dear George Dillwyn followed in the same line,
and after him William Savery.

"`25th, fourth-day.--In the forepart of the meeting today, my heart was humbled,
and I trust felt a little revival of hope,
that the Lord will carry me through all I have yet to meet
with in this land My heart is frequently melted within me,
and my cries with tears are poured out unto thee, O Lord.
Thou hast measurably favoured with a sense of thy forgiveness and mercy this morning,
even in the deeps.
William Savery closed the meeting in solemn prayer, in which I united with tears,
and perhaps I never felt greater love for him at
any time in my life than in this meeting.
I spent the evening with him, and took an affectionate farewell;
and this was the language of my soul when I left him; O Fountain of mercy,
open the way for me to labour--remove the clouds; and be with my dear fellow servant,
and safely waft him over the great deep to his family and friends in peace.

"`26th.--I walked to Ratcliff meeting alone, and towards the close was engaged in prayer.
O what a dispensation this is; how I mourn along the streets of London;
and am ready to cry out unto God.
After leaving dear William Savery last evening,
I felt how easy it would be for all-powerful Help to change my condition from weakness,
to strength and firmness.
The Lord has been my helper hitherto, surely he will not leave me in this distant land,
a poor, solitary man, as a desolate captive passing to and fro.
I hope at times, that a blessing will spring out of my trials,
if my faith and confidence fail not.
When I can believe that I am doing or suffering the Lord`'s will, it balances my soul,
and is enough for the moment,
I went to White Chapel burial ground to the burial of Captain;
a number of his little sailor boys and others were there, f felt the evening before,
an unusual impression on being invited to attend,
and was favoured to speak at the grave,--it was a time of tears,
and some of the lads wept aloud.

"`27th.--To children`'s meeting at Clerkenwell; it was small, but to my great admiration,
my heart was enlarged to speak to the visited minds under trial;
and afterwards appeared in supplication.

"`Eighth month 4th, seventh-day.--An humbling morning,
and yet I hope I see that a day of deliverance and enlargement will come,
if patience is abode in.
And must I indeed wait longer and be content thus to be shut up?
Yes, I can make nothing: the maker and builder of all things is God.
O then, the prayer of my soul is, that thou wouldest bless me indeed,
that thy good hand may condescend to be with me, and that thou wouldest enlarge my coast,
and keep me from evil, that it may not grieve my soul.
Cover thy servant with the mantle of love, and bring up out of the deeps;
forgive his iniquities, for thy name and mercy sake,
and qualify him to teach his fellow creatures thy ways.
O that I could once more be favoured, through thy heavenly power,
to convert and call sinners unto thee.
Thou hast done much for me,--favour me, O Lord, I pray thee, to love thee and thy cause,
yet much more.

"`5th, first-day.--Attended the meeting at Wandsworth,
where I had to deliver a close testimony.
I thought myself unworthy, and yet feared to omit the opportunity presented.
Amongst other things told them of a people who chant to the sound of the viol,
and invented for themselves instruments of music, but forgot the afflictions of Joseph.
I was afterward informed it was true,
and that there was not strength in the meeting to labour with such.

"`7th.--Took a lonely walk, in which I remembered how I was tried,
when in the utmost bounds of Georgia, in my native land.
There I was proved for a season, and then a notable work and service opened,
and through divine assistance was performed,
and I returned with a good share of sweet enriching peace.
I also remembered, that when in New England, my soul was proved and tried,
how I lamented my state in a lonely place in the woods,
and afterwards was made use of in reconciling a meeting,
and bringing them back into love and unity.

"`In the afternoon went to the girls`' school;
and soon after I sat down in the large room, where the children were at work,
they laid aside their work, and a comfortable silence ensued,
in which I felt my mind not only drawn forth in communication, but also in prayer,
and my own children were remembered,
and those of my fellow servants labouring in this land.
It was a very tendering time,
and I felt astonished that it should be so on looking at my poor, stripped state.

"`10th.--I sensibly felt my solitary condition this morning, and I said in my heart.
May I still be preserved patient this one day more: '`Cast thy burden on the Lord,
he shall sustain thee.`'
Lord, indulge thy servant with this favour.

"`11th.--Prayer with tears this morning.
And the king said unto Zadok, carry back the ark of God into the city:
if I shall find favour in the eyes of the Lord,
he will bring me again and show me both it and his habitation.
But if he say, I have no delight in thee, behold here am I,
let him do to me as seemeth good unto him.`'
O holy confidence in this afflicted servant,
even when he thought he was justly afflicted of his God,
thus to cast himself on the Lord: better to fall into the hands of the Lord,
than into the hands of men, for as is his majesty, so is his mercy.

"`When shall my feet be again shod with the preparation of the gospel,
and my commission be sealed to go forth.
I long at times that it may be so, but am checked and stopped by remembering,
that if I am happily doing and suffering according to the will of God,
I am doing what I should do; and with him, unto whom a thousand years are as one day,
my time spent in this manner may prove acceptable--so be it, saith my soul.

"`19th,
first-day.--Had an open opportunity at Tottenham meeting to plead with the rich and gay,
and also bent in prayer, and supplicated for the poor prisoners,
both such as were so in spirit, and those outwardly in bonds;
and also for the poor wandering emigrants,
who are driven from their homes and all they hold dear: felt comfortable after meeting.
I long to be set further at work; and stand resigned and willing in this respect.
In the afternoon meeting I felt an opening to encourage the burden bearers and mourners.

"`Ninth month 3rd, second-day.--Have a hope I am in my place,
having felt on rising an intimation to be still, and wait in patience.
The Lord grant it may be so, with a sufficient portion of faith to believe.

"`5th.--I attended the burial of B. Head,
whose body was brought from London to Tottenham meeting-house.
To my admiration I was favoured, out of weakness to be raised into strength,
and had an encouraging tendering opportunity.

"`7th, first-day.--I am so stripped this morning on arising and dressing,
that if I can say in truth, '`Lord have mercy;`'--'`Lord,
save or I perish;`' it is as far as I think I can go.
Went to meeting very poor;
but again through divine favour I was raised up in some degree of strength.
I could not be easy without inviting the people at
large to attend a meeting at five o`'clock this evening,
which was much filled up, and proved an open, solid time.

"`13th,
fifth-day.--Scattered a few tears this morning
in my chamber on taking a view of my state;
yet not without hope.
Elisha had hope when he confidently said to his master Elijah, '`as the Lord liveth,
and as thy soul liveth, I will not leave thee.`'
His master was a type of my Lord and master, Jesus Christ,
who ever liveth to make intercession for us; who though ascended up on high,
still regards the low estate of his servants:--have faith then, O my soul,
in his most Holy name, who can open a way where no way appears.

"`15th.--Received a letter from Mary Dudley; amongst other sweet sisterly expressions,
the following overcame me, and brought me into contrition: '`My mind,
according to its capacity, has felt for thee,
under sensations resembling deep uttering unto deep;
so that I cannot admit a doubt of its having been with
thy tribulated spirit a time of sorrow and distress;
out of which if thou art not yet brought, the Lord will assuredly deliver thee,
and put the new song into thy mouth; for he that has anointed is faithful,
and will open the two leaved gates, and cut in sunder the bars of iron.`'

"`16th, first-day.--To Winchmore hill with T. H., where came many gay folks.
I went in weakness and under a sense of great unworthiness,
and sat the forepart of the meeting much so;
but could not be easy without labouring with them from the
wise man`'s expressions concerning weights and measures,
settling with partners, putting all down in writing, etc.,
alluding to merchants who are very punctual in settling their accounts weekly,
and thus find it easy to balance them at the years`' end;
which drew me to speak of settling our accounts with the Almighty, day by day,
that so a heavy account might not remain against us in a time of sickness and death.
I told them I believed no one there had come to that meeting in a sense of greater
weakness and unworthiness than myself.--Upon returning I feel more light and easy.
How pleasant to feel thus, even for a moment.

"`19th.--My soul seems let down into sympathy with the
wretched among men--O poor tried and tempted man,
thou hast an advocate with the Father, who was also tempted and tried,
even Jesus Christ the righteous.

"`22nd.--A news-paper was brought to me,
containing information that the yellow fever had broken out in Philadelphia,
and that the inhabitants were very generally leaving the city.
I am thankful that my mind was favoured with such quiet this morning.

"`23rd, first-day.--This morning I looked home and said, Lord,
I desire to submit all to thy disposal, who knowest best what is best for us;
and was willing to offer up a prayer and tear for the inhabitants of Philadelphia;
and thought also of the poor sailors wounded and mangled in the war in the Mediterranean.
Lord, thy power, thy mercy, spread over sea and land.
I was favoured with a pretty full and open time at Tottenham meeting.
The afternoon meeting was put off to six o`'clock, and the neighbours invited;
it was a large, and I trust a solid meeting,
and I felt relieved and comfortable after it.

"`24th.--Attended the select quarterly meeting of London, which was small,
many members being abroad at watering places.
I had a pretty relieving opportunity after the queries were gone through,
and in the close was engaged in prayer.

"`25th.--Attended the quarterly meeting, and laboured in the first meeting;
that for business was an exercising time,
but at length a committee was appointed to sit with Friends of Tottenham,
and try to help them over the difficulties respecting tithes and the payers of them.

"`26th.--A more wakeful night than usual, and in those wakeful moments,
it seemed as though I had to go through yesterday`'s meeting again.
O how distressing is the state of these Tobiahs and Sanballats, who oppose the work,
and yet are willing to be thought in their places.

"`Tenth month 4th, fifth-day.--Went this morning to Westminster meeting, which was small,
but to me a quiet sweet time, wherein my heart was a little enlarged and lifted up,
and endeavoured to encourage others to trust in the Lord.
Mary Watson closed the meeting, I thought weightily, in solemn prayer.

"`10th.--Although no opening presents to move away from London and its neighbourhood,
yet I feel a comfortable degree of calmness and resignation.
I am going into the city to look out a little, resembling, I think,
the prophet`'s servant,
who was bid to go again and again to look for the arising of the cloud,
which after a time appeared the bigness of a man`'s hand.
Is there not a cloud gathering?
I beg for support and sustaining help a little longer.
Attended Grace-church street meeting, where dear Mary Watson was much favoured.
She seemed to have the same weapon put into her hand which I was formerly favoured with:
my spirit united while she plead with some who had known better days.`"
