== Chapter XIII

[.chapter-subtitle--blurb]
Testimony of the monthly meeting of Philadelphia, for the Northern District,
concerning Thomas Scattergood.

From the love we feel for the memory of this our dear friend,
and the continued sense we have of his fervent pious engagements,
it appears to be a duty to posterity to transmit
some account of his life and conversation.

He was born in the city of Burlington, New Jersey,
of parents professing belief in the doctrines and
principles held by us as a religious Society:
his father dying whilst he was young, he was placed an apprentice in this city;
and though often sensible of the checks of divine grace, which condemns for sin,
he followed the inclination of his own corrupt will,
which led into estrangement from the path of peace;
till being in mercy visited with an humbling sense of his miserable condition,
he turned at the reproofs of instruction,
and submitting to the gentle manifestations of light upon his understanding,
was enabled to bear the cross of Christ,
and became qualified to extend advice and counsel to others.
Under those exercises, a sense of a call to the ministry of the gospel was,
in the wisdom and love of God, communicated to his mind;
but through great reluctance to yield to this awful work, he forbore for several years,
and thereby brought upon himself very deep distressing conflicts.
At length, whilst accompanying a Friend who had been here on a religious visit,
the impression of divine requiring being renewed upon him,
his mouth was opened with a few words in a religious meeting; and after his return,
he expressed at times in our religious assemblies,
a few sentences in a tender broken manner, much to the satisfaction of his friends;
and continuing steadfast under many baptisms and trials,
he was remarkably careful that no part of his conduct might lessen
the force of the doctrine which he had to preach to others.
Keeping faithful to the intimations of duty,
he became prepared for more extensive service;
and with the concurrence of the monthly meeting,
proceeded to fulfil a prospect he had of a religious visit to
the meetings of Friends within the government of New York,
and part of New England, and was favoured to return with the reward of peace.
Thus diligently labouring in the work of the ministry,
he was for many years much from home, visiting meetings in various places,
particularly in Maryland, Virginia, and Carolina;
where he experienced much close exercise and proving of faith and patience;
but through the goodness and power of the blessed Shepherd of Israel,
whose help is ever near for the support of his humble dedicated servants,
he was carried through all, to the comfort of his own mind,
and the satisfaction of his friends.

The prospect of making a visit to the churches in Europe being opened upon his mind,
and meekly abiding under the weight of this exercise
until it was ripe for the information of his friends,
he was induced to spread it before them; and obtaining their unity and sympathy,
he embarked, and arrived in England in the year 1794.
Much deep and silent exercise was often his lot,
but as resignation and patience were maintained,
he was enabled to discharge what appeared to be his duty;
and labouring for several years in the fulfilment of this arduous service,
he experienced the near unity and fellowship of Friends in those countries,
and came away in the enjoyment of peace,
under a sense of the immediate protecting providence of Him,
who is to his children a sure rock and never-failing refuge.
He continued mostly at home for several years,
diligently attending the respective meetings of which he was a member,
and also other religious services.

He was much devoted to the promotion of the cause of truth and righteousness,
and through the efficacy of heavenly love, was at times enabled to say,
it was more to him than his necessary food;
but being sensible of his various infirmities, he was frequent in inward retirement,
and hence his mind became strengthened in watchfulness against those things which
interrupt the aspiration of the soul towards the Fountain of everlasting life;
being thereby made quick in the fear of the Lord, he increased in solid experience,
and gradually advanced in the way and work of salvation.
His example in silent waiting in our religious meetings was instructive,
and in the exercise of his gift,
it was evident that he had been careful to feel the putting forth of the divine hand,
being at times eminently endued with a clear
discernment of the states of meetings and individuals,
and in the power of the gospel,
was made instrumental to baptize many into deep contrition,
through a heartfelt sense of their own condition.
Thus, as a scribe well instructed into the kingdom,
he brought forth out of the treasury things new and old,
to the edification of the body and to the praise of its ever adorable head.

His sympathy with the afflicted was often manifest;
and the situation of those in necessitous circumstances
peculiarly claiming his tender regard,
occasioned his frequently bringing to the notice of his brethren,
their suffering condition,
that their benevolent endeavours might be exerted for their alleviation.

He was so tender of the reputation of all,
that he could not take the liberty of expressing any thing to lessen it,
nor was he easy to hear others in such a practice.

He attended several sittings of our yearly meeting in the fourth month, 1814,
and was taken unwell the 21st. The disorder though
apparently not alarming at the commencement,
in a short time greatly prostrated his strength:
yet he was preserved throughout in much quietness and sweetness of spirit;
was frequently pleasant and cheerful;
his concern for the prosperity of Zion was still the prevalent engagement of his mind,
and he often enquired how the yearly meeting was advancing in its important business.

On the third day of his illness,
a friend sitting by him expressed he felt a peaceful solemnity--he replied, "`So do I;
my mind is centered in quiet, peaceful resignation.`"
On the next day those about him apprehended he was near departing, but reviving a little,
he at intervals expressed nearly as follows;
"`This is the last piece of the garment that is to be worked up;
and if I can be favoured to join the righteous of every generation, it will be enough.`"
Again--"`Well, I don`'t know that I have much to say for myself; I leave it to the Lord,
the Shepherd that sleepeth not by day nor slumbereth by night,
who watcheth over his children and over his flock:`" Again:
"`I hope that a righteous generation will be raised up
and preserved as a seed`"--and after a silent pause,
added, "`Oh,
if we can but be favoured to take some of that love
with us--the end crowns all--I have nothing to boast of;
I have been baptized into many low places, and raised up again.`"
He appeared disposed for more expression,
but his bodily powers were so far gone as to render his attempts unintelligible;
yet after a considerable time of silence, he uttered with much emphasis,
"`I will lead them.`"
Soon after which he quietly and peacefully departed, the 24th of the fourth month, 1814;
and we doubt not hath entered into rest,
enjoying that crown of righteousness which the Lord, the righteous Judge,
will give unto all them that love his appearing.
